- helix-term/src/ui/popup.rs
when the available height for the popup is low/small, then it is not possible to scroll until the end
[this recording shows the problem](https://github.com/helix-editor/helix/assets/2721423/1ff9c7d1-795f-4d26-ad24-96af1a0470dc) (created by @thomasaarholt)
> Fix scrolling to the end within a popup

- runtime/themes/adwaita-dark.toml
Issue from: https://www.reddit.com/r/HelixEditor/comments/1bxxri4/helix_themes_and_vertical_or_column_rulers_dont/
> feat(themes): add ruler for `adwaita-dark`

- runtime/themes/solarized_dark.toml
Issue from: https://www.reddit.com/r/HelixEditor/comments/1bxxri4/comment/kyfu9je/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
Before:
After:
> refactor(themes): removed `ui.highlight` effects from `solarized_dark`

- runtime/themes/material_deep_ocean.toml
the fg color was not really readable, and changing the accent to blue because I feel it's also an improvement to the colorscheme:
before
after
> material theme: fix statusline color

- book/src/languages.md
- helix-term/src/commands/lsp.rs
- helix-term/src/handlers/completion.rs
- helix-term/src/ui/completion.rs
Hi!
It's small changes to render completions/actions from lsp by they definition order on languages.toml
> Respect lsp definition order for code actions

- helix-core/src/object.rs
- helix-core/src/selection.rs
- helix-core/src/syntax/tree_cursor.rs
- helix-term/src/commands.rs
- helix-term/src/keymap/default.rs
- helix-term/tests/test/commands/movement.rs
This adds two new related commands:
Selects all siblings of the node under the cursor.
[![asciicast](https://asciinema.org/a/yt7SserYwGL7QJ3UGVAmhe60t.svg)](https://asciinema.org/a/yt7SserYwGL7QJ3UGVAmhe60t)
Selects all children of the node under the cursor.
[![asciicast](https://asciinema.org/a/GiMx8a5uZMtbyXI0Zh8Z6CoDh.svg)](https://asciinema.org/a/GiMx8a5uZMtbyXI0Zh8Z6CoDh)
~~Selects all children of the node under the cursor, but only if the children are contained inside the starting selection.~~
Edit: saving this one for a future PR
> feat(command): select all siblings and children

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/solidity/highlights.scm
- runtime/queries/solidity/textobjects.scm
This PR adds textobject queries for the solidity language. In order to enable some of the queries, some upstream work has been done on the tree-sitter grammar.
This PR updates the grammar version and fixes a few highlight queries, as well as adds new queries for textobjects.
Fixes:
- spelling mistake in `event_parameter`
- precedence of `@variable` vs other identifiers
Additions:
- Textobject queries
- Type alias highlight query
- `abstract` keyword
- Variable builtins for `this`, `msg`, `block`and `tx` identifiers
> feat(solidity): add textobject queries for solidity

- runtime/themes/nord.toml
When "nord2" color is used in ui.selection it is almost invisible if cursorline highlighting is enabled. Changing the color to "nord3" fixes the issue.
"nord2":
"nord3":
> Brighten nord selection highlight

- helix-term/src/ui/editor.rs
closes #10315
this code was copy pased from elsewhere but overlay highlights use char indecies not byte indecies. One day we will use  byte indecies everywhere and avoid these mixups
> fix char/byte index mixup in overlay rendering

- helix-core/src/graphemes.rs
- helix-stdx/src/rope.rs
- helix-term/src/ui/document.rs
- helix-term/src/ui/editor.rs
Closes #6645
I have known the root cause of #6645 for a while: The c grammar has a bug where it sometimes creates non-grapheme aligned highlight spans when cealing with unicode characters like emojois.
This caused crashes because our grapheme alignment code couldn't deal with non-char aligned offsets. I think that is the right (potentially only valid) choice for doing grapheme alignment. 
In our case it was unfortunate as it leads to crashes. I also wanted to get rid of this grapheme alignment anyway because we already render the text one grapheme at a time, so it's really unnecessary to do this. However, in the past it wasn't possible to remove the alignment because the additional highlight iterators merged on top of the base iterator were using char indexing/grapheme aligned indexes. …
> don't manually grapheme align ts highlights

- runtime/themes/monokai.toml
Matching comment styling so that it doesn't get confused for actual code.
> themes/monokai: add inlay-hint style

- helix-term/tests/test/commands/write.rs
- helix-term/tests/test/helpers.rs
- helix-view/src/document.rs
> Read symlink when writing files

- languages.toml
- runtime/queries/ld/highlights.scm
This pull request updates tree-sitter-ld. (I found a bug with the use of names in expressions, and have fixed it in https://github.com/mtoohey31/tree-sitter-ld/commit/0e9695ae0ede47b8744a8e2ad44d4d40c5d4e4c9.)
> Update tree-sitter-ld and highlights

- languages.toml
Since Odin is LLVM based I adapted the Zig configuration for debugging locally, been using this for a bit and thought it would be a good idea to add this to the project
> Add lldb-dap debugger support for Odin

- runtime/themes/vim_dark_high_contrast.toml
In the "vim dark high contrast" theme, I have set the bufferline and cursorline colors, so it does the following:
1. the currently active buffer is easily recognizable (just like in the other themes)
2. the current line has a slightly lighter color than the bg
Without fix:
With fix:
> Add bufferline and cursorline colors to vim dark theme

- helix-core/src/syntax.rs
- languages.toml
- runtime/queries/rust/highlights.scm
Updates tree-sitter-rust to v0.21.0. There were a number of changes since 0.20.3 ([diff](https://github.com/tree-sitter/tree-sitter-rust/compare/v0.20.3...v0.21.0)). The only breaking change  ([commit](https://github.com/tree-sitter/tree-sitter-rust/commit/99c6922d407ca9c3c1a3b7c10ac480985c3e9d47)) that I found was renaming `loop_label` node to `label`, which is addressed in the `highlights.scm` file. I haven't experienced any regressions, but it would be great if other people could try it out too before merging.
> chore: update tree-sitter-rust to v0.21.0

- Cargo.lock
- helix-vcs/Cargo.toml
This update contains a security fix for
https://rustsec.org/advisories/RUSTSEC-2024-0335.html
> Update gix to version 0.62

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/xtc/highlights.scm
Add syntax highlighting for .xtc/.xoa/.xpc files.
This merge request build upon my tree sitter, tree-sitter-xtc,
visible here: https://github.com/Alexis-Lapierre/tree-sitter-xtc.
* XTC stand for Xena Traffic Configuration
* XOA stand for Xena OpenAutomation
* XPC stand for Xena Port Configuration
You can read about the scripting language here:
https://docs.xenanetworks.com/projects/xoa-cli/en/latest/index.html
> Add support for Xena OpenAutomation files

- helix-term/src/commands.rs
- helix-term/src/commands/typed.rs
- languages.toml
This aims to address https://github.com/helix-editor/helix/issues/10400 and allows prefixing `gn` and `gp` commands with a number to cycle through multiple buffers.
Feedback is always welcome.
This is my first attempt at contributing to something, so go easy on me 😅
> Enabled traversing multiple buffers at once

- languages.toml
`hyprpaper.conf`, `hyprlock.conf` and `hypridle.conf` were incorrectly identified as hocon
This supports them for the hyprland configuration language
> Add missing hyprlang support

- helix-term/src/handlers/signature_help.rs
- helix-term/src/ui/lsp.rs
implement handle_event to cycle through the function signatures.
by pressin alt + p/n the function signature will be changed. (similar behavior as the completion popup)
fixes #5403
edit:
key bindings are changed to alt + p/n.
[![asciicast](https://asciinema.org/a/coDBxc6PGrsAjp73zS9khdML0.svg)](https://asciinema.org/a/coDBxc6PGrsAjp73zS9khdML0)
> feat: cycle through function signatures/overloads

- languages.toml
The former is one of the more popular forks of the original idea:
https://rust-script.org/
The latter is an RFC for folding that functionality into cargo itself, available on nightly:
https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#script
> languages/rust: add `rust-script` and `cargo` shebangs

- runtime/queries/svelte/highlights.scm
Fix for syntax highlighting in svelte, its currently not working correctly for certain tags.
Im not familiar with scheme but it seems (tag_name) and a few others were being used before having the correct highlight applied so moving them to the top of the file seems to fix the issue.
Before:
After:
> Fix: Svelte queries

- book/src/generated/typable-cmd.md
- helix-term/src/commands/typed.rs
- helix-term/tests/test/commands.rs
Resurrects https://github.com/helix-editor/helix/pull/3966/. This is 100% @idursun's work. Using `read_to_string` from https://github.com/helix-editor/helix/pull/7431.
closes https://github.com/helix-editor/helix/issues/3796
> Implement read command

- runtime/themes/kanagawa.toml
The recent change to increase the contrast of the primary selection background (https://github.com/helix-editor/helix/pull/10094) was a good idea - previously the contrast was way too low and I'd often be sat squinting at my monitor.
Unfortunately the new ui.selection.primary colour happens to match exactly the colour used by the cursorline. On top of this, the colour `sumiInk5` is just a duplicate of `sumiInk3`.
This pull request chooses another contrastic colour (specifically `waveBlue2`) that doesn't clash with the cursorline and removes the `sumiInk5` variant:
Previously:
(Highlighted line is completely invisible because of the cursorline)
Now:
Paging @mxpv and @zetashift for visibility
> Fix kanagawa theme when using cursorline

- book/src/lang-support.md
The prior URL invites you to create a new wiki page. I think https://github.com/helix-editor/helix/wiki/Language-Server-Configurations is the correct place to point to now.
There might be more issues related to changes in wiki structure that are not caught by some CI link check because of this (it's a valid URL, just not what you want to direct to lol)
> Update lang-support.md for new wiki page name

- runtime/themes/everblush.toml
changes the statusline colors for SELECT mode in the Everblush theme.
the previous colours seem to be incorrect and quite ugly (sorry!).
I chose the magenta over the cyan (colours that were already present) as it has more contrast with the existing INSERT colour.
the statusline colours are now inline with eachother, all having the background be the 'background' colour, with varying foregrounds.
images below for before and after:
normal:
insert:
before - select:
after - select:
> theme: everblush -  statusline colours

- runtime/themes/gruvbox.toml
The current choice for `orange1` came from the `CoC` setting in the [gruvbox](https://github.com/morhetz/gruvbox) repo, however, both the `ALE` and `Syntastic` settings use `yellow`. Going by majority rule, and a stated improvement by someone who uses a version of the theme, this changes the color to `yellow1` from `orange1`.
In hopes for as small a footprint as possible, and to propagate changes to maintain consistency between `gruvbox` variations, I changed the base `gruvbox` from which the others inherit. The original issue #10455 only brought up`gruvbox_light`, but having checked  checked the rest with the change, I decided it looked good to me.
`gruvbox`:
`gruvbox_dark_hard`:
`gruvbox_dark_soft`:
`gruvbox_light`:
`gruvbox_light_hard`:
`gruvbox_light_soft`
Closes: #10455
> refactor(themes): `gruvbox` warnings to `yellow1`

- helix-tui/src/backend/crossterm.rs
This option allows overriding the NO_COLOR environment variable, which crossterm honors by default.
As noted in https://no-color.org/, "User-level configuration files and per-instance command-line arguments should override $NO_COLOR".
> Disable crossterm's support for NO_COLOR.

- helix-term/src/commands.rs
Currently the editor mode has no effect on the behavior of `search` and `rsearch`. We can pass in the right movement for the editor mode to make the behavior or `search` and `rsearch` match `search_next` and `search_prev` in select mode.
See https://github.com/helix-editor/helix/issues/5672#issuecomment-2064161299
> Respect mode when starting a search

- helix-term/src/ui/completion.rs
- helix-term/src/ui/editor.rs
- helix-term/src/ui/mod.rs
- helix-term/src/ui/popup.rs
Make the popup positions more consistent.
Improvements:
1. if the signature popup content is bigger than the available space, then the popup is always shown under the cursor, even if there more space above the cursor than below. [check this video](https://asciinema.org/a/JNF85TAwa2bsZJWOHW70dstJU) 
2. There is no mutation anymore inside required_size. Maybe in the future we can update all widgets to have no mutations and change the trait
the following is the new behavior
[![asciicast](https://asciinema.org/a/44ZvwHoJX7UGZiPfLpnZR8asY.svg)](https://asciinema.org/a/44ZvwHoJX7UGZiPfLpnZR8asY)
IMO this make at least the completion dialog consistent and will be shown always bellow the cursor.
Edit: Video Updated
> Improve popup position

- languages.toml
- runtime/queries/bash/highlights.scm
This PR addresses #3151 
I have set the rev for the bash grammar to the latest commit hash on master for [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash), and have updated the runtime/queries/bash/highlights.scm to the latest for the updated grammar as well.
> feat: update bash grammar to latest tree-sitter-bash rev

- helix-core/src/indent.rs
I originally thought that it might be necessary to look at the syntax tree to decide whether a node is the first node on its line. Since then, I haven't really seen any example where this is the case, so we can replace my initial implementation with a simpler one that just checks if all preceeding characters on the same line are whitespace.
This fixes #10336 and should generally prevent issues with tree-sitter grammars that insert nodes for whitespace.
> Simplify first-in-line computation for indent queries

- helix-term/src/lib.rs
Ignores `.svn`. This makes hx more usable with svn VC. Fixes #2406
> Ignore .svn version control files

- runtime/themes/modus_operandi.toml
- runtime/themes/modus_vivendi.toml
Add styling for jump-labels for modus themes. I couldn't find any official approach here so picking `yellow-cooler`. `cooler` is used for other meta highlights by modus and yellow seems to be used the least - only warnings, so there's little chance of colliding with other highlights.
> feat(themes): jump-label for modus themes

- helix-core/src/object.rs
- helix-term/tests/test/commands/movement.rs
- helix-term/tests/test/movement.rs
Use `Direction::Forward` for `select_next_sibling` and `Direction::Backward` for `select_prev_sibling` instead of inheriting the direction from the original selection / range.
Reference - https://github.com/helix-editor/helix/issues/4612#issuecomment-2068028963
> specify direction for select_prev_sibling and select_next_sibling

- helix-core/src/match_brackets.rs
- helix-core/src/selection.rs
- helix-core/src/surround.rs
- helix-core/src/textobject.rs
- helix-term/src/commands.rs
- helix-term/tests/test/commands.rs
- helix-term/tests/test/movement.rs
Closes #8325 
closes  #3615
closes #3432
closes #4475
closes #7012
Finding the closest surround pairs (`mim`, `mam`) was done without being aware of the syntax. This PR adds a tree-sitter implementation that may be faster (untested), but most important it's more correct.
If the syntax distinct strings than `mim` and `mam` will work inside strings (didn't work with plaintext impl), matching should also work inside injections.
<details>
<summary>OLD</summary>
`find_nth_closest_pairs_pos` produces unsorted tuple. The tuple must be sorted before passing it to the change Transaction. Otherwise, this statement will fail:
https://github.com/helix-editor/helix/blob/13d4463e4146473391e37b7f75e99b731aa55878/helix-core/src/transaction.rs#L582-L585
MRE: 
1. `hx`
2. repeat exact keys (two spaces after …
> feat: find closest pairs using tree-sitter

- runtime/themes/dark_plus.toml
Original from VS Code online:
New highlights for Helix:
I grabbed the colors using Firefox dev tools, and tested this method was an accurate way of doing it with some other colors, they all matched what was already in the Helix theme. I don't see these debug colors used anywhere else, so I have not given them color names for reuse.
> Add debug highlights to the dark plus theme

- languages.toml
By default Metals does not enable inlay hints, enabling support means that whether they are displayed is then in control of the editor.
> Enable metals inlay hints

- book/src/themes.md
- runtime/queries/ecma/highlights.scm
It's bugged me that private members haven't been highlighted in editor I've used so far, so I've added the queries to allow actually restyling. Currently, they're targeted as a `.private` child under `variable.other.member` and `function.method` so that they automatically take on the existing highlighting properly while being individually style-able. This was a personal preference, since it would match other langs which don't colour public & private methods/field differently while allowing the unique syntax of JS to be taken advantage of, however there's 2 other options that could also work:
- Remove all the `.private` parts and match other langs exactly
- Rename to not be a child and instead standalone (eg `variable.other.private-member`) to preserve the current lack of styling
Example …
> Fixed ECMAScript private member highlighting

- helix-lsp/src/lib.rs
closes #10610 
this was a minor regression from #10539 
the main problem was a mix-up where the new client was removed from the registry instead of the old one (accidentally used `cliend.id()` instead of `old_cient.id()`) but I also noticed that we don't actually stop an old lsp if the new one fails to start and similarly don't restart a server if it failed to start/was stopped in the past which doesn't seem correct, so I fixed that too.
> fix lsp restart

- helix-term/src/commands/dap.rs
- helix-term/src/commands/lsp.rs
- helix-term/src/ui/completion.rs
- helix-term/src/ui/lsp.rs
- helix-term/src/ui/menu.rs
- helix-term/src/ui/popup.rs
fixes #10569
this fixes regression introduced by #10257 both regarding general crashes and bugs when popup borders are used (#10566/https://github.com/helix-editor/helix/issues/10553). While working on this I noticed there were actually existing bugs where the border size wasn't quite taken into account while scrolling which I also fixed. Since borders now need to be accounted for in the popup I made the border config and entirely internal config so its moore self contained.
Also incorporated the fixes from #10507 with some slight adjustments.
Marked for the next release since this fixes newly introduced crashes that are fairly easy to trigger
> Fix bugs in popup

- helix-view/src/tree.rs
Not really sure it's a proper fix but with the patch original testcase could not be reproduced.
resolves #9877
> fix: avoid child area overflow on split

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/pest/highlights.scm
- runtime/queries/pest/indents.scm
- runtime/queries/pest/injections.scm
- runtime/queries/pest/textobjects.scm
Add  [pest-parser](https://github.com/pest-parser) Support.
- [pest-language-server](https://github.com/pest-parser/pest-ide-tools)
- [tree-sitter-pest](https://github.com/pest-parser/tree-sitter-pest)
close #7878
> language: Add pest support

- runtime/queries/typst/injections.scm
Previously, comments in Typst files would not get any comment highlighting. This PR adds the injection query for comments in the Typst language.
An example of a Typst file after this change:
> Add comment injection to typst queries

- runtime/queries/rust/highlights.scm
`try` keyword can be used in nightly rustc after 2018 edition.
```rust
#![feature(try_blocks)]
fn main() {
let res: Option<i32> = try {
let a = Some(1)?;
a
};
println!("{res:?}");
}
```
> add `try` keyword to rust highlights

- book/src/keymap.md
PR #9974 added alt-p/alt-n keybindings to scroll through signatures. This wasn't very discoverable, as it's not in the docs or the command palette.
This also removes a broken link for "comment mode" in the table of contents.
> Add completion/signature bindings to keymap.md

- helix-term/src/handlers/signature_help.rs
- helix-term/src/ui/lsp.rs
some LSPs does update the active signature and some not. To make both worlds happy, make the active signature more intelligent.
1. SignatureHelp store now the suggested lsp_signature
2. if the lsp_signature changes then use it
3. otherwise use the last signature from the old popup
4. in case the old signature doesn't exist anymore, show the last signature
> signature: use the suggested LSP signature when changed

- runtime/queries/python/highlights.scm
Fixes #10585. It appears if statements only support a single keyword operator between operands. To fix this, I added `is not` and `not in` as separate keywords.
> Add `is not` and `not in` to python syntax

- book/src/guides/adding_languages.md
Previously, the link would point to the now moved "How to install the default language servers" page. The link now directly points to the up-to-date page.
> Update wiki link to language server configs in adding languages guide

- book/src/install.md
Hi!
I installed my helix by pre-build binary following [the book](https://docs.helix-editor.com/install.html#pre-built-binaries), and the highlight didn't work.
I found [the issue #1098](https://github.com/helix-editor/helix/issues/1098#issuecomment-968564508) with the problem and the solution, and moving the runtime to the correct location the syntax highlight started to work.
These issues update the installation of the pre-build binary docs to add the `runtime` folder information, so people who follow the instructions will have the syntax highlighting working on the first time.
The book explains how to setup the runtime folder [on the building by the source section](https://docs.helix-editor.com/install.html#multiple-runtime-directories), but I didn't find it on the first time because …
> docs[install/pre-build binaries]: add runtime setup

- runtime/queries/json/highlights.scm
- runtime/queries/json5/highlights.scm
This PR makes `json` and `json5` highlighting more consistent with `yaml` and `toml` by using `@variable.other.member` for member keys. Aside from being consistent with yaml and toml, this key simply makes sense in this context so it should be more consistent across all languages.
> lang(json): make field key highlighting consistent with toml and yaml

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/_gjs/highlights.scm
- runtime/queries/_gjs/injections.scm
- runtime/queries/gjs/highlights.scm
- runtime/queries/gjs/indents.scm
- runtime/queries/gjs/injections.scm
- runtime/queries/gjs/locals.scm
- runtime/queries/gjs/tags.scm
- runtime/queries/gjs/textobjects.scm
- runtime/queries/gts/highlights.scm
- runtime/queries/gts/indents.scm
- runtime/queries/gts/injections.scm
- runtime/queries/gts/locals.scm
- runtime/queries/gts/tags.scm
- runtime/queries/gts/textobjects.scm
Add support for glimmer-js and glimmer-ts
=
(error due to using linguist sample and missing imports)
> feat: add support for gjs and gts

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/inko/highlights.scm
- runtime/queries/inko/indents.scm
- runtime/queries/inko/injections.scm
- runtime/queries/inko/locals.scm
- runtime/queries/inko/textobjects.scm
This adds formatting and Tree-sitter support for Inko (https://inko-lang.org/), using the grammar located [here](https://github.com/inko-lang/tree-sitter-inko/).
> Add support for Inko

- default.nix
Currently, the `default.nix` for Helix only exposes a single package which is always built for `builtins.currentSystem`, the system where the Nix code is being evaluated. If you aren't using flakes, there's not an easy way to build Helix for a different system.
This change instead does what most other users of `flake-compat` do in `default.nix`: expose all of the flake's outputs. This allows consumers to use the package for a specific system if they need to by doing something like `(import helix).packages.${system}.helix`. And the current behavior is still accessible by doing `(import helix).default` instead of `import helix` as you currently can.
> Expose all flake outputs through flake-compat

- helix-term/src/ui/statusline.rs
This reverts commit bcf7b26393cd2a32e38c187f69b602be018798f4, which has caused a lot of unexpected regressions and requires further discussion.
> Revert "Refactor statusline elements to build `Spans` (#9122)"

- languages.toml
In addition to BUILD files, bazel repositories contain a WORKSPACE file,
which is also written in starlark.
See https://bazel.build/reference/be/workspace.
> lang(starlark): Add WORKSPACE glob.

- helix-core/src/match_brackets.rs
- helix-term/tests/test/commands/movement.rs
This PR fixes a couple of edgecases that were noticed in the match bracket implementation after the recent changes to match_bracket.
This should cover both the markdown cases discovered by @David-Else (although I think there are still some cases involving injections that may not be covered but all the examples discussed work now) and the python cases discoreved by @ thomasaarholt. I also included fixes for some issues for cases where in cases where multiple nested pairs are siblings. I think this probably shouldn't happen usually, but it can happen in case there are syntax error so it's nice to be a bit more robust
> improve match bracket matching

- helix-term/Cargo.toml
- helix-view/Cargo.toml
- helix-view/src/clipboard.rs
- helix-view/src/editor.rs
While building Helix today the new lints from 
https://blog.rust-lang.org/2024/05/06/check-cfg.html
Fired for the helix-view crate. Specifically there were two things spelled incorrectly:
1. It used the unicode-lines feature, but the feature was not declared in its manifest. 
2. It used the `target_os` cfg key for wasm32 rather than `target_arch`.
I don't know enough about either of these to write tests for them. It doesn't even look to me like wasm32 is tested in ci anyways, and the `unicode-lines` feature is not enabled in CI either.
```
warning: unexpected `cfg` condition value: `wasm32`
--> helix-view\src\clipboard.rs:93:7
|
93 | #[cfg(target_os = "wasm32")]
|       ^^^^^^^^^^^^^^^^^^^^
|
= note: expected values for `target_os` are: `aix`, `android`, `cuda`, `dragonfly`, `emscripten`, …
```
> FIx incorrectly spelled cfg options

- runtime/themes/dark_high_contrast.toml
I'd been using this theme quite a while because it looks the nicest to my dyslexia. That said, when I open up XML or HTML documents, they pretty much always show up in complete white, except for attribute values.
Finally decided to take a look at why, and added the two colors (`tag` & `attribute`) needed to make the theme actually usable with the two formats.
> Added missing colors to dark_high_contrast theme for XML/HTML highlighting

- helix-core/src/indent.rs
- helix-core/src/syntax.rs
- helix-core/src/transaction.rs
- helix-core/tests/indent.rs
- helix-lsp/src/file_event.rs
- helix-lsp/src/lib.rs
- helix-term/src/application.rs
- helix-term/src/handlers/completion/resolve.rs
- helix-term/src/handlers/signature_help.rs
- helix-vcs/src/git.rs
- helix-view/src/register.rs
- helix-view/src/tree.rs
- rust-toolchain.toml
The changes are basically all cosmetic: 1.74 has a few new clippy lints to address (mostly using `or_default`/`unwrap_or_default` rather than explicit defaults), and the formatter now formats let-else.
Connects https://github.com/helix-editor/helix/pull/10704
> Raise MSRV to 1.74

- book/src/keymap.md
I just used the `=` binding to format a selection in a CSS file in helix 23.10 (5931a46c) so removing this comment as outdated.
> Remove outdated comment about key binding being disabled

- book/src/package-managers.md
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: https://github.com/NixOS/foundation/issues/113
> docs: update nixos link to official wiki

- helix-view/src/document.rs
fsync(2) is a somewhat expensive operation that flushes writes to the underlying disk/SSD. It's typically used by databases to ensure that writes survive very hard failure scenarios like your cat kicking the plug out of the wall. Synchronizing isn't automatically done by `flush`ing (from the `std::io::Write` or `tokio::io::AsyncWriteExt` traits). From the [`tokio::fs::File`] moduledocs:
> To ensure that a file is closed immediately when it is dropped, you should call `flush` before dropping it. Note that this does not ensure that the file has been fully written to disk; the operating system might keep the changes around in an in-memory buffer. See the `sync_all` method for telling the OS to write the data to disk.
This seems like a likely fix for …
> Synchronize files after writing

- runtime/queries/julia/highlights.scm
This fixes the `#match?` queries lacking a `#` in front in Julia queries.
See https://github.com/helix-editor/helix/pull/10031#issuecomment-2119137712
> Fix `#match?` predicates in julia queries

- helix-core/src/selection.rs
- helix-term/src/commands/typed.rs
- helix-vcs/src/diff.rs
This is useful for resetting multiple changes at once. For example you might use `maf` or even `%` to select a larger region and reset all changes within.
The original behavior of resetting the change on the current line is retained when the primary selection is 1-width since we look for chunks in the line range of ~the primary~ each selection.
> Reset all changes overlapped by selections in `:reset-diff-change`

- helix-stdx/src/env.rs
get_current_directory alnways returns a cannonicalized path (since cwd is just a file descriptor that is passed to realpath). That means that opening any file inside a symlinked directory would show that file as an absolute path outised the cwd instead of as an relative path (since we don't cannonicalize/resolve symlinks normally). To fix that I made helix mirror the behavior of `pwd -L`. We use PWD environment variable set by the shell which has a "memory" of which symlinks were transversed with `cd`.
> correctly handle opening helix inside symlinked directory

- helix-term/tests/test/commands/write.rs
- helix-view/src/document.rs
Resolves https://github.com/helix-editor/helix/issues/10732
> Handle relative symlinks on write

- helix-tui/src/backend/crossterm.rs
Inspired @pascalkuthe's comment on my previous PR to revert the use of cnorm for resetting the cursor, I've tried writing an approach that checks the $TERM_PROGRAM or $TERM to decide whether to use cnorm or `\x1B[0 q`.
Please note, this is my first time writing rust, so please be picky about what I've done wrong or could do better.
I only have access to tmux and alacritty, and getting other terminals on my system is a little tedious because I need to compile them (gentoo). It would be nice if the folks affected by #10089 could run `echo $TERM_PROGRAM` and `echo $TERM` in their terminal. I'll add those terminals to this PR.
> avoid cnorm on certain terminals

- helix-term/src/commands/typed.rs
- helix-view/src/editor.rs
Stopping or restarting an LSP currently does not cleanup the inlay hints for the documents.
They're correctly recomputed later in the restart case *if the restarted LSP supports them*: changing the binary and restarting can change that behaviour (e.g. after an update, which is reason to call `:lsp-restart` on an open document)
> fix: correctly reset inlay hints when stopping or restarting LSPs for a document

- helix-term/src/commands.rs
Fixes https://github.com/helix-editor/helix/issues/10765
Original MR for this issue: https://github.com/helix-editor/helix/pull/10788
> Flush pending writes before suspend

- helix-term/src/handlers/completion/resolve.rs
Rust-analyzer for example sends `Some([])` for completion items and then sends the actual additional text edits in the completionItem/resolve response.
Fixes https://github.com/helix-editor/helix/issues/10787
> LSP: Resolve completion items when any info is missing

- helix-loader/build.rs
Fixes #10855.
The loader build.rs tries to determine when HEAD changes,
so it can re-run and update the embedded version.
It was shelling out to do this, and capturing a trailing newline,
so it always thought HEAD did not exist.
I confirmed that if I update helix-term, helix-loader rebuilds and updates the commit hash:
```
[rcorre@midgar helix]$ git rev-parse --short HEAD
e24eed2c
[rcorre@midgar helix]$ hx --version
helix 24.3 (e24eed2c)
[rcorre@midgar helix]$ hx helix-term/src/main.rs
[rcorre@midgar helix]$ git cma "test changing helix-term"
[fix-version cbb68bab] test changing helix-term
1 file changed, 1 insertion(+)
[rcorre@midgar helix]$ cargo install --path helix-term --locked
Installing helix-term v24.3.0 (/home/rcorre/src/helix/helix-term)
Updating crates.io index
Compiling …
```
> Fix logic to update version when HEAD changes.

- helix-tui/src/backend/crossterm.rs
> "it's" -> "its", in `crossterm.rs`

- languages.toml
This PR adds `py` as a valid injection regex for Python. `py` is a valid key for various highlighter implementations. The most glaring example being the one used on GitHub itself:
````md
```py
print()
```
````
being
```py
print()
```
EDIT:
I noticed the lack of `hs` for Haskell and `rs` for Rust, which are also very common, so I added those too.
EDIT2:
I've also added `typ` for `typst`.
> Add `py`, `hs`, `rs` and `typ` injection regexes

- helix-term/src/commands.rs
- helix-term/tests/test/commands.rs
Remove special handling of line ending characters in selection replacement which prevented newline characters from being replaced
Fixes #10725
> Remove special handling of line ending characters in selection replacement

- runtime/themes/noctis.toml
This affects both `goto_word` and LSP inlay hints.
Before:
https://webaim.org/resources/contrastchecker/?fcolor=073A40&bcolor=00262A
After:
https://webaim.org/resources/contrastchecker/?fcolor=0D6772&bcolor=00262A
I just chose a similar colour from the pallet defined by noctis; Notably, the new colours still don't pass the accessibility contrast threshold for WCAG 2.0 level AA. This might be something to consider, but perhaps is acceptable as these elements are meant to not stick out.
> Improve readability of virtual text with 'noctis' theme

- languages.toml
- runtime/queries/cairo/highlights.scm
- runtime/queries/cairo/indents.scm
- runtime/queries/cairo/injections.scm
- runtime/queries/cairo/locals.scm
- runtime/queries/cairo/textobjects.scm
Move from rust grammar to a proper cairo grammar. Both the grammar and the queries are based on the rust one
> feat(cairo): update tree-sitter grammar and queries

- helix-term/src/commands/lsp.rs
Fix https://github.com/helix-editor/helix/issues/10560 by accepting an optional history register for the
`rename_symbol` command.
> Optional history for rename_symbol

- helix-term/src/ui/editor.rs
Current behavior allowed a user to input a more than reasonable value for count, where it could grow till the full value was larger than the allotted render width, and could eventually overflow.
This pull request takes guidance from this [comment](https://github.com/helix-editor/helix/issues/10922#issuecomment-2160779267) by @the-mikedavis and caps the value to be below 100,000,000. This would leave the full value viewable and prevent any overflow.
There were other options, such as converting to a string first to check the length, and then dropping the digit that would grow past the allotted render width, keeping a rolling in-render value, but this would add an allocation each time even when not going beyond the selected size.
Ultimately, it was decided that this would be a low percentage …
> fix(editor): prevent overflow in count modifier

- Cargo.lock
unicode-width 0.1.13 contains some fixes that change the widths of line endings, which breaks some assumptions in helix-tui, causing some rendering artifacts. We can downgrade to remove the rendering errors for now.
Fixes https://github.com/helix-editor/helix/issues/10950
> Downgrade unicode-width to 0.1.12

- runtime/themes/catppuccin_frappe.toml
- runtime/themes/catppuccin_latte.toml
- runtime/themes/catppuccin_macchiato.toml
- runtime/themes/catppuccin_mocha.toml
Closes #10903. Updates the vendored Catppuccin themes with changes from https://github.com/catppuccin/helix.
> Sync latest Catppuccin themes changes

- runtime/themes/github_dark.toml
The colors while using the newly introduced jump feature have been bugging me, especially in the github_dark family of themes.
(I can hardly see this, especially the jump characters on selection)
> improve jump colors for github_dark themes

- helix-core/src/match_brackets.rs
Closes #10966.
The change works fine on my computer. I'm not sure what, if anything, else I should be checking.
Thanks to @the-mikedavis for pointing out where to make this change.
> Add curly single and double quotes to BRACKETS

- book/src/keymap.md
- book/src/syntax-aware-motions.md
- book/src/textobjects.md
This fixes some links that were somehow not caught by the linter in https://github.com/helix-editor/helix/pull/10619.
I added this one as well to keep them all together: https://github.com/helix-editor/helix/pull/10921, so you can close that if you like.
> Fix multiple broken links in the documentation

- Cargo.toml
- helix-dap/Cargo.toml
- helix-lsp/Cargo.toml
- helix-term/src/application.rs
- helix-term/src/args.rs
- helix-term/src/commands.rs
- helix-term/src/ui/mod.rs
- helix-view/Cargo.toml
- helix-view/src/document.rs
- helix-view/src/editor.rs
As per the suggestions in #10726 this pull request changes the argument parsing to only add a PathBuf to args.files if it is either a file or a symlink. This has been tested on the scenarios provided in the issue and simply opens an empty buffer as if no argument was provided in those cases. (instead of freezing)
> Prevent improper files (like /dev/random) from being used as file arguments

- helix-core/src/syntax.rs
When parsing injections, we skip adding a new layer if there is an existing layer covering the same range. When doing so we did not update the parent layer ID, so some layers could have `parent` layer IDs that pointed to a layer that no longer existed in the `layers` HopSlotMap which could cause a panic when using `A-o`.
To fix this we update the `parent` pointer for both newly created injection layers and reused ones.
Fixes #10974
> tree-sitter: Update parent links on reused injection layers

- base16_theme.toml
Currently, virtual text such as LSP inlay is impossible to distinguish from 'real' text by default; the `color-modes` option does nothing. I've added a default gray similar to comments (with italics, if supported to more easily distinguish, but we can probably assume that inlay mostly wont be inside comments). Also added `ui.statusline.insert` to match `diff.plus` and `ui.statusline.select` to match the selection colour, `ui.statusline.normal` is intentionally left unthemed.
> base16_default: add styles to newer unthemed features

- languages.toml
As the title suggests, tested it locally and it works as expected.
> Add block comment tokens for typst

- languages.toml
(Sorry for making another PR with a really small configuration change)
Reference: https://leanprover-community.github.io/contribute/style.html
> Line length
> Lines should not be longer than 100 characters. This makes files easier to read, especially on a small screen or in a small window. If you are editing with VS Code, there is a visual marker which will indicate a 100 character limit.
I think it would be helpful to also have this in helix so I added a ruler at 101 and text-width at 100.
Tell me if anything needs to be changed, thanks!
> Add ruler at 101 and text-width at 100 to lean in languages.toml

- helix-term/src/commands/typed.rs
Rather than showing an error of `n unsaved buffer(s) remaining: ...`, we use either `buffer` or `buffers` as required.
> Only pluralise "buffer" when required

- helix-term/src/handlers/auto_save.rs
- helix-view/src/handlers.rs
Saving while in insert mode causes issues with the modification indicator and this is very easy to reproduce with the current state of the auto-save hook. We can tweak the hook slightly to await the mode switch out of insert mode to perform the save.
The debounce is preserved: if you save and then immediately exit insert mode the debounce will be respected. If the debounce lapses while you are in insert mode, the save occurs as you switch out of insert mode immediately.
Fixes #10991
> Delay auto-save until exiting insert mode

- runtime/queries/vhdl/highlights.scm
Hi, the highlighting for the VHDL language is very basic and is missing a lot of features. My changes fixes that. I'd like to think these are sane defaults and also minimalist.
@teburd
> VHDL highlights.scm improvement

- docs/releases.md
"No contribution is too small" :smile:
The homebrew link in [docs/releases.md](https://github.com/helix-editor/helix/blob/master/docs/releases.md) is currently a 404. Updates it to the current link.
> Fix homebrew formula link in docs/releases.md

- languages.toml
- runtime/queries/cairo/highlights.scm
- runtime/queries/cairo/indents.scm
The next cairo release will introduce associated impls and iterators which come with some new syntax. Update the tree-sitter to support that and the queries
> chore: update cairo tree sitter + queries

- Cargo.lock
Current lock file has time version 0.3.23 in it. But this version is broken (possibly only on nightly, but I compile everything with nightly):
```
Installing helix-term v24.3.0 (C:\Users\Ross\AppData\Local\helix\helix-term)
Updating crates.io index
Compiling bstr v1.8.0
Compiling thiserror-impl v1.0.61
Compiling serde_derive v1.0.203
Compiling time v0.3.23
Compiling regex-cursor v0.1.4
Compiling which v6.0.1
Compiling windows_x86_64_msvc v0.48.0
Compiling tokio-macros v2.3.0
Compiling regex v1.10.5
Compiling smartstring v1.0.1
Compiling slotmap v1.0.7
Compiling unicode-general-category v0.6.0
Compiling regex-syntax v0.8.2
Compiling bytes v1.4.0
Compiling shell-words v1.1.0
Compiling ryu v1.0.13
Compiling cov-mark v1.1.0
Compiling unicode-segmentation v1.11.0
Compiling arc-swap v1.7.1 …
```
> Bump time from broken version (0.3.23)

- helix-lsp/src/client.rs
Without providing the formatting capability, the language server might not advertise its ability to format in return, causing the `:format` command to be broken.
> Tell language servers that Helix can request formatting

- runtime/themes/gruvbox_light.toml
Religious Gruvbox light user here. @Chirikumbrah recently made a number of excellent tweaks to the base Gruvbox theme (#10773). One of these has had the unfortunate effect of turning the non-primary cursor line dark, making the text of the current line unreadable due to poor contrast. This is shown in the 'before' panel of the image below.
This PR sets things right by overriding the non-primary cursor background in the Gruvbox Light variant (which propagates to the other Light variants through inheritance.) The result is shown in the 'after' panel.
---
Question for @Chirikumbrah: I see you've defined a special `bg0_s = "#32302f"` (dark0_soft in gruvbox.nvim) for the cursorline. This is the same color as the background in Gruvbox Dark Soft, meaning that the non-primary cursorline doesn't …
> Gruvbox light theme. Fix cursorline readability after #10773.

- helix-term/src/commands/typed.rs
- helix-term/src/ui/mod.rs
This fix allows for multiple language servers at once which support workspace commands. This was previously broken as just the first language server supporting workspace commands was queried when listing allowed worspace commands.
The fix is in two parts. Firstly, querying all workspace commands from all language servers available and using them when actually running the command in `lsp_workspace_command`. Secondly, doing the same in `completers::lsp_workspace_command` such that completion still works as expected.
The fix has one remaining issue, which I am unsure how to handle in the best way possible, but which I also don't think should happen often: Multiple language servers may register commands with the same name. This will lead to that command being listed in the popup menu and in …
> Allow multiple language server with lsp-workspace-command

- helix-term/src/commands/typed.rs
This fixes the build after merging https://github.com/helix-editor/helix/pull/10176. The outdated use of `usize` in that PR conflicts with refactor to newtype language server IDs in https://github.com/helix-editor/helix/pull/10539.
> Fix language server ID type in lsp_workspace_command

- runtime/themes/base16_transparent.toml
Shouldn't be a problem as they need to be opted into manually. Better than having nothing when they are enabled in config.
> Add cursorcolumn and cursorline to base16_transparent theme

- helix-dap/src/client.rs
- helix-loader/src/grammar.rs
- helix-lsp/src/client.rs
Full explanation: ["Choose the Right Option"](https://youtu.be/6c7pZYP_iIE) by [Logan Smith](https://youtube.com/@_noisecode)
[NPO](https://doc.rust-lang.org/std/option#representation)
TLDR:
- internal APIs are less likely to break, as implementation details aren't exposed
- flexibility
- memory optimizations
> `&Option<T>` -> `Option<&T>`

- runtime/queries/bash/highlights.scm
1. `ansi_c_string` was missing as a string type
2. `heredoc_start` was wrongly a string, and `heredoc_end` was missing.
I have fixed these issue, I chose to use `@label`for heredoc following Neovim.
> Fix heredoc highlights and add ansi_c_string highlights in bash queries

- helix-term/src/commands.rs
Previously `gf` on `~/.config/helix` for example would error if the entire path was selected but succeed and open a picker for the directory contents if the selection was one one-width cursor. We need to expand tildes for all paths instead of just the auto-detected paths.
This also refactors the `goto_file` blocks a little so that we construct `paths` once instead of creating the Vec and immediately clearing it when the selection is one single-width cursor.
Fixes #10948
> Expand tilde for selected paths in `goto_file`

- contrib/completion/hx.fish
- add -w and --working-dir options
- shorten option description
- dynamically call hx --health
> feat: improve hx fish completion

- contrib/completion/hx.zsh
1. Add working directory
2. Change some wording to make it follow https://github.com/helix-editor/helix/pull/10853 more closely
3. Increase tail to +11 as this is where the actual languages start in the output from `hx --health`
4. Filter ✘ and ✓ from the output
QUESTION: Why is `#compdef _hx hx` commented out? I have not un-commented it in case it is something to do with packaging I may not be aware of. It of course does not work until it is un-commented and will confuse people just trying to install the script themselves. Shall I un-comment it?
> Update ZSH completions

- languages.toml
Small additions:
* Lockfiles for [pdm](https://pdm-project.org/latest/usage/lockfile/) and [uv](https://github.com/astral-sh/uv)
* Git's `~/.config/git/ignore` [file](https://git-scm.com/docs/gitignore)
* npm's `npmrc` [files](https://docs.npmjs.com/cli/v10/configuring-npm/npmrc#files)
> Add {pdm,uv}.lock, git/ignore, npmrc to languages

- book/src/building-from-source.md
When following the documentation for installing the desktop files as it is, I encountered numerous issues where the Helix icon and Helix desktop integration would sometimes work and sometimes not. Diagnosing the root cause was a nightmare. Eventually, I discovered that the `.desktop` file needed absolute paths to the Helix binary and icon.
Note that kitty asks users to do the same thing: https://sw.kovidgoyal.net/kitty/binary/#desktop-integration-on-linux
```sh
sed -i "s|Icon=kitty|Icon=$(readlink -f ~)/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
sed -i "s|Exec=kitty|Exec=$(readlink -f ~)/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
```
I am aware that the next section `To use another terminal...` …
> Documentation: Convert the links in the `.desktop` file to absolute paths to avoid potential problems

- contrib/completion/hx.zsh
> > Why is #compdef _hx hx commented out?
> 
> Sorry for the drive-by comment, but it was correct before. That's zsh's tag syntax for autoloaded completion files (i.e. those in `$fpath`, which is where `brew` and other packagers place them): https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Autoloaded-files
Based on https://github.com/helix-editor/helix/pull/11120#issuecomment-2221865789 removing the `#` was a mistake, I have replaced it.
> Fix ZSH completions

- helix-term/src/commands.rs
- helix-term/tests/test/commands.rs
Current `pipe`-like commands, `pipe`, `insert-output`, and `append-output`, return directly what `stdout` had, which usually includes a newline. This can limit its efficiency in the editor as when someone would want to run the same command on many selections, the additional whitespace can become cumbersome to manually trim.
This PR trims all whitespace from the end of the output. This was mainly chosen do to the simplicity of the change, but even when testing an iteration where only a single newline was removed, it felt more inline with expectations and so was chosen for the final change.
`pipe:exa`
```diff
base16_theme.toml
book
Cargo.lock
Cargo.toml
CHANGELOG.md
contrib
default.nix
docs
Files
flake.lock
flake.nix
grammars.nix
helix-core
helix-dap
helix-event
helix-loader
helix-lsp …
```
> refactor(commands): trim end of `pipe`-like output

- languages.toml
Currently, files in a Helm Chart's `templates/` directory ending with the `yml` extensions do not use the `helm` language but the default `yaml`. This PR fixes that, by also adding `.yml` files to the `helm` language.
> Include .yml files in Helm chart templates

- languages.toml
- runtime/queries/hare/highlights.scm
- runtime/queries/hare/locals.scm
This change uses <https://git.sr.ht/~ecs/tree-sitter-hare/> that is up-to-date and linked from the official documentation.
> Update Hare grammar

- helix-term/src/commands/typed.rs
This fixes the modification indicator when saving from insert mode with a config such as:
```toml
[keys.insert]
C-s = ":write"
```
Previously the modification indicator would be stuck showing modified even if the buffer contents matched the disk contents when writing after some changes in insert mode with this binding. In insert mode we do not eagerly write undo checkpoints so that all changes made become one checkpoint as you exit insert mode. When saving, `Document`s `changes` `ChangeSet` would be non-empty and when there are changes we show the buffer as modified. Then switching to normal mode would append the changes to history, bumping the current revision past what it was when last saved. Since the last saved revision and current revision were then unsynced, the modification …
> Commit undo checkpoints before each `:write`

- README.md
This change excludes EOL repos from the Repology packaging status badge.
| Before: | After: |
| --------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| ![Packaging status](https://repology.org/badge/vertical-allrepos/helix.svg) | ![Packaging status](https://repology.org/badge/vertical-allrepos/helix.svg?exclude_unsupported=1) |
> Exclude EOL repos from the Repology badge

- runtime/queries/blade/highlights.scm
- runtime/queries/blade/injections.scm
Simple pull request adding the missing, bracket theming selector for `blade.php` files
**VS**
> Update highlights.scm and injections.scm for blade.php files

- helix-view/src/editor.rs
When an existing Document is opened with `Editor::open(path, Action::Load)`, this causes `Editor::switch` to be called.
This in turn resets the mode of the editor to normal mode, even if the loaded Document is not even in the current buffer.
To my knowledge this is only an issue in combination with the LSP `workspace/applyEdit` functionality.
Language servers that heavily utilize `applyEdit` make using helix nearly impossible, as typing and selecting is constantly interrupted by unexpected mode changes.
> Improve LSP workspace/applyEdit by keeping the editor from switching to normal mode when loading a Document

- Cargo.lock
- Cargo.toml
- book/src/themes.md
- helix-core/Cargo.toml
- helix-core/src/fuzzy.rs
- helix-core/src/lib.rs
- helix-core/src/uri.rs
- helix-event/src/lib.rs
- helix-event/src/redraw.rs
- helix-term/Cargo.toml
- helix-term/src/application.rs
- helix-term/src/commands.rs
- helix-term/src/commands/dap.rs
- helix-term/src/commands/lsp.rs
- helix-term/src/commands/typed.rs
- helix-term/src/ui/menu.rs
- helix-term/src/ui/mod.rs
- helix-term/src/ui/picker.rs
- helix-term/src/ui/picker/handlers.rs
- helix-term/src/ui/picker/query.rs
- helix-term/src/ui/prompt.rs
- helix-view/src/document.rs
- helix-view/src/editor.rs
- helix-view/src/handlers/lsp.rs
I was hoping to make these picker changes as separate PRs but they layer in a way that makes reviewing them independently awkward: one commit changes a block and the next changes it again, so I think it's easier to review altogether. This PR is a kind of "version 2" for the `Picker` component that resolves a bunch of things we've wanted to change about `Picker`s:
* Lay out items in a table format so that we can filter on columns independently (previously https://github.com/helix-editor/helix/pull/7265)
* Control whether certain columns are used for Nucleo-based filtering or not (useful for `DynamicPicker`s, see #5714)
* Replace the ad-hoc `IdleTimeout` approach for syntax highlighting the preview with an event-system hook (https://github.com/helix-editor/helix/issues/9629)
* Use …
> `Picker`s "v2"

- helix-term/src/commands/typed.rs
Vim supports these, and i can't think of any reason helix would want to have a different meaning for `:edit` than `:open`.
note that it is not possible to add this manually in helix configuration until https://github.com/helix-editor/helix/issues/4423 is fixed.
docs: https://vimhelp.org/editing.txt.html#%3Aedit
> add `:edit` and `:e` as aliases for `:open`

- book/src/guides/adding_languages.md
- book/src/guides/indent.md
- book/src/guides/injection.md
- book/src/guides/textobject.md
- book/src/lang-support.md
- book/src/languages.md
- book/src/remapping.md
- book/src/themes.md
Fixed single `#` headings to match the pattern:
title page - `#`
- installation - `#`
- package managers - `##`
- building from source - `##`
- usage - `#`
- registers - `##`
- surround - `##`
- textobjects - `##`
etc.
Why is `commands.md` unchanged? Did it in #11152 .
> Fixed headings (# / ##) in /book to match other docs

- helix-term/src/commands.rs
Checks to see if the input ended in a newline to decide if the output should have it trimmed, if it too ended in one, and only ever trim one newline.
This follows Kakoune's [decision](https://github.com/mawww/kakoune/commit/6f135c0c8e4d4d5b66cd6b56394ad7d690a16252) [here](https://github.com/mawww/kakoune/issues/3669) to make sure **input** is not corrupted:
```cc
if (in.back() != '\n' and not out.empty() and out.back() == '\n')
out.resize(out.length()-1, 0);
```
`pr`:
```rust
if !input.ends_with("\n") && !output.is_empty() && output.ends_with('\n') {
output.pop();
// windows
if output.ends_with('\r') {
output.pop();
}
}
```
To note: This still trims a single newline from pipe output if the input selection does not end in a newline.
Closes: #11177
> fix(commands): change `pipe`-like output trimming

- CHANGELOG.md
According to the [keymap/defaults.rs](https://github.com/helix-editor/helix/blob/24.07/helix-term/src/keymap/default.rs#L90) the correct keybind is `A-I` and not `A-i`.
> Fix `select_all_children` command keybind

- runtime/themes/kanagawa.toml
- Fixes some colours not matching their counterpart in neovim.
- Adds `ui.debug` colours
- Fix for separators in inactive statuslines
> Bring `kanagawa` colours better in line with neovim version

- helix-term/src/ui/picker.rs
- helix-term/src/ui/prompt.rs
The Prompt is set up to push the current line to history when hitting Enter but the Picker doesn't pass the Enter event down to the Prompt (for good reason: we don't want the Prompt's behavior of changing completions when we hit a path separator). We should save the Prompt's line to its configured history register when hitting Enter when there is a selection in the Picker.
This currently only applies to `global_search`'s Picker since it's the only Picker to use `Picker::with_history_register`.
Fixes https://github.com/helix-editor/helix/issues/11205
> global_search: Save search when accepting an option

- helix-term/src/ui/picker.rs
- helix-term/src/ui/prompt.rs
Two changes from #11209 (which this PR partially reverts):
* Save only the `Picker::primary_query` - so you don't save other parts of the query, for example `%path foo.rs` while in `global_search`.
* Move the saving out of the `if let Some(option) = self.selection()` block. So when you hit enter you save to history whether you have a selection or not. If you want to close the picker without saving to the register you can use C-c or Esc instead.
Fixes https://github.com/helix-editor/helix/issues/11214 and addresses part of https://github.com/helix-editor/helix/issues/11205#issuecomment-2233888741
> global_search: Save only the primary query to the history register

- languages.toml
There has been a new release with a few minor tweaks to the parser. The queries are fine still.
> tree-sitter: Update SHA of parser fro the slint language

- helix-term/src/ui/picker.rs
- helix-term/src/ui/picker/handlers.rs
Pastes are probably the last edit one means to make before the query should run so it doesn't need to be debounced. This makes global search much snappier for example when accepting the history suggestion from the '/' register or pasting a pattern from the clipboard or a register.
Connects #11206
> Picker: Skip dynamic query debounce for pastes

- contrib/completion/hx.nu
See the note at the top of the file, it's not perfect, but it does 99% of the job:
Toplevel:
`--heath` completions:
`--grammar` completions:
> contrib: add nushell completions

- book/src/generated/typable-cmd.md
- helix-term/src/commands/typed.rs
`mv` is the familiar shell command to move or rename a file. Add this to Helix as an alias for `:move`.
> Add `:mv` as an alias for `:move`

- runtime/themes/kanagawa.toml
Turns out `winter*` are meant for background colours and makes text marked as `@diff.*` really hard to read.
> Revert `kanagawa` diff colour change from #11187

- helix-view/src/register.rs
This matches Kakoune's behavior. Its '%' special register returns the current buffer's "display path" which is the same as our `Document::display_name`: a relative path, or a path with a tilde (if the path is under the home dir) or an absolute path otherwise, and `SCRATCH_BUFFER_NAME` if the doc has no path.
> Return document display name from the `%` special register

- helix-term/src/application.rs
- helix-term/src/commands.rs
- helix-term/src/commands/lsp.rs
- helix-term/src/commands/typed.rs
- helix-term/src/ui/editor.rs
- helix-term/src/ui/mod.rs
- helix-view/src/document.rs
- helix-view/src/editor.rs
- helix-view/src/lib.rs
- helix-view/src/view.rs
Supersedes #7568, fixes #7355.
Since view offsets can no longer be initialised in `View::new()`, I moved them next to selection initialisation in `doc.ensure_view_init(view_id)`. I was a little concerned about all those unwraps on `doc.view_data(view_id)` (those functions are infallible and don't have a mutable reference to doc, so there's no way to ensure view_data is initialised in there), but in theory it should be panic-safe, as long as `doc.ensure_view_init(view_id)` is called for every new view, which it is. It was missing from some test cases, since they didn't seem to need selections, but it's added even to those now.
> Keep ViewPosition consistent when a Document is edited from different Views, and on buffer switching

- runtime/tutor
This is just a simple addition to the tutor file to document the ```gw``` 2-character label jump motion.
> Add tutor entry about 2-character label jump

- runtime/tutor
Some small tweaks that fix some minor typos in the recent `gw` addition to the Tutor.
> Fix typos in 2-character label jump Tutor entry

- languages.toml
`just` has modules (see https://github.com/casey/just#modules1190) (since 1.19, stable 1.31) which are files defined as `foo.just`, `foo/mod.just`, `foo/justfile`, or `foo/.justfile` with the latter two having any capitalization.
This pr adds the file extension `just` for `just`/`justfile`s
> feat(language): just module extension

- helix-lsp/src/lib.rs
Fixes an off-by-one error that caused index out of bounds for some LSP responses, or the eating of newlines for others. 
Fixes: #10689
> fix(lsp): `find_completion_range` off-by-one

- contrib/completion/hx.bash
Hi,
while I try to using helix the completion kept presenting me the flags even if I never tiped `-`.
Since I think this is not how completion should work I refactored so it behaves more sanely.
https://github.com/user-attachments/assets/acd49cee-d00d-432c-a654-5d025408f57a
> Make bash completion behave normally

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/jjdescription/highlights.scm
Basic highlighting support for `jjdescription` files.
Language rules are copied from `git-commit` as they're essentially the same thing currently.
Default theme preview:
> Add support for `jjdescription` files

- languages.toml
`mdx` - markdown with jsx support is becoming quite popular for some react-based javascript frameworks
the standard markdown highlighting works fine
> languages: add mdx to markdown filetypes

- helix-view/src/document.rs
These changes are ported from https://github.com/helix-editor/helix/pull/9801. It's a cleanup of `Document::apply_impl` that uses some early returns to reduce nesting and some reordering of the steps. The early returns bail out of `apply_impl` early if the transaction fails to apply or if the changes are empty (in which case we emit the SelectionDidChange event). It's a somewhat cosmetic refactor that makes the function easier to reason about but it also makes it harder to introduce bugs by mapping positions through empty changesets for example (https://github.com/helix-editor/helix/issues/11291).
Fixes #11291
> Reorganize `Document::apply_impl`

- helix-term/src/application.rs
- helix-view/src/document.rs
- helix-view/src/editor.rs
In the case of network file systems, if the server time is ahead of the local system time, then helix could annoy with messages that the file has already been modified by another application.
closes #10840
> Use fs' mtime to avoid saving problem on out-of-synced network fs

- Cargo.lock
- helix-stdx/src/faccess.rs
- helix-stdx/src/lib.rs
- helix-term/Cargo.toml
- helix-term/tests/test/commands/write.rs
- helix-view/src/document.rs
> Fix writing hardlinks

- helix-core/Cargo.toml
Cargo automatically bumbs the patch version when installed with `cargo install`
without the locked flag. That creates weird rendering artifacts as unicode-width changes width definitions in a minor release (in a way incompatible with our logic and most terminals). I have my own version of this crate taht I created a long time ago that we should switch to at some point.
> lock unicode width

- helix-term/tests/test/commands/write.rs
Non-rooted Android typically doesn't have permission to use hard links at all, so this test fails on Android.
> Disable hard link integration test on Android

- helix-lsp/src/lib.rs
Currently if you stop language server(s) for a file with `:lsp-stop` and then open another file from that language, the language server(s) will be restarted. Instead of removing the language server info entirely when we `:lsp-stop`, we can replace the records in the registry with a "tombstone" which prevents automatic restarts by `Registry::get`.
Closes #11319
> Tombstone LSP clients stopped with `:lsp-stop`

- helix-core/src/syntax.rs
- languages.toml
- runtime/queries/just/folds.scm
- runtime/queries/just/highlights.scm
- runtime/queries/just/indents.scm
- runtime/queries/just/injections.scm
- runtime/queries/just/locals.scm
- runtime/queries/just/textobjects.scm
Updates the queries and grammar for [just](https://github.com/casey/just). This includes support for shebang syntax highlighting in the commands.
Part of this pr also includes a change in how `language_configuration_for_injection_string` works, with [instructions](https://github.com/helix-editor/helix/pull/9850#issuecomment-2075704352) from @the-mikedavis.
Supersedes: #9850
Fixes: #8226
> feat(languages): update `just` grammar and queries

- contrib/completion/hx.nu
And once a few characters are entered:
> contrib: nushell: also complete available languages with --health

- docs/CONTRIBUTING.md
On MacOS Sonoma 14.5 with an M1 Pro chip, I ran into errors such as the one below for having "Too many open files"
```
---- test::commands::write::test_write_scratch_no_path_fails stdout ----
thread 'test::commands::write::test_write_scratch_no_path_fails' panicked at helix-term/tests/test/commands/write.rs:297:7:
Failed building the Runtime: Os { code: 24, kind: Uncategorized, message: "Too many open files" }
```
This causes the tests to fail. AFAICT there's nowhere in the docs for "code contributor errata", so I hope this is the appropriate place for this note :)
> Documented ulimit fix for error during integration tests

- helix-view/src/document.rs
These are changes that fell out of commit:
d7a3cdea65ef321d53b8dc8417175781b5272049
> Remove unnecessary `.as_mut()` call and fix log messages

- helix-view/src/document.rs
On platforms which don't support fetching file system mod times, this error message gets printed on every single file write, which is really not helpful. So, reduce the log level to debug.
Also slightly modify the error message to be a bit more generic; there are reasons other than platform support that fetching metadata can fail.
> reduce log noise on file writes

- helix-lsp/src/lib.rs
- helix-term/src/commands/lsp.rs
Closes #11174
The lsp spec specifies that if there are multiple edits at the same position (overlaps are forbidden) that text should be inserted in the order send by the LS. The unstable sort we are using essentially made the order in these cases practically undeterminstic. Using a stable sort tkeeps the order of edits from the sever.
This is mostly orthogonal to the nvim related issues mentioned in the issue description (our transactions atomically apply multiple edits while nvim has to apply the edits in reverse since it doesn't have an equivalent API).
> stable sort lsp edits

- book/src/themes.md
- helix-term/src/ui/picker.rs
full fill column's background for picker, it can be defined use 
```toml
"ui.picker.header" = { fg= "white", bg = "red" }
```
> Add theme keys for the picker header area

- helix-core/src/syntax/tree_cursor.rs
The `take_while` should limit the ranges we consider to those that end on/after the searched `end`: the ranges are sorted by `end` ascending and if a tree has nested injection layers, the starts might be sorted in descending.
For example
```vue
<script setup lang="ts">
const foo = 'bar'.match(/foo/);
const bar = foo;
</script>
```
L2 and L3 are a typescript layer and the `/foo/` part is a small regex layer. If you used `A-o` before the regex layer you would select the entire typescript layer. The search in `layer_id_containing_byte_range` would not consider the typescript layer since the regex layer comes earlier in `injection_ranges` and that layer's start is after `end`.
The `partition_point` in the line above this change leads us to the start of the ranges where `range.end >= end` and …
> Fix finding injection layer in tree cursor with nested layers

- languages.toml
The primary executable that comes with Tcl is `tclsh`. Not really sure what `tclish` is, as I initially thought it was a typo. However, there seems to be references to it based on a quick search (e.g. [here](https://wiki.tcl-lang.org/page/Tclish) and [here](https://tclish.sourceforge.net/)), so maybe it's a valid executable that I just haven't been aware of. I was hesitant to replace it and instead opted to just add `tclsh`.
> update shebangs language configuration for Tcl

- helix-core/src/auto_pairs.rs
- helix-core/src/indent.rs
- helix-core/src/syntax.rs
- helix-stdx/src/faccess.rs
- helix-term/build.rs
- helix-term/src/application.rs
- helix-term/src/commands/lsp.rs
- helix-term/src/commands/typed.rs
- helix-term/src/main.rs
- helix-tui/src/text.rs
- helix-view/src/document.rs
- helix-view/src/handlers/dap.rs
- helix-view/src/handlers/lsp.rs
Using `clippy 1.80.0`. Cleans up some that were windows only.
There was one left over:
```shell
warning: accessing first element with `args.get(0)`
--> helix-term\src\commands\typed.rs:2501:20
|
2501 |     let filename = args.get(0).unwrap();
|                    ^^^^^^^^^^^ help: try: `args.first()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#get_first
= note: `#[warn(clippy::get_first)]` on by default
```
But this is addressed in #11149.
> chore: clean up clippy lints

- helix-lsp/src/client.rs
- helix-view/src/editor.rs
Fix for #11384
I am unsure if this is the best way to fix it. But it does work.
> fix :move panic when starting a new language server

- helix-term/src/commands.rs
- helix-term/src/commands/typed.rs
Rather than getting the error in the one row of the status bar, and needing to check the logs to see what the error actually was, it now outputs to the popup. This doesn't address every use case, but for when it's sufficient, its a very nice quality of life improvement. Other options could come later to improve this, like what was said [here](https://github.com/helix-editor/helix/issues/2700#issuecomment-1206328317)
> A horizontal split with a scratch buffer similar to what log does could be a good approach
But I don't see a reason not to have a quick fix for something now.
Connects: #2700
> refactor(commands): output `stderr` in `:sh` popup

- helix-term/src/commands.rs
When using `keep_selections` (`K`) if we find no matches all selections are kept.
This can be confusing since we only want to keep the selections that match the regex, if no match is found the expected behavior is to keep no selection.
I've also added a status indicating this to the user, so that the user knows that the command ran as expected and no matches were found.
For the `remove_selections` this case is when all lines match so no line will be removed, I also added a status update for this.
> Add statusline errors when nothing is selected with `s`, `K`, `A-K`

- languages.toml
Gleam has added a new short-hand syntax for labeled arguments.
```gleam
pub fn main() {
let day = 11
let month = October
let year = 1998
date(year:, month:, day:)
}
```
> Update Gleam tree sitter to support label shorthand syntax

- helix-core/src/movement.rs
- helix-term/src/commands.rs
This PR adds commands that enable movement within subwords that are snake_cased or camelCased, as previously proposed in discussion https://github.com/helix-editor/helix/discussions/5463. Subwords are delimited by underscores and by transitions from lowercase to uppercase.
The commands are named `{move,extend}_{next,prev}_sub_word_{start,end}`. This PR doesn't add any keybinds.
Example usage (`|` characters indicate cursor):
- `|f|oo bar baz` -> move next sub word -> `|foo |bar baz`
- `|f|oo_bar_baz` -> move next sub word -> `|foo_|bar_baz`
- `|f|ooBarBaz` -> move next sub word -> `|foo|BarBaz`
Example keybinds:
```toml
[keys.normal]
W = 'move_next_sub_word_start'
B = 'move_prev_sub_word_start'
E = 'move_next_sub_word_end'
[keys.select]
W = 'extend_next_sub_word_start'
B = …
```
> Add commands for movement by subwords

- book/src/generated/lang-support.md
- languages.toml
Hi, I noticed that meson was configured but there was no default LSP setup.
I went looking and could only really find one major LSP for Meson which is also in active development.
`mesonlsp` is both in the Arch Linux official repo and is also the LSP used for integration on VSCode. 
I've added it to my `languages.toml` and thought it might be helpful to just have this built-in.
> Added `mesonlsp` as the default LSP for Meson

- runtime/themes/dark_plus.toml
1. The first change involves updating the "attribute" color. This now matches the color scheme used in VS Code for HTML and does not appear to negatively affect other languages I tested.
2. The second change involves the bold modifier. Previously, it changed the text to blue, which was correct for Markdown to mimic VS Code but looked unappealing in other contexts. Additionally, it was unusual since no other Markdown editor does this. Now, the text is changed to actual bold, consistent with other editors. This change might be contentious, but considering the updates to enable bold highlights in HTML (see [Helix Editor Pull Request #11400](https://github.com/helix-editor/helix/pull/11400)), having blue text stand out in HTML is undesirable and inconsistent with VS Code.
Now it looks like …
> Dark_Plus: Add picker highlights, update underlined modifier, and change a few settings

- helix-term/src/ui/picker/query.rs
With this as an example:
```rust
1 fn main() {
2    let _ = 1 > 2;
3    let _ = match 1 {
4        1 => 2,
5        _ => unreachable!(),
6    };
7 }
```
When looking to match ` > 2`, local search correctly only matches line 2. Global search was trimming the pattern and so would match line 2, but also line 4.
Fixes #11404
> fix(picker): no longer `trim` search pattern

- runtime/queries/html/highlights.scm
@the-mikedavis Please reference our discussion https://github.com/helix-editor/helix/discussions/11392
Quick question before I mark this ready... I want to add:
```
((element
(start_tag
(tag_name) @_tag)
(text) @markup.underline)
(#eq? @_tag "u"))
```
but there is no Helix equivalent to `@markup.underline`, what do you advise? Add the modifier? Not sure of best practice, it would loose it's semantic meaning adding a modifier rather than a proper scope?
I think I cracked the precedence problem by replacing:
```
[
"\""
(attribute_value)
] @string
```
with
```
((attribute
(quoted_attribute_value) @string))
```
Is the original some kind of old fashioned way of doing it?
I experimented with the order and it now seems to make no difference, so I just placed it in the order that made most sense, …
> Update HTML highlights

- languages.toml
- runtime/queries/just/folds.scm
- runtime/queries/just/highlights.scm
- runtime/queries/just/indents.scm
- runtime/queries/just/injections.scm
- runtime/queries/just/locals.scm
- runtime/queries/just/textobjects.scm
In each example below, OLD is **left**, NEW is **right**.
All tests were made with the file https://github.com/poliorcetics/tree-sitter-just/blob/b67d9e6b80d3472f37fff95b884951b327a69f65/examples/all-items.just, on that specific commit
It's my first time writing queries (even just updating some) for tree-sitter so don't hesitate to tell me if I'm doing it wrong!
> just: Use updated grammar with recent language changes and correct highlighting

- helix-vcs/src/diff.rs
- helix-vcs/src/diff/worker.rs
- helix-vcs/src/diff/worker/test.rs
- helix-view/src/gutter.rs
The situation currently is that `render_gutter` builds out a `Vec` of `LineDecoration`s, where `LineDecoration` is a closure. These don't get evaluated until actually rendering, so the `MutexGuard` in `diff_handle.load()` doesn't go out of scope before being accessed again.
This PR does the following:
- Adds the method `try_load() -> Option<Diff>` to `DiffHandle`, using `try_lock` to avoid deadlocks.
- Use said method in `gutter.rs` `diff()`, which will use a blank `GutterFn` instead when met with a locked `Diff`.
Fixes #11027.
> Use `try_lock` in `diff_handle` for Diff gutter

- languages.toml
- runtime/queries/fsharp/highlights.scm
- runtime/queries/fsharp/injections.scm
- runtime/queries/fsharp/locals.scm
The repository reference used here was a fork of the actual repository https://github.com/Nsidorenco/tree-sitter-fsharp, which has now been moved under ionide organization https://github.com/ionide/tree-sitter-fsharp, where it is in active maintenance and development.
The commit SHA is the currently latest commit from main branch.
The injections.scm is copied as is from the fsharp treesitter repo [queries](https://github.com/ionide/tree-sitter-fsharp/blame/main/queries).
The locals.scm is copied from the repo and the capture names are updated to follow the standard names:
- Replace @local.definition.var @local.definition.function, and @local.definition.parameter with @local.definition
- Remove (#set! "definition.function.scope" "parent")
The highlights.scm is copied as well from the …
> Update fsharp tree sitter repo reference

- book/src/install.md
Provides more details on what to do with the runtime directory.
> Provide more details on runtime directory

- book/src/keymap.md
Document bindings discussed in https://github.com/helix-editor/helix/discussions/10976
> Document completion menu bindings

- book/src/generated/lang-support.md
- languages.toml
> Update languages.toml - add nixd

- book/src/generated/lang-support.md
- xtask/src/docgen.rs
Using unique from itertools::Itertools function to clear out and duplicate string entries. Tested on my ARM64 Windows 11 system with mdbook and generated via xtask docgen.
> Deduplicate command names in generated LSP support doc

- book/src/remapping.md
- helix-term/src/commands.rs
- helix-term/src/keymap.rs
Macro key-sequences can be used to implement custom keybinds for commands that require some sort of input like `t` or `mi`:
```toml
[keys.normal]
D = "@t<ret>d"
W = "@miw"
```
To implement them, we parse a sequence of KeyEvents the same way that we parse macro input, then execute them by setting up a callback which passes the KeyEvents through the compositor.
Closes #1383
> Support macro-style keybindings

- helix-core/src/selection.rs
- helix-core/src/transaction.rs
Fixes #5910
Whenever a document is changed helix maps various positions like the
cursor or diagnostics through the `ChangeSet` applied to the document.
Currently, this mapping handles replacements as follows:
* Move position to the left for `Assoc::Before` (start of selection)
* Move position to the right for `Assoc::After` (end of selection)
However, when text is exactly replaced this can produce weird results
where the cursor is moved when it shouldn't. For example if `foo` is
selected and a separate cursor is placed on each character (`s.<ret>`)
and the text is replaced (for example `rx`) then the cursors are moved
to the side instead of remaining in place.
This change adds a special case to the mapping code of replacements:
If the deleted and inserted text have the same (char) length …
> keep (cursor) position when exactly replacing text

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/gherkin/highlights.scm
Add tree-sitter grammar and highlights for the [gherkin language](https://cucumber.io/docs/gherkin/reference/) aka .feature files.
This is what it looks like with the `dracula` theme:
This was requested in https://github.com/helix-editor/helix/issues/3115 but it does not completely solve the issue as this PR does not add the LSP support.
> Add gherkin syntax highlighting

- helix-term/src/commands/typed.rs
`master`
`pr`
I have noticed that this change seems to be common for shell output, so wondering if we should just trim all shell output or keep with the scoped changes?
> refactor(commands): `trim_end` of `sh` output

- runtime/themes/everforest_dark.toml
- runtime/themes/everforest_light.toml
* add background colors to diff gutters and lsp errors/warnings/etc
* stylize v2 picker columns
Hi! I made this changes so that the git diff and lsp warnings are more visible, and the column names of the new picker are differentiated from the data.
> Update everforest themes

- runtime/queries/rust/highlights.scm
A relatively simple change, but I like having the things in the prelude highlighted as builtin types
> Highlight types and enum members in the rust prelude

- runtime/tutor
Previous wording could be understood as the word should be removed, not the selection.
> Clarify lesson 10.1 wording

- flake.nix
Install the shell completion files from `contrib/completion` in the nix flake output.
Allows shell completion without manually copying the files.
> copy shell completion to nix output

- helix-term/src/commands.rs
Usually, when switching between documents, `Editor::switch` is used, but as this adds to the jumplist, the `jump_*` commands have a bespoke way of handling switching. The current implimentation forgot to ensure the view for the document like it does in `switch`:
https://github.com/helix-editor/helix/blob/e2904794749ccc709a238a10e6ee364411c2b820/helix-view/src/editor.rs#L1637-L1639
This PR adds this step.
Fixes #11508
> fix: ensure view is initiated for `jump_*` commands

- runtime/themes/gruvbox.toml
* stylize v2 picker column headers
Doing the same as #11459
> Update gruvbox themes

- helix-view/src/document.rs
Helix panics  when the LSP server sends a diagnostic of severity 0. The nice thing about Helix being so strict in what it accepts, is that it allowed me to find [this clangd bug](https://github.com/clangd/clangd/issues/2124), but as Helix gets more mainstream, it shouldn't panic and throw away unsaved changes just because the LSP server is slightly misbehaving.
> lsp: Gracefully ignore invalid diagnostic severity

- runtime/themes/naysayer.toml
Differentiate primary selection by changing its cursor color.
Before:
After:
> Change primary selection cursor color for naysayer

- helix-lsp-types/src/inline_value.rs
Fixes lints for 1.81.0 rust. This could have been a lint warning for earlier versions, as the lsp-types crate I think was only recently vendored? But this would fix it up till now, regardless.
> fix(clippy): `doc_lazy_continuation`

- languages.toml
Apparently, the Lean process spawned by the language server can use excessive memory in certain situations. Even on very simple code files. That caused my system to freeze. See: https://github.com/leanprover/lean4/issues/5321 . The language server accepts a CLI flag for limiting memory use. I set it to 1024MB, which might be a bit arbitrary, but definitely prevents the system from freezing. The language server seems to respect this limit. So it does not just crash when the limit is reached. Instead it even provides linting, which code lines cause this excessive memory use.
> fix: Lean language server consuming excessive memory

- runtime/themes/horizon-dark.toml
> Stylize horizon-dark picker v2 columns

- runtime/themes/darcula.toml
Before:
After:
Changes based on https://github.com/helix-editor/helix/pull/11477
> Update picker headers styling in Darcula themes

- book/src/generated/lang-support.md
- languages.toml
Ruff provide a `server` command that starts a LSP server:
https://docs.astral.sh/ruff/editors/#language-server-protocol
> chore: add ruff and jedi lsp servers

- runtime/queries/vue/highlights.scm
This is my first "serious" PR request - please, advice as to what to do to get it merged.
It fixes some minor syntax highlighting in Vue.js files.
In the preview you can see the "before" and "after", but there is still work to be done in the <style> part with SCSS, I was just writing queries for the first time today, kind of hard.
Also, when "commenting a line" (`<space-c>`) - it incorrectly infers the type of comment to make. In `.vue` files it always comments as if it is an html, but it has to comment `//` for js/ts and `/* */` for CSS/SCSS. Is that because of the lack of Tree Sitter queries or internal problem?
Thank you
> small fix syntax highlighting in vue.js files

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/circom/highlights.scm
- runtime/queries/circom/locals.scm
This PR adds LSP and tree-sitter support for the zero-knowledge circuit language [Circom](https://docs.circom.io/).
Syntax highlighting was added three days ago in the [tree-sitter-circom](https://github.com/Decurity/tree-sitter-circom/pull/4) repo.
I have tested the changes on my machine with my local helix configuration, but not with the forked helix build. Let me know if I need to test with the forked helix binary as well.
cheers
> add circom tree-sitter, syntax-highlighting, and lsp support

- helix-loader/src/lib.rs
Hey ! 
This PR add support for detecting [Jujutsu VCS](https://github.com/martinvonz/jj) repos as the workspace directory !
Hope it can be integrated into Helix :)
> adding support for jujutsu VCS inside find_workspace resolution

- helix-term/src/ui/document.rs
- helix-term/src/ui/text_decorations.rs
- helix-term/src/ui/text_decorations/diagnostics.rs
When pressing tab at the edge of the screen, Helix panics in debug mode subtracting position.col - self.offset.col.
I don't fully understand the logic here, but if cut_off_start < width, then self.offset.col - position.col < width (from the definition of cut_off_start), and so self.position.col + width > self.offset.col, meaning in_bounds is true and the second condition is currently unreachable.
I believe these conditions should be reversed so that the logic for rendering partially visible characters can apply properly.
> Fix panic when drawing at the edge of the screen.

- languages.toml
Updates the Tree-Sitter grammar to the newest version available in the repository.
The main motivation is to support provider-defined function calls in Terraform, as implemented on the repository in https://github.com/tree-sitter-grammars/tree-sitter-hcl/pull/51
I have tested this locally with my `helix 24.7 (079f5442)` by
1. Changing my own `languages.toml` file to point to the new Git ref
2. Fetching grammars via `hx -g fetch`
3. Building the grammar via `hx -g build`
4. Verifying with a test terraform file that the syntax is displayed correctly again
A simple test file:
```hcl
terraform {
required_providers {
netparse = {
source = "gmeligio/netparse"
version = "0.0.2"
}
}
}
output "testing" {
value = provider::netparse::parse_url("https://test.page/hello?world=true")
}
```
> Update HCL grammar

- languages.toml
Bump the commit to the tree-sitter corresponding to the latest Slint release.
> chore: Update slint tree-sitter grammar to version 1.8

- languages.toml
The `-stdin` in `odinfmt` does not take any arguments, the `true` part here just confuses the formatter, and makes it ignore `odinfmt.json` file.
Removing it fixes the issue.
> Remove "true" from odinfmt line

- languages.toml
`rbs` is a kind of header file for ruby, [introduced with ruby 3.0](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/), similar to rbi files.
More info about [rbs](https://github.com/ruby/rbs)
Adding this file to the default language configuration enables syntax highlight and some features for example by the [steep](https://github.com/soutaro/steep) language server.
Before:
After
> Add .rbs files to ruby language configuration

- languages.toml
- runtime/queries/nickel/highlights.scm
Also updates highlights query to account for changes in let bindings and patterns.
> Bump tree-sitter-nickel to the latest version

- runtime/tutor
It said "split" instead of "swap"
> Fix typo in tutor ch 13.5

- runtime/queries/fish/highlights.scm
Because in helix, queries override from the top, rather than from the bottom, the more special query should be above the non-special query.
Before this PR, all the builtin commands were highlighted as `function`. This is a bug.
Now, they are correctly highlighted as `function.builtin`, because they override the query that is now below.
> fix: fish builtin functions are highlighted as such

- book/src/generated/typable-cmd.md
- helix-core/src/syntax.rs
- helix-term/src/commands/typed.rs
Make unnamed nodes visible in subtree view, to make it easier to debug things related to tree sitter trees.
Before             |  After
:-------------------------:|:-------------------------:
> Improve tree-sitter-subtree

- book/src/keymap.md
Add the keybindings for the following commands to the book:
select_all_siblings
move_parent_node_end
move_parent_node_start
> [Documentation] Add undocumented keybindings to book

- book/src/generated/lang-support.md
- languages.toml
Adds [superthtml](https://github.com/kristoff-it/superhtml) as an lsp option for `html`. It has stricter rules than the html spec, but this can help when hand writing html.
> feat(languages): add `superhtml` as lsp for `html`

- languages.toml
It is now the best spelling and grammar option as `ltex-ls` is slow and uses a lot of RAM, I added a WIKI about it: https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#vale-ls
I don't know why there was no new line at the end of the file before, but Helix adds one.
> Add vale language server

- runtime/themes/gruber-darker.toml
> chore: add "ui.virtual.jump-label" to gruber-darker theme

- book/src/usage.md
Inspired by some questions I've seen in Matrix (e.g., someone who did not know what buffers were despite having used Vim), I think it would be helpful to define some key terms up front to help people know what to search for to learn more.
What I take to distinguish the things I've added here is that they are important concepts, but they don't need such a long explanation that they each should get their own page. At first I was going to make this a separate page for `Key Concepts`, but Usage seems like a good spot and avoids cluttering the sidebar more.
I considered including entries for pickers and commands, but they have their own pages. For commands, I thought the distinction between typable and static commands would be especially worth explaining, but I saw that …
> Add key concepts to `usage.md`

- runtime/themes/bogster.toml
This add two features that have not been added to Bogster from what I can tell:
- A distinct way to show jump labels.
- Primary selection highlight color (see #3842).
Here's a before / after view for the jump labels:
|--------|--------|
| ![Alacritty-2024-07-28-lcCG9dyQ](https://github.com/user-attachments/assets/5ff097db-1839-4e5b-85ac-125e74998917) | ![Alacritty-2024-07-28-WEU4MrWs](https://github.com/user-attachments/assets/babb85dc-2d94-4da8-b786-822e7c01c1cf) |
And here's a before after view for the primary selection highlight:
|--------|--------|
| ![Alacritty-2024-07-28-Ak5ErFFx](https://github.com/user-attachments/assets/98a5e3c7-de7e-42bd-9816-d86903937a20) | ![Alacritty-2024-07-28-E1g8x9jt](https://github.com/user-attachments/assets/72f7f9bf- …
> Small bogster theme improvements

- book/src/generated/lang-support.md
- languages.toml
Adds [ELP](https://whatsapp.github.io/erlang-language-platform/) to Erlang's language configuration.
> Add Erlang Language Platform (ELP) support to Erlang

- runtime/queries/odin/highlights.scm
Some of the odin highlights seemed wrong or lacking, like the import names were not being matched:
```odin
// color both "rl" here to same value
import rl "vendor:raylib"
...
rl.Vector3
```
Import color was also not being used correctly
> Fix some odin highlights

- runtime/themes/onedark.toml
Rust highlight queries make use of `keyword.storage` for keywords like `struct`, `enum`, and also for references, and modifiers like `mut` and `ref`.
Using a color that's different to the one used for `"variable.parameter"` (red) improves differentiation for mutable function arguments.
e.g. 
Before: 
After:
> Add a highlight for the keyword.storage scope to the onedark theme

- languages.toml
- runtime/queries/zig/highlights.scm
this is for: #9458 I started reversing some more queries (only zig for now) and I updated the ron and dockerfile grammars to fix  query-check because they where using new node types, cue has more problems cause we are quite out of sync with the grammar so we should either revert the changes there or fully update to what tree-sitter-neovim is using
> gabydd: reverse query precedence order

- helix-vcs/src/git.rs
- helix-vcs/src/git/test.rs
Currently, if a symlink is opened which points to a file inside a git repo, the git repo is not detected, so there is no diff gutter. This was done because if we used the content of a symlink git object, whose content is a file path, that literal file path would be used as the content of the diff base, producing a diff gutter in the UI that was all additions.
On the other hand, because of this, the git diff gutter doesn't work at all on symlinks.
We work around both of these problems by resolving symlinks before finding the path's git repo.
> fix git repo detection on symlinks

- helix-core/src/uri.rs
- helix-term/src/commands/lsp.rs
- helix-term/src/ui/picker.rs
- helix-view/src/handlers/lsp.rs
The lsp location type has the lsp's URI type and a range. We can replace that with a custom type private to the lsp commands module that uses the core URI type instead.
<details><summary>Note that we can't create a helix-core Location type instead...</summary>
That type would look like:
```rust
pub struct Location {
uri: helix_core::Uri,
range: helix_core::Range,
}
```
But we can't convert every `lsp::Location` to this type because for definitions, references and diagnostics language servers send documents which we haven't opened yet, so we don't have the information to convert an `lsp::Range` (line+col) to a `helix_core::Range` (char indexing).
---
</details>
This cleans up the picker definitions in this file so that they can all use helpers like `jump_to_location` and …
> Replace uses of `lsp::Location` with a custom Location type

- helix-term/src/ui/lsp.rs
If the `active_signature` lies outside the range of `signatures`, it [functionally] defaults to zero. This is inline with the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelp):
>  /**
> \* The active signature. If omitted or the value lies outside the
> \* range of `signatures` the value defaults to zero or is ignored if
> \* the `SignatureHelp` as no signatures.
> */
Fixes #11269
> refactor(lsp): handle out-of-range `active_signature`

- languages.toml
Similar to OCaml and other ML languages, single quote is a normal character that can appear in identifiers and is also used in type parameters. It is not used for strings or character literals, which both use double quote.
> Remove auto-pair for single quote in SML.

- master/package-managers.html
- package-managers.html
- print.html
Repology has renamed the package from `helix` to `helix-editor`. This causes a redirect on the website but the SVG needs an update in order to render. Connects helix-editor#11877
> Fix repology links pt 2

- book/src/package-managers.md
At the moment we have the following, when clicked it does a redirect:
It needs back-porting asap as site is currently broken.
> Update repology URL after change from helix to helix-editor

- book/src/generated/lang-support.md
- languages.toml
Just like #993, I could not get [glslls](https://github.com/svenstaro/glsl-language-server) to work, but [glsl_analyzer](https://github.com/nolanderc/glsl_analyzer) works well.
> Add glsl_analyzer as default language server for GLSL

- book/src/themes.md
Maybe that's the idea, but I think it's better to group similarly named keys together
Also fixed a minor typo in the table formatting
> docs(themes): place `ui.highlight.frameline` and `ui.highlight` together

- flake.lock
- flake.nix
This bumps the dependencies in the flake.lock (updating rust-analyzer for example) and adds the `--cfg tokio_unstable` flag to `RUSTFLAGS` - necessary for running the integration testsuite from the devShell
> Update Nix flake

- languages.toml
Release notes:
- https://github.com/casey/just/releases/tag/1.35.0
- https://github.com/casey/just/releases/tag/1.36.0
Notably, this adds `[private]` attributes on modules, which the current version of the grammar cannot parse,
as well as unicode codepoint escape sequences.
> just: update tree-sitter-grammar to support 1.36.0

- languages.toml
Prettier treats its .prettierrc config file as "JSON or YAML". (https://prettier.io/docs/en/configuration.html)
Because all JSON is valid YAML, it is just YAML. So, Helix should treat it as YAML too.
(not sure what happened at the end of file, it wasn't even formatted well so I had to set-language text to reduce diff)
> Treat .prettierrc as YAML

- languages.toml
This is the [default file name](https://github.com/swiftlang/swift-format/blob/main/Documentation/Configuration.md), and explicitly providing it as an argument causes an error if the file does not exist.
Also, just a QQ: how come some langs have `auto-format` enabled and some dont? Surely all off by default (to be the least annoying) would make more sense? At the least, having all the langs 1 way or the other would be more consistent to me.
> fix: removed explict default config file from swift-format

- runtime/themes/serika-dark.toml
> chore: add "ui.virtual.jump-label" to serika-dark theme

- runtime/tutor
In this pull request I would like to change every instance of 'parenthesis' to 'parentheses' in the tutorial. The tutorial describes jumping or matching between parentheses, so in this context it makes sense to use the plural form, which is 'parentheses'.
P.S. I edited all occurrences of 'parenthesis' simultaneously with helix :).
> Pluralize 'parenthesis' in the tutorial

- book/src/remapping.md
The documentation says that static_commands and TypableCommandList are both found in helix-term/src/commands.rs, however TypableCommandList is actually in helix-term/src/commands/typed.rs. This PR is a simples fix for that.
> Add correct source file for TypableCommandList

- helix-term/src/commands.rs
I often paste and find out that my clipboard didn't have what I expected on it. Previously, undoing the change (`u` in normal mode) would also undo everything else I added in insert mode which is usually too much.
> Save an undo checkpoint before paste in insert mode

- book/src/editor.md
- helix-term/src/commands/typed.rs
- helix-term/src/health.rs
- helix-view/src/clipboard.rs
- helix-view/src/editor.rs
- helix-view/src/register.rs
This change adds the `clipboard-provider` setting to the `editor` section of configuration.
This option can have values of:
- `none` (use an internal buffer) (on windows only)
- `windows` (use native windows clipboard) (on MacOS only)
- `macos` (use pbcopy/pbpaste) (on neiter of the above)
- `wayland`
- `xclip`
- `xsel`
- `win23yank` (for wsl) (on all targets with "term")
- `termux`
- `tmux`
- `term` (osc codes)
- `custom` (see below for the configuration)
Note for a custom provider the configurations should look like:
```toml
[editor.clipboard-provider.config]
copy = ["tee", "test.txt"]
paste = ["cat", "test.txt"]
primary-copy = ["tee", "test-primary.txt"] # optional
primary-copy = ["cat", "test-primary.txt"] # optional
```
This can be configured at runtime with the usual:
```
set …
```
> Add clipboard provider configuration

- languages.toml
- runtime/queries/rescript/highlights.scm
- runtime/queries/rescript/injections.scm
- runtime/queries/rescript/locals.scm
- runtime/queries/rescript/textobjects.scm
The official rescript org tree-sitter repo now includes generated files, helix can depend on it directly.
This MR points to the newest version of the repo, and updates the queries to match the new tree-sitter grammar (coppied from https://github.com/rescript-lang/tree-sitter-rescript/tree/main/queries/rescript)
> update to newest rescript treesitter library and queries

- languages.toml
([link to repo](https://github.com/naclsn/tree-sitter-nasm) for completeness)
> Bump tree-sitter-nasm 

- runtime/queries/nix/injections.scm
This adds syntax highlighting for inline Nim source in Nix files when using
`writers.writeNim` and `writers.writeNimBin`, introduced in nixpkgs in
https://github.com/NixOS/nixpkgs/pull/338857
> queries/nix: add injections for nim writers

- runtime/themes/eiffel.toml
I created a light theme based on the design of an old TextMate theme called Eiffel (itself vaguely modeled after the EiffelStudio IDE). That's the theme I always used with Sublime Text, so I targeted the weird way that Sublime rendered it. 🙂
Please check out the screenshots below and let me know if you think this is polished enough to be merged.
|Normal mode|Visual mode|Insert mode|
|---|---|---|
|![image](https://github.com/user-attachments/assets/ef6c30c8-968f-4aff-9aa4-bbe2bb239dfc)|![image](https://github.com/user-attachments/assets/72813baa-4972-4474-9314-77fa99e3904b)|![image](https://github.com/user-attachments/assets/178b3f60-73ea-4a14-a50d-c59b534d010a)|
> Add new "Eiffel" theme

- runtime/themes/carbonfox.toml
- runtime/themes/licenses/carbonfox.license
#4769 added the original Nightfox theme for EdenEast/nightfox.nvim#213, this adds the [Carbonfox theme](https://github.com/EdenEast/nightfox.nvim?tab=readme-ov-file#carbonfox)
(that image was larger than expected, cropping to the left half seems better for the wiki)
> Add Carbonfox theme

- languages.toml
[Livebook](https://github.com/livebook-dev/livebook) uses a subset of Markdown for its file format, so it is, by default, supported by any Markdown language support/tooling.
> feat(languages): add .livemd Markdown extension

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/unison/highlights.scm
- runtime/queries/unison/indents.scm
- runtime/queries/unison/textobjects.scm
Updates to `2.0.0`: https://github.com/kylegoetz/tree-sitter-unison/blob/master/CHANGELOG.md#200---2024-11-06
> Update Unison grammar and queries

- .gitignore
- languages.toml
Based on [this comment](https://github.com/helix-editor/helix/pull/12052#issuecomment-2473955089) I've disabled the auto-formatting for Swift because there is not a community-wide formatter that's been settled on as the standard yet. There is an ['official'](https://github.com/swiftlang/swift-format) one, but it seems to be rarely used currently and there is [community-built](https://github.com/nicklockwood/SwiftFormat) one that can also be used. Also, Xcode doesnt have formatting built-in, which is very annoying (and the re-indent defaults to 4-space tabbing but the official formatter does 2-space??? anyway). I think it's worth sticking to the official one as the built in, still, but auto-formatting I dont think is the way to go here.
> Swift: disable `auto-format` and added `.swift-format` highlighting

- languages.toml
background:
tsconfig.json allow /* comments */ as well as trailing commas.
issue:
default tsconfig.json generated with tsc --init contains comments, so helix can't handle it correctly.
solution:
treat it as jsonc.
typescript repo has jsonc-parser in devDependencies, so it probably uses jsonc parser internally too. (though I couldn't find relevant code) 
other text editors:
- VS Code treats it as JSON with Comments.
- Zed: https://github.com/zed-industries/zed/issues/14906#ref-pullrequest-2421504857
> fix(languages): treat tsconfig.json as jsonc

- runtime/themes/monokai.toml
Fixes #11866 
Sets monokai (and related themes like molokai) tag color.
Uses same color as vscode monokai theme for tags names = #F92672.
> Set  tags color in monokai theme

- runtime/themes/spacebones_light.toml
I find with this theme currently it is difficult to keep track of which picker item is currently selected.  This should make it clearer.
> Make Spacebones theme picker selection more legible

- languages.toml
The ssh_config format supports a config file fragment inclusion mechanism by using the `Include` directive. Some Linux distros such as Debian, Ubuntu, and distros derived from Debian/Ubuntu specify `Include /etc/ssh/ssh_config.d/*.conf` in their default /etc/ssh/ssh_config config file [0]. Similarly, ssh users can also use this directive in their ~/.ssh/config file, for instance specifying `Include ssh_config.d/*.conf` to include all files matching the glob `~/.ssh/ssh_config.d/*.conf` into their ssh client configuration.
This commit adds the glob `ssh_config.d/*.conf` to the sshclientconfig language so that these config file fragments will be detected.
[0] https://salsa.debian.org/ssh-team/openssh/-/blob/e9f52d3c18a4bb5e2055bcec0cf08abfb137ea2c/debian/patches/debian-config.patch#L126
> languages: Add `ssh_config.d/*.conf` as a glob for sshclientconfig

- languages.toml
Hello,
This PR adds [Doc Comment](https://ziglang.org/documentation/0.13.0/#Doc-Comments) and [Top-Level Doc Comment](https://ziglang.org/documentation/0.13.0/#Top-Level-Doc-Comments) tokens to Zig's `comment-tokens`.
Related PR: #10996.
Thanks
> Update Zig's comment tokens

- helix-core/src/wrap.rs
The the way the `textwrap` crate is configured results in the reflow command utilizing a more sophisticated word separator (`WordSeparator::UnicodeBreakProperties`). As there is currently no mechanism for language-aware reflowing, this approach results in issues like links breaking from their labels in Markdown (#12003). Explicitly using the simpler ASCII space separator addresses this issue and, in my opinion, serves as a better default behavior.
> fix: simplify text reflowing strategy to improve language compatibility

- book/src/generated/lang-support.md
- languages.toml
Adding the hyprls language server as the default one for hyprlang. I'm using it and it works just fine. Currently does not seems to have packages, so I created one for nixpkgs [here](https://github.com/NixOS/nixpkgs/pull/323392).
Edit: it was merged.
Source code: https://github.com/hyprland-community/hyprls
> hyprlang: add hyprls language server

- languages.toml
1. Updated the `file-types` argument in Snakemake language definition to properly detect the language for `Snakefile`.
2. Added a formatter command for Snakemake using `snakefmt`.
> Update Snakemake language config

- book/src/editor.md
- helix-term/src/commands.rs
- helix-view/src/editor.rs
> Add default-yank-register option

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/amber/brackets.scm
- runtime/queries/amber/highlights.scm
A screenshot of [install.ab](https://github.com/amber-lang/amber/blob/master/setup/install.ab):
The query files are from https://github.com/amber-lang/amber-zed/tree/b49e5a877872a7feb321723ca55bbd70f4e376b5/languages/amber.
Closes #12001
> Add support for Amber-lang

- Cargo.lock
- book/src/editor.md
- book/src/languages.md
- helix-core/src/completion.rs
- helix-core/src/lib.rs
- helix-core/src/syntax.rs
- helix-event/src/cancel.rs
- helix-event/src/lib.rs
- helix-stdx/Cargo.toml
- helix-stdx/src/env.rs
- helix-stdx/src/path.rs
- helix-term/src/commands.rs
- helix-term/src/handlers/completion.rs
- helix-term/src/handlers/completion/item.rs
- helix-term/src/handlers/completion/path.rs
- helix-term/src/handlers/completion/resolve.rs
- helix-term/src/handlers/signature_help.rs
- helix-term/src/ui/completion.rs
- helix-term/src/ui/editor.rs
- helix-term/src/ui/menu.rs
- helix-term/src/ui/mod.rs
- helix-view/src/document.rs
- helix-view/src/editor.rs
This PR adds support for path completion.
It supports the following:
* Autocompletion is triggered with `/`.
* Documentation preview (file permissions, canonicalized path).
* shell expansion (e.g. `~/path`, `$HOME/path`, `${HOME}/path`)
* Async (via `spawn_blocking` instead of tokios file accessor functions, as they IMHO make the code less readable and are quite a bit slower than just spawning a "thread")
* Configurable with `editor.path-completion` (default `true`), per-language overrideable path-completion support
* Refactors `goto_file` with a new more robust path-detection/resolution mechanism and also adds shell-expansion.
A baby-step towards #1015
> Add support for path completion

- helix-term/src/handlers/completion/path.rs
```shell
warning: unused variable: `md`
--> helix-term\src\handlers\completion\path.rs:152:23
|
152 | fn path_documentation(md: &fs::Metadata, full_path: &Path, kind: &str) -> String {
|                       ^^ help: if this is intentional, prefix it with an underscore: `_md`
|
= note: `#[warn(unused_variables)]` on by default
```
> fix(clippy): suppress `unused` lint on windows

- helix-term/src/commands.rs
Introduced in https://github.com/helix-editor/helix/commit/dc941d6d24cd4876f75e68487047542239b8316a
> fix: Remove leftover debug println!

- helix-core/src/graphemes.rs
- helix-core/src/indent.rs
- helix-core/src/selection.rs
- helix-core/src/syntax.rs
- helix-core/src/syntax/tree_cursor.rs
- helix-core/src/text_annotations.rs
- helix-core/src/transaction.rs
- helix-lsp-types/src/completion.rs
- helix-lsp/src/jsonrpc.rs
- helix-parsec/src/lib.rs
- helix-term/src/commands.rs
- helix-term/src/compositor.rs
- helix-term/src/ui/menu.rs
- helix-term/src/ui/picker.rs
- helix-term/src/ui/popup.rs
- helix-term/src/ui/prompt.rs
- helix-tui/src/text.rs
- helix-tui/src/widgets/block.rs
- helix-tui/src/widgets/paragraph.rs
- helix-tui/src/widgets/reflow.rs
- helix-tui/src/widgets/table.rs
- helix-view/src/register.rs
- helix-view/src/tree.rs
Lots of lifetime elisions/unneeded lifetime specifiers. Manual implimentation of `div_ceil` changed to the stdlib one. Doc comment block that was not connected to the rest of the block.
> fix(clippy): clippy 1.83 lints

- languages.toml
Tweaks HOCON language configuration to only match `.conf` files located under `src/*/resources/` (usually `main `or `test`). This aligns with the convention in JVM projects, where HOCON is most commonly used. Also adds support for recognizing Scalafmt and Scalafix config files.
Closes  https://github.com/helix-editor/helix/issues/12120
> Fix language configuration for .conf files

- languages.toml
- runtime/queries/just/highlights.scm
Release notes at https://github.com/casey/just/releases/tag/1.37.0
> just: bump grammar support to Just 1.37.0

- runtime/themes/flexoki_dark.toml
- runtime/themes/flexoki_light.toml
simple add for bufferlines to showup on `flexoki_light` and `flexoki_dark`
Light:
Dark:
> add bufferline highlighting for flexoki themes

- runtime/themes/catppuccin_mocha.toml
Before:
After:
This is how it looks like in Neovim Catppuccin aswell.
The other 3 flavors are also updated automatically since they inherit from the one I changed
> fix: catppuccin theme colors for checked and unchecked lists

- helix-term/src/commands/typed.rs
Fixes #6736.
Before when user run :fmt command, but no formatter was available, there was no feedback which was confusing to the users.
> Show an error when formatter is not available

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/teal/folds.scm
- runtime/queries/teal/highlights.scm
- runtime/queries/teal/locals.scm
Add basic support for [Teal language](https://github.com/teal-language/tl).
> The compiler for Teal, a typed dialect of Lua 
Queries and grammar are from [euclidianAce/tree-sitter-teal](https://github.com/euclidianAce/tree-sitter-teal). Language server is [tl/teal-language-server](https://github.com/teal-language/teal-language-server). I couldn't find a proper formatter.
> Add support for Teal language

- helix-term/src/commands/typed.rs
Previously, `:cd` would error if no arguments was given. This PR makes `:cd` behave as expected on unix systems, where it changes to home directory if no args are given
> feat: `:cd` with no args changes to home directory

- helix-term/src/ui/document.rs
- helix-term/src/ui/text_decorations/diagnostics.rs
`set_string_truncated` renders the entire string while ignoring newlines, so if the diagnostic's message contains multiple lines then `draw_eol_diagnostic` produces output like 'first linesecond line'.
An alternative would be to reformat the message to replace newlines with spaces (or something), but I think the first line should be sufficient for end of line diagnostics.
Before:
After:
> Avoid ignoring newlines in multi line messages when rendering end-of-line diagnostics

- helix-term/src/commands.rs
- helix-term/tests/test/commands.rs
- helix-term/tests/test/commands/insert.rs
- helix-term/tests/test/languages/yaml.rs
This is like https://github.com/helix-editor/helix/pull/4854 but works on any trailing whitespace. The fast-lane for an entire line being whitespace (#4854) is kept as-is. The idea is to work well with #10996: you should be able to hit `<ret>` twice when starting on a comment line and the middle commented line should not have trailing whitespace.
For example before:
```rust
//·Comment⏎
//·⏎
//·|⏎
```
after:
```rust
//·Comment⏎
//⏎
//·|⏎
```
This happens to fix the first case mentioned in https://github.com/helix-editor/helix/issues/12165
> Trim all trailing whitespace on insert_newline

- book/src/generated/lang-support.md
- languages.toml
fixes mojo-lsp not working due to [mojo binaries being moved to magic environment](https://docs.modular.com/magic/)
(one could also learn about modular-cli deprecation [here](https://docs.modular.com/mojo/changelog/))
using the current language configuration (mojo command)
```
hx --health mojo
Configured language servers:
✘ mojo-lsp-server: 'mojo-lsp-server' not found in $PATH
Configured debug adapter: None
Configured formatter: mojo
Binary for formatter: 'mojo' not found in $PATH
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```
when updated to `magic` command:
```
hx --health mojo
Configured language servers:
✓ magic: /Users/instable/.modular/bin/magic
Configured debug adapter: None
Configured formatter: magic
Binary for formatter: /Users/instable/.modular/bin/magic …
```
> Fix mojo LSP configuration to conform to magic introduction

- helix-stdx/src/env.rs
- helix-term/src/commands/typed.rs
- helix-term/src/main.rs
- helix-view/src/editor.rs
In https://github.com/helix-editor/helix/pull/12042#pullrequestreview-2480121674 it was suggested to also add `:cd -` to change to the *previous working directory*
- if a previous working directory exists, change to it
- if it doesn't, do nothing. This is the same behaviour as if you open a terminal and write `cd -`, it will not do anything. + displays informational message
> feat: `:cd -` changes to the previous working directory

- helix-view/src/input.rs
> fix: allow to parse "-" as a key code

- book/src/remapping.md
- helix-view/src/input.rs
- helix-view/src/keyboard.rs
Terminals which support the enhanced keyboard protocol send events for keys pressed with the Super modifier (Windows/Linux key or the Command key). We can support keybindings with the Super modifier in Helix with a few small changes: mapping the event from crossterm and parsing/representing the modifier in the KeyEvent string representation.
The binding can be done with `Meta-`, `Win-` or `Cmd-` prefixes - these are all synonymous. For example `keys.normal.Cmd-s = ":write"`.
Closes https://github.com/helix-editor/helix/issues/2913
Closes https://github.com/helix-editor/helix/issues/6582
> Support bindings with the Super (Meta/Cmd/Win) modifier

- helix-term/src/application.rs
- helix-term/src/main.rs
- helix-view/src/editor.rs
When you open two of the same file with `hx README:6 README:8`, it will say `Opened 2 files` even though only 1 file will be opened (with 1 buffer). This PR fixes that, it will say `Opened 1 file` now.
---
The PR also provides context when Helix can't parse a directory as a file. For example, if you do `hx README.md helix-term` helix will think that `helix-term` is a file, and since it's a directory you will see an error message:
```
Error: unable to create new application
Caused by:
expected a path to file, found a directory. (to open a directory pass it as first argument)
```
With this PR the error message is improved now:
```
Error: unable to start Helix
Caused by:
expected a path to file, but found a directory: "/home/e/r/helix/helix-term". (to open a directory pass it as first …
```
> fix: report correct amount of files opened and improved error message when Helix can't parse directory as file

- book/src/editor.md
- helix-term/src/commands.rs
- helix-view/src/editor.rs
This fixes https://github.com/helix-editor/helix/issues/1730#issuecomment-2497839562
@johnbchron may I ask if you could try my PR out? My PR adds the field in the `[editor]` section. Just add a `continue-comment = false` line and you should be good to go.
I'm also wondering if it might be worth it to add a command for this: `:set-continue-comment [true/false]`
> Add config option for continue commenting

- book/src/editor.md
Credits to @jlebon https://github.com/helix-editor/helix/pull/12213#discussion_r1878467459 for finding this.
> doc: fix default value in doc for `continue-comments`

- languages.toml
there are 2 repos for v-analyzer, but one that belongs to v-analyzer (org) is outdated.
- https://github.com/v-analyzer/v-analyzer/
- https://github.com/vlang/v-analyzer/
> languages(v): use vlang/v-analyzer instead of v-analyzer/v-analyzer

- runtime/queries/comment/highlights.scm
```rust
// COMPLIANCE: Specification says that `foo` *MUST* be greater than `bar`.
```
> feat(highlights): add `COMPLIANCE` to `error`

- helix-term/src/ui/prompt.rs
This PR fixed a panic that occurred when pressing <kbd>Ctrl-a</kbd> <kbd>Ctrl-k</kbd> in prompts while a multibyte string was inserted.
Before:
https://github.com/user-attachments/assets/ca6c776c-4f25-4716-bc2e-ef1c8a6a4997
After:
https://github.com/user-attachments/assets/1c5f8d25-441d-43ee-b4df-04088cd28793
> Fix panic in `kill_to_end_of_line` when handling multibyte characters

- languages.toml
Was introduced from https://github.com/helix-editor/helix/pull/12080 since the default comment got changed.
Fixes https://github.com/helix-editor/helix/issues/12265
> language: add comment token for java files

- book/src/remapping.md
Since https://github.com/helix-editor/helix/pull/12191 you no longer need to use `minus`.
Also, I've added a mention that all other keys can be used literally. This is something that I personally didn't get initially as i assumed that keys like `!` require e.g. `exclam` or something like that
> docs: remove mention that `-` requires special handling

- helix-term/src/main.rs
- Although `format!` macro is very powerful, it introduces overhead of memory allocation on the heap compared to `&str`. Therefore, when `format!` macro is unnecessary, we should avoid using it.
> Avoid allocating the `--help` message

- languages.toml
- runtime/queries/dockerfile/highlights.scm
The diff between the two versions is here:
https://github.com/camdencheek/tree-sitter-dockerfile/compare/8ee3a0f7587b2bd8c45c8cb7d28bd414604aec62...087daa20438a6cc01fa5e6fe6906d77c869d19fe
fixes: https://github.com/helix-editor/helix/issues/3166
> dockerfile: bump tree-sitter grammar to gain support for heredocs

- book/src/themes.md
- helix-term/src/commands.rs
- helix-term/src/commands/typed.rs
- helix-term/src/ui/mod.rs
- helix-term/src/ui/prompt.rs
- helix-view/src/graphics.rs
- runtime/themes/catppuccin_mocha.toml
- runtime/themes/dark_plus.toml
- runtime/themes/dracula.toml
- runtime/themes/dracula_at_night.toml
- runtime/themes/github_dark.toml
- runtime/themes/github_light.toml
- runtime/themes/gruvbox.toml
- runtime/themes/material_deep_ocean.toml
- runtime/themes/rose_pine.toml
- runtime/themes/tokyonight.toml
- theme.toml
Currently, directories and files both use the same color. This makes it hard to distinguish between them. This PR adds the ability to pass custom styles to prompt items.
---
This PR adds `ui.text.directory` theme key for many themes. Screenshots of themes' base colors
<details>
<summary>
Screenshots of themes which are inherited from
</summary>
All themes in bullet points will show new colors for directories. 2nd level bullet point themes inherit from 1st level, so I only screenshot 1st level bullet point themes
- `catppuccin_mocha`
- `catppuccin_latte`
- `catppuccin_frappe`
- `catppuccin_macchiato`
- `dark_plus`
- `dracula`
- `dracula_at_night`
- `github_light`
- `github_light_dimmed`
- `github_light_colorblind`
- `github_light_tritanopia`
- `github_light_high_constrast`
- `github_dark` …
> Allow theming directory prompt completions

- runtime/themes/dark_plus.toml
After a @the-mikedavis [comment](https://github.com/helix-editor/helix/discussions/12279#discussioncomment-11600337) I was horrified to learn `dark_plus` had no inactive text theme. I added that and improved the jump label. Before it was set to a background colour when it wants to _jump_ out more, like other themes.
> Update dark_plus theme for inactive text and improve jump label

- helix-term/src/health.rs
Closes #1858.
I can also add a `parser` column to the --health table for all languages, if this looks good.
> Show parser availability in --health [LANG]

- languages.toml
Bump the commit to the tree-sitter corresponding to the latest Slint release.
> chore: Update slint tree-sitter grammar to version 1.9

- book/src/editor.md
- book/src/languages.md
Closes #11592. Use the correct spelling without the first letter as uppercase Specify which values are accepted for diagnostic severity.
Following mike's [recommendation](https://github.com/helix-editor/helix/issues/11592#issuecomment-2323369457)
> Document diagnostic severity levels

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/koto/folds.scm
- runtime/queries/koto/highlights.scm
- runtime/queries/koto/indents.scm
- runtime/queries/koto/injections.scm
- runtime/queries/koto/locals.scm
- runtime/queries/koto/textobjects.scm
This PR adds support for the [Koto](https://koto.dev) language, making use [tree-sitter-koto](https://github.com/koto-lang/tree-sitter-koto) and [koto-ls](https://github.com/koto-lang/koto-ls).
> Add Koto language support

- helix-lsp/src/lib.rs
When a new language server is started, `find_lsp_workspace` is called with `LanguageConfiguration::workspace_lsp_roots` as the `root_dirs` argument.
This behavior is different when a new document is opened. `find_lsp_workspace` is called with `editor::Config::workspace_lsp_roots` which is never set.
This leads to a bug where `workspace-lsp-roots` is not respected when opening a new document. This commit fixes this bug.
I don't quite understand why the field `editor::Config::workspace_lsp_roots` exists when it is never used. Is it something LSP specific?
I'm also happy to change this PR if someone can point me into the right direction if the current fix is wrong.
Thanks a lot!
Closes helix-editor/helix#12222
> fix: Respect workspace-lsp-roots on doc opening

- helix-term/src/commands.rs
> feat: autohelp for delete, replace and add surrounds

- runtime/themes/nightfox.toml
Applies the same text foreground color as nightfox.nvim over directory names (references: [1](https://github.com/EdenEast/nightfox.nvim/blob/7557f26defd093c4e9bc17f28b08403f706f5a44/lua/nightfox/group/editor.lua#L18), [2](https://github.com/EdenEast/nightfox.nvim/blob/7557f26defd093c4e9bc17f28b08403f706f5a44/lua/nightfox/palette/nightfox.lua#L68)).
Current:
Updated:
> feat(themes): add `ui.text.directory` to nightfox

- book/src/package-managers.md
macports requires SUDO to install things.
> docs: Mention sudo in macports installation snippet

- languages.toml
- runtime/queries/jjdescription/injections.scm
https://github.com/jj-vcs/jj/pull/5155
https://github.com/kareigu/tree-sitter-jjdescription/pull/2
Contingent on both of the above landing.
Unsure where these should live. `git-commit` has them in the helix repo, and not the tree-sitter repo. It looks like they need to be inlined into helix to be used in helix (by default), unsure if other projects would benefit from having them in the tree-sitter repo.
> Add diff injections for jjdescription tree-sitter

- flake.nix
- helix-loader/build.rs
Sets new `HELIX_NIX_BUILD_REV` in nix flake builds, with value inserted if `git rev-parse HEAD` fails.
Discussed previously here: https://github.com/helix-editor/helix/issues/1700 (I guess back then neither `self.rev` nor `self.dirtyRev` were available.)
> Make git revision available for nix flake builds

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/tsq/folds.scm
- runtime/queries/tsq/highlights.scm
- runtime/queries/tsq/injections.scm
WIP adding support for tree-sitter query files (scheme-like), using https://github.com/tree-sitter-grammars/tree-sitter-query for the grammar and https://github.com/ribru17/ts_query_ls as the LSP.
> Improve tsq/tree-sitter-query language support

- languages.toml
Only block comment tokens are added because these languages don't support inline comments.
Docs:
- jinja: https://jinja.palletsprojects.com/en/stable/templates/#comments
- nunjucks: https://mozilla.github.io/nunjucks/templating.html#comments
> languages: add block comment tokens for jinja and nunjucks

- languages.toml
correctly highlights the following justfile with injected python
```just
script:
#!/usr/bin/env uv run
import foo
```
> add `uv` shebang for python

- helix-term/src/health.rs
If the terminal has a white background, this makes them invisible.
fixes https://github.com/helix-editor/helix/issues/5516
> fix (hx --health): Don't print headers in white

- languages.toml
Bumping `vento` to the latest revision that fixes a crash on unix. https://github.com/ventojs/tree-sitter-vento/issues/2
> fix: Bump `vento` grammar revision

- helix-lsp/src/jsonrpc.rs
This solves #12367
I'm not particularly familiar with serde, but couldn't find a way of only accepting the trailing suffix ".0". Instead of stripping ".0" this tries to parse the id as a `serde_json::Number` and accepts either a u64 or a f64 with zero fractional parts (.0, .00, .000, etc.).
> LSP Client: Accept floats with trailing zeros as valid JSONRPC IDs

- languages.toml
Previously it was hardcoded to some files, this change will make all hypr/*.conf to use hyprlang.
> Update hyprland langugauge file type.

- book/src/usage.md
I remembered that the updated usage page from #11485 would be moving to the stable site with the next release, so I gave it a skim and found a typo!
> docs: fix typo in usage.md

- CHANGELOG.md
I assume Cwd was meant to be Cmd for Mac.
> Change Cwd to Cmd

- languages.toml
Congrats on 25.01 release! While testing I noticed that Teal LSP wasn't working.
The reason for this is that the Teal LSP name on `language.toml` it's first defined as `teal-language-server` (as the actual command):
https://github.com/helix-editor/helix/blob/dabfb6ceeae1da57fb93efcd254e917db49655e6/languages.toml#L129
However, the Teal language is later configured as `teal-lsp`:
https://github.com/helix-editor/helix/blob/dabfb6ceeae1da57fb93efcd254e917db49655e6/languages.toml#L1319
The fix is done by using `teal-language-server` instead of `teal-lsp`.
> Fix Teal LSP name

- runtime/queries/rust/highlights.scm
> feat: highlight `:` as a delimiter in Rust

- runtime/queries/swift/highlights.scm
- runtime/queries/swift/injections.scm
- Adds injections for the `comment` language
- Correct highlight of the `nil` value. Same highlight as `null` in javascript, java and others
- Recognize `<` and `>` as punctuation, used in generics (same color as the syntax used in other languages)
- `protocol` function methods are recognized
- When accessing object properties, like `hello.world`, the `world` is properly recognized as being a member
- Recognize the `\` as an operator
> feat: correct Swift highlights

- runtime/themes/catppuccin_mocha.toml
After https://github.com/helix-editor/helix/pull/12391#issuecomment-2570053460 , looks like it will be better for people to make their changes in the catppuccin repository rather than here. The changes can be synced time to time
> docs: catppuccin themes should not be directly edited here

- runtime/themes/iceberg-dark.toml
Add cursorline color for iceberg-dark and iceberg-light themes, which were missing when `cursorline = true` is set in the configuration.
> Add cursorline color to iceberg theme

- helix-stdx/src/path.rs
- helix-term/src/commands/typed.rs
- helix-view/src/document.rs
- helix-view/src/editor.rs
`helix_stdx::path::get_relative_path` was always performed for the statusline render. This PR now caches the relative path in `Document` instead. 
(Highlighted in purple: `statusline::render`)
Before:
After:
> perf: cache `Document`s relative path

- runtime/queries/_jsx/highlights.scm
Since JSX attributes are the equivalent of HTML attributes, I see no reason why these shouldn't also use the `@attribute` scope.
> Use `@attribute` scope for JSX attributes

- runtime/queries/markdown/highlights.scm
This PR changes the markdown highlights to apply the `@markup.heading.<n>` (e.g. `@markup.heading.3`) captures to the entire heading - not just the text content, specifically including the marker (`##` part of `## ABC`). I have tested this and can confirm that if the `markup.heading.marker` key is set in the theme configuration, that applies to the headers. If it isn't set, the `@markup.heading.<n>` capture styles apply.
> Improve markdown heading highlights

- helix-view/src/document.rs
Addresses issue https://github.com/helix-editor/helix/discussions/10187
> Run formatter from Document directory

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/codeql/highlights.scm
- runtime/queries/codeql/textobjects.scm
adds [CodeQL](https://codeql.github.com/) support for highlighting, text objects, and LSP!
the treesitter grammer defines the language as just `ql` (thus exporting the function `tree_sitter_ql` in the dylib) but I've never heard it referred by just that, it's always "CodeQL", so I stuck with "codeql" for all user facing names for this language.
For code fences in markdown, github supports this language as `codeql` or `ql`, but again, I don't think anyone refers to this language as just `ql`, so I left the injection-regex as `codeql`.
For the language server, it works as defined, but minimally. Formatting works, goto definition, etc. But to be actually useful, users will probably need to override the args to add `--search-path=P` where P is a path to their local checkout of the [standard …
> language support: CodeQL

- .github/workflows/release.yml
See https://github.com/helix-editor/helix/issues/12411
> pin to `ubuntu-22.04` for releases

- runtime/queries/ecma/highlights.scm
- runtime/queries/haskell/highlights.scm
- runtime/queries/rust/highlights.scm
- [Includes all `Prelude` functions for Rust](https://doc.rust-lang.org/std/prelude/index.html)
- [Includes all `Prelude` functions for Haskell](https://hackage.haskell.org/package/base-4.21.0.0/docs/Prelude.html)
- Includes global functions for JavaScript
> feat(highlights): add more built-in functions for `ecma`, `rust` and `haskell`

- helix-term/src/ui/completion.rs
In https://github.com/helix-editor/helix/pull/12299#issuecomment-2585354083 it was discovered that some LSPs also send additional documentation per LSP color, other than the color's hex code
Since our current approach is to check if the *entire* documentation matches a hex code, this meant the hex code can't be detected
With this PR, we now check against the end of the documentation, which means all LSPs which currently work will continue to work, but LSPs that send extra documentation per-color (like Dart LSP) will work as well.
> fix: unable to detect Color completion item hex code for some LSPs

- languages.toml
[LuaRocks](https://luarocks.org/) is a common Lua package manager.  The metadata file for a LuaRocks package is a Lua file with a `.rockspec` extension.
> add `rockspec` to lua file types

- helix-term/src/commands.rs
- helix-term/tests/test/commands/insert.rs
Fixes https://github.com/helix-editor/helix/issues/12448 and added some tests for them.
TL;DR: I deleted a variable (`offs`) in https://github.com/helix-editor/helix/pull/12215 which I though wouldn't be useful but it was
Sorry for this.
> Fix `open_{below, above}` behaviour with multiple cursors

- runtime/themes/dark_plus.toml
I made some important changes that I hope can get merged before the upcoming patch release :)
1. Color the fuzzy searcher, before there was no color and it was a bad user experience:
I based the choice on the official VS Code theme using the closest available color in the `dark_plus` theme:
I took into account that `special` is also used as syntax and checked the change worked there too.
2. Changed the `ui.text.directory` slightly to a more VS Codish blue vibe:
3. Made `ui.virtual.wrap` the same color as white-space, before it was white and horrible, leaping out when it is meant to be in the background.
> Improve `dark_plus` theme: Change `special`, `ui.text.directory` and `ui.virtual.wrap`

- languages.toml
- runtime/queries/solidity/highlights.scm
- runtime/queries/solidity/locals.scm
- runtime/queries/solidity/textobjects.scm
This PR updates the solidity grammar to the latest version and fixes the queries to work with it.
At the same time, a few improvements were made:
- user-defined types are colored like types also in their definition statement
- identifiers that are SCREAMING_SNAKE_CASE are colored as constants
- add missing keywords: `type`, `transient`, `immutable`
- fixed modifier invocation query
- fix locals query for variable declaration and add constructor scope
- change some textobject queries to use `entry` instead of `parameter` where it makes sense
> chore(solidity): update to newest grammar and fix queries

- helix-stdx/src/env.rs
The regexes in `expand_impl` may match multiple times on a single variable like `${HOME:-$HOME}`: once for the `${HOME:-` part and again for its default value `$HOME`. This could cause a panic because of an invalid slice `&bytes[pos..range.start]`: `pos` is set to `range.end` which corresponds to the closing `}` in the first iteration of the loop, so it's greater than `range.start` in the second iteration.
Fixes #12552
> Fix slicing panic in path completion variable expansion

- helix-term/src/commands.rs
- helix-term/src/ui/editor.rs
- helix-term/tests/test/commands/insert.rs
Fixes https://github.com/helix-editor/helix/issues/12570
> fix: surprising behaviour when changing line above a comment

- languages.toml
Merge commit messages use a different staging file, but should otherwise be treated equally.
> feat: add `MERGE_MSG` file glob for git-commit

- helix-core/src/syntax.rs
This is a rewrite of the `LanguageInjectionMarker` type with two purposes:
* Add a new `LanguageId` variant that can be used to look up languages by `language_id`. This is used instead of `Name` for `(#set! injection.language "lang")`.
* `Name`, `Filename` and `Shebang` variants can all use `RopeSlice` as their inner type and avoid allocations in the common case.
The first change should be the more impactful one: `(#set! injection.language "language-id")` is far more common than capturing `@injection.language`, which is used for things like markdown code fences. Previously we treated both as the `Name` variant meaning that we looked the languages up by the longest matching `injection_regex`. Instead we can lookup by checking equality with the `language_id` field which is much cheaper. …
> Refactor the injection marker type

- helix-core/src/snippets/active.rs
- helix-core/src/snippets/elaborate.rs
- helix-core/src/snippets/parser.rs
This is an alternative approach to https://github.com/helix-editor/helix/pull/12640. Instead of attempting to handle the placeholder text on tabstop `$0` we can simply discard it and log a warning. This should only happen on older versions of `clangd`.
See https://github.com/helix-editor/helix/discussions/12603#discussioncomment-11923324
> Discard placeholder text for tabstop 0

- book/src/generated/lang-support.md
- languages.toml
This pr adds ruby-LSP made by Shopify as candidate for ruby LSP. I noticed that the solargraph lsp is not working for my end, so I decided to use ruby-LSP so it's work very fine.
> add ruby-lsp as candidate for the ruby lsp

- book/src/generated/lang-support.md
- languages.toml
This PR adds [wasm-language-tools](https://github.com/g-plane/wasm-language-tools) as language server for WebAssembly Text Format (wat).
> add language server for wat

- helix-term/src/ui/picker.rs
#4435 added an Alt-Enter keybinding to the file picker that loads the selected file in the background, allowing the user to open multiple files without closing the picker. I assumed the binding wasn't working at all and opened #12413, where I learned that the binding *was* working – it just loads the selected file in the background. Another user there described the same issue, which indicates that I'm not the only one who finds the existing behavior confusing.
Accordingly, this PR changes the behavior of the binding so that the selected file replaces the current file, which provides immediate feedback to the user. I personally find this behavior more intuitive (it's what I originally expected to happen, which is why I assumed the binding wasn't working), and I can't come up with a reason …
> Replace current file when loading in background from picker

- languages.toml
fixed cl-lsp exiting instantly because of wrong arguments: old was "stdio" instead of "--stdio"
> Update languages.toml to fix cl-lsp

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/fish/highlights.scm
* Add [fish-lsp](https://github.com/ndonfris/fish-lsp) as the default language server for fish (disabling popups as helix doesn't yet support them: https://github.com/helix-editor/helix/issues/4699)
* Add [`~/.config/ghostty/config`](https://ghostty.org/docs/config) and [`hgrc`](https://www.mercurial-scm.org/doc/hgrc.5.html) as INI  files
* Bump to latest https://github.com/ram02z/tree-sitter-fish/commit/a78aef9abc395c600c38a037ac779afc7e3cc9e0 and https://github.com/justinmk/tree-sitter-ini/commit/1b0498a89a1a4c0a3705846699f0b0bad887dd04
> Add fish-lsp and ghostty + hgrc file types

- runtime/queries/ecma/injections.scm
> Restrict tagged template language injections for ecma

- languages.toml
- runtime/queries/zig/highlights.scm
- runtime/queries/zig/indents.scm
- runtime/queries/zig/injections.scm
- runtime/queries/zig/textobjects.scm
The previous tree-sitter repo seems to be unmaintained.
Switch to a more maintained tree-sitter repo.
I also fixed the queries: precedences, some helix captures, ...
> Update to more up-to-date zig tree-sitter repo

- helix-term/src/ui/picker.rs
- helix-term/src/ui/prompt.rs
- helix-tui/src/buffer.rs
Fixes #12218
The current prompt does not manage well long inputs:
- It's not possible to navigate at the beginning of the string to modify it
- They aren't correctly scoped to their respective area and leak on other elements (especially on pickers)
I tried to refactor that a bit in order to enhance the user experience on that.
Strings are now scoped to their respective area. Ellipses are placed at the start and/or end of long strings, when needed. A user can them easily navigate through its input, whether using arrows or shortcut like `ctrl+a` or `ctrl+e`.
> fix: better display of prompts on long inputs

- book/src/generated/static-cmd.md
- helix-term/src/commands.rs
- helix-term/src/keymap/default.rs
- helix-term/src/ui/mod.rs
- helix-term/src/ui/picker.rs
This is a minimal implementation of the file browser, which would probably cover a lot of requirements in #200. The whole thing works analogous to the https://github.com/nvim-telescope/telescope-file-browser.nvim as suggested in [this comment](https://github.com/helix-editor/helix/issues/200#issuecomment-1340815804). Even though the resolution of the discussion seems to be "file tree/browser is too hard, it should be implemented as a plugin", I feel like my changes are quite small and natural to be considered for adding to the core nonetheless.
The implementation simply builds on the existing file picker and only modifies 3 files, so the added maintenance burden should be quite small. The code itself is not particularly elegant (in my rather inexperienced opinion), but I did not want to …
> Add file browser

- helix-core/src/syntax.rs
Previously, there would always be a `Regex::find` that would take place, even if the name perfectly matches an id(`name` in the `language.toml`). This PR introduces a short-circuit opportunity, to check if the name matches the id, as regex is much more expensive and shouldn't be done unless as a fallback, especially when the most often case appears to be an exact match.
The workload here was to go into `helix-term::commands::typed.rs`, and at the start of the file, enter insert mode, and hold enter to insert newlines until it reaches line ~1000. This is artificial, but it shows the point well. In just this operation, it accounted for 16% of samples. After, 0.5%.
Before:
After:
> perf(syntax): short-circuit if name matches `language_id`

- book/src/generated/typable-cmd.md
- helix-lsp/src/lib.rs
- helix-term/src/commands/typed.rs
- helix-term/src/ui/mod.rs
also comes with completion for language servers:
Closes https://github.com/helix-editor/helix/issues/12569
> feat: specify custom lang server(s) for `:lsp-stop` and `:lsp-restart`

- helix-term/src/commands.rs
> fix: `goto_file_impl` incorrect use of `slice` instead of `byte_slice`

- helix-term/src/commands/typed.rs
I often forget that `:{,r}sort` only does something with multiple selections, and not 1. This commit will print a helpful suggestion to the user when `:{,r}sort` is called with one selection that spans more than 1 line, to first do `split_selection_on_newline`.
> feat: print helpful suggestion when using `:{,r}sort` incorrectly

- runtime/queries/zig/highlights.scm
this fixes zig highlighting of identefiers, before this they where highlighted as ``@type``
> fix zig highlight query use of #lua-match

- helix-view/src/clipboard.rs
- helix-view/src/graphics.rs
Previously failed to compile when `features = []`
> Properly prevent `crossterm` features being used when `feature = "term"` not enabled in `helix-view`

- helix-term/src/compositor.rs
- helix-term/tests/test/commands.rs
Fixes #12697 by not recording key presses of macros replayed while recording a macro. This results in the macro in the `@` register in the issue's reproduction example being `"aqi<space>world<esc>` instead of `"aqihello<esc>i<space>world<esc>`.
> Do not record keys pressed by macros while recording a macro

- Cargo.toml
- helix-core/Cargo.toml
- helix-stdx/Cargo.toml
Per the `ropey` [docs](https://docs.rs/ropey/latest/ropey/#a-note-about-simd-acceleration):
> Ropey has a `simd` feature flag (enabled by default) that enables explicit SIMD on supported platforms to improve performance.
> 
> There is a bit of a footgun here: if you disable default features to configure line break behavior (as per the section above) then SIMD will also get disabled, and performance will suffer. So be careful to explicitly re-enable the `simd` feature flag (if desired) when doing that.
This also matches `helix-core`.
> perf(ropey): enable `simd` feature for `stdx`

- languages.toml
there was a PR which changed the default comment token from `//` to `#`. Since svelte didn't have a token set, its comment token was changed to `#`
> fix: add comment token for svelte files

- helix-core/src/doc_formatter/test.rs
- helix-core/src/graphemes.rs
Currently, a grapheme is classified as a "word boundary" if any codepoint in the grapheme is non-alphanumeric. This doesn't work for combining accent characters, like e\u{0301} which renders as é and should usually be considered part of a word for English words like Éclair.
I think the correct behavior here is to only inspect the first code point in the grapheme cluster, based on this recommendation from the Unicode line breaking algorithm: "give each grapheme cluster the line breaking class of its first code point"
https://www.unicode.org/reports/tr14/#Examples
Fixes #12482
> Use the first char in a grapheme for classification

- languages.toml
Just opened the configuration file of [Sublime Merge](https://www.sublimemerge.com/) which has the file extension `.sublime-settings` and is encoded as json. I was a bit annoyed that helix did not recognize the extension. This PR add `file-types` entries to detect the various files used by Sublime Text and Sublime Merge.
> Recognize `.sublime-*` files

- runtime/queries/ecma/injections.scm
See https://github.com/helix-editor/helix/pull/12217#issuecomment-2572394677. Supports highlighting `$` template literals as shell commands, as commonly done in [execa](https://github.com/sindresorhus/execa), [zx](https://github.com/google/zx), and [bun](https://bun.sh/docs/runtime/shell).
| --- | --- |
| ![CleanShot 2025-02-01 at 18 54 36](https://github.com/user-attachments/assets/2564a9f1-4455-4857-b90b-2eaf1b5e533d) | ![CleanShot 2025-02-01 at 18 54 29](https://github.com/user-attachments/assets/0e40cd33-4e5b-42ec-8fbe-576376cb873e) |
> Highlight $ template literals as shell commands

- docs/CONTRIBUTING.md
Without this, people who rely on the rust-analyzer version provided by rustup have to install it manually to work on helix.
> Document installation of rust-analyzer via rustup

- languages.toml
Adds another comment token for a very common documentation header style used in the R language, see example from [`dplyr::mutate()`](https://github.com/tidyverse/dplyr/blob/fb25640fa1eb74746a7a74a06090045106e5d20f/R/mutate.R#L1-L7)
> feat(lang:r): Add roxygen header comment token

- helix-core/src/syntax.rs
As per the documentation in `anyhow`: https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations to print the full error, one should use `{:#}`. 
This helped me debug an error where a .so file would fail to load for a treesitter grammar by giving more information on the error so I'd figured I'd open a PR so that it might help others.
I didn't write a test because I'm not very familiar with the helix code and test structure but if you'd like one, please give some suggestion on how to implement it and I will 😄
> Print full error chain when failing to load grammar

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/tera/highlights.scm
- runtime/queries/tera/injections.scm
- runtime/queries/tera/locals.scm
Adds support for the [Tera](https://keats.github.io/tera/) templating language, using my grammar https://github.com/uncenter/tree-sitter-tera. This only highlights the template tag logic and not the content around the template tags, but I plan to do that in the future by adding multiple `tera-` languages if I am allowed to do so - see https://github.com/uncenter/zed-tera/tree/main/languages for what I mean.
Closes https://github.com/helix-editor/helix/issues/6277.
> Add Tera templating language support

- book/src/generated/lang-support.md
- runtime/queries/typst/symbols.scm
I added symbols for typst (alternative to latex). IMO there should be symbols for markup, in this case `heading` and `link/tag/reference`.
> typst: add symbols query

- runtime/themes/gruber-darker.toml
This matches the highlights used for directories in the "upstream" Emacs theme, e.g. here: https://github.com/rexim/gruber-darker-theme/blob/2e9f99c41fe8ef0557e9ea0f3b94ef50c68b5557/gruber-darker-theme.el#L143
> feat(themes): add `ui.text.directory` to gruber-darker

- languages.toml
Asked for in poliorcetics/tree-sitter-just#3
> just: bump grammar support to handle more kind of shebang injections

- contrib/completion/hx.bash
Once fixed in #9708, PR #11246 accidentally introduces a regression that breaks bash completion with space in filename (The `IFS=$'\n'` is removed).
Instead of setting `IFS`, this PR uses an alternative `mapfile` approach, as suggested by ShellCheck [SC2207](https://www.shellcheck.net/wiki/SC2207).
> Fix Bash completion space regression

- runtime/queries/nix/injections.scm
Adds missing injection queries for ["writers"](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/writers/scripts.nix) in [nixpkgs](https://github.com/NixOS/nixpkgs).
The list of writers are taken from reading the attrset keys of `pkgs.writers.write*` in the current release of nix `nix --version` 2.24.11
> feat: add mising pkgs.writers.write* nix tree-sitter injections

- book/src/generated/lang-support.md
- runtime/queries/nix/indents.scm
Crawled through the nix grammar definition and through other indent queries.
I am not sure that it covers 100% of the language but should work good enough in hybrid mode.
> nix: add indent TS query

- helix-term/src/ui/markdown.rs
this PR makes Markdown highlights use the same scopes as what Tree Sitter uses:
- Horizontal rule uses `punctuation.special`
- Numbered lists use `markup.list.numbered`
- Unnumbered lists use `markup.list.unnumbered`
Also, has cosmetic improvements:
- Use `•` for bullet points instead of `-`
- Use `───` for rule instead of `---`
> fix: Align `Markdown` styles with tree sitter highlights

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/djot/highlights.scm
- runtime/queries/djot/injections.scm
This change adds support for the Djot markup language. The grammar used is [tree-sitter-djot](https://github.com/treeman/tree-sitter-djot) and the highlights & injections have been adapted for Helix's scopes.
There are 4 highlight queries with TEMP comments above them as they are semantically significant but I don't feel they have appropriate existing scopes.
In preparation for #9458 I will be maintaining a version with inverse precedence.
Closes #12264
Closes treeman/tree-sitter-djot#10
> Add Djot support

- languages.toml
Another XML file in disguise.
e.g. https://github.com/docbook/xslt10-stylesheets/blob/master/xsl/manpages/docbook.xsl
> mark xsl files as XML

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/ink/highlights.scm
Add support for [ink by inkle](http://github.com/inkle/ink). I have currently implemented basic syntax highlighting.
- Since ink is a language for interactive fiction we use soft-wrap. The inky IDE also uses soft-wrap. This is what users expect.
- Since ink is more a markup language and language constructs (knot, stitch, weave, gather, glue) are very different to traditional programming languages, I look the highlighting-types in highlights.scm that give a good visual impression
- This uses my [tree-sitter-ink](https://github.com/rhizoome/tree-sitter-ink) parser, to my knowledge there is no other tree-sitter parser for ink
- I made this because inky does not properly support unicode and I took special care to support it well
> feat: Add support for the Ink programming language

- runtime/themes/cyan_light.toml
> Cyan Theme : fix popup not having any background

- runtime/queries/rust/highlights.scm
Uses `punctuation.special`. I think this scope is fitting here.
note: Some usages of metavariables aren't highlighted. I thought it was an issue with precedence but that doesn't seem to be the caes. I assume this is a bug in the highlighter? (See `$key`)
> feat: highlight rust repetition pattern

- runtime/themes/onedarker.toml
Previously `ui.cursorline.primary`
(`light-black`)/`ui.selection.primary` (`gray`) and `ui.selection` (`light-gray`)/`comment` (`light-gray`) had little or no contrast. `ui.cursorline.primary` is changed to a new darker color, `dark-black` and `ui.selection` is set to use `reversed`.
After playing with the example solution in #12579 I decided to go with one that keeps the gray hue for selections and only requires adding one new color to the palette. The change also supports 256-color mode.
24-bit color:
256-color:
> Improve `onedarker` theme contrast `cursorline`/`selection`

- runtime/themes/github_light.toml
Improve jump label colors as per issue (#12904)
The "reversed" modifier seems to provide a better visibility.
The screenshot below demonstrates the before-and-after result of this fix.
Kindly approve these changes and accept the pull request as this theme is very important to many users.
Yours faithfully
~oxcrow
> Improve jump label colors for `github_light` theme

- helix-term/src/commands.rs
- helix-term/src/ui/picker.rs
When yanking to the search register with `*`, percent signs are used verbatim, which messes with the picker column filter.
> fix: escape percent character when yanking to search register

- helix-term/src/commands/lsp.rs
This (experiment) adds the container name of a symbol to the picker as well. The intention is to be able to navigate to various implementations of a method for example, if there's multiple classes in the same file.
Note: I have no clue what I'm doing, so consider this more as an "enhanced feature request". It seems to work just fine for me though, so any feedback is appreciated.
I've also thought about joining the container and name together into one column, but that's difficult if you're trying to respect language specific symbol separators (`::` in C++, `.` in JS, Python etc, ...) so I've figured I'd rather have a separate column.
Maybe even better would be to have the column selection configurable, as it may not make sense for some languages, and may take away quite a bit of room in …
> feat(lsp): add container name as a column in the symbol pickers

- book/src/generated/lang-support.md
- languages.toml
- [bufls](https://github.com/bufbuild/buf-language-server) is deprecated, removed
- [buf lsp](https://buf.build/docs/reference/cli/buf/beta/lsp/) is current verison of `bufls`
- [protols](https://github.com/coder3101/protols) is another implement
> feat(lsp): add protobuf language servers

- languages.toml
* Change SConstruct, as many times in scons projects you end up with test.SConstruct, gmock.SConstruct, mock.SConstruct
* Change SConscript, as many times in scons projects you end up with test.SConscript, gmock.SConscript, mock.SConscript
* Add sconstruct, as this is epcifically called out in the manual:
> By default, scons searches for a file named SConstruct, Sconstruct, or sconstruct (in that order)
in the current directory and reads its configuration from the first file found. An alternate file name may be specified via the -f option.
> Accept more scons as python language

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/mail/highlights.scm
- runtime/queries/mail/textobjects.scm
This PR adds `mail` language support to Helix. It includes a tree-sitter grammar, highlight queries, and textobject queries. I've updated the documentation and tested it extensively.
> feat: language support for mail files

- runtime/queries/toml/textobjects.scm
This PR adds `comment` text object support to TOML. Being able to select comments with `]c` and `[c` is a big quality of life improvement.
> feat: added comment textobject to toml

- languages.toml
This PR configures [kdlfmt](https://github.com/hougesen/kdlfmt), which can easily be installed with `cargo install`, as the default formatter for `kdl` files.
> feat(kdl): add `kdlfmt` as formatter for kdl

- runtime/queries/css/highlights.scm
I saw that some highlighting was missing in my CSS files. 
I added the missing scopes (or nodes? idk how to call them) but I don't know what proper color for them would be, so please, advice me regarding the changes to make.
For now, for demonstration purposes, I added them as keywords.
Before:
After:
Also, right now we have these queries
```
[
"and"
"not"
"only"
"or"
] @keyword.operator
```
Which incorrectly capture things inside `::part()` selector, inside of which can be any label (used to access elements inside Shadow-DOM). But as I understood it requires some changes to the C parser, and I have never written C or Parser/lexer so I cannot fix it... I will just notify whoever can fix it 
And one more question, is there any way to copy/dump the tree-sitter tree, similar to #12208? That …
> Added missing CSS highlight Tree Sitter Scopes

- helix-term/src/commands.rs
This PR:
- Styles directory segments with `ui.text.directory` for consistency with the rest of the editor (as well as readability: it is easier now to tell the filename of each entry apart from its path)
- Applies `constant.numeric` to the line number and `:` to the colon. This also has the advantage that it's easier to tell apart a filename ending with a colon / number from the actual line number
> feat: Improve look of Global Search Picker

- helix-term/src/commands.rs
previously it would allocate a Vec for every single char it would try to switch_case for, even when the case did not actually change, which is not necessary.
> remove unnecessary allocations in switch_case

- helix-core/src/command_line.rs
- helix-term/tests/test/command_line.rs
https://github.com/helix-editor/helix/issues/12999
This improves the error message if "%" is not escaped as "%%" as in the test.
> Improve %% escaping error message

- runtime/themes/beans.toml
This adds the `beans` theme. Based on jellybeans, with some improvements for higher contrast and better support for multiple cursors and selections so the primary can be easily identified.
Add the beans theme, based on jellybeans but modified for better highlighting of multiple cursors and selections.
> Add beans theme

- default.nix
- flake.lock
- flake.nix
- grammars.nix
Hello. It has been a while since #11528. I am better at Nix, so I decided to take a crack at cleaning the flake up. 
My main issues with it is that it was not setup to be very customizable. Also the Cachix cache is nearly useless since it is compiled with `target-cpu=native`, so the cache will nearly always be missed. So I refactored it and added some comments.
1. ~~I am unconvinced it needs all the source filtering.~~
2. By default everything uses the MSRV compiler as that is a safe default.
3. Cleaned up a few vestigial things that my guess is were left from earlier revisions
I did preserve the behavior that the devshell will compile with `target-cpu=native` and other flags. But now the Cachix cache is actually possible to hit.
You can see an example of it in use in my NixOS config …
> Clean up Nix Flake & make it easier to customize

- default.nix
- flake.nix
The git hash is not added properly. When I copy and pasted to a new file it referenced `self`, but this new `self` is the derivation so there is no `rev` or `dirtyRev` attrs, leading to it always being null. This fixes that. 
I also expanded the comment about overriding.
> Follow-up to #12831, fix the git hash

- languages.toml
This PR adds the `harper-ls` LSP configuration. It doesn't add it to any language by default, but now to use Harper, users just need to install it to their path and add it to the `language-servers` array for the language they want.
_Note:_ I edited this PR description to reflect the changes discussed in the conversation below. The PR is now ready for review.
> feat: add `harper-ls` LSP configuration 

- book/src/generated/lang-support.md
- languages.toml
The binary name was changed in wgsl-analyzer commit [4c56b1435d30cd45d8aee52297bbf68ed5bb3beb](https://github.com/wgsl-analyzer/wgsl-analyzer/commit/4c56b1435d30cd45d8aee52297bbf68ed5bb3beb) and released in [0.9.7](https://github.com/wgsl-analyzer/wgsl-analyzer/releases/tag/v0.9.7).
I updated my [AUR packages](https://aur.archlinux.org/packages/wgsl-analyzer) to use the new executable name. Please let me know if there are problems with this change!
> languages.toml: Change wgsl_analyzer to wgsl-analyzer

- book/src/install.md
Added a link to the package managers page.
If you're in the habit of hyperactively skim-reading documentation, the fact that there's a totally separate page with package manager details (including the ubuntu PPA etc) is easy to miss. This PR makes it more explicit that this where you probably need to go.
> Update install instructions

- languages.toml
The `ini` tree-sitter parser was just updated to fix an issue where global parameters were preventing the entire file from being highlighted properly. This PR bumps the version that `languages.toml` points to for the grammar to include this fix. Please see the issue below for more details.
https://github.com/justinmk/tree-sitter-ini/issues/14
> feat(ini): bumped grammar version to include support for global parameters

- languages.toml
- runtime/queries/vhdl/highlights.scm
Hi, @jpt13653903 has created and maintained a vhdl tree-sitter, which has been merged with neovim-treesitter for some time now, see https://github.com/nvim-treesitter/nvim-treesitter/pull/6925
We have used it successfully for many months now. To make it short, I think it's time to get merged here as well!
There were some fundamental problems with the currently used (fork of) https://github.com/alemuller/tree-sitter-vhdl , mainly because it is no longer maintained, see https://github.com/nvim-treesitter/nvim-treesitter/discussions/6701#discussioncomment-9589203
Anyway, let me know if anything is missing.
> update vhdl tree-sitter

- helix-term/src/application.rs
if `config.toml` either does not have `editor.true-color` or sets it to false, many (most?) themes stop being usable. when loading such a theme, Helix falls back to the default theme, but didn't mention this anywhere - even in `~/.cache/helix/helix.log` when run with `-v`.
if this occurs when reloading a theme at runtime with `:theme`, there's a fairly helpful error about
> `theme requires true color support`
seems worth logging about this if it happens during startup too.
i didn't see an obvious place to include a test about this, but this log shows up in my `~/.cache/helix/helix.log` in the cases i was very confused about this afternoon, and is no longer logged when i set `true-color = true` :)
> warn when configured theme is unusable for color reasons

- languages.toml
- runtime/queries/openscad/highlights.scm
References https://github.com/Leathong/openscad-LSP/issues/35
tree-sitter-openscad has moved to the https://github.com/openscad org where the NPM package, crate, and python lib are pushed from. This PR updates the grammar location for openscad to point to https://github.com/openscad/tree-sitter-openscad/
> chore: Point OpenSCAD grammar to official repo

- runtime/queries/ruby/highlights.scm
A few things were no longer highlighted correctly with the highlight precedence changes in #9458:
* Some control keywords (such as `require` or `raise`) were highlighted as regular function calls
* Builtin functions (such as `include` or `attr_accessor`) were highlighted as regular function calls
* Constants were highlighted as constructors
* Local variables were not distinguished from other variables or function calls
I'm not very familiar with the syntax myself, but as the goal of #9458 was to reverse the precedence ordering, my strategy was to rearrange the higher-level groups (Keywords, Function calls, Function definitions, Identifiers, Literals, Operators) so they were fully reversed from what they were in `25.01.1`, then identify any remaining mismatches resulting from conflicts …
> Fix Ruby highlights

- languages.toml
This is useful for maintaining syntax highlighting when editing git config files which have been included via `include` or `includeIf`.
> languages: Also include `gitconfig` as an extension

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/markdown-rustdoc/highlights.scm
- runtime/queries/markdown-rustdoc/injections.scm
- runtime/queries/rust/injections.scm
This PR is described in https://github.com/helix-editor/helix/pull/12972#issuecomment-2725719482
> `tree-house`: Inject `rust` language into documentation comments when the language is not specified

- languages.toml
> ### [:link: Generating Amber Documentation](https://docs.amber-lang.com/0.4.0-alpha/getting_started/usage#generating-amber-documentation)
> 
> The following command extracts comments prefixed with `///` (triple slashes) from a single Amber file, and generates a Markdown file for documentation, by default in the `docs` subdirectory:
> ```sh
> $ amber docs stdlib.ab
> ```
> (https://github.com/amber-lang/amber-docs/blob/dee443f7b67f4b014a4dec307ab0aef6b584e943/docs/0.4.0-alpha/getting_started/usage.md?plain=1#L110-L116)
I missed this at my last PR.
> Add '///' to Amber comment-token configuration

- helix-stdx/tests/path.rs
- helix-view/src/document.rs
pretty straightforward, the title says it all, just a simple spelling issue.
> fix: adjust spelling of simlink->symlink

- runtime/queries/scheme/highlights.scm
in a few scheme dialects `λ` and `lambda` behave the same, but the tree-sitter highlight to highlight the first argument of `lambda` as a variable instead of a `function` was only added for the `lambda` keyword. this also adds that for `λ`.
before:
after:
(note: i am using a custom version of the solarized light theme where variables are blue and functions are violet)
(note: the "after" image was taken with the tree-house branch, as it didn't work otherwise)
> queries(scheme): consider the first argument of λ to be a variable as well

- helix-term/src/commands/lsp.rs
When requesting code actions from multiple LSP servers, rather than bailing as soon as an error is encountered, instead log the error and then keep going so that successful requests can be presented to the user.
I encountered this while using `harper-ls` alongside `rust-analyzer` in Rust files, and sometimes harper starts erroring in complex documents, and it was confusing to suddenly no longer have Rust code actions available.
> Show successfully requested code actions after a failed request

- helix-vcs/src/diff/worker.rs
In my custom branch I remove the `rust-toolchain.toml` and this is now triggering `clippy`.
> chore(worker): remove unused lifetime on `EventAccumulator`

- book/src/editor.md
- helix-core/src/editor_config.rs
- helix-core/src/lib.rs
- helix-term/src/commands/typed.rs
- helix-view/src/document.rs
- helix-view/src/editor.rs
This adds support for EditorConfig to the core. This aims to be as minimal and direct of an integration as possible. This configures matching documents':
* indent style (`indent_size` + `indent_style` + `tab_width`)
* line ending (`end_of_line`)
* encoding (`charset`)
* whether to add a trailing line ending is added on save (`insert_final_newline`)
* whether to trim trailing whitespace on save (`trim_trailing_whitespace`)
* text-width (`max_line_length`)
`spelling_language` is left for future work.
Closes #279
Closes #1777
> Support EditorConfig

- helix-loader/src/grammar.rs
Even though there is a check for `is_like_msvc`, when setting the `CXX`  environment variable to `clang++`, this will miss that check and try to use `-fPIC`, which is an invalid flag for the target.
> build(grammar): remove `-fPIC` flag from windows build

- runtime/themes/adwaita-light.toml
I just copied the change from commit 5fac4b610eef700d22e2323bca7b4ca7e841db94 to the Adwaita Light theme.
Before on the left and after on the right.
Screenshot is Ghostty with the Adwaita theme, but GNOME Terminal shows the same before and after.
> Make `goto_word` highlights visible for Adwaita Light (same fix as #12904)

- helix-term/src/commands/typed.rs
Updates the signature for the command to take 0 arguments. This probably regressed during 0efa8207d86d39f9bdd54e72117ae9c8817e2cc6.
> Allow `:theme` to show current theme

- runtime/themes/earl_grey.toml
Minimal color scheme which tries to accentuate only main structural elements.
Functions are most important, then only types/keywords are accented.
|TypeScript|Rust|Go|
|-|-|-|
|![earl_grey_ts](https://github.com/user-attachments/assets/96ed8ec0-4cd1-42f5-9754-4512496b3eeb)|![early_grey_rust](https://github.com/user-attachments/assets/5dd38fb9-ea22-4fbd-9913-5f5b1a53e8e8)|![earl_grey_go](https://github.com/user-attachments/assets/10afd11e-af09-475b-956d-36c700d7225a)|
> Add earl_grey theme

- languages.toml
This PR makes `.tmTheme` files recognized as the `xml` filetype. Note that `.tmtheme` and `.tmTheme` are both valid.
> feat: add tmTheme as XML filetype

- languages.toml
Hello there 👋 
golangci-lint as made an [update to its v2](https://golangci-lint.run/product/changelog/#v200), which break command line arguments needed to be pass in order to work correctly in helix (or any editor I presume). This PR correct this command. I'm just wondering when it will be a good time to make it default.
PS: That my first PR, I'm sorry if its not up to standard. Its also the first occasion for me to thanks everyone who work on Helix for this great piece of software !
> Update golangci-lint command for v2

- helix-lsp/src/lib.rs
- helix-term/src/application.rs
The title supplied in the initial progress begin message is a more human understandable marker than the progress token which for metals at least is a UUID and not intended for human consumption.
> Track progress title an display in place of internal token

- helix-term/src/keymap/macros.rs
`KeyTrie::Sequence` takes a `Vec<MappableCommand>`, not any `Command`.
```rust
pub enum KeyTrie {
MappableCommand(MappableCommand),
Sequence(Vec<MappableCommand>),
Node(KeyTrieNode),
}
```
> fix(keymap): point to proper `MappableCommand` instead of `Command`

- runtime/themes/tokyonight.toml
Fixes #13215 
Previous issues: #5961 and pr #6009. I think that since this seems to affect multiple themes, there should be some lint for this (if possible). It probably affects other themes as well, I haven't checked.
Also, I'm not sure if removing the `bg` field from `"ui.text"` would cause problems elsewhere. I essentially copied the change from #6009 into tokyonight.
> Remove bg from tokyonight text

- runtime/themes/peachpuff.toml
Porting of the famous Vim's `Peachpuff` theme to Helix
<p>
<div>
Rust
</div>
</p>
<p>
<div>
Python
</div>
</p>
> Add peachpuff theme

- contrib/Helix.desktop
I was grouping apps based on categories and noticed that desktop entry file is missing ConsoleOnly in categories. So I have just added that.
Thanks!
> feat: add ConsoleOnly to desktop entry categories

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/prolog/folds.scm
- runtime/queries/prolog/highlights.scm
- runtime/queries/prolog/indents.scm
- runtime/queries/prolog/injections.scm
This PR adds a tree-sitter grammar for Prolog. It uses https://codeberg.org/foxy/tree-sitter-prolog, a fork/rewrite of https://github.com/Rukiza/tree-sitter-prolog.
I've probably made a mistake in how the `runtime/queries/prolog/*` files should be done, sorry about that! The changes in this PR seem to be working for me, though I'd appreciate it if others could try it out and ensure it works for them.
> Add Prolog tree-sitter grammar

- runtime/queries/ada/highlights.scm
Accidentally found a typo in capture group for `queries/ada`, and removed a duplicate query
> Fix  typo in ada queries

- helix-core/src/test.rs
- helix-lsp/src/client.rs
- helix-term/src/ui/prompt.rs
- helix-view/src/document.rs
- helix-view/src/register.rs
In particular, for the [`next_back`](https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last) change:
> `Iterator::last` is implemented by consuming the iterator, which is unnecessary if the iterator is a `DoubleEndedIterator`. Since Rust traits do not allow specialization, `Iterator::last` cannot be optimized for `DoubleEndedIterator`.
> fix(lints): clippy 1.86

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/debian/highlights.scm
Thanks for Helix! Would love colors for Debian metadata as I'm reading them often.
File format described at https://www.debian.org/doc/debian-policy/ch-controlfields.html
The grammar is pretty basic at the moment but I'm hoping to add specific AST nodes for things like version specifiers at some point.
> Debian control file syntax highlighting

- languages.toml
Hi,
The Mint language now keeps the lsp server under the `tool` subcommand.
This PR updates the mint lsp command args to reflect this change.
https://mint-lang.com/guides/cli/tool-ls
>  Update mint lsp command args 

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/wesl/highlights.scm
- runtime/queries/wesl/injections.scm
- runtime/queries/wesl/locals.scm
- runtime/queries/wesl/textobjects.scm
Adds [WESL](https://wesl-lang.dev) as a supported language following the instructions [here](https://docs.helix-editor.com/guides/adding_languages.html). The queries are copied from [here](https://github.com/wgsl-tooling-wg/tree-sitter-wesl/tree/94ee6122680ef8ce2173853ca7c99f7aaeeda8ce/queries).
> Add WESL language

- helix-loader/src/config.rs
- helix-loader/src/lib.rs
merge_toplevel_arrays is no longer a parameter for this method since #3080, and the example fits better in a doc comment.
> Fix out of date comments on merge_toml_values

- book/src/generated/static-cmd.md
- helix-term/src/commands.rs
- helix-term/src/commands/typed.rs
- helix-term/src/keymap/default.rs
> Add support for extend_file_{start,end}.

- runtime/queries/_typescript/highlights.scm
- runtime/queries/ecma/highlights.scm
Before:
After:
This one, I couldn't highlight (bug in parser?)
Please, advise me if anything needs adjustments.
---
And in `queries/ecma` - I was wondering, why `delete`, `typeof`, `instanceof`, and `void` are in `@keyword` category, shouldn't they be in `@keyword.operator`?
> Added: missing highlighting to `queries/_typescript`

- book/src/other-software.md
Now that [zsh-helix-mode](https://github.com/Multirious/zsh-helix-mode) is reliable enough and complete enough for daily driving, I think it is ready to be mentioned in the other-softwares section.
> Mentions zsh-helix-mode in other-softwares

- runtime/queries/ocaml/highlights.scm
Since precedence reversing, ocaml functions and applications are highlighted as variables.
> fix: Ocaml highlights queries order

- default.nix
Output paths were non-stable, made them stable.
`./contrib/Helix.desktop` turned into the path `/nix/store/hash-Helix.desktop` so `$out/share/applications` was populated with a desktop file called `hash-Helix.desktop` instead of `Helix.desktop`.
> helix derivation fix output paths

- .github/workflows/build.yml
- .github/workflows/release.yml
This is currently in public preview: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
This is mostly experimental to see about adding an arm runner to the CI `build` workflow. We can wait till its stable but just thought I would see about how it runs for us now.
> ci: add arm64 runner

- book/src/editor.md
- helix-term/src/ui/statusline.rs
- helix-view/src/editor.rs
Adds `diagnostics` and `workspace-diagnostics` fields to the statusline editor config. This allows you to define a list of severities that will then be rendered in the order of definition:
```toml
[editor.statusline]
diagnostics = ["error", "hint", "warning"]
workspace-diagnostics = ["warning", "hint", "error"]
```
This defaults to:
```toml
[editor.statusline]
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]
```
the current `master` behavior.
Subsumes:  #13256 and #13257
> feat(config): add `[workspace-]diagnostics` fields to statusline

- book/src/guides/injection.md
Took me a bit to figure out why all the languages support highlighting inside comments, although it's never in the actual highlight queries. So I thought, maybe worth documenting.
> docs: another injection query example

- languages.toml
- runtime/queries/jjdescription/highlights.scm
Trying it out more in my workflow and noticed that some of the symbols weren't highlighted.
> chore(jjdescription): bump rev to latest

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/fennel/highlights.scm
Closes https://github.com/helix-editor/helix/issues/3846 .  After pondering it (for two years) it seems obvious that having a single grammar that tries to cover multiple Lisps is silly.
There are two different tree-sitter parsers for Fennel mentioned in that issue:
* https://github.com/travonted/tree-sitter-fennel
* https://github.com/alexmozaidze/tree-sitter-fennel
This PR has mostly-arbitrarily chosen the second one.  There's also several different `highlights.scm` options, I've mostly chosen the most recent one but tried to incorporate bits and pieces from the others where I could find them.
> Basic language support for Fennel.  Might even work.

- runtime/themes/gruvbox-material.toml
Port of https://github.com/sainnhe/gruvbox-material, trying to stay as close as possible to the highlights in Neovim.
> feat(themes): add gruvbox-material

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/quarto/highlights.scm
- runtime/queries/quarto/indents.scm
- runtime/queries/quarto/injections.scm
I saw #9389 and took a swing at following the instructions to add support. I gave it a test and it seems to work, but very new to helix so not sure what I may have missed.
At the moment there is no language server, though one is planned, so it also occurred to me that maybe adding `.qmd` to `markdown` is the more straightforward approach.
> feat: add basic Quarto support

- languages.toml
Newer version has support for `tool` directives.
Full diff: https://github.com/camdencheek/tree-sitter-go-mod/compare/e8f51f8e4363a3d9a427e8f63f4c1bbc5ef5d8d0..6efb59652d30e0e9cd5f3b3a669afd6f1a926d3c
> chore(languages): bump tree-sitter-go-mod

- runtime/themes/sonokai.toml
properly sets them to purple (based on the original's vim `colors`)
Before:
After:
> sonokai: fix constant.builtin highlights

- runtime/queries/lua/highlights.scm
This PR adds proper syntax highlighting for function calls that use dot notation (methods) in Lua files. Previously, when using a function call like object.method(), the method name was highlighted as a property (variable.other.member) rather than as a function call.
Before:
After:
> Add highlighting for lua methods

- runtime/queries/go/highlights.scm
I don't believe these should be highlighted as `function.macro`:
- They're keywords
- Many themes highlight `function` and `function.macro` the same, which colors `go someFunc()` and `defer someFunc()` uniformly, making the keywords easy to miss
- Other editors give these keyword-ish highlighting as well
> fix(highlights/go): defer, go, goto are keywords

- helix-term/src/commands.rs
- helix-term/src/commands/typed.rs
- helix-term/src/ui/mod.rs
This makes the very first argument of shell commands (like run-shell-command or pipe) auto complete programs instead of files.
This works relatively well for the commands themselves, however for the shell prompts (so the action pipe or pipe-to) this is pretty hard to do, because there the completions functions get the full line as input. This makes it impossible to figure out what argument you are editing, since you are missing the cursor position. (For command mode, this is handled by the command mode prompt itself, so the input for completion functions is just the argument which the user is editing right now.
Thinking about it, the pipe action might be able to be replaced using a macro that effectively does "@:pipe ", since the shell actions duplicate the commands from command mode.
For …
> Improve auto completion for shell commands

- .github/workflows/build.yml
- Cargo.toml
- helix-event/src/test.rs
- helix-lsp-types/src/lib.rs
- helix-stdx/tests/path.rs
- rust-toolchain.toml
Seems the update to the [policy](https://firefox-source-docs.mozilla.org/writing-rust-code/update-policy.html) page is lagging behind, as looking at the [source](https://searchfox.org/mozilla-release/source/Cargo.toml), the MSRV was indeed already bumped to `1.82` (and its what the policy update says it will be updated to).
> chore(msrv): bump from 1.76 to 1.82

- book/src/languages.md
- helix-core/src/command_line.rs
- helix-term/src/commands/typed.rs
- helix-view/src/document.rs
Partially solves #3596 
This implementation is a bit different from #5626 in that here the contents of the buffer is still passed to the formatter via stdin and not read from disk. This implementation allows to use the filename of the current buffer with formatters that accept arguments like `--stdin-filepath` or `--stdin-filename` ([prettier](https://prettier.io/docs/options#file-path), [stylua](https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#filtering-when-using-stdin), [ruff](https://docs.astral.sh/ruff/formatter/), [black](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#stdin-filename), [eslint](https://eslint.org/docs/latest/use/command-line-interface#--stdin-filename) and [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html …
> feat: give formatters access to filename

- .gitattributes
I noticed that linguist was identifying some queries as Scheme and others as Tree-sitter Queries.
My fork's stats might not have updated yet, but I confirmed the expected results by running github-linguist locally.
> Help Linguist identify Tree-sitter queries

- book/src/generated/static-cmd.md
- book/src/keymap.md
- helix-term/src/commands.rs
- helix-term/src/keymap/default.rs
Adds `goto_column` and `goto_line`.
The second commit adds them to the `Goto` menu as `|`, similar to how vim uses `<n>|`.
> Add goto_column and extend_to_column commands

- helix-loader/src/grammar.rs
`cc` should pick correct defaults when `debug` or `release`.
This was discussed at https://github.com/helix-editor/helix/discussions/13345#discussioncomment-12847728
> build(grammar): remove explicit opt out of optimizations for MSVC

- book/src/command-line.md
- helix-view/src/expansion.rs
This is needed so that, for example, there could be conditional logic around the type of file. For example, run `cargo test` when its `rust` and `go test` when its `go`.
Rough example:
```
:noop %sh{ test ${language}  }
```
```nushell
def --env test [lang: string] {
match $lang {
"rust" => (cargo test)
"go" => (go test)
}
}
```
> feat(commands): add `language` variable expansion

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/pug/highlights.scm
- runtime/queries/pug/injections.scm
This adds support for Pug.js (previously known as Jade), a templating language that compiles to HTML.
This is my first time writing tree-sitter queries, so I apologize if the queries look strange in any way.
> Add support for Pug language

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/slang/highlights.scm
- runtime/queries/slang/indents.scm
- runtime/queries/slang/injections.scm
- runtime/queries/slang/textobjects.scm
Related issue: #13343
I was unable to find any tree-sitter grammars with queries and do not have the familiarity with the language to write my own.
LSP support works so hopefully this is still helpful for Slang users.
If lack of queries is too large an issue, feel free to reject.
Thank you!
> feat: add basic Slang support

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/dunstrc/highlights.scm
Helix currently has an `ini` grammar defined in the `languages.toml`, but `dunstrc`'s `ini` flavor is different than that grammar.
`dunst` differs by:
- allowing comments at end of lines [^1]
- allows using quotation marks to mark values that can contain comment indicators [^2]
- ignoring any content after the closing `]` in a section [^3]
Example of the syntax highlighting in Helix using this PR:
[^1]: https://github.com/dunst-project/dunst/blob/d0f89761/src/ini.c#L137-L139
[^2]: https://github.com/dunst-project/dunst/blob/d0f89761/src/ini.c#L125-L135
a common use case for this is RGB colors (e.g., `"#FFAACC"`)
[^3]: https://github.com/dunst-project/dunst/blob/d0f89761/src/ini.c#L102-L108
> feat: add a tree-sitter grammar and highlights for dunst's config

- default.nix
- flake.lock
- flake.nix
Remove the dependency on flake-utils, which simplifies the flake by removing abstraction. 
Add nix-systems to enable local overriding of the systems.
> flake: drop flake-utils dependency

- grammars.nix
Nix 2.6 was released over three years ago, I think we can drop the `HACK` in grammars.nix.
> chore: clean up grammars.nix

- languages.toml
- runtime/queries/cpp/highlights.scm
Recently fixed how C++23's lambdas were sometimes failing to highlight with tree-sitter (link to the issue https://github.com/tree-sitter/tree-sitter-cpp/issues/315). Bump to bring this feature into helix o/
> bump: tree-sitter-cpp

- runtime/queries/verilog/highlights.scm
The keyword is semantically similar to the "wire" keyword, covered by the `(net_type)` production. However, the grammar does not have a named production for the "var" keyword.
Instead of using a catch-all `"var"` in the same query, this adds three queries to cover the legal uses of the "var" keyword. Example:
```verilog
module example_m(
input var abc  // <-- variable_port_header
);
var something; // <-- data_declaration
endmodule
function example_f(
input var def  // <-- tf_port_item1
);
endfunction
```
> verilog: add highlighting for the "var" keyword

- languages.toml
I've changed the configuration for rust-analyzer to use the server-side file watching mechanism instead of the missing client-side.
This means there is no need to use `lsp-restart`  after using `cargo add` or `cargo remove`. Rust-analyzer automatically identifies the added / removed dependencies and provides intellisense and autocompletion.
> Changed rust-analyzer configuration to use server-side file watching

- languages.toml
You will see this extension used for source files that solely consist of an R7RS library declaration (where the `sld` file can then include the corresponding `scm` file).
You can check this part of the chibi scheme source for an example of this kind of organization: https://github.com/ashinn/chibi-scheme/tree/master/lib/chibi
> add `sld` to Scheme file type extensions

- languages.toml
Per https://git-scm.com/docs/gitattributes, the new "global scope" location for this file is *~/.config/git/attributes*.
> More glob to detect gitattributes file

- runtime/queries/python/locals.scm
Got hit during the wide updating of locals.scm everywhere. Closes #13548
> Updated python/locals.scm to label `self` and `cls` as `variable.buitin`

- helix-term/src/health.rs
I recently got confused when I checked `--health rust` and saw this:
```
Configured language servers:
✓ rustup: /usr/bin/rustup
```
It's actually due to having the following in my languages configuration (because I wanted to try out the range formatting features):
```
[language-server.rust-analyzer]
command = "rustup"
args = ["run", "nightly", "rust-analyzer"]
``` 
So `--health` actually prints the `command` of the LSP rather than the configured name. I believe it would make more sense to print the name along with the path, so in my case:
```
Configured language servers:
✓ rust-analyzer: /usr/bin/rustup
```
I also changed the `--health` "all languages" to have the same behavior and the DAP/formatter output style to match the LSP style (newline, checkmark), for example:
```
> helix …
```
> Use configured LSP name wherever possible in --health

- book/src/building-from-source.md
For users who don't need/want reproducible builds, and to [set a sensible-default that would be a breaking-change for Cargo](https://github.com/rust-lang/cargo/issues/4150)
> docs(building-from-source): suggest optimized install cmd as alternative

- book/src/generated/lang-support.md
- helix-term/tests/test/commands.rs
- helix-term/tests/test/movement.rs
- languages.toml
- runtime/queries/rust-format-args/highlights.scm
- runtime/queries/rust/injections.scm
This is a revival of https://github.com/helix-editor/helix/pull/12768
This adds syntax highlighting to a hard-coded set of Rust macros that accept a string literal which will be passed to `format_args!`. 
All `std` macros are included as well as several crates
One thing that I'm not sure how to fix, is that the `rust` language syntax highlighter injections seems to break for other arguments when I inject `rust-format-args` into the 1st argument
I don't know if it's something we can do about the query or `tree-house`
```scm
(macro_invocation
macro:
[
(scoped_identifier
name: (_) @_macro_name)
(identifier) @_macro_name
]
(token_tree
. (string_literal
(string_content) @injection.content
)
)
)
```
> feat: highlight rust string interpolation macros that use `format_args!`

- runtime/queries/ungrammar/highlights.scm
Improve UX of highlighting `ungrammar` grammar by assuming each Rule as a `function`, Labeled as a `type`, and Node as a `parameter`. This is better than just all white.
- Before:
- After:
> fix(highlights/ungrammar): improve UX

- default.nix
This PR fixes the missing parameters in Helix's package derivation, nominaly: `grammarOverlays` and `includeGrammarIf`.
This closes #13603.
> (Nix) Fix support for grammar overlays and include predicate for package in flake

- helix-term/src/ui/lsp/signature_help.rs
- helix-tui/src/widgets/paragraph.rs
Closes #13559 
Side note: Why are the helix-tui tests commented out?
> Make signature_help more like hover, fix overflow and lack of scrolling in signature_help

- book/src/generated/lang-support.md
- languages.toml
Adds support for [ty](https://github.com/astral-sh/ty), which is a new Python type checker and language server from Astral. The server requires no additional arguments passed to it whatsoever as compared to [Astral's ruff](https://github.com/astral-sh/ruff), which is already supported by Helix.
> Add ty language server

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/clarity/highlights.scm
This PR adds LSP and syntax highlighting support for the Clarity language. Clarity is a decidable, Lisp-like language used for writing smart contracts on the [Stacks blockchain](https://github.com/stacks-network/stacks-core), and is identified by `.clar` file endings
> feat: Add Clarity language support

- runtime/queries/go/highlights.scm
- runtime/queries/go/locals.scm
Look at below Rust snippet and note the highlighting of struct fields and function parameters:
Now look at the quasi-equivalent code in Go, note that function parameter and struct field highlighting spill into places they shouldn't:
With this PR, we get the same (correct) highlighting in Go, just as shown in the Rust example:
> highlights/go: fix locals clashing with variable.other.member

- book/src/generated/static-cmd.md
- helix-term/src/commands.rs
The usecase is to have made some selections, and then jumping to either the first or the last one, to then "remove all other selections" on. Very helpful for navigation!
> feat: add goto_first_selection, goto_last_selection

- languages.toml
Add [pyrefly](https://pyrefly.org/) language server for Python.
> Add Pyrefly language server

- runtime/queries/python/highlights.scm
Some highlights were overwriting each other in a way that seemed accidental (i.e. more general matches overwriting specific ones). I reordered the highlights and attempted to group them by category except when necessary for correct matching order.
I also switched whole-word `match` predicates to `any-of`.
Before/After:
`for`, `in`, `break`, and `continue` should all be `keyword.control.repeat`, `in` is `keyword.operator`.
`.__init__()`, `.__new__()`, `Init()`, `Gee()`, `__init__`, and `__new__` should all be `constructor`, but `.__init__()` and `.__new__()` are `function.method` and `Init()` and `Gee()` are `type`.
All should be `type.builtin` but above `bool`, all are `type`.
> fix: re-ordered and updated python highlights

- helix-lsp/src/client.rs
> Merge formatting options and `config.format` in range format request

- runtime/queries/ecma/highlights.scm
Highlights the Ecma `escape_sequence` node with `constant.character.escape`, which makes escape sequences such as `\n` and `\t` more visible in strings.
| --- | --- |
| <img width="399" alt="image" src="https://github.com/user-attachments/assets/7070b2a4-bb01-40aa-981a-484aa4d2c413" /> | <img width="394" alt="image" src="https://github.com/user-attachments/assets/9c7fd768-de99-415e-bb11-5e8d3510a43c" /> |
> Highlight Ecma escape sequences

- book/src/generated/lang-support.md
- languages.toml
Repository: https://github.com/KrosFire/amber-lsp
I think some servers are sorted alphabetically, but most of them are not. Anyway, I've sorted servers around Amber which start with `a`.
> Add Amber language server

- book/src/editor.md
- helix-term/src/commands/lsp.rs
- helix-view/src/editor.rs
Resolves #13582
What's more, I notice that in `helix-view/src/document.rs` 
here `oudated` might be a spelling error, is it `outdated`(I have not modify it yet)?
> Feat: inlay hint length limit

- languages.toml
- runtime/queries/astro/highlights.scm
- runtime/queries/html/highlights.scm
Updates the tree-sitter-html repository from where it was - 2022 commit? - to the latest commit (5 months ago). This is required to support the `entity` node that has been added, which is captured here with the `string.special.symbol` capture/scope.
| --- | --- |
| ![CleanShot 2025-06-12 at 16 24 08](https://github.com/user-attachments/assets/e28ea442-6ab6-4d24-9b9c-2011063cd048) | ![CleanShot 2025-06-12 at 16 24 37](https://github.com/user-attachments/assets/a6bc93a1-2ca6-4eda-a213-c5f3e3f48ac8) |
> Highlight HTML entities

- runtime/queries/cpp/highlights.scm
Referencing [this discussion](https://github.com/helix-editor/helix/discussions/13766).
- Fixes highlighting on namespaced variables
- Fixes highlighting on namespaced functions
- Adds highlighting for constructors and destructors
- Fixes highlighting on nested namespaces
However, making highlighting on namespaced things work makes enum variants be highlighted as variables. Due to how the syntax is parsed, I do not believe there is a solution to have both be highlighted correctly. I believe it is far more common to use namespaced variables and functions (i.e. the entire `std` library or other namespaced libraries), than using enums, so I believe this is the correct option.
Before and after screenshots can be seen in the linked discussion.
> Fix: update c++ highlights

- helix-view/src/editor.rs
Currently moving nonexistent files fails with no such file or directory. A simple condition to only move when the file exists resolves this issue. This could be useful when you :open a new file but decide on a different name before writing it
> feat: allow moving nonexistent file

- helix-term/src/application.rs
The byte sizes get very long for large files, ditto the title and the pr.
> use human-readable sizes for file size on save/write

- helix-term/src/commands/lsp.rs
Solves https://github.com/helix-editor/helix/issues/12474 and https://github.com/helix-editor/helix/issues/11452
This should probably be configurable so my current approach is very naive. I just wanted to quickly whip something up for myself.
When programming in Python multiple/many LSP's is the norm and it can be hard to make sense of things. Hence this PR that displays the LSP responsible for a certain diagnostic in the picker.
> feat: Make the diagnostic picker display the resposible LSP

- helix-term/src/lib.rs
Fixes #13661
Use `From<std::process::Command>` instead of `args`, the latter will result in unexpected behaviors on Windows, just as said in the issue. `raw_arg` is the way to fix it, but `open::commands` has provided us `std::process::Command`s, just use `.into()` to wrap it in tokio's `Command` instead of constructing it by hand.
> Fix `goto_file` bug on Windows

- book/src/themes.md
- languages.toml
- runtime/queries/gleam/highlights.scm
- runtime/queries/gleam/injections.scm
This PR adds markdown injections for Gleam's documentation comments `///` and `////`
It also improves syntax highlighting by aligning all of the scopes more closely with Rust's (e.g. `->` function return operator is `@operator`)
I tested this with all of the files in [Gleam's standard library](https://github.com/gleam-lang/stdlib)
> feat: Improved syntax highlighting for Gleam

- runtime/queries/gleam/highlights.scm
For example in this code:
```gleam
pub fn debug(term: anything) -> anything {
term
|> string.inspect
|> do_debug_println
term
}
```
`inspect` in `string.inspect` would be a field access, but we know it must be a function if it's the subject of a pipe
> fix: highlight `floor` in `|> float.floor` as function in Gleam

- helix-term/src/commands/lsp.rs
This brings code-actions in line with hover popups. Having the code action menu follow the cursor around feels strange and I am of the opinion it makes sense to close it when moving around.
Closes: #11104
> UI: Make code-action popup auto close like other popups

- languages.toml
This file stores client credentials for [RubyGems.org](https://rubygems.org/), the package management framework for Ruby.
I have not found any official docs describing the format, but going through the [code](https://github.com/rubygems/rubygems/blob/89f7f5f760fa24dda7f21fee7c93f0a69780cd21/lib/rubygems/config_file.rb#L365-L385) one can see that it is expected to be parsed as yaml.
> languages: detect `~/.gem/credentials` as yaml

- languages.toml
On Free-Desktop/XDG compliant systems, the file-path `~/.config/mimeapps.list` is used to set default handler apps and associations (`xdg-mime`). In addition to the user-specific one, there's also a system-wide equivalent, but I couldn't find info about its standard path
> recognize `mimeapps.list` as INI

- runtime/queries/dockerfile/injections.scm
Inspired by https://github.com/helix-editor/helix/pull/13845, we can also add injections for heredocs to Dockerfiles.
`RUN` with heredoc:
`COPY` with heredoc (language detected by file extension):
> queries/dockerfile: injections for heredocs

- runtime/queries/nix/injections.scm
I was looking through some nix code in [home-manager](https://github.com/nix-community/home-manager) and thought that the examples set with `lib.literalExpression ''...''` were hard to parse without it being highlighted as nix code. This PR adds an injection query to set the string argument for `lib.literalExpression` to be nix code.
IMO it makes it easier to tell the structure of the examples, but at the same time it makes it harder to quickly tell if these expressions are evaluated as code, or just as a string. 🤷
If there is no support for this, then maybe it can serve as an example in the docs for how to write a somewhat complex tree-sitter query.
**Before**
**After**
> queries: inject nix into `lib.literalExression` string contents

- helix-term/src/application.rs
- helix-view/src/document.rs
Closes  #13268
I documented the list of files updated on `:config-reload` and added `.editorconfig` to the list of files reloaded since it is now a part of the configuration of the editor.
Any feedback is appreciated.
> Fix: .editorconfig is now reloaded on `:config-reload`

- book/src/command-line.md
- helix-view/src/expansion.rs
When calling commands with `:sh` and friends, it wasn't previously possible to access the start and end line numbers for the primary selection. Expand `selection_line_start` and `selection_line_end` at the command line.
Replaces #13839
> helix-view: expand primary selection line range in shell commands

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/caddyfile/highlights.scm
- runtime/queries/caddyfile/indents.scm
- runtime/queries/caddyfile/injections.scm
- runtime/queries/caddyfile/locals.scm
- runtime/queries/caddyfile/textobjects.scm
Add support for the Caddy configuration format aka. [Caddyfile](https://caddyserver.com/docs/caddyfile). It uses the official tree-sitter parser from the Caddy project. It does not fully parse the entire grammar properly yet, e.g. it does not handle multiple addresses for a site block. 
```Caddyfile
localhost:8080,
example.com,
www.example.com {
...
}
```
But, it is still very usable today. Fixes #12668
**Highlighting Preview**
> languages: add Caddyfile support

- book/src/generated/typable-cmd.md
- xtask/src/docgen.rs
The same is already being done for static commands.
> Docs: escape `|` in typeable command names

- helix-term/src/commands.rs
Ensures that Helix doesn't crash if jump-label-alphabet is empty. If it is, jump_to_label() returns early instead of trying to find the correct character by erroneously dividing by zero (the length of the alphabet).
Closes https://github.com/helix-editor/helix/issues/13175
> fix: empty editor.jump-label-alphabet doesn't lead to a crash anymore

- runtime/queries/c/highlights.scm
- runtime/queries/c/locals.scm
C parsing is cursed. `void foo(int *****bar);` is legal. The nature of tree-sitter means that we have to explicitly choose how many layers we support. I arbitrarily selected 6 including the identifier. If someone hits this limit in the wild, they have larger problems than highlighting. This change also fixes things like `char** argv` not getting highlighted as a parameter. We also add a `locals.scm` capturing function parameters. Preprocessor parameters aren't included since the preprocessor body is currently parsed as an opaque block lol.
Closes: #12038
> queries: Add locals.scm for C. Improve C parameter highlights

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/properties/highlights.scm
- runtime/queries/properties/injections.scm
- runtime/queries/properties/locals.scm
- runtime/queries/properties/textobjects.scm
Add support for [.properties](https://en.wikipedia.org/wiki/.properties) files, most commonly used in the Java ecosystem.
Most of the highlight queries are taken from the [tree-sitter-properties](https://github.com/tree-sitter-grammars/tree-sitter-properties) repository, where the parser is from. Modified to work with our highlight capture names. In addition, I have added some niceties like detecting values that are boolean, numeric and path file and highlighted them accordingly.
**Highlight Preview**
> languages: add Java .properties file support

- languages.toml
- runtime/queries/odin/highlights.scm
- runtime/queries/odin/indents.scm
The added keywords are used like this:
```odin
for {
(foo == true) or_continue
(bar == true) or_break
}
```
> Odin grammar and query updates

- helix-term/src/commands/typed.rs
- helix-term/tests/test/commands/write.rs
Currently, the `:move` command only accepts a file as the target. If a user wants to move a file to a different directory without changing its name, they must manually re-enter the file name, which can be inconvenient.
This PR checks whether the target path is a directory. If so, it automatically appends the original file name to the destination path.
> Allow `:move` command to accept directories as target

- book/src/editor.md
- helix-core/src/editor_config.rs
- helix-view/src/document.rs
- helix-view/src/editor.rs
For some file watching/hot reloading programs, the way that Helix writes files can confuse them and cause them to throw errors or corrupt their caches. One such program is the `parcel` bundler
https://parceljs.org/features/development/#known-issues-with-file-watching
They explicitly document that if your editor saves files using an "atomic save" or "safe write" or "backup copy" strategy, that it should be disabled. Helix currently does not allow you to disable this functionality, and adding this configuration option makes it so that that is possible.
> Add ability to configure atomic saving

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/jjconfig/highlights.scm
- runtime/queries/jjconfig/indents.scm
- runtime/queries/jjconfig/injections.scm
- runtime/queries/jjconfig/textobjects.scm
- runtime/queries/jjrevset/highlights.scm
- runtime/queries/jjtemplate/highlights.scm
The config file for [`jj`](https://github.com/jj-vcs/jj) has some tables that canonically contain a few domain-specific languages: all keys in `[revsets]` and `[revset-aliases]` are revsets, and similar for templates in `[templates]` and `[template-aliases]`.
This injects those languages where appropriate.
> Add tree-sitter injections for jj config files

- book/src/generated/lang-support.md
- book/src/generated/static-cmd.md
- book/src/guides/textobject.md
- book/src/keymap.md
- book/src/textobjects.md
- helix-term/src/commands.rs
- helix-term/src/keymap/default.rs
- runtime/queries/_jsx/textobjects.scm
- runtime/queries/html/textobjects.scm
- runtime/queries/jsx/textobjects.scm
- runtime/queries/xml/textobjects.scm
Building on the work done by @ff2400t this adds text-objects to select xml-like elements in html, jsx and xml files.
Fixes: #6682 
The behaviour is consistent with other text-objects in helix. It is however not consistent with vim's tag textobject:
```html
<p>
<span> inner_span </span>
</p>
```
If the cursor is on `<span>` `vit` would select ` inner_span ` in vim.
In Helix `mix` will select `  <span> inner_span </span>`
If the cursor is actually inside the tag, both solutions work the same.
I think despite the difference to vim this textobject is very useful and would love to see it in my daily work.
> Add textobjects for XML, HTML and jsx

- .github/workflows/release.yml
Lower the version of ubuntu to `22.04` as `24.04` uses a much newer GLIBC version, causing issues for people who want to use the built binaries on systems not as up to date.
It also adds documentation to warn any changes made should be reviewed to make sure that this is caught earlier on, as this is now the second release in a row where this has happened.
Perhaps as a rule of thumb we use the older of an LTS release? And special case from there. Really not sure what other process we can have for this other than just making sure during the review/pr process to just verify that its not causing large issues.
Related #12464
Closes #13960
> build(release): lower ubuntu version from `24.04` to `22.04`

- Cargo.lock
- book/src/editor.md
- book/src/languages.md
- helix-core/src/completion.rs
- helix-core/src/syntax/config.rs
- helix-core/src/transaction.rs
- helix-term/src/handlers.rs
- helix-term/src/handlers/completion.rs
- helix-term/src/handlers/completion/request.rs
- helix-term/src/handlers/completion/word.rs
- helix-view/Cargo.toml
- helix-view/src/document.rs
- helix-view/src/editor.rs
- helix-view/src/handlers.rs
- helix-view/src/handlers/word_index.rs
- languages.toml
Completion of words from open buffers is a feature I miss from Kakoune. The spirit of this implementation is the similar: words are extracted from open buffers and stored in a database (`WordDB` in Kakoune). Then completion reads from the database to fuzzy-find candidates. All reading and writing to the index is done off the main thread and large changes to the index are debounced. Updates to the index examine the `ChangeSet` which caused the change and only consider windows of the text around each `Operation::Insert` and `Operation::Delete`.
Note that this doesn't follow Pascal's idea for using Aho-Corasick on the current buffer ([comment](https://github.com/helix-editor/helix/pull/3328#issuecomment-1559031060)) because I would like words from all documents. Word completion is especially …
> Word completion

- languages.toml
- runtime/queries/just/highlights.scm
- runtime/queries/just/locals.scm
This brings Helix in line with Just 1.42 released recently.
> just: bump grammar support to handle module path in aliases and recipes dependencies

- runtime/gruvbox_material_light_hard.toml
- runtime/themes/gruvbox_material_light_medium.toml
- runtime/themes/gruvbox_material_light_soft.toml
Port of Gruvbox Material Light theme.
> feat(themes): add Gruvbox Material Light theme

- languages.toml
There is a new official Kotlin language server being developed at https://github.com/Kotlin/kotlin-lsp.
This PR adds it to `language-servers` in `languages.toml`.
The language server is still relatively young and not feature complete, so I decided to hold off from enabling it for Kotlin by default.
For reference, [this is the configuration in `nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig/blob/v2.3.0/lsp/kotlin_lsp.lua).
> feat: Add `kotlin-lsp` to `languages.toml`

- helix-term/src/ui/mod.rs
Previously `fn directory_content` did not traverse symbolic links to query about the destination of the symlink and therefore symlinks were always treated as files in the file picker
If you would like me to add a test, I'd be happy to do so
- `ln -s helix-dap example-symlink`
- `cargo run` and select "example-symlink" in the filepicker
- Fails with "unable to open..." 
- [`DirEntry::file_type`](https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.file_type:~:text=type%20for%20the%20file%20that%20this%20entry%20points%20at.-,This%20function%20will%20not%20traverse%20symlinks%20if%20this%20entry%20points%20at%20a%20symlink,-.)
- [`fs::metadata`](https://doc.rust-lang.org/std/fs/fn.metadata.html#:~:text=This%20function%20will%20traverse%20symbolic%20links)
> Fix symlinked directories being recognized as a file

- languages.toml
- runtime/queries/koto/highlights.scm
- runtime/queries/koto/textobjects.scm
This PR updates Koto's tree-sitter queries, and adds a `formatter` definition.
> Koto updates

- .github/workflows/release.yml
Updates the releases CI job to the current OS for windows and macos. Starting with macos-14 the `macos-latest` image is solely ARM. There is a `macos-latest-large` for x86_64, which this changes for the x86_64 job. Tests are now not skipped, as it was before, bringing all platform to the same state now.
The windows image was changed to `windows-latest` and the check for when the built artifacts are moved is changed to check the `os` field for `windows-latest` rather than the now deprecated `windows-2019`.
https://github.com/actions/runner-images?tab=readme-ov-file#available-images
A Windows 11 ARM exists, but does not come with Rust like the ubuntu one so leaving for later. Rust on Windows ARM is also only a tier 2 support.
https://github.com/actions/partner-runner-images/blob/main/images/ …
> ci(release): update runner os for windows and macos

- helix-term/src/ui/prompt.rs
This change helps to avoid crash due to unwrapping an empty value with graphemes.  The issue was discovered accidentally while porting the Helix editor to ARM-based platforms. The simplest way I found to reproduce the problem is to run Helix in QEMU and try entering some commands. 
The crash is actual only for fresh **25.07.1** version. **25.01.1** is fine. 
I modified the code to prevent the crash, but I haven’t investigated the root cause in depth. There’s a possibility that the issue originates from the environment rather than from Helix (I was using very minimal BusyBox-based environments). It’s also possible that crashing is preferable to continuing to run in this state — I’m not sure. This is something I’d like to discuss during the review.
Please let me know if you need any …
> helix-term:fix crash on unwrap graphemes

- languages.toml
This PR adds [yamlfmt](https://github.com/google/yamlfmt) as the default configured formatter for `yaml` files. It also enables `auto-format` for consistency with what's already set for `json` and `jsonc`.
> feat: add yamlfmt as default yaml formatter

- contrib/completion/hx.bash
- contrib/completion/hx.fish
- contrib/completion/hx.nu
- contrib/completion/hx.zsh
- helix-loader/src/grammar.rs
- helix-term/src/health.rs
- helix-term/src/main.rs
This adds a `my-languages` category to `hx --health`.
`hx --health my-languages` has same output than `hx --health languages`, but only shows languages corresponding to the use-grammars option in the user's languages.toml.
> feat: add languages filtering to `hx --health`

- book/src/keymap.md
Clarify that the `G` keybinding in the normal model and the `g` keybinding in the goto mode should follow an integer.
Resolving #10529.
> Improve the keymap doc in the book

- helix-term/src/commands/lsp.rs
This was brought up again in https://github.com/helix-editor/helix/issues/3543 and I think that while the search options to narrow a scope down is very nice, I find myself searching for errors as the most common case, which requires to always have a `%s E` search. This works, but one issue is that the `SPACE+'`, for example, doesnt update with new info after changing things. And the picker doesnt persist the queries, requiring a retype of the same thing many times as issues are addressed.
Sorting by default optimizes this flow. And the search options still provide a way to narrow from there. While I think this should be the default, there was mention of configuration, but most cases need a search, which bypasses any specific search order anyways (I think it uses a different search sort …
> feat(lsp): sort diagnostic picker by severity

- book/src/SUMMARY.md
- book/src/jumplist.md
My take on adding documentation for the jumplist to the book. Would love to have other eyes on this and suggest ways to improve the page.
Closes: #13594
> docs: Add jumplist documentation to the book

- runtime/themes/jetbrains_dark.toml
I have tried to use the `jetbrains_dark` theme, and realized that there was no primary selection color set. That caused some issues, e.g. it is not visible which selection is the primary one.
> Use separate color for primary selection in `jetbrains_dark`

- book/src/editor.md
- helix-view/src/annotations/diagnostics.rs
- helix-view/src/editor.rs
As discussed in https://github.com/helix-editor/helix/discussions/13956
These are the settings we used to recommend in documentation. We could discuss switching up the defaults though. I believe @archseer uses info for the cursor-line severity while I use error.
> Enable inline diagnostics by default

- runtime/themes/catppuccin_mocha.toml
Effectivly sync the changes made in https://github.com/catppuccin/helix/pull/75 to support the addition of the Rainbow theme key made in https://github.com/helix-editor/helix/pull/13530
> feat(theme): Sync catppuccin themes to include rainbow array.

- helix-core/src/indent.rs
A loose fix for #9556 that specifically targets the case of single indented comments that some languages use (see #9822).
In the rare case where a document is 1 size indented, it will still supply the correct indentation so long as there isn't a significant mix of other indentation sizes. If there is a significant mix, the indentation detection should fail.
Before: 
After:
> Reduced the weight of size 1 indents in the indent auto-detection system

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/blade/folds.scm
- runtime/queries/blade/highlights.scm
- runtime/queries/blade/injections.scm
- runtime/queries/blade/rainbows.scm
- runtime/queries/blade/textobjects.scm
Hello!
This commit upgrades the very outdated `tree-sitter-blade` with the upstream repo and adds new features. Below is a brief summary of what has been changed and added:
- `tree-sitter-blade` upgraded to the latest `v0.12.0` (complete rewrite + ABI 15 + many bug fixes)
- As the parser now inherits from `html` rather than injection, I have duplicated/merged the latest `html` `.scm` files with the new `blade` `.scm` files. (unfortunately I do not think Helix supports query file inheritance? neovim supports something like `;inherits language` in the `.scm` files
- The highlighting selector has changed for the `blade directives` to `keyword.directive` from `tags` which is more semantic and clearly distinguishes blade markups
- Support for all sort of injections in the blade files have also …
> FEAT: Tree-Sitter-Blade Upgrade

- helix-core/src/editor_config.rs
This makes it such that sections like `[*.y{,a}ml]` correctly match `.yml` and `.yaml` file extensions.
> editorconfig: allow empty alternates

- book/src/languages.md
The example will result in a two arguments being passed to the formatter: `--stdin` and `--stdin-filename %{buffer_name}`. Most command line parsers expect option values as separate arguments so the second argument should be split into two `--stdin-filename` and `%{buffer_name}` for three arguments in total.
> docs: Correct expansion argument formatting

- languages.toml
This matches the default for Vim, VSCode, Lapce, and probably others. I believe indenting with four spaces is more common with Docker because it indents past the commonly wrapped instructions, e.g. this:
```dockerfile
RUN apt-get update && apt-get install -y \
gcc \
binutils
```
Becomes this:
```dockerfile
RUN apt-get update && apt-get install -y \
gcc \
binutils
```
> docker: Update the default indentation to match other editors

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/go-format-string/rainbows.scm
- runtime/queries/go/injections.scm
- add `rainbows.scm` queries for explicit argument index e.g. `%[2]d`
- detect '%w' as verb for `fmt.Errorf`
- inject into string argument for `fmt.Errorf`
> Update `go-format-string` grammar and queries

- languages.toml
Simple change, `///` is commonly used for doc comments in C# and that isn't currently being respected.
> languages: Add doc comment token for C#

- languages.toml
- runtime/queries/go/highlights.scm
- runtime/queries/go/textobjects.scm
Updated grammar.
Added builtins: `min`, `max`, `clear`.
Added operators: `&^`, `&^=`.
Had to update templ grammar too because it inherits golang highlights.scm.
> feat: update go grammar and queries

- helix-term/src/commands/typed.rs
- helix-term/src/ui/picker.rs
`:vsplit` and `:hsplit` lack features that only `:open` supports:
- Cannot create a new split at a specific `file:line:column`
- Passing a directory doesn't trigger a file picker
This unifies the underlying implementation so it's shared between `open/vsplit/hsplit` and all support the same feature set.
> Support features of `:open` in `:vsplit` & `:hsplit`

- languages.toml
Code blocks in commit messages are typically set off by four spaces. This is also required when they are rendered as markdown (two leading spaces just gets stripped).
Update jj.description to use 4 spaces, which matches the config for git messages as well as Vim.
> jj: Set the indent to four spaces for descriptions

- helix-term/src/commands.rs
- helix-term/tests/test/commands.rs
- helix-term/tests/test/commands/reverse_selection_contents.rs
- helix-term/tests/test/commands/rotate_selection_contents.rs
This PR fixes 2 bugs with the `rotate_selection_contents_forward` (`A-)`) and `rotate_selection_contents_backward` (`A-(`) commands.
Key: `[a]` means the letter `a` has a single selection around it.
Pressing `A-)` 2 times will go from file `A -> B -> C`:
```
A      B      C
[a]    [e]    [d]   
[b]    [a]    [e]   
[c] -> [b] -> [a]
[d]    [c]    [b]   
[e]    [d]    [c]   
```
However, if you press 2 followed by `A-)` then the result is not the same:
```
A      C      
[a]    [b]       
[b]    [a]      
[c] -> [d]
[d]    [c]      
[e]    [e]    
```
This PR fixes this problem. `<count><A-)>` is now the same as `<A-)>` `count` times
Key: `{a}` means primary selection, `[a]` means secondary selection.
Pressing `A-)` 2 times does not change index of the primary selection:
```
A      B …
```
> fix: 2 bugs in the `Alt-)` and `Alt-(` commands

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/pip-requirements/highlights.scm
- runtime/queries/pip-requirements/injections.scm
Add the [pip requirements file](https://pip.pypa.io/en/stable/reference/requirements-file-format/) format commonly known as just `requirements.txt`.
**Showcase**
> feat: add `pip-requirements` language

- book/src/generated/lang-support.md
- runtime/queries/janet/rainbows.scm
These are pretty much analogous to the rainbow queries for clojure.
> Add rainbows.scm queries for Janet

- book/src/package-managers.md
Building the Helix PPA has become increasingly cumbersome, as newer versions of Helix often require newer Rust toolchains that are not available in older Ubuntu releases. This creates difficulties for Ubuntu LTS users who still want to run the latest Helix version.
With the availability of the Snap package, I have decided to stop building new Helix versions in my PPA. The PPA repository has been archived, and users are encouraged to either:
1. Build the Debian package themselves, or
2. Use the Snap version.
For more details, see the official documentation:
* [Ubuntu/Debian installation](https://docs.helix-editor.com/package-managers.html#ubuntudebian)
* [Snap installation](https://docs.helix-editor.com/package-managers.html#snap)
> Remove the Ubuntu PPA installation method from the docs

- helix-term/src/commands/lsp.rs
Fixes the confusing UX where pressing `gD`, for example, would show an error about definitions when the command is specifically for declarations.
Before:
https://github.com/user-attachments/assets/ec97c7f5-a578-48f3-915d-6211a0dec3ff
After:
https://github.com/user-attachments/assets/0ffc464c-a944-4369-a6da-7a729254d1d1
We can dynamically generate error messages based on the `LanguageServerFeature` type:
- GotoDeclaration → "No declaration found."
- GotoDefinition → "No definition found."
- GotoTypeDefinition → "No type definition found."
- GotoImplementation → "No implementation found."
> Fix misleading error messages for goto LSP commands

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/systemverilog/highlights.scm
This PR adds support for proper syntax highlighting for SystemVerilog using the [Systemverilog tree sitter]( https://github.com/gmlarumbe/tree-sitter-systemverilog).
> feat: add a tree-sitter grammar for systemverilog

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/kconfig/folds.scm
- runtime/queries/kconfig/highlights.scm
- runtime/queries/kconfig/indents.scm
- runtime/queries/kconfig/injections.scm
- runtime/queries/kconfig/locals.scm
Uses: https://github.com/tree-sitter-grammars/tree-sitter-kconfig. Adapted from the original neovim queries. Screenshot:
> Add support for KConfig

- runtime/themes/adwaita-light.toml
Hi, the current `ui.virtual` setting for `adwaita-light` has too little contrast, rendering e.g. inlay hints almost invisible. I propose bumping the color to `light_6` for better visibility.
While at it, maybe we could also lower the `ui.virtual.ruler` `bg` to `light_3` to make it gentler? (I can commit to this PR, if we agree to a lighter color.
> fix adwaita-light ui.virtual color

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/cross-config/highlights.scm
- runtime/queries/cross-config/injections.scm
- runtime/queries/cross-config/rainbows.scm
- runtime/queries/cross-config/textobjects.scm
This adds an injection query only active for `Cross.toml` files used by [`cross`](https://github.com/cross-rs/cross) that highlight string literals in the `pre-build` array of each target as `bash`. This aids in readability for config files with multi-line pre-build instructions.
**Showcase**
> feat(languages): specilize toml file-type for cross-rs config file

- helix-term/src/commands.rs
- helix-term/src/ui/picker.rs
When switching files, there is often a need
to swap to the prev file quickly.
This defaults the cursor to the last file if
present instead of keeping it on the current
file which almost always is never picked
as that is the file that is currently being
edited anyway.
> Make buffer picker default to last file

- languages.toml
These files are used to define package-level configuration and use the starlark dialect similar to BUCK files.
See: https://buck2.build/docs/rule_authors/package_files/
> feat(languages): Add buck2 PACKAGE files as starlark file type

- helix-term/src/commands.rs
- helix-term/src/commands/typed.rs
The `shell_pipe`, `shell_keep_pipe`, `shell_insert_output` etc. commands aren't typable commands, yet they have a command line. These lack integration with command expansions, which are only available in typable commands. This PR does the necessary plumbing such that command expansions work for these special cases.
This is mostly a refactor such that `commands.rs` can reuse some bits of `typed.rs` without the need to summon a full `TypableCommand`.
---
cc @david-crespo would love if you could give this a test run
> Fix shell pipe command lines not using expansions

- book/src/package-managers.md
hej, i think it could be an small improvement to the docs, if you could include a direct link to the github release page.
i actually stumbled across this missing link 2-3 times - its not hard to find the location, but adding it might save someone a few seconds :)
> add a link to github release page on debian installation docs

- helix-term/src/ui/editor.rs
- helix-view/src/editor.rs
This is meant to work towards fixing transaction crashes like https://github.com/helix-editor/helix/issues/13585, https://github.com/helix-editor/helix/issues/12582. I've never run into these crashes myself but also I never use the mouse to navigate or switch between windows. Revisiting the `Editor::focus` code I see that we swap views and then enter normal mode. This leads to a number of smaller bugs like indentation not being reset properly in the old view. I suspect it's also a factor in a lot of these transaction panics. We also rely on the implicit behavior of appending changes to history when a command is executed in normal mode (handled at a high level in the editor) rather than explicitly appending while entering normal mode. Like in …
> Fix bugs in `Editor::focus`

- runtime/queries/rust/injections.scm
test file:
```rs
fn foo() {
rsx! { "{hello} world" }:
rsx! { div { "{hello} world" } }
rsx! { div { div { "{hello} world" } } }
}
```
split up from https://github.com/helix-editor/helix/pull/13932
> queries(rust): properly highlight Dioxus' `rsx!` macro

- runtime/themes/flatwhite.toml
- Highlight goto_word (Before/After)
- Comments (Before/After)
</br></br>
- Also an unnecessary comment about a fixed bug was removed
> fix(theme): correct goto_word and comments background in `flatwhite.toml`

- languages.toml
`.irbrc` is an init script written in Ruby that gets sourced when starting `irb`
> feat(ruby): detect `.irbrc` file as ruby

- languages.toml
Used to configure the WSL2 VM on Windows. Format documented as being ini [here](https://learn.microsoft.com/en-us/windows/wsl/wsl-config).
> feat: detect `.wslconfig` as ini filetype

- languages.toml
Examples of use:
- `runhaskell` is used in [Pandoc filters](https://pandoc.org/filters.html)
- `stack` is listed in the [official documentation](https://docs.haskellstack.org/en/stable/topics/scripts/) of stack.
> feat: add `runhaskell` and `stack` as haskell shebangs

- runtime/queries/scheme/highlights.scm
the arguments to each case of a `case-lambda` are variables, but the first one was previously marked as a function. additionally i think it makes sense to mark the case-lambda also as a keyword.
before:
after:
(note: i am using a custom version of the solarized light theme where variables are blue and functions are violet)
> queries(scheme): mark arguments of case-lambda as @variable, mark case-lambda as @keyword

- runtime/queries/scheme/highlights.scm
before:
after:
(note: i am using a custom version of the solarized light theme where variables are blue and functions are violet)
additionally i also converted all one-space indents to two spaces and switched from a `#match?` to a `#any-of?`.
(note: i wanted to add this to #14386, but i was too slow lol)
> queries(scheme): mark the variables of do as `@variable`

- languages.toml
- `fods` is the file extension used for a flat xml representation of a OpenDocument Spreadsheet file
- and `fodt` is the one used for OpenDocument Text file
> feat: add `fods` and `fodt` extensions to `xml` filetype

- book/src/generated/lang-support.md
- runtime/queries/kdl/injections.scm
- runtime/queries/kdl/tags.scm
- **queries(kdl): basic tags.scm based on nodes that hold objects**
representing *every* named node is a bit overgrabby — ends up being annoying to filter through, when usually you want to get to some object to them do stuff in
- **queries(kdl): injections for niri**
I feel like most people's usage of kdl is the niri config file \
I wrote the queries in a way where they make double sure it's the niri config structure, before actually committing the injection, so that we don't annoy people with an unexpected injection
> kdl queries: basic tag.scm and niri injections

- languages.toml
- runtime/queries/hurl/highlights.scm
Version 6.0.0 of [hurl](https://hurl.dev/blog/2024/12/04/announcing-hurl-6.0.0.html) added some new operators and 3 shorthand alias names for section names. This PR adds highlighting support for them.
> feat(highlights): add missing highlight for `hurl` from version 6.0.0

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/gitlab-ci/highlights.scm
- runtime/queries/gitlab-ci/indents.scm
- runtime/queries/gitlab-ci/injections.scm
- runtime/queries/gitlab-ci/rainbows.scm
- runtime/queries/gitlab-ci/tags.scm
- runtime/queries/gitlab-ci/textobjects.scm
- runtime/queries/yaml/injections.scm
Split injections specific to [GitLab CI](https://docs.gitlab.com/ci/) `.gitlab-ci.yml` files into its own separate language name `gitlab-ci`.
In addition this PR adds:
- [gitlab-ci-ls](https://github.com/alesbrelih/gitlab-ci-ls) as a language server for `gitlab-ci` language.
- Additional `bash` injections for keys: `command`, `entrypoint` and `pre_get_sources_script`.
- Adds `tags.scm` to select jobs and variables
- Extends the `highlights.scm` to add more specialized captures to elements that have unique meaning in the context of GitLab CI e.g. the stage names `.pre`, `build`, `test`, `deploy` and `.post`.
**Showcase**
> feat(languages): add `gitlab-ci` language specialized from `yaml`

- languages.toml
feat(languages): add podman `*.conf` files to `toml` file-types
File paths are documented here:
- https://docs.podman.io/en/latest/markdown/podman.1.html#configuration-files
- https://github.com/containers/common/blob/main/pkg/config/containers.conf
- https://man.archlinux.org/man/containers.conf.5.en
> feat(languages): add podman `*.conf` files to `toml` file-types

- helix-core/src/syntax/config.rs
- helix-term/src/commands/dap.rs
Add support for JSON objects in debugger template args
```toml
[language.debugger.templates.args.pathMappings]
"/some/path/on/server" = "/some/path"
"/another/server/path" = "/another/local/path"
```
> Extend DebugArgumentValue to support toml tables

- helix-term/src/ui/picker.rs
- helix-tui/src/text.rs
- helix-tui/src/widgets/table.rs
- helix-tui/tests/text.rs
`helix_tui::widgets::Cell` contains styled `Text`. In the case of a styled `Cell` with styled `Text`, the styled `Text` would override the style of the `Cell`. This led to errors where it seemed `ui.text.directory` had more priority than `ui.menu.selected` and `ui.text.focus`. This change also adds some tests from doc comments of `Text` and makes them actually tested.
Closes: #13768
Before/After
Autocomplete:
Picker:
> fix: Make `Table` `Cell`s set the style of their text

- book/src/editor.md
- helix-view/src/clipboard.rs
Win32Yank clipboard provider is referred to as `win-32-yank` in docs and in `:show-clipboard-provider`. But the actual name as per `serde`'s translation is `win32-yank`. 
Currently if you set `clipboard-provider` to `win-32-yank` it results in a bad config error. So I feel like it would be better to keep it same in all places to avoid confusion. 
```
Bad config: unknown variant `win-32-yank`, expected one of `pasteboard`, `wayland`, `x-clip`, `x-sel`, `win32-yank`, `tmux`, `termux`, `termcode`, `custom`, `none`
in `clipboard-provider`
```
> fix(helix-view/clipboard): use serde generated name for Win32Yank

- helix-term/src/ui/statusline.rs
Previously, when switching between split panes, the statusline for unfocused panes always used a fixed-width space, regardless of the actual mode string length. This caused the statusline to shift or jump inconsistently as panes gained or lost focus. Now, the empty space matches the mode string’s width, keeping the statusline aligned when moving between panes.
https://github.com/user-attachments/assets/8215b213-d25a-4131-97e8-c3a7dafbc67f
https://github.com/user-attachments/assets/238676ae-4a85-4466-b797-5ef4f157fee8
```toml
[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = [
"diagnostics",
"selections",
"position",
"file-encoding",
"file-line-ending",
"file-type",
]
separator = "|"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
```
> statusline: dynamic padding for unfocused mode

- book/src/editor.md
- helix-term/src/ui/mod.rs
- helix-term/src/ui/picker.rs
- helix-view/src/editor.rs
This implements #14071.
Marked as draft because some things remain to do, such as making this configurable.
Also some potential IO errors are silently ignored, mostly unlikely to append (dir with no child, after it has been count to 1, possible if child dir is suppress after the count…). However, this should at least be tested on different environments (I have tested only on Linux, issues with file read rights can vary on different systems), and maybe better error handling could be made.
Selecting `..` goes only one dir up, so intermediate directories remain accessible.
> feat: flatten single-child dirs in file explorer

- runtime/themes/licenses/zenburn.license
- runtime/themes/zenburn.toml
As the title suggests.
Building on @theli-ua 's work, I've attempted to faithfully port the complete color palette and map them to tree-sitter scopes. I like the way it turned out, but have only checked python, rust, and markdown highlighting, so this PR could benefit from additional set of eyes and maybe some testing, e.g., by @theli-ua :)
ps: also included the missing license file
> Update zenburn theme

- runtime/themes/doom-one.toml
- Updated `ui.popup.info` background color
- Added `ui.virtual.jump-label`
Updated doom-one theme popup color, because otherwise is very hard to see the popup.
Original
Updated theme
> Update doom-one theme

- languages.toml
As specified here: https://iterm2.com/documentation-preferences-profiles-colors.html
Apparently, a formatter removed a trailing space on another line as well. 🤷‍♂️
> Add .itermcolors to xml file types

- runtime/queries/scheme/highlights.scm
mark define-values as `@keyword` and mark its args as `@variable`.
before:
after:
as a drive-by this converts all of the `#match?`es, that just had a list of names to `#any-of?`, to avoid extremely long lines and having to escape symbols like `*` and `+`.
> queries(scheme): properly highlight define-values

- book/src/generated/lang-support.md
- languages.toml
- runtime/queries/eiffel/highlights.scm
- runtime/queries/eiffel/indents.scm
- runtime/queries/eiffel/textobjects.scm
Adding support for the Eiffel programming language.
- grammar: https://github.com/imustafin/tree-sitter-eiffel.git
- language-server: https://github.com/alschena/eiffel-tools.git
> feat(languages): add support for the eiffel programming language.

- languages.toml
See `HISTFILE` in [POSIX](https://pubs.opengroup.org/onlinepubs/9799919799/utilities/sh.html)
> feat(langs): recognize `.sh_history`

- flake.lock
- flake.nix
Currently it would require me to override it which is annoying.
> Nix: Use `lib.systems.flakeExposed` so that I can build Helix for RISC-V

- Cargo.lock
- Cargo.toml
- helix-dap/Cargo.toml
- helix-dap/src/lib.rs
- helix-dap/src/transport.rs
- helix-lsp/Cargo.toml
- helix-lsp/src/lib.rs
- helix-lsp/src/transport.rs
This PR adds `sonic_rs` as a dependency and replaces the `serde_json::from_str` implementation for deserializing  `ServerMessage` and `Payload` . This results in an order of magnitude less `cycles` and substantially less `page-faults`.
In profiling, `simd_json` was also chosen as a candidate. These are the samples with a percentage value with `serde_json` being the baseline at 100%. Total samples is for the `hx` process, `__clone` is the base stack in which the LSP messages are parsed, and `process_server_message` is the `Transport::process_server_message` method.
Metric | serde_json | simd_json | sonic_rs
-- | -- | -- | --
Total Samples (hx) | 15,200,000,000 (100%) | 14,600,000,000 (96.05%) | 626,400,000 (4.12%)
__clone3 Samples | 9,460,000,000 (100%) | 8,791,000,000 (92.92%) | …
> perf(transport): switch to `sonic_rs` for parsing
