helix-editor/helix

.gitmodules, helix-syntax/src/lib.rs, languages.toml, runtime/queries/elixir/highlights.scm
Seems the queries were committed but not the language settings
=> Added elixir syntax

helix-term/src/main.rs
=> Use config_dir for logging, create config_dir

helix-term/src/compositor.rs, helix-tui/src/terminal.rs
=> autoresize terminal in compositor render

Cargo.lock, helix-term/Cargo.toml, helix-term/src/main.rs
That means help, version and friends finally work as intended now
=> Drop pico-args in favour of a hand rolled parser

helix-view/src/document.rs
I missed the fast return.
Fix #89
=> Fix undo redo

helix-syntax/src/lib.rs, languages.toml, runtime/queries/haskell/highlights.scm, runtime/queries/haskell/locals.scm
=> Restored haskell syntax

.github/workflows/build.yml
Runs every day as cron. Add matrix for test, includes windows and macos.
=> Add more coverage for CI

helix-core/src/lib.rs, helix-core/src/movement.rs, helix-core/src/words.rs, helix-term/src/commands.rs, helix-term/src/keymap.rs, helix-tui/tests/terminal.rs
It seemed to panic when I pressed too many times, but that is from
lsp side. I missed this from neovim when I first used kakoune, I wish it really have this.
=> Add ctrl-w in insert mode

helix-term/src/application.rs, helix-term/src/commands.rs, helix-term/src/keymap.rs, helix-term/src/ui/editor.rs, helix-view/src/document.rs
=> Add diagnostics keybindings

helix-term/src/main.rs
=> Create all parent directories for config and cache

helix-term/src/ui/completion.rs
Tested using pyright as was used in the linked issue and completion works as expected.
Closes: #131
=> completion: Fix unimplemented autocomplete

book/src/keymap.md, helix-term/src/commands.rs, helix-term/src/keymap.rs
=> commands: Add replace with yanked as `R`

helix-lsp/src/client.rs, helix-lsp/src/lib.rs, helix-view/src/editor.rs
=> Don't panic on LSP not starting/misbehaving 

helix-view/src/document.rs
=> Add missing newline to end of file on load

book/src/keymap.md, helix-core/src/comment.rs, helix-core/src/indent.rs, helix-core/src/lib.rs, helix-term/src/commands.rs
=> commands: Add goto first non-whitespace char of line

helix-term/src/commands.rs, helix-term/src/ui/editor.rs, helix-view/src/editor.rs
=> Support go to line 1

runtime/queries/elixir/highlights.scm
=> Updated elixir queries to fix crash

helix-lsp/src/client.rs, helix-lsp/src/lib.rs, helix-term/src/application.rs, helix-view/src/editor.rs
=> lsp: Display LSP progress messages

helix-lsp/src/client.rs, helix-lsp/src/lib.rs, helix-term/src/application.rs, helix-term/src/commands.rs
=> lsp: Check bounds when converting lsp positions

README.md, helix-core/src/lib.rs, helix-core/src/syntax.rs
=> Add more ways to detect runtime directory

helix-term/src/ui/picker.rs
Follow window mode and vim behavior, x seemed weird.
=> Change picker horizontal split to h

book/src/keymap.md, helix-lsp/src/client.rs, helix-lsp/src/lib.rs, helix-term/src/commands.rs
use the lsp document_symbol request
=> add symbol picker

helix-term/src/commands.rs, helix-term/src/ui/prompt.rs, helix-view/src/document.rs
I'm wondering if the name of the command should be `wq` or perhaps `write_quit` and then the alias `wq`.
=> commands: Add more write commands

contrib/themes/boster.toml
=> Add `bogster` theme

contrib/onedark.theme
=> Add onedark theme

contrib/themes/onedark.toml
Follow up from https://github.com/helix-editor/helix/pull/249#issuecomment-860526671 (sorry for the clunkiness 😅 )
=> Correct onedark theme file location

book/src/configuration.md, contrib/themes/bogster.toml, contrib/themes/ingrid.toml, contrib/themes/onedark.toml, helix-term/src/ui/editor.rs, theme.toml
Enables changing the color of the selection which was previously hard coded.
=> Add ui.selection to theme.toml

book/src/configuration.md, book/src/keymap.md
- Wrapped appropriate table elements in inline code blocks
- Added links to different modes
- Capitalised table elements'
=> Format docs for better readability

book/src/configuration.md
=> Fix Markdown typos

contrib/themes/bogster.toml, contrib/themes/ingrid.toml, contrib/themes/onedark.toml, helix-term/src/ui/editor.rs, theme.toml
=> Add `ui.statusline.inactive`, use `ui.statusline` for statusline text

helix-term/src/application.rs, helix-term/src/commands.rs, helix-term/src/config.rs, helix-term/src/keymap.rs, helix-term/src/main.rs, helix-term/src/ui/editor.rs, helix-view/src/document.rs, helix-view/src/input.rs, helix-view/src/lib.rs
Now also make use of Deserialize for Config.
Haiyaa still fail, failed to parse string as enum. Probably related to https://github.com/alexcrichton/toml-rs/issues/302.
cc @PabloMansanet
=> Refactor key into helix-view

book/src/keymap.md, book/src/remapping.md, book/src/themes.md
=> Fix docx formatting and links

book/src/configuration.md, helix-lsp/src/lib.rs, helix-term/src/application.rs, helix-term/src/commands.rs, helix-term/src/compositor.rs, helix-term/src/config.rs, helix-term/src/ui/editor.rs, helix-term/src/ui/mod.rs, helix-term/src/ui/spinner.rs
I'm wondering if emoji is a good idea :laughing:  I was thinking of doing triple dots like:
```
.
..
...
```
=> Add lsp progress spinner, add option to enable lsp messages (off by default)

Cargo.lock, helix-core/src/line_ending.rs, helix-term/src/commands.rs, helix-term/src/ui/editor.rs, helix-view/src/document.rs
- Fix remaining places where a single-character line ending is assumed.
- Fix silly bug where I accidentally flipped the condition in which Helix adds a line ending to the end of the file on load.
=> Missed some items in the CRLF PR.

theme.toml
I don't know which of them were meant to be left there, so I made a guess
=> Remove duplicate properties from theme.toml

helix-term/src/ui/picker.rs
=> Fix picker item width overflow

helix-term/src/commands.rs
Fixes #363.
I set out to fix issue #363, but after fixing it discovered some
other things were wrong with the command while testing.  In
summary:
- #363 was because it was still assuming a line ending width
of 1 char in its indexing calculations, even when actually
inserting CRLF.
- Aside from #363, it actually needed to set `line_end_index`
to zero for *all* calculations that use it when line == 0,
but it was only doing so for a single calculation.
=> Fix open-new-line command for CRLF, as well as other bugs.

helix-term/src/commands.rs
=> Fix goto line end

helix-core/src/graphemes.rs, helix-term/src/ui/editor.rs
Fixes #381.  I was trying to change an index value that... wasn't
even an index value.
=> Fix silly mistake in previous phantom line bug fix.

helix-tui/src/buffer.rs
Follow up of #375 
cc @sudormrfbin
=> Trait width method use refactor

runtime/themes/onedark.toml
Add colors for matching brace, non primary selections, inactive statusline.
=> Update onedark theme

helix-term/src/commands.rs
=> Add more modes to infobox

languages.toml
Fixes toggle_comment not finding the correct language comment token
=> Fixes toggle_comment not finding the correct language comment token

helix-term/src/commands.rs, helix-term/src/compositor.rs, helix-term/src/ui/picker.rs
Inspired by space ' in doom emacs.
=> Resume last picker

helix-view/src/document.rs
=> Mark reloaded buffers as unchanged

book/src/keymap.md
=> Add missing keybinds to docs

book/book.toml
Stolen from https://github.com/rust-lang/wg-async-foundations/pull/225
=> Quick edit page

helix-term/src/commands.rs, helix-term/src/keymap.rs
=> Add `goto_last_line` command, and bind it to `ge`.

helix-core/src/surround.rs, helix-core/src/textobject.rs
=> Fix buggy surround behavior from #376.

helix-core/src/position.rs
Particularly the effect of the `limit_before_line_ending`
parameter.
=> Document `pos_at_coords` better.

Cargo.lock
=> Bump chardetng to 0.1.14

.gitmodules, languages.toml, runtime/queries/ledger/highlights.scm, runtime/queries/ledger/injections.scm
Might need to update later since the current one highlight does not
work very well yet.
=> Add ledger tree-sitter

helix-core/src/match_brackets.rs
=> Fixes crash on empty rust file.

helix-syntax/build.rs
=> Added "/utf-8" to Windows compilation options.

helix-core/src/auto_pairs.rs
=> Fix auto pairs return wrong selection

helix-term/src/ui/picker.rs
=> use `ui.text.focus` for the picker

Cargo.lock, helix-term/src/ui/editor.rs, helix-term/src/ui/markdown.rs, helix-term/src/ui/menu.rs, helix-term/src/ui/picker.rs, helix-view/src/graphics.rs, helix-view/src/view.rs
Introduces methods that can be chained to construct new Rects out of pre-existing ones.
=> Refactor new Rect construction

helix-lsp/src/transport.rs
There could still be more unwraps for this that need to be handled. Luckily I have a very broken lsp to test with :sweat_smile: 
I'll remove draft status when I'm sure there are none left.
=> don't panic on defunct lsp process

helix-term/src/ui/info.rs
info component style config use ui.info ui.info.text
=> info component style config use ui.info ui.info.text

runtime/themes/monokai.toml
I don't intend to use this, but I thought it was cool enough that maybe others might like it.
=> Add Monokai Theme

book/src/themes.md, helix-term/src/ui/menu.rs
=> add menu text style

helix-term/src/commands.rs
=> Expand `~` in `change-current-directory` command

helix-lsp/src/lib.rs, helix-view/src/editor.rs
=> Log errors produced when trying to initialize the LSP

helix-term/src/commands.rs
As suggested in #777 , smart case option is now passed to `RegexMatcherBuilder` in `global_search`.
=> Allow smart case in global search

runtime/queries/zig/highlights.scm, runtime/queries/zig/indents.toml
- update tree-sitter-zig subproject
- use highlights.scm from upstream, just use helix scopes
- update indents.toml, this one actually works
=> Zig tree-sitter rework

book/src/keymap.md, helix-term/src/keymap.rs
This is a minor quality-of-life improvement for my own usage, having come from vim. Opening a PR in case anyone else wants this.
=> Add arrow-key bindings for window switching

book/src/keymap.md
https://github.com/helix-editor/helix/discussions/949#discussioncomment-1580777
=> Add better description for copy_selection command

book/src/SUMMARY.md, book/src/guides/adding_languages.md, book/src/languages.md
Add a section in the book about language-specific settings and the languages.toml file.
=> feat(book/src/languages.md)

helix-core/src/lib.rs
=> fix(core): stop merging array toml config values

book/src/remapping.md
=> added Down keymapping.

.gitmodules, languages.toml, runtime/queries/glsl/folds.scm, runtime/queries/glsl/highlights.scm, runtime/queries/glsl/indents.scm, runtime/queries/glsl/indents.toml, runtime/queries/glsl/injections.scm, runtime/queries/glsl/locals.scm
Hello, I added glsl language syntax highlighting.
I tried to use glslls https://github.com/svenstaro/glsl-language-server as lsp but couldn't get things working.
=> glsl  support

runtime/themes/solarized_light.toml
=> add solarized_light theme

helix-term/src/commands.rs
=> buffer picker add is_modifier flag

book/src/keymap.md, helix-core/src/selection.rs, helix-term/src/commands.rs, helix-term/src/keymap.rs
Closes #1062.
I have added the keybind to `A-K`, let me know if it should be changed.
=> Add `remove_selections` command

book/src/keymap.md
=> docs: Mark more keybinds that require LSP and treesitter

helix-term/src/commands.rs
=> Ensure cursor in view after pipe

helix-term/src/main.rs
=> revert log truncation (#895)

runtime/themes/spacebones_light.toml
This adds a new light theme: spacebones.
=> Add spacebones light theme

README.md
=> Fix "good first issue" link

.github/ISSUE_TEMPLATE/bug_report.md
=> Fix bug report template use wrong hx version

.gitmodules, book/src/themes.md, languages.toml, runtime/queries/llvm/highlights.scm
=> Add language support for LLVM IR

runtime/themes/rose_pine.toml, runtime/themes/rose_pine_dawn.toml
To add rose_pine_dawn color scheme based from rose_pine.toml in the repo.  So I give credits to @raygervais for his effort.
=> adds: rose_pine_dawn.toml colorscheme

helix-term/src/keymap.rs
This fixes tests in release mode.
=> Assert in release mode too on duplicate keys

book/src/remapping.md
=> Update book to include typable command remapping

helix-core/src/movement.rs, helix-term/src/commands.rs, helix-term/src/ui/prompt.rs
Array iterators are now implicit.
=> apply recent nightly suggestions

book/src/keymap.md, helix-term/src/commands.rs
Suggested by @Robert-M-Muench https://github.com/helix-editor/helix/discussions/1251#discussioncomment-1795072
=> Change text for gg to explain <n>gg

.gitmodules, book/src/generated/lang-support.md, languages.toml, runtime/queries/fish/highlights.scm, runtime/queries/fish/indents.toml, runtime/queries/fish/injections.scm, runtime/queries/fish/textobjects.scm
The highlights were copied and modified from
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/fish/highlights.scm
=> Add fish highlighting

helix-core/src/match_brackets.rs
=> Fix match brackets comment

runtime/themes/rose_pine.toml, runtime/themes/rose_pine_dawn.toml
add markup scope to the rose pine themes.
=> chore: update rose pine themes to support markup

book/src/generated/lang-support.md, runtime/queries/ruby/indents.toml
=> Add ruby indents

helix-tui/README.md
=> Fix minor grammatical error

helix-term/src/config.rs, helix-view/src/theme.rs
It was missing in a few places.
=> Put some tests behind #[cfg(test)]

runtime/queries/zig/highlights.scm, runtime/queries/zig/indents.toml
use latest upstream version
move comptime from @keyword.function to @keyword.directive
use AssignOp
enhance indents
=> Update zig tree-sitter

helix-term/src/commands.rs
When writing all documents, fmt wouldn't be run.
Run fmt in close all implementation so that all documents
are formatted if necessary.
Fixes: https://github.com/helix-editor/helix/issues/1442
=> fix(commands): run fmt for all documents being closed

Cargo.lock, helix-term/Cargo.toml, helix-term/src/ui/markdown.rs
=> Dependabot/cargo/pulldown cmark 0.9.1

runtime/themes/monokai_pro.toml, runtime/themes/monokai_pro_machine.toml, runtime/themes/monokai_pro_octagon.toml, runtime/themes/monokai_pro_ristretto.toml, runtime/themes/monokai_pro_spectrum.toml
Screenshots for monokai pro:
Relative: #1525
=> add markup support for monokai pro themes

helix-view/src/document.rs
Refactor methods in `helix-view/src/document.rs`.
=> Refactor document methods

book/src/generated/typable-cmd.md
=> Add new dap commands to docs

runtime/themes/rose_pine.toml, runtime/themes/rose_pine_dawn.toml
Update rose_pine themes per #1618
=> chore(theme): update markup styles for rose_pine themes

book/src/themes.md, helix-term/src/ui/info.rs, runtime/themes/solarized_dark.toml, runtime/themes/solarized_light.toml
This makes it play nicely with https://github.com/helix-editor/helix/pull/1714.
=> Rename infobox theme scopes

runtime/themes/rose_pine.toml, runtime/themes/rose_pine_dawn.toml
also, base05 does not exist in the themes so update it to foam
=> chore(theme): apply renamed infobox theme scopes for rose_pine themes

book/src/generated/lang-support.md, languages.toml
This requires a recent version of Solidity 0.8.11+
https://docs.soliditylang.org/en/latest/installing-solidity.html
=> Add LSP support for Solidity

helix-core/src/syntax.rs
Just something I saw while working on #1854
=> Fix typo in query parsing error message

grammars.nix
This removes IFD when using Nix >= 2.6.0
=> Use fromTOML on Nix >= 2.6.0

languages.toml, runtime/queries/bash/highlights.scm
=> Update bash tree sitter

runtime/themes/dark_plus.toml
=> [dark_plus] remove `ui.text` background

helix-term/src/commands.rs
=> Add paragraph to last motion

helix-core/src/movement.rs
Fix #1928
Oh, I wonder how I write the correct variable name but wrong logic, maybe because I copy pasted from prev logic. T_T
=> Fix next paragraph logic over muliple blank lines

runtime/themes/boo_berry.toml
Hello! I've created this theme specifically for helix and been using it locally for a few months. It's low contrast and has a magical color palette. Below is a preview of how it looks in Rust and Zig. I'm not sure if you are still accepting new themes, but if so, I would be honored to have boo_berry be among them!
=> add boo_berry theme

helix-loader/src/grammar.rs
connects https://github.com/helix-editor/helix/issues/1973
=> remove hardcoded '/' from grammar source path

book/src/generated/lang-support.md, languages.toml
This one has no formatting built in.
=> Add default language server for CSS

book/src/generated/lang-support.md, languages.toml
See https://github.com/ocaml/ocaml-lsp
=> Add language server command for OCaml

runtime/themes/dracula.toml
Selections now maintain syntax highlighting.
=> Improve Dracula Theme selections (#2075)

book/src/themes.md
Just added a few descriptions to theme scopes that initially confused me.
=> Additions to 'themes' section of docs

runtime/themes/onedark.toml
=> Remove dim attribute in onedark ui.linenr

book/src/generated/lang-support.md, languages.toml, runtime/queries/devicetree/highlights.scm, runtime/queries/devicetree/indents.scm
https://elinux.org/Device_Tree_Reference
https://github.com/joelspadin/tree-sitter-devicetree
=> feat(lang): add devicetree (Flattened Device Tree Source)

runtime/themes/night_owl.toml
Original: https://marketplace.visualstudio.com/items?itemName=sdras.night-owl
Color palette from: https://github.com/haishanh/night-owl.vim
I've been tweaking it for a bit but there is still room for suggestions. I can also update the wiki with the theme screenshot if it is merged.
=> Add Night Owl Color Theme.

helix-term/src/commands.rs
Looks better and is consistent with the rest, nothing else.
=> feat(term): wrap command palette in overlay

languages.toml
This just adds inc files to php (another common types of files for php).
=> languages: add inc files to php

book/src/generated/lang-support.md, languages.toml, runtime/queries/meson/highlights.scm, runtime/queries/meson/indents.scm
https://mesonbuild.com/Syntax.html
https://github.com/bearcove/tree-sitter-meson
=> feat(lang): add Meson language support

helix-term/src/ui/popup.rs
#2148
Before:
https://user-images.githubusercontent.com/55039048/168697627-65871924-6b04-4ad6-a6f4-bfbe355a8d5e.mp4
After:
https://user-images.githubusercontent.com/55039048/169089108-b4a864b6-922c-4a15-9532-3b403412cb60.mp4
=> feat(helix-term): deletion of lines affecting popup scrolling

helix-term/src/ui/prompt.rs, runtime/themes/bogster.toml, runtime/themes/ingrid.toml, runtime/themes/monokai.toml, runtime/themes/monokai_pro.toml, runtime/themes/monokai_pro_machine.toml, runtime/themes/monokai_pro_octagon.toml, runtime/themes/monokai_pro_ristretto.toml, runtime/themes/monokai_pro_spectrum.toml, runtime/themes/nord.toml, runtime/themes/onedark.toml, runtime/themes/onelight.toml, theme.toml
This should fix https://github.com/helix-editor/helix/issues/2379
=> use `ui.menu` instead of `ui.statusline` for command completion menu theme

base16_theme.toml, runtime/themes/autumn.toml, runtime/themes/base16_default_dark.toml, runtime/themes/base16_default_light.toml, runtime/themes/rose_pine.toml, runtime/themes/rose_pine_dawn.toml, theme.toml
This PR corrects issues in some TOML files stored in this repository.
=> fix: invalid toml in themes

runtime/themes/autumn.toml
This highlights the status line of the active window.
=> Highlight active window in Autumn theme

book/src/generated/lang-support.md, languages.toml
lua lsp https://github.com/sumneko/lua-language-server
=> Add lua lsp

CHANGELOG.md
See also https://github.com/helix-editor/website/pull/10
=> add 22.05 changelog notes

README.md
Updates the README instruction so it follows the version in the web docs
=> Update from-source install instruction in README

book/src/generated/lang-support.md, languages.toml, runtime/queries/openscad/highlights.scm
This adds basic support for [openscad](https://openscad.org/index.html) and highlighting.
closes #1415
=> support for openscad

flake.lock, flake.nix, grammars.nix, shell.nix
Formats nix files with alejandra. Updates nix flake inputs. Some nix code is refactored.
=> chore(nix): format nix files with alejandra, update deps, minor code refactors

runtime/tutor.txt
This adds the missing variant of entering insert mode
to the chapter 1 recap section.
=> Expand chapter one recap of tutor

runtime/tutor.txt
=> Clarified the text in chapter 3 of the tutor

languages.toml, runtime/queries/heex/highlights.scm
See https://github.com/phoenixframework/tree-sitter-heex/pull/16 for more information on what changed.
cc @the-mikedavis
=> HEEx: upgrade version and support new special_attribute node

helix-term/src/commands/lsp.rs, helix-term/src/ui/info.rs, helix-term/src/ui/markdown.rs, helix-term/src/ui/picker.rs, helix-term/src/ui/popup.rs, helix-term/src/ui/prompt.rs, helix-tui/src/layout.rs, helix-view/src/graphics.rs
I refactored the Margin implemention with the intent to use it to give some padding for the completion popup, but didn't end up using it. Cherry-picking the commit anyways since it looks useful.
=> Refactor Margin for fine grained control

languages.toml
see https://github.com/nickel-lang/tree-sitter-nickel/pull/9
and  https://github.com/tweag/nickel/pull/737
=> update tree-sitter-nickel to include ' in ident

helix-term/src/ui/editor.rs
Fixes #2856.
This appears to work but I don't have a great sense of any other side-effects. Needs a bit of testing.
=> fixes #2856 by resetting style on diagnostic

book/src/keymap.md
It should only repeat the last insert by design, see #2868
=> book: fix the description of dot repeat

runtime/themes/meliora.toml
My own theme, hope this is fine, it's my first pull request.
=> add meliora theme

runtime/themes/meliora.toml
added cursorline highlight, improved some other highlights
=> update meliora theme

helix-term/src/ui/editor.rs
- Simplified match statements by destructuring `MouseEvent` struct at the top and then matching on `event.kind`.
- Extracted out closures for calculating (1) position and view of mouse click and (2) gutter coordinates and view of mouse click.
=> Refactor handling of mouse events

book/src/themes.md
Docs re: https://github.com/helix-editor/helix/pull/2170#issuecomment-1167075064
=> add docs for cursorline scopes

runtime/themes/solarized_dark.toml, runtime/themes/solarized_light.toml
Also fix `ui.menu` to be consistent with the light theme.
=> add mode colors to solarized

languages.toml
Update haskell roots configuration for support of stack and cabal projects.
=> Add Haskell roots

runtime/themes/autumn.toml, runtime/themes/autumn_night.toml
Under some lightning conditions, a high contrast theme is preferable.
=> Add autumn night theme

book/src/install.md, book/src/title-page.md
=> book: add wiki links to the title page and install page

helix-term/src/commands.rs
3n would go to the third next match
=> respect count for selecting next/previous match

runtime/themes/onelight.toml
Add keyword.function and keyword.storage.type for TS
=> Add `color-modes` for onelight theme

runtime/themes/monokai.toml
=> Highlight constructor in monokai theme

runtime/themes/ayu_dark.toml, runtime/themes/ayu_light.toml, runtime/themes/ayu_mirage.toml
The themes are based on the three variants of the [ayu](https://github.com/ayu-theme/ayu-colors) colours.
Note that I've been giving more focus on the Dark theme as it's the one I use.
Hope you enjoy it 😄
=> Add ayu themes

book/src/generated/lang-support.md, languages.toml, runtime/queries/gotmpl/highlights.scm, runtime/queries/gotmpl/injections.scm
Adds Go Template highlighting support.
=> feat(tree-sitter): :sparkles: add go template support

runtime/themes/nord.toml, runtime/themes/nord_light.toml
Add color-modes to nord and nord_light themes
=> Nord color modes

helix-term/src/commands.rs
=> Use OR of all selections in search_selection command

README.md
Basic formatting and path changes.
=> Update README command table

helix-term/src/ui/prompt.rs
=> Don't add empty prompt input to history

book/src/generated/lang-support.md, languages.toml, runtime/queries/dot/highlights.scm, runtime/queries/dot/injections.scm
- <https://graphviz.org/>
- lsp <https://github.com/nikeee/dot-language-server>
-  `npm i -g dot-language-server` 
- tree-sitter <https://github.com/rydesun/tree-sitter-dot>
=> Add Graphviz Dot lang support

runtime/themes/flatwhite.toml
The flatwhite theme!
Inspired by https://github.com/biletskyy/flatwhite-syntax and the popular [doom-flatwhite](https://github.com/doomemacs/themes/blob/master/themes/doom-flatwhite-theme.el) version.
Here's a quick screenshot:
=> Flatwhite Theme

helix-term/src/commands.rs
=> Fix align_selection behaviour with tabs

runtime/themes/gruvbox.toml, runtime/themes/gruvbox_light.toml
Add color-modes to gruvbox and gruvbox_light themes
=> fix: gruvbox color modes

runtime/queries/python/highlights.scm, runtime/queries/python/locals.scm
Just improved some things I noticed.
=> Improve Python queries, add locals

runtime/themes/rose_pine_moon.toml
This is based on [Rosé Pine theme](https://github.com/helix-editor/helix/blob/master/runtime/themes/rose_pine.toml)...
[Rose Pine Moon palette.](https://rosepinetheme.com/palette)
There's 3 reasons why i've opened this pr:
1) I don't like Rose Pine theme, the Moon version is much more enjoyable
2) I don't know any possible way to configure the theme in user config file...
3) I don't want to modify `/var/lib/helix/runtime/themes/` folder...
And I must say, helix is great. I liked it very much... Thanks
=> Rosé Pine Moon Theme

book/src/generated/lang-support.md, languages.toml, runtime/queries/slint/highlights.scm, runtime/queries/slint/indents.scm, runtime/queries/slint/locals.scm
<https://slint-ui.com/>
lsp: <https://github.com/slint-ui/slint/tree/HEAD/tools/lsp>
tree-sitter-slint: <https://github.com/jrmoulton/tree-sitter-slint>
=> Add slint-ui support

runtime/themes/ayu_dark.toml, runtime/themes/ayu_light.toml, runtime/themes/ayu_mirage.toml, runtime/themes/base16_transparent.toml
=> Fix Typos in base16_transparent

helix-term/src/ui/mod.rs
closes https://github.com/helix-editor/helix/issues/3354
Might want to do something more complicated later if we want to make multiple themes with the same name possible.
=> Remove duplicate entries from theme picker

helix-core/src/line_ending.rs
=> Fix failing test with unicode-lines feature

runtime/themes/papercolor-light.toml
based on https://github.com/NLKNguyen/papercolor-theme
=> theme: add papercolor light

runtime/queries/awk/injections.scm
=> AWK Regex injection

book/src/generated/lang-support.md, languages.toml, runtime/queries/pascal/highlights.scm, runtime/queries/pascal/injections.scm, runtime/queries/pascal/textobjects.scm
=> Pascal support

runtime/themes/fleetish.toml
Based on the unreleased JetBrains Fleet. 
Passes themelint #3234
=> Fleetish theme

helix-view/src/input.rs
=> Allow less than and greater than in macros

runtime/queries/rust/injections.scm
=> Highlight SQL in `sqlx::{query,query_as}!()` in Rust

runtime/tutor.txt
* Add `-->` which is referred to
* Fix a typo
=> Fix typos in tutor

runtime/themes/rasmus.toml
Porting over a color theme that I use on `neovim` to `helix`.
=> Theme: Rasmus

helix-term/src/commands/typed.rs
=> Fix :reflow panic by enusring cursor in view

book/src/generated/lang-support.md, languages.toml, runtime/queries/sml/highlights.scm
Hi
This is my first PR and I hope everything is fine, I had to create a fork for the tree-sitter grammar sources like in [#1854](https://github.com/helix-editor/helix/pull/1854) but apart from that everything went smoothly thanks to the nice docs
I'm really enjoying Helix, nice work!
=> Add syntax highlighting for SML

book/src/generated/lang-support.md, languages.toml, runtime/queries/jsonnet/highlights.scm
Add jsonnet language and syntax highlight. The best tree-sitter grammar as of now seems to be: https://github.com/sourcegraph/tree-sitter-jsonnet (used in the PR).
=> feat(languages): jsonnet

runtime/themes/papercolor-dark.toml
Currently looks like this :smile:
=> Add papercolor dark variant

book/src/generated/lang-support.md, languages.toml, runtime/queries/godot-resource/highlights.scm
godot-resource hightlight for tscn, tres
- https://github.com/PrestonKnopp/tree-sitter-godot-resource
=> Add godot resource support

book/src/generated/lang-support.md, languages.toml, runtime/queries/gdscript/highlights.scm, runtime/queries/gdscript/textobjects.scm
- Add textobjects.scm
- Fix class highlight
- Fix set default indent to `\t`
=> Add textobject for gdscript

book/src/usage.md
=> Update usage.md with paragraph textobject

runtime/themes/nord.toml
- Add markup styles
- Replace custom colors with Nord colors
- Clean up code spacing
=> Clean Up Nord Theme

helix-term/src/commands/lsp.rs
=> Remove border from code actions popup

runtime/themes/flatwhite.toml
@AlexanderBrevig 
- Removal of several background colors makes the theme more consistent. 
- Adjusted the readability of a few items.
- Primary selection highlight should be more readable now (#3842).
=> Improve flatwhite theme

languages.toml
See https://github.com/phoenixframework/tree-sitter-heex/releases/tag/v0.6.0
=> Upgrade HEEx grammar, set HEEx/EEx roots to match Elixir

book/src/languages.md
Had to check the PR to figure out how to configure it: https://github.com/helix-editor/helix/pull/2128/files
Related to https://github.com/helix-editor/helix/pull/2423
=> Add documentation for `max-line-length`

runtime/themes/onedarker.toml
Dark theme partially copyed from LunarVim
=> themes: Add onedarker

helix-lsp/src/lib.rs
Resolves #3859 by generating a diff if the LSP replaces the entire document.
=> diff full-doc LSP edits

helix-term/src/ui/mod.rs
=> Show "Invalid regex" message on enter (Validate)

helix-term/src/commands.rs
=> Add command names to command palette

book/src/configuration.md
See https://github.com/helix-editor/helix/blob/4d4be0e880efd136100439cc34e8c526d299ec34/helix-view/src/editor.rs#L575
=> Fix incorrect scrolloff default in documentation

runtime/tutor
Add a few missing words from the tutorial.
=> tutor: 5.5 add missing words

runtime/themes/ayu_mirage.toml
Related issues: https://github.com/helix-editor/helix/issues/3842 https://github.com/helix-editor/helix/issues/1833
=> Use different cursor color for primary cursor for ayu_mirage

languages.toml, runtime/queries/twig/highlights.scm
https://github.com/eirabben/tree-sitter-twig seems to be abandonned. I suggest to use my  [twig tree-sitter parser](https://github.com/gbprod/tree-sitter-twig) instead :)
=> Change twig tree-sitter grammar

helix-term/src/application.rs, helix-term/src/ui/editor.rs, helix-view/src/input.rs
Depends on https://github.com/helix-editor/helix/pull/3169.
=> Propagate idle timeout event to components

helix-term/src/commands.rs, helix-view/src/info.rs, xtask/src/themelint.rs
- chore: fix clippy linting
- fix: remove unneeded allocations when calling helix_view::Info::new
=> Optimize `helix_view::Info::new`

runtime/themes/monokai_pro_octagon.toml
Adding mode colors for statusline when `color-modes = true`
=> Monokai Pro Octagon statusline modes

runtime/themes/heisenberg.toml
Dark theme inspired by Breaking Bad for helix.
=> Created heisenberg theme for helix editor

languages.toml
See https://github.com/elixir-lang/tree-sitter-elixir/pull/42
=> Bump tree-sitter-elixir to latest version

runtime/themes/kanagawa.toml
Here's my attempt at an helix version for: https://github.com/rebelot/kanagawa.nvim
=> Add a first version of kanagawa theme

languages.toml
=> Update scala treesitter grammar

helix-term/src/ui/editor.rs
=> fix: repeating repeat operator

languages.toml
See #3849. I added some new fixes to the grammar.
=> Update tree-sitter markdown grammar

languages.toml
Since zig is also using LLVM, i added the necessary settings to debug with lldb.
I also tested it in a default zig hello world, and it did work. :)
=> Add the debugger for Zig

book/src/generated/lang-support.md, languages.toml, runtime/queries/vhs/highlights.scm
Added [vhs](https://github.com/charmbracelet/vhs)
=> language: added vhs

languages.toml, runtime/queries/sql/highlights.scm
=> Update SQL grammar

book/src/generated/lang-support.md, languages.toml, runtime/queries/wit/highlights.scm, runtime/queries/wit/indents.scm
fix https://github.com/helix-editor/helix/issues/4523
=> Support WIT grammar

book/src/generated/lang-support.md, languages.toml, runtime/queries/env/highlights.scm, runtime/queries/ini/highlights.scm
Fixes https://github.com/helix-editor/helix/issues/4452
=> add highlights for env and ini file formats

languages.toml, runtime/queries/typescript/highlights.scm
fixes: #4702
updates grammars for typescript, and tsx
as well as updates queries for template literal types
=> Update typescript grammar and queries

book/src/generated/lang-support.md, languages.toml, runtime/queries/bicep/highlights.scm
=> Add support for Bicep files

helix-term/src/commands/typed.rs
May or may not fix https://github.com/helix-editor/helix/issues/4884
=> reload-all: Only update viewport when view focuses on the doc

runtime/themes/varua.toml
Minor color tweaks improving cursorline and statusline.
=> Varua theme updates (cursorline, statusline)

helix-core/src/diagnostic.rs, helix-lsp/src/lib.rs, helix-term/src/application.rs
fix https://github.com/helix-editor/helix/issues/4934
=> feat(lsp): add support for lsp Diagnostic{}.data

README.md
Centre Helix title and logo and add badge with latest release and link to matrix chat.
=> feat(docs): style readme & add badges

runtime/themes/zenburn.toml
=> Update zenburn theme for git gutters

runtime/themes/doom_acario_dark.toml
=> Update Doom Acario for git gutters

runtime/themes/autumn.toml, runtime/themes/autumn_night.toml
Adjust some gray colors used for the status line and line numbers.
=> Autumn theme: adjust some gray colors

runtime/themes/acme.toml, runtime/themes/nord_light.toml
=> Update Acme and Nord Light for git gutters

runtime/themes/serika-dark.toml, runtime/themes/serika-light.toml
As requested in #4972 this PR chooses better suited colors for diff gutters.
I guess I should revisit this theme and do an overhaul of this in general in the next days...
=> Change diff colors for serika themes

runtime/themes/gruvbox_dark_hard.toml
I love the new curl underlines and I think they look great here in my favorite theme!
=> use curl underlines for gruvbox_dark_hard

book/book.toml
=> chore(book): link repository

book/src/generated/lang-support.md, languages.toml, runtime/queries/mermaid/highlights.scm
<https://mermaid-js.github.io/mermaid/>
=> Add Mermaid.js for markdown support

book/src/keymap.md
Tiny change in the documentation.
=> Fix a typo in the docs

flake.lock
Update flake inputs since there have been a lot of changes to dream2nix and nci that may improve stuff.
=> build(nix): update inputs

book/src/install.md
@podsvirov @yashpalgoyal1304 Please review.
=> book: Clarify install commands for msys2 in Windows

book/src/install.md
this was the suggestion i was mentioning at https://github.com/helix-editor/helix/pull/5363 but got busy thereafter...
=> book: Link MSYS2 proper command page

helix-term/src/commands.rs, helix-term/src/keymap.rs
=> keymap: Test backslash escaping in commands

book/src/themes.md
Looks like this was missed :slightly_smiling_face:
=> Add `ui.virtual.wrap` to theme docs

runtime/themes/darcula-solid.toml
Based on the original Darcula, with darker and more contrasting colors.
Original repository: https://github.com/jesusmgg/darcula-solid-helix
=> Add Darcula Solid theme

.github/ISSUE_TEMPLATE/bug_report.yaml
Added some hints to the bug report template to (hopefully) reduce the number of inactionable bug reports.
=> update bug report template

runtime/tutor
=> Remove Outdated Tutor Note About Increment and Decrement Behavior

book/src/generated/lang-support.md, languages.toml, runtime/queries/gdscript/indents.scm, runtime/queries/gdscript/injections.scm, runtime/queries/godot-resource/highlights.scm, runtime/queries/godot-resource/injections.scm
* update grammar for gdscript.
* add comment injections for gdscript.
* add indent for gdscript
* add file-type support for godot-resource
=> Update grammar for godot

runtime/queries/dhall/highlights.scm, runtime/queries/dhall/injections.scm
I didn't realize someone beat me to the punch adding Dhall support. This adds a slew of highlighting queries and an injection for comments.
=> dhall: additional highlight queries

book/src/generated/lang-support.md, languages.toml, runtime/queries/po/highlights.scm, runtime/queries/po/textobjects.scm
- [The format of po files](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html).
=> Add GNU gettext PO grammar

helix-core/src/selection.rs
=> Doc string fix in selection.rs

runtime/themes/everblush.toml
Everblush is an Independent, Dark, Vibrant and Beautiful Colorscheme for helix !!
=> theme: Add Everblush

languages.toml
=> Add graphql schema file type

book/src/configuration.md
Document the `file-modification-indicator` status line element
=> Document the file-modification-indicator statusline element

book/src/generated/lang-support.md, languages.toml, runtime/queries/rst/highlights.scm
Basic support for reStructuredText, with some _very_ rudimentary highlight queries.
=> Add support for reStructuredText

languages.toml, runtime/queries/gdscript/highlights.scm, runtime/queries/gdscript/indents.scm, runtime/queries/godot-resource/injections.scm
- keyword
- Annotations: like `@export`, `@onready`, `@tool`
- Getters/setters
- get_node: as %node, $node
=> Update queries for godot4

runtime/queries/ecma/highlights.scm
=> Update highlight for ecma/js/ts

languages.toml, runtime/queries/go/highlights.scm
- update tree-sitter-go
- refine keywords
- set package as namespace
- add label
- add error
=> Update highlights for golang

helix-core/src/surround.rs
While doing some research on #5903 I expanded the tests of the underlying logic to understand it a bit better. Still noodling on a solution but figured these were independently worth reviewing and landing.
=> Add test cases for existing pair matching logic.

runtime/queries/php/injections.scm
=> queries/php: add injections for regex and sql injection

docs/CONTRIBUTING.md
I think this will be helpful for Rust newbies like myself.
=> Document how to run tests

book/src/themes.md, runtime/themes/onelight.toml
- fix: add `markup.strikethrough` for theme.md 
- add virtual.inlay-hint
- fix ui.virtual.wrap
- rename light-white to grey-300
=> Theme onelight add inlay-hint

helix-core/src/indent.rs
Should be an easy fix that closes #6262
=> Fix indentation level calculation for lines mixing tabs and spaces

runtime/themes/flatwhite.toml
=> fix: flatwhite with inlay

runtime/themes/serika-dark.toml, runtime/themes/serika-light.toml
This adds inlay-hints to both `serika-dark` and `serika-light`.
=> Update Serika themes for inlay-hints

runtime/themes/tokyonight.toml
Adding inlay-type hints for the tokyonight themes
=> Theme: Inlay-Hints for tokyonight theme

book/src/generated/lang-support.md, languages.toml, runtime/queries/capnp/folds.scm, runtime/queries/capnp/highlights.scm, runtime/queries/capnp/indents.scm, runtime/queries/capnp/injections.scm, runtime/queries/capnp/locals.scm
Tree-sitter grammar and queries from https://github.com/amaanq/tree-sitter-capnp.
=> Add language support for Cap’n Proto format

runtime/themes/nord.toml
=> Update nord with inlay-hints

book/src/install.md
Instructions for Linux Systems using AppImage. (Con. of PR:#4866)
=> Add instructions for installing via AppImage

runtime/themes/onedark.toml
=> Update OneDark theme to use light-gray for inlay hints.

runtime/themes/varua.toml
Another tiny PR, sorry I missed this in #6568.
I think I'm done catching up with the new release, thanks everyone :D
=> Update Varua theme for inlay hints

languages.toml
=> Recognize CUDA files as C++

runtime/themes/zenburn.toml
otherwise it just blends with the argument
=> [theme][zenburn] set inlay hint to comment style

book/src/generated/lang-support.md, runtime/queries/julia/textobjects.scm
This PR finishes filling out the language support for Julia by adding textobject queries.
=> Add textobject queries for Julia

book/src/from-vim.md
=> Fix minor grammar issue in 'from-vim' docs

book/src/generated/lang-support.md, languages.toml, runtime/queries/dtd/highlights.scm, runtime/queries/dtd/injections.scm
- Added syntax highlighting for the DTD subset of the XML spec.
- Included .dtd and .ent as common file extensions
=> Add DTD language support

runtime/themes/ayu_dark.toml, runtime/themes/ayu_light.toml, runtime/themes/ayu_mirage.toml
Some improvements to the `ayu_dark` theme. Happy to discuss color choices, this is just what I use in my local config.
=> Ayu dark improvements

book/src/configuration.md, book/src/languages.md
Solves #6803.
Not sure I fully understood the problem, but I can at least update the typo. New to the project, feedback very welcome.
=> Change soft-wrap.wrap_at_text_width to kebab case in documentation.

runtime/themes/noctis.toml
Just an improvement to address some frustrations I had with the theme. 
Before:
After:
=> [Theme - Noctis] improve multiple cursor highlighting and change whitespace rendering color

helix-vcs/src/lib.rs
=> downgrade gix log level to info

book/src/keymap.md
Change j/k/up/down to be `move_visual_line_*` over `move_line_*`
=> Update docs for `move_visual_line_*`

runtime/themes/dracula.toml
I applied the 'foreground' color to the variable.**other** and variable.**other.member**
>
And changed dropdown menu colors
=> Dracula theme: change variable and menu colors

book/src/generated/typable-cmd.md, helix-term/src/commands/typed.rs
Resolves #6857
I'm not sure what are the policies are there wrt to new commands but this one feels useful to me as well.
=> Implement wbc and wbc! commands

helix-core/src/syntax.rs
=> Fix typo in syntax.rs

helix-term/src/commands.rs
=> fixed repeat_last_motion extends selection

helix-term/src/config.rs, helix-term/src/keymap.rs, helix-term/src/keymap/default.rs, helix-term/src/keymap/macros.rs, helix-view/src/info.rs
Depends on:  #7167, #7168, #7169, #7193.
=> Remove Keymap(KeyTrie) and simply use KeyTrie.

runtime/themes/gruvbox_dark_soft.toml
This PR adds the soft contrast variant of gruvbox dark theme
=> theme: added gruvbox dark soft variant

runtime/themes/merionette.toml
Hi! I created a dark theme for helix, called merionette, focused on pinkish colors and striving for some contrast between overall colors.
=> Add merionette theme

book/src/generated/lang-support.md, languages.toml, runtime/queries/svelte/indents.scm
- Support inlay-hints
- Add indents.scm for svelte
=> Support inlay-hints for svelteserver.

book/src/generated/lang-support.md, languages.toml, runtime/queries/fsharp/highlights.scm
Added installation instructions to the wiki
https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#fsharpf
=> Add fsharp language support

README.md
I changed my username.
Removing it entirely is also fine if that's preferable. Credit isn't necessary - just making sure there are no dead links anywhere.
Thanks! ❤️
=> Update my name README.md

languages.toml
This PR registers [glTF](https://en.wikipedia.org/wiki/GlTF) files for the JSON language configuration
=> Register .gltf file type for JSON

book/src/generated/lang-support.md, languages.toml, runtime/queries/java/indents.scm
Closes #7789.
I also changed the default `tab-width` to 2. I'm not a Java user, but this is the value suggested by [Google](https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation).
=> feat(indent): add basic java indentation queries

runtime/themes/yellowed.toml
This is Yellowed, a theme for vscode (you can find it [here](https://github.com/Gael-Lopes-Da-Silva/YellowedVSCode)) that I ported to Helix ([github](https://github.com/Gael-Lopes-Da-Silva/YellowedHelix)).
=> Add new Yellowed theme to default themes

languages.toml, runtime/queries/slint/highlights.scm, runtime/queries/slint/indents.scm, runtime/queries/slint/injections.scm, runtime/queries/slint/locals.scm
Fixd: https://github.com/helix-editor/helix/pull/5290
=> Update slint grammar

helix-view/src/editor.rs
Obsoleted by https://github.com/helix-editor/helix/pull/4731
=> Update stale comments

Cargo.lock, Cargo.toml, helix-core/src/syntax.rs
This includes some changes in syntax.rs to address the change in https://github.com/tree-sitter/tree-sitter/pull/2431
=> Update tree-sitter to latest master

languages.toml
Prevent pyright from timing out as requested by @the-mikedavis in https://github.com/helix-editor/helix/pull/7897#issuecomment-1686622885
(I added a missing space too, for good measure)
=> Update pyright config to avoid time-outs

languages.toml
The grammar received some improvents to code quality and coverage.
=> highlight(matlab): bumps grammar after some improvements

languages.toml
Handles a couple more edge cases, I haven't seen an error in a while now
=> chore: update strace tree sitter grammar

runtime/themes/catppuccin_frappe.toml, runtime/themes/catppuccin_latte.toml, runtime/themes/catppuccin_macchiato.toml, runtime/themes/catppuccin_mocha.toml
Contains changes for these two commits:
- https://github.com/catppuccin/helix/commit/1e0d722206889eeb89b98e962c9088f4d05a9eda
- https://github.com/catppuccin/helix/commit/95f9093c81e1cb6a39af2e091f322088829c9d43
=> Sync latest catppuccin theme changes

flake.nix
We can continue to use the MSRV for local development and checks while building release executables with the latest stable Rust, as we do in CI.
=> Build flake packages with stable Rust

book/src/generated/lang-support.md, languages.toml, runtime/queries/gas/highlights.scm, runtime/queries/gas/injections.scm, runtime/queries/gas/textobjects.scm
Add gas support suggested in #3329
=> Support GNU assembler syntax

languages.toml
=> Add `.webmanifest` as supported JSON files

languages.toml
polkit policy files are just xml files, https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html for more info
=> add polkit policy files to xml detection

runtime/themes/nord.toml
=> [Nord theme]: Fix typo, improve JSX/TSX highlighting, improve overall highlighting

book/src/guides/injection.md
=> book: Fix broken link

runtime/themes/nord-night.toml
=> Add nord night theme

runtime/themes/gruber-darker.toml
=> Theme: Add gruber-darker theme

runtime/queries/comment/highlights.scm
some additions are inspired by https://github.com/folke/todo-comments.nvim
=> feat(highlights): add more comment highlights

helix-term/src/ui/picker.rs
=> Only render preview if picker has a preview function

runtime/themes/everblush.toml
Use comment color for ui.virtual.inlay-hint in everblush theme.
=> Adjusted ui.virtual.inlay-hint color for everblush theme

languages.toml, runtime/queries/purescript/highlights.scm
The last one was less than a month ago but we had a lot of updates since it's a new grammar
=> Update PureScript grammar

book/src/languages.md
Related to: https://github.com/helix-editor/helix/issues/8331#issuecomment-1727012552
=> docs: add docs for soft-wrap in languages.toml

book/src/generated/lang-support.md, languages.toml
Nushell [recently got a built in lsp](https://www.nushell.sh/blog/2023-11-14-nushell_0_87_0.html#lsp-is-coming-to-nushell-toc).
=> feat(languages.toml): nushell lsp

runtime/themes/rose_pine.toml
Main repo: https://github.com/rose-pine/helix
=> fix: update rose_pine to be identical to main repo

book/src/generated/lang-support.md, languages.toml
https://haskell-language-server.readthedocs.io/en/latest/features.html#cabal-parse-errors-and-warnings
=> Add haskell-language-server as lsp for cabal files

runtime/themes/nord.toml
Fixes https://github.com/helix-editor/helix/issues/9131
=> Add markup styling to nord theme

helix-lsp/src/lib.rs
Aims to fix #9103. I could not reproduce the original issue though.
Any suggestions are welcome!
=> Avoid crashing with 2 instances of the same LSP

runtime/themes/monokai_pro.toml, runtime/themes/monokai_pro_machine.toml, runtime/themes/monokai_pro_octagon.toml, runtime/themes/monokai_pro_ristretto.toml, runtime/themes/monokai_pro_spectrum.toml
=> Fix: misleading active tab color in monokai_pro*

helix-term/src/args.rs
=> Fallback to filename for +arg

helix-term/src/commands.rs, helix-term/src/commands/dap.rs, helix-term/src/commands/typed.rs, helix-term/src/keymap.rs, helix-term/src/ui/spinner.rs
I ran the Clippy against the codebase and found some things that can be simplified so the code can be more readable.
=> Address clippy lints

languages.toml, runtime/queries/typst/highlights.scm, runtime/queries/typst/injections.scm
Revise the grammar for typst to accommodate typst version 0.10 and introduce heading levels.
I hope this PR is OK :smile:
=> Update Typst Tree-Sitter grammar

runtime/themes/dracula.toml
I did the same change like in [this PR](https://github.com/helix-editor/helix/pull/9435) :)
=> Make status line modes bold for theme "dracula".

runtime/themes/cyan_light.toml
=> Update cyan_light theme : adjust color darkness on ruler & inlay-hints

runtime/themes/zed_onedark.toml, runtime/themes/zed_onelight.toml
While updating the colors, accidentally broke the cursor line + picker line colors. Apologies!
=> Fix cursorline Zed OneDark

book/src/generated/lang-support.md, languages.toml, runtime/queries/pkl/highlights.scm, runtime/queries/pkl/indents.scm, runtime/queries/pkl/injections.scm
Add [pkl](https://github.com/apple/pkl) language. Official documentation: https://pkl-lang.org/. Mostly adopted from https://github.com/apple/pkl-neovim and https://github.com/apple/tree-sitter-pkl plus resolved some injections for comments.
=> feat(languages): pkl

book/src/install.md
Closes https://github.com/helix-editor/helix/issues/9573
=> expand upon the arch linux install instructions

Cargo.lock, helix-term/Cargo.toml, helix-term/src/lib.rs
Resolves https://github.com/helix-editor/helix/issues/5319 according to https://github.com/neovim/neovim/blob/32b49448b227588c2fbc93f89743104fd445e0a6/src/nvim/tui/tui.c#L1816-L1846
=> follow neovim's truecolor detection

runtime/themes/sonokai.toml
=> sonokai: Add color modes support and change contrast between ruler and bg

runtime/themes/dracula.toml
I made the whitespace color more contrasting :)
Before:
After:
=> Dracula whitespace color changes

languages.toml, runtime/queries/nim/highlights.scm, runtime/queries/nim/indents.scm, runtime/queries/nim/textobjects.scm
See #3117. aMOPel/tree-sitter-nim was a good but inaccurate parser, alaviss/tree-sitter-nim is a 100% accurate parser.
=> Switch Nim tree-sitter queries to alaviss/tree-sitter-nim

book/src/generated/lang-support.md, languages.toml, runtime/queries/powershell/highlights.scm, runtime/queries/powershell/injections.scm
Fixes #3123 using a newer and more actively developed PowerShell grammar.
=> Add PowerShell highlighting

runtime/themes/modus_operandi.toml, runtime/themes/modus_operandi_deuteranopia.toml, runtime/themes/modus_operandi_tinted.toml, runtime/themes/modus_operandi_tritanopia.toml, runtime/themes/modus_vivendi.toml, runtime/themes/modus_vivendi_deuteranopia.toml, runtime/themes/modus_vivendi_tinted.toml, runtime/themes/modus_vivendi_tritanopia.toml
https://protesilaos.com/codelog/2024-03-17-modus-themes-4-4-0/
Applies upstream changes.
=> Update to modus-themes 4.4.0

languages.toml, runtime/queries/hurl/highlights.scm
- Add formmter for hurl 
- Highlights for hurl 4
=> Updated grammar for hurl 4

helix-stdx/src/env.rs, helix-stdx/src/path.rs, helix-term/src/ui/statusline.rs, helix-view/src/document.rs
I am done with stdx, I promise :)
This time, there are only two small changes outside of stdx. No dramatic API changes.
You can point me to other places where such optimizations are welcome :)
=> stdx optimizations

book/src/generated/lang-support.md, languages.toml, runtime/queries/pkgbuild/highlights.scm, runtime/queries/pkgbuild/indents.scm, runtime/queries/pkgbuild/injections.scm, runtime/queries/pkgbuild/textobjects.scm
This adds `pkgbuild-language-server` to PKGBUILDs
=> Enhance support for PKGBUILDS

book/src/generated/lang-support.md, languages.toml, runtime/queries/helm/highlights.scm, runtime/queries/helm/injections.scm
=> Add support for helm charts

languages.toml, runtime/queries/cpp/highlights.scm, runtime/queries/erlang/highlights.scm, runtime/queries/erlang/injections.scm, runtime/queries/erlang/locals.scm, runtime/queries/git-config/highlights.scm, runtime/queries/gleam/highlights.scm, runtime/queries/rust/highlights.scm
This is a group of minor language support updates. Each commit has the details on its changes
=> Update tree-sitter parsers and queries for a few languages

runtime/themes/horizon-dark.toml
adds the new jump label color and some fmt fixes apparently
=> Add jump label color to horizon-dark theme

helix-stdx/src/path.rs
Something I didn't take care of in https://github.com/helix-editor/helix/pull/9769/commits/86d3fa92cb32c18bdf323717a575aec69f4c67e1
=> Use the OS path separator instead of /

runtime/themes/flexoki_dark.toml, runtime/themes/flexoki_light.toml
Based on [Flexoki](https://stephango.com/flexoki)
=> add flexoki theme

runtime/themes/darcula.toml
=> Add jump label support to Darcula themes

runtime/queries/python/highlights.scm
=> Add new keyword as per PEP 695

runtime/themes/dark_high_contrast.toml
- ~~base16_transparent~~
~~[gw_transparent](https://github.com/helix-editor/helix/assets/106496265/6abf10a3-b085-415f-be87-1855f2b9874b)~~
- dark_high_contrast
=> Add jump-label style for dark high contrast

runtime/themes/varua.toml
=> Varua theme jump label support

book/src/generated/lang-support.md, languages.toml, runtime/queries/ldif/highlights.scm
=> feat(lang): add LDIF support

book/src/generated/lang-support.md, languages.toml, runtime/queries/typst/highlights.scm
Update the tree sitter to support Typst 0.11 and changed the lsp to [Tinymist](https://github.com/Myriad-Dreamin/tinymist)
=> Support Typst 0.11

runtime/tutor
=> correctly describe behavior of C in tutor

languages.toml, runtime/queries/earthfile/highlights.scm
- **update tree-sitter-earthfile to 0.2.4**
- **update earthfile higḥlight queries based on nvim-treesitter feedback**
=> update earthfile grammar and highlight queries

runtime/themes/dark_plus.toml
=> Remove myself from `dark_plus` maintainer list

theme.toml
The cursor colour is now different for selection
and insert modes. Specifically:
- Insert mode's cursor is now white.
- Selection mode's cursor colour is now delta.
closes #10568
=> Change cursor color per mode for default

helix-vcs/src/git.rs, helix-vcs/src/git/test.rs, helix-vcs/src/lib.rs
I'm working on redoing https://github.com/helix-editor/helix/pull/9951 with shared autodetection instead of per-file and having to carry small patches around is annoying so I extracted them here.
cc @pascalkuthe since you reviewed those already in the original MR.
=> chore: Some small VCS cleanup

book/src/generated/lang-support.md, runtime/queries/hurl/textobjects.scm
Added textobjects queries for comment and function.
=> add textobjects queries for hurl

helix-core/src/match_brackets.rs, helix-term/tests/test/commands/movement.rs
Fixes a minor regression introduced in #10613.
=> fix match bracket matching

helix-view/src/document.rs
Fixes #11077
Big thanks to @the-mikedavis for pointing out how to fix it.
=> Add changes for undo in insert mode

runtime/tutor
Fixes https://github.com/helix-editor/helix/issues/11030 (and one spelling error as a bonus)
=> Add one space back to the main text in the tutor after chapter 11.1

runtime/queries/bash/injections.scm
This is my first attempt at tree-sitter syntax, it seems to work, but please confirm I have not made any errors as I have no idea what I am really doing at this point and just referencing what Neovim does!
=> Add regex injections into bash

runtime/themes/kanagawa-dragon.toml, runtime/themes/zed_onedark.toml, runtime/themes/zed_onelight.toml
Implements the Dragon variant of the Kanagawa theme.
https://github.com/rebelot/kanagawa.nvim?tab=readme-ov-file
=> Theme: Kanagawa Dragon

helix-term/src/commands.rs
=> Make `format_selections` respect document configuration

book/src/generated/typable-cmd.md
This change adjust the documentation with b0cf86d31bd85e1f0e38ec86f4dfeeade2cd0918.
=> Regenerate documentation

.github/workflows/build.yml
=> fix: usage of `node12 which is deprecated`

helix-view/src/document.rs
=> Fix panic when starting helix tutor

book/src/generated/lang-support.md, languages.toml, runtime/queries/gdscript/highlights.scm, runtime/queries/gdscript/indents.scm, runtime/queries/gdscript/textobjects.scm, runtime/queries/godot-resource/injections.scm, runtime/queries/godot-resource/textobjects.scm
- update gdscript highlights
- add godot-resource textobjects
=> Updated Godot support

helix-loader/src/lib.rs
=> Add .svn as workspace root marker

book/src/generated/lang-support.md, languages.toml, runtime/queries/jq/highlights.scm, runtime/queries/jq/injections.scm, runtime/queries/jq/locals.scm, runtime/queries/jq/textobjects.scm
jq is a language for manipulating JSON data: https://jqlang.github.io/jq/
(wild code from the screenshot: https://github.com/wader/jqjq)
=> Add jq language support

runtime/queries/verilog/textobjects.scm
Tested locally, seems to have worked.
=> add comment textobjects for verilog

book/src/generated/lang-support.md, languages.toml, runtime/queries/thrift/folds.scm, runtime/queries/thrift/highlights.scm, runtime/queries/thrift/injections.scm, runtime/queries/thrift/locals.scm
add thrift file tree-sitter conifg
=> add thrift hightlight

runtime/themes/iceberg-dark.toml, runtime/themes/iceberg-light.toml
Add light and dark themes based off iceberg by cocopon https://github.com/cocopon/iceberg.vim.
=> feat: add iceberg light/dark themes

languages.toml
Fixes https://github.com/helix-editor/helix/discussions/11084
=> Add cshtml to html file-types

runtime/themes/snazzy.toml
Also includes a format commit for the snazzy theme file.
=> fix(themes): fix diagnostics in snazzy

helix-term/src/commands.rs, helix-term/tests/test/commands.rs
=> Join single-line comments with J.

languages.toml
https://ldtk.io/docs/game-dev/json-overview/
=> languages.toml: recognize `ldtk` files

book/src/generated/lang-support.md, languages.toml, runtime/queries/dune/highlights.scm
Add support for the https://dune.build/ project language
=> Add support for dune project language

languages.toml
=> Bump `jjdescription` grammar revision

book/src/generated/lang-support.md, languages.toml, runtime/queries/snakemake/LICENSE, runtime/queries/snakemake/folds.scm, runtime/queries/snakemake/highlights.scm, runtime/queries/snakemake/indents.scm, runtime/queries/snakemake/injections.scm, runtime/queries/snakemake/locals.scm
Hi,
Thank you for helix! It has changed my coding experience!
I have added syntax highlighting for snakemake, which is a python based language.
I have not made the tree-sitter. Credit goes to osthomas (https://github.com/osthomas/tree-sitter-snakemake/). 
Kind regards,
Sebastian
=> Adding snakemake to language

book/src/generated/lang-support.md, languages.toml, runtime/queries/cylc/highlights.scm, runtime/queries/cylc/indents.scm, runtime/queries/cylc/injections.scm, runtime/queries/cylc/textobjects.scm
> Cylc (pronounced silk) is a general purpose workflow engine that also manages cycling systems very efficiently. It is used in production weather, climate, and environmental forecasting on HPC, but is not specialized to those domains.
[Cylc](https://github.com/cylc/cylc-flow)
Configurations are the main filetype of Cylc, as they're used to define workflows (tasks and their dependencies).
=> feat: Add support for cylc configuration files

book/src/generated/lang-support.md, languages.toml, runtime/queries/textproto/highlights.scm, runtime/queries/textproto/indents.scm, runtime/queries/textproto/textobjects.scm
See https://protobuf.dev/reference/protobuf/textformat-spec/
=> Add support for textproto language.

runtime/themes/seoul256-dark-hard.toml, runtime/themes/seoul256-dark-soft.toml, runtime/themes/seoul256-dark.toml, runtime/themes/seoul256-light-hard.toml, runtime/themes/seoul256-light-soft.toml, runtime/themes/seoul256-light.toml
Dark color scheme based on [Seoul256](https://github.com/junegunn/seoul256.vim)
=> Theme: Seoul256 dark & light

languages.toml, runtime/queries/perl/highlights.scm
The parser versions you're using are from like a year ago, a lot of good stuff has
happened since then.
This should close #9060
=> chore: update perl + pod parsers

runtime/themes/yo.toml, runtime/themes/yo_berry.toml, runtime/themes/yo_light.toml
I made these themes for Helix. They're inspired by Zenbones/Alabaster themes and use [Radix Colors](https://www.radix-ui.com/colors)
https://github.com/mrmcc3/yo-theme-helix has more info, variants and screenshots
=> Add yo themes

book/src/remapping.md
Fixes https://github.com/helix-editor/helix/issues/11929
=> Document how to use modifier keys in macro remaps

runtime/themes/modus_operandi.toml, runtime/themes/modus_operandi_deuteranopia.toml, runtime/themes/modus_operandi_tinted.toml, runtime/themes/modus_operandi_tritanopia.toml, runtime/themes/modus_vivendi.toml, runtime/themes/modus_vivendi_deuteranopia.toml, runtime/themes/modus_vivendi_tinted.toml, runtime/themes/modus_vivendi_tritanopia.toml
Only one slightly modified color to update (cf. https://github.com/protesilaos/modus-themes/compare/4.3.0...4.6.0).
=> Update modus themes to 4.6.0

runtime/themes/onedarker.toml
Following up on #9435 for theme "onedarker".
=> Use bold statusline for mode indicator in onedarker theme

runtime/themes/sunset.toml
=> Add Sunset theme

book/src/generated/lang-support.md, languages.toml, runtime/queries/gpr/highlights.scm
I copied `highlights.scm` from the tree-sitter-gpr repository, it seems to work well.
=> Improve language support for Ada

book/src/keymap.md, helix-term/src/commands.rs, helix-term/src/keymap/default.rs
Inspired by Kakoune's behavior.
=> Search selection with word boundary detection

book/src/generated/lang-support.md, languages.toml, runtime/queries/vento/highlights.scm, runtime/queries/vento/injections.scm
=> Add support for the Vento template language

helix-term/src/commands/typed.rs
=> Expand tildes in `:read` command

helix-term/src/ui/completion.rs
=> feat: use `ui.text.directory` for path completion item if its a folder

runtime/themes/catppuccin_mocha.toml
Just a small change for one Tree-sitter capture, the other changes made to the theme in recent months in this repository were also backported to the theme repository.
=> Sync Catppuccin theme changes

languages.toml
See https://github.com/phoenixframework/tree-sitter-heex/pull/45
=> chore: update tree-sitter-heex to version 0.7.0

book/src/themes.md, runtime/themes/onelight.toml
- Update for tabstop, picker v2, path completion
=> Update onelight theme

languages.toml, runtime/queries/matlab/indents.scm
Fixes https://github.com/acristoffers/tree-sitter-matlab/issues/19 and updates the grammar to its
latest version, which I believe contains other bugfixes and was updated with the latest tree-sitter.
Building and running locally showed no issues.
=> Fix a bug in matlab indentation and updates the grammar commit hash to latest

languages.toml
See https://github.com/helix-editor/helix/pull/9316#issuecomment-2294240727
=> Re-enable Hare by default

CHANGELOG.md, Cargo.lock, Cargo.toml, contrib/Helix.appdata.xml
This will be a patch release focusing on some bug fixes from the 25.01 release
=> Add changelog notes for 25.01.1

book/src/generated/lang-support.md, languages.toml
Add [beancount-language-server](https://github.com/polarmutex/beancount-language-server) as a language server for beancount.
=> Add beancount-language-server

helix-term/src/handlers/completion.rs, helix-term/src/handlers/completion/path.rs
Adds path completion for multiple cursors/selections:
https://github.com/user-attachments/assets/7df01e2d-a18d-451b-b218-8cce19d6159f
Closes https://github.com/helix-editor/helix/issues/12477
=> Add path completion for multiple cursors

helix-term/src/commands.rs
Didn't know of this before. Hope this help discover it better.
=> doc: Document `mdm` and `mrm` for popup help

runtime/themes/modus_operandi.toml, runtime/themes/modus_vivendi.toml
Add a special color for directories
Add a different background color for help
=> Small refinements for modus themes

book/src/generated/lang-support.md, languages.toml
Add [asm-lsp](https://github.com/bergercookie/asm-lsp) for assembly dialects.
=> feat: add asm-lsp for assembly dialects

helix-term/src/commands.rs
fixes https://github.com/helix-editor/helix/issues/12685
=> goto_diag: avoid wraparound by default

runtime/queries/zig/highlights.scm
these got updated after I had reversed them so they weren't reversed I also did a couple fixes to some highlighting
=> reverse zig highlights

runtime/themes/cyan_light.toml
=> Cyan light UI grays and directory prompt

languages.toml
Add additional XML-formatted multimedia related file extensions:
- smil: Synchronized Multimedia Integration Language
- mpd: Media Presentation Description
=> languages/xml: add mpd & smil extensions

book/src/generated/lang-support.md, runtime/queries/rust/symbols.scm
Added rust symbol support for #12275 
Thanks for your work on that feature @the-mikedavis !
=> Rust symbol queries

book/src/generated/lang-support.md, languages.toml, runtime/queries/kotlin/highlights.scm, runtime/queries/kotlin/indents.scm, runtime/queries/kotlin/injections.scm, runtime/queries/kotlin/textobjects.scm
Also updates the grammar version to enable some of the queries, and adds "companion" as a keyword in highlights.
=> Add indents and textobjects for Kotlin.

book/src/generated/lang-support.md, languages.toml
[starpls](https://github.com/withered-magic/starpls) is a language server for Starlark.
=> languages.toml: add starpls as Starlark language server

book/src/generated/lang-support.md, languages.toml
Adding https://github.com/apple/pkl-lsp for Apple's Pkl config format
=> Add pkl-lsp

runtime/themes/sunset.toml
=> Sunset theme: version 2.0

runtime/themes/carbon.toml
This is a theme for the [Helix](https://helix-editor.com/) text-editor that is inspired by the [Carbon Design System](https://carbondesignsystem.com/).
Adding from the original repository created by me at https://github.com/rishikanthc/carbon-helix
=> Adds Carbon theme for helix editor

book/src/generated/lang-support.md, languages.toml, runtime/queries/werk/highlights.scm
adds suport for the [werk](https://simonask.github.io/werk/) language
=> add werk language and highlights

runtime/themes/solarized_dark.toml, runtime/themes/solarized_light.toml
=> Switch from reddish-orange to orangeish-yellow for Solarized `diff.delta`

runtime/themes/focus_nova.toml
Custom theme designed for maximum readability and low eye strain with cool hues and balanced contrasts. Inspired by Gruvbox, modernized for long coding sessions.
=> Add focus_nova theme

runtime/themes/onedark.toml
Copied from onedarker: https://github.com/helix-editor/helix/blob/7e7a98560e58371690d00e380d79e0bbaaf19d54/runtime/themes/onedarker.toml#L86
=> add `ui.text.directory` to onedark

book/src/generated/lang-support.md, languages.toml
This PR adds `just-lsp` as the configured `lsp`.
=> feat: added lsp for just

runtime/themes/catppuccin_mocha.toml
syncs the latest changes for the catppuccin theme from https://github.com/catppuccin/helix
\cc @uncenter
=> feat: sync catppuccin theme changes

book/src/remapping.md
link to Commands.md was commands.html
=> Docs: Update docs link for Commands.md in Remapping.md

book/book.toml
See https://github.com/szabgab/public-mdbooks/issues/10
=> remove the multilingual field from book.toml

runtime/queries/quint/injections.scm
Just to enable highlighting inside comments.
=> Basic injection queries for Quint

runtime/themes/serika-dark.toml, runtime/themes/serika-light.toml
Turnes out, the original color choices were a bit too subtle to be practical in daily usage, so this tweaks some colors a little bit to provide more distinction.
Also add some additional theming keys and tweak some existing ones.
=> update serika themes

runtime/themes/ashen.toml, runtime/themes/licenses/ashen.license
This PR contributes my own theme, Ashen. I've been daily-driving this theme for many months now. It's also in a very stable state; I haven't tweaked it in a while. Thus, I finally feel it's ready to contribute to Helix. 
The Helix theme, along with Ashen's many other ports, are maintained by me on [sr.ht/~ficd/ashen](https://sr.ht/~ficd/ashen/). I intend to keep maintaining the theme in the upstream repository, and open PRs here for any critical changes -- therefore, please don't worry about much maintenance overhead for Ashen.
I'm contributing the theme here for discoverability. I think many people would enjoy this theme. I had a lot of fun making it, and I would be honored if Ashen makes it into the next Helix release :smile:. 
I've been daily-driving this theme for many months now. …
=> feat: added ashen theme

languages.toml, runtime/queries/scss/highlights.scm
- fix scss file-types
- update scss highlight
=> Update scss and highlights

runtime/themes/onelight.toml
fix `ui.picker.header.column.active`
=> fix theme onelight: ui.picker.header

runtime/queries/ini/highlights.scm
This change is inspired from the official queries:
- https://github.com/justinmk/tree-sitter-ini/blob/master/queries/highlights.scm
- https://github.com/helix-editor/helix/blob/master/runtime/queries/toml/highlights.scm
=> fix(highlights/ini): make consistency with toml

helix-term/src/commands/typed.rs
I just heavily needed this so..
=> implement case insensitive search for `:sort`

runtime/themes/lapis_aquamarine.toml, runtime/themes/licenses/lapis_aquamarine.LICENSE
=> feat(colorscheme): add lapis_aquamarine colorscheme

helix-stdx/src/rope.rs
This is a three part change to expand the helpers in `helix-stdx::rope` for unicode segmentation. The new functions are all byte-indexed in preparation for eventually transitioning to Ropey v2.
* Add `RopeSliceExt::(nth_){next,prev}_grapheme_boundary`. These 4 functions mirror the ones adapted from Led in `helix_core::graphemes` which are character-indexed. These will be drop-in replacements as we transition to v2 and byte indexing.
* Refactor `RopeGraphemes` and `RopeGraphemesRev` to be one reversible type. The new unified `RopeGraphemes` mirrors the `Bytes` and `Chars` types in Ropey v2. While not strictly necessary for the Ropey v2 transition it's useful to have these types combined, and it's nice that they mirror Ropey. We might use this for issues like #13342 where we want to have a …
=> Expand byte-indexed grapheme cluster helpers in helix-stdx

languages.toml
=> languages: add comment tokens for DTD language

book/src/generated/lang-support.md, languages.toml, runtime/queries/ini/highlights.scm, runtime/queries/systemd/highlights.scm
Configure two new language servers:
- https://github.com/JFryy/systemd-lsp
- https://github.com/igor-prusov/dts-lsp
(and improve ini highlighting)
=> Add systemd-lsp and dts-lsp

helix-term/src/commands.rs
=> Fix off by one error when opening multiple new lines with CRLF line endings

book/src/generated/lang-support.md, languages.toml, runtime/queries/lua/injections.scm, runtime/queries/luap/highlights.scm, runtime/queries/luau/injections.scm
Queries copied from [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/) and adapted to work with our captures.
**Showcase**
=> feat: add grammar for lua pattern language

book/src/generated/lang-support.md, languages.toml, runtime/queries/robots.txt/highlights.scm, runtime/queries/robots.txt/injections.scm, runtime/queries/robots.txt/tags.scm, runtime/queries/robots.txt/textobjects.scm
Add support for [Robots Exclusion Protocol RFC9309](https://www.rfc-editor.org/rfc/rfc9309) better known as `robots.txt`
**Showcase**
=> feat: add `robots.txt` language

book/src/generated/lang-support.md, languages.toml, runtime/queries/hdl/highlights.scm
Hi,
I'm currently learning [nand2tetris](https://www.nand2tetris.org/), and I'd like to add a Tree-sitter grammar for the HDL (Hardware Description Language) used in this course.
=> feat: add a tree-sitter grammar for hdl

book/src/generated/lang-support.md, languages.toml, runtime/queries/flatbuffers/highlights.scm
Tree-sitter queries based on https://github.com/yuanchenxi95/tree-sitter-flatbuffers/blob/95e6f9ef101ea97e870bf6eebc0bd1fdfbaf5490/queries/highlights.scm
=> Add Flatbuffers language and grammar

languages.toml, runtime/queries/svelte/folds.scm, runtime/queries/svelte/highlights.scm, runtime/queries/svelte/indents.scm, runtime/queries/svelte/injections.scm, runtime/queries/svelte/locals.scm
Closes: #14180
Source of queries: https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/svelte
=> Switch svelte treesitter and update queries

book/src/generated/lang-support.md, languages.toml, runtime/queries/koto/highlights.scm, runtime/queries/koto/rainbows.scm
This PR adds rainbow bracket support for Koto.
=> Add rainbows for Koto

languages.toml
As specified in https://support.apple.com/guide/terminal/import-and-export-terminal-profiles-trml4299c696/mac
=> Add .terminal to xml file types

runtime/queries/jsonnet/injections.scm
Based on injections for C language
=> feat: enable comment highlights in jsonnet
