helix-editor/helix

languages.toml, runtime/queries/tsq/highlights.scm, runtime/queries/tsq/injections.scm
A few changes to make TSQ highlights better:
* A parsing error has been fixed in the grammar itself
* Previously tree-sitter-tsq did not parse the variables
in predicates like `(#set! injection.language "javascript")`
* Theme nodes as `tag`
* The newly added node to the parser (from the above fix) is
`variable` which takes over the `variable` capture from nodes
* Highlight known predicates as `function` and unsupported
predicates as `error`
* This may help when translating queries from nvim-treesitter.
For example `#any-of?` is a common one used in nvim-treesitter
queries but not implemented in Helix or tree-sitter-cli.
* Inject tree-sitter-regex into `#match?` predicates
=> Update TSQ queries

book/src/keymap.md, docs/architecture.md, helix-core/src/indent.rs, helix-term/src/ui/markdown.rs, runtime/queries/elm/highlights.scm, runtime/queries/git-commit/highlights.scm, runtime/queries/kotlin/highlights.scm, runtime/queries/lean/highlights.scm, runtime/queries/make/highlights.scm, runtime/queries/solidity/highlights.scm, runtime/queries/verilog/highlights.scm, runtime/queries/verilog/textobjects.scm, runtime/themes/nord.toml, runtime/themes/pop-dark.toml
Ran the typos tool to find typos, and manually corrected them. Mostly in comments, some in docs (the book + architecture.md), as well as some typos in themes/queries.
=> Fix some typos

book/src/themes.md, runtime/queries/javascript/highlights.scm, runtime/queries/typescript/highlights.scm
Inspired by and following the patterns of #2731.
Adds `keyword.storage.type` and `keyword.storage.modifier` scopes for syntax highlighting.
=> Introduce storage highlighting for typescript/javascript

runtime/themes/onedark.toml
=> theme(onedark): Remove bg for window separator

helix-lsp/src/client.rs
The functionality already existed, but the capability wasn't being reported correctly to the server:
https://github.com/helix-editor/helix/blob/230ba264bf78d9b4ecd42440f0cbb20529f9c235/helix-term/src/application.rs#L716-L728
=> lsp: Add workspace/applyEdit to client capabilites

book/src/install.md, flake.nix
For those not familiar, Nix will ask on first use if you would like to adopt these settings from the flake, if accepted then users will pull artifacts from the official cache when available instead of needlessly building them whenever running a Nix flake command such as `nix build`.
=> nix flake: make the binary cache "just work"

flake.nix
Even though in the default package this list is empty, it is still useful to apply extra wrapper args downstream. 
For example, one may wish to wrap Helix with the `PATH` set to include various language servers by default if not installed with the `--suffix` arg.
Full list of possible args:
https://github.com/NixOS/nixpkgs/blob/1c70b694fe0fece5ae74beb747a40f1b7237d251/pkgs/build-support/setup-hooks/make-wrapper.sh#L14-L35
One can see a real world example in this commit:
https://github.com/nrdxp/nrdos/commit/d8bf68e639343566d33545f189616bba57e0ed3f
=> nix: pass makeWrapperArgs to wrapProgram

helix-term/src/commands.rs
=> fix: error that caused usize to overflow

book/src/generated/lang-support.md, languages.toml, runtime/queries/fortran/folds.scm, runtime/queries/fortran/highlights.scm, runtime/queries/fortran/indents.scm
This PR adds syntax highlighting and LSP support for Fortran. It doesn't include textobjects but `fortls` seems to work without any issues.
Let me know if I made any mistakes, or if there's anything I need to change. 😄
=> add fortran language

book/src/generated/lang-support.md, languages.toml, runtime/queries/ungrammar/highlights.scm
Adds support for the ungrammar language (mostly tree-sitter highlighting):
=> Added ungrammar language support

book/src/generated/lang-support.md, runtime/queries/glsl/textobjects.scm
Hello, I added  textobjects support to GLSL, based on C. After some testing this seems to work as expected.
=> Add textobjects.scm to GLSL

runtime/themes/noctis.toml
A port of the [Noctis](https://github.com/liviuschera/noctis#noctis) theme.
=> [Theme] Noctis

book/src/keymap.md, helix-term/src/application.rs, helix-term/src/keymap/default.rs, helix-term/src/ui/prompt.rs
Ctrl-Left and Ctrl-Right are common shortcuts in numerous applications.
This change is just adding a new key binding for the existing word-wise movement:
- Ctrl-Left is equivalent to Alt-b and Alt-Left, and
- Ctrl-Right is equivalent to Alt-f and Alt-Right.
**EDIT: after reviews, changed to the following:**
- Adds Ctrl+{Left/Right/Backspace/Delete} for word-wise movement/deletion in prompt, picker, …
- Removes Alt-Left and Alt-Right in prompt, picker, …
- Adds Alt-Delete in insert mode for forward word deletion
In some terminals, Alt-Backspace might not work because it is ambigous.
See: https://github.com/helix-editor/helix/pull/2193#issuecomment-1105042501
Hence, Alt alternative is not removed.
=> feat(term): uniformize word-wise movement and deletion

book/src/configuration.md
> Valid values for these options are block, bar, underline, or none.
> [_configuration docs_](https://docs.helix-editor.com/configuration.html#editorcursor-shape-section)
This config
```toml
[editor.cursor-shape]
insert = "none"
```
leads to an error
`unknown variant 'none', expected one of 'block', 'bar', 'underline', 'hidden'`
=> fix wrong value for cursor shape config in the docs

book/src/generated/lang-support.md, languages.toml, runtime/queries/scss/highlights.scm, runtime/queries/scss/injections.scm
Adds SCSS language support:
- Highlighting
- Language server support
=> Add SCSS language support

languages.toml
The current build fails when publishing flake:
https://github.com/helix-editor/helix/runs/7376788959?check_suite_focus=true
This URL fails:
https://api.github.com/repos/serenadeai/tree-sitter-scss.git/tarball/c478c6868648eff49eb04a4df90d703dc45b312a
This one works:
https://api.github.com/repos/serenadeai/tree-sitter-scss/tarball/c478c6868648eff49eb04a4df90d703dc45b312a
=> Hotfix: Remove .git extension from SCSS url

book/src/keymap.md, helix-term/src/ui/picker.rs
Add a key to toggle preview panel so that we can get more info when searching files with long names.
=> support toggling pickers' preview panel

book/src/configuration.md, helix-term/src/ui/editor.rs, helix-view/src/editor.rs, helix-view/src/gutter.rs, helix-view/src/view.rs
If all gutters are removed, there are still an extra one padding, would be nice
to remove that to save some space.
[![asciicast](https://asciinema.org/a/aSUgtapPdQoZs2vZC14V1nGt8.svg)](https://asciinema.org/a/aSUgtapPdQoZs2vZC14V1nGt8)
=> Make gutters padding optional

helix-term/src/application.rs
After f10b6f6e, `hx file:row` doesn't work, because the first file skips `doc.set_selection()` in a loop now.
So I rewrote it as just a loop without `.skip(1)`.
It seems to work well.
=> Set the selection point of the first file correctly

runtime/queries/rust/locals.scm
The fix comes from the rewriting of the `closure_parameters` stanza:
it was capturing the entire `closure_parameters` node including
`|`s, whitespace and commas. Capturing the identifiers within
fixes the tracking.
In order to make sure locals definitions from closure parameters don't
leak out of the body of the closure, though, we should also mark the
closure itself as a locals scope.
|---|---|
| ![before](https://user-images.githubusercontent.com/21230295/178153007-6abbe31e-a613-4dbb-a3ec-d399d91e46e5.png) | ![after](https://user-images.githubusercontent.com/21230295/178153019-fe389a99-b78e-42d2-a60a-9031a712f4ae.png) |
Where `variable.parameter` is underlined white in my theme (notice `layer` and `r` above).
=> Fix locals tracking in Rust closures

runtime/themes/onedark.toml
After the following themes:
```
autumn
autumn_night
meliora
night_owl
rose_pine
solarized_dark
solarized_light
```
...comes **onedark**!
Regarding the colors (blue for normal, green for insert and purple for selection), I took inspiration from lualine, which uses these colors by default.
Additionally, I find it especially intuitive to have green for insertion (which we know from diffs) and blue for the regular, default state.
I opted for a dark foreground, as a light foreground simply lacks any minimal amount of contrast. A very dark gray ("light-black") seemed to yield the best results.
_For those who didn't know yet: This wonderful coloring feature comes from #2676 and must be enabled in the configuration by setting `color-modes = true` under `[editor]`._
=> Add mode colors (`color-modes`) to the "onedark" theme

book/src/configuration.md, helix-term/src/commands/typed.rs, helix-term/src/ui/statusline.rs, helix-view/src/editor.rs
File line endings: CRLF or LF.
=> add statusline element to display file line endings

book/src/generated/lang-support.md, languages.toml
See: https://gleam.run/news/v0.21-introducing-the-gleam-language-server/
Gleam has a built-in language server we can use in Helix 🙂 
I lifted this from the vscode plugin for Gleam: https://github.com/gleam-lang/vscode-gleam/blob/19a4a82f1afc769dfa32bbc9be22215249a8d1c2/src/extension.ts#L34
cc @lpil @the-mikedavis
=> Gleam: add support for built-in language server

book/src/keymap.md, helix-term/src/commands.rs, helix-term/src/keymap/default.rs, helix-view/src/view.rs
=> jumplist picker

helix-term/src/commands.rs, helix-view/src/editor.rs, helix-view/src/tree.rs, helix-view/src/view.rs
i was missing the beheviour from vim
=> keep jump/file history when using :split

helix-term/src/commands.rs
Fixes https://github.com/helix-editor/helix/issues/1673
Supersedes https://github.com/helix-editor/helix/pull/1379
No problems with multiple selections observed.
Putting match inside tuple would hurt readabilty - these tuples already take a while to comprehend.
Simple logic inspired by Godot 3.x stable branch:
https://github.com/godotengine/godot/blob/14f69acaa4ef80b235ef78f9caac1072daf8008b/scene/gui/text_edit.cpp#L2101
https://github.com/godotengine/godot/blob/14f69acaa4ef80b235ef78f9caac1072daf8008b/scene/gui/text_edit.cpp#L2054
=> Auto pair-removal

helix-view/src/document.rs
This tiny code change adjusts the default indentation behavior when no language-specific or user-defined setting applies.
_Wait, don't run away... We're not having the tabs vs. spaces discussion!_
Keep in mind we're talking about the behavior when Helix is opened for **regular text files** or with an **empty scratch buffer**:
At that moment, as a user, I expect the editor to act like a simple, "dumb editor".
At that moment I _don't_ expect Helix to replace tabs with spaces because Helix _thinks_ I could be programming in a language where spaces _could_ be more important.
A simple, dumb editor, inserts a tab when I press [Tab], and a space when I press [Space].
There's many examples of default behavior in simple editors; KWrite, Notepad, Writer on Mac, ... but also Vim and Emacs (when …
=> Indent with tabs by default (when no specific indentation settings apply)

runtime/themes/catppuccin.toml, runtime/themes/dracula.toml, runtime/themes/dracula_at_night.toml, runtime/themes/noctis.toml, runtime/themes/rose_pine.toml, runtime/themes/rose_pine_dawn.toml, runtime/themes/serika-dark.toml, runtime/themes/serika-light.toml, runtime/themes/snazzy.toml
Quick attempt at removing some warnings from the log.
I have no theming knowledge, so unknown colors are probably off.
=> helix_view::theme [WARN] Theme

languages.toml
Add missing `vh` verilog header file type to `file-types`
=> Add `vh` verilog header file type to `file-types`

helix-view/src/editor.rs
Issue #3148 
Would panic when given the view for the current document for a different document. This should fix the panic while keeping the jump history when splitting for the same file.
=> Fix different document panic

runtime/queries/heex/highlights.scm, runtime/queries/heex/injections.scm
* Highlights the open and close tags for comments as comments
* Injects the comment lang into HEEx comments
=> Improve HEEx comment highlights and injections

languages.toml
These are regular ruby files used for templating JSON API responses:
https://github.com/nesquena/rabl
https://github.com/rails/jbuilder
https://github.com/amatsuda/jb
=> Add rabl/jbuilder/jb extensions for Ruby

helix-loader/src/grammar.rs
Only send msvc args to the grammar compiler if we're targetting msvc.
Fixes https://github.com/helix-editor/helix/issues/1973
=> Fix non-msvc grammar compile on Windows

helix-loader/src/config.rs, helix-loader/src/lib.rs
This ensures that other values than just the top-level arrays are overridden, and makes this function generally more flexible, like merging nested objects, where it makes sense.
For the `languages.toml`, `merge_depth` is set to 3 so that top-level language features are merged (like 'scope'), but everything deeper is overridden with the user-config. With the current configuration schema the result should be equivalent to the current behavior. 
This change is a requirement for #2507 since language-servers there, are configured via a table instead of an array.
=> Refactor 'helix-loader::merge_toml_values' to use a 'merge-depth' instead of 'merge_toplevel_arrays'

book/src/keymap.md
There are a lot of different sets of keymaps. It would be nice to index them at the top so that they're easier to jump to.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/19535809/180630650-69bbd54a-e28d-4a28-be24-5b8e60c88137.png) | ![image](https://user-images.githubusercontent.com/19535809/180630670-b2052e64-3892-4695-9ecc-95b26aa77363.png) |
=> Add table of contents to keymap.md

book/src/configuration.md, helix-term/src/ui/statusline.rs, helix-view/src/editor.rs
Addresses #3106 and associated other comments. Multiple `"spacer"` elements may be specified in each statusline section.
=> add spacer element to statusline

book/src/configuration.md, helix-view/src/view.rs
Remove padding gutter type, and automatically add 1 padding if gutters is
non-empty.
Fix #3111
cc @kchibisov hopefully this solves your issue
Sad to see a breaking change but it should be fine given that we haven't do a release yet
=> Make gutters padding automatic

languages.toml, runtime/queries/python/highlights.scm
These changes were based on `nvim-treesitter`.
- Highlight import identifiers as `@namespace`
- Highlight boolean values as `@constant.builtin.boolean`
- Made `@keyword` captures more granular with the existing scopes. No new scopes were introduced.
- Added `@punctuation` captures.
=> Improve python highlighting

helix-core/src/diagnostic.rs, helix-lsp/src/lib.rs, helix-term/src/application.rs
This PR provides a solution to resolve #2994. missing Code Actions for lsp
=> add code for diagnostic.

flake.nix, grammars.nix
Adds a way change which grammars get built and included by adding an `override` function to the helix package that takes an `includeGrammarIf` attribute which is a function that decided whether the grammar should be included (`true`) or not (`false`). This also avoid fetching all of the grammars if you don't need them (like me) which speeds up fetching stuff when you are fetching when the sources aren't cached already. I also added `makeWrapperArgs` to the `override` function so it can be set there, I think @nrdxp asked about this.
=> build(nix): add a way to override what grammars get built

runtime/queries/rust/locals.scm
This fixes some edge-cases like [here](https://github.com/helix-editor/helix/blob/9a496237215dc09ef8f639fc79f7e63e2309c080/helix-term/src/commands.rs#L1752-L1757):
| before | after |
|---|---|
| ![before](https://user-images.githubusercontent.com/21230295/181211105-f4e0e0a5-5ce1-4d92-8d48-a641976d9442.png) | ![after](https://user-images.githubusercontent.com/21230295/181211136-63474190-750d-4b8e-9dce-093cc59501b0.png) |
I don't think it ever makes sense to have a let-declaration define a local, right? We want to tag parameters as `local.definition` so that you can identify function/closure parameters but let-declarations always create variable bindings even when pattern matching so we can use normal highlighting for those.
=> Remove let_declaration from Rust locals tracking

book/src/generated/lang-support.md, runtime/queries/javascript/textobjects.scm, runtime/queries/jsx/textobjects.scm, runtime/queries/tsx/indents.scm, runtime/queries/tsx/textobjects.scm, runtime/queries/typescript/textobjects.scm
=> Add textobject for javascript

runtime/themes/base16_transparent.toml
related #3059 
discussions #3142 
It was created based on the base16_default theme, and matches especially dark images.
The drawback is that the background is all transparent, making it hard to see pop-ups.
The pop-up background can be black for better visibility, but I don't do that.
=> Add transparent theme based on base16_default

helix-term/Cargo.toml
Adding rust-version ensure a check at compile that the compiler version can build helix. I have used [`cargo-msrv`](https://github.com/foresterre/cargo-msrv) to retrieve this value and it can be checked using `cargo msrv verify`.
This value is also useful to contributors, because they know which features they can use.
=> Add rust-version (MSRV) to helix-term package

helix-term/src/commands/dap.rs
cwd field has been changed in #2959 by making it a required field.
However, when starting the debugging session, cwd is not set, causing
an error in the deserialization part. Manually set cwd to the current
directory as a quick fix.
=> Add cwd parameter which is not optional anymore

book/src/generated/lang-support.md, languages.toml, runtime/queries/cue/highlights.scm
This PR add support for [CUE](https://github.com/cue-lang/cue) using [dagger/cuelsp](https://github.com/dagger/cuelsp) and [eonpatapon/tree-sitter-cue](https://github.com/eonpatapon/tree-sitter-cue).
I'm wondering if it's there's a way to give the `format` command another command than the lsp (`cue fmt`)?
It's not a big caveheat since https://github.com/dagger/cuelsp/issues/44 should resolve that anyway.
=> feat: add cue support

flake.nix
It only supports that platform: https://github.com/NixOS/nixpkgs/blob/433bd5e89cbb5fec3d16e90a9df4734ef2fe9fcb/pkgs/development/tools/analysis/cargo-tarpaulin/default.nix#L29
Without this `nix develop` fails with this error on my system:
```
error: Package ‘cargo-tarpaulin-0.20.1’ in /nix/store/.../cargo-tarpaulin/default.nix:25
is not supported on ‘aarch64-linux’, refusing to evaluate.
```
=> Only add cargo-tarpaulin on x86_64

helix-term/src/application.rs
I changed [this line](https://github.com/helix-editor/helix/blob/55b45ec4a4cb958b241a93cc7c3f4e499379890e/helix-term/src/application.rs#L791) by changing the 2 to a 0.
The previous escape code `\x1B[2 q` sets the cursor to be a static block according to [this specification](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_). The new escape code `\x1B[0 q` restores the cursor to the user's default.
To be honest, I'm not sure if this will fix the issue for everyone. It fixes it for me on arch linux using gnome and with the alacritty terminal. With this change, when I exit out of helix, my terminal cursor is restored to a blinking underscore.
@DivergentClouds found the solution, which he shared in issue #2684. 
There are also …
=> Fix terminal cursor shape reset

.github/workflows/release.yml, helix-loader/src/grammar.rs, helix-term/build.rs, helix-term/src/main.rs
Closes #1647.
A preview CI run based on this patch and the built artifacts can be found at <https://github.com/yvt/helix/actions/runs/2709143241>.
=> Enable CI builds for `aarch64-macos`

helix-core/src/syntax.rs
This fixes problems arising in #3108.
The markdown parser needs to exclude children for language injection, but only named ones. This is *different* from the behavior in tree-sitter-highlight, but to me it seems more sensible. 
To give a technical example: Otherwise there is almost no way to write something like
```js
rule: $ => seq('(', repeat(choice($._content, $.excluded)), ')'),
```
where `$._content` and the parentheses should be included and `$.excluded` excluded. This is because there will always be `'('` and `')'` nodes as a child of `rule`.
=> Exclude only named children without injection.include-children

.ignore
I've been using this .ignore file while working on Helix to let me use ripgrep without getting a big block of spurious result in highlight.js. I thought it might be useful for others. No worries if it isn't, I can just add it to my .git/info/exclude.
=> Add a .ignore file to make ripgrep more useful

book/src/languages.md, helix-core/src/syntax.rs, helix-lsp/src/lib.rs, helix-term/src/commands.rs, helix-term/src/commands/typed.rs, helix-view/src/document.rs, helix-view/src/editor.rs, languages.toml
I have never worked on a big project in rust, so I don't know if the `Result`/`Option` handling is ok.
This PR aims to allow the user to choose which formatter to use instead of always relying on lsp. Discussion about this in issue  #2362.
Currently the only problem is that write_all_impl saves only the viewed buffers, this is because the formatter needs to reload or apply the transaction to the document. How do we get around this?
=> Change default formatter for any language

helix-core/src/increment/date_time.rs, helix-term/src/ui/editor.rs, helix-view/src/handlers/dap.rs
Clippy was complaining about using `format!` to append to an existing `String`.
=> Resolve clippy lints

helix-core/src/selection.rs, helix-term/src/commands.rs, helix-term/src/commands/typed.rs, helix-term/src/ui/editor.rs
~Might fix #3127.~
This changes the `Range::fragment` and `Selection::fragments` to return `RopeSlice`. This way we can avoid copying the ropes' contents in a few cases, specifically
* `shell_impl`
* Sometimes one less copy in `switch_to_*case`
* Sometimes one less copy in all commands that "yank"
* Sometimes one less copy in `sort` and `rotate_selection_contents`
Also, it will make the computational overhead of copying the fragments more apparent in places where `Range::fragment` is used (until now it almost looked like there was no copy, since a `Cow` was returned).
(I also rewrite the mouse event handling because (I think, without optimizations) until now it copied the entire file on each mouse up event)
=> Avoid copying fragments

helix-term/src/commands/typed.rs
Indent style may change when choosing a language with `:set-language`.
Line-endings most likely will not change, but `:set-language` should
have a similar effect as reloading a file (`:reload`), plus the two
are currently grouped in the implementation and line-ending detection
is not particularly expensive.
That this didn't happen (prior to this change) is more noticeable because of https://github.com/helix-editor/helix/pull/3095
=> Detect indent-style in `:set-language`

helix-core/src/syntax.rs
Resolves #2986.
Resolves #3230.
Probably resolves #2484 as well, although I didn't have the code to copy paste in order to check :P
This is done by preferring matches in the beginning, i.e. for `keyword.function`, `keyword` is a better match than `function`.
Source for non-determinism: `HashMap` traverse order is different each time.
According to comments: 
> Consumers of these queries can choose to recognize highlights with different levels of specificity.
For example, the string `function.builtin` will match against `function.method.builtin` 
and `function.builtin.constructor`, but will not match `function.method`.
`keyword.function `can therefore match both `keyword` and `function`.
- Both of these matches have the same `match_len` which is what is used to rank them
- The list of …
=> Fix nondeterministic highlighting

contrib/completion/hx.elv
It has the expected basics:
But then `-g` and `--grammar` leads to only two suggestions
`--config` will only show files in it's completions.
Finally, flags that will not open the editor will stop further suggestions.
=> fix: add elvish completions

helix-term/src/commands.rs
Hi!
Another small PR which avoids adding the stdin handler in `shell_impl` when not necessary.
This allows to run commands that don't expect any stdin whtout getting a `ENOTTY` error.
While this works, I have no experience with terminals (and rust), so it might be the completely wrong approach.
=> Avoid setting stdin handle when not necessary

runtime/queries/php/highlights.scm
=> Fix php hightlight

helix-view/src/document.rs
literally just fixing a comment that become incorrect due to a change made for pr #3095
=> Fix comment

runtime/queries/rust/locals.scm
Function parameter highlighting was leaking into other scopes.
before:
after:
=> Rust queries: add `(function_item)` as a local scope

runtime/themes/doom_acario_dark.toml
This theme is ported from [acario themes](https://github.com/doomemacs/themes/blob/master/themes/doom-acario-dark-theme.el) from Doom Emacs.
I've however only focused on the dark one as that's the one I'm using.
=> Add Doom's Acario dark theme.

runtime/themes/spacebones_light.toml
* Adds cursorline (primary and secondary)
* Reworks colors slightly to try and match upstream theme better
* Distinguishes primary from regular selections
* Implements some of the markup specific styles
* Implements mode colors support
The upstream doesn't have much in the way of guides, so I did my best. Not expecting everyone to agree on the color choices but those can be further adjusted before or after merge.
=> Attempt to bring spacebones light up to speed with recent features

helix-term/src/ui/editor.rs, runtime/themes/dark_plus.toml
Resolves #3298.
The problem was that the indent guides would render on top of whitespace, and get their theme. The incorrect looking white indent guides were actually correct according to the theme.
The first part of the fix is to make the indent guides actually use the indent guide theme.
The second part is to make indent guides a sub theme of whitespace so that when not defined they will look like whitespace, which is the desired behavior. I updated all themes that set `ui.virtual.indent-guide` to use `ui.virtual.whitespace.indent-guide`, as well as updating the documentation.
=> Fix indent guide styling

helix-term/src/ui/editor.rs
Resolves #2992.
Works for tabs, as well as other wide graphemes such as `Ideographic Space "　"`
=> Fix tab highlight when tab is partially visible

book/src/generated/lang-support.md, languages.toml, runtime/queries/markdown.inline/highlights.scm, runtime/queries/markdown.inline/injections.scm, runtime/queries/markdown/highlights.scm, runtime/queries/markdown/injections.scm
See #3072.
Only a draft because `markdown_inline` grammar is not injected properly, but to me it seems like this is a problem with helix and not the language config? After a few experiments I think the grammar _is_ injected, but highlighting is still not done according to the injected language. I'm not very sure though.
Another weird behavior is with fenced code blocks. They seem to work to some degree, but if you enter something like
~~~markdown
```rust
let foo = "bar";
```
~~~
then `let` is highlighted correctly while `"bar"` is not highlighted at all.
=> Use split_parser branch for markdown grammar

helix-term/src/ui/mod.rs
Nested settings such as `search.wrap-around` are now also completed.
Addresses part of #2772 (show suggestion for sub-keys such as `cursor-shape.normal` but still no suggestions for valid values for that option)
=> Add completion for nested settings

Cargo.lock
This is causing builds to fail when there is no time zone info, e.g. Alpine, Android. Caused by an upstream issue:
https://github.com/chronotope/chrono/issues/755
=> revert chrono to 0.4.19

helix-term/src/application.rs, helix-term/src/commands.rs, helix-term/src/compositor.rs, helix-term/src/ui/completion.rs, helix-term/src/ui/editor.rs, helix-term/src/ui/menu.rs, helix-term/src/ui/overlay.rs, helix-term/src/ui/picker.rs, helix-term/src/ui/popup.rs, helix-term/src/ui/prompt.rs, helix-view/src/input.rs, helix-view/src/keyboard.rs
Add custom event type replacing crossterm's Event
Ported over from 61365dfbf3 in the `gui` branch. This will allow adding our own events, most notably an idle timer event (useful for adding debounced input in [dynamic pickers][1] used by interactive global search and workspace symbols).
[1]: https://github.com/helix-editor/helix/pull/3110
=> Add custom event type replacing crossterm's Event

helix-lsp/src/client.rs
I was looking at workspace symbols in Go based on some Matrix discussion. This doesn't appear to be related to `gopls` and workspace symbols not working but we should probably advertise the client capability anyways since it's implemented.
=> Advertise WorkspaceSymbolClientCapabilities support

README.md, book/src/install.md
xcopy doesn't copy recursively, so subfolders (themes, grammars etc.) aren't getting copied atm (see [here](https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/xcopy))
adding `/e` fixes that.
=> adds xcopy param to recursively copy runtime folder

book/src/generated/lang-support.md, languages.toml, runtime/queries/latex/highlights.scm, runtime/queries/latex/textobjects.scm
update tree-sitter-latex 
update highlights from https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/latex/highlights.scm
add textobject from https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/master/queries/latex/textobjects.scm
About highlights
I'm not sure about the markup for the Math section， It wasn't marked before. I left it as it was.
=> Update tree-sitter-latex and highlights

languages.toml
Hello,
I'd like some feedback on this PR since I don't fully understand all the fields that are being set in this table.
Does this edit look complete, or does the injection regex need to be updated in order to match some of the other file types, like `edn` and `boot`?
Otherwise, this is a simple update to add support for Clojure files supported by clojure-lsp but which aren't reflected in helix's language definition, and to correct the comment token.
File types
- `cljs` for ClojureScript
- `cljc` for cross-compiled Clojure files
- `clje` for Clojerl
- `cljr` for ClojureCLR
- `cljx` for legacy cross-compiled Clojure
- `edn` for Extensible Data Notation files, they are to Clojure what JSON is to JS
- `boot` for build files using the boot build tool
The last thing I'd like confirmation on is …
=> Update Clojure language definition

book/src/keymap.md
The docs currently don't list Tab and Shift-tab as options to scroll in the picker. This PR adds that
=> Update keymap.md to have Tab and Shift-tab listed

runtime/queries/rust/highlights.scm
Currently closure pipes highlight as operators, even though semantically they should be brackets. This PR adds an explicit highlight for pipes within the `closure_parameters` scope.
=> highlight closure pipes as brackets

helix-term/src/commands.rs
fixes #3374
I still like the change to avoid setting stdio if necessary, but it looks like this causes an issue on Windows.
After attempting other fixes, reverting the changes was the only thing that worked.
P.S. Conditional compilation could be added for non-Windows targets, but I think this would not add value to the codebase or Helix.
=> Revert conditional setting of stdin handle

runtime/queries/markdown/injections.scm
TOML identified by opening and closing +++.
YAML identified by opening and closing ---.
- https://gohugo.io/content-management/front-matter/#front-matter-formats
- https://docs.gitlab.com/ee/user/markdown.html#front-matter
- https://www.getzola.org/documentation/content/section/#front-matter
=> Fix Markdown Metadata

book/src/themes.md, runtime/queries/regex/highlights.scm, runtime/themes/autumn.toml, runtime/themes/autumn_night.toml, runtime/themes/base16_default_dark.toml, runtime/themes/base16_default_light.toml, runtime/themes/base16_terminal.toml, runtime/themes/base16_transparent.toml, runtime/themes/doom_acario_dark.toml, runtime/themes/flatwhite.toml, runtime/themes/night_owl.toml, runtime/themes/noctis.toml, runtime/themes/noctis_bordo.toml, runtime/themes/onedark.toml, runtime/themes/onelight.toml, runtime/themes/pop-dark.toml, runtime/themes/rose_pine.toml, runtime/themes/rose_pine_dawn.toml, runtime/themes/rose_pine_moon.toml, runtime/themes/serika-dark.toml, runtime/themes/serika-light.toml, runtime/themes/snazzy.toml, runtime/themes/spacebones_light.toml
- Replace "text" with "ui.text" in rose_pine* themes
- Change "attributes" to "attribute" in many included themes
- Document "attribute", "property" and "punctuation.special" in the theme section of the book.
- Remove "variable.function" from the documentation: it doesn't appear to exist in any highlights.scm.
- Remove "path" from snazzy; maybe it should be string.special.path?
=> Theme Related Fixes

book/src/configuration.md
Added statement that git related file-picker configurations only work in
a git repo.
Closes #3415
Can somebody confirm that actually all git related file-picker configurations options are only enabled in a git repo and not only the git-ignore option?
=> Improved file-picker configuration documentation

helix-loader/src/grammar.rs
feat: shorten output for grammar fetching and building
New look:
```
Fetching 102 grammars
98 up to date git grammars
4 updated grammars
bash      now on 275effdfc0edce774acf7d481f9ea195c6c403cd
beancount now on 4cbd1f09cd07c1f1fabf867c2cf354f9da53cc4c
c         now on f05e279aedde06a25801c3f2b2cc8ac17fac52ae
c-sharp   now on 53a65a908167d6556e1fcdb67f1ee62aac101dda
```
```
Building 102 grammars
100 grammars already built
2 grammars built now
["bash", "rust"]
```
=> feat: shorten output for grammar fetching and building

helix-core/src/textobject.rs, helix-term/src/commands.rs
Minor cleanups for easier understanding of functionality and code.
=> Adjust `m` textobject description and minor code clarification

languages.toml
while still [documented](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/doc/Using-Omnisharp.md) the `--stdio` flag for omnisharp is deprecated since 2019...
see: [here](https://github.com/OmniSharp/omnisharp-roslyn/pull/1362)
as well as [here](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Stdio/StdioCommandLineApplication.cs), [here ](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Host/CommandLineApplication.cs) and [here](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Http/HttpCommandLineApplication.cs)
=> removes deprecated stdio flag for omnisharp

book/src/generated/lang-support.md, languages.toml, runtime/queries/task/highlights.scm, runtime/queries/task/injections.scm
=> feat: add taskwarrior to languages so `task N edit` is nice

runtime/themes/penumbra+.toml
From Penumbra's [README](https://github.com/nealmckee/penumbra):
> Penumbra is a mathematically balanced colour scheme constructed in a perceptually uniform colour space with base colours inspired by the shades of colour occurring in nature due to the light of the sun and the sky. It cleanly separates the perceptual properties of colours while optimally utilizing the available colour space of typical displays.
This PR adds a new built-in theme to Helix using the Penumbra+ color scheme. The "+" is for "higher-contrast". Similar versions of this theme for the "balanced" (lower-contrast) and "++" (even higher contrast) variants of Penumbra can be created just be modifying the palette at the bottom of the theme according to the values in Penumbra's README.
---
This PR is currently in draft …
=> add penumbra+ theme

book/src/configuration.md, helix-term/src/ui/editor.rs, helix-view/src/editor.rs
Resolves #3427.
Added new `whitespace.characters.tabpad` option which sets the padding for tabs
Example:
=> Allow tab virtual whitespace padding

languages.toml
Fixes #2997 
The commit with the actual fix is: elm-tooling/tree-sitter-elm@a66f8b0d6060c56852df87e3007074b2ad3dd26b
=> Update tree-sitter-elm to latest commit

Cargo.lock, helix-term/Cargo.toml, helix-term/src/ui/editor.rs, helix-tui/Cargo.toml, helix-view/Cargo.toml, helix-view/src/input.rs, helix-view/src/keyboard.rs
I've got a couple PRs that depend on this update. I thought it'd be nice to get the library bump in separately to keep from conflating any issues.
=> Update to crossterm-0.25

helix-term/src/health.rs
Use the same tick as book to reduce margin of whitespace errors.
Before
After
This may be a terminal issue, but at the same time I just make it consistent with the docs. Also, I noticed this because I saw the same symbol in https://rsdlt.github.io/posts/rust-nvim-ide-guide-walkthrough-development-debug/.
=> Reduce health tick width

helix-term/src/ui/markdown.rs
Relates to https://github.com/helix-editor/helix/pull/3425 and https://github.com/elixir-lsp/elixir-ls/issues/694
Properly handles the rendering of indented code blocks in markdown. Given that we do not have a language identifier available, we style these blocks as generic code (visually distinct from markdown text, but no highlighting via tree-sitter).
This improves the experience of writing Elixir in Helix, as the majority of documentation favors indentation over fences.
**Before** ☹️ 
**After** 😁
=> Fix rendering of indented code blocks in markdown

languages.toml, runtime/queries/dart/indents.scm
This PR improves the indentation for dart. It is based on a more recent version of the grammar, so it updates it in addition to changing `runtime/queries/dart/indents.scm`
=> Improve dart indent

book/src/generated/lang-support.md, languages.toml, runtime/queries/esdl/highlights.scm
Adds grammar for EdgeDB's SDL as well as highlight queries.
ESDL: https://www.edgedb.com/docs/datamodel/index
Grammar: https://github.com/greym0uth/tree-sitter-esdl
=> feat(lang): Add esdl grammar

languages.toml, runtime/queries/julia/highlights.scm, runtime/queries/julia/injections.scm, runtime/queries/julia/locals.scm
This PR updates the grammar to the newest version and does a major refactoring of the `highlights.scm`.
I reorganized the file to make it more managable and fixed the broken, obsolete and missing queries (there was a lot). This will probably need another polishing pass in the future but this should be enough for now.
I also added regex injections and some locals.
=> Julia queries: update grammar, major refactoring

book/src/generated/lang-support.md, languages.toml, runtime/queries/awk/highlights.scm, runtime/queries/awk/injections.scm, runtime/queries/awk/textobjects.scm, runtime/queries/bash/injections.scm
=> AWK support

runtime/themes/doom_acario_dark.toml
Changed the `namespace` style to fix the issue (#3533).
I also made the theme look a little closer to how it looks in Emacs, I did however opt to still have it slightly different as I found it easier to read with my port than on the original in Emacs.
I also sorted most keys (mainly from line 8 to 28) for the theme to be in alphabetical order, so it's easier to have a quick glance where they are.
=> Fixed Doom acario theme

book/src/generated/lang-support.md, languages.toml, runtime/queries/c-sharp/highlights.scm, runtime/queries/c-sharp/textobjects.scm
This PR adds basic textobjext based navigation for c-sharp.
=> Add c-sharp textobjects

helix-view/src/editor.rs
https://github.com/wez/wezterm is a terminal emulator with its own built-in multiplexer
=> Add wezterm to get_terminal_provider

helix-term/src/application.rs, helix-term/src/commands.rs, helix-term/src/compositor.rs, helix-term/src/ui/completion.rs, helix-term/src/ui/editor.rs, helix-term/src/ui/menu.rs, helix-term/src/ui/overlay.rs, helix-term/src/ui/picker.rs, helix-term/src/ui/popup.rs, helix-term/src/ui/prompt.rs, helix-view/src/input.rs
This adds bracketed paste support to fix https://github.com/helix-editor/helix/issues/2239. It's based on [this PR on crossterm](https://github.com/crossterm-rs/crossterm/pull/693), so that will need to land and be released before this can be merged.
I haven't done any serious benchmarking, but I tried the [Moby Dick Workout](https://www.hogbaysoftware.com/posts/moby-dick-workout/). Pasting with this enabled took maybe a tenth of a second to get the whole meg of book in there. Without this, I think it would've taken a day or so.
=> Add bracketed paste

helix-term/src/commands/lsp.rs, helix-term/src/ui/completion.rs, helix-term/src/ui/statusline.rs, helix-view/src/document.rs
This changes switches from deriving the language name from the
`languages.toml` `scope` key to `name` (`language_id` in the
`LanguageConfiguration` type). For the most part it works to derive
the language name from scope by chopping off `source.` or `rsplit_once`
on `.` but for some languages we have now like html (`text.html.basic`),
it doesn't. This should be a more accurate fallback for the `language_id`
method which is used in LSP and currently uses the `rsplit_once`
strategy.
Here we expose the language's name as `language_name` on `Document` and
replace ad-hoc calculations of the language name with the new method.
This is most impactful for the `file-type` statusline element which is
currently using `language_id`.
It should also improve highlighting in popups for languages like …
=> Derive Document language name from languages.toml name key

helix-term/src/commands.rs, helix-view/src/document.rs
As mentioned by @dead10ck in https://github.com/helix-editor/helix/pull/2942#discussion_r939606221 if something is printed to stderr it doesn't mean that the process failed, so we need to check the exit code and then print stderr if there is anything. This should also be valid when calling the shell from helix
=> Fix process spawning error handling

helix-term/src/ui/editor.rs
When changing the focused view with C-w for example, the w event was
being handled in the EditorView event handler as if it belonged to
the newly focused window.
~Instead of handling the event for the newly focused window, we should
return early. We don't want the change in focus to trigger a history
checkpoint (following block) and we don't want to execute the mode
transition hooks (the block after). With some configs this can cause
a panic, for example~
keys.normal.w = ["no_op"]
keys.normal.C-w.m = "rotate_view"
~since these fall into the `unimplemented!` in the mode transition block.~
Instead of handling the event in the newly focused view, we should handle
the event in the original view.
=> Use the current document and view for mode-change hooks

helix-term/src/commands.rs
This change adds documents to the view's document history Vec.
(This is used by `ga` for example to access the last buffer.)
Previously, a sequence like so would have confusing behavior:
1. Open file A: any document with an active language server
2. Find some definition that lives in another file - file B - with `gd`
3. Jump back in the jumplist with `C-o` to file A
4. Use `ga` intending to switch back to file B
The behavior prior to this change was that `ga` would switch to file
A: you could not use `ga` to switch to file B.
=> jumplist: Add documents to view history

README.md, book/src/install.md, docs/releases.md
Now that helix is packaged in homebrew-core, I don't think it's necessary to run the tap anymore.
It's difficult to install a formula from a tap because core has higher precedence than taps: you need to first tap helix `brew tap helix-editor/homebrew-helix` and then `brew install helix-editor/homebrew-helix/helix` (https://docs.brew.sh/Taps#formula-with-duplicate-names).
=> packaging: Point to homebrew-core instead of tap

languages.toml, runtime/queries/c/highlights.scm, runtime/queries/erlang/highlights.scm, runtime/queries/rust/highlights.scm
Closes #3463
Updates tree-sitter-rust to the latest which fixes some edge-cases in the parsing. It doesn't look like there were any breaking changes and scanning around the code I don't see anything off.
I also have some random fixes here for:
* The `#` in rust attributes
* C booleans, `const` and `<=`/`>=` operators
* Empty Erlang records and Edoc-style auto-pairs
=> Update tree-sitter-rust and fix C, Rust and Erlang highlights

helix-term/src/application.rs
This is invalid according to the [LSP spec]:
> In addition the server is not allowed to send any requests
> or notifications to the client until it has responded with an
> InitializeResult, with the exception that during the initialize
> request the server is allowed to send the notifications
> window/showMessage, window/logMessage and telemetry/event as well
> as the window/showMessageRequest request to the client.
So we should discard the message when the language server is not
yet initialized. This can happen if the server sends
textDocument/publishDiagnostics before responding to the initialize
request. clojure-lsp appears to exhibit this behavior in the wild.
[LSP Spec]: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize
=> Discard LSP publishDiagnostic when LS is not initialized

helix-term/src/commands.rs
This refactor changes the overall structure of the goto_ts_object_impl
command without removing any functionality from its behavior. The
refactored motion:
* acts on all selections instead of reducing to one selection
* may be repeated with the `repeat_last_motion` (A-.) command
* informs the user when the syntax-tree is not accessible in the current buffer
Ultimately this moves the `goto_ts_object_impl` function closer to the `goto_para_impl` function and is part of (but kinda unrelated to) adding extend variants (https://github.com/helix-editor/helix/issues/3263)
Closes #1993
=> Refactor `goto_ts_object_impl` as a motion

helix-term/src/ui/editor.rs
Fixes a panic with a config like:
[keys.normal.space]
x = [":buffer-close"]
by bailing out of the command-execution handling if the document
doesn't exist after handling a command.
See https://github.com/helix-editor/helix/pull/2634#discussion_r959288551
=> Avoid command execution hooks on closed docs

helix-term/src/application.rs
It was starting to diverge as the normal exit code was restoring the prompt but the panic code
wasn't, and the panic code was disabling bracketed paste but the normal code wasn't.
This changes the panic path slightly in that we won't disable raw mode if exiting alternate screen
and disabling bracketed paste fails. If that happens, things are so busted I don't think it matters
anyway.
=> Share the restore_term code between panic and normal exits

helix-term/src/health.rs, helix-term/src/main.rs
=> Show clipboard info in --health output

helix-term/src/commands/dap.rs, helix-term/src/ui/mod.rs, helix-term/src/ui/picker.rs, helix-term/src/ui/prompt.rs, helix-term/tests/integration.rs, helix-term/tests/test/prompt.rs
Fixes a panic related to completion when using the arrow keys to navigate through the prompt history.
Minimal reproduction steps for the panic
```
<launch helix>
:asdf<Enter> <- Anything that is shorter than what you will be trying to complete next works.
:theme d <- Note that triggering completion is not necessary since it's recalculated on each character entry.
<up arrow>
<tab>
```
It should not be possible to modify the prompt `line` without also updating completion list. Most functions modifying the `line` update the completions. `Prompt::insert_str` and `Prompt::change_history` does not which allows this panic to happen. This means that the `<c-s>` shortcut probably also can create a panic and there are also possible panics in the DAP prompt as well …
=> fix: Recalculate completion when going through prompt history

helix-term/src/commands.rs, helix-term/src/ui/prompt.rs
This PR prevents putting the last entered prompt command into the history stack if it was already the top. For example, if you execute `:o <file>` first and then execute `:w` three times in the prompt, the current state stores the `:w` command three times in the history register and you have to scroll three times up to retrieve the entered `:o <file>` command. This PR fixes it.
=> fix: prevents storing last prompt if is top of stack

runtime/tutor.txt
I'm pretty sure this is what was originally intended.
=> fix: typo in tutor about searching compared to vim

runtime/themes/monokai_pro_spectrum.toml
Text painted in red (JSON object keys for example) is not visible in case
of error. Change to magenta can fix this.
before:
after:
=> Change MonokaiProSpectrum theme error background from red to magenta.

helix-term/src/ui/editor.rs, helix-view/src/tree.rs
=> Fix closing buffer with custom keymap

runtime/themes/varua.toml
Porting the color palette I've been using for a couple years before moving to Helix.
Cheers :)
=> theme: Add Varua color scheme

.github/workflows/cachix.yml, flake.lock, flake.nix
Updates NCI, separates wrapping of hx binary to another derivation so that helix doesn't get recompiled when grammars or runtime get changed, adds filtering to source for helix-term build so that unnecessary rebuilds are reduced.
=> build(nix): update nci, refactor flake, seperate wrapping, add source filtering

flake.lock
This updates NCI, updating dream2nix in turn which has a pretty critical bug fix regarding to caching (https://github.com/nix-community/dream2nix/pull/287)
=> build(nix): update flake deps

.github/workflows/build.yml, helix-core/src/indent.rs, helix-term/src/ui/prompt.rs, helix-view/src/tree.rs
Resolves #3150.
Fixes cargo doc warnings, and adds GitHub action to ensure cargo doc runs without warnings
=> Fix cargo doc warnings, and add GitHub action to ensure it

helix-view/src/document.rs
Currently it is not possible to save a file with a language that
has an external formatter configuration unless the external
formatter is installed, even if the language has a Language Server
configuration capable of auto-format. This change checks that the
external formatter exists before using it to create a formatting
callback.
=> Look for the external formatter before invoking it

helix-term/src/commands.rs
`extend_line_above` (and `extend_line` when facing backwards) skip
a line when the current range does not fully cover a line.
Before this change:
foo
b#[|a]#r
baz
With `extend_line_above` or `extend_line` selected the line above.
#[|foo
bar]#
baz
Which is inconsistent with `extend_line_below`. This commit changes
the behavior to select the current line when it is not already
selected.
foo
#[|bar]#
baz
Then further calls of `extend_line_above` extend the selection up
line-wise.
=> Fix off-by-one in extend_line_above

book/src/keymap.md
I wanted to remap the file picker for the current working directory but didn't know which command it uses because it's missing from https://docs.helix-editor.com/keymap.html#space-mode. It was easy to find that it's `file_picker_in_current_directory` by looking at the code but I figured it would be good to update the documentation so the next person doesn't have to do this again.
=> Add `file_picker_in_current_directory` to `keymap.md`

README.md, book/src/install.md
By default xcopy asks if the destination is a file or directory. Since we know it's a directory we can add the `/i` flag and prevent an extra prompt.
Description of `/i`
```
If source is a directory or contains wildcards and destination does not exist, 
xcopy assumes destination specifies a directory name and creates a new directory. 
Then, xcopy copies all specified files into the new directory.
```
=> xcopy - assume destination is a directory

runtime/queries/elixir/injections.scm, runtime/queries/elixir/textobjects.scm
This PR makes the following changes to the Elixir tree-sitter queries:
* tree-sitter text object comments are now grouped together
* markdown is injected into Phoenix Live View declarative attribute `:doc` options
See the following examples:
- https://github.com/phoenixframework/phoenix_live_view/blob/c1c4754e772de529529a046b42f5fdf02c66dede/lib/phoenix_component.ex#L1452
- https://github.com/phoenixframework/phoenix_live_view/blob/c1c4754e772de529529a046b42f5fdf02c66dede/lib/phoenix_component.ex#L1418
- https://github.com/phoenixframework/phoenix_live_view/blob/c1c4754e772de529529a046b42f5fdf02c66dede/test/phoenix_component/declarative_assigns_test.exs#L583
=> Elixir: update tree-sitter queries

languages.toml, runtime/queries/nix/injections.scm
By simply placing a comment with the name of the desired language above a multi-line string, that language will be injected.
Opening as a draft because I'm sure there must be a better way to write this, and hopefully someone with more experience can give me some pointers. Tried using repetition via `*` but I couldn't seem to get it right.
=> nix: add language injections

.github/workflows/release.yml
Closes #3237
A preview CI run based on this patch + `22.08.1` can be found at <https://github.com/yvt/helix/actions/runs/2987431541>. The "release" artifact contains `helix-dev-aarch64{.AppImage,-linux.tar.xz}`.
=> Enable CI builds for `aarch64-linux`

runtime/queries/nix/highlights.scm
* avoid coloring `identifier`s globally
* fix function application when not part of `select_expression`
* add `has_attribute_expression` highlighting
* fix precendence for interpolation, which should be after select
* highlight `@` as delimiter
=> nix: fix highlighting rules

runtime/queries/rust/highlights.scm
With the update in https://github.com/helix-editor/helix/pull/3467, attribute identifiers were no longer marked as `@function.macro` - the grammar now marks these as `attr_item`s containing a `token_tree`.
=> Fix Rust attribute highlights

helix-view/src/document.rs
Adresses [comment](https://github.com/helix-editor/helix/pull/3670#issuecomment-1236150951)
If formatting fails, report error to log and save without formatting.
log entry looks something like this:
`2022-09-04T13:17:52.359 helix_view::document [ERROR] Formatter exited with non zero exit status`
(tested by adding formatter to `$PATH` which is just a shell script that returns exit status)
```bash
#!/usr/bin/env bash
exit 1
```
=> Handle formatter errors, and save anyway

languages.toml
Around 50 columns for the summary is good because it is often used as heading or as subject in emails. 72 columns for the body is generally good because some tools do not wrap long lines (`git log` with pager `less` is a good example). Helix's `:reflow` command is really good to help with the second point.
Linux kernel documentation says:
> For these reasons, the ``summary`` must be no more than 70-75 characters, and it must describe both what the patch changes, as well as why the patch might be necessary.  It is challenging to be both succinct and descriptive, but that is what a well-written summary should do.
Source:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst#n627
tpope: …
=> Add good default rulers when editing git messages

languages.toml
Markdown files can also end with `.markdown`.
This fixed the highlighting not being enabled in files that end with `.markdown` for me.
=> Add "markdown" as a possible filetype

book/src/generated/lang-support.md, languages.toml
Old one is abandoned and lacks many features and fixes therefore it is necessary to use https://github.com/Leathong/openscad-LSP instead.
=> change to openscad-lsp

book/src/generated/lang-support.md, languages.toml
Add jsonnet-language-server for jsonnet language.
See: https://github.com/grafana/jsonnet-language-server
=> feat(lsp): jsonnet-language-server

helix-loader/src/grammar.rs
Currently errors are listed from 0 up until 1 less than the total number, like so:
```
107 grammars failed to fetch
Failure 0/107: ...
...
Failure 105/107: ...
Failure 106/107: ...
```
This just makes it start at 1 and go until 107/107 for this example
=> ordinals instead of indexes when listing grammar fetch errors

helix-term/src/commands/typed.rs, helix-term/src/ui/mod.rs, helix-view/src/document.rs
Add `text` to completion for possible languages, and report error if user inputs invalid language.
=> Improve `:set-language` command

helix-term/src/application.rs
=> Improve error handling for config-reload

.github/workflows/release.yml
AppImage build is not possible for now because [AppImageKit](https://github.com/AppImage/AppImageKit/blob/729a1a60e41cdd90554462495576cdae4a2896ed/src/appimagetool.c#L68-L73) does not recognize the architecture name.
~~A preview CI run based on this patch + `22.08.1` can be found at <https://github.com/yvt/helix/actions/runs/2987576146>.~~ (out of date)
=> Enable CI builds for `riscv64-linux`

.github/workflows/release.yml
Expands the trigger sources of the release CI workflow (`release.yml`), allowing the developers to test changes to `.github/workflows/release.yml` easily. The new trigger sources start the workflow in a *preview* mode, in which it publishes build outputs as a CI artifact ([example](https://github.com/yvt/helix/actions/runs/2987431541)) instead of creating a new release so that they can be manually inspected.
The following events trigger the preview mode:
- Pushing to any branch matching the glob pattern `patch/ci-release-*`.
- Opening a pull request that modifies `.github/workflows/release.yml`.
- Pushing versioning tags to a forked repository (they would create a release otherwise).
=> Support "preview" release CI runs

.github/workflows/release.yml
Replaces the post-build strip step with a new pre-build step that sets `profile.release.strip = true`. The effect is identical to #3327, but this approach sidesteps [the MSRV issue](https://github.com/helix-editor/helix/pull/3327#issuecomment-1205158407) by not committing the change.
~~*Note:* Untested! We should check the result using #3757 just in case.~~ https://github.com/helix-editor/helix/pull/3780#issuecomment-1242755396
=> Strip release binary by setting `profile.release.strip` in a pre-build step

runtime/themes/monokai_pro_spectrum.toml
Make whitespace in monokai-pro-spectrum theme one step dimmer to avoid the white space confusion with hyphen.
before:
after:
=> Make whitespace in monokai-pro-spectrum theme one step dimmer

runtime/tutor
As a follow-up to https://github.com/helix-editor/helix/pull/3671
The tutor mentioned that arrow keys can be used in insert mode which is no longer the case
See #3808
=> Remove arrow key recommendation from tutor

helix-core/src/syntax.rs
Remove an unwrap identified in #3816 that caused a crash in syntax.rs
=> fix: map_err()? instead of unwrap

book/src/generated/lang-support.md, languages.toml, runtime/queries/astro/highlights.scm, runtime/queries/astro/injections.scm
Adding syntax highlighting for Astro files using the grammar defined here: https://github.com/virchau13/tree-sitter-astro.
This is my first time attempting a contribution to Helix, please let me know if I've missed a step or if any alterations should be made. Aside from verifying these additions with some Astro files, I have run `cargo xtask docgen` and `cargo integration-test` according to the contribution guidelines to update the docs and verify all tests still pass.
=> feat: Syntax highlighting for Astro files

helix-term/src/ui/markdown.rs
Resolves #3411.
Before:
After:
=> Render html `<code>` tags as code in markdown

flake.nix
LLDB is marked broken on ~all arches except for x86_64-linux~ aarch64-darwin. So we can fix `nix develop` by removing lldb for it on aarch64-darwin
=> Fix Nix flake devShell on aarch64-darwin

helix-loader/src/lib.rs
When looking up the runtime/ directory relative to the executable path, canonicalize the path first in case the executable is a symbolic link.
Fixes #3768
=> Canonicalize executable path

runtime/themes/fleetish.toml
- Adjusted the readability of whitespace
- Primary selection highlight should be more readable now (#3842).
=> improve fleetish theme

languages.toml, runtime/queries/jsx/indents.scm, runtime/queries/tsx/indents.scm
Adding JSX tag indents for JSX and TSX files, addressing issue #3820
=> fix: Improving JSX and TSX indents

book/src/generated/lang-support.md, languages.toml
Marksman is an LSP server for Markdown: https://github.com/artempyanykh/marksman
It supports a bunch of LSP features: symbols, references, rename, diag, etc. and already has integrations with emacs, neovim, and vscode. I think it can be a good addition to Helix.
_Context_:
I'm the author of Marksman. I've recently got [a bug-report](https://github.com/artempyanykh/marksman/issues/45) from a user that Marksman doesn't work with Helix. I haven't heard about Helix before, but it looked like an awesome project, so I  fixed a couple things and now the latest release of Marksman seems to work pretty well with Helix.
=> Add Markdown LSP via Marksman

book/src/generated/lang-support.md, languages.toml, runtime/queries/bass/highlights.scm
Hiya, I'm working on an admittedly pretty obscure language called [Bass](https://bass-lang.org). I just finished writing a tree-sitter grammar and highlighter for it, and then got the itch to try out Helix, having been a fan of Kakoune in the past. I'm really impressed with the out-of-the-box experience. :)
I initially tried configuring this in my own `~/.config/helix/languages.toml` but I'm on NixOS so the grammar install path is read-only. Adding it directly to Helix seems to be the only way at the moment. (#3310 & #3346)
My language is still very young so I'll take no offense if you prefer to just close this, but I figured I'd shoot my shot!
=> add `bass` language + highlighting

.github/workflows/msrv-rust-toolchain.toml
Almost all distributions (even ubuntu) now support 1.59.0.
The original MSRV was set to 1.57 to support void linux and homebrew.
Both now ship version 1.63.
This MSRV bump is required to use gitoxide (see #3890) but many crates
have bumped their MSRV to 1.59 and therefore the same problem will likely also occur for other dependencies in the future.
=> raise msrv to 1.59

helix-view/src/document.rs
Applying document-change transactions to diagnostic ranges is not stable with respect to the ordering of diagnostics. This can cause diagnostics to become temporarily unordered with some edits to a document, which can eventually break some invariants/assumptions in `syntax::merge`. The result can be a flash of "ghost" (duplicated) text before the language server refreshes the diagnostics (which causes the diagnostics to be re-sorted).
With this change, `Document::diagnostics` are always sorted.
I found this while debugging some broken invariants in #3695.
=> Re-sort diagnostics after transaction transform

helix-core/src/diagnostic.rs, helix-lsp/src/lib.rs, helix-term/src/application.rs
In #3005, Haskell users have been running into an issue where many of the CodeActions supported by the `haskell-language-server` are not present in Helix.
By my read of things:
- `hls` generates diagnostics and sends them to Helix
- Helix stores these, but discards the `source` and `tags` fields
- The user triggers a codeAction query
- Helix sends `textDocument/codeAction` to `hls`, in the `context` field it includes the relevant diagnostic _but without the `source` and `tags` that have been discarded_
- `hls` generates codeActions for all diagnostics it knows about (freshly computing the diagnostics, which include the `source` and `tags` fields), [only returning them if the freshly generated diagnostic matches the diagnostic in the `textDocument/codeAction` …
=> Track source and tags in diagnostics

helix-term/src/commands/typed.rs, helix-term/src/ui/prompt.rs
closes https://github.com/helix-editor/helix/issues/3620.
This works by ensuring an abort is sent to the original command. The update callback being moved is for ensuring the completion shows for the correct command.
=> Fix preview bug

book/src/generated/typable-cmd.md, helix-lsp/src/lib.rs, helix-term/src/commands/typed.rs
May or may not fix https://github.com/helix-editor/helix/issues/523
=> add :lsp-restart command

runtime/queries/rust/highlights.scm
Resolves #3922 with the fix suggested by @the-mikedavis
=> Fix highlighting on single-character Rust consts

helix-term/src/keymap.rs
Currently, opening helix with a config containing a bad command mapping fails with a cryptic error. For example, say we have a config (bad.toml) with a command name that doesn't exist:
```toml
[keys.normal]
b = "buffer_close" # should be ":buffer-close"
```
When we `hx -c bad.toml`, we get...
> Bad config: data did not match any variant of untagged enum KeyTrie for key `keys.normal` at line 1 column 1
> Press <ENTER> to continue with default config
This is because of the way that Serde tries to deserialize untagged enums such as `helix_term::keymap::KeyTrie`. From the Serde docs[^1]:
> Serde will try to match the data against each variant in order and the first one that deserializes successfully is the one returned.
`MappableCommand::deserialize` fails (returns an Err variant) when a …
=> Improve keymap errors from command typos

runtime/themes/papercolor-dark.toml, runtime/themes/papercolor-light.toml
With horizontal splits it was hard to visually distinguish
the beginning of the adjacent splits content.
Only went by eye for the closest match from (1). Feedback appreciated!
(1): https://github.com/NLKNguyen/papercolor-theme
=> Theme: Papercolor: Tune inactive statusline

.github/workflows/msrv-rust-toolchain.toml, Cargo.lock, docs/CONTRIBUTING.md, helix-term/Cargo.toml, helix-term/src/ui/picker.rs
The MSRV was previously bumpbed in to 1.59 in #3896.
However the newest gitoxide version (which contains some nice API additions usable in #3890) requires 1.60, because the bstr crate bumped its MSRV.
Before #3896 the MSRV was set to 1.57 to support void linux and homebrew.
Both now ship rust 1.63.
I checked [repology](https://bugs.launchpad.net/ubuntu/+source/rustc/+bug/1986648) and all distributions that ship the newest helix version also already ship at least rust 1.61.
However setting the MSRV to some arbitrary value again seemed bad to me and so I looked into MSRV in more detail.
The (mainstream) package repository which updates rustc last are usually ubuntu, debian and enterprise distributions like REHL.
Debian and REHL ship ancient rustc versions anyway that are hard to support …
=> Bump MSRV to 1.61 and document MSRV policy

helix-core/src/lib.rs, helix-loader/src/lib.rs, helix-lsp/src/client.rs, helix-term/src/commands.rs
The documentation of find_root described the following priority for detecting a project root:
- Top-most folder containing a root marker in current git repository
- Git repository root if no marker detected
- Top-most folder containing a root marker if not git repository detected
- Current working directory as fallback
The commit contained in https://github.com/helix-editor/helix/pull/1249 extracted and changed the implementation of find_root in find_root_impl, actually reversing its result order (since that is the order that made sense for the local configuration merge, from innermost to outermost ancestors).
Since the two uses of find_root_impl have different requirements (and it's not a matter of reversing the order of results since, e.g., the top repository dir should be used by …
=> Split helix_core::find_root and helix_loader::find_local_config_dirs

languages.toml
Simplify opening an Elixir project placed in a monorepo
=> Add mix.exs and mix.lock as Elixir root markers

runtime/tutor
Correctness aside, _“the line below marked”_ reads oddly, and makes one assume _“below --->”_ for a second.
=> docs: Punctuation on tutor

runtime/themes/acme.toml, runtime/themes/ayu_dark.toml, runtime/themes/ayu_light.toml, runtime/themes/ayu_mirage.toml, runtime/themes/base16_default_dark.toml, runtime/themes/base16_default_light.toml, runtime/themes/bogster.toml, runtime/themes/catppuccin_frappe.toml, runtime/themes/catppuccin_latte.toml, runtime/themes/catppuccin_macchiato.toml, runtime/themes/catppuccin_mocha.toml, runtime/themes/darcula.toml, runtime/themes/dark_plus.toml, runtime/themes/doom_acario_dark.toml, runtime/themes/emacs.toml
Fixes visual discrepancy with a few themes by adding bufferline colors. There's one issue in a few commits where I've added `fg` to `ui.bufferline.background` where it was unnecessary. I only realized later. It does not break anything though.
=> Add bufferline colors to 15 themes

runtime/queries/ruby/indents.scm
`do_block` and `block` seem to conflict, causing double-indentation in some cases. Removing `do_block` does not seem to have any negative effect, while fixing the double-indentation issue.
=> Remove `do_block` from Ruby indents

grammars.nix
The `runCommandNoCC` alias was deprecated in https://github.com/NixOS/nixpkgs/pull/134225 and removed in
https://github.com/NixOS/nixpkgs/pull/192681.
This PR fixes/preempts code breakage from this change.
=> nix: replace `runCommandNoCC` with `runCommand`

runtime/themes/gruvbox-dark.toml, runtime/themes/gruvbox_dark_hard.toml
Uses the [official gruvbox dark hard colors](https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L89).
There's already [gruvbox_light](https://github.com/helix-editor/helix/blob/master/runtime/themes/gruvbox_light.toml) so let's also have gruvbox_dark. :)
To note, it would be technically more correct to rename the original gruvbox helix theme to `gruvbox_dark` and have _this_ one be called `gruvbox_dark_hard` but eh, it would break some configs.
=> Add gruvbox dark

runtime/tutor
Fixed the mismatch of the word `favourite` and `favorite` in the tutor.
So i fixed that to be synchronous now.
=> Fix tutor typo `favourite` to `favorite`

runtime/tutor
In tutor 5.2, when the user wants to remove the second cursor, he has to exit the Insert mode first.
=> Tutor 5.2.: Missing <ESC> before removing the second cursor

languages.toml, runtime/queries/wgsl/highlights.scm
This PR adresses #3982. tree-sitter-wgsl is bumped to the latest commit and highlights.scm is updated accordingly.
The updated highlights file is based on the one in the tree-sitter-wgsl repository but with a few changes to make it work properly in Helix. If there are any problems with it let me know.
=> WGSL syntax highlighting fix

book/src/generated/lang-support.md, languages.toml, runtime/queries/wast/highlights.scm, runtime/queries/wat/highlights.scm
Adds support for the WebAssembly text format with some basic queries.
=> Add support for webassembly text format

helix-term/src/commands.rs
addresses #4038 and "follow up" from PR #4043
credits to https://github.com/helix-editor/helix/pull/4043#pullrequestreview-1126084661 
I did not know that resetting the head would close the PR. Hope this is ok
=> Ensure cursor in view after format

helix-term/src/commands.rs
Closes #4050.
Adds support for the following commands:
- Find 'till next char: *t*
- Find 'till previous char: *T*
- Find next char: *f*
- Find previous char: *F*
- Extend 'till next char: *t*
- Extend 'till previous char: *T*
- Extend next char: *f*
- Extend previous char: *F*
=> Add pseudo_pending for t/T/f/F

languages.toml, runtime/queries/markdown/injections.scm
Fixes broken table highlighting: https://github.com/helix-editor/helix/issues/3849
[MDeiml](https://github.com/MDeiml), the creator of the treesitter syntax said there was no need to update any queries:
>Updating to the latest commit helped, because I added support for tables. The queries should be fine. You would only need to change them if you wanted some special highlighting for tables.
=> Update treesitter markdown

helix-term/src/commands/typed.rs, helix-view/src/editor.rs
This PR adds a preview to `:goto`:
https://user-images.githubusercontent.com/19535809/177451164-5dff41b5-5af1-4388-a6f4-8c9b5e9e7e1e.mov
Added behaviours:
- `:g <line-number>` previews the line that is asked for
- backspacing to just `:g ` takes them back to their original line
- aborting brings them back to their original line
---
Definitely looking for some refactoring suggestions here. This bit is repeated quite a bit:
```rust
goto_line_impl(cx.editor, NonZeroUsize::new(line_number));
let (view, doc) = current!(cx.editor);
view.ensure_cursor_in_view(doc, line_number);
```
I figure we can toss that into a separate function, I just don't know what to name it 👀 
Also, would it be preferred to put the `last_theme` and `last_line_number` into a history struct of some sort just for …
=> Add goto line preview

Cargo.lock, helix-view/Cargo.toml, helix-view/src/theme.rs
This PR provides a solution to resolve #2454
=> Inherit theme

helix-term/src/commands.rs, helix-term/src/ui/mod.rs
Resolves #3153.
[asciinema demonstration](https://asciinema.org/a/x2wbGSRBtnKPDacB48EFbUCPd)
Made `search_impl`, and `regex_prompt's fun` take `&mut Editor` instead of `&mut View, &mut Document` to make this possible.
=> Cycled to end/beginning + no more matches msgs

helix-core/src/movement.rs, helix-core/src/selection.rs, helix-term/src/commands.rs, helix-term/tests/test/movement.rs
https://asciinema.org/a/523187
This is a somewhat significant behavior change for tree-sitter textobject motion. Prior to this change you could select all functions in a file with repeated `]f`. With this change, nested functions are not selected with repeated `]f` but I think the new behavior makes sense.
The new behavior is something like
* `]f` selects the function textobject with a `start_byte()` after the current selection's cursor
* `[f` selects the function textobject with an `end_byte()` before the current selection's cursor
After a bit of adjustment, I think the new behavior 'feels' right.
Enabled with that change, I've added `doc.mode == Mode::Select` behavior for `goto_treesitter_object` which behaves as option 1 of #3263.
~Based on #3264 for simplicity's sake~
Supersedes #2802 …
=> Add extend variants for tree-sitter textobjects

book/src/configuration.md, helix-term/src/ui/statusline.rs, helix-view/src/editor.rs
I made a PR for this feature a while back, however I was told to make another one after the status line config was implemented. It is a small feature however I think a few people would like the option
=> feat(statusline): add option to show total line numbers in file

helix-lsp/src/lib.rs
=> [lsp-restart]: call the force_shutdown method for the old_client

helix-term/src/ui/lsp.rs
When signature help is too large it may cause a panic when it is too large, now I just make the hover do an intersection with surface to make sure it never overflow.
How it looks like when it was fully expanded, cursor at the top.
But if the signature shows up at the bottom of the screen it will cause a panic since it is too huge.
<details><summary>stacktrace</summary>
```
thread 'main' panicked at 'Trying to access position outside the buffer: x=1, y=24, area=Rect { x: 0, y: 0, width: 80, height: 24 }', helix-tui/src/buffer.rs:218:9
stack backtrace:
0: rust_begin_unwind
at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt
at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
2: …
```
=> Fix signature help panic when too large

book/src/keymap.md, helix-term/src/commands.rs, helix-term/src/keymap/default.rs
[![asciicast](https://asciinema.org/a/Y5Jq6mJHg41UUuZeInU4jfJGw.svg)](https://asciinema.org/a/Y5Jq6mJHg41UUuZeInU4jfJGw)
Will be useful to remove those inserted space if I want.
=> Select inserted space after join

helix-lsp/src/client.rs, helix-lsp/src/lib.rs, helix-term/src/commands/typed.rs, helix-view/src/editor.rs
When starting helix outside of a workspace/git repository, the workspace discovery fails, because he only goes upwards from cwd.
This patch makes the workspace discovery start from the directory of the opened document.
=> Find workspace from document path

Cargo.toml
According to [the rustc book](https://doc.rust-lang.org/rustc/codegen-options/index.html#split-debuginfo), this is not supported on Windows. It also prevents Helix from compiling on the latest nightly on Windows.
=> remove `split-debuginfo` setting

book/src/keymap.md, helix-term/src/commands.rs, helix-term/src/keymap/default.rs
The language for the `A` binding is potentially confusing because `A` behaves like `i` done at the end of the line rather than `a`. This change renames the command to match Kakoune's language[^1].
This is a breaking change since the name of the command changes.
See https://github.com/helix-editor/helix/issues/3744#issuecomment-1240726094
[^1]: https://github.com/mawww/kakoune/blob/021da117cf90bf25b65e3344fa8e43ab4262b714/src/normal.cc#L2229
=> Rename I/A "Insert at start/end of line"

book/src/configuration.md, helix-term/src/ui/editor.rs, helix-view/src/editor.rs
coming from my previous setup, the first indent guide are a bit distracting. Therefore the option to disable this
current:
enabled:
my neovim config for comparison (using indent-blankline with `show_first_indent_level = false`
=> Add option to skip the first indent guide

helix-term/src/commands/typed.rs, helix-view/src/document.rs, helix-view/src/editor.rs
Resolves #3857
When quitting with modified documents, automatically switch focus to one of them.
=> Change focus to modified docs on quit

book/src/configuration.md, helix-term/src/application.rs
Small PR to add handling for the USR1 signal on unix machines, whereby the config is reloaded from disk. This is useful in settings where automation rewrites the config (or parts thereof, such as the theme config) and we want it reflected immediately instead of manually executing `config-reload` each time.
=> respond to SIGUSR1 by reloading config

helix-term/src/commands.rs, helix-term/src/ui/editor.rs, helix-view/src/editor.rs
This change automatically tracks pending text for for commands which use on-next-key callbacks. For example, `t` will await the next key event and "t" will be shown in the bottom right-hand corner to show that we're in a pending state.
Previously, the text for these on-next-key commands needed to be hard-coded into the command definition which had some drawbacks:
* It was easy to forget to write and clear the pending text.
* If a command was remapped in a custom config, the pending text would still show the old key.
With this change, pending text is automatically tracked based on the key events that lead to the command being executed. This works even when the command is remapped in config and when the on-next-key callback is nested under some key sequence (for example `mi`).
Closes …
=> Automatically track pseudo-pending text

helix-term/src/application.rs
If the close method fails, the editor will quit before restoring the terminal. This causes the shell to break if, e.g. the LS times out shutting down.
This fixes this by always restoring the terminal after closing, and printing out a message to stderr if there is an error.
=> Exit gracefully when close operation fails

book/src/keymap.md
Following #3915, I think reducing friction for people wanting to try out the "no arrow keys in Insert Mode" is nice
=> doc: add example to disable arrow keys in insert mode

book/src/themes.md
With the introduction of #3067 this adds some simple documentation, with an example, on using the `inherits` property to the theme page.
=> doc: add theme inheritance example

helix-term/src/commands.rs
Fixes 2 bugs I just found in a previous PR of mine: #3176
Before it would display message in the statusbar about wrapping around while you where typing the regex.
It would also display a message about wrapping around when there are no matches at all and you hit n/N
=> Fix bugs in search wraparound message

runtime/tutor
This PR fixes as minor typo in `runtime/tutor`.
=> Fix tutor typo

book/src/configuration.md, book/src/themes.md, helix-term/src/ui/editor.rs, helix-view/src/editor.rs, helix-view/src/theme.rs
Closes #4015.
Currently uses the same theme keys as cursorline, but they could be separated if that would be preferred.
=> Add cursorcolumn

languages.toml, runtime/queries/c-sharp/highlights.scm
Added some missing operators and highlights, and organised the keywords into the right colours.
Before:
After:
=> Improve C# syntax highlighting

helix-view/src/lib.rs
A pretty minor issue but it was personally bugging me.
**Reproduction:**
1. Open helix. Resize your terminal height until you have an even number of lines displayed in the editor.
2. Navigate to the middle of a long file and perform a view center (`zc`). The currently selected line is moved to right below the midpoint.
3. Perform a goto center (`gc`). The cursor moves one line up.
**Expected:**
I would expect the second command to not result in any cursor movement. This issue does not occur with an odd number of editor lines. Goto/view with top/bottom also do not have such discrepancies.
**Root cause:**
- `goto_window` is operating relative to the top of the first line until the top of the last line while `align_view` is operating from the top of the first line until the bottom of the …
=> Fix goto/view center mismatch

README.md, book/src/install.md
This should address: https://github.com/helix-editor/helix/issues/4159
=> Add instructions for gnome desktop support using the `.desktop` file

book/src/configuration.md
This PR updates the default indent-guide character from a vertically aligned pipe (`|`) to a left aligned pipe (`▏`).
This makes a big difference visually as the indent guides are now aligned precisely to the indent level instead of starting half a character later.
* Before
* After
=> Add some vertical characters to the editor.indent-guides documentation

helix-term/src/commands.rs, helix-term/src/commands/lsp.rs, helix-term/src/commands/typed.rs, helix-term/src/ui/completion.rs, helix-term/src/ui/editor.rs, helix-view/src/document.rs, helix-view/src/lib.rs, helix-view/src/view.rs
From #3592:
> Previously, the jumplist was not updated by changes to the document. This meant that the jumplist entries were prone to being incorrect after some edits and that usages of the jumplist were prone to panics if, for example, some edits truncated the document.
> This change applies `Transaction`s (document edits) to the selections stored in any jumplists.
This is an alternative to https://github.com/helix-editor/helix/pull/3592
Sharing the selections between Editor and Document (as in #3592) is convenient because there are many call-sites for applying transactions to a document. It's a bit awkward to use shared memory between the View and Document though. This is an alternative that applies transactions to both Documents and Views separately and directly. We introduce a helper …
=> Apply transactions to jumplist selections

book/src/keymap.md, helix-term/src/ui/fuzzy_match.rs, helix-term/src/ui/fuzzy_match/test.rs, helix-term/src/ui/mod.rs, helix-term/src/ui/picker.rs
Closes #2290 and #2564
This PR makes helix treat spaces as seperators instead of a normal character during matching.
This means that "foo bar" also matches "bar/foo" for example.
To match spaces as characeters they must now be escaped.
For example "foo\ bar" matches "foo bar" but not "bar foo" or "foobar".
This behaviour is inline with other IDEs (VScode and Intellij) and fuzzy finders (fzf and skim).
Therefore most people will expect helix to behave the same (I personally still trip up over this
even after using helix quite a while)
While a similar effect can be achieved by pressing C-space, this is quite inconvenient.
Especially in cases where you do not exactly know what you are looking for and often have to adjust the search.
Furthermore this approach also doesn't handle scenarios …
=> Adjust fuzzy matching to be more inline with other editors

helix-term/src/ui/editor.rs
Here we separate the diagnostics by severity and then overlay the Vec of spans for each severity on top of the highlights. The error diagnostics end up overlaid on the warning diagnostics, which are overlaid on the hints, overlaid on info, overlaid on any other severity (default), then overlaid on the syntax highlights.
Kudos to @pascalkuthe for coming up with this idea 🎉
This fixes two things:
* Error diagnostics are now always visible when overlapped with other diagnostics.
* In order to see this, you need `diagnostic.*` theming that makes the severities look visually different (#4061 / #3015 are good for this, or using `bg` highlighting).
* Ghost text is eliminated.
* Ghost text was caused by duplicate diagnostics at the EOF: overlaps within the merged `Vec<(usize, Range<usize>)>` …
=> Overlay all diagnostics with highest severity on top

Cargo.lock, helix-core/Cargo.toml, helix-core/src/syntax.rs
Files with large amounts of injections are incredibly laggy even on beefy CPUs.
For example `CHANGELOG.md` has about 800 injections, because the markdown grammar handles many items as injections.
Helix calls the TS parser for each layer on each keystroke.
TS incremental parsing relies a lot on not parsing unchanged text.
However for injections we call the parser manually defeating the incremental parser.
This PR fixes that problem by tracking in a `HashMap` which layers are modified.
The idea for this fix comes from the original PR (#3108) by @MDeiml that added the split markdown parser:
> It's related to this TODO:
> 
> https://github.com/helix-editor/helix/blob/681c0a91dc36f9db1d23bd31ac1b66414d2a6099/helix-core/src/syntax.rs#L724
> 
> Just going one step further and also avoid parsing …
=> Improve performance for files with lots of injections

runtime/themes/ayu_light.toml
This PR adds statusline mode colours to the ayu light theme when the `editor.color-modes` option is true. 
I've also renamed the `dark_gray` colour to `light_gray` since it's lighter than the default `gray`, so being called "dark" didn't make much sense. 
Normal:
Insert:
Select:
Modes are in the right split, the left split shows the inactive colours.
=> Add colours "color-modes" to ayu_light theme

runtime/themes/everforest_dark.toml, runtime/themes/everforest_light.toml
This syncs the latest version of the `everforest` theme, which I've kept up to date in my [theme repo](https://github.com/CptPotato/helix-themes).
It mostly adds missing theme keys and includes some smaller adjustments.
*edit: for whatever reason GitHub slightly tints the image on upload, so this is not 100% accurate.*
=> Update everforest theme

book/src/generated/lang-support.md, book/src/guides/indent.md, helix-core/src/indent.rs, helix-core/tests/indent.rs, runtime/queries/python/indents.scm
This introduces 2 new capture types for indent queries. With this, the python indent queries have been improved and re-enabled. It should fix most of the issues from #763. We still don't update the indentation retroactively, so there is still some room for improvements:
```python
if condition:
do_smth()
else:
```
Here the `else` should ideally be outdented automatically, once one has finished typing it. This is tricky for 2 reasons:
- We have to figure out when and for which lines to run indentation queries. For performance reasons, we don't want to do it too often and it also shouldn't "correct" the indentation after the user has manually changed it.
- With python, the tree-sitter grammar doesn't even recognize the `else` statement since it is indented (see the discussion in #763). …
=> Fix python indentation

README.md
The runtime copy should happen before you fetch and build grammars, so it should be described in that order in the README.md
=> Rearrange README.md slightly

helix-term/src/commands.rs, helix-term/tests/test/movement.rs
Fixes #4074. Cursor position was set to the wrong location when the anchor of a selection was at the end of a file. There was already a fix for the head of a selection being at the end, it just has to apply when the anchor is at the end as well.
=> Fix append cursor location when selection anchor is at end of document

helix-term/src/commands.rs, helix-term/src/commands/typed.rs, helix-view/src/document.rs
Undo/redo/earlier/later call `Document::apply_impl` which applies transactions to the document. These transactions also need to be applied to the view as in 0aedef0.
Fixes https://github.com/helix-editor/helix/issues/4226
=> Apply transactions to the jumplist for undo/redo

languages.toml, runtime/queries/c/highlights.scm, runtime/queries/cpp/highlights.scm, runtime/queries/wgsl/highlights.scm
Fixes #3788, and adds various missing operators & highlights and organises keywords better for C, C++, and WGSL. Also contains a couple of fixes to WGSL highlighting to prevent text from being highlighted as an error as it's being typed, and remove edge cases where `@variable` text modifiers could leak to other theme keys.
(theme is onedark but modified to make all variables red as shown in the issue)
=> Fix C++ syntax highlighting, and improve C & WGSL highlighting

book/src/generated/lang-support.md, languages.toml, runtime/queries/purescript/highlights.scm, runtime/queries/purescript/injections.scm, runtime/queries/purescript/locals.scm
Basic highlighting based on Haskell (no treesitter grammar for Purescript yet) and LSP support
=> Add support for Purescript language

helix-term/src/commands.rs
Per #2615, the message for yanking to the secondary clipboard when selecting text is clarified.
=> Changed Selection Yank Message

runtime/queries/c/highlights.scm, runtime/queries/cpp/highlights.scm
C gave us the infamous declaration-follows-use syntax for pointers, which can make it hard to tell at a glance whether a `*` is dereferencing a pointer or declaring one.
C++ copied the syntax for references, despite the logic not applying.
This patch highlights */& as (builtin) types when they're used to declare pointers/refs, and continues to treat them as operators in other contexts.
This is more formally correct, but also practically useful (at least for me), particularly with pointer-binds-right code styles. The potential downside is reduced contrast within type declarations.
Before: 
After:
=> c/c++ highlights: *& are @type or @operator based on context

runtime/queries/c/highlights.scm, runtime/queries/cpp/highlights.scm
- treat `restrict`/`_Atomic` like `const`/`volatile` => @keyword.storage.modifier
- highlight `unsigned int` as builtin => @type.builtin
- recognize `static_cast` and friends => @keyword
- `template` is a kind of entity like `typename` => @keyword.storage.type
- many declaration modifiers have nothing to do with storage/types (explicit, friend, access specifiers, inline in C++) => @keyword
- fix floats highlighted as integer => @constant.numeric
Before: 
After:
(OK, the difference in number highlighting is just for this patch :-))
=> c/c++ highlighting: various tweaks

runtime/queries/zig/indents.scm
Some indent queries for Zig were missing (which are obv. typically indented).
I also sorted the queries alphabetically.
=> Fixup Zig Indent Queries

runtime/queries/c-sharp/highlights.scm
- Angle brackets are now highlighted as `@punctuation.bracket` when not used as operators
- `break`, `continue`, and `goto` are moved to `@keyword.control`
- `catch`, `finally`, `throw`, and `try` are moved to `@keyword.control.exception`
- The rest of the keywords are arranged in alphabetical order so they're easier to read
Before:
After:
=> C# syntax highlight tweaks

runtime/themes/bogster.toml
This PR cleans up the bogster theme with names for specific colors and makes the palette match the original colors closer.
=> themes: Update bogster theme

runtime/themes/bogster_light.toml
This PR adds a matching light theme for `bogster` called `bogster_light`.
=> themes: Add `bogster_light` theme

helix-dap/src/types.rs, helix-view/src/handlers/dap.rs, languages.toml
Add C# debugger support in the `languages.toml` file. This includes "launch" and "attach" configurations that employ [netcoredbg][netdbg].
In order to make it work with the aforementioned debugger, the `Initialized` DAP event response is changed to include an optional `DebuggerCapabilities` response, as per the specification.
[netdbg]: https://github.com/Samsung/netcoredbg
Closes: #4212
Signed-off-by: Filip Dutescu <filip.dutescu@gmail.com>
=> feat(csharp,debug): add C# debugger support

book/src/keymap.md
Currently, the [minor mode sections of the book](https://docs.helix-editor.com/keymap.html#view-mode) don't actually contain the key needed to reach them.  Finding this requires an unpleasant amount of forward/backward searching.  So this PR adds a line to each of the sections with the corresponding key.
P.S.  Excellent editor, by the way :smiley:
=> Show keys required to enter each minor mode

helix-term/src/ui/editor.rs
The debug assertion that document diagnostics are sorted incorrectly panics for cases like `[161..164, 162..162]`. The merging behavior in the following lines that relies on the assertion only needs the input ranges to be sorted by `range.start`, so this change simplifies the assertion to only catch violations of that assumption.
See https://github.com/helix-editor/helix/pull/4113#issuecomment-1279997870
=> Fix debug assertion for diagnostic sort order

helix-core/src/syntax.rs
Info logs don't show up in the log file by default, but this line should: failures to load tree-sitter parser objects are useful errors. A parser might fail to load it is misconfigured (https://github.com/helix-editor/helix/pull/4303#discussion_r996448543) or if the file does not exist.
=> Log failures to load tree-sitter parsers as error

runtime/themes/pop-dark.toml
**Reproduction**
1. Type in `:theme pop-dark`
2. No theme preview appears, pressing enter results in `Theme does not exist` error
**Cause**
- toml deserialization error due to duplicate keys
Out of scope for this PR but I think there's room for improvement for how this is handled. I feel like built in themes failing to deserialize should result in build/CI errors.
Also the error message is not the greatest specifically in the `:theme pop-dark` command scenario. If setting it in your config and then doing a `:config-reload`, the error message will instead be ``failed to load theme `pop-dark` - Failed to deserialize theme`` which is much better. After having saved the config value and upon re-opening helix, that same improved error message will logged as a warning.
=> Fix selecting pop dark theme

languages.toml, runtime/queries/cairo/highlights.scm
In [Cairo 0.10.0](https://github.com/starkware-libs/cairo-lang/releases/tag/v0.10.0) the comment token has been changed from the Pythonic style `#` to the more C-like `//`:
> Change comment to use `//` instead of `#`
The PR fixes the comment token used in Helix for Cairo.
There are also many other changes, including the introduction of curly brackets, but those need changes in the tree-sitter grammar, so it's probably better to deal with those in a future PR.
=> Update tree-sitter-cairo with support for 0.10

helix-term/src/ui/editor.rs, helix-view/src/editor.rs
Before things would be cast to u16 earlier than needed, which would cause problems for insanely long lines (longer than 2^16 ~ 65 thousand)
In order to reproduce:
- Open file with _really long_ lines, for example <http://tom7.org/abc/paper.txt>
- `65500l` (go 65500 to the left)
- hold `l` for a bit
Before it would disappear when you reached 2^16 (65536), now it doesn't.
**Note:** currently moving around when the cursor is very far left is very slow, especially in debug mode, this is an unrelated issue.
=> Fix rendering of lines longer than 2^16

helix-term/src/commands.rs
Previously the `.git` dir was searched with the global search, I don't think that's intended (as the default file picker does ignore it), so I synced the `WalkBuilder` configs.
=> Use the same `WalkBuilder` configuration for the global search file picker as the default file picker

helix-term/src/commands/typed.rs
Fixes https://github.com/helix-editor/helix/issues/4325
=> display tree sitter scopes in a popup

helix-term/src/commands.rs
Fixes #4327.
This PR skips the range adjustment for excluding the cursor if the cursor is at the very end of the buffer. Doing this fixes the "one extra character left" issue.
This is my first contribution to Helix that actually touches Rust code. Please kindly let me know if I'm doing anything wrong. Thanks!
=> Fix deleting word from end of buffer

book/src/keymap.md
Minor thing I figured I'd fix after coming across it: the anchor "#textobject" wasn't correctly linking to the section in Usage "#textobjects".
=> Fix link to textobjects usage from keymap documentation

Cargo.lock, book/src/themes.md, helix-tui/Cargo.toml, helix-tui/src/backend/crossterm.rs, helix-tui/src/buffer.rs, helix-tui/src/text.rs, helix-view/src/graphics.rs, helix-view/src/gutter.rs, helix-view/src/theme.rs, runtime/themes/dark_plus.toml, runtime/themes/onedark.toml
Supersedes  #3015 (and closes #2809).
I have rebased the original PR on master and addressed the issues raised in the original PR.
The reasons for the disappearing undercurls/underlines was that the orignal PR
treated them as modifiers. However, underlines styles behave more like colors than modifiers:
There are multiple different underline styles that are incompatible, overwrite each other and
are removed with a single escape sequence.
Modifiers on the other hand can be added and removed independent of other modifiers.
Tracking underline styles in the modifier set can not work correctly.
The fix suggested by @archseer of only emitting `NoUnderline` if there is no
underline left in `to` does not work for nested highlights.
Consider the following example of 3 nested highlights (underline …
=> Support different kinds of underline rendering (updated)

helix-core/src/syntax.rs, helix-term/src/commands/typed.rs
Closes #2880
This PR indents and line-breaks the expression displayed for `:tree-sitter-subtree`. For short sexprs it might be a little annoying. Maybe we should generate the sexpr and if it's longer than ~40 chars, manually format it?
I didn't know where to put the formatting function, so I just put it inside the command itself.
Before:
After:
With named fields:
=> Pretty print `tree-sitter-subtree` expression

README.md, book/src/install.md
Add a "Windows" section to `install.md` that points users to scoop and Chocolatey.
I also made a short notice about symlinks on Windows. Though, I'm not sure if this fits in very well.
closes #4253
=> Update windows install instructions

helix-term/src/commands.rs
Resolve tiny TODO for error message for `no last picker`.
=> fix(commands): no last picker error

helix-term/src/commands.rs, helix-view/src/document.rs
Remove indent_unit as the identation is conveniently available in `Document::indent_style`.
=> chore(view): remove indent_unit helper fn

helix-term/tests/test/helpers.rs
Write path fixes (#2267) introduced some flaky behavior in the integration test suite that happens when running within GitHub Actions.
The Windows runner has `clangd` installed, but it sometimes takes too long to shutdown which causes false-positive test failures. All runners have the `R` binary installed but not the language server package. This causes a flake whenever `tempfile::NamedTempFile` creates a file which is mistaken as R (this happens surprisingly often in practice). The R binary starts but immediately crashes because the language server package is not installed. Then the language server cannot be shutdown in the expected timeframe, resulting in a false-positive failure.
Here I've removed all language server configuration for the integration tests by default with the ability …
=> Fix integration test flakes in CI

helix-view/src/editor.rs
In replace_document_in_view re-use align_view function to align the newly viewed doc.
=> feat(view): re-use align_view function

README.md, book/src/install.md
This adds some documentation to clarify that:
1. Having `HELIX_RUNTIME` set prior to building the project will generate tree-sitter grammars in `$HELIX_RUNTIME/grammars`.
2. If keeping the repo locally, an alternative copying/symlinking runtime files is to simply set `HELIX_RUNTIME`.
See issue https://github.com/helix-editor/helix/issues/4336 for discussion.
=> Clarify use of `HELIX_RUNTIME`

helix-term/src/commands/lsp.rs, helix-term/src/ui/completion.rs, helix-term/src/ui/menu.rs
Code actions are currently sorted alphabetically because they simply reuse the `Menu` used for autocompletions.
This is extremely inconvenient in many cases.
For example rust-analyzer emits a ton of (sometimes useful) refactors code-actions that get sorted before
the quick fix (import ...) I am interested in.
This PR improves upon this in two ways:
The simplest fix is simply not sorting code actions in the `Menu`.
However many LSP implementations send their code actions unordered because they assume that the client will sort the code actions by the `kind` field.
VScode uses 8 cateogoris for code actions:
* quickfix
* refactor (extract)
* refactor (inline)
* refactor (rewrite)
* refactor (move)
* refactor (surround)
* source
* anything else
I have opted to match this behavior by sorting …
=> Improve sorting for inline menu (codeaction + completion)

helix-core/src/shellwords.rs
This allows commands such as `:set statusline.center ["file-type"]` to work. Before the quotes within the list would mess it up. Also added a test to ensure correct behavior.
Addresses the parsing part of #2206 (the not updating is solved by #3457)
=> Fix shellwords delimiter handling

book/src/configuration.md, helix-term/src/application.rs, helix-term/src/commands/typed.rs, helix-term/src/ui/editor.rs, helix-view/src/editor.rs
This listens to focus change events from the terminal and writes all files when focus is lost. It's not ready to merge, but I had a couple questions that it'd be good to answer before proceeding.
1. Should this be behind an option? I'd certainly always use it, but I could see others who only want to save when they explicitly request it.
a. If it should, what should the option be? After this, I was thinking about adding behavior to autosave on buffers being hidden. If we add that second autosave behavior, I think an option set like the `gutters` option could make sense. For this, we'd have an option `autosave` with a default value of `["focus-lost"]` and an eventual default of `["focus-lost", "buffer-hidden"]`.
2. Do we need to do something about terminals that don't support this? It's …
=> Autosave all when the terminal loses focus

helix-term/src/commands/typed.rs, helix-term/tests/integration.rs, helix-term/tests/test/auto_indent.rs, helix-term/tests/test/auto_pairs.rs, helix-term/tests/test/commands.rs, helix-term/tests/test/movement.rs, helix-term/tests/test/prompt.rs, helix-term/tests/test/write.rs
When force quitting, we need to block on the pending writes to ensure that write commands succeed before exiting, and also to avoid a crash when all the views are gone before the auto format call returns from the LS.
This fixes an intermittent failure in the integration tests as well.
=> flush writes on force quit

helix-term/src/commands.rs, helix-term/src/commands/typed.rs
When we do auto formatting, the code that takes the LSP's response and applies the changes to the document are just getting the currently focused view and giving that to the function, basically always assuming that the document that we're applying the change to is in focus, and not in a background view.
This is usually fine for a single view, even if it's a buffer in the background, because it's still the same view and the selection will get updated accordingly for when you switch back to it. But it's obviously a problem for when there are multiple views, because if you don't have the target document in focus, it will ask the document to update the wrong view, hence the crash.
The problem with this is picking which view to apply any selection change to. In the absence of any more data …
=> fix: write-all crash

helix-term/src/application.rs, helix-term/src/commands.rs, helix-term/src/commands/lsp.rs
- nit: move an allocation to happen after a `continue`, making sure it's not done for nothing
- nit: Do less allocations in `ui::menu::Item::label` implementations, often dividing by two or more
the number of allocations in a call
=> Optimize `ui::menu::Item::label()` implementations

helix-core/src/syntax.rs, helix-loader/src/grammar.rs, xtask/src/querycheck.rs
As described in #4346 both language and grammar names are sometimes lower-cased. For grammars this is incompatible with ones using uppercase names. And for languages this can be a bit surprising. (At least I stumbled across helix ignoring my queries because of this).
Note that the syntax part is  not strictly necessary to get grammars as described in the issue to work.
Closes #4346
=> Remove lower-case requirement for language/grammar

book/src/generated/lang-support.md, runtime/queries/zig/textobjects.scm
Unfortunately the way how the Zig grammar is declared, i had to do some (probably) not so decent practices when it comes to TSQ.
However, this code is tested and i am pretty certain someone smarter than me might be able to refine this code a little bit.
=> Add textobjects.scm for zig

book/src/languages.md, helix-core/src/syntax.rs, languages.toml
The change in #2455 to search for suffixes in `file-types` is too permissive: files like the tutor or `*.txt` files are now mistakenly interpreted as R or perl, respectively. This also contributed to the CI flakiness (see https://github.com/helix-editor/helix/pull/4391) since tempfiles created by `tempfile::NamedTempFile` had a much higher chance of being mistaken as R or C.
This change changes the syntax for specifying a file-types entry that matches by suffix:
```toml
file-types = [{ suffix = ".git/config" }]
```
And changes the file-type detection to first search for any non-suffix patterns and then search for suffixes only with the file-types entries marked explicitly as suffixes.
=> Change syntax for suffix file-types configurations

helix-term/src/ui/completion.rs, helix-term/src/ui/editor.rs, helix-term/src/ui/menu.rs
Some language servers may not send the `documentation` field if it is expensive to compute. Clients can request the missing field with a completionItem/resolve request.
In this change we use the idle-timeout event to ensure that the current completion item is resolved.
Closes https://github.com/helix-editor/helix/issues/2052
=> lsp: Resolve completion items missing documentation on idle

helix-term/src/ui/picker.rs
This is mostly for the sake of the diagnostics pickers: without rendering the diagnostic styles, it's hard to tell where the entries in the picker are pointing to.
=> Render diagnostics in the file picker preview

helix-term/src/commands.rs
This bug occurs on `shell_insert_output` and `shell_append_output` commands.
The previous implementation would create a child process using the Rust stdlib's `Command` builder. However, when nothing should be piped in from the editor, the default value for `stdin` would be used. According to the Rust stdlib documentation that is `Stdio::inherit` which will make the child process inherit the parent process' stdin. This would cause the terminal to freeze.
This change will set the child process' stdin to `Stdio::null` whenever it doesn't pipe it. In the `if` statement where this change was made there was an extra condition for windows that I am not sure if would require some special treatment.
Fixes #3524.
=> fix: terminal freezing on `shell_insert_output`

book/src/generated/typable-cmd.md, helix-term/src/commands/typed.rs
#4400 
Add a command update that will write the changes if the file has been modified.
=> Add  `:update` that will write the changes if the file has been modified.

book/src/generated/typable-cmd.md, helix-term/src/commands/typed.rs, helix-view/src/theme.rs
Most commands that accept an argument show their current value if no argument is specified. The `:theme` command previously displayed an error message in the status bar if not provided with an argument:
```
Theme name not provided
```
It now shows the current theme name in the status bar if no argument is specified.
Signed-off-by: James O. D. Hunt <jamesodhunt@gmail.com>
=> commands: Make no arg ':theme' show name

helix-tui/src/buffer.rs, helix-tui/tests/terminal.rs, helix-view/src/graphics.rs
Now the editor can fill **very** large terminals.
Changed/removed tests which check the truncating behavior.
Closes #4283
=> Allow the editor area to be bigger than u16 (width and height remain u16)

runtime/queries/markdown.inline/injections.scm
Simple fix for html tags in inline markdown not working sometimes.
=> Include unnamed children for html injected into inline markdown

helix-term/src/ui/completion.rs, helix-term/src/ui/menu.rs
In addition to suggesting completion, some **LSP servers can tell the client which suggestions would be the most probable fit**.
For instance, if you want to assign a value to a variable named `position`, rust-analyzer will preselect a method that is also named `position()` if it is part of the suggested items. The LSP server can mark multiple completion items as preselect, but in this case the order they are send back to the LSP client defines their order. This PR makes these preselected items appear at the top of the completion menu, in the same order as the LSP server intended.
This superseeds #3215 after the merge of #4134. It also partially superseeds #2705.
=> feat(lsp): LSP preselected items appear first in completion menu

helix-term/src/commands.rs, helix-term/tests/test/commands.rs
`goto_file_impl` now trims surrounding `'`, `"`, `(` and `)` before opening the path.
The `current_word` selection was inverted so that now it works from both the first and last characters of the word.
Fixes #4122
=> Trim quotes and braces from paths in goto_file_impl

helix-term/src/commands/lsp.rs
Testing strategy:
- Go on a function parameter with a language server that has doc popups, like rust-analyzer
- Create a macro that enters Insert mode and exits it (`Qi<Esc>Q`)
- Hit `q`
- **Old behaviour**: a doc popup appears and gets stuck
- **New behaviour**: no doc popup appears
Fixes #3112
Fixes #4360
=> fix: Never create automatic doc popups outside of Insert mode

helix-term/src/commands.rs
Based on #3136. Fixes #3127 and might fix #3133.
This changes `shell_impl` to concurrently write to `stdin` while reading from `stdout` and `stderr`. This way processes will not block, if their input buffer is full, which is the current behavior.
I renamed `shell_impl` to `shell_impl_async` and added a new `shell_impl` as a blocking wrapper.
~Since `shell_impl_async` needs to take ownership of the input, I changed the input type to `Rope`. This can be constructed from the `RopeSlice` with `RopeSlice::into` in O(log n). We might want to copy the whole rope and give the current selection as an extra parameter which would be O(1), but a bit more ugly.~
This is not true. It's O(log n) either way. And obviously O(n) to pipe everything into the process. Don't know what I thought.
=> Make shell_impl concurrent

book/src/generated/lang-support.md, languages.toml, runtime/queries/kdl/highlights.scm
Adds the KDL (a cuddly document language) grammar to the languages.
Website: https://kdl.dev/
Repo: https://github.com/kdl-org/kdl
Grammar: https://github.com/Unoqwy/tree-sitter-kdl
=> feat(lang): add kdl grammar

runtime/themes/fleetish.toml
- Small changes to more closely resemble the official fleet theme. 
- Some create freedom to fit my own preferences and to keep it interesting.
- Reworked diagnostics to reduce bleeding from the eyes :)
Themelint compliant.
Will update wiki when approved.
=> Fleetish: Adjustments to resemble official theme and reworked diagnostics to reduce subconjunctival hemorrhage

book/src/generated/lang-support.md, languages.toml, runtime/queries/xml/highlights.scm, runtime/queries/xml/indents.scm, runtime/queries/xml/injections.scm
There have been two issues opened about this (#3479 and #4331) so I think it would be good for us to include something in the default configuration that handles XML.
The solution in this pull request adds a new grammar. This same grammar was added to lapace in https://github.com/lapce/lapce/pull/1554, and it seems to handle things well. The highlight queries were copied from the grammar's repository. Here's a screenshot with the Darcula theme:
There was also [a suggestion](https://github.com/helix-editor/helix/issues/3479#issuecomment-1221323100) on one of the XML-related issues that we could re-use the HTML grammar. If we'd prefer to avoid adding another grammar, let me know and I can update this pull request. The XML grammar is pretty small though (only 97K), so I think the small size …
=> feat(lang): add xml

helix-term/src/commands.rs
This pull request fixes the same issue as #2620, except for `scroll` instead of `move_vertically`.
The issue is kind of complicated to explain in text, so here's a video of the before and after:
I believe the comment on line 1395 about things getting truncated properly should still be accurate, but I wouldn't mind a second opinion on that.
Also, do we have tests for scrolling anywhere? Is there somewhere that I could add a unit test for this behaviour?
=> fix: make `scroll` aware of tabs and wide characters

languages.toml, runtime/queries/latex/highlights.scm, runtime/queries/latex/injections.scm
Update the LaTex grammar. I also noticed that the comment injection has been broken for a while and math delimiters were not highlighted, so I fixed that too.
=> Update LaTex grammar

languages.toml, runtime/queries/sshclientconfig/highlights.scm
This updates the highlight queries for SSH client configs to be more closely aligned with what helix themes expect and it fetches the latest upstream source which fixes some grammar related issues as well.
Before:
After:
=> Update SSH client config grammar & highlight queries

runtime/queries/wat/highlights.scm
added "if", "then", "else", "block", "loop", "end" and "mut" to the wat keyword highlights.
=> Added missing keywords to wat (wasm) hightlights

flake.lock, flake.nix
- update nci input
- fixup flake to match new nci interface
- filter helix source to reduce unnecessary recompiles
=> build(nix): update nci, fixup flake

helix-core/src/shellwords.rs, helix-term/src/commands/typed.rs, helix-term/src/ui/prompt.rs
This fixes two issues with spaces handling in file names for auto completion:
1. the code so far did not use `shellworlds::shellwords` for handling completion. This is now corrected so that the logic for completion matches that of parsing
2. when auto completing it did not correctly apply escaping which is now happening.
Fixes #4266 on unix.
This however does not really fix the issue on Windows. This is because `shellwords` behaves differently on windows. I'm not sure how to properly fix this, but basically it requires double quoting there and from what I can tell it does not support escapes there. It might be that it results in a better user experience if the behavior actually changes there? I'm not sure. At the very least the code requires double quotes there and the completion code …
=> Correctly handle escaping in completion

helix-term/src/commands.rs
When backward-deleting a character, if this character and the following character form a Pair, we want to delete both. However, there is a bug that deletes both characters also if both characters are closers of some Pair.
This PR fixes that by adding an additional check that the deleted character should be an opener in a Pair.
Closes https://github.com/helix-editor/helix/issues/4544.
Are any more tests needed?
=> Fix `delete_char_backward` for paired characters

helix-term/src/commands.rs
Currently Helix doesn't exit select mode when replace commands are used, which is inconsistent with yank commands.
Confirmed in Matrix with @archseer that this is a bug, though I wasn't very clear about _which_ replace command I was talking about (there are 4). But I think it makes sense to exit select mode on them all. Please let me know if that's not the case. Thanks!
This PR makes the editor exit select mode on the follow commands:
- `replace`
- `replace_with_yanked`
- `replace_selections_with_clipboard`
- `replace_selections_with_primary_clipboard`
=> Exit select mode on replace commands

runtime/queries/python/highlights.scm, runtime/queries/python/indents.scm
- Add syntax highlighting for Python pattern matching
- Add indentation for Python pattern matching
Closes https://github.com/helix-editor/helix/issues/4526
=> Add syntax highlighting and indentation for Python pattern matching expressions

helix-view/src/base64.rs, helix-view/src/clipboard.rs, helix-view/src/editor.rs, helix-view/src/env.rs, helix-view/src/lib.rs
This emits an [OSC 52 terminal code](https://terminalguide.namepad.de/seq/osc-52/) for copying into the system terminal if we don't find a local provider. That gets setting the local clipboard to work through SSH.
It doesn't do the get clipboard side of OSC 52 for a few reasons:
* OSC 52 get isn't often enabled as it's a security hole that lets remote terminals read your local clipboard
* It'd require getting the clipboard to be async since we'd need to wait for the terminal response
* Getting the clipboard is way less useful since you can go into insert and use your OS-level paste command to simulate it
vim-oscyank has [this nice list of supported terminals](https://github.com/ojroques/vim-oscyank#vim-oscyank). I've tried it on Kitty on Mac and it seems to work well. I believe the …
=> Use OSC 52 as a fallback for setting the system clipboard

helix-term/src/ui/editor.rs, helix-view/src/editor.rs
This change has two fixes for a scenario that can come up if you use multiple windows to edit/view the same document.
The first fixes the panic in #3978 by clamping the syntax highlighting range to always be within the length of the document. The second fixes a minor UX issue where if you delete enough of a document, one window may be looking past the end of the document - in this case we ensure that the cursor is within view upon switching windows.
Closes #3978
=> Fix panic from two windows editing the same document

languages.toml
The Julia language server often needs more than the default 20 seconds to respond to the initial request, especially on slower computers. This increases the default timeout, one less potential issue to troubleshoot.
Can be removed once the Julia precompiling story improves.
=> Increase default language server timeout for Julia

languages.toml
This PR makes the editor use language=bash when the shebang line uses zsh. We already use language=bash for zsh related files (~/.zshrc, ~/.zshenv etc.), so it's expected for the same to be true for shebang lines as well.
=> Use language=bash when shebang line uses zsh

languages.toml
This PR bumps the version of `LhKipp/tree-sitter-nu` up for `nushell` syntax highlighting support.
this has been tested locally, as stated in #4577, by applying
```diff
diff --git a/.config/helix/languages.toml b/.config/helix/languages.toml
index 94313dc..f4b0775 100644
--- a/.config/helix/languages.toml
+++ b/.config/helix/languages.toml
@@ -7,3 +7,7 @@ roots = []
comment-token = "(*"
indent = { tab-width = 4, unit = "  " }
grammar = "pascal"
+
+[[grammar]]
+name = "nu"
+source = { git = "https://github.com/LhKipp/tree-sitter-nu", rev = "eb95bdac3abd73ef47e53f19c63e74a31405ebd2" }
\ No newline at end of file
```
and then running
```bash
> hx --grammar fetch
Fetching 114 grammars
113 up to date git grammars
1 updated grammars
nu now on eb95bdac3abd73ef47e53f19c63e74a31405ebd2
> hx …
```
=> bump up LhKipp/tree-sitter-nu's version to latest

helix-term/src/commands.rs
This follows changes in Kakoune to the same effects:
* `p`/`<space>p`: https://github.com/mawww/kakoune/commit/266d1c37d0d970a7eff747f5e6a5773a3cea39d8
* `!`/`<A-!>`: https://github.com/mawww/kakoune/commit/85b78dda2e29d70b620836b04224b104426bdbae
Selecting the new data inserted by shell or pasting is often more useful than retaining a selection of the pre-paste/insert content.
Closes https://github.com/helix-editor/helix/issues/3401
=> Select text inserted by shell or paste

helix-term/src/commands.rs
The sequence `"_y"_p` panics because the blackhole register contains an empty values vec. This causes a panic when pasting since it unwraps a `slice::last`.
=> Fix panic on paste from blackhole register

helix-term/src/commands.rs, helix-term/tests/test/commands.rs
#4458 introduced a regression with multi-selection paste where pasting would not adjust the ranges correctly. To fix it, we need to track the total number of characters inserted in each changed selection and use that offset to slide each new range forwards.
=> Fix range offsets in multi-selection paste

helix-core/src/shellwords.rs, helix-term/src/commands/typed.rs, helix-term/src/ui/prompt.rs
A few fixes/improvements here for shellwords-based completion in command_mode (`:`):
* Fix completion when the last item in the prompt is a space
* Fix a panic for the sequence `:<space>`
* Escape values in the completion list
* Fix an edge-case in completion when the input is escaped
Closes https://github.com/helix-editor/helix/issues/4586
Closes https://github.com/helix-editor/helix/issues/4563
=> Fix whitespace handling in command-mode completion

.github/workflows/build.yml, helix-core/src/test.rs, xtask/src/querycheck.rs
Currently CI runs clippy as `cargo clippy --all-targets` without the `--all` flag, causing some code to be ignored. This PR enforces the `--all` flag and resolves some warnings from the addition of the flag.
=> Run clippy on workspace in CI

runtime/themes/gruvbox.toml
Details from https://github.com/helix-editor/helix/issues/4625
Top part of the screenshot above is the OOTB Gruvbox theme. As you can see, it's quite offensive to the eyes and makes it hard to see exactly where the selected region begins and ends at a glance. The bottom part of the screenshot is the theme after a couple tweaks to the palette.
Not sure if anyone actually prefers the way it is now, but it seems untenable to me.
Here's the modified settings from the screenshot:
```toml
"ui.selection" = { bg = "bg2" }
"ui.cursor.primary" = { bg = "fg4", fg = "bg1" }
"ui.cursor.match" = { bg = "bg3" }
```
=> Fixed disorienting selection palette on Gruvbox theme

runtime/tutor
In recap for chapter 5.1 specify that the cursor is duplicted to the next suitable line instead of the next line.
Fixes #4598
=> tutor: fix wording in recap for chapter 5

runtime/queries/ruby/textobjects.scm
This PR Refactor current TextObjects and improves it adding:
- Adds Singleton Methods
- Adds Module
- Adds `@parameter.around`
=> Improve Ruby TextObjects

contrib/completion/hx.bash
Use a builtin bash option which detects filenames in completion outputs and reflects this in sensible <tab> completion behaviour.
Fixes https://github.com/helix-editor/helix/issues/3606.
Solution taken from https://stackoverflow.com/a/57385447/470509
=> bash completion: use builtin filenames option

runtime/queries/rust/highlights.scm
Without this scoped attribute macros are not matched as macros. Eg
```
#[path::macro]
```
=> [rust highlights] fix scoped attribute macro matching

helix-core/src/indent.rs
`deepest_preceding` is known to be a descendant of `node`. Repeated calls of `Node::parent` _should_ eventually turn `deepest_preceding` into `node`, but when the node is errored (the tree contains a syntax error), `Node::parent` returns None.
<details><summary>In the typescript case...</summary>
```typescript
if(true) &&true
//      ^ press enter here
```
The tree is:
```
(program [0, 0] - [1, 0]
(if_statement [0, 0] - [0, 15]
condition: (parenthesized_expression [0, 2] - [0, 8]
(true [0, 3] - [0, 7]))
consequence: (expression_statement [0, 8] - [0, 15]
(binary_expression [0, 8] - [0, 15]
left: (identifier [0, 8] - [0, 8])
right: (true [0, 11] - [0, 15])))))
```
`node` is the `program` node and `deepest_preceding` is the
`binary_expression`. The tree is errored on the `binary_expression` …
=> Fix panic from indenting on tree with errors

book/src/generated/typable-cmd.md, helix-lsp/src/client.rs, helix-term/src/commands.rs, helix-term/src/commands/lsp.rs, helix-term/src/commands/typed.rs, helix-term/src/ui/mod.rs
LSPs can communicate that they can run additional commands via the `executeCommandProvider`. This adds a picker for these commands. To use it you need to map it to e.g. `<space>W`.
=> Add LSP workspace command picker

languages.toml
Files ending in `.sc` are known as "Scala Scripts". The scalac compiler
knows how to handle these, popular tools like
[Ammonite](https://github.com/com-lihaoyi/Ammonite) and
[scala-cli](https://github.com/Virtuslab/scala-cli) use them, and even
some Scala build tools like [mill](https://github.com/com-lihaoyi/mill)
use them as their build files (`build.sc`). This change just makes sure
that they are treated as Scala files so Metals kicks in.
=> feat: add sc to filetypes for Scala

book/src/generated/lang-support.md, languages.toml
Elixir-LS is also supported for `.heex`-files.
Not sure if we should also add `config = { elixirLS.dialyzerEnabled = false }` like we have in the `elixir` configuration.
=> Enable elixir-ls for heex language

helix-core/src/syntax.rs
Helix sometimes freezes when performing treesitter motions on medium to large files.
The problem only occurs in very particular cases and depends highly on the grammar, specific capture and file content.
I was able to reproduce the problem consistently by using any treesitter motion in the `iter.rs` file of ropey.
But @dead10ck also noted that the same problem sometimes occurs for him in the matrix chat.
Looking at the flamegraph almost all time is spent in treesitter itself:
After a bit of digging I found the problem:
Since treesitter version `19.5` treesitter does not set any limit for the amount of in-progress captures any more (used to be 32).
Because advancing the `QueryCursor` requires comparing every new capture to all in-progress captures, this can become `O(N^2)` in pathalogical …
=> improve performance of tree sitter query captures (for text object motions in particular)

languages.toml
This adds in a couple more roots that are common in Scala.
- `build.sc` which is used in Mill
- `build.gradle` for Scala Gradle projects
- `.scala-build` for scala-cli projects
=> update scala roots

helix-term/src/commands.rs, helix-term/src/keymap/default.rs
Increment increases the increment amount by 1 (or negative 1) for each value based on issue #3910.
This completely changes the way increment works, so maybe this is better as another command. I don't know what that would be though.
=> feat(commands) increment by range

.github/workflows/languages.toml, helix-core/tests/data/indent/languages.toml, languages.toml, runtime/queries/rust/highlights.scm, runtime/queries/rust/indents.scm, runtime/queries/rust/textobjects.scm
- deps: Update tree-sitter-rust (supports let-else && let-chains)
- fix: Outdated Rust queries after TS update
Refs:
- https://github.com/tree-sitter/tree-sitter-rust/commit/6ebdb1dc6cf4c19d8bae1d04f7bad44408e877d8
- https://github.com/tree-sitter/tree-sitter-rust/commit/63eba73c6e5923a6946c3e3a23582b5ecd496d79
=> update tree sitter rust

helix-term/src/commands.rs
Adds `extend_prev_word_end` to user callable commands.
=> add `extend_prev_word_end` command

book/src/configuration.md, helix-term/src/ui/statusline.rs, helix-view/src/editor.rs
=> Statusline indicator to show number of selected chars

helix-term/src/commands.rs, helix-term/tests/test/commands.rs
#4458 introduced a regression for shell commands like `|`, `!`, and `<A-!>` which caused the new selections to be incorrect. This caused a panic when piping (`|`) would cause the new range to extend past the document end.
The paste version of this bug was fixed in #4608. This fix is slightly more complicated because of the different types of shell insertions/replacements.
This change also inherits the direction of the new range from the old range and adds integration tests to ensure that the behavior isn't broken in the future.
=> Fix range offsets for multiple shell insertions

book/src/configuration.md, helix-term/src/ui/statusline.rs, helix-view/src/document.rs, helix-view/src/editor.rs
#4540
For <SPACE>+d
For <SPACE>+D
=> Add global error/warning count statusline element

runtime/queries/zig/indents.scm
This additional statement caused constructs such as 
`} else if (...) {` to have 1 too many indents.
The drawbacks of removing `Statement` from the Indent queries is so far only to my knowledge, that the first line of multi-line string assignments aren't properly indented.
I am the one to blame for this as well.
Introduced with #4281
=> Remove Statement in Zig indentation query

languages.toml
I broke the build 😅
Tree-sitter-bicep doesn't have the `src` directory checked in on the main repo. I made a fork, removed the gitignore line and checked in the sources
=> Use tree-sitter-bicep fork with sources checked in

helix-term/src/commands/lsp.rs, helix-term/src/ui/completion.rs, helix-term/src/ui/menu.rs, helix-term/src/ui/popup.rs
Closes #1248 by implementing a scrollbar as the required hint. As mentioned by @the-mikedavis in #4364. This is a simple copy of the scrollbar functionality from `Menu`. The scrollbar is enabled by default and `Popup::with_scrollbar()` can be used to toggle it on/off.
=>  Popup scrollbar

helix-term/src/commands.rs
This adds a command to rewrite the search register to add word boundaries to the regex that's there. This is an alternative to #4222.
```toml
[keys.normal]
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection", "make_search_word_bounded", "search_next"]
```
This seems more complex but has the added benefit that it can be used independently. So for instance if one is already down the search of something and discovers that it's not specific enough, a hotkey can be hit to automatically add word boundaries and resubmit the search:
```toml
[keys.normal]
A-s = ["make_search_word_bounded", "search_next"]
```
=> Add command to add word boundaries to search

helix-term/src/ui/picker.rs
Fixes #4688
Currently, the fuzzy matching in the picker is only sorted by the fuzzy match score.
An unstable sort is used so the order of elements with equal score is random (still deterministic but may vary between `rustc`/`std` versions).
`fzf` and `skim` offer the `--tiebreak` flag to specify a criterion to use in that case.
Available options are:
* (byte) length
* (byte) position of the first matched char
* (byte) position of the last matched char (causes matching to be performed in reverse)
* original index in the list supplied to the fuzzy matcher
Both `fzf` and `skim` allow an arbitrary list of these tiebreakers to be specified.
`fzf` uses the `length` tiebreaker by default (skim does not).
I think this is a good default because the user can always filter for longer matches by …
=> sort fuzzy matches with equal score by length in picker

helix-term/src/commands.rs
The text within the command palette used a custom format to display the keybinding for a command. This change switches to the key sequence format that we use for pending keys and macros.
This was originally done in https://github.com/helix-editor/helix/pull/2790 but I think it was accidentally reverted in https://github.com/helix-editor/helix/pull/2814 because of a merge conflict.
=> Use key-sequence format for command palette keybinds

helix-view/src/editor.rs, helix-view/src/tree.rs
There is some common code between `Editor::focus_next` and `Editor::focus` that can be eliminated by refactoring `Tree::focus_next` into a function that only returns the next `ViewId`.
=> Factor out common code for focusing the next view

helix-core/src/shellwords.rs, helix-term/src/commands/typed.rs
This fixes an edge case for completing shellwords. With a file "a b.txt" in the current directory, the sequence `:open a\<tab>` will result in the prompt containing `:open aa\ b.txt`. This is because the length of the input which is trimmed when replacing with completion is calculated on the part of the input which is parsed by shellwords and then escaped (in a separate operation), which is lossy. In this case it loses the trailing backslash.
The fix provided here refactors shellwords to track both the _words_ (shellwords with quotes and escapes resolved) and the _parts_ (chunks of the input which turned into each word, with separating whitespace removed). When calculating how much of the input to delete when replacing with the completion item, we now use the length of the last part.
This …
=> Capture word parts while calculating shellwords

helix-core/src/syntax.rs
The current `:tree-sitter-subtree` has a bug for field-names when the field name belongs to an unnamed child node. Take this ruby example:
```ruby
def self.method_name
true
end
```
The subtree given by tree-sitter-cli is:
(singleton_method [2, 0] - [4, 3]
object: (self [2, 4] - [2, 8])
name: (identifier [2, 9] - [2, 20])
body: (body_statement [3, 2] - [3, 6]
(true [3, 2] - [3, 6])))
But the `:tree-sitter-subtree` output was
```scm
(singleton_method
object: (self)
body: (identifier)
(body_statement (true)))
```
The `singleton_method` rule defines the `name` and `body` fields in an unnamed helper rule `_method_rest` and the old implementation of `pretty_print_tree_impl` would pass the `field_name` down from the named `singleton_method` node.
To fix it we switch to the [TreeCursor] API which …
=> Use TreeCursor to pretty-print :tree-sitter-subtree

helix-tui/src/buffer.rs
Hello. First time contributor here.
SUMMARY:
With these changes, when `truncate_start` is `true` in a call to `Buffer::set_string_truncated`, the `x_offset` is now properly updated according to the (potentially truncated) content width.
Previously, the `x_offset` was never updated in this branch of code, which caused a layout error when rendering a Picker with items whose calculated labels contained multiple Spans. Since `x_offset` was not updated between calls to `set_string_truncated`, each span's content would render starting from the leftmost edge of the item's line, causing the content items to overlap each other. For example, in a menu item with two spans with content `some_directory/` and `14.5 KB`, it would render as `14.5 KBrectory/`.
Also, I took the liberty of renaming a …
=> update `x_offset` calculation in `Buffer::set_string_truncated`

helix-term/src/commands.rs
When doing a `surround add` operation, the original selection is kept in place, which makes it difficult to chain surrounds and does not feel idiomatic. 
It might feel more natural when chaining surround operations. For example, quoting something, then wrapping parenthesis, then prepending `Box::new` might look like a selection of `someStringContent` then `ms"ms(iBox::new`
This PR/MR changes the behavior of the editor. 
`ms"` before:
`ms"` after this commit:
=> Select surrounding characters when using match/surround (m) mode

helix-view/src/tree.rs
Issue: https://github.com/helix-editor/helix/issues/4539
~~this solution adds a new field to the `Tree::Node` struct: `spawned_by`. when a new view is created, the new view's `spawned_by` field is populated with the `ViewId` of the view that was in focus at the time of creation. when a view is closed, i.e. `:q`, focus will move to the `spawned_by` view, provided it still exists. if it no longer exists, `Tree::focus_next()` is called, which moves focus to an arbitrary view that exists (as best i can tell).~~
2nd attempt:
~~i've implemented `focus_prev`. when a view closes, and it is the view in focus, `focus_prev` is called. it attempts to shift focus to the "`(current_view - 1)`" view (if it exists. if it does not, the legacy method `focus_next` is called).~~
3rd attempt:
see …
=> When buffer closes, focus on parent buffer

runtime/themes/mellow.toml
A brand new color scheme for helix (and other editors).
=> Theme: Mellow

languages.toml
Haskell source files are now either `.hs` (as before) or `.hs-boot`, which is a type of Haskell file that only contains type declarations (https://downloads.haskell.org/ghc/latest/docs/users_guide/separate_compilation.html#how-to-compile-mutually-recursive-modules)
=> Match `.hs-boot` files to Haskell

helix-lsp/src/client.rs, helix-term/src/ui/completion.rs, helix-term/src/ui/menu.rs
#4406 resolves completion items on the idle-timeout event. The `Completion::resolve_completion_item` function blocks on the LSP request though, which blocks the compositor and in turn blocks the event loop. So until the language server returns the resolved completion item, Helix is unable to respond to keypresses or other LSP messages.
This is typically ok since the resolution request is fast but for some language servers this can be problematic, and ideally we shouldn't be blocking like this anyways.
When receiving a `completionItem/resolve` request, the Volar server sends a `workspace/configuration` request to Helix and blocks itself on the response, leading to a deadlock. Eventually the resolve request times out within Helix but Helix is locked up and unresponsive in that window.
This …
=> lsp: Resolve completion item asynchronously on idle-timeout

helix-lsp/src/lib.rs, helix-lsp/src/transport.rs, helix-term/src/application.rs
This change handles a language server exiting. This was a UX sore-spot: if a language server crashed, Helix did not recognize the exit and continued to send requests to it. All requests would timeout since they would not receive responses. This would also hold-up Helix closing itself down since it would try to gracefully shutdown the server which is implemented in the LSP spec as a request.
We could attempt to automatically restart the language server on crash. I left this for future work since that change will need to be slightly complicated: it will need to cover the case of a language server repeatedly crashing.
=> Handle language server termination

helix-term/src/commands.rs
Currently, commands such as `r<tab>` (replace with tab) or `t<tab>` (select till tab) have no effect. I consider this a bug because these commands work in Kakoune and I sometimes try to use them. Also, both `r<ret>` and `t<ret>` already work in Helix.
=> Make `r<tab>` and `f<tab>` work

flake.lock
This pull request updates the `nci` flake input to a version that includes the overrides added in https://github.com/yusdacra/nix-cargo-integration/pull/100. This will allow flake users to avoid having to download unnecessary inputs.
=> build(nix): update nci

book/src/generated/typable-cmd.md, helix-term/src/commands/typed.rs
This introduces a new command :reload-all and a short alias :ra to reload all open files.
This fixes https://github.com/helix-editor/helix/issues/2326
=> Add `:reload-all` command

runtime/queries/html/highlights.scm
Adds the missing `<!` to the html highlights.scm to fix the incorrect highlighting of `DOCTYPE` declarations.
Before:
After:
=> Fix broken html doctype highlighting

book/src/generated/lang-support.md, runtime/queries/elixir/indents.scm
Simple implementation of elixir indentations.
I am also not sure whether or not it is possible to do some kind of auto-pre outdent for "end", as it should be outdented before "end" and not after.
=> Implement simple indents.scm for Elixir

helix-term/src/commands.rs
#4458 changed the behavior of paste to select the newly inserted text. This is preferrable in normal mode because it's useful to be able to act on the new text. This behavior is worse for insert or select mode though:
* In insert mode, the cursor ends up on the last character of the newly selected text, so further typing inserts text before the last character.
* In select mode, the current selection is replaced with the new text selection which doesn't extend the current selection. With this change, the selection is extended to include the new text.
This aligns the behavior more closely with Kakoune, but it's coincidental instead of intentional: Kakoune doesn't implement bracketed paste (AFAIK) which causes this behavior in insert mode, and Kakoune doesn't have a select mode.
=> Select new pasted text in normal mode only

helix-core/src/syntax.rs
The limit of 64 breaks some highlighting in Erlang files with complicated record definitions. Bumping to 256  seems to work on all files I have seen.
|---|---|
| ![before](https://user-images.githubusercontent.com/21230295/202921390-4a79d2ad-6ef4-4697-a042-2bc7997d12df.png) | ![after](https://user-images.githubusercontent.com/21230295/202921398-89d80c7f-a881-477b-bfdc-76d2540080d5.png) |
=> Bump tree-sitter pattern matching limit to 256

flake.lock, flake.nix
Disable running tests since CI already runs them. The tests take up about 6 minutes of time in CI so I think disabling them would be nice.
=> build(nix): don't run tests in builds since CI runs them already, update inputs

helix-term/src/commands.rs, helix-view/src/view.rs
Previously, jumplists could grow unchecked. Every transaction is applied to jumplist selections to ensure that they are up to date and within document bounds, so this would cause every edit to become more expensive as jumplist lengths increased throughout a session. Setting a maximum number of entries limits the cost.
Vim and Neovim limit their jumplists:
* https://github.com/vim/vim/blob/b298fe6cbae3b240b10dbd55d9c38d0cc8e033d3/src/structs.h#L141
* https://github.com/neovim/neovim/blob/e8cc489accc435076afb4fdf89778b64f0a48473/src/nvim/mark_defs.h#L57
Notably, Kakoune does not. In Kakoune, changes are applied to jumplist entries lazily as you hit `<C-o>`/`<C-i>` though, so Kakoune doesn't have the same growing cost concerns. Kakoune also does not have a concept of a View which limits the …
=> Limit the number of items in the jumplist

helix-lsp/src/client.rs, helix-term/src/commands.rs, helix-term/src/commands/lsp.rs, helix-term/src/ui/completion.rs
Language Servers may signal that they do not support a method in the initialization result (server capabilities). We can check these when making LSP requests and hint in the status line when a method is not supported by the server. This can also prevent crashes in servers which assume that clients do not send requests for methods which are disabled in the server capabilities.
We already check server capabilities for document notifications and signature-help. This change covers manually invoked LSP commands like hover, documentHighlight, codeActions, etc.
=> lsp: Check server provider capabilities

Cargo.lock, helix-core/Cargo.toml, helix-core/src/syntax.rs
While working on an unrelated PR related to treesitter performance I noticed that editing text is extremely slow for large files with loads of injections.
The testcase I was looking at during testing is the largest file in the Linux kernel: `drivers/gpu/drm/amd/include/asic_reg/dcn/dcn_3_2_0_sh_mask.h`
From the flamegraph (see below) I noticed that most of the time is actually spent inside helix comparing language layers.
After some digging I found that helix checks if an injection layer is already present (and hence can be incrementally updated) by iterating the entire list of injections. This has worst-case performance of `O(N^2)`.
For example the Linux kernel header I was investigating contains 27859 injections (comments) all inside the top layer, so about 776 million comparisons are …
=> significantly improve treesitter performance while editing large files

helix-core/src/history.rs, helix-term/src/ui/editor.rs, helix-term/tests/test/splits.rs, helix-view/src/lib.rs, helix-view/src/macros.rs, helix-view/src/view.rs
Previously, transactions were only applied to the currently focused view. This could lead to jumplist selections not being updated or panics if a jumplist selection pointed past the end of the document.
Closes #4732
Closes #4600
Closes #4841
=> Apply transactions to all views

book/src/generated/lang-support.md, languages.toml, runtime/queries/qml/highlights.scm, runtime/queries/qml/indents.scm, runtime/queries/qml/injections.scm
Fixes https://github.com/helix-editor/helix/issues/2771
=> Add QML language support

helix-core/src/history.rs, helix-term/src/commands.rs, helix-term/src/commands/typed.rs, helix-term/src/ui/editor.rs, helix-term/tests/test/commands.rs, helix-view/src/document.rs
#4733 left a few edge-case bugs with undo/redo: `View::apply` was still being called directly in the `Document::undo_redo_impl` and `Document::earlier_later_impl` functions. This change removes those calls and applies the necessary transactions to all views in EditorView. In order to do this for `undo` and `earlier`, `History::changes_since` now handles the case where the given revision is less than the current revision and composes all of the inverted transactions between the two history points.
=> Fix transaction application on undo/redo/earlier/later

languages.toml, runtime/queries/edoc/highlights.scm, runtime/queries/edoc/injections.scm, runtime/queries/erlang/highlights.scm, runtime/queries/erlang/injections.scm, runtime/queries/erlang/locals.scm, runtime/queries/gleam/highlights.scm, runtime/queries/heex/injections.scm
This PR has a few updates for BEAM language (Erlang, Gleam, HEEx, EDoc) tree-sitter grammars and queries.
The main improvement is in Erlang where EDoc can now be injected into inline-comments and line breaks are handled correctly. This enables highlighting things like code-fences within function doc comments, and fixes some highlights when they are broken across comment lines:
|---|---|
| ![before](https://user-images.githubusercontent.com/21230295/203657865-32f85c7a-fac7-4a58-a458-24323e31ba14.gif) | ![after](https://user-images.githubusercontent.com/21230295/203657890-65492b50-8b1a-43bf-867d-26c97167f053.gif) |
The trick was to parse the newline characters as a part of the comment node in the Erlang grammar and then inject comments together as `injection.combined` …
=> Update tree-sitter grammars for beam languages

helix-term/src/commands.rs
Similar to #4554, this PR fixes the bug where the editor doesn't exit select mode after performing a surround command. The following commands are affected:
- `surround_add` (`ms`)
- `surround_replace` (`mr`)
- `surround_delete` (`md`)
Sending this patch with @archseer's confirmation on Matrix, quoting here:
> Anything that does an action on the selection should exit select mode
=> Exit select mode on surround commands

helix-lsp/src/transport.rs
This prevents a freeze while shutting down when using `efm-langserver`. `efm-langserver` exits immediately after seeing a shutdown request, without responding to the request. We block awaiting the reply to the shutdown request which will never come, so we time out.
This change responds to any pending requests with `Err` saying that the stream has been closed.
See https://github.com/helix-editor/helix/issues/4468#issuecomment-1323073907
=> Drain pending requests on language server termination

helix-term/src/commands.rs
This matches the insert-mode behavior for Vim and Kakoune: if the current line is empty except for whitespace, `<ret>` should insert a line ending at the beginning of the line, moving any indentation to the next line.
|---|---|
| ![before](https://user-images.githubusercontent.com/21230295/203450518-245adef1-5925-49ec-8cf7-fb0bda47bfa1.gif) | ![after](https://user-images.githubusercontent.com/21230295/203450531-b7883c91-0fa5-428e-b35d-4d98827b6ea4.gif) |
=> Clear line on `<ret>` when line is all whitespace

runtime/themes/nightfox.toml
This theme is an adaptation of
[github.com/EdenEast/nightfox.nvim](https://github.com/EdenEast/nightfox.nvim)
=> add theme nightfox

languages.toml, runtime/queries/html/highlights.scm
Bumps the tree-sitter-html version to address potential issues with trailing spaces.
=> Bump tree-sitter-html version

runtime/themes/fleetish.toml
Updates to the `fleetish` theme. Specifically:
- use darker background for menues as it (purely subjectively) loooks better
- use different color for `constant.buildin.boolean` and `keyword` to make statements such as `return true` read better
- use different colors for different markup link parts
- destructure the config where appliable
The PR also introduces new highlight scope called `function.declaration` that can be used to style function declaration different from function calls. Specifically for fleet, function declarations are white & bold and the thing that pops-out in the code the most. I think this might be useful also for other themes but happy to leave it out of this PR.
cc @krfl as the theme author.
Inspired by: https://github.com/cloudwindy/fleet-dark and …
=> feat(themes): improve fleetish

helix-view/src/editor.rs
Previously we removed selections for a closed view on only the currently focused document. A view might have selections in other documents though, so the view needs to be removed from all documents.
Closes #4878
=> Remove selections for closed views on all documents

book/src/generated/lang-support.md, languages.toml, runtime/queries/java/highlights.scm, runtime/queries/java/injections.scm, runtime/queries/java/textobjects.scm
tree-sitter-java [gained support](https://github.com/tree-sitter/tree-sitter-java/compare/bd6186c24d5eb13b4623efac9d944dcc095c0dad...09d650def6cdf7f479f4b78f595e9ef5b58ce31e) for Java """text blocks""", switch expressions, and records, so I figured it was time to update it.
=> Update tree-sitter-java and add Java textobjects

runtime/queries/go/indents.scm
Fixes #4877 
This fix correctly indents factored variable declarations.
=> Fix Go variable indentation

languages.toml, runtime/queries/css/highlights.scm
Bump the tree-sitter-css version to fix issues with spaces before colons, adds missing highlights, attempts to make other highlights more consistent, and organises the rest.
=> Update CSS syntax highlighting

Cargo.lock, helix-core/Cargo.toml
This `ropey` release contains multiple bugfixes and performance improvements for the line iterator.
Unblocks #4457 and #3890
=> Bump ropey to 1.5.1-alpha

Cargo.lock, helix-core/Cargo.toml, helix-core/src/diff.rs, helix-core/src/transaction.rs
Closes #4228 and #433
When `:reload` is called helix currently uses `similar` to compare
the on-disk file with the current state, to create a changeset that can be added to the history.
Similar implements a basic version of myers algorithm.
However, myers algorithm without additional enhancements quickly behaves quadratic over the filesize.
The implementation in `similar` also has many inefficiencies which lead to huge memory consumption as reported in #4228.
The situation is worsened by the fact that `similar` requires random access to the collections it is diffing.
This requires us to convert the ropes to a `String` (essentially duplicating the entire file in memory) before performing the diff.
Finally, helix used a **char** diff over the whole file.
While this produces `ChangeSet`s …
=> Significantly improve performance of `:reload`

runtime/queries/latex/injections.scm
This adds the remaining comment injections to `latex/injections.scm`.
I've looked at the rust grammar to find out how I should add those.
Fixes #4921.
=> fix(grammar): Add `block_comment` and `comment_environment` injection for latex comments

helix-core/src/history.rs, helix-term/src/commands.rs, helix-term/src/commands/lsp.rs, helix-term/src/commands/typed.rs, helix-term/src/ui/editor.rs, helix-term/tests/test/splits.rs, helix-view/src/document.rs, helix-view/src/editor.rs, helix-view/src/view.rs
We still have some panics from updating jumplist selections. The problem with the last strategy (#4733) was that not all edits are done through `EditorView::handle_event`: LSP edits like [autoformatting](https://github.com/helix-editor/helix/blob/583c2a5456263865c8aaf8b260909bfe431db549/helix-term/src/commands.rs#L2555-L2581) are done in callbacks. We would have to copy the code that updates all views everywhere.
Instead, this PR follows the hint in [#4733 (comment)](https://github.com/helix-editor/helix/pull/4733#issuecomment-1322916958): apply the transactions to other views lazily. In this change we apply transactions to the focused view eagerly in `Document::append_changes_to_history` and record on the view the document's revision. When switching windows or documents, we check the …
=> Apply transactions to views lazily

helix-view/src/input.rs, helix-view/src/keyboard.rs
Media keys are sent despite `DISAMBIGUATE_ESCAPE_CODES` being unset. Previously we panicked on these. This change translates the disambiguated keys from crossterm so that they do not cause a panic.
Closes #4125.
Supersedes #4576.
Closes #4576.
=> Handle disambiguated keycodes

book/src/keymap.md, helix-term/src/keymap/default.rs, helix-term/src/ui/prompt.rs
Not sure if this PR works but would be nice to have, no real reason not to I guess?
=> Add shift-backspace keybind alias for backspace

book/src/generated/lang-support.md, languages.toml, runtime/queries/racket/highlights.scm, runtime/queries/racket/injections.scm
Both the racket and scheme entries used the rkt file-extension. This commit removes that entry for scheme and so that the racket entry takes precedence. We explicitly point to the scheme grammar now and setup queries that inherit from scheme. This should enable using the racket language server configuration.
Closes #4913
=> Fix file-types declaration for racket

Cargo.lock, Cargo.toml, book/src/configuration.md, helix-core/src/lib.rs, helix-term/Cargo.toml, helix-term/src/application.rs, helix-term/src/commands/typed.rs, helix-term/src/ui/editor.rs, helix-vcs/Cargo.toml, helix-vcs/src/diff.rs, helix-vcs/src/diff/line_cache.rs, helix-vcs/src/diff/worker.rs, helix-vcs/src/diff/worker/test.rs, helix-vcs/src/git.rs, helix-vcs/src/git/test.rs, helix-vcs/src/lib.rs, helix-view/Cargo.toml, helix-view/src/document.rs, helix-view/src/editor.rs, helix-view/src/gutter.rs, helix-view/src/view.rs
Supercedes #1623.
I took this PR up as the original PR was tagged as waiting-for-author/inactive.
This PR is rebased on the current master to avoid conflicts.
Additionally, I have updated the PR with some improvements.
The design is now much more similar to the design suggested by @p-e-w.
The original author already did most of the work by implementing incremental diffing.
However, I have now streamlined the git interface.
The incremental diff only requires that git provides the head state of a file while the rest is handled by helix.
Therefore, I have simplified the git interface down to one function: `get_file_head`.
This interface is now provided by a trait, that is implemented for git but is trivial to implement for other diff sources as well and could be exposed to the plugin system …
=> (Git) diff gutter implementation

helix-term/src/commands/typed.rs
=> reload_all: Ensure view is synced with doc history before reload

helix-term/src/keymap/default.rs, runtime/tutor
Closes https://github.com/helix-editor/helix/issues/4874, closes https://github.com/helix-editor/helix/issues/4864
Tested on both Linux and Windows, the aliases don't seem to conflict each other.
"tab" on Linux works as both tab and C-i and "C-i" itself doesn't do anything on gnome terminal.
While on Windows tab works as tab and "C-i" works as C-i.
=> Add Ctrl-i alias for Windows

languages.toml, runtime/queries/go/indents.scm
Update tree-sitter-go to latest with updated support for generics.
See: https://github.com/tree-sitter/tree-sitter-go/compare/0fa917a7022d1cd2e9b779a6a8fc5dc7fad69c75..05900faa3cdb5d2d8c8bd5e77ee698487e0a8611 for full diff.
=> feat(lang): bump tree-sitter-go

runtime/themes/nightfox.toml
Hi, I just fix the  nightfox theme Diff sign color too dumb， so that can no see it in the code edit view.
Please take a moment to see this，Thanks！
=> nightfox theme: Use brighter colors for diff scopes

helix-core/src/history.rs, helix-term/tests/test/splits.rs
=> Fix transaction composition order in History::changes_since

languages.toml
Took me a while to figure out why auto format doesn't work. I think these are sensible defaults.
`provideFormatter` enables capability in LS and `auto-format` performs format on save.
=> Enable auto format for css and scss files

helix-vcs/src/diff/worker.rs
This log message is not that important and can occur very frequently when editing large files.
To avoid excessive IO/polluting the log file the log level is reduced to `info` which is not written to disk by default.
=> Reduce log message about diff timeout from warn to info

helix-lsp/src/lib.rs, helix-term/src/ui/completion.rs
Completion edits - either basic `insert_text` strings or structured `text_edit`s - are assumed by the LSP spec to apply to the current cursor (or at least the trigger point). We can use the range (if any) and text given by the Language Server to create a transaction that changes all ranges in the current selection though, allowing auto-complete to affect multiple cursors.
Closes https://github.com/helix-editor/helix/issues/2016
=> Apply completion edits to all cursors

helix-term/src/commands.rs, helix-view/src/view.rs
Since `jumplist_picker` doesn't update screen, we need to do one action to get the correct view.
So I added 'align_view' to the callback like `jump_backward`.
=> fix: align view after jumplist_picker

runtime/themes/serika-light.toml
While developing lints for `diff` key, I found that `serika` did not parse.
This is a quickfix for that.
Originiated from https://github.com/helix-editor/helix/issues/4972 and https://github.com/helix-editor/helix/pull/5037
=> fix(theme): serika toml syntax valid

helix-term/src/ui/completion.rs
=> Only write newlines in menu selection popup if the lsp returns detail

helix-term/src/commands.rs
Previously completions would still show when `auto-completion` was set to `false`.
=> Fix LSP completions ignoring auto-completion option

runtime/themes/acme.toml
=> Update `diagnostic.error` background for acme theme

book/src/generated/lang-support.md, languages.toml, runtime/queries/bibtex/highlights.scm
This PR does three things:
- Adds an entry to `language.toml` (using https://github.com/latex-lsp/tree-sitter-bibtex/commit/ccfd77db0ed799b6c22c214fe9d2937f47bc8b34)
- Adds [queries from the same repo](https://github.com/latex-lsp/tree-sitter-bibtex/tree/master/queries)
- Adds a formatting configuration that uses [FlamingTempura/bibtex-tidy](https://github.com/FlamingTempura/bibtex-tidy#sec-cli)
Out of the three, the most opinionated is probably the last one. Let me know if there's anything to add or remove.
=> Add support for the BibTeX file format

helix-core/src/lib.rs, helix-loader/src/grammar.rs, helix-loader/src/lib.rs, helix-term/src/ui/mod.rs
Right now we check if `.git` exists and is a directory to detect a git repo root.
This does not work well for git repos with multiple/detached work-tree where `.git`
is a file which contains the location of the folder that contains files that would normally be located in `.git`.
This PR changes all checks for `.git` to use `.exists()` instead of `.is_dir()`, so it also works for files.
Since the `git` cli uses the same detection mechanism (try `tough .git && git status` in an empty directory)
this seems more inline with the intended behavior.
Furthermore, workflows with multiple worktrees become much nicer with this (I use one for each branch to quickly context switch)
as the file picker now stops at the correct location. 
Fixing this will also be important for getting repo caching to …
=> properly handle detachted git worktrees

helix-term/src/commands.rs, helix-view/src/editor.rs
This is similar to the change in e4c9d4082a139aac3aea4506918171b96e81f5b9: reset the editor to normal mode when changing buffers. Usually the editor is already in normal mode but it's possible to setup insert-mode keybindings that change buffers.
Fixes #5058
=> Reset mode when changing buffers

book/src/themes.md, runtime/themes/base16_transparent.toml, runtime/themes/dark_high_contrast.toml
- Use `underline` instead of `modifier = ["underlined"]`
- Add base theme author sign
- Adjust some colors
=> update(theme): adjust base16_transparent and dark_high_contrast

languages.toml
Fixed typo in file-types, and corrected auto pairing since lisp uses single ``` ` ``` and ```'```
=> Fix commonlisp filetypes typo and auto-pairs

book/src/generated/typable-cmd.md, helix-term/src/commands/typed.rs
I often use an editor in conjunction with a REPL open in another terminal.
To quickly send commands from my editor to the REPL I pipe the editor selection into kitty's remote control feature: `kitty @ send-text --match recent:1 --stdin`.
In kakoune I could set up a keybinding utilizing the `pipe-to` command <Alt-|> and pass the shell command directly.
For helix I can only pass the command to typed arguments, but there is currently no typed command to pipe selections to shell commands while ignoring the output.
My suggestion is this:
Add a `:pipe-to` command which is essentially a copy of the `:pipe` command, but uses `ShellBehavior::Ignore` instead of the hard-coded `ShellBehavior::Replace`.
=> Add `:pipe-to` typable command that ignores shell output

book/src/generated/lang-support.md, runtime/queries/bash/indents.scm
Resolves #5087 
Adds indents for pipelines, if statements, case statements, and functions, which was mentioned in the original issue. I'm sure there's more indents that would be applicable here, so if anyone catches any that should be added, let me know :-)
=> Add Bash indents

helix-term/src/commands/typed.rs, helix-view/src/theme.rs
The error messages for a theme that failed to be deserialized (or otherwise failed to load) were covered up by the context/with_context calls:
* The log message for a bad theme configured in config.toml would only say "Failed to deserilaize theme"
* Selecting a bad theme via :theme would show "Theme does not exist"
With these changes, we let the TOML deserializer errors bubble up, so the error messages can now say the line number of a duplicated key - and that key's name - when a theme fails to load because of a duplicated key.
Providing a theme which does not exist to :theme still gives a helpful error message: "No such file or directory."
See #5043
=> Improve error message handling for theme loading failures

helix-term/src/commands/lsp.rs, helix-term/src/ui/mod.rs, helix-term/src/ui/overlay.rs, helix-term/src/ui/picker.rs
Supersedes #3110. Many language servers don't send all symbols when the client sends an empty query (typically for performance reasons). This change adds a DynamicPicker component that re-requests workspace symbols when the query changes.
See sudormrfbin's before & after gifs:
| ---- | ---- |
| ![helix-old-workspace-symbols](https://user-images.githubusercontent.com/23398472/179821244-0d82aa7d-c941-49a5-9c48-b92e5d5b01c2.gif) | ![helix-dynamic-workspace-symbols](https://user-images.githubusercontent.com/23398472/179821259-408a4d3d-c5a3-4e01-b370-e933cf4cee59.gif) |
This version uses the idle-timeout event as a sort of debounce which prevents querying the language server too aggressively.
Fixes #1437
Fixes #3619
Fixes #4910
Closes #3110
=> Re-request workspace symbols dynamically

helix-term/src/commands.rs
This roughly matches the behavior of the diagnostic picker: when jumping to a diagnostic with `[d`/`]d`/`[D`/`]D`, the range of the diagnostic is selected instead of the start point.
=> Select diagnostic range in goto_*_diag commands

book/src/generated/typable-cmd.md, helix-term/src/commands/typed.rs, helix-term/src/compositor.rs
Not sure if we want this, as per [this comment](https://github.com/helix-editor/helix/issues/4350#issuecomment-1282988182), but anyway, here it is.
Fixes https://github.com/helix-editor/helix/issues/4350
=> add redraw command

helix-term/src/commands.rs
This function appears to have been deleted by mistake in https://github.com/helix-editor/helix/commit/42ad1a9e043e2e0fb148924ff79b9abbe06907ae.
=> Restore deleted goto_pos function

languages.toml
used in, for instance, https://github.com/ifax/HylaFAX/tree/0aa97f2dfe7e71005c2406dcd7677f09691bf48b/faxd
=> set 'c++' as a recognised extension for cpp

helix-term/src/health.rs
This commit resolves #5193, where the author requested that the name of the binary needed is printed along with the rest of the health information.
This commit adds a `format!` macro which formats in the name of the binary and then it will be printed along with the rest of the debug information. The value in `cmd` is referenced to the call to which, and then consumed upon the call to `format!`.
This is my first issue in Helix, so please give feedback if this is not the kind of solution that you find optimal.
=> Print the binary required by the debug adapter

helix-term/src/ui/mod.rs, helix-term/src/ui/picker.rs
Before:
After:
Wouldn't be opposed to writing a test here, but, given that this doesn't fail any existing test, also happy to let it pass :P
=> Better sorting in picker in case of ties

book/src/generated/lang-support.md, languages.toml, runtime/queries/matlab/highlights.scm
Add highlighting for MATLAB/Octave using the grammar defined at https://github.com/mstanciu552/tree-sitter-matlab
=> Add support for MATLAB/Octave files

base16_theme.toml, book/src/themes.md, helix-term/src/ui/prompt.rs, theme.toml
Resolves #4920.
This PR adds a new theme key `ui.text.inactive`, and sets the value in the default themes (`theme` and `base16_theme`) to be the same value as the `comment` key.
Themes from external contributors are left untouched, in the hope that maintainers of those themes will support this new key themselves.
=> Add new theme scope `ui.text.inactive` for prompt suggestions

runtime/queries/nix/injections.scm
`comment` lang injection was missing for `nix`
adding it doesn't seem to interfer with the marking of multiline strings.
so this still works...
```
foo = /*rust*/''
pub fn bar() {}
''
```
=> Add missing comment injection for nix

runtime/themes/monokai_pro_spectrum.toml
This is a partial fix for https://github.com/helix-editor/helix/issues/5249 - notably the comment https://github.com/helix-editor/helix/issues/5249#issuecomment-1361571312 
The theme `monokai_pro_spectrum` uses a non-hex-coded color `"cyan"`.
`"cyan"` should be `#5ad4e6` according to the screenshot at https://www.vscolors.com/themes/f5d7ffda-c1d6-4070-ba80-803c705a1ee6-3ed72ace, which is in fact the palette color `"blue"`.
=> fix(theme): Replace invalid `cyan` by `blue` in line with original theme

runtime/queries/rust/highlights.scm
- Loop labels are now highlighted as `@label` instead of `@type`
- `unsafe` is now `@keyword.special`
- `macro_rules!` is now `@function.macro`
- `@type.variant` is replaced with `@type.enum.variant` so enum constructors are highlighted correctly
- Some newlines were removed for consistency
=> Fix & Tweak Rust's Syntax Highlighting

runtime/queries/markdown/injections.scm
HTML nodes should be combined injections in the markdown block grammar. When nodes are together the highlighting works properly but when there is markdown content between HTML nodes like in a `<details>` tag, the highlighting of the closing tag breaks since tree-sitter-html looks for opening and closing tags.
|---|---|
| ![before](https://user-images.githubusercontent.com/21230295/209239556-53824ed3-2918-406a-b9c0-9dec4e2fd879.png) | ![after](https://user-images.githubusercontent.com/21230295/209239567-6a0d0cbd-ffae-4076-a98a-1e74eef42dc0.png) |
(See that closing `</div>` tag on L17.)
=> Fix HTML injection within markdown

runtime/tutor
Efforts towards [#506](https://github.com/helix-editor/helix/issues/506).
The tutor section `10.1` tells you to select `would`, which causes later cycling of content make no visible changes with `Alt-(` and `Alt-)`.
Instructions are added to the note, so that the user selects different contents before attempting to cycle them.
=> tutor: Add a content cycling section

book/src/keymap.md, helix-core/src/selection.rs, helix-term/src/commands.rs, helix-term/src/keymap/default.rs
My attempt at https://github.com/helix-editor/helix/issues/4914 
Adds command that will merge consecutive ranges in the selection, bound to `Alt-_` for now.
=> Add command to merge consecutive ranges in selection

helix-term/src/ui/editor.rs
=> mouse operations respect scrolloff

runtime/themes/rose_pine.toml
Apply the new curl underline diagnostics to the `rose_pine` theme. Also fixes the color "gold" being used for too many kinds of diagnostics, now there's a more conventional choice of diagnostics colors (redish = error, yellowish = warning, blueish = hint).
Before
After
I've updated the authors section above as it seemed to be some sort of list of people who contributed to the theme, but I'm not sure if this is correct. If it isn't, then please let me know :)
=> Use curl underlines in the rose_pine theme

helix-term/src/application.rs
Fixes a minor grammar error with "Loaded 1 files" message. Only adds the `s` character when the number of files opened is not 1.
=> Avoid trailing `s` in message when only 1 file is opened

helix-term/src/commands/typed.rs
Commit 1b89d3e5350f83b2ffb86a86326bd2714308ee53 introduced a regression where opening a new file would no longer work, because attempting to canonicalize its path would lead to a "No such file or directory" error. Fall back to opening a new file when encountering an error to fix this case.
=> Fix opening new files

runtime/tutor
Maybe this is obvious, but it took me several days to google this up :-)
=> Add eb word selection trick to the tutor

runtime/tutor
Hello. Just a small addition to the tutor. :D
=> tutor: add chapter for commenting lines

runtime/queries/vue/injections.scm
Changes the injections for *Vue* `script` and `style` tags to allow for custom preprocessors. Before they were hardcoded to  plain `javascript` and `css`.
*Vue* tooling can specify a preprocessor via the `lang` attribute.
This only adds injections for languages that helix already supports.
e.g.
```vue
<script lang="typescript">
```
or very commonly used
```vue
<style lang="scss">
```
=> Allow custom preprocessors for 'vue' injections

runtime/themes/kanagawa.toml
This comprises 4 changes:
1. added "sumiInk3" as ui.cursorline.primary bg color (in line with original)
2. swapped the cursor bg and fg colors (to maintain readability with cursorline; now in line with original)
3. added ui.menu and ui.menu.selected colors (should be close to original)
4. separated ui.selection and ui.selection.primary
@zetashift please take a look; especially regarding my choice of color for change 4.
--
Edit: now 8 changes:
5. added the theme's official git gutter colors to address kanagawa's share of #4972 
6. added "sumiInk4" as ui.virtual.indent-guide
7. added "roninYellow" as ui.linenr.selected
8. set ui.help bg to "sumiInk1"
=> Fix kanagawa theme lint and added git gutter colors

helix-core/src/auto_pairs.rs, helix-term/src/commands.rs
Currently, inserting a newline sometimes creates an additional indent (and an additional line) even if the cursor is not between matching auto-pairs:
````
))
````
Pressing enter when the cursor is on the second closing bracket results in the following text and indented cursor:
````
)
|
)
````
This commit fixes that issue (which occured whenever the cursor was between 2 closers of some auto-pair) and the wrong documentation that probably caused this in the first place.
=> Fix erroneous indent between closers of auto-pairs

runtime/themes/emacs.toml
Screenshot:
This PR fixes #4972. CC @David-Else
=> Update `emacs` theme diff colors

helix-term/src/application.rs
Just had a go at implementing this
Not quite sure where to make test or what tests to make, but I tried it and it seems to be able to reload auto formatting, at least
https://user-images.githubusercontent.com/30967965/208830221-40562d71-cec4-4c2d-9f31-e6a056360fa4.mp4
=> Reload language config with `:config-reload`

helix-term/src/args.rs, helix-term/src/commands/typed.rs
Addresses #5322.
- `:open` should work on directories with `~` in the filepath (i.e. file picker dialog opens)
https://user-images.githubusercontent.com/59901837/209839820-7887b399-07f7-4213-b98f-9d1c575012be.mov
=> Expand `~` when parsing file paths in `:open`

helix-view/src/theme.rs
=> Fix theme inheritance for default themes

book/src/configuration.md, helix-term/src/ui/statusline.rs, helix-view/src/editor.rs
Makes the `FileName` status line element render just the `basename` of the open file. The existing variant that renders the relative path of the open file is renamed to `FilePath` (render functions are also renamed accordingly).
```toml
[editor.statusline]
left = ["mode", "spinner", "file-name"]
```
```toml
[editor.statusline]
left = ["mode", "spinner", "file-path"]
```
=> Add a status line element that shows just the basename of the file

helix-term/src/commands.rs, helix-term/tests/test/commands.rs
for both extend_line_(above/below) the check for if current line is selected now works if there is a count:
this now means if you select a line with ``x`` and then do ``2x`` 3 lines will be selected whereas before only 2 lines would be, this keeps ``2x`` on a not fully selected line only selecting 2 lines which is the desired functionality of ``extend_line``
fixes #5270
=> fix(commands): extend_line to proper line when count and current line selected

languages.toml
Currently the `sshclientconfig` language uses the default comment token `//` instead of the correct `#`. This PR fixes it.
=> Fix comment token for sshclientconfig

flake.nix
Runs of `cargo build` would fail with `ld: framework not found CoreFoundation` inside a devshell (`nix develop`) on a Darwin host.
This is fixed with two changes:
* Including the `CoreFoundation` package within the devshell's derivation.
* Switching from `value` to `eval` so that we append to the `RUSTFLAGS` environment variable rather than overwriting it. `numtide/devshell` already exposes the `Library/Frameworks` path within the devshell derivation but it was being overwritten by the manual setting of `RUSTFLAGS` in `env`.
=> flake: Fix devshell for darwin hosts

README.md
Helix now has an icon and `./contrib/Helix.desktop` makes use of it. However `README.md` still says that helix has no icon.
=> Mention the icon in README.md

helix-term/src/application.rs, helix-term/src/commands/typed.rs
Fixes  https://github.com/helix-editor/helix/issues/5377.
I think the bug https://github.com/helix-editor/helix/issues/5377 stemmed from not updating the reference to the syntax loader in the `editor` as well.
Hence, it probably was the case that before, the old reference was in fact actually never dropped, and that the `editor` was still pointing to the old syntax loader.
Took the chance to improve some status messages too.
=> Fix language config reload logic

book/src/generated/lang-support.md, runtime/queries/tfvars/folds.scm, runtime/queries/tfvars/highlights.scm, runtime/queries/tfvars/indents.scm, runtime/queries/tfvars/injections.scm
I noticed that the `.tfvars` files in my Terraform projects don't get syntax highlighting unless I manually run `:set-language hcl`. 
The `tfvars` language is already configured to use the `hcl` grammar (since it was separated from `hcl` in #2244):
https://github.com/helix-editor/helix/blob/0dbee9590baed10bef3c6c32420b8a5802204657/languages.toml#L1279-L1288
So this small PR adds the `tfvars` files into `runtime/queries/`, with each simply inheriting from `hcl` (as advised on Matrix by @archseer).
I've added files to inherit everything from `hcl` (`folds`, `highlights`, `indents` and `injections`), though I'm unsure if all are necessary, or if perhaps only `highlights.scm` should be added. Please let me know if anything needs to be changed. 
Thanks!
=> Add runtime queries for `tfvars` (based on `hcl`)

runtime/queries/python/indents.scm
This is a workaround for the python tree-sitter grammar being very sensitive to incomplete code in some cases (an `try_statement` without an except/finally clause sometimes even prevents the surrounding function from being recognized). I simply added a few queries that improve the indentation in common situations. Since they only match `ERROR` nodes, this shouldn't break anything that works correctly right now.
Should fix  #763 and #5045. At least for the common scenario of writing down a `try_statement` with a missing `except_clause`/`finally_clause`, the indentation is now correct in all cases I tested,
=> Improve indent queries for python

README.md
The ignore-0.4.19 package has a breaking change for the current build configuration as it requires Rust 1.63 or greater. The cargo install command ignores the lock file producing the following error: error[E0658]: use of unstable library feature 'scoped_threads'
--> /build/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.19/src/walk.rs:1285:9
The locked flag keeps the package pinned at 0.4.18.
See:
Cargo install lock issue: https://github.com/rust-lang/cargo/issues/7169
ignore commit: https://github.com/BurntSushi/ripgrep/commit/e95254a86f484eec663be4714924d91d3cf39cb8
=> Update the cargo installation instructions to include --locked

book/src/install.md
By default `cargo install` ignores `Cargo.lock` file.
This lead to a problem where ignore 0.4.19 didn't compile (was using unstable feature of Rust 1.61)
This change make an update in the 'Install from source'  forcing cargo to respect the aforementioned file.
=> Adding '--locked'

helix-term/src/application.rs
After changes in #5239, the loaded configuration wasn't stored, resulting in a success message even if the instance kept the previous configuration values.
=> Store new config on application in :config-reload

runtime/themes/solarized_dark.toml
Title and border were barely visible.
Changed foreground color and modifier to match the text.
=> Fix theme solarized_dark infobox

helix-term/src/ui/mod.rs
Fix for https://github.com/helix-editor/helix/issues/5136
Bug has to do with how the `file_name` method deals with paths ending in `.` or `/.`. I hardcoded the value for `file_name` for paths ending in `/.` and paths that only consist of a single period, and updated the logic for `path`.
=> Fix autocompletion for paths with period 

book/src/themes.md, runtime/queries/rust/highlights.scm
The deleted code contained keys that aren't used by Helix's themes, caused inconsistent highlighting of punctuation, highlighted lowercase arguments as integers, and was in the wrong section of the file.
However it was also highlighting `derive` as `@special` instead of `function.macro`, so if we want to keep that behaviour then maybe something like this could be inserted at the top of the `Macros` section instead?
```scheme
(attribute
(identifier) @special
(#eq? @special "derive")
)
```
=> Fix Broken Attribute Highlights

runtime/themes/gruvbox.toml, runtime/themes/gruvbox_dark_hard.toml, runtime/themes/gruvbox_light.toml
Set a different `ui.selection.primary` colour for the Gruvbox family of themes so that the active selection is visually distinct when there are multiple selections.
=> Specify primary selection colour for Gruvbox themes

helix-lsp/src/jsonrpc.rs
The JSONRPC spec says:
> If present, parameters for the rpc call MUST be provided as a Structured value
https://www.jsonrpc.org/specification#parameter_structures
(Where a "Structured value" is elsewhere defined as either a map or array.)
This change skips the serialization of the `params` field for JSONRPC method calls and notifications if the `params` field is the `None` variant. This fixes compatibility with LSP servers which adhere closely to that part of the spec: `ocamllsp` in the wild.
Fixes #5400
=> jsonrpc: Skip serializing params if params are None

runtime/themes/acme.toml
Current configuration doesn't really fit this theme.
Previously:
Now:
=> Acme Theme - Change bufferline foreground color

runtime/themes/acme.toml
Current configuration doesn't have `ui.linenr` set up which leads to showing line numbers in an unpredictable way, like in an example below:
After change:
=> Acme Theme - Add `ui.linenr` configuration

book/src/generated/lang-support.md, languages.toml, runtime/queries/ponylang/highlights.scm, runtime/queries/ponylang/indents.scm, runtime/queries/ponylang/locals.scm, runtime/queries/ponylang/textobjects.scm
I followed the official docs as good as possible, i hope this language addition (tree-sitter only for now) meets your requirements. If not, please advise. Happy to change anything.
It is based on this tree-sitter grammar that i wrote: https://github.com/mfelsche/tree-sitter-ponylang
=> Add language support for ponylang

languages.toml, runtime/queries/cpp/injections.scm
The grammar now exposes the delimiter of raw-strings. We can now inject the inner grammar in cases like:
const char* script = R"js(
alert('hello world!');
)js";
=> Update tree-sitter-cpp, support injections in tagged rawstrings

languages.toml
Helix uses old tree-sitter-json git revision. Not too long ago new [version](https://github.com/tree-sitter/tree-sitter-json/commit/124edff33adfa209247c03119285feec8c4aca43) came out that supports comments. Also I added _jsonc_ format as alias for _json_. In todays world they're equal, all uses _json_ with comments and I very rarely see _jsonc_ format. There is no needs to distinct this formats.
Both formats look like this:
Previously json:
=> Update tree-sitter-json that supports comments, add jsonc as file-type for json format (#5452)

book/src/generated/lang-support.md, book/src/languages.md, languages.toml, runtime/queries/dhall/highlights.scm, runtime/queries/dhall/textobjects.scm
This adds language configuration for the [dhall language](https://dhall-lang.org/).
I chose to add configuration for the command line formatter even though the LSP implementation handles formatting, since the formatter is part of the `dhall` CLI and is more widely available.
- The class queries don't apply to dhall.
- Dhall does not have unit tests per se, but does have assert expressions.
- dhall does not have named functions, but has lambdas (term and type-level)
=> Language support for dhall

Cargo.lock, helix-view/Cargo.toml, helix-view/src/clipboard.rs
Fixes the issue described in #5424 
The code has been changed so that for unix type platforms a call is made to `libc::setsid` using the unix specific CommandExt [pre_exec](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.pre_exec).
The `setsid` call happens just after `fork` has been called and before `execve` is called. This means it runs in the context of the child process.
The call is necessary to ensure that spawned child processes related to the clipboard (e.g. `xclip`) have a distinct process session ID and process group ID.
Without this change when the parent process exits, the child (i.e. `xclip`), can be erroneously killed leading to copy/paste breaking in some specific circumstances such as those detailed in #5424
=> Fix for lost clipboard contents (#5424)

helix-term/src/ui/picker.rs
Closes #3924. This is a pretty small change but everyone has to start somewhere :P
=> Add ability to load files in the background without closing the picker

languages.toml, runtime/queries/scala/highlights.scm
There have been a lot of changes in tree-sitter/tree-sitter-scala, including partial support for Scala 3 syntax and breaking changes in some of the nodes.
This bumps up the grammar to the latest, and adjusts the queries.
Co-authored-by: Anton Sviridov <keynmol@gmail.com>
Co-authored-by: Chris Kipp <ckipp@pm.me>
=> highlight(scala): update the Scala highlight queries

book/src/configuration.md, book/src/remapping.md
It was not clear (to me) that minor modes were configurable in the keymap configuration (it can be inferred from the `ga` mapping in the example, but it's easy to overlook).
=> doc: add a note about nested bindings in key remapping

languages.toml
This is required to make commands like [doctor-run](https://scalameta.org/metals/docs/integrations/new-editor#run-doctor) work. It simply opens a browser to get general information about the build.
[isHttpEnabled](https://scalameta.org/metals/docs/integrations/new-editor/#ishttpenabled)
=> Enable http server by default in Metals config

helix-term/src/commands.rs
Fixes #5261
While this does fix the underlying issue of that bug, which was that appending to history only happened in [editor.rs:1424](https://github.com/helix-editor/helix/blob/1af76b738dd5bdae14b025d07d3001c4ad23e071/helix-term/src/ui/editor.rs#L1424) which meant that undo-ing after executing a command from the palette would call `undo` before the change was committed, it does not address the bigger issue - that it's way too easy to mutate a document and have document and history desync.
I'm opening this PR not necessairly to have this fix merged (although we could do it to fix the issue temporarily) but to document and highlight the root cause and possibly discuss a long-term fix, which I'd gladly take on implementing.
Discussion from the matrix channel about this issue:
> Pascal …
=> Commit to history after executing a command from the palette

helix-term/src/commands.rs, helix-view/src/editor.rs
Adds command 'rotate_view_backward' and changes 'rotate_view' to 'rotate_view_forward' to stay consistent.
=> Add command to rotate view backward

runtime/themes/gruvbox.toml, runtime/themes/gruvbox_dark_hard.toml, runtime/themes/gruvbox_light.toml
The diagnostic indicator background did not match the column or row's background colour as this was context specific, and the background for the indicator was being explicitly set.
This commit removes the explicit value for the indicators background allowing it to adapt to the context. This aligns it with other themes, and resolves the issue.
Before:
After:
=> Fix diagnostic indicator background for gruvbox themes

book/src/themes.md, helix-term/src/ui/editor.rs
This PR is the result of a discussion held in #4298. It's an alternative solution to #4298 and #2366, which in turn closes the issues in ~~#1833 and~~ #1337.
In short; it adds the possibility to set primary and non-primary (secondary) cursor colors for a given mode. Compared to the other presented solutions:
* The source change is smaller and IMO cleaner.
* Adds the possibility to set a primary for normal mode and a fallback for the other modes.
* Does not introduce any breaking changes to the themes and their current behavior.
* Is consistent with other fallback behavior for themes.
Example of something that was previously not possible to do:
https://imgur.com/a/JHxYuJm
Diagram for fallback behavior:
https://imgur.com/a/Kds3606
=> Primary cursor colors by mode

helix-term/src/commands.rs, helix-term/src/commands/dap.rs, helix-term/src/commands/lsp.rs, helix-term/src/ui/completion.rs, helix-term/src/ui/menu.rs, helix-term/src/ui/picker.rs, helix-tui/src/text.rs, helix-tui/src/widgets/table.rs
Continues #2814. This change reuses the table widget directly in the picker, finally allowing items to be formatted as columns 🎉. Column formatting can be done by implementing `menu::Item::row()` on the picker items.
- There was a subtle bug in rendering the highlights for matching text which produced incorrect highlighting with multi byte characters. The algorithm to calculate highlights had to be re-written anyway to be injectable into a row of the table, and the issue was fixed along with this:
```
The fuzzy matcher returns char indices of the choice that matched
the pattern, while highlighting can only be done on whole graphemes.
The earlier code assumed char indices == grapheme indices which
broke highlighting with characters like å.
This commit solves this issue by converting …
```
=> Reuse table widget in picker

book/src/install.md
Adds build instructions for musl to the installation section of the book.
See https://github.com/helix-editor/helix/issues/1028#issuecomment-1387251890 for reference.
I tested this on the official docker image without this flag tree-sitter
grammars do not load but with this flag they do load.
=> doc: add build instructions for musl-libc

runtime/themes/zenburn.toml
Add a separate theme for `selection.ui.primary`. To stay consistent, I took the `Visual` value of the `alternate_visual` variant (https://github.com/jnurmine/Zenburn/blob/master/colors/zenburn.vim#L421)
See #3842
=> theme(zenburn): separate theme for selection.ui.primary

helix-term/src/commands.rs
Fixes #5423
This change simply makes `join_selections` and `join_selections_space` command return early when there is nothing to join (hence they have no effect anyway). This prevents setting an empty selection for `join_selections_space` (which would lead to a crash).
=> Fix panic for noop selecting join

runtime/themes/kanagawa.toml
This PR introduces following changes
* Add sumiInk2 color for theming rulers – at the moment only »virtual« is set, which themes both whitespace characters and rulers. This change themes the foreground for whitespace characters and the background for rulers.
* Dark background for menu and help – while the current version works for the command mode menu and help, these UI elements are also in use for auto-completion. Using the main background for such popups is a little confusing, because there is no border to separate menu content from main content.
* Bold modifier for insert and select mode in statusline – normal mode already uses bold and it is a matter of taste, but I’d say it looks more consistent this way.
* Dark foreground color for window separators – the original nvim theme seems …
=> Kanagawa: theme rulers and some miscellaneous fixes

languages.toml
Add more file-types for Python. Based on https://stackoverflow.com/a/18032741/14986231 and https://github.com/neovim/neovim/blob/nightly/runtime/lua/vim/filetype.lua#L816
=> Add more file-types for python

languages.toml, runtime/queries/scala/highlights.scm
Ref https://github.com/tree-sitter/tree-sitter-scala/pull/164
tree-sitter-scala has recently add a fix to workaround segv crashes in other editors. Not sure if it happens to Helix as well, but it's probably a good idea to use the latest.
=> highlight(scala): update to fix potential crash

runtime/themes/monokai_pro_spectrum.toml
Fixes #5249
`"magenta"` is not defined as hex code in the theme's palette and thus depends on the terminal emulator color theme.
This commit replaces the color with `"red"`, which is defined.
After 1f0a76fe6dd2968cc183bdb7b08132a4836153ad, a remaining issue mentioned in https://github.com/helix-editor/helix/issues/5249 is:
> Arguably, yellow on magenta has low contrast by definition (even if it was hex-coded) and thus is bound to be more or less hard to read.
> 
> The root cause is that unlike others, this theme uses red as color for builtin types, keywords and operators. Therefore, red is not a good error color. (See https://github.com/helix-editor/helix/pull/2433)
Note that https://github.com/helix-editor/helix/pull/2433 should no longer be a problem, since …
=> fix(theme): Replace non-palette color "magenta" with palette color "red" in `monokai_pro_spectrum`

helix-term/src/commands.rs, helix-term/src/commands/lsp.rs, helix-term/src/commands/typed.rs, helix-term/src/ui/completion.rs, helix-term/src/ui/editor.rs, helix-term/tests/test/helpers.rs, helix-view/src/document.rs, helix-view/src/editor.rs, helix-view/src/lib.rs, helix-view/src/view.rs
Not sure why there is this TODO, so I cleaned it up.
=> Remove apply_transaction helper

runtime/themes/monokai_aqua.toml
Problem
-------
Current monokai (pro or otherwise) seems too red and green, missingthe bright aqua / cyan color found in Sublime's Monokai.
Solution
--------
This adds a variant of monokai, which I named monokai_aqua.
=> theme: monkai_aqua variant

runtime/tutor
“Type Escape” makes it seem one has press <kbd>e</kbd><kbd>s</kbd><kbd>c</kbd><kbd>a</kbd><kbd>p</kbd><kbd>e</kbd> instead of pressing the key. This may be even better as “Press the esc key” but it’s wordier.
=> tutor: Change "Type" to "Press" for specials keys and modifiers

book/theme/css/variables.css, book/theme/highlight.css
Until this patch, all mdbook themes in the documentation used the Colibri values for syntax highlighting. This made the documentation very hard to read in some light themes.
Fix #3765
=> book: Use per-theme syntax-highlighting CSS variables

runtime/themes/dracula.toml
Hi,
while using the editor I've notided that the colors for the invisible characters are the same as comments, and I find that really poping especcialy comming from `dracula/vim`. The PR simply adds a new highlight color (taken from the `dracula/vim` repo) and used that for the invisible characters.
**before**
**after**
=> theme: make dracula ui.virtual.whitespace less intrusive

helix-view/src/graphics.rs, helix-view/src/keyboard.rs
remove `#[cfg_attr(feature = "serde")]` from helix-view crate.
`serde` feature is not currently being used in helix-view crate
Fixes https://github.com/helix-editor/helix/issues/5615
=> refactor(helix-view): remove cfg_attr references a nonexistent feature

languages.toml
After much pain and tribulation I finally found that what I needed to do was add build.gradle to my list of roots for java in order to get jdtls to not hate me. 
I figure this would be a good general addition
=> Add build.gradle to list of java roots

helix-view/src/editor.rs
There's a clippy warning on Windows. This PR fixes it.
=> Make clippy happy on Windows

languages.toml
Use markdown language for hub pull-request files
The hub[^1] command-line tool uses a file called `PULLREQ_EDITMSG`[^2].
This file is used to edit the text from of each commit being submitted
in a pull request, and the final content is rendered as markdown by
GitHub.
This commit adds `PULLREQ_EDITMSG` to the list of markdown file-types.
[^1]: https://github.com/github/hub
[^2]: https://github.com/github/hub/blob/c8e68d548a39ec0fab6f674a669c21b54d4eec61/commands/pull_request.go#L225
=> Use markdown language for hub pull-request files

helix-term/src/commands.rs
=> Fix selecting a changed file in global search

book/src/generated/lang-support.md, languages.toml, runtime/queries/sage/highlights.scm, runtime/queries/sage/injections.scm, runtime/queries/sage/textobjects.scm
Hi this is my first contribution to this project. I copied the structure from: https://github.com/helix-editor/helix/pull/2903
The goal of this PR is to add support for the [sagemath](https://www.sagemath.org/) language. 
- The syntax is based on python.
- I didn't succeed at running the python language server by default with `.sage` files.
- It would be nice if  the syntax highlighting supported sage's docstrings:  In a comment, the lines starting with `sage: ` contain sage code. It would be nice if its syntax were highlighted. For an example of a docstring, see: https://doc.sagemath.org/html/en/developer/coding_basics.html#template
=> Support sagemath language

helix-loader/src/config.rs, helix-loader/src/lib.rs, helix-view/src/theme.rs, xtask/src/helpers.rs, xtask/src/themelint.rs
Unblocks #5656
Just a small fix since that function was removed.
I found the usage of `std::fs::read` instead of `std::fs::read_to_string` odd anyway.
Sadly there is no `include_str!` macro so we have the conversion ourselves (not a big deal regardless).
=> Switch from toml::from_slice to toml::from_str

runtime/themes/sonokai.toml
Without styling the primary and secondary selections differently, it's
impossible to tell them apart when cycling through selections.
Make the primary selection slightly brighter and secondary selections
slightly paler.
=> Sonokai theme: style secondary selections differently

contrib/Helix.appdata.xml, docs/releases.md
For #5624.
In the future when new release is out we should add 
```xml
<release version="23.12" date="2004-12-07" />
```
or maybe even something like
```xml
<release version="23.12" date="2004-12-07">
<description>
<p>"X = 'extend_line_above'" is now the default!</p>
</description>
<url>https://helix-editor.com/news/release-23-12-highlights/</url>
</release>
```
=> Add Appstream metadata file

book/src/generated/lang-support.md, languages.toml
According to the [V Language Server Repository README](https://github.com/vlang/vls#via-v-cli-recommended), the recommended way to install the V Language Server is via the `v` CLI. Therefore, the default config should expect it to be called by using `v ls` not `vls`.
=> Change default language server for 'v' from 'vls' to 'v ls'

languages.toml
cuelsp does not support formatting.
Cue language support was added to Helix before "formatter" was available.
References:
https://github.com/helix-editor/helix/pull/3262
https://github.com/dagger/cuelsp/issues/44
=> add explicit formatter for cue

runtime/queries/nix/injections.scm
- queries/nix: document existing injections subjects
- queries/nix: add injection for writeCBin nixpkgs trivial builder
- queries/nix: add injections for nix builtins
- queries/nix: add injections for nixpkgs writers
=> queries/nix: add injections for builtins and writers

helix-view/src/editor.rs
=> Parse gutter-types as Strings

helix-loader/src/config.rs, helix-loader/src/grammar.rs, helix-term/src/ui/menu.rs, helix-term/src/ui/picker.rs, helix-tui/src/buffer.rs, helix-view/src/theme.rs
This is my first commit using Rust and to Helix, so I hope to be useful :smile:
=> Fix clippy 1.67 warnings

runtime/tutor
I noticed while running the tutor that the logo in the tutor was a little out of sync on with the logo on the website and in the repository. I adjusted the letter proportions and added the helix icon to the logo. Lemme know what y'all think. Happy to change it however folks like or delete PR if no changes wanted!
Screen shot of the proportion fitting:
Screenshot in running helix:
=> Update tutor logo

helix-term/src/commands/typed.rs
This PR changes to use the `filename` completer on the `run-shell-command` typed command. With the current completer:
- I find myself having to type out the filename myself most of the time anyways when using `sh` for file operations like `chmod` and `rm`; 
- One would have to manually append `/` to get new completions for the next directory level, which is sub-optimal.
Switching to use `filename` conveniently solves both issues.
=> Use filename completer on run-shell-command

Cargo.lock, helix-core/Cargo.toml, helix-loader/Cargo.toml, helix-term/Cargo.toml, helix-view/Cargo.toml, xtask/Cargo.toml
[breaking changes](https://github.com/toml-rs/toml/blob/57c9bb07f45303626fc44bdb9a8721d27591123e/crates/toml/CHANGELOG.md#070---2023-01-27) don't seem to have any effect for helix
=> build(deps): bump toml from 0.6.0 to 0.7.0

helix-lsp/src/client.rs, helix-term/src/commands.rs, helix-term/src/commands/lsp.rs, helix-term/src/keymap/default.rs
Adds "goto declaration" support in the LSP client and defines a command to invoke it which is by default bound to `g D`.
=> Support goto-declaration LSP command

runtime/themes/onedark.toml
ui.highlight is used in hightlighting lines in the picker preview. Also change the grey shade of the secondary selections to not obstruct comment text (earlier the bg of secondary selections and fg of comments were the same).
Fixes #5750.
=> theme(onedark): Add ui.highlight scope

runtime/themes/ayu_evolve.toml
Add ayu_evolve theme
An even darker 😈 version of ayu that leverages many of the newer theming features.
Differentiates:
* Primary non-primary selection
* Primary cursor between modes
- Primary: Orange, Insert: Green, Select: Purple
* Variable members
* Inline raw markdown
* Strings and constructors
* Built in types
* Storage keywords
* Diagnostic underline color by type
* `ui.text.inactive` from #5104
=> Add ayu_evolve theme

helix-core/src/syntax.rs
The purpose of the RefCell in this change is to remove the mutable self borrow on `HighlightIterLayer::sort_key` so that we can sort layers with the correct ordering using the `Vec::sort` function family. `HighlightIterLayer::sort_key` needs `&mut self` since it calls `Peekable::peek` which needs `&mut self`. `Vec::sort` functions only give immutable borrows of the elements to ensure the correctness of the sort.
<details><summary>I thought we could use an eager Peekable but it won't work in practice...</summary><br>
I tried an eager version of Peekable (reads the peeked element eagerly on `new` and `next`):
```rust
struct EagerPeekable<I: Iterator> {
iter: I,
peeked: Option<I::Item>,
}
impl<I: Iterator> EagerPeekable<I> {
fn new(mut iter: I) -> Self {
let peeked = iter.next();
Self { …
```
=> Fix initial highlight layer sort order

helix-term/src/commands.rs
This change makes `ms<ret>` work similarly to `t<ret>` and related find commands: when the next event is a keypress of Enter, surround the selection with the document's line-endings.
=> Surround with line-endings on `ms<ret>`

helix-core/src/shellwords.rs
If the last argument to shellwords ends in a multibyte utf8 character the entire argument will be dropped.
e.g. `:sh echo test1 test2𒀀` will only output `test1`
=> Fix utf8 length handling for shellwords

book/src/configuration.md, helix-term/src/commands.rs, helix-term/src/lib.rs, helix-term/src/ui/mod.rs, helix-view/src/editor.rs
Fixes #5395
Fixes  #5725
Fixes #5210
This PR adds a config option to the picker to hide symlinks that point into the root directory of a picker.
These symlinks always point at files that would be included in the picker anyway and are therefore essentially duplicate.
The config option is enabled by default.
While working on this I noticed some small issues with the existing handling around symlinks.
They were included in the file picker if `follow-links` was disabled (which seems really odd, `global_search` already handled this correctly). Also added documentation for `follow-links` since that seems to have been missed.
Edit: The fix for filtering symlinks from the picker I described in the last paragraph more generally filters all kinds of "non standard" files like pipes, block devices, …
=> Hide duplicate symlinks from the picker

helix-term/src/ui/document.rs
Fixes #5782
The new rendering code added in #5420 performs char_idx -> visual_pos translations on the fly for performance reasons. This code needs a special case for the EOF character as that character is not a real char_idx in the text (it's rendered as virtual text but virtual text normally doesn't have a separate char_idx). When softwrap is enabled the view may be offset multiple visual lines from the start of the line. That means that any position needs to have a vertical offset applied (`pos.row -= row_offset`). This is always done for all graphemes that get actually rendered but because the EOF position takes a specical branch (only used for position translation) it needs to be done there too (which was missed so far).
=> fix position translation at EOF with softwrap

helix-term/src/commands.rs
Arranges the document id, file flags (is-modified, is-current) and file path in a table leveraging https://github.com/helix-editor/helix/pull/3053.
| --- | --- |
| ![before][1] | ![after][2] |
[1]: https://user-images.githubusercontent.com/23398472/216238043-ac5fa30d-7865-4127-9d7b-96a56d01c294.png
[2]: https://user-images.githubusercontent.com/23398472/216238080-f4a824e3-9964-4bec-b385-a2357ee23777.png
=> Tabulate buffer picker contents

helix-term/src/ui/menu.rs
Related to issue https://github.com/helix-editor/helix/issues/4963
When in insert mode, when a completion menu is up, `C-k` (kill to end of line) and `C-j` (insert newline) are overwritten by navigation within completion menu. I see that something similar was the case for pickers at one point, https://github.com/helix-editor/helix/pull/1792, and the solution was to remove said bindings. 
This PR will help to resolve these conflicts as well as making navigation within pickers and completion menus more similar.
=> Resolve conflicts between insert mode and completion menu bindings

helix-term/src/commands.rs
Slightly different take for https://github.com/helix-editor/helix/issues/3014, looking for feedback
=> add picker: current view dir

book/src/configuration.md, helix-term/tests/test/auto_indent.rs, helix-term/tests/test/helpers.rs, helix-view/src/clipboard.rs, helix-view/src/editor.rs
I had had this code sitting around in a branch I'm working on already before #4391 became necessary in order to turn off LSP for the integration tests. It slows them down and is totally unnecessary until we figure out a good way to do integration tests with real language servers.
I'm making this PR as a proposed different way to approach this, where this is generalized into a user config option exposed to the user. I figure that while my motivation for this was reducing noise in the integration tests, this could conceivably be desirable by some users without having to e.g. compile out LSP integration with a feature flag.
Another benefit is that when we do get to integration tests around LSP, we won't need to manually specify a language config; we'll just need to set this one boolean …
=> Provide option to completely disable LSP

helix-term/src/commands.rs, helix-term/src/commands/typed.rs
Fixes #5733
This PR ensures that the cursor is in view and that any changes are appended to history when using typeable commands instead of keybindings. If changes are not saved to history crashes can occur later. For example the reproduction case for #5733 uses middle mouse to trigger the `:clipboard-paste-before` command which causes the undo command to produce a crash later. 
While looking into a fix, I noticed that `ensure_cursor_in_view` was also not being called. When the cursor is at the EOF (`vgegl`) of a large file and replaced with a very short string from the clipboard the view currently becomes empty (no visible text or line numbers). That second bug is fixed by adding the `ensure_cursor_in_view` call.
=> Ensure history is completed and cursor is in view after pasting

runtime/themes/jellybeans.toml
I missed the Jellybeans theme so I created this, based on the original Vim theme : https://github.com/nanotech/jellybeans.vim
=> Add Jellybeans theme

languages.toml, runtime/queries/sql/highlights.scm
Diff: https://github.com/DerekStride/tree-sitter-sql/compare/4fe05b2d81565ddb689d2f415e07afdacc515c52...286e10c5bc5d1703ee8f9afb351165a9a6182be1
- [Default values in Column Definitions](https://github.com/DerekStride/tree-sitter-sql/commit/e2f0f3f74dbc4c2f77a8a85bd8e5599fa248a7ec)
- [Detect empty comments](https://github.com/DerekStride/tree-sitter-sql/commit/bca2ad23df7a662e9050474e0170cc13c000f7ec)
- [Allow for nested joins](https://github.com/DerekStride/tree-sitter-sql/commit/bb58ae16e62e8ad252a4359d54191257892f0acc)
- [Parse more functionality of the `CREATE TABLE` statement](https://github.com/DerekStride/tree-sitter-sql/commit/286e10c5bc5d1703ee8f9afb351165a9a6182be1)
- Update to current `tree-sitter-sql` `main` `HEAD`.
- Migrate grammar to match …
=> feat: Update `tree-sitter-sql` and migrate `highlights.scm` to match grammar

book/src/generated/lang-support.md, languages.toml, runtime/queries/msbuild/highlights.scm, runtime/queries/msbuild/indents.scm, runtime/queries/msbuild/injections.scm
Filetype reference: https://stackoverflow.com/questions/2007689/is-there-a-standard-file-extension-for-msbuild-files
#5754
=> Add MSBuild language based on XML grammar

book/src/generated/typable-cmd.md, helix-term/src/commands/typed.rs, helix-term/tests/test/commands.rs
This is my take on Vim's get ascii (<kbd>g</kbd><kbd>a</kbd>) / get utf8 (<kbd>g</kbd><kbd>8</kbd>) command. This works on graphemes not characters, so it correctly handles things like emoji with skin tone modifiers or characters with combining diacritics.
I'm open to opinions on what the output should look like. Atm, it outputs the decimal value only for single byte characters in an ascii-compatible encoding. For UTF-8, it also prints the decoded codepoints. (The decoder is based on [fasterthanlime's article](https://fasterthanli.me/articles/working-with-strings-in-rust) since I could not find anything in std or already in helix, or on crates.io for that matter, and it's pretty concise).
| Character | Encoding | Output |
|-|-|-|
| a | UTF-8 | `"a" (U+0061) Dec 97 Hex 61` |
| a | …
=> Add :character-info command

languages.toml
These file types are used with [CocoaPods](https://cocoapods.org) – a dependency manager for Swift and Objective-C Cocoa projects. They should be recognized as ruby files. 
Here is the page from their wiki: https://github.com/CocoaPods/CocoaPods/wiki/Make-your-text-editor-recognize-the-CocoaPods-files
=> Add Podfile and *.podspec to the file types for ruby

.cargo/config.toml, Cargo.toml, helix-term/src/application.rs, helix-term/tests/test/write.rs
This will allow testing more of the code base, as well as enable UI- specific testing.
Debug mode builds are prohibitively slow for the tests, mostly because of the concurrency write tests. So there is now a profile for integration tests that sets the optimization level to 2 for a few helix crates, and lowers the number of rounds of concurrent writes to 1000.
=> enable rendering in integration tests

languages.toml
.C, and .H and two more valid cpp source and header types. Note the capitalization, as opposed two .c, and .h for c files.
I also found a source that mentions the extensions multiple different compilers support https://stackoverflow.com/a/3223792
=> Recognize .C and .H file types as cpp

runtime/themes/fleet_dark.toml
The current palette for the theme didn't use the official palette, and some scopes used the wrong colors. The contrast between the cursorline and comments also caused eye strain.
I copied the palette from `dark.json` in the themes folder, and reworked the theme to reflect the official one. I'm a bit displeased with the color for `type.enum.variant`, which the official theme doesn't highlight, as well as the contrast between `variables.builtin` and the background (for which I preferred the old color).
Fleet vs. `new fleet-dark` (top) vs. `old fleet-dark` (bottom)
---
updated `fleet-dark`'s palette to be identical to the one in the official theme
=> Make `fleet-dark` accurate to the official theme

helix-term/src/commands.rs
This matches the behavior from #4713 but for the first and last change. The selection rules are the same as for goto_next/prev_change: additions and modifications select the added and modified range while deletions are represented with a point.
=> Select change range for goto_first/last_change commands

helix-core/src/movement.rs
The loop always iterates the number of times the user specified even if the beginning/end of the document is reached.
For an extreme demonstration try the following commands, Helix will hang for several seconds.
100000000w
100000000]c
=> Short-circuit the word and treesitter object movement commands

languages.toml
I have to often deal with these files, so I'm adding them here.
- `.mobileconfig` files are configuration profiles for Apple devices.
- `.plist` is just another format created by Apple, although `.plist` files can also have binary data instead of XML.
=> xml: add mobileconfig & plist file types

book/src/generated/lang-support.md, languages.toml, runtime/queries/pem/highlights.scm
This merge request adds support for PEM files. I'm not sure whether this sort of less commonly editied filetype is something we'd like to support out of the box, but I've been working with PEM files pretty frequently recently, so I figured I'd suggest adding support. Here's a screenshot with the nord theme:
=> feat: add pem language

languages.toml
The `Containerfile` is a vendor independent name for the `Dockerfile` when using things like `podman`. It has the same syntax and therefore it is possible to extend the `file-types`.
But I am not sure whether it would be better to define a different language with the same parameters. It would better show being vendor independent but also a bit more bloat.
Further I am not sure why there is a lowercase `dockerfile` in the `file-types` and if it is also needed for the `Containerfile`.
=> Add `Containerfile` file-type for dockerfile language

.github/workflows/build.yml, .github/workflows/msrv-rust-toolchain.toml, helix-term/src/commands.rs, helix-term/src/compositor.rs, helix-term/src/job.rs, helix-term/src/lib.rs, helix-term/src/ui/editor.rs, helix-term/src/ui/menu.rs, helix-term/src/ui/picker.rs, helix-term/src/ui/prompt.rs, rust-toolchain.toml
Firefox 109 was released with a MSRV of 1.63.
In accordance with the MSRV policy this PR bumps the MSRV to 1.63.
Fixes #1557
Fixes #5432
=> bump msrv to 1.63

helix-core/src/line_ending.rs, helix-core/src/transaction.rs, helix-lsp/src/client.rs, helix-lsp/src/lib.rs
Fixes #4791
Fixes #3286
Fixes #2547 
Fixes #5809
I started to thoroughly investigate the char_pos <-> lsp_pos conversion in an effort to fix #4791. Initially I just started with the suggestion by @the-mikdavis of capping the `character` offset to the line length. While this is only mentioned offhand in the LSP standard, it's still part of the standard and seems a good precaution against crashing from broken LSPs.
This fixed the original panic but caused panics and weird formatting bugs for slightly different json files. So I investigated further and found a pretty mayor bug: Helix implemented the `UTF-8` encoding incorrectly:
Currently, helix treat the `Position::character` field as a char offset in `Utf-8` mode and as `utf16` offset in UTF-16 mode. This is incorrect, the …
=> properly handle LSP position encoding

helix-term/src/commands.rs, helix-term/tests/test/commands.rs
Example:
```
test
testitem
```
Select line 2 with x, then type Alt-C; Helix will go into an infinite loop. The saturating_sub keeps the head_row and anchor_row pinned at 0, and a selection is never made since the first line is too short.
=> Fix the infinite loop when copying the cursor to the top of the file

helix-core/src/comment.rs, helix-core/src/increment/integer.rs, helix-core/src/indent.rs, helix-core/src/syntax.rs, helix-lsp/src/client.rs, helix-term/src/commands.rs, helix-term/src/lib.rs, helix-term/src/ui/document.rs, helix-term/src/ui/editor.rs, helix-term/src/ui/fuzzy_match.rs, helix-vcs/src/git/test.rs, helix-view/src/base64.rs, helix-view/src/clipboard.rs, helix-view/src/document.rs, helix-view/src/gutter.rs, helix-view/src/input.rs, helix-view/src/view.rs, xtask/src/themelint.rs
With the MSRV raised to 1.63 we can now resolve all clippy lints that showup with 1.67. These new lints are actually improving the code (instead of just being false positives/pedantic like some other lints) so it seemed worth it to include the fixes. Particularly in #5420 I missed alot of unnecesary `usize` casts (so `usize` -> `usize`), because I changed types of some variables while working on that.
=> Fix new clippy lints

helix-term/src/commands.rs
Closes https://github.com/helix-editor/helix/issues/5716 (last pr here https://github.com/helix-editor/helix/pull/5885)
Added the actual exit code to the `Shell command failed` message to be less ambiguous. Main reason is because some commands still succeed with exit codes other than 0.
Thx @CptPotato for the explanation. 👍
=> Add exit code to command failed msg

Cargo.lock, helix-lsp/Cargo.toml, helix-lsp/src/client.rs, helix-lsp/src/lib.rs, helix-term/src/commands/lsp.rs
So far LSP always required that `PositionEncoding.characters` is an UTF-16 offset. Now that LSP 3.17 is available in `lsp-types` request the server to send char offsets (UTF-32) or byte offsets (UTF-8) instead. For compatability with servers that don't support other encodings, UTF-16 is used as a fallback as required by the standard.
=> Negotiate LSP Position Encoding

helix-term/src/ui/completion.rs
Refactor the logic for rendering completion documentation popup. The changes include using an early return, renaming some variables (overshadowing `area`, `height`, etc tends to be confusing) and making some area calculations more readable. Most importantly this PR also contains a fix for preventing the rendering of the completion doc popup over the completion popup itself and to not draw over the cursor.
| --- | --- |
| ![before][1] | ![after][2] |
[1]: https://user-images.githubusercontent.com/23398472/216852789-05edb90f-68c9-4b9e-9da3-c8002dc5bad0.png
[2]: https://user-images.githubusercontent.com/23398472/216852784-92bdccf7-a130-40c9-99be-021955522d64.png
---
Each commit does a single refactor and the last commit contains the bug fix (The full diff across all the …
=> Refactor completion doc popup and fix positioning

languages.toml
`hosts` file uses `#` character as a comment token.
[hosts(5)](https://www.man7.org/linux/man-pages/man5/hosts.5.html)
=> Add comment-token to the hosts language definition

helix-core/src/comment.rs
Open a new document `test.rs` and type the following: `di//<esc><C-c>`
The margin calculation pushes the range out of bounds for the comment marker when there are no characters (newline) after it.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char range out of bounds: char range 0..3,
Rope/RopeSlice char length 2', ropey-1.6.0/src/rope.rs:546:37
The debug build catches the error in the transaction: thread 'main' panicked at 'attempt to subtract with overflow',
helix-core/src/transaction.rs:503:26
=> Prevent a panic when uncommenting a line with only a comment token

book/src/generated/typable-cmd.md, helix-term/src/commands/typed.rs
This command toggles the value of boolean options. `:toggle key`
Mostly useful for custom keybindings to toggle settings such as `smart_case`, or `cursorline`.
Closes #2849
=> Add :toggle-option command

helix-lsp/src/client.rs, helix-term/src/ui/completion.rs
Mark deprecated completions using strike-through (CROSSED_OUT modifier). The deprection information is taken either from the `deprecated` field of the completion item or from the completion tags.
The `deprecated` field seems to be the older way of passing the deprecated information and it was already marked as deprecated for `Symbol`. In `CompletionItem` the `deprecated` field is still valid but it seems that the LSP is moving in the general direction of using tags for this kind of information and as such relying on tags as well seems reasonable and future-proof.
=> feat(ui): deprecated completions

book/src/keymap.md
Small clarification that "space" refers only to space inserted between joined lines.
=> docs: clarify `join_selections_space`

helix-term/src/commands.rs
Fixes #5965
Reverts a small change from #5892 that caused crashes at the EOF.
`std::cmp::clamp` crashes when `max < min` which was the case at the EOF.
By using `max(..).min(..)` directly we ensure that the `min` always takes predence and avoid the crash.
In the other place where `min/max`  was replaced with `clamp` in #5892 it is impossible for `max < min` to occur
and therefore didn't need to be reverted.
=> Fix crash in goto_window_center at EOF

runtime/themes/monokai.toml
Fixes #5961
I originally assumed that this was a regression introduced by #5420 (which it technically is). In that PR the picker highlight was changed to be rendered in the background (behin text) instead of in the forground. This was mostly an oversight, because rendering in the background is the default with the new line decoration API.
However upon investigating further I found this to be consistent with other similar highlights like:
* Buffer line
* Buffer column
* Current DAP frame
The only thing that is really rendered in the foreground is the selection (which uses the syntax highlighting API). All of this is for good reason because otherwise these overlays would hide the cursor/selection. Therefore I think its more consistent to keep the same behavior for the picker highlight too. …
=> Remove text bg from monokai

languages.toml
`.env.dist` files are distributed `.env` files without secrets /  `.env`-templates.
These are not currently highlighted by Helix.
This PR adds them to the `source.env` scope, alongside other common `.env.*`.
=> Add `.env.dist` to `source.env` language scope

helix-term/src/ui/completion.rs
The completion component has a separate branch for handling the Escape key but it can use the `ignore_escape_key` helper added for signature-help instead (#1755).
This should not cause a behavior change - it's just cleaning up the completion component.
=> Use Popup::ignore_escape_key helper for completion

helix-lsp/src/client.rs, helix-lsp/src/jsonrpc.rs, helix-lsp/src/lib.rs
This improves error logging for requests - without the ID it's hard to know which request is the one that timed out.
This is helpful for debugging #5958 for example.
=> LSP: Add request ID to request timeout message

helix-term/src/ui/menu.rs
Fixes #2017
This PR changes the fuzzy matching in the completion menu to be always case insensitive.
We never really documented that it used smart casing and I don't think that is actually desirable here.
A common use-case for competitions is mistyping/misremembering an identifier and using autocomplete to fixup that problem. For that use-case case sensitive matching is actually detrimental. Other editors like nvim/vscode/intellij also seem to always use case insensitive auto completions.
Note that the original reproduction case from #2017 already seems to work:
However after this fix the following also works which doesn't work on master (see screenshot)
Note that we rank completions by their fuzzy matching score which gives a penalty for case mismatch in case ignore case is enabled soo …
=> ignore case while filtering completions

helix-term/src/application.rs
This PR changes a call to `unwrap()` to `match`. Currently the editor crashes when the LSP publishes diagnostics with an unsupported URI. With this PR it simply ignores them.
Submitting this patch because the [Cairo language server](https://github.com/starkware-libs/cairo/tree/main/crates/cairo-lang-language-server) crashes Helix when it sends a file URI like `vfs://xxxxxx` where `vfs` refers to the internal in-memory file system of the Cairo language server.
I'm not sure if this is considered a bug of the Cairo lang server as I don't know for sure if schemes other than `file` is allowed. But in any case I think we shouldn't panic here.
=> Ignore invalid file URIs from LSP

runtime/themes/pop-dark.toml
- had to update the gutter, looks now cleaner with the line numbers having the same background as the rest of the gutter.
- also updated the line highlight to make it softer
- also made the background for code blocks in markdown less strong
- and a few simple color adjustments
- unified the usage of `"`, `'` to `'` only
=> feat(theme) pop-dark adjustments and clean up

helix-core/src/indent.rs, helix-core/tests/indent.rs, helix-term/src/commands.rs, helix-view/src/document.rs
Previously, we used sometimes `doc.indent_style` and sometimes `doc.language_config.indent`. This caused some issues if they differ (e.g. if a non-default indent style is auto-detected in a document or manually set). For example, in a markdown file, setting `:indent-style 8` and then continuously pressing enter (starting on an indented line) increases the indent each time. This happens because the indent_style used to detect the indentation level of an existing line is different from the indent_style used to convert an indentation level to a string. The same issue occurs in any language without indent queries.
With these changes, `language_config.indent` is only used to initialize `doc.indent_style` and afterwards ignored. Resolves #2236 and #3406.
=> Unify usage of indent_style

book/src/generated/typable-cmd.md, helix-term/src/commands/typed.rs, helix-term/src/ui/statusline.rs, helix-view/src/document.rs
The command `:set-language` and `:lang` now behaves like `:theme`, as mentioned [here](https://github.com/helix-editor/helix/discussions/5847#discussioncomment-4883555).
- Should the default value "text" be used, like in the statusline, maybe define a constant?
- I expected `:language` to work, is there any reason against adding it as an alias?
=> Show current language when no argument is provided

helix-dap/src/client.rs, helix-dap/src/lib.rs
This improves error logging for dap requests - without the ID it's hard to
know which request is the one that timed out, just like [6010](https://github.com/helix-editor/helix/pull/6010).
=> DAP: Add request ID to request timeout message

flake.nix
This allows easily (re)making helix (wrapped) from an overriden helix-unwrapped derivation, e.g. if one wanted to patch helix from nix:
```nix
helix.passthru.wrapper (helix-unwrapped.overrideAttrs (old: {
patches = old.patches ++ [ ./cargo-tree-sitter.patch ];
}))
```
I needed this to patch helix from my own nixos configuration flake after hitting #4862.
=> flake: pass helix' wrapper through

runtime/themes/ayu_evolve.toml
Reasoning explained in commit. The fault is mine from #5638 .
=> ayu_evolve theme: remove variable.other.member

book/src/generated/lang-support.md, languages.toml, runtime/queries/uxntal/highlights.scm
About [uxntnal](https://wiki.xxiivv.com/site/uxntal.html).
I'm also the author of the tree-sitter grammar, and it's not fully complete. I still think this is better than no syntax highlighting though.
=> Add support for the uxntal language

docs/CONTRIBUTING.md
Just a couple tips and tricks that @pascalkuthe gave on the [matrix server](https://matrix.to/#/!zMuVRxoqjyxyjSEBXc:matrix.org/$k9ILSGRe2Ohj7ZpL2FnLnd2LlllzCEEwlevB_h0k1bQ?via=matrix.org&via=mozilla.org&via=envs.net)
=> Expand contributing docs

helix-dap/src/client.rs, helix-dap/src/lib.rs, helix-dap/src/types.rs, helix-term/src/commands/dap.rs, helix-view/src/handlers/dap.rs
Send a `Disconnect` DAP request if the `Terminated` event is received. According to the specification, if the debugging session was started by as `launch`, the debuggee should be terminated alongside the session. If instead the session was started as `attach`, it should not be disposed of.
This default behaviour can be overriden if the `supportTerminateDebuggee` capability is supported by the adapter, through the `Disconnect` request `terminateDebuggee` argument, as described in
[the specification][discon-spec].
This also implies saving the starting command for a debug sessions, in order to decide which behaviour should be used, as well as validating the capabilities of the adapter, in order to decide what the disconnect should do.
An additional change made is handling of the `Exited` …
=> feat(dap): send Disconnect if Terminated event received

helix-term/src/commands/dap.rs
Check if the stack frames contain the thread id and the frame before trying to get the frame id. If case any of the two fails to be found, provide the user with messages to inform them of the issue and gracefully return.
Closes: #5625
Signed-off-by: Filip Dutescu <filip.dutescu@gmail.com>
=> fix(dap): validate key and index exist when requesting vars

book/src/generated/lang-support.md, languages.toml, runtime/queries/yuck/highlights.scm, runtime/queries/yuck/injections.scm
Adds syntax highlighting support for yuck (DSL for eww). The parser should be complete now and closely follows the original lalrpop parser in eww.
=> Added yuck language support (for eww)

flake.lock, flake.nix, helix-term/Cargo.toml
Rewrites most of the flake so that it uses `flake-parts` and the new NCI. Should be a lot more cleaner now
=> build(nix): update flake to use flake-parts and nci flake-parts module

languages.toml, runtime/queries/markdown.inline/injections.scm, runtime/queries/markdown/highlights.scm
* Changes some nodes from `punctuation.delimiter` to `punctuation.special` which is more accurate in regards to highlighting.
* Updates markdown grammar to newest commit
* Adds language injection for newly added `latex_block` node
=> Improve markdown highlights and add latex injection

book/src/generated/lang-support.md, languages.toml, runtime/queries/sway/highlights.scm, runtime/queries/sway/indents.scm, runtime/queries/sway/injections.scm, runtime/queries/sway/locals.scm, runtime/queries/sway/textobjects.scm
Adds language support for the [sway](https://github.com/FuelLabs/sway) smart contract programming language using [tree-sitter-sway](https://github.com/FuelLabs/tree-sitter-sway/).
=> Add language support for sway

book/src/generated/lang-support.md, languages.toml, runtime/queries/nasm/highlights.scm, runtime/queries/nasm/injections.scm, runtime/queries/nasm/textobjects.scm
This pull request adds nasm assembly as a language.
Closes #3329.
Under the issue mentioned above, there is a discussion about how to support various assembly flavours. I think the best approach is to add flavour-specific language definitions with the appropriate grammars, then users can override the `file-types` values as desired in their local `languages.toml` files so that the `.asm` extension (or whichever extension they're using) is recognized as the flavour that they're working with. Since nasm will be the only flavour supported so far after the changes in this merge request, I've included the `.asm` extension under nasm's `file-types` so that there is at least _some_ syntax highlighting out of the box, even though it might not be for the right flavour. If there's a different …
=> feat: add nasm language

book/src/generated/lang-support.md, runtime/queries/elm/textobjects.scm
Fixes #6083 
This is a first (naive) attempt at adding treesitter text objects for the elm language.
To test this out, copy the [textobjects.scm](runtime/queries/elm/textobjects.scm) file to your runtime folder in `runtime/queries/elm` and restart helix.
To find where your runtime folder is, use `hx --health | grep runtime`.
It should now allow you to select
- the code of function with `mif`
- the function itself with its optional type annotation with `maf`
- a function parameter with `mia` or `mac`
- a line of block comment with `mic` or `mac`
And you can navigate with the same text objects, so
- previous or next function with `[f` or `]f`
- previous or next parameter with `[a` or `]a`
- previous or next comment with `[c` or `]c`
=> Add elm treesitter textobjects

runtime/themes/catppuccin_mocha.toml
The current behavior sets the foreground color, and this is very difficult to read. Instead, only the underline itself should be a different color.
=> Fix diagnostic underline colors in catppuccin themes

runtime/themes/adwaita-dark.toml
Added Gnome adwaita dark theme. Colors are taken from `gtksourceview5`
=> theme: Add Adwaita Dark

book/src/keymap.md
Refs #3705
This change is mainly whitespace, and two new lines to document the missing `<space>-h` and `<space>-g` keymaps.
=> book: Document <space>h and <space>g

Cargo.lock, book/src/keymap.md, helix-term/Cargo.toml, helix-term/src/application.rs, helix-term/src/keymap/default.rs, helix-term/src/ui/prompt.rs, helix-tui/Cargo.toml, helix-tui/src/backend/crossterm.rs, helix-view/Cargo.toml
See the Kitty documentation on this: https://sw.kovidgoyal.net/kitty/keyboard-protocol/
Key events given by the terminal are limited by default: the terminal confuses keycodes like C-i and tab and can't tell the difference between backspace and S-backspace or ret and S-ret. We can detect support for an enhanced keyboard protocol and enable that protocol to be able to disambiguate these keys on terminals which support the protocol.
Closes https://github.com/helix-editor/helix/issues/3725
Closes https://github.com/helix-editor/helix/issues/3210
Closes https://github.com/helix-editor/helix/issues/1085
Closes https://github.com/helix-editor/helix/issues/5765
=> Enable progressive keyboard enhancement protocol

helix-term/src/application.rs
Since crossterm 0.26.x, we receive press/release keyboard events on Windows always. We can ignore the release events though to emulate the behavior of keyboard input on Windows on crossterm 0.25.x.
Fixes #6133
=> Ignore key-release keyboard events

helix-term/src/ui/document.rs
Closes #6134.
This is my first contribution and I'm honestly surprised at how quick I was able to implement the fix.
Criticism is welcome - I don't know what I'm doing xD
=> Fix indentation lines (#6134)

.github/workflows/cachix.yml
This fixes an issue with installing Nix 1.14 which causes the cachix/cachix-action in the next step to fail.
See https://github.com/cachix/install-nix-action/issues/161
=> CI: Update cachix/install-nix-action to v20

helix-term/src/ui/text.rs
Helix crashed when I cut the window too much.
```
thread 'main' panicked at 'attempt to divide by zero', helix-term/src/ui/text.rs:61:23
stack backtrace:
0: rust_begin_unwind
at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
1: core::panicking::panic_fmt
at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
2: core::panicking::panic
at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
3: helix_term::ui::text::required_size
4: <helix_term::ui::markdown::Markdown as helix_term::compositor::Component>::required_size
5: <helix_term::ui::popup::Popup<T> as helix_term::compositor::Component>::required_size
6: <helix_term::ui::popup::Popup<T> as helix_term::compositor::Component>::render
7: …
```
=> Fix 'attempt to divide by zero' panic

helix-view/src/view.rs
Fixes #6141
Fixes a regression introduced in #5420 where a scrolloff of `x - 1` was used instead of `x` at the bottom of the screen (but not at the top). This was especially problematic if the scrolloff was set to `0` in that case the scrolloff behaved as tough set to `-1` and the cursor disappeared from the view if scrolled to the bottom (see #6141).
=> Fix scrolloff at view bottom

book/src/generated/lang-support.md, languages.toml, runtime/queries/prql/highlights.scm, runtime/queries/prql/injections.scm
Adds support for PRQL languange. 
I hope I added everything thats necessary to add language support. 
Closes #6050
=> feat(prql): add prql support

helix-term/src/application.rs
Since https://github.com/helix-editor/helix/commit/79bf5e3094e16a34637703b14c7bf090d2dcf155 `C-z` and `fg` has taken 2 seconds for me. This small change fixes that.
=> fix: Handle signals before crossterm events

runtime/themes/papercolor-dark.toml, runtime/themes/papercolor-light.toml
Using the picker with syntax highlighting the
fallback `ui.selection` makes a lot of text,
especially for the light variant, hard to read.
Instead, use a lighter background for highlights
=> Theme: Papercolor: Add ui.highlight

.github/workflows/build.yml, Cargo.lock, helix-term/Cargo.toml, helix-term/src/commands.rs, helix-term/src/ui/document.rs, helix-vcs/Cargo.toml, helix-vcs/src/git.rs, rust-toolchain.toml
Updates MSRV to 1.65 per our policy.
Ubuntu has finally followed their own policy and updated rustc to 1.65 so this should now be uncontroversial and not cause any problems.
This PR includes #6065 (with permission from @Byron) to update gix and the usual update of the CI, `rust-toolchain.toml` and resolving of MSRV related TODOs (clippy lints were resolved in #5892)
Note that the large diff is caused by `Cargo.lock` changes mostly from renaming all the `gitoxide` subcrates from `git-..` to `gix-..` and gitoxide dropping dependencies (caused by reviews from the cargo people, as gitoxide is now used in `cargo`)
=> Raise MSRV to 1.65

helix-term/src/commands.rs
Removed `align_view` calls from `goto_*_diag` as per issue #6177
=> Remove centering view from Unimpaired commands

helix-dap/src/client.rs, helix-dap/src/types.rs, helix-term/src/commands.rs, helix-term/src/commands/dap.rs, helix-term/src/keymap/default.rs
Add a restart debug session command, which would issue a [Restart Request][1], if the debugger supports it and a session is running. It uses the same arguments and requests used to start the initial session, when recreating it.
It builds upon #5532, making use of the changes to the termination workflow of a session.
[1]: https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Restart
Closes: #5594
Signed-off-by: Filip Dutescu <filip.dutescu@gmail.com>
=> feat(dap): implement Restart request

book/src/languages.md
This is a slight addition that explains what the `tab-width` and `unit` subkeys refer to in `languages.toml`. You can figure this out by reading the default configuration, but I thought it would be useful to make it more explicit.
I didn't see any commit style guidelines; let me know if anything needs to be changed.
=> docs: describe tab-width and unit subkeys

runtime/themes/onelight.toml
Reset the keyword section to complete most of the highlighting colors.
wiki has update.
=> Update onelight theme

runtime/themes/pop-dark.toml
After reading today through the updated docs i found and ran the `cargo xtask themelint`...
This fixes the issues around `ui.statusline.<MODE>`.
by adding the three missing keys for the `color-modes`-option.
=> feat(theme): Update pop-dark for color-modes

Cargo.lock, Cargo.toml
Tree-sitter has some unreleased improvements that can speed up small queries and prevent hangs due to error recovery in some parsers. This change pins tree-sitter to the latest master.
Neovim also pins tree-sitter to a commit on master.
(Distributions could decide to ignore this patch if they don't allow git revisions - there are no changes in the Helix codebase that require the new changes to tree-sitter.)
Fixes https://github.com/helix-editor/helix/issues/4862
See https://github.com/tree-sitter/tree-sitter/pull/2085
=> Pin tree-sitter at git master

languages.toml, runtime/queries/php/highlights.scm
- update tree-sitter-php
- add basic types, operator
- refine keyword
=> Update highlight for PHP

Cargo.lock, Cargo.toml, helix-core/src/selection.rs, helix-lsp/Cargo.toml, helix-lsp/src/client.rs, helix-lsp/src/lib.rs, helix-lsp/src/snippet.rs, helix-parsec/Cargo.toml, helix-parsec/src/lib.rs, helix-term/src/ui/completion.rs
This PR adds a basic support for LSP completion snippet based on https://github.com/helix-editor/helix/tree/snippets.
A snippet is a bit different from a normal completion in that it contains tab stops/placeholders (ie `$1, $2 or ${3:foo}` and `$0` who is always the last one). A complete definition of the syntax can be found [here(https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#snippet_syntax). So when creating the transaction we parse the snippet input, create the output text with the correct indentation and create the selections for the placeholders.
This PR brings the support for snippet in a good state where only variable, placeholder removal and Tab/S-Tab support isn't implemented for the moment, those should be feasible but I didn't wanted …
=> Add basic support for LSP snippets

book/src/generated/typable-cmd.md, helix-term/src/commands.rs, helix-term/src/commands/typed.rs, helix-vcs/src/diff.rs, helix-vcs/src/diff/line_cache.rs, helix-vcs/src/diff/worker.rs, helix-vcs/src/diff/worker/test.rs, helix-view/src/gutter.rs
Closes #4974
Adds the `:reset-diff-change` command  (aliases `:diffg` and `:diffget`) that resets a hunk back
to its original text. 
This change requires exposing the `diff_base` (the file that a diff was computed against). To accommodate that I slightly refactored the terminology the `DiffHandle` and renamed the `FileHunks` struct to `Diff` as it doesn't just contains hunks anymore.
=> Add command for resetting diff hunks

Cargo.lock, helix-term/src/application.rs, helix-tui/Cargo.toml, helix-tui/src/backend/crossterm.rs, helix-tui/src/backend/mod.rs, helix-tui/src/backend/test.rs, helix-tui/src/terminal.rs
This is #6160 but in a way that is more extendable in the long-term. This will make it easier to add checks for other host terminal information like initial cursor shape, title line, whether the terminal supports synchronized output, etc. without adding a whole bunch of fields to Application or functions to the Terminal trait.
The first commit in this change moves `Application::claim_term` and `application::restore_term` to `helix-tui` into the crossterm backend. I believe this is the more proper place for this code and it makes the second change much easier: we cache whether the terminal supports the enhanced keyboard protocol, resolving #6149 (though it would stil be nice to improve this upstream).
=> Move terminal claim/restore to helix-tui, cache keyboard enhancement support query

helix-term/src/application.rs
Previously we did not respond to malformed or unhandled LSP requests. The JSONRPC spec says that all non-notification requests must have responses:
> When a rpc call is made, the Server MUST reply with a Response,
> except for in the case of Notifications
(Note that Helix is the "Server" in this case. Also from the spec: "The Server is defined as the origin of Response objects and the handler of Request objects.")
So this change sends error replies for requests which can't be parsed or handled. Request IDs are also now added to the log messages for unhandled requests.
Fixes #5958
=> LSP: Send replies for malformed and unhandled RPC requests

helix-term/src/commands/lsp.rs
This follows prior changes like #4713: we select the range given by the language server rather than the starting point.
=> Jump to symbol ranges in LSP goto commands

helix-term/src/ui/picker.rs
This fixes blank row text in a DynamicPicker which is initially given no options. This can happen for language servers which respond to the workspace symbol request for an empty query with an empty list of symbols, and that behavior is somewhat common since returning all symbols as the spec suggests is very expensive.
For empty options, `Picker::new` calculated the widths of each column as 0. We can recalculate the column widths when the new options are set to fix this. This refactor is also a good opportunity to formalize setting new options on a picker: besides setting the new options and calculating column widths we also want to reset the cursor and rescore the options.
Fixes #5920
=> DynamicPicker: Recalculate column widths for new options

helix-term/src/commands.rs, helix-term/src/commands/typed.rs, helix-view/src/editor.rs, helix-view/src/view.rs
Based on [this discussion](https://github.com/helix-editor/helix/discussions/5741). (@the-mikedavis)
This patch:
* Only appends to the jumplist when the `:<linenum>` invocation is accepted with <kbd>Enter</kbd> (`PromptEvent::Validate`).
* Fixes what appears to be a bug in the jumplist behavior where the `current` pointer points past the end of the list when it's appended to, resulting in a "dead" invocation of `C-o`. This caused issues with the previous implementation especially, as it would append to the list _twice_ implicitly during validate (since the movement logic previous lived outside the handler for the `PromptEvent::Update` event.
=> Do not add intermediate lines to jumplist with :<linenum> command.

runtime/themes/ayu_evolve.toml
Currently a bit hard to discern inactive and active buffers in a brighter environment.
Before:
After:
Apologies for the white borders in the screenshots.
=> Theme - auy_evolve: Up bufferline fg brightness

Cargo.lock, helix-term/src/commands.rs, helix-term/src/ui/completion.rs, helix-term/src/ui/editor.rs, helix-view/Cargo.toml, helix-view/src/document.rs, helix-view/src/editor.rs
Supercedes #1819
This PR resolves multiple problems with the completions.
The root cause of all of these issues were shortcomings in the way savepoints are handled.
Savepoints are set when a completion is triggered so that the changes sent by the server
can be applied correctly (refer to the same document).
The exact explanation is a bit tricky. I will provide an overview here but looking at the commits individually also helps. Every commit has a separate explanation/justification and usually just contains a couple of LOC of changes and therefore makes the explanation more digestible.
The savepoint is currently created when the completion request **response was received**. However, a (spec compliant) language server computes the completion response for the document state when it …
=> Fix completion race conditions

helix-core/src/selection.rs, helix-term/src/commands.rs
Fixes #6092 
Caused by some incorrect assumptions that missed an edge case in the `Selection.contains()` calculation. Tests were added accordingly.
[![asciicast](https://asciinema.org/a/NINyXHNywRUe6ULYZo4nGQjCi.svg)](https://asciinema.org/a/NINyXHNywRUe6ULYZo4nGQjCi?t=23)
=> Fix `shrink_selection` with multiple cursors.
