helix-editor/helix

book/src/keymap.md

Go to definition mapping is "gd" not "ge"

Fixed c/p error in keymap doc

---

helix-syntax/build.rs

When building helix, I was gettting the following error:
```
--- stderr
thread '<unnamed>' panicked at 'byte index 12 is out of bounds of `.DS_Store`', helix-syntax/build.rs:122:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Collect files for tree-sitter-go
Collect files for tree-sitter-rust
Collect files for tree-sitter-java
Collect files for tree-sitter-html
Collect files for tree-sitter-python
Collect files for tree-sitter-cpp
Collect files for tree-sitter-bash
Collect files for tree-sitter-toml
Collect files for tree-sitter-c
Collect files for tree-sitter-php
Collect files for tree-sitter-ruby
Collect files for tree-sitter-swift
Collect files for tree-sitter-scala
Collect files for tree-sitter-javascript
Collect files for tree-sitter-agda
Collect …
```

Add .DS_Store to ignored directories

---

helix-term/src/commands.rs

Fixed panic when enter command mode and press enter key.
``` shell
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', helix-term/src/commands.rs:1035:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Fix empty command cause panic

---

helix-term/src/main.rs

Application::new will use stuff that requires tokio runtime.
```
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/context.rs:18:26
```
I see that there seemed to be quite a lot of panic as well.

Fix panic opening rust file

---

helix-core/src/history.rs
helix-core/src/transaction.rs
helix-view/src/document.rs

As history is used separately from the rest of the edits, separating it
can avoid needless borrowing and cloning. But one need to be aware later.

Separate document history into Cell

---

helix-view/src/view.rs

Fix panic when buffer larger than terminal width

---

helix-core/src/lib.rs
helix-term/src/main.rs

```
helix-term 0.1.0
Blaž Hrastnik <blaz@mxxn.io>
A post-modern text editor.
USAGE:
hx [FLAGS] [files]...
ARGS:
<files>...    Sets the input file to use
FLAGS:
-h, --help       Prints help information
-v               Increases logging verbosity each use for up to 3 times
(default file: /home/xxx/.cache/helix/helix.log)
-V, --version    Prints version information
```

Default log file to cache

---

helix-term/src/keymap.rs
helix-term/src/ui/editor.rs

I would like to remove the shift modifier from ascii keys, as the current key matching is running into some problems on windows 10 for me.

removed shift matching

---

helix-term/src/commands.rs
helix-view/src/document.rs

On the current HEAD one can crash the editor by opening an empty buffer, and inputting d -> i -> enter. This is a possible fix.

Disable deleting from the end of a buffer which can cause a crash.

---

helix-term/src/commands.rs

Giving a goto count greater than the number of lines in the buffer
would cause Helix to panic.
```console
thread 'main' panicked at 'Attempt to index past end of Rope: line index 299, Rope line length 11', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec8
23/ropey-1.2.0/src/rope.rs:946:9
```
Fixes #94

Limit goto count

---

helix-term/src/ui/editor.rs

When the matching pair is out of bounds it still paints it causing an
out of bound panic. A dirty fix since it still have some issue, at least
it does not panic now.

Fix panic paint mysterious matching pair

---

helix-core/src/movement.rs
helix-core/src/selection.rs
helix-core/src/transaction.rs
helix-term/src/commands.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/prompt.rs
helix-view/src/view.rs

Split from #98. It fixes #58, #61, #73, #74, #88, and partially #107. It doesn't fix all the panics that #98 fixes (and introduces), but there shouldn't be any regressions.

Fixing Multiple Panics

---

helix-core/src/search.rs
helix-term/src/commands.rs
helix-term/src/ui/editor.rs

Bevore this PR `commands::find_prev_char` and `commands::till_prev_char` were triggerable through keys but `seach::find_nth_next()` was hardcoded in `_find_char`.
The passed `fn` was nerver used. With this PR the passed `fn` is used.
The change in `search.rs` resolves an off by one error in the behivor of `find_nth_prev`
fix: panicked at 'attempt to subtract with overflow' helix-term/src/ui/editor.rs:275:29
This would happen when the window-size was to small to display the entire `width` and one would start jumping forwards with `f<some_char>` and the beginning of the highlighted area would end up outside of the window and was greater than the end-postion. 
For me this happend when I opened helix/README.md in a terminal that is to small to display the entire width and start jumping …

fix: make find_prev_char and till_prev_char work + fix one panic

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/keymap.rs

Fix #93
cc @kevinsjoberg although we don't have `ctrl-w hjkl` yet, `ctrl-w w` (or `ctrl-w ctrl-w`) is usable.

Add window mode

---

Cargo.lock
README.md
book/src/install.md
helix-core/Cargo.toml
helix-core/src/lib.rs
helix-core/src/syntax.rs
helix-term/Cargo.toml

Hello, love the project! I don't know if this feature is desirable or not it wasn't clear to me whether the user is supposed to be able to easily edit things inside the runtime folder. If that's the case feel free to close this :)
I did consider making it so that if the HELIX_RUNTIME env variable is not specified we will use the baked in queries which I can do if desired.

Embed the runtime folder into the binary instead of using HELIX_RUNTIME env variable.

---

helix-term/src/ui/picker.rs

When moving down in the picker, we should not allow moving past the number of matches.
Fixes #141

Do not move past number of matches in file picker

---

helix-view/src/document.rs
helix-view/src/editor.rs

This PR fixes a crash on startup when the document that should be opened doesn't exist. For now the file will be created at launch, and will exist even if the user doesn't save it.
Closes: #25

Create file if it doesn't exist on save

---

helix-term/src/ui/picker.rs

If there are more matches than rows, we now calculate an offset to properly paginate the list of matches.
See https://asciinema.org/a/7lK3xY2DnoimW0Ky0iQwUMyw8
Fixes #139

Paginate file picker matches

---

Cargo.lock
book/src/configuration.md
contrib/themes/README.md
contrib/themes/ingrid.toml
helix-view/Cargo.toml
helix-view/src/theme.rs

Support for configuring style modifiers like bold, italic, etc. in theme.toml. They're done as an array, alongside fg and bg.

theme: Enable style modifiers in theme.toml

---

helix-term/src/ui/prompt.rs

This is an attempt to improve prompt completion. More specifically, the following items:
- Completing a directory would not trigger new completion results. Now pressing `Enter` when the selection is over a directory, will trigger new completion results from within that directory.
- While you could use `Tab` to move forward between completion results, you could not use `Shift+Tab` to move backwards. Now pressing `Shift+Tab` will move backwards in the completion results, wrapping to the end as expected.
**Demo**
https://asciinema.org/a/GPWVRd0EhRiO9VmarcWMGtU0x

Improve prompt completion

---

book/src/keymap.md
helix-term/src/commands.rs

This changes `spc w w` which save window, we already have `:w` for that.

Add spc w w for window mode

---

helix-core/src/movement.rs

`is_ascii_punctuation` will only work for ASCII punctuations, and when
we have unicode punctuation we jump into the `unreachable`.
This patch fallback into categorizing everything in this branch as
punctuation (kakoune approach).
Fixes https://github.com/helix-editor/helix/issues/123
This only prevents panic, but movements by-words are broken (stop at the Unicode punctuation).
I get this selection when pressing `b`

Fix panic when moving over unicode punctuation

---

helix-core/src/search.rs
helix-term/src/ui/editor.rs

The panics will only appear while using a `debug build` of helix, because of `debug_assertions` in helix-tui/src/buffer.rs +217 in `Buffer::index_of`
The panics would occur because `set_style` would draw outside the `surface`. 
Both occurred using `find_prev` or `till_prev`. In my case the first `panic!` would appear
in a terminal with around 80 columns in helix/README.md going to the end of the file
with `geglF(` 
the second with `geglFX`
The off by one fix ensures that `find_nth_prev` starts at the first character to the left. 
Before it started at the second to the left.

fix: 2 panics while setting style + off by 1 in find_nth_prev

---

helix-core/src/register.rs
helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-term/src/ui/editor.rs
helix-view/src/editor.rs
helix-view/src/lib.rs
helix-view/src/register_selection.rs

User can select register to yank into with the " command.
A new state is added to `Editor` and `commands::Context` structs.
This state is managed by leveraging a new struct `RegisterSelection`.

Implement register selection

---

helix-term/src/application.rs
helix-term/src/args.rs
helix-term/src/lib.rs
helix-term/src/main.rs

helix-term stuff will now be documented in rustdoc.
It will be useful for us to generate docs directly in keymap to keep the docs beside code.

Separate helix-term as a library

---

helix-term/src/ui/mod.rs

As a quick fix before we decide what to do next in #52, I've bumped the limit.

Bump file picker limit

---

Cargo.lock
helix-lsp/Cargo.toml
helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-lsp/src/transport.rs

I've been looking at the `helix-lsp` crate and half-instinctively started to tidy it up, removed unused imports, deleted a copy of the `select_all` file from `futures`, got rid of a couple of allocations, renamed a few methods, etc.
I wonder if you would be willing to accept a cleanup/refactor PR with no fixes/new features in it? If so, I'll continue with `helix-lsp` in this PR, otherwise, feel free to close it :)

[WIP] helix-lsp code cleanup

---

helix-term/src/ui/editor.rs

Make matching bracket dimmed, prevent out of bounds rendering

---

helix-view/src/document.rs

If the document was empty we would panic trying to insert the final newline.

Don't panic on empty document

---

helix-term/src/ui/menu.rs

`Shift-Tab` wasn't working for moving upwards in the menu.

Fix Shift-Tab for moving upwards in menu

---

helix-term/src/ui/picker.rs

In preparation of consolidating the picker and menu, I've adjusted the key bindings to match those of menu.
Move down: `Tab`, `Ctrl-n` or `Down`
Move up: `Shift-Tab`, `ctrl-p` or `Up`

Match keybindings of menu

---

helix-term/src/ui/mod.rs

According to the discussion in #171 I've changed how the limit work. It's now only applied if there's no `.git` folder in the project root.

Only enforce limit outside of .git

---

helix-term/src/ui/popup.rs

Closes: #198
Behaviour after fix when pressing `K`:

ui: Fix documentation popup panic

---

helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-view/src/view.rs

Better jump behavior since we override the first jump if it's on the
first document. At the same time, ctrl-i is now working with gd jumps.

Fix jump behavior, goto_implementation now jump

---

.gitignore
flake.lock
flake.nix

This isn't ideal for development, since it pulls Helix from GitHub instead of from the underlying filesystem, but it does get the package working for nix users. As an additional convenience, I also embedded the runtime by default.
Opening as a draft as I'm not sure if this is the direction we want to take here, but unless NixOS/nix#3978 get's a proper solution, this may be the best way to do it for now.
Potentially resolves #27

Fix flake package

---

helix-term/src/commands.rs

This matches the behaviour in vim and kak

move to first nonwhitespace on shift-i

---

helix-term/src/commands.rs

Pressing `t<ENTER>` will select all text up to new line.

Handle `t<ENTER>` as till newline

---

book/src/keymap.md
helix-term/src/commands.rs
helix-view/src/editor.rs
helix-view/src/view.rs

inspired by vim ctrl-6/kak ga commands. the alternate file is kept per view

add alternate file

---

helix-term/src/commands.rs

follow up of #223 
cc @robinvd include the "accessed" for more clarification in help

Add clarification to last buffer

---

.envrc
flake.lock
flake.nix
helix-term/Cargo.toml
shell.nix

This does a few changes:
- use nix-cargo-integration to integrate with cargo instead of own rust expressions
- use crate2nix to build the package instead of naersk (much more cache friendly)
- make the shell.nix file use the flake devshell (thanks to flake-compat)
- use local code, submodules will still be taken from git master branch

build(nix): use nix-cargo-integration, make shell.nix use flake devshell

---

flake.lock

Updates nixCargoIntegration so that crate2nix also gets updated.

chore(nix): update nixCargoIntegration input

---

helix-term/src/commands.rs

Target range was too narrow.
It would result in leaving the last character of the selection intact

fix offset by one problem in replace_with_yanked

---

contrib/themes/onedark.toml
helix-term/src/keymap.rs

Adds a macro rule to the `key!` macro so that keymaps using `Left`, `Home`, `Esc`, etc. will also be accepted.

Refactor keymap definitions using macros

---

helix-core/src/lib.rs
helix-term/src/ui/prompt.rs

Maybe need to update docs but there is none for prompt yet I believe, we also didn't differentiate between prompt and picker so we need to have docs to explain those. I am so used to ctrl-w to delete word in rather than backspace so many times.

Add ctrl-w for prompt

---

helix-core/src/chars.rs
helix-core/src/lib.rs
helix-term/src/commands.rs
helix-term/src/ui/editor.rs
helix-view/src/document.rs

- Move the primary indentation-style setting into `Document`.
- Attempt to auto-detect the indentation style of a document when first loading it, but fall back to a language-based default when confidence is too low.
- Add a command to manually set a document's indentation style.

Per-document indentation style, and indent-style auto-detection.

---

helix-term/src/commands.rs

Also print an error message when the argument is malformed.

Report indent style when calling indent-style with no arguments.

---

book/src/keymap.md
helix-term/src/ui/picker.rs
helix-term/src/ui/prompt.rs

Inspired by doom emacs. Able to filter picker options multiple times using ctrl-space.
[![asciicast](https://asciinema.org/a/hiZcV8V6jnSrGZeWp6ECK56Ha.svg)](https://asciinema.org/a/hiZcV8V6jnSrGZeWp6ECK56Ha)

Add filter ability to picker

---

helix-term/src/commands.rs
helix-term/src/ui/editor.rs

Helpers / internal implementations where using the `_` prefix.
However, this prefix also suppress unused warnings.
I suggest we use the `_impl` suffix instead.
For `_count` → `count` attribute renaming. This is not a issue in Rust. When appending `()` this is the function call, otherwise this is the attribute.

Use `_impl` suffix instead of `_` prefix

---

helix-core/src/register.rs
helix-term/src/commands.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/mod.rs
helix-view/src/editor.rs

Registers are stored inside `Editor` and accessed without `RwLock`.
To work around ownership, I added a sister method to `Editor::current`:
`Editor::current_with_context`. I tried to modify `Editor::current`
directly but it's used at a lot of places so I reverted into this for
now at least.

Remove RwLock for registers

---

book/src/configuration.md
contrib/themes/bogster.toml
contrib/themes/ingrid.toml
contrib/themes/onedark.toml
helix-term/src/ui/editor.rs
helix-view/src/theme.rs
theme.toml

Adds `ui.linenr.selected` which controls highlight of line numbers which have cursors on them. Selections are now rendered before the gutter to accommodate this change (is this important ?).
TODO:

Theme key to change highlight of selected line numbers

---

helix-term/src/commands.rs

- `O` at the beginning of file didn't move cursor
- `o` and `O` messed up cursor position with multiple cursors
Fixes #127

Fix cursor position bugs related to o and O

---

helix-term/src/commands.rs
helix-term/src/lib.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/mod.rs
helix-view/src/editor.rs
helix-view/src/lib.rs
helix-view/src/macros.rs

This is necessary to workaround ownership issues across function calls.
The issue notably arised when implementing the registers into `Editor`
and I was getting annoyed again when implementing copy/pasting into
system clipboard.
The problem is addressed by using macro calls instead of function calls.
There is no notable side effect.

Replace `Editor::current` by a macro

---

helix-term/src/ui/prompt.rs

It was attempted to use `String::insert` and `String::remove` to insert
without taking care of unicodes.
Fixes https://github.com/helix-editor/helix/issues/282

Fix panic when entering unicode in command prompt

---

helix-core/src/lib.rs
helix-term/src/commands.rs
helix-term/src/ui/mod.rs
helix-view/src/document.rs
helix-view/src/editor.rs

Fix expansion of `~`

---

book/src/configuration.md
helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-lsp/src/transport.rs
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/config.rs
helix-view/src/document.rs

This PR reenables workDoneProgress and adds handling for workDoneProgress/create requests from lsp server.

lsp: Actually implement workDoneProgress

---

helix-term/src/commands.rs

Indents were no longer respected with `o` and `O`. Using counts resulted
in multiple cursors in the same line instead of cursors on each line.
Introduced by 47d2e3ae

Fix indent regression issue with o, O

---

helix-term/src/config.rs

As @pickfire noticed, we shouldn't derive `Default` because `lsp_progress` by default should be turned on (opt out).

Don't derive `Default` for `GlobalConfig`

---

helix-core/Cargo.toml
helix-lsp/Cargo.toml
helix-syntax/Cargo.toml
helix-term/Cargo.toml
helix-tui/Cargo.toml
helix-view/Cargo.toml

~~This enables us to publish on crates.io~~
This is a first step towards enabling us to publish on crates.io.
I also ran [cargo-diet](https://github.com/the-lean-crate/cargo-diet), a helper for computing the optimal `include` directives for Cargo.toml manifests.
See #42

Cargo manifests cleanup

---

Cargo.lock
helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-lsp/src/transport.rs
helix-term/src/application.rs
helix-view/Cargo.toml
helix-view/src/editor.rs

Closes: #266 
Closes: #33 
Maybe closes?: #278
Tested with clangd and it correctly removes the `preamble...` file from `/tmp` on close.

lsp: Gracefully shutdown language servers, fix unwraps in transport

---

helix-term/src/ui/editor.rs

Fix overflow

---

helix-term/src/config.rs

I think it got lost somewhere during the merge.
Without this it's impossible to set the theme other than through `:theme`

Add missing `theme` option to toml config

---

helix-term/src/ui/completion.rs
helix-term/src/ui/markdown.rs
helix-view/src/tree.rs

Make completion window move to top when cursor is below half

---

Cargo.lock
book/src/keymap.md
helix-term/src/commands.rs
helix-view/Cargo.toml
helix-view/src/clipboard.rs
helix-view/src/editor.rs
helix-view/src/lib.rs

This commit adds six new commands to interact with system clipboard:
- clipboard-yank
- clipboard-yank-join
- clipboard-paste-after
- clipboard-paste-before
- clipboard-paste-replace
- show-clipboard-provider
System clipboard provider is detected by checking a few environment
variables and executables. Currently only built-in detection is
supported.
`clipboard-yank` will only yank the "main" selection, which is currently the first
one. This will need to be revisited later.
Closes https://github.com/helix-editor/helix/issues/76

Add system clipboard yank and paste commands

---

helix-term/src/application.rs

As discussed on matrix, this fixes the leftover spinners when workDoneProgress reaches the end without any message.

Cleanup spinners and messages on progress end

---

languages.toml

Change the default spaces of python indentation to follow pep8 which is the standard.
Kakoune does not support language defaults as far as I know https://github.com/mawww/kakoune/pull/3510 but I think we should follow standards for respective language rather than follow editor defaults.

Use pep 8 indentation for python

---

book/src/keymap.md
book/src/usage.md
helix-core/src/lib.rs
helix-core/src/surround.rs
helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-view/src/document.rs

Adds [vim-surround](https://github.com/tpope/vim-surround) functionality, with keybinds inspired from [vim-sandwich](https://github.com/machakann/vim-sandwich):
- ~`ma<char>`~ `ms<char>` - Add `char` around selection
- `md<char>` - Delete `char` pair
- `mr<from><to>` - Replace `from` with `to`
Goto matching bracket (previously `m`) has been moved to `mm`.
- `vim-sandwich` like visual feedback
- `b` as a generic surround char finder (like `b` in vim-sandwich)
- Show error when replace or delete cannot be done
- Treesitter based implementation ?
There are some subtle bugs right now with finding the correct surround pairs when they are spread across multiline lines, which can be solved by either using indent heuristics (works for most files) or directly querying treesitter, which is easier …

Add surround keybinds

---

helix-term/src/commands.rs
helix-term/src/ui/mod.rs

These commands let the user check and change the current working directory for the running helix session.
I mostly implemented those to play with the codebase but I thought they might be useful (they would be useful to me at least, I regularly change the working directory in vim).
As an aside, I think it would be nice if TypableCommands returned a Result<()> and any error was automatically logged using `editor.set_error(_)`, that would let one `bail!` out of a command implementation without having to manually call `editor.set_error(format!(...)); return;`. I could submit such a change if it was deemed acceptable.

Implement change_directory/show_directory commands

---

helix-term/src/commands.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/picker.rs
helix-term/src/ui/prompt.rs

This is the part of #285 that changes the callbacks' argument from an `Editor` to a `compositor::Context`. It's the source of lots of merge conflicts, so I'm hoping I can get this in quickly while I work on the other parts of #285.

Make the prompt callback take a Context.

---

book/src/themes.md
helix-term/src/ui/editor.rs
theme.toml

Perhaps this might be a solution for #323 ?

Add ability to theme cursor and primary selection

---

helix-core/src/graphemes.rs

Handle erroneously ignored case in RopeGraphemes iterator.

---

helix-term/src/config.rs

It should have been in kebab-case, but it was the default snake_case.

Fix lsp config deserialization case

---

helix-core/src/surround.rs

Surround operations previously ignored other pairs that are  enclosed within which should be skipped. For example if the cursor is on the `,` in `{{a},{b}}`, doing `md{` previously would delete the `{` on the left of `a` and `}` on the right of `b` instead of the outermost braces. This commit corrects this behavior.

Skip enclosed pairs in surround

---

helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/config.rs
helix-term/src/keymap.rs
helix-term/src/main.rs
helix-term/src/ui/editor.rs
helix-view/src/document.rs
helix-view/src/input.rs
helix-view/src/lib.rs

Need to be used for autoinfo
Revert "Revert "Refactor key into helix-view""
This reverts commit 10f9f72232f5789323d689bf0f9cd359715770d6.
cc @wojciechkepka

Fix previous broken refactor key into helix-view

---

helix-term/src/ui/picker.rs
helix-tui/src/buffer.rs

Visually indicate that characters have been truncated from the list:
https://github.com/helix-editor/helix/pull/353#issuecomment-867312177

Add … when chars are truncated in picker

---

runtime/themes/bogster.toml
runtime/themes/ingrid.toml
runtime/themes/onedark.toml
theme.toml

Not all terminals support dim, for those terminal that does not support
this (konsole, item2, wezterm), users cannot differentiate between match
and primary cursor. So set a color for this.
Before
After
cc @wojciechkepka

Add default color for cursor match

---

helix-tui/src/buffer.rs

(please do not merge before testing with CJK characters)
cc @pickfire

Use unicode_width to correctly truncate picker chars

---

helix-view/src/document.rs

Fixes #378.  The issue was that because indent style detection
ran before language detection, there was no language indent
style to fall back on if indent style detection failed, so it
would just default to 2 spaces.

Detect file language before file indent style.

---

helix-term/src/ui/mod.rs

So this might not be very optimized but it's a big quality of life improvement. I use file picker a lot and sometimes I just want to see what I edited last without having to remember the exact filename. I tested this change on a quiet big repository - https://fuchsia.googlesource.com/fuchsia/  and the additional time to sort the entries was negligible even in debug mode.
I'm ok not to push it either if that will be the general consensus.
EDIT:
Actually meant access time not modification time

Sort files in file picker by access, modification and creation date

---

helix-core/src/graphemes.rs
helix-term/src/ui/editor.rs

This resulted in phantom blank lines in files with CRLF line
endings, but could potentially have manifested with other
graphemes as well.

Fix highlight code splitting graphemes.

---

.gitattributes

It's unnecessary as they are `.txt` files, but correct me if I'm wrong.

Remove `.gitattributes`

---

helix-lsp/src/lib.rs
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/compositor.rs
helix-term/src/job.rs
helix-term/src/lib.rs
helix-term/src/ui/editor.rs
helix-view/src/document.rs
helix-view/src/editor.rs

This is a first stab at #53. 
There are definitely some rough edges still:
- I wanted commands to be able to provide `LspCallback`s, so I made them take a `compositor::Context` instead of an `Editor`. I don't know whether that's reasonable.
- I'm not sure if I'm keeping the language-server's changes in sync correctly
- `Transaction` isn't `Sync`, so lots of `Arc<Mutex<>>`...

First attempt at sync formatting.

---

helix-core/src/syntax.rs

Only noticeable when using the "embed_runtime" feature.

Add missing import

---

book/src/keymap.md
book/src/usage.md
helix-core/src/lib.rs
helix-core/src/movement.rs
helix-core/src/selection.rs
helix-core/src/textobject.rs
helix-term/src/commands.rs

Closes #213.
Uses `ma` (match around) and `mi` (match inside).
- Treesitter based objects (function, class, parameter, etc)
- Paragraph object
- WORD object

Add object selection (textobjects)

---

helix-core/src/surround.rs
helix-core/src/textobject.rs

For example when the cursor is on the `'` in `'word'`, the cursor wouldn't move because the search for a matching pair started _from_ the position of the cursor and simply found itself.

Fix surround bug when cursor on same pair

---

Cargo.lock
helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/info.rs
helix-term/src/ui/mod.rs
helix-tui/Cargo.toml
helix-tui/src/backend/test.rs
helix-tui/src/buffer.rs
helix-tui/src/text.rs
helix-tui/src/widgets/paragraph.rs
helix-tui/src/widgets/reflow.rs
helix-tui/src/widgets/table.rs
helix-view/Cargo.toml
helix-view/src/editor.rs
helix-view/src/info.rs
helix-view/src/input.rs
helix-view/src/lib.rs

Progress (goto and space mode done)

Add infobox

---

helix-term/src/ui/editor.rs

Fixes #415.  The issue was that cursor highlighting wasn't extending
to encompass the entire CRLF grapheme, and therefore ended up splitting
it.  This presumably was messing up other grapheme rendering as
well, and this fixes that as well.

Fix phantom lines in some CRLF files.

---

languages.toml
runtime/queries/julia/folds.scm
runtime/queries/julia/highlights.scm
runtime/queries/julia/injections.scm
runtime/queries/julia/locals.scm

I took the treesitter recipes from here: https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/julia
and the command for the LSP is from: https://github.com/julia-vscode/LanguageServer.jl/wiki/Kakoune
I can't make the languageserver work, but this is maybe because I can't make it work in general.
***
Got the following log:
```
2021-07-05T10:55:54.618 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2021-07-05T10:55:54.618 mio::poll [TRACE] registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
2021-07-05T10:55:54.618 mio::poll [TRACE] registering event source with poller: token=Token(3), interests=READABLE | WRITABLE
2021-07-05T10:55:54.618 helix_lsp::transport [INFO] -> …
```

Add julia support (LSP not working)

---

helix-term/src/application.rs

Use biased select!, don't eagerly process lsp message since we want to
prioritize user input rather than lsp messages, but still limit rendering
for lsp messages.
It seemed faster, at least for me in debug mode when inserting text. Not sure if it's my imagination, not benchmarked or flamegraph or something, just based on intuition.

More responsive key input

---

.gitignore
Cargo.lock
helix-core/src/indent.rs
helix-core/src/syntax.rs
helix-syntax/Cargo.toml
helix-syntax/build.rs
helix-syntax/src/lib.rs
theme.toml

Motivated by some of the findings in #330 I went ahead and attempted to split out grammars.
The set of languages is no longer static, this way the user will be able to self-compile additional grammars and provide them under `runtime/grammars`. Languages can now be declared without a matching grammar too, which should unblock #205.
I think it would be cool to expose some of the `build.rs` code as an optional feature under the `hx` CLI, so that the user would be able to easily point to a cloned tree sitter grammar and compile it into their runtime dir.
Additionally, the grammar objects are now persisted and we only recompile when necessary (if the grammar sources changed), which should massively speed up `cargo clean && cargo build`.
With these changes, release build of `hx` is now `7.8M` …

Dynamically load grammar libraries at runtime

---

helix-term/src/keymap.rs

Extend_line has two identical entries in keymap.rs; this removes one of them.

Remove double entry of extend_line in keymap.rs

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/keymap.rs

In vim I use the chance case function quite a lot and found it missing here.
Here is my attempt at adding it.

Added change_case command

---

helix-term/src/application.rs
helix-view/src/editor.rs

See discussion #444.
This changes the startup behaviour of helix; When multiple files were specified from the command-line, it used to be that helix would open a view per file (potentially causing a crash). Now it will open only one view with the first file specified, regardless how many files are given on the command-line.
This commit does not allow for any configuration; I can add that if desired.

Changed startup behaviour regarding multiple files.

---

helix-core/src/comment.rs
helix-core/src/indent.rs
helix-core/src/syntax.rs
helix-term/src/commands.rs
helix-view/src/document.rs
languages.toml

This adds a line in the language.toml file declaring the type of single line comment to use for the specified language. This still does not support <start> <end> comment types like xml, nor multiline comments.

Made toggle_comments language dependent

---

helix-core/src/syntax.rs

Fixed warning:
```
warning: the item `fmt` is imported redundantly
--> helix-core/src/syntax.rs:98:9
|
16 |     fmt,
|     --- the item `fmt` is already imported here
...
98 |     use std::fmt;
|         ^^^^^^^^
|
```

The item `fmt` was imported redundantly

---

helix-core/src/comment.rs

Fix #474. This change will cause uncommenting to use a margin of `0` when any of the uncommented lines does not have a space after the comment token, rather than unconditionally using a margin of `1`. I apologise if I might have overlooked something, I've never actually contributed to an open source project before.

Determine whether to use a margin of 0 or 1 when uncommenting

---

helix-core/src/indent.rs

Fix #492
cc @luctius thanks for reporting the issue
I noticed an issue when I try reproduce it and spammed `}}}}}}}}}}}}}}}}}}}}}}}}}}<newline>`, and it crashed like yours.
Seemed like the function is also a source of slowness in debug mode, whenever I typed `}` or `{`, it feels very slow. Maybe I will fix that next time.

Fix append newline indent

---

runtime/themes/bogster.toml

fix: change primary cursor color in bogster theme

---

helix-view/src/keyboard.rs

While I was reading through this file, I found a doc-comment typo. This fixes it.

Fix Doc Comment Typo

---

helix-term/src/keymap.rs
helix-term/src/ui/editor.rs

Show pending keys in status line

---

helix-term/src/commands.rs
helix-term/src/keymap.rs

Regression from #454. Go to line 10 with `10gg` or `10G`.

Fix goto line number

---

helix-term/src/commands.rs
helix-view/src/input.rs

Uses the new `char` method on `KeyEvent` to simplify the logic in some places.
Also fixes the bug of ignoring modifier keys at places where they shouldn't be ignored (for example in insert mode pressing ctrl-a would input a).

Refactor case where key event is solely a character

---

helix-core/src/comment.rs
helix-core/src/graphemes.rs
helix-core/src/line_ending.rs
helix-core/src/match_brackets.rs
helix-core/src/movement.rs
helix-core/src/object.rs
helix-core/src/position.rs
helix-core/src/search.rs
helix-core/src/selection.rs
helix-core/src/surround.rs
helix-core/src/syntax.rs
helix-core/src/textobject.rs
helix-term/src/commands.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/editor.rs
helix-view/src/document.rs
helix-view/src/editor.rs
helix-view/src/view.rs

Addresses #362.
Switch all code over to:
1. Use gap indexing.
2. Not assume a file-final line-ending.
All code has been adjusted so that it still presents an on-char indexing model to the user, but internally everything works in terms of gap indexing.

The Great Line Ending & Cursor Range Cleanup

---

helix-term/src/commands.rs

The non-extending variants of the commands weren't selecting from the range head.
Fixes #527.

Fix incorrect behavior of `find_char` command and friends.

---

helix-core/src/indent.rs
helix-term/src/commands.rs
helix-view/src/document.rs

This is more consistent with the line-ending code, and collects related code in one place in a nicer way.

Move indent-style code into `helix_core::indent`.

---

helix-term/src/application.rs
helix-term/src/config.rs
helix-term/src/ui/editor.rs
helix-view/src/tree.rs
helix-view/src/view.rs

TODO:
- ~~Double-clicking to select words (will probably need to add extra vars to state for counting)~~
- ~~Select lines by dragging on the left side~~
- ~~Pick items from menus using mouse (may be out of scope)~~

Mouse selection support

---

helix-view/src/view.rs

Specifically, test cases for double-width characters and grapheme
clusters.

Add more unit tests for pos_at_screen_coords.

---

Cargo.lock
helix-lsp/Cargo.toml
helix-term/Cargo.toml
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/compositor.rs
helix-term/src/keymap.rs
helix-tui/src/terminal.rs
helix-view/Cargo.toml
helix-view/src/graphics.rs

Not sure why but the cursor seemed to be gone be broken right after it suspend. `tput reset` does fix it.

Add ctrl-z to suspend

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/keymap.rs

My attempt to add #457.
This does not 'undo' a selection when moving into the opposite direction; instead it enlarges it. Not sure what the behaviour should be.

Vertical Selection

---

helix-term/src/commands.rs

Yank should proceed with normal mode.
I am thinking of a better solution that we always change back to normal mode after a command but if continue with a movement key then just kept the extend mode.

Back to normal after yank

---

helix-term/src/application.rs

Fixes a bug where the language server is told to shutdown directly after application start.
I'm not sure _why_ the call of close_language_servers is here, to opinions are welcome.

Do not shutdown lsp during claim_term

---

helix-term/src/ui/editor.rs
helix-term/src/ui/info.rs
helix-view/src/graphics.rs

The issue was that we were indiscriminately writing all of the lines of the info box regardless of the viewport's height. I additionally inlined some functions of `Rect`, as I believe they were being used frequently enough (20+ times in `helix-tui`), and would help if/when `helix-view` is used for a different frontend.

fix small terminal size panic with info popup

---

helix-term/src/commands.rs

I realized this issue after noticing that `C-w` in insert mode correctly deleted a word backward, but wrongly exited insert mode in the process.

Change `exit_select_mode` to check that select mode is active before switching to normal mode

---

languages.toml
runtime/queries/java/highlights.scm

Closes #419
I don't know Java at all, so I don't know if what I put in `languages.toml` is correct.

Add java highlighting

---

helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/ui/editor.rs
helix-view/src/editor.rs

Fix #552
- ~~Possibly add scrolling inside pickers, that also worked when terminal emulated up/down keypresses~~ out of scope
Both tasks can be done separately if that would be better.

helix-term: handle scrolling when mouse is enabled

---

helix-term/src/commands.rs

Fix surround_replace replacing the wrong character on the right.

---

helix-view/src/graphics.rs
helix-view/src/theme.rs

Makes all parsing functions return a `Result` and handles errors inside deserializing functions instead of using `warn!()` everywhere. Also moves associated functions to structs.

Refactor theme parsing

---

helix-core/src/selection.rs
helix-term/src/commands.rs
helix-term/src/compositor.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/info.rs
helix-term/src/ui/markdown.rs
helix-term/src/ui/menu.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/picker.rs
helix-term/src/ui/popup.rs
helix-term/src/ui/prompt.rs
helix-term/src/ui/text.rs
helix-view/src/document.rs
helix-view/src/editor.rs
helix-view/src/view.rs

Show file preview in split pane in fuzzy finder

---

CHANGELOG.md

Seems that the version 0.3.0 title was changed unintentionally.

Reverted unintended change?

---

book/src/configuration.md

Added explicit paths for WIndows, Mac, and Linux based on [`choose_base_strategy`](https://docs.rs/etcetera/0.3.2/etcetera/base_strategy/fn.choose_base_strategy.html). If this is obvious, please reject, but I had to trace it down through the etcetera module to be sure I had `config.toml` in the right place.

Update configuration.md for Windows

---

Cargo.lock
helix-term/src/keymap.rs
helix-term/src/ui/info.rs
helix-view/src/info.rs

Uses widget primitives to render the text instead of manual character-by-character render and also cleans up `Info` creation.

Refactor infobox rendering and parsing

---

helix-syntax/build.rs

Hey, Arch Linux maintainer of [`helix`](https://archlinux.org/packages/community/x86_64/helix/) is here.
While updating `helix` from `0.3.0` to `0.4.1` I realized the grammar libraries are loaded dynamically at runtime (dd2903ff10387c04e933aa37846663131297b8b3) which is fine but they all lack [full RELRO](https://www.redhat.com/en/blog/hardening-elf-binaries-using-relocation-read-only-relro) when they are built. [namcap](https://gitlab.archlinux.org/pacman/namcap) shows the following warning:
```
helix W: ELF file ('usr/lib/helix/runtime/grammars/agda.so') lacks FULL RELRO, check LDFLAGS.
helix W: ELF file ('usr/lib/helix/runtime/grammars/bash.so') lacks FULL RELRO, check LDFLAGS.
helix W: ELF file ('usr/lib/helix/runtime/grammars/c-sharp.so') lacks FULL RELRO, check LDFLAGS.
helix W: ELF …
```

Compile the grammar libraries with full RELRO

---

helix-term/src/commands.rs

Consistent with yanking, exit select mode after toggling comment. Fixes #597

Exit select mode after toggle_comment. Fixes #597

---

languages.toml

INO is file extension for C++ files used in Arduino sketches.
Reference: https://www.arduino.cc/en/Guide/Environment

Adding INO to C++ file type

---

languages.toml

MJS is a file extension for JavaScript modules using standard ES2015+

Adding mjs to JavaScript file type

---

languages.toml

``.hh`` is often used alongside ``.cc`` files. However, it is not part of Google's C++ style guide.
``.ipp`` and ``.tpp`` are template implementation files, which are kind of like ``.cpp`` files in what they do, except that they have to be ``#include``'ed in a different way due to how the linker works.
``.*xx`` files are common alternatives to ``.*pp`` files. They are discouraged by the CPP Core Guidelines, but legacy code often still uses them, and even some modern coders favor them to ``.*pp`` files.

More C++ extensions

---

.gitmodules
languages.toml
runtime/queries/protobuf/highlights.scm
runtime/queries/protobuf/indents.toml

NOTE: This only supports protobuf 3 syntax.

feat: add protobuf language support

---

runtime/queries/protobuf/highlights.scm

It appears I forgot about the "optional" keyword while doing the other PR. This adds it.

fix: add missing optional keyword to protobuf syntax

---

helix-term/src/commands.rs

Mostly copied this from `helix-term::src::commands::split`, but it works similar to how vim handles splits.

Add :vsplit and :hsplit commands

---

helix-core/src/lib.rs
helix-core/src/path.rs
helix-term/src/commands.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/picker.rs
helix-view/src/document.rs
helix-view/src/editor.rs

I had already done this work for #634.

Move path util functions from `helix-term` to `helix-core`

---

.gitmodules
languages.toml
runtime/queries/zig/highlights.scm
runtime/queries/zig/indents.toml

Highlighting works, indenting not so much, but I guess it is more than nothing.
Queries are from https://github.com/Himujjal/tree-sitter-zig

Add zig tree-sitter support

---

helix-term/src/ui/editor.rs

I'm not sure why rustfmt didn't fix this.

Fix code indentation

---

helix-term/src/ui/editor.rs

fix: use head instead of anchor for relative line

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/config.rs
helix-term/src/keymap.rs
helix-view/src/editor.rs

Addresses #75.
I've added a config option for `shell` which would be set like `shell = ["bash", "-c"]`, ~~but the code does not currently use it because command functions are not able to access config currently. As such, the code is only able to fall back to `cmd /C` on Windows and `sh -c` otherwise.~~ ~~Currently, the command's stderr isn't handled.~~
- ~~Shell command completions~~

Shell commands

---

docs/vision.md

People have asked what Helix's vision/direction is, so hopefully this can be something we can point them to when that comes up.

Add a "vision" document.

---

helix-term/src/commands.rs
helix-term/src/keymap.rs

I want to use kakoune's keybindings in helix. But commands extending to long words are missing in helix. This PR adds those commands.

Add commands that extends to long words

---

helix-term/src/commands.rs

Refactor `move_*`, `extend_*` and `switch_case_*` commands by factoring out common code.

Refactor movement and case commands

---

helix-term/src/keymap.rs
helix-term/src/ui/editor.rs

Adds an option to turn keymap nodes sticky, which will temporarily make the sticky node the base keymap. Subsequent keys will be looked up from this sticky keymap node for commands to be executed. Pressing `Escape` will exit out of this sticky mode.
Usage with the `keymap!` macro:
```rust
let normal_mode = keymap!({ "Normal mode"
"g" => { "Goto" sticky=true
"g" => goto_file_start,
"e" => goto_file_end,
},
});
```
Use case includes keybindings for debug mode (#574), sticky view mode, etc.

Add a sticky mode for keymaps

---

helix-term/src/keymap.rs

Regression due to #635 where escape key in insert mode would not exit normal mode. This happened due to hard coding the escape key to cancel a sticky keymap node.

Fix escape not exiting insert mode

---

helix-term/src/commands.rs
helix-term/src/keymap.rs

Currently, `goto_line_{start,end,end_newline}` commands works as `extend` when in select mode. This PR adds `extend_to_line_{start,end,end_newline}` commands that always extend to regardless of current mode.

Add command to extend to line start or end

---

languages.toml

this adds language servers for elixir and nix.
I tried testing, but upon `nix build . -L`, I hit a compilation error on darwin
```
Building build.rs (helix-syntax)
> Running rustc --crate-name build_script_build build.rs --crate-type bin -C debuginfo=2 -C codegen-units=4 --edition 2018 --cfg feature="default" --out-dir target/build/helix-syntax --emit=dep-info,link -L dependency=target/buildDeps --extern anyhow=/nix/store/4qppk39q3ailrlx1h3756q76dwd5d3f9-rust_anyhow-1.0.43-lib/lib/libanyhow-70434c982d.rlib --extern cc=/nix/store/6z4n0z64yb56idhxmjq1jjvirdg2zrvp-rust_cc-1.0.70-lib/lib/libcc-a04023643d.rlib --extern threadpool=/nix/store/rw61d1dy16gizzarhh88328my0wg6x3p-rust_threadpool-1.8.1-lib/lib/libthreadpool-56ad10a5c6.rlib --cap-lints allow --color always
> thread 'main' panicked at …
```

add language server for elixir and nix

---

helix-term/src/commands.rs

Resolves #715
WIP because it doesn't play nice with the LSP.

Convert clipboard line ending to document line ending when pasting

---

runtime/themes/dark_plus.toml

This was recently changed in VSCode.

Update dark_plus error colour

---

.gitmodules
languages.toml
runtime/queries/svelte/highlights.scm
runtime/queries/svelte/indents.toml
runtime/queries/svelte/injections.scm

I'm opening this prospecive PR just to see if I haven't made anything stupid.
I've added the tree-sitter gitmodule
added all the queries file that were in the tree-sitter repository.
I need to update my nix to include the latest PR that downloads the submodules automatically.
I should have time to test this in the next few days.

languages: add svelte support

---

helix-term/src/commands.rs

`search_next_impl`: don't panic on invalid regex

---

runtime/themes/everforest_dark.toml

Ports the "Dark Hard" variant of the [Everforest](https://github.com/sainnhe/everforest) theme to helix.
- there were a few theme keys used in other themes that I didn't find documentation for
- the usage of colors might be slightly different from the original (however, the palette's colors are the exact ones used in the original)
<details>
<summary>screenshot (not up to date anymore)</summary>
</details>

add everforest dark theme

---

flake.nix

This adds a dependency needed for local builds for darwin. This is pretty straightforward
(from here this is just a description of a weird behavior related to flakes, not related to this PR).
@yusdacra the weirdest thing happened today. Trying to build helix from the flake, I couldn't get some changes that actually work with local compilation.
If you look at the following [PR](https://github.com/helix-editor/helix/pull/733), trying to build it from the flake did not enable syntax highlighting on svelte files (which is what the pr is about). However a local `cargo build --release` actually works.
I can't explain it. (there is a svelte example on the PR in case you are interested in testing).
(I verified that I was on the right commit)
(this is what the flake.lock contained)
```
"helix": { …
```

flake: add darwin devshell dependency

---

TODO.md
book/src/configuration.md
book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/ui/mod.rs
helix-view/src/editor.rs

First stab at smartcase search.
Some thoughts:
- What's the desired behaviour for `select_regex`? Never enabled? Configured with a separate option?
- Where would the regex builder live in `helix-core`? (so it can be used for other ui:s than term and #651) 
(edit: i didn't look at 651:s implementation before. guess the pr's not a reason for moving it to `helix-core`..)

smartcase regex search

---

Cargo.lock
book/src/keymap.md
helix-term/Cargo.toml
helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-term/src/ui/mod.rs

Since we haven't figure out how to properly implement a global search feature yet #196 , I hope this could at least be an inspiration of an potential better design:)
This implementation bind ```space + /``` to display a prompt (like the search prompt), and on ```Enter```, start the search, gathers the result and pop up a ```FilePicker```. A few necessary changes are made, such as ```regex_prompt```, which now accepts an extra callback that would be invoked once ```Enter``` is pressed.
Feel free to close this if we figure out something better later.

Initial implementation of global search

---

book/src/configuration.md
helix-term/src/commands.rs
helix-view/src/editor.rs

This just makes it possible to turn off the automatic insertion of parentheses.
I assume `HOOKS` was `const` for a reason (maybe generating it is computationally expensive, so you wouldn't want it running on every key press?). So, instead of moving the definition of `HOOKS` to within the function it's used in, I added an alternative `HOOKS` without the auto-pair hook, and had the function determine which to use on the fly.

Add option for automatic insertion of closing-parens/brackets/etc

---

helix-term/src/commands.rs

Allows for opening files with `:open ~/your/path/here`.

add tilde expansion for file opening

---

helix-term/src/commands.rs

This commit fixes #786
I basically copied the code from `ui/mod.rs :: file_picker` for this, nothing special.

global search: show file names as relative paths

---

runtime/themes/nord.toml

This adds a theme that I've wanted in Helix since day one, [Nord!](https://www.nordtheme.com/). For accuracy, I've followed the documentation provided by Nord  [here](https://www.nordtheme.com/docs/colors-and-palettes) and also compared it with the Nord theme for Neovim.
_toml_
_rust_
_go_
_yaml_

adds: nord colortheme

---

helix-term/src/commands.rs

Now we can have multiple aliases to the same command.
I also added the alias `x` for `wq` and all the associated variants.

Add a bunch of aliases

---

helix-term/src/commands.rs

@archseer, sorry with my PR #797 I introduced a new clippy warning. Here is the fix

Fix clippy warnings

---

helix-view/src/editor.rs

https://matrix.to/#/!zMuVRxoqjyxyjSEBXc:matrix.org/$UF70A_vWmDH5EawsTQLnyLVp0qIqokNwVI4aRFXdEd4?via=matrix.org&via=tchncs.de&via=nixos.dev  
> When I use Helix, I tend to start it with no arguments and then `space f` and open a file. As a result, the scratch buffer which opened when I first started the editor remains in the buffer list, and this has been annoying me. I'd prefer if, when switching buffers, if a scratch buffer has no path and is not modified (meaning that it is empty), that it be automatically removed (given that no open view currently displays the buffer).
I had to do some stuff to get around borrow errors.

If switching away from an empty scratch buffer, remove it

---

helix-term/src/commands.rs

Only remove primary selection with `search_next` without extend.

only remove primary index when search next without extend

---

languages.toml
runtime/queries/php/indents.toml

This adds an indents.toml for PHP, based on the one from nvim-treesitter. I added a few more indents to the list nvim had. I also adjusted the default indent unit to 4 spaces based on the PSR2/PSR12 standards that are popular in modern PHP application development.

Add indents for PHP

---

helix-term/src/keymap.rs
helix-view/src/info.rs
helix-view/src/input.rs
helix-view/src/keyboard.rs

This sorts the keys in the infobox, when multiple keys are associated to a command (or command group).
What previously looked like this:
now looks like this:
I also tried adding a padding to make everything align but I'm not sure if that's an improvement. If that is desired, I can add it to this PR:

Implement key ordering for info box

---

helix-core/src/lib.rs
helix-core/src/movement.rs
helix-core/src/position.rs
helix-term/src/ui/completion.rs
helix-view/src/view.rs

The issue affected files with lots of tabs at the start as well.
Fix #840
Before
After

Ensure coords in screen depends on char width

---

helix-term/src/keymap.rs

If a user wants to disable a key by binding it to `no_op`, they probably don't want it showing as `Do nothing` in infoboxes.

Hide keys bound to `no_op` from infobox

---

helix-term/src/ui/picker.rs
helix-tui/src/buffer.rs

Truncate the starts of file paths instead of the ends in picker

---

Cargo.lock
helix-term/Cargo.toml
helix-term/src/ui/picker.rs

This PR adds detect binary file and large file on file picker. (#847)
Use [content_inspector](https://github.com/sharkdp/content_inspector) to detect binary file (I'm new to this project, let me know any already exist way on this project to detect binary file).

Prevent preview binary or large file

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/prompt.rs

Like title
ui prompt add a shortcut to pick a word.
Command `search` make histories as completions
The `global search` currently has no completions because it does't have histories register.

prompt add a shortcut `c-s` to pick a word under cursor. command `search` make histories as completions.

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/keymap.rs

In kakoune / tmux i often use goto next buffer / next window shortcut.
I find it faster for my workflow than using the buffer picker so i tried implementing it.

Implement "Goto next buffer" command

---

helix-term/src/commands.rs
helix-view/src/document.rs

* `Already at oldest change` when undo fails
* `Already at newest change` when redo fails

Inform when reaching undo/redo bounds

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/keymap.rs

It looks a good deal less efficient than forward search, but searching a 1500+ line file for 'a' doesn't seem to have caused any noticeable latency for me. 
I wasn't sure what to do with `extend_search_next` and `extend_search_prev`, given that there's a shortage of letters left available, so I bound them to `H` and `L`. 
This is my first commit that's actually adding/renaming functions, let me know if there are any naming conventions I should be aware of.

Add reverse search functionality

---

helix-term/src/config.rs
helix-term/src/main.rs
helix-view/src/editor.rs

Resolves #670.
* Startup message if there is a problematic config, then launch with default config.
* Statusline error if trying to switch to an invalid theme, and reject the switch. This results in using the default theme if an invalid theme is set in `config.toml`.

Launch with defaults upon invalid config/theme

---

book/src/usage.md
helix-core/src/textobject.rs
helix-term/src/commands.rs
helix-term/src/ui/prompt.rs

Add WORD textobject

---

helix-core/src/match_brackets.rs

This enables `mm` to work on quote characters as well as highlighting of
matching quote when on it. I'm unsure if there's a reason these weren't
added in the first place, but some brief testing it works for me in some
rust, javascript and php files.

Adds single and double quotes to matching pairs

---

languages.toml

#968 
https://www.mint-lang.com/
mint ls was merged into nvim-lspconfig recently.
There is an open pull request for mint in emacs here.
Mint's language server is built into the cli interface of mint itself.
Here are the features that are currently supported by the mint language server:
https://github.com/mint-lang/mint/blob/master/src/ls/README.md

Adds mint language server (WIP)

---

.gitmodules
languages.toml
runtime/queries/perl/highlights.scm
runtime/queries/perl/textobjects.scm

Perl support

---

book/src/guides/adding_languages.md
helix-core/src/indent.rs
helix-core/src/syntax.rs
helix-view/src/document.rs
languages.toml

Most of the shell and perl scripts i have to work on have no extensions.
With this change im adding shebang support for detecting file types.
There is also a new config entry in languages.toml: "shebangs"

Detect filetype from shebang line

---

languages.toml

Fix the error:
```
thread 'main' panicked at 'Could not parse merged (built-in + user) languages.toml: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, at: None, message: "missing field `shebangs`", key: ["language"] } }', helix-term/src/application.rs:87:14
```

Fix panicked missing field `shebangs`

---

helix-core/src/syntax.rs
helix-term/src/application.rs

I forgot to account for `languages.toml` in #982.

Use default `languages.toml` if user's is invalid

---

helix-term/src/commands.rs
helix-view/src/view.rs

I often use `search` to move cursor to pos I aready know and keep my eyes on it.
Currenly helix always align cursor to center that cause Eyes lost the pos.
This PR  will only align cursor center when it isn't in view.
Previous:
After:

Only align cursor center when it isn't in view.

---

helix-term/src/ui/mod.rs

When user press escape to abort search, it will restore the original position and **offset**.

Restore screen position when abort search

---

book/src/keymap.md

- Clearly mark keybinds that require LSP
- Fix incorrect rendering of Prompt section due to missing newline'

Cleanup keymap doc book page

---

helix-term/src/application.rs
helix-view/src/editor.rs

Allow piping from stdin into a buffer on startup

---

helix-term/src/keymap.rs

Space mode and view mode are duplicated on two different keybinds, and they tend to get out of sync by contributors forgetting to update both of them. This commit adds a test that explicitly checks that they are identical. Prevents issues like #1050.

Ensure that identical keymaps stay in sync

---

helix-term/src/keymap.rs
helix-term/src/ui/menu.rs
helix-term/src/ui/picker.rs
helix-term/src/ui/popup.rs
helix-term/src/ui/prompt.rs

Adds `ctrl!` and `alt!` macros (which existed before the big keymap refactor) and uses them in event handling of `Component`s. Note that this converts crossterm's `KeyEvent` to our own `KeyEvent` on each invocation of `handle_event` in Components.

Refactor keyevent handling using key, ctrl macros

---

helix-term/src/commands.rs

Add `m` textobject for pair under cursor

---

helix-term/src/commands.rs

Closes https://github.com/helix-editor/helix/issues/1053.
---
I think that `[scratch]` is the best name for this, however this is not a very strongly held opinion, so I'll bow to what you maintainers deem the best choice.

helix-term/command: make scratch buffer name consistent

---

helix-term/src/commands.rs
helix-view/src/document.rs

Fix earlier/later missing changeset update

---

helix-term/src/commands.rs
helix-view/src/document.rs

This way, the name is accessible everywhere Document and related types
are.
----
While working on https://github.com/helix-editor/helix/pull/1035, I needed the name of the scratch buffer. However, since the const is defined in `helix-term` and not `helix-view`, I have no way to access it. This PR moves the const to `helix-view/src/document.rs` so that the const is accessible everywhere `Document` and related types are.
(I didn't think the original placement through, sorry. I swear, I'm not trying to pad my PR stats :P)

helix-term/commands: move SCRATCH_BUFFER_NAME to helix-view/document

---

helix-term/src/ui/editor.rs

Closes https://github.com/helix-editor/helix/issues/1090.

helix-term/editor: display scratch buffer name in status bar

---

helix-term/build.rs
helix-term/src/main.rs

Fixes #922. Right now it doesn't detect release versions, and just blindly throws on the commit hash in all cases that one exists. Reverts to old (current) behavior if built in an environment with no git repo.

Add commit hash to version info, if present

---

book/src/keymap.md
helix-core/src/history.rs
helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-term/src/ui/editor.rs
helix-view/src/document.rs

Another comand i use frequently: Goto last modification (Goto last buffer change in kakoune).
The key is g+; because g+. repeated last insertion.

Implement "Goto last modification" command

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-term/src/ui/picker.rs

closes #1009
Uses `space` > `t` to open a workspace wide symbol picker.

Added workspace_symbol_picker

---

book/src/keymap.md
helix-core/src/history.rs
helix-term/src/commands.rs
helix-term/src/keymap.rs

Add movement shortcut for history

---

helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/main.rs
helix-view/src/editor.rs

This allows you to exit helix with an exit code, e.g. `:cq 2`.
---
Closes https://github.com/helix-editor/helix/issues/1082.

helix-term/commands: implement cquit

---

helix-term/src/commands.rs
helix-view/src/editor.rs
helix-view/src/tree.rs
helix-view/src/view.rs

This behaves the same as Kakoune's `delete-buffer` / `db` command:
* With 3 files opened by the user with `:o ab`, `:o cd`, and `:o ef`:
* `buffer-close` once closes `ef` and switches to `cd`
* `buffer-close` again closes `cd` and switches to `ab`
* `buffer-close` again closes `ab` and switches to a scratch buffer
* With 3 files opened from the command line with `hx -- ab cd ef`:
* `buffer-close` once closes `ab` and switches to `cd`
* `buffer-close` again closes `cd` and switches to `ef`
* `buffer-close` again closes `ef` and switches to a scratch buffer
* With 1 file opened (`ab`):
* `buffer-close` once closes `ab` and switches to a scratch buffer
* `buffer-close` again closes the scratch buffer and switches to a new
scratch buffer
---
Closes …

helix-term/commands: implement buffer-close (bc, bclose)

---

helix-view/src/editor.rs

Follow-up to https://github.com/helix-editor/helix/pull/1035 -- forgot to rebase on master and use this constant prior to it getting merged.

helix-view/editor: use SCRATCH_BUFFER_NAME const

---

runtime/themes/solarized_dark.toml
runtime/themes/solarized_light.toml

Hi, I began work on a Solarized Dark theme based on the existing Solarized Light theme, and then found out that one had already been merged (this repo is moving very fast!). However, I think the current theme highlights a bit too much. It also did some weird stuff like colors string literals white. After studying the vim solarized theme that was developed by the original author of the theme, I made some adjustments to more closely match the vim theme. Here are some screenshots for comparison:
And here are the light theme changes:

Improve Solarzed Dark theme

---

runtime/themes/nord.toml

Before:
After
New color borrow from:
https://github.com/arcticicestudio/nord-jetbrains/blob/430eed72fa2d94e60a609a0a9d396aa4b3e9d0d1/src/nord.theme.json#L314
Also using italic font for comment, Err... just based on my personal habit....

improve nord theme status bar line

---

helix-term/src/commands.rs

Handle part of #1046 
In detail, the `backspace` behavior is more likely on vscode.   
Given the following example:
```
this is     def
```
If we enter `backspace` on the cursor right before `t`, the line will dedent, if we enter on the cursor right before `d`, it will just move back by one character.

Implement indent-aware delete

---

book/src/keymap.md

I was under the impression that scrolling does not work for the hover command.
I started digging in the source to figure out how to add it.
Ended up disovering the `Popup` struct and its `scroll` method, followed the refs and found the shortcuts :)
To save some time for others, I added the info to the keymap.md.

Document scrolling for hover command in keymap.md

---

helix-core/src/match_brackets.rs
helix-term/src/commands.rs
helix-term/src/ui/editor.rs

This partially solves #1072
The change allows the user to use `mm` from any position between the surrounding pair.
The idea is to traverse the tree until the leaf node for the given cursor position is found.
Once the leaf is found, we traverse the parents until we find the first surrounded parent.
This PR does not solve `m[i,a]m` from an arbitrary cursor position.

Jump to end char of surrounding pair from any cursor pos

---

helix-term/src/ui/markdown.rs
runtime/themes/solarized_dark.toml
runtime/themes/solarized_light.toml

Add mentioned by @rypervenche in [this comment](https://github.com/helix-editor/helix/pull/1105#issuecomment-971723023), the pop-up colors don't work well in the dark theme, and aren't great in the light theme either. I fixed the dark theme here. Apologies for the screenshots, I did this on my phone because I don't have my laptop with me at the moment.
And I also changed the foreground color in the menu to the base color.
I tried using the same colors in the light theme, but that did not work very well, as most of the text is violet or white, which doesn't contrast enough with the light background.
I wasn't able to find a good background color at all that worked with the theme of the docs content, and I'm not even sure what that theme is, whether it's markdown or something special. So …

Solarized theme: fix popup colors, adjust menu

---

book/src/configuration.md
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/ui/mod.rs
helix-view/src/editor.rs

Fixes #280
Connects settings from user defined config in `cargo.toml` to file picker by adding a second parameter to `file_picker()`.
This is an extensible pattern for more user defined file picker configuration options, including the option to see or ignore dotfiles, etc.
Currently sets config for file picker to hide or display files listed in `.gitignore`. 
Sets default preference to see files listed in `.gitignore`.

File picker config

---

book/src/remapping.md

This updates the remapping page to open the Keymap page of book, rather than the commands file.
I have also updated the original link to open at line #L178(opens at the invocation of `commands!` macro)

Add link to Keymap page in book.

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/keymap.rs

Select above lines, `&` and input `\|` would turn them to 
`2&` and input `\|` would turn them to 
`3&` and input `\|` would turn them to

align selections

---

helix-term/src/commands.rs

I thought this might be useful.
Digging through the code, I realized that `<line>gg` also works,
but I thought this is more convenient for *vim users.

Add `:<line>` and `:goto <line>` commands

---

languages.toml

Add language and lsp config: racket

---

helix-term/src/commands.rs

Report an error when running goto command without entering a
line number.
Fixes #1159

Do not crash when run goto command without line number

---

helix-view/src/editor.rs
helix-view/src/lib.rs

Now `Option<DocumentId>` uses one byte rather than two

Optimize space for DocumentId with NonZeroUsize

---

.gitmodules
languages.toml
runtime/queries/wgsl/highlights.scm

Tested w/ https://raw.githubusercontent.com/bevyengine/bevy/db3258264a2d2c838640cb5347ea03ec54cd9696/pipelined/bevy_pbr2/src/render/pbr.wgsl
Not totally accurate, but it should work well enough (note that line 36 is incorrectly highlighted as `@error`).

Add language support for WGSL

---

helix-core/src/selection.rs
helix-core/src/surround.rs
helix-core/src/textobject.rs

Fixes #1077. This was caused by the assumption that a block cursor is represented as zero width internally and simply rendered to be a single width selection, where as in reality a block cursor is an actual single width selection in form and function.
Behavioural changes:
1. Surround selection no longer works when cursor is _on_ a surround character that has matching pairs (like `'` or `"`). This was the intended behaviour from the start but worked till now because of the cursor position calculation mismatch.

Fix surround cursor position calculation

---

helix-term/src/commands.rs

also fix view is not fulfilled issue.
`9gt` would go to the 9th line from window top;
`3gb` would go to the 3th line from window bottom;

accept count for goto_window

---

helix-core/src/diagnostic.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/markdown.rs
helix-view/src/editor.rs
helix-view/src/gutter.rs
helix-view/src/lib.rs
helix-view/src/view.rs

Allows us to have each gutter as a separate function so that it can be extendable in the future.
I'm not sure if this is overkill or not, I don't like the closure boxing but that was the only way to put them all on a single `gutters` slice to loop over.

Gutter functions

---

book/src/install.md

The helix-bin package has been removed from the AUR, presumably as the community package makes it redundant. This PR removes the broken link from the install page

Remove defunct helix-bin AUR link

---

helix-term/src/commands.rs
helix-term/src/ui/editor.rs
helix-view/src/document.rs

close:  #1046
-------------------
And make `kill_to_line_end` behave like emacs. I found it's easiler to use for me.. And it helps resolving the issue.
> C-k kills from point up to the end of the line, unless it is at the end of a line. In that case it kills the newline following point, thus merging the next line into the current one.
here is emacs kill by line [reference](https://home.cs.colorado.edu/~main/cs1300-old/cs1300/doc/emacs/emacs_14.html#SEC56)

Improve Dedent behavior, make kill_to_line_end behaves like emacs

---

book/src/guides/adding_languages.md
helix-core/src/lib.rs

small typo on guide and `main.rs`

Fix typo on docs

---

helix-term/src/commands.rs

This is very straightforward fix for    #1205 , we can only go to a line in the range from `first_line + scrolloff ` to `min(last_line, first_line + height) - scrolloff`.
@archseer , let me know if we want to consider more cases, thanks!

fix goto_window offset crash

---

runtime/themes/monokai_pro.toml

It's highly based on jetbrains monokai pro theme https://github.com/subtheme-dev/monokai-pro
Three main files reference:
[color definition file](https://github.com/subtheme-dev/monokai-pro/blob/master/colors/default.yaml)
[language scheme definition](https://github.com/subtheme-dev/monokai-pro/blob/master/theme/jetbrains/templates/scheme.xml)
[ui definition](https://github.com/subtheme-dev/monokai-pro/blob/master/theme/jetbrains/templates/theme.json)
Here is the screenshot for `helix` and `jetbrains`:

Add monokai pro theme

---

runtime/themes/monokai_pro_machine.toml
runtime/themes/monokai_pro_octagon.toml
runtime/themes/monokai_pro_ristretto.toml
runtime/themes/monokai_pro_spectrum.toml

Since this pr #1206 is merged, maybe it's ok to complete monokai pro themes family:
These four color themes with default monokai pro theme just have different  `[palette]` color.
Original color definition: https://github.com/subtheme-dev/monokai-pro/tree/master/colors
I don't think we need `monokai_pro_classic` theme, because we already have a classic monokai theme.

complete monokai pro themes

---

helix-core/src/syntax.rs

For example:
```bash
#!/usr/bin/env -S bash ../.port_include.sh
```

Support env flags in shebang

---

helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-term/src/ui/editor.rs

Fixes: https://github.com/helix-editor/helix/issues/852
This makes it possible to add keymaps for `TypableCommands` (including aliases + commands with arguments) in your `config.toml` like the following example:
```toml
[keys.normal]
"space" = { "t" = ":earlier 5 sec", "y" = ":theme default"}
"f"  = ":format"
"C-s" = ":w"
"C-l" = "jump_view_right"
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
```
This solution is a lot less hacky than my previous pr and makes it possible to map all current and future `TypableCommands`. I decided to not go for the `[ .. ]` surround for command arguments because it would just be more of a hassle to parse with little benefit for users imo. Arguments are passed by space separating them after the initial command instead. 
**Update: …

feat: Make it possible to keybind `TypableCommands`

---

helix-term/src/commands.rs

I found it's easiler to use for me...
Reference to emacs kill_to_line_end behavior (https://home.cs.colorado.edu/~main/cs1300-old/cs1300/doc/emacs/emacs_14.html):
> C-k kills from point up to the end of the line, unless it is at the end of a line. In that case it kills the newline following point, thus merging the next line into the current one.

make kill_to_line_end behave like emacs

---

runtime/themes/solarized_dark.toml
runtime/themes/solarized_light.toml

* do not select a foreground color in selections, as this eliminates syntax coloring
* select lighter color for selections
* Make non-primary cursor cyan instead of green
* fix a typo in diagnostic highlight
primary
multiple
primary
multiple

fix solarized selection colors

---

helix-term/src/commands.rs
helix-term/src/compositor.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/popup.rs

replace old documentation popups

---

helix-term/Cargo.toml

Following the addition of `xtask`, `cargo run` has multiple possible targets, necessitating the usage of the less convenient `cargo run --bin hx` to run Helix during development. This allows `cargo run` to be used to run `hx`.

Add `default-run = "hx"` to `helix-term/Cargo.toml`

---

helix-core/src/auto_pairs.rs
helix-core/src/transaction.rs
helix-term/src/commands.rs

* Add unit tests for all existing functionality
* Add auto pairs for same-char pairs (quotes, etc). Account for apostrophe in prose by requiring both sides of the cursor to be non-pair chars or whitespace
* Slight factor of moving the cursor transform of the selection to inside the hooks. This will enable doing auto pairing with selections, and fixing the bug where auto pairs destroy the selection.
I will still be working on other things, but I thought it would be a good idea to make an incremental smaller PR for the sake of ease of review, and for providing opportunity for feedback with the approach to testing and implementation details before I build further on them.
Fixes #1014
Things I'd still like to do:
* delete implementation where it erases the whole bracket (|) -> |
* do not …

Add auto pairs for same-char pairs

---

book/src/generated/lang-support.md
runtime/queries/perl/indents.toml

It has sometimes problem indenting/outdenting the first line after a block starts/ends.

Add indents.toml to perl

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/scala/highlights.scm
runtime/queries/scala/indents.toml
runtime/queries/scala/injections.scm

Hi!
I really like helix, so I'd like to add scala syntax highlight and LSP support for it.
Amazingly, LSP support with metals works out-of-the-box, although additional metals commands like import build and others obviously needs to be added. 
I've copied the tree-sitter highlights and injections from nvim-treesitter, but found a couple of issues with it, and couldn't figure out it yet, so the syntax highlighting is partial currently. I'm happy to receive suggestions how to migrate the whole from nvim.

Add scala syntax highlights

---

.gitmodules
languages.toml
runtime/queries/dart/highlights.scm
runtime/queries/dart/indents.toml
runtime/queries/dart/locals.scm

Add basic LSP config for dart. The queries are from:
https://github.com/theHamsta/nvim-treesitter/blob/master/queries/dart/highlights.scm
The setup requires that dart be in the users path, such as:
```
export PATH="$HOME/Android/flutter/bin/cache/dart-sdk/bin/:$PATH"
```

Add dart lsp config and queries

---

.gitmodules

Fix the path to the submodule and init the submodule.

Fix tree-sitter-llvm submodule

---

runtime/queries/yaml/highlights.scm

Unquoted values that can't be interpreted as another datatype are strings, so this change highlights them as strings.
Before:
After:

Improve yaml syntax highlighting

---

book/src/themes.md
runtime/queries/latex/highlights.scm
runtime/queries/markdown/highlights.scm
runtime/queries/svelte/highlights.scm
theme.toml

- Rename markup.underline.link to markup.link.url
- Add markup.link.label
- Add markup.quote
(The constructor theme scope was missing from the docs, so unrelated to this PR).

Add link and quote queries for markdown

---

runtime/queries/c/injections.scm
runtime/queries/cmake/injections.scm
runtime/queries/cpp/injections.scm
runtime/queries/glsl/injections.scm
runtime/queries/llvm/injections.scm

Also, reuse the c injections in glsl.

Highlight comments in c, cpp, cmake and llvm

---

runtime/queries/rust/highlights.scm

- Highlight fragment specifiers (expr, tt, in macro definitions) with @type.
- Highlight attributes as macros.
| --- | --- |
| ![before-rust](https://user-images.githubusercontent.com/23398472/146651130-019036c6-3245-4a49-9454-e18d4db92538.png) | ![after-rust](https://user-images.githubusercontent.com/23398472/146651133-44ba5d63-0896-43de-9547-ade09db8bd0e.png) |
Note that it looks drastic for onedark only from what I tested since it doesn't define some punctuation highlights.

Improve rust macro highlighting

---

book/src/guides/adding_languages.md

Inspired from https://github.com/helix-editor/helix/pull/1170#issuecomment-997294090.

docs: Add note about tree-sitter query precedence

---

helix-core/src/auto_pairs.rs
helix-core/src/selection.rs

Previously, the auto pairs code was converting the user selection into its cursor form, and setting the transaction's selection to that cursor. This has the effect of destroying the user's selection if they type a pair character that gets auto completed.
This fixes the code to work with the user's selection, inserting auto pairs where appropriate, but either keeping or extending the user's selection.
This PR is built on top of #1219, so this PR includes commits from there as well until it is merged. I'll mark it as a draft until then.

Auto pairs selection

---

helix-term/src/commands.rs
helix-term/src/ui/editor.rs
helix-view/src/document.rs

handle the remaining of #1046 :  Hitting o to go to a new line auto indents. If you then immediately hit Esc, it should delete all of the whitespace and just leave a blank line.

Improve Dedent behavior

---

helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-term/src/application.rs
helix-term/src/commands.rs

This is work in progress PR that implements LSP commands. Usable for example for code actions and code lens.
Fixes: https://github.com/helix-editor/helix/issues/1299
Related: https://github.com/helix-editor/helix/issues/183

feat(lsp): commands

---

languages.toml

Many folks use `.dockerfile` as an extension for dockerfiles in addition to plain `Dockerfile`. This change associates both file extensions with dockerfile syntax highlighting

languages: add .dockerfile extension

---

runtime/queries/rust/highlights.scm

- Differentiates between `as` keyword as a binary type cast operator and import renamer.
- `mod` and `use` are now under `@keyword.control.import`, but `mod` is a `@keyword` if used as `mod name;`.

Add precise rust queries for use, mod, as

---

runtime/queries/ocaml/indents.toml

Typo fix in ocaml indents.toml

---

runtime/themes/onedark.toml

(Uses `markup.link.label` from #1296, so it should be merged first.)

Update onedark theme to use new scopes

---

languages.toml

`loadOutDirsFromCheck` is now called `runBuildScripts` and has been enabled by default for 10 months. And proc macros are enabled in upstream by default, so maybe there's no particular reason to disable them?
https://user-images.githubusercontent.com/308347/147342914-e8643820-6d71-4ec6-85fc-032df5960eb5.mp4

Enable Rust proc macro support

---

helix-term/src/ui/editor.rs

Fixes the same issue as in [#945](https://github.com/helix-editor/helix/issues/945) but for the StatusLine.
Before:
We can see that the file name is truncated, while this is more important to the user than the path.
And in the second red rectangle, we can see that the letters "od" from the path is rendered outside of the statusline area.
After:

Truncate the start of file paths in the StatusLine

---

book/src/guides/adding_languages.md
book/src/languages.md
helix-core/src/diagnostic.rs
helix-core/src/indent.rs
helix-core/src/syntax.rs
helix-term/src/application.rs
helix-view/src/document.rs

Allow severity of diagnostic messages to be configured.
E.g. allow turning of Hint level diagnostics.
Fixes: https://github.com/helix-editor/helix/issues/1007

feat(lsp): configurable diagnostic severity

---

helix-lsp/src/client.rs
helix-term/src/ui/completion.rs

This one solves the issue: [1313](https://github.com/helix-editor/helix/issues/1313)
That is my first contribution to a Rust project, and to this project, so I'm really open to receive suggestions 😄 
Talking about the solution, I adopted the suggestions that I received on the Matrix chat, from the user "archseer".
The suggestion was to request the language server directly from `Completion` component, and use `block_on` since this component does not have any way of enqueuing async jobs yet.

Resolve completion item

---

book/src/generated/lang-support.md
runtime/queries/cmake/indents.toml
runtime/queries/cmake/textobjects.scm

Indentation and parameter selection works well.
Function selection doesn’t work, my guess is that something is weird with the cmake grammar.
(Also, I wasn’t able to add a matcher for `@function.inside` because there is no dedicated element for that. The tree is just `(macro_def (macro_command) (<body node>) (<more body nodes>) … (endmacro_command))`.)

Add textobjects and indents to cmake

---

Cargo.lock
helix-core/Cargo.toml
helix-core/src/lib.rs
helix-term/Cargo.toml
helix-term/src/ui/editor.rs
helix-view/Cargo.toml
helix-view/src/document.rs

Display file encoding in statusline if the encoding isn't UTF-8.
---
I assume this will be configurable in the future with the rest of the statusline but for now this seems like a reasonable step in between, hopefully with reasonable default.

feat(ui): file encoding in statusline

---

book/src/generated/typable-cmd.md
helix-term/src/commands.rs
helix-term/src/ui/mod.rs
helix-view/src/editor.rs

Hello,
I would love to add this feature to helix, but there are multiple issues that I don't know how to solve currently.
1. I'm currently deserializing and re-serializing the same struct [over](https://github.com/helix-editor/helix/compare/master...irevoire:settings_at_runtime?expand=1#diff-d782c07f22492bcae17333aba5dc5b840fb30317727e71267ebf4863f84787fdR2093-R2103) and [over](https://github.com/helix-editor/helix/compare/master...irevoire:settings_at_runtime?expand=1#diff-a2f72be0dae9186774ac716ae568f5216a5223dbf91e6ac8a25f62617c4fa55cR187-R192) again.
I can see multiples solutions here, but I'm not a fan of either of them:
* We could do a `match` on the `keys` of the deserialized conf and updates the `current_conf` accordingly:
```
let conf = toml::from_str::<Map<String, …
```

Update settings at runtime

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-view/src/input.rs

cc @Omnikar 
This does not solve the macro internal representation issues but it should be a quick fix for now for some of the issues mentioned in #1234 
Leftover

Refactor macros and mark as experimental

---

book/src/generated/typable-cmd.md
helix-term/src/commands.rs

Add basic implementation of sort command.
This PR adds `sort` and `sort!` (reverse sort) commands that sort _selections_. This can be used to not only sort data on separate lines (select -> split on new line `Alt-s` -> `:sort`) but also any arbitrary list (select -> select all matches, for example numbers `\d+` -> `:sort`).
Additional functionality can be added in the future such as removing duplicates, case insensitivity, etc.
---
edit: provide better description for the PR

feat(commands): sort command

---

helix-core/src/selection.rs
helix-term/src/commands.rs
helix-term/src/keymap.rs

Add `ensure_selections_forward` command and bind it to `A-:` by default.
Fixes: https://github.com/helix-editor/helix/issues/1332

feat(commands): ensure_selections_forward

---

helix-term/src/commands.rs

For me this is a nice quality of life improvement that helps with discoverability of commands. Open to other points of view though 😄

Use a fuzzy matcher for commands

---

book/src/generated/lang-support.md
runtime/queries/llvm/highlights.scm
runtime/queries/llvm/indents.toml
runtime/queries/llvm/locals.scm
runtime/queries/llvm/textobjects.scm

The llvm tree-sitter parser was updated to support scopes and more
accurate highlighting: https://github.com/benwilliamgraham/tree-sitter-llvm/pull/1

Improve llvm highlighting and queries

---

helix-term/src/ui/mod.rs

The addition of shellwords included support for escaping, which breaks windows style paths in the prompt.
This change converts backslashes to slashes for directories if helix is on windows.
According to the video in the issue tracker, unix style paths work fine there too.
I couldnt test this. 
Issue #1380

Convert Windows style path separator in completers to Unix style

---

.gitmodules
book/src/generated/lang-support.md
languages.toml
runtime/queries/git-commit/highlights.scm
runtime/queries/git-commit/injections.scm
runtime/queries/git-diff/highlights.scm

primarily meant to be used in verbose commit diffs with the injections:
but I also added config for it to be used on `*.diff` files.
There was a fun bug to hunt down in the grammar that prevented me from including it on #1338 (see https://github.com/helix-editor/helix/pull/1338#issuecomment-1000626113), but I fixed that in this commit: https://github.com/the-mikedavis/tree-sitter-git-commit/commit/066e395e1107df17183cf3ae4230f1a1406cc972 (actually, the one in the screenshot above ^^), and now the injections seem to be working really well :tada:

add tree-sitter-git-diff

---

helix-core/src/lib.rs
helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-term/src/commands.rs
languages.toml

Implement workspace root detection based on https://github.com/helix-editor/helix/issues/256#issuecomment-1001039937

Detect workspace root using language markers

---

runtime/queries/markdown/injections.scm

Markdown code blocks should be highlighted as a single block, so set
`injection.include-children`.
**Before**
**After**

Fix markdown code-block highlighting

---

runtime/themes/bogster.toml

Diagnostics (warnings, errors) are undisinguishable from selections when using the `bogster` theme.
This PR highlights diagnostics by underlining them instead.
I understand that this is subjective and personal taste, so feel free to ignore the PR.

Underline diagnostics in bogster theme

---

.gitmodules
book/src/generated/lang-support.md
languages.toml
runtime/queries/tablegen/highlights.scm
runtime/queries/tablegen/indents.toml
runtime/queries/tablegen/injections.scm
runtime/queries/tablegen/textobjects.scm

Here comes yet another llvm grammar.
Add a tree-sitter grammar and highlights for TableGen files.
TableGen and its grammar are described here:
https://llvm.org/docs/TableGen/index.html

Add LLVM TableGen highlighting

---

helix-core/src/indent.rs
helix-term/src/commands.rs
runtime/queries/rust/indents.toml

Previously, when there was no treesitter grammar and `indents.toml` for a language, new lines had no indentation. This changes it, so that as a fallback, the indentation of the current line is used.
While changing this, I also noticed a few issues with the treesitter indentation handling, which I also fixed where possible:
There was an off-by-one error in the position used for the indent query, which caused a line to be indented too much:
```rust
fn test() { 0 |}
```
When pressing Enter with this cursor position, the closing brace was indented too much:
```rust
fn test() { 0 
|}
```
There was also an issue where the result of the indent query was influenced by the presence/absence of nodes that are not specified in `indents.toml`. For example, these 2 cursor positions resulted in …

Add basic indentation handling as a fallback for treesitter queries

---

helix-lsp/src/lib.rs

optimize lsp_pos_to_pos

---

book/src/generated/typable-cmd.md
helix-term/src/commands.rs

`:cquit` no longer ignores unsaved changes, and `:cquit!` is added to replace that behaviour. Also updated the signature of `quit_all_impl` and made `:cquit` implementation use it.

Add `:cquit!` command and prevent `:cquit` from ignoring unsaved changes

---

helix-term/src/commands.rs

Fixes #917.
* Scrolling will never change secondary selections.
* Primary selection is replaced with a single char selection when the cursor gets out of view.
This is the same behavior as in Kakoune. I believe in vim / nvim it would grow / shrink the main selection instead of deleting it.

Scrolling view keeps selections

---

.gitmodules
book/src/generated/lang-support.md
helix-core/src/indent.rs
helix-core/src/syntax.rs
languages.toml
runtime/queries/llvm-mir-yaml/highlights.scm
runtime/queries/llvm-mir-yaml/indents.toml
runtime/queries/llvm-mir-yaml/injections.scm
runtime/queries/llvm-mir/highlights.scm
runtime/queries/llvm-mir/indents.toml
runtime/queries/llvm-mir/injections.scm
runtime/queries/llvm-mir/textobjects.scm
runtime/queries/yaml/injections.scm

LLVM Machine IR is dumped as yaml files that can embed LLVM IR and
Machine IR.
To support this, add a llvm-mir-yaml language that uses the yaml
parser, but uses different injections to highlight IR and MIR.

Add llvm-mir highlighting

---

book/src/generated/lang-support.md
runtime/queries/c/indents.toml
runtime/queries/c/textobjects.scm
runtime/queries/cpp/indents.toml
runtime/queries/cpp/textobjects.scm

Somehow, indentation inside conditions doesn't work, i.e.
```
while (1 +<hit enter>)
```
leads to
```
while (1 +
)
```
but the expected result should be
```
while (1 +
)
```
But it is a lot better than before.

Add textobjects and indents to c and cpp

---

helix-term/src/commands.rs

Quick one: fixes status message to reference correct register

Fix slash in search selector status message

---

runtime/queries/nix/highlights.scm

null and boolean literals were previously detected as `variable.builtin`. This PR fixes this and detects these as:
`constant.builtin` and `constant.builtin.boolean` respectively

Fix null and boolean constants in tree-sitter-nix highlights queries

---

book/src/keymap.md
helix-core/src/object.rs
helix-core/src/selection.rs
helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-view/src/document.rs
helix-view/src/view.rs

Add `shrink_selection` command that can be used to shrink previously expanded selection.
To make `shrink_selection` work it was necessary to add selection history to the Document since we want to shrink the selection towards the syntax tree node that was initially selected.
Selection history is cleared any time the user changes selection other way than by `expand_selection`. This ensures that we don't get some funky edge cases when user calls `shrink_selection`.
Related: https://github.com/helix-editor/helix/discussions/1328

feat(commands): shrink_selection

---

.gitmodules
book/src/generated/lang-support.md
languages.toml
runtime/queries/elixir/injections.scm
runtime/queries/regex/highlights.scm
runtime/queries/rust/injections.scm

Example injected into elixir
it's a pretty subtle improvement; I'm not too impressed yet. Let me dig into the grammar and see if we can write some more interesting queries beyond brackets and quantifiers.

add tree-sitter-regex

---

book/src/themes.md

The specifics of configuring themes has caused some confusion. Hopefully this will clarify things a little.
This change is intended to make it clearer that the position of the theme line in config.toml is important and that the value should be quoted as per the toml spec. Also, it was surprising to one user that the theme name "default" cannot be re-used for a custom user theme.

Rework beginning of themes chapter

---

book/src/generated/lang-support.md
languages.toml

The [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server) supports both JavaScript and TypeScript. We can use it as the default language server for JavaScript as well.

Add default language server for JavaScript

---

book/src/themes.md
runtime/queries/markdown/highlights.scm
theme.toml

captures the [text](https://github.github.com/gfm/#link-text) part of a link as a new scope, such as in these examples
```
[documentation](http://example.org)
```
cc @sudormrfbin (since I saw you on https://github.com/helix-editor/helix/pull/1296)

capture markdown link text as markup.link.text

---

helix-syntax/build.rs
runtime/queries/haskell/highlights.scm

I've made changes to `tree-sitter-haskell` that remove the need for c++14. It now happily compiles with c++11.
I think this is ubiquitous enough to reenable it by default?

Upgrade and reenable tree-sitter-haskell

---

.gitmodules
book/src/generated/lang-support.md
book/src/themes.md
languages.toml
runtime/queries/make/highlights.scm

This commit adds syntax highlighting for GNU Make[^1] makefiles
via tree-sitter-make[^2].
[^1]: https://www.gnu.org/software/make/
[^2]: https://github.com/alemuller/tree-sitter-make

feat: add tree-sitter-make

---

helix-core/src/object.rs

builds on the work in #919 so we can expand selections when on a terminal node of the tree.
before:
https://user-images.githubusercontent.com/21230295/148426748-8c176c09-db2f-4faf-b948-f44035cc9c80.mp4
after:
https://user-images.githubusercontent.com/21230295/148426755-383cf8c9-a3b2-4923-92f3-703ab18541b0.mp4
Where in this case the tree looks like
```tsq
(arguments (identifier) (identifier))
```
So expand_selection will grow the current selection to fit the node (`(identifier)`), or grow to the parent (`(arguments (identifier) (identifier))`) if the current node is already _fully_ selected. IMHO this is more intuitive. What do you think?

expand_selection to current node with no children

---

book/src/configuration.md

Using `editor.filepicker` results in this error:
```
Bad config: unknown field `filepicker`, expected one of `scrolloff`, `scroll-lines`, `mouse`, `shell`, `line-number`, `middle-click-paste`, `smart-case`, `auto-pairs`, `auto-completion`, `idle-timeout`, `completion-trigger-len`, `auto-info`, `file-picker`, `true-color` for key `editor` at line 6 column 1
Press <ENTER> to continue with default config
```

Update config docs: editor.filepicker -> editor.file-picker

---

.gitmodules
book/src/generated/lang-support.md
languages.toml
runtime/queries/git-config/highlights.scm

Since I spend so much time looking at `.gitmodules` I thought it should have some highlighting :smile:
Luckily git uses this config syntax for virtually all config, so this grammar applies to things like `~/.gitconfig` as well.
I think this is a good grammar to start asking questions about expanding the `file-types` config in `languages.toml`. Ideally this grammar would apply for `.git/config`, `~/.config/git/config`, and other `config` files under a git directory (for example: `.git/modules/helix-syntax/languages/tree-sitter-git-config/config`). I'm fine leaving off changes to language detection in this PR but it's something to think about.
Playground for the grammar: https://the-mikedavis.github.io/tree-sitter-git-config/

add tree-sitter-git-config

---

helix-term/src/commands.rs

Allow using `Ctrl-v` and `Ctrl-s` in the buffer picker to open in a split view, just like in the file picker
(idk why it wasn't the case, probably an oversight during 5c2d2fda)

small fix: buffer picker allow hsplit / vsplit

---

languages.toml

(super tiny PR)
The grammer works fine for scss files to and it is better than no hihglighting at all.

feat(languages): enable css tree-sitter for scss files

---

runtime/themes/gruvbox_light.toml

Similar to `gruvbox`, add the light version as well.

Add gruvbox-light theme

---

runtime/queries/php/highlights.scm

Brings in PHP 8.1 features, like enums, union types and the like.

Update tree-sitter-php to latest upstream

---

helix-term/src/commands.rs
languages.toml

https://user-images.githubusercontent.com/21230295/148418001-fde4c441-6f20-4365-9893-3696982f3670.mp4
I have this setup for testing but I'm not sure this command really deserves a default binding in the `space+<command>` submap:
```diff
diff --git a/helix-term/src/keymap.rs b/helix-term/src/keymap.rs
index 49f8469..3050315 100644
--- a/helix-term/src/keymap.rs
+++ b/helix-term/src/keymap.rs
@@ -677,6 +677,7 @@ impl Default for Keymaps {
"R" => replace_selections_with_clipboard,
"/" => global_search,
"k" => hover,
+                "t" => show_subtree,
"r" => rename_symbol,
},
"z" => { "View"
```
I kinda just did whatever the rust compiler told me to do, there's probably some wacky stuff in here :sweat_smile:. In particular the two nested levels of `if let Some(...)` feel a little clumsy, …

add show_subtree command for viewing tree-sitter subtree in Popup

---

runtime/themes/gruvbox.toml
runtime/themes/gruvbox_light.toml

As recommended by @archseer in https://github.com/helix-editor/helix/pull/1509#issuecomment-1013583069

Add `markup.` scopes in `gruvbox` themes

---

helix-term/src/keymap.rs

I'm missing [M-BACKSPACE](https://www.gnu.org/software/emacs/manual/html_node/emacs/Erasing.html), [M-< and M->](https://www.gnu.org/software/emacs/manual/html_node/emacs/Moving-Point.html) in emacs..
With `M-<` and `M->`, we can move cursor without goto normal mode.
Although they can be configured in config, I still want to make it builtin.....

add alt-backspace, alt-<, alt->, ctrl-j keymap to delete word backward, goto file start, goto file end, insert newline

---

runtime/themes/dracula.toml

Modifies the background color in the dracula theme so popup boundaries are clear. 
Before
After
Still a bit low contrast, so happy to iterate on color, but vastly better having it distinguished. cc @loewenheim

Add modified background to dracula popup

---

helix-term/src/ui/editor.rs
helix-term/src/ui/menu.rs
helix-term/src/ui/picker.rs
helix-term/src/ui/prompt.rs
helix-tui/src/backend/test.rs
helix-tui/src/buffer.rs
helix-tui/src/widgets/block.rs
helix-tui/src/widgets/paragraph.rs
helix-view/src/graphics.rs

FIxes #1403
The editor crashes when the window is very small. Two reasons:
- some widgets have a minimum size (e.g. boxes) -> integer calculations may overflow.  
- buffer panics when accessed out-of-range
* Changed `Buffer::get` and `Buffer::get_mut` to return an Option, like `std::Vec`
* Implemented traits `Index` and `IndexMut` for Buffer with a pair of coordinates, i.e. `buf[(x, y)]`
* Replaced calls to `Buffer::get` and `Buffer.get_mut` with the Index, which is known to panic. Makes code clearer with the intent not to perform bounds checks.
* Fixed a few divisions by zero and integer substraction underflows.

Panics when resizing

---

.gitmodules
book/src/generated/lang-support.md
languages.toml
runtime/queries/lean/folds.scm
runtime/queries/lean/highlights.scm
runtime/queries/lean/injections.scm
runtime/queries/lean/locals.scm

Trying out the experimental tree-sitter-lean from @Julian

feat(languages): Lean experimental tree-sitter-lean

---

.gitmodules
book/src/generated/lang-support.md
languages.toml
runtime/queries/elm/highlights.scm
runtime/queries/elm/injections.scm
runtime/queries/elm/locals.scm
runtime/queries/elm/tags.scm

Hey there,
This PR adds support for [Elm](https://elm-lang.org/)!

feat(languages): Elm

---

book/src/keymap.md
helix-core/src/object.rs
helix-term/src/commands.rs
helix-term/src/keymap.rs

builds on expand_selection and shrink_selection to move to next and previous sibling nodes in the syntax tree
mostly I'm interested in all four of those together an alternate means of motion, like so:
https://user-images.githubusercontent.com/21230295/149166562-e79d1717-87c2-4d95-af04-9812c3c0a998.mp4
Where I have
- `A-j` shrink selection
- `A-k` expand selection
- `A-h` select prev sibling
- `A-l` select next sibling
in my personal config. I don't know if these commands are worthy of a default keybind :thinking:
What do you think?

add select_next_sibling and select_prev_sibling commands

---

.gitmodules
book/src/generated/lang-support.md
languages.toml
runtime/queries/graphql/highlights.scm
runtime/queries/javascript/injections.scm

Hey there,
This PR adds support for Graphql!

feat(languages): GraphQL

---

runtime/themes/dracula.toml

This adds markup scopes to the dracula theme according to [the spec](https://spec.draculatheme.com/#sec-Markup-Markdown-RST-etc-).

dracula theme: add markup support

---

runtime/themes/gruvbox.toml

Missed in the commit 943fca332e.
This is a follow up to: https://github.com/helix-editor/helix/pull/1518#discussion_r785316711

Add `tag` to gruvbox theme

---

book/src/generated/lang-support.md
languages.toml

After the changes to upgrade and reenable tree-sitter-haskell #1417
for the purpose of enabling Haskell syntax highlighting #1384, we
might as well take the final step.

Add haskell-language-server-wrapper --lsp to default `languages.toml`

---

helix-core/src/position.rs
helix-term/src/application.rs
helix-term/src/args.rs
helix-term/src/commands.rs
helix-term/src/main.rs

Like helix-term/src/commands.rs:3426:15

Allow specifying file start position

---

helix-term/src/ui/picker.rs

Created another pull request because #1546 was stuck.

Fix picker won't scroll down when it hits the bottom #1544

---

book/src/themes.md
helix-term/src/commands.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/markdown.rs

The PR add some style to markdwon ui to make the theme can be changed.
before:
after:

improve  markdown's ui theme

---

languages.toml

https://github.com/helix-editor/helix/commit/7d510429c564d216b4f1419b37a37cf7384f49c0 missed .bash_profile

Enable tree-sitter for .bash_profile

---

runtime/themes/serika-dark.toml
runtime/themes/serika-light.toml

A theme inspired by [monkeytype](https://monkeytype.com/) and [this Atom theme](https://github.com/arturoalviar/serika-syntax) which was based off the [GMK Serika keycap](https://zambumon.com/serika/) set by Zambumon.
A slight twist on the other takes I took was to use quite subtle shades on the colors as I did want to interfer with the dichromacity of the theme base as less as possible.
This might change a bit over a few future iterations to optimise the experience over time.
Any feedback welcome.

[theme] Serika light and dark

---

.gitmodules
book/src/generated/lang-support.md
languages.toml
runtime/queries/iex/highlights.scm
runtime/queries/iex/injections.scm

This is a pretty small grammar for Interactive Elixir (IEx), the repl for elixir. It's perfect to add new because of the recently merged combined injections support :tada:. For example, these examples need combined injections in order to be properly parsed:
connects #1378

add tree-sitter-iex

---

runtime/themes/rose_pine.toml
runtime/themes/rose_pine_dawn.toml

To fix the 2 rose_pine themes' popup bg color as

chore(theme): fix rose_pine/rose_pine_dawn themes' popup bg color

---

helix-view/src/editor.rs

Looks like it checked the wrong doc id when setting last modified doc.

Fix incorrect last modified behavior

---

helix-term/src/commands.rs
helix-term/src/compositor.rs

(The large diff is due to replacing an if let match with an early return).

Preselect first item in code action popup menu

---

helix-core/src/register.rs
helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-term/src/ui/editor.rs
helix-view/src/editor.rs
helix-view/src/info.rs

Show infobox with register contents

---

helix-term/src/commands.rs
helix-term/src/ui/mod.rs
helix-view/src/editor.rs

Adds configuration for search wrap around and moves search config into separate config struct.
Fixes: https://github.com/helix-editor/helix/issues/1489

feat(editor): add config for search wrap_around 

---

helix-term/src/commands.rs

I've been reading the source code of the helix and noticed that there is one unnecessary clone of the iterator. The clone can be placed after the name is matched to make the matching more efficient.

refactor: postpone the clone of iterator

---

.gitmodules
book/src/generated/lang-support.md
languages.toml
runtime/queries/erlang/highlights.scm
runtime/queries/erlang/injections.scm

I was touching up a fork of [AbstractMachinesLab/tree-sitter-erlang](https://github.com/AbstractMachinesLab/tree-sitter-erlang/) for a while but I ended up writing from scratch to fix some composability problems with the rules. That also gave me an opportunity to structure the rules a bit more "tree-like", so this grammar responds well to the `A-j/k/h/l` motions:
https://user-images.githubusercontent.com/21230295/153741374-a2754163-c9db-4011-8dae-6512343106d0.mp4
playground: https://the-mikedavis.github.io/tree-sitter-erlang/
I know that there's an Erlang LSP but I haven't tried it out yet. I'll make a follow-up PR if my tests go well.

add tree-sitter-erlang

---

helix-term/src/commands.rs
helix-term/src/ui/mod.rs

Fixes #1646 #1569
Also preemptively changes other uses of `as_str()` because they look like places where a similar panic would happen.

use PathBuf::to_string_lossy() instead of to_str()

---

book/src/keymap.md
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/overlay.rs
helix-term/src/ui/picker.rs

Add `PageUp`, `PageDown`, `Ctrl-u`, `Ctrl-d`, `Home`, `End` keyboard shortcuts to file picker

---

book/src/guides/textobject.md
book/src/keymap.md
book/src/usage.md
helix-core/src/movement.rs
helix-core/src/syntax.rs
helix-core/src/textobject.rs
helix-term/src/commands.rs
helix-term/src/keymap.rs

Adds support for navigating between functions, classes, etc, using tree-sitter and textobjects. Requires that a `*.around` capture is defined for a filetype in it's correspoding `textobjects.scm` file. So for goto next function to work in Rust, `function.around` textobject has to be defined in Rust's `textobjects.scm`.
<details>
<summary>Added keybinds (click to expand)</summary>
| Keybind | Description|
| ---| --- |
| `]f`     | Go to next function |
| `[f`     | Go to previous function |
| `]c`     | Go to next class |
| `[c`     | Go to previous class |
| `]p`     | Go to next parameter |
| `[p`     | Go to previous parameter |
</details>
- Should we fall back to using the inside textobject if around is not defined ? Currently `parameter.around` is not defined in any query file, so …

Add tree-sitter based function, class navigation

---

runtime/themes/base16_default_dark.toml
runtime/themes/base16_default_light.toml
runtime/themes/base16_terminal.toml

Fixes #1665
Not 100% confident here but it seems like the right idea?

Fix hover menu item text color in base16 themes

---

helix-term/src/commands.rs
helix-term/src/commands/dap.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/picker.rs
helix-term/src/ui/prompt.rs
helix-view/src/lib.rs

Closes https://github.com/helix-editor/helix/issues/1043.

Buffer complete

---

helix-term/src/commands.rs
helix-term/src/keymap.rs
helix-term/src/ui/editor.rs

Add new command to display command pallete that can be used
to discover and execute available commands.
Fixes: https://github.com/helix-editor/helix/issues/559

feat(commands): command palette

---

helix-term/build.rs

Noticed this when building with a derivation very similar to the one in nixpkgs (https://github.com/the-mikedavis/dotfiles/blob/4767713774fb87b369725585719c75c334ca92a0/overlays/helix.nix): the git hash comes out to the empty string :thinking:. The next line takes a `[..8]` slice of the string so it ends up panicing.
In this case I think it makes sense to leave the revision out of the version string.

helix-term build: check git command's exit code

---

helix-term/src/ui/mod.rs

Some users (including myself) want to turn off filtering of files
prefixed with `.`, as they are often useful to edit. For example, `.env`
files, configuration for linters `.eslint.json` and the like.

Always ignore the .git directory in file picker

---

book/src/themes.md
helix-term/src/commands/lsp.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/markdown.rs
runtime/queries/markdown/highlights.scm

This makes it possible to use separate styles for each markup heading level:
I've never worked with tree sitter before, so someone might want to confirm that `highlights.scm` is okay.
adresses #1597

Allow separate styles for markup headings

---

runtime/themes/everforest_dark.toml
runtime/themes/everforest_light.toml

Update `everforest_dark` and `everforest_light` to use correct markup styles and make use of `markup.heading.marker`:

Update markup styles for everforest theme

---

book/src/configuration.md
helix-core/src/auto_pairs.rs
helix-core/src/indent.rs
helix-core/src/syntax.rs
helix-term/src/commands.rs
helix-view/src/document.rs
helix-view/src/editor.rs
languages.toml

Implements configuration for which pairs of tokens get auto completed.
In order to help with this, the logic for when *not* to auto complete has been generalized from a specific hardcoded list of characters to simply testing if the next/prev char is alphanumeric.
It is possible to configure a global list of pairs as well as at the language level. The language config will take precedence over the global config. This is specifically intended to address and close #992 and #1347; it adds a pair mapping to the Rust section of the default `languages.toml` that excludes single quotes.
I had some ideas for more sophisticated configs for pairings, such as lexical rules, tree-sitter node lineage, etc, but I think these can be separate PRs. In particular, I'd really like to add a rule for checking a …

impl auto pairs config

---

.gitmodules
book/src/generated/lang-support.md
languages.toml
runtime/queries/hcl/folds.scm
runtime/queries/hcl/highlights.scm
runtime/queries/hcl/indents.toml
runtime/queries/hcl/injections.scm

Queries based on the neovims ones: https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/hcl and modified for helix support.
I am making use of a couple of scopes that are used by other queries but not listed in the themes page. `@none` and `@punctuation.special` not sure if these are not valid or just missing from the docs.

Add support for HCL language

---

helix-term/src/commands/lsp.rs

Shows an "LSP not active" message if goto definition, etc are invoked in a buffer without a running LSP. `editor` and `doc` are both passed to the `language_server!()` macro to avoid borrowck issues.

Alert if LSP is inactive when command is invoked

---

runtime/themes/rose_pine.toml
runtime/themes/rose_pine_dawn.toml

Fix "ui.selection" of rose_pine themes as
before
after

chore(theme): fix "ui.selection" for rose_pine themes

---

helix-core/src/surround.rs
helix-term/src/commands.rs

Shows errors for example when surround pairs cannot be found with replace and delete instead of failing silently. Also fails instantly with replace if the character to replace is not found. For example if the text is `(word)` with cursor on `o`, `mr{[` will fail as soon as `{` is pressed instead of waiting for the whole input.
Partially addresses #1589.

Show surround delete and replace errors in editor

---

helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-term/src/application.rs

This partially fixes #1268, LSP configuration should now work with all servers (tested with texlab). Even though we don't yet allow for changing settings on the fly, providing the `workspace/didChangeConfiguration` capability has some advantages:
- Some servers might continuously request the configuration if the capability isn't defined, in case any settings change.
- The client receives the configuration even if it doesn't request it by itself, because we send a notification immediately after initialization. This is (probably) not required by the spec but Neovim does it as well.

Implement LSP `workspace/configuration` and `workspace/didChangeConfiguration`

---

book/src/configuration.md

I copied the wording for `wrap-around` out of the source, hope this is fine.

Bring configuration documentation up to date (missing editor.search section)

---

helix-term/src/ui/mod.rs

Mainly removes an unwrap that was unlikely to panic, but wouldn't need to regardless, and adds some comments to help anyone reading the code.

Minor cleanup of file picker file gathering logic

---

helix-term/src/commands.rs
helix-term/src/ui/editor.rs
helix-view/src/editor.rs

We should probably add to the status area as well, but this is a significant improvement in discoverability for textobject surround selection.

Show infobox to hint textobjects with `mi` and `ma`

---

book/src/generated/typable-cmd.md
helix-term/src/commands.rs

These are convenience methods for cleaning up accumulated buffers as described in #1637.
This could probably be further cleaned up to unify the buffer_close_impl in a way that works for all of the various buffer closing commands, but for now this is effective in my testing. Also I ran out of time, and wanted to get something up. Feel free to rip apart and I'll address later.

Implement bulk buffer closing commands

---

helix-core/src/syntax.rs

Treesitter captures can contain multiple nodes like so:
```
(line_comment)+ @comment
```
This would match each line in a comment as a separate `@comment` capture when what we actually want is the whole set of contiguous `line_comment` nodes to be captured under the `@comment` capture. This commit enables this behavior. Also required for making `comment.around` textobject (#1605) work.
Note that some cases of multi node capture is not implemented yet, see the commented out test cases for more.
/cc @EpocSquadron

Allow capturing multiple nodes in textobject queries

---

helix-term/src/ui/mod.rs

Should fix #1625
I'm not sure if this is everything that is required (i.e. if I missed some edge cases), I'm not yet deep into the codebase...
But so far everything seems to be working fine for me.
One thing I noticed with this change, is that if in selection mode and extending (`extend_search_next, extend_search_previous`), this is also added into the jumplist, I'm not sure if this good or bad (I like it for now, which is why I left it as is)

Add jumplist support for the search (closes #1625)

---

book/src/generated/lang-support.md
languages.toml

Using terraform-ls and enables auto-format support. Also adds tfvars as an extra filetype.

Add terraform lsp support

---

.github/workflows/cachix.yml
book/src/install.md

closes #1717 
based on https://github.com/cachix/install-nix-action/tree/b2b9fc6cf9ad2446d49c06143ad34b98bf73be99#usage-with-flakes
I grabbed the `helix` cache on Cachix. I'll need to coordinate with @archseer to get the auth token secret set up in actions.

add workflow for pushing nix flake artifacts to Cachix

---

helix-term/src/commands.rs
helix-term/src/commands/lsp.rs
helix-term/src/compositor.rs

This was last known to be working with 5995568c at the time of commit, but now doesn't work with latest rust stable.
The issue probably stems from using `std::any::type_name()` for finding a component in the compositor, for which the docs explicitly warn against considering it as a unique identifier for types. `replace_or_push()` takes a boxed `Component` and passes it to `find_id()` which compares this with a bare Component. `type_name()` returns `Box<T>` for the former and `T` for latter and we have a false negative. This has been solved by using a generics instead of trait objects to pass in a `T: Component` and then use it for comparison.
I'm not exactly sure how this worked fine at the time of commit of 5995568c; maybe the internal implementation of `type_name()` changed to properly …

Fix bug with auto replacing components in compositor

---

helix-term/src/commands.rs

refactor align_selection using kakoune logic

---

flake.lock
flake.nix

Before this PR, the helix flake created two separate entries of `nixpkgs` in `flake.lock`.
This PR fixes this issue.

Add `inputs.nixpkgs.follows` to `rust-overlay` in `flake.nix`

---

flake.nix

closes #1746
The queries for Go were updated in ddbf03613d5a3dd64f3f5ba13795e70c29297837.
The old ref was before this commit, so running helix from the flake
nix flake run github:helix-editor/helix/d62ad8b595a4f901b9c5dba1bb6e8f70ece395bf -- path/to/file.go
will crash because the old grammar's query analysis will fail (because `iota`
was not yet a named node).
This commit updates the version of the grammars that we pull down when building
the flake so that the queries match the grammars. We'll have to do an update like
this whenever a grammar is bumped in a breaking way (which happens fairly often
in tree-sitter) until #1659 comes along and the version of the grammar becomes
tied to the version declared in source.

update helix-syntax revision in flake.nix

---

book/src/guides/textobject.md
book/src/keymap.md
book/src/usage.md
helix-term/src/commands.rs
helix-term/src/keymap.rs
runtime/queries/c/textobjects.scm
runtime/queries/cmake/textobjects.scm
runtime/queries/fish/textobjects.scm
runtime/queries/go/textobjects.scm
runtime/queries/llvm-mir/textobjects.scm
runtime/queries/llvm/textobjects.scm
runtime/queries/perl/textobjects.scm
runtime/queries/php/textobjects.scm
runtime/queries/python/textobjects.scm
runtime/queries/rescript/textobjects.scm
runtime/queries/rust/textobjects.scm
runtime/queries/tablegen/textobjects.scm

This attempts to add a comment textobject to the surround matching logic. This seems like it would be an easy add, but I'm having trouble getting it to behave at all in Rust. In PHP @comment.inside works fine, but @comment.around does not.
I'm intending to support both @comment.inside and @comment.around, where the difference is that @comment.around should select adjacent line comments, so line comments like the following will match in total:
```php
// This is some very long description of why some tricky logic works
// the way it does, split across lines rather than using block comments
```
.. whereas the .inside will only select one such line comment. Both methods are intended identical for block comments.
Once we figure this out it should partially address #1505.

Add comment textobject for surround selection and navigation

---

helix-term/src/ui/markdown.rs

Depends on #1714.
I'm currently working on adding signature help and need the syntax highlighted signature text separately to apply further styles like underlining the current parameter. This commit separates out a function that highlights the text with the language specified and returns a `helix_tui::text::Text`.

Extract markdown code block highlighting function

---

flake.lock
flake.nix

closes #1757
possibly connects #1647 but I don't have an ARM machine to test on. @jdahm would you mind trying `nix run github:the-mikedavis/helix/665e01b4639f87de1f33a1cfa99c97d6a3549fd0`? I suspect the tree-sitter `gcc` failure is unrelated but it's worth a shot.
builds on @yusdacra's wonderful [work](https://github.com/yusdacra/nix-cargo-integration/issues/58#issuecomment-1059814719) - I just added back the `shell` part. I watched that presentation on dream2nix and I'm pretty excited 😄

flake: use dream2nix within nix-cargo-integration

---

helix-term/src/commands/lsp.rs

Fixes https://github.com/helix-editor/helix/issues/1773

Fix bug in LSP when creating a file in a folder that does not exist

---

book/src/configuration.md
helix-term/src/application.rs
helix-term/src/args.rs
helix-term/src/main.rs

Just a nice-to-have that makes editing the config feel a bit more first class.

Add --edit-config flag to directly open config.toml

---

helix-term/src/main.rs

As @Omnikar said on matrix, there's an extra 's' in here! 🤦

fix '--grammar' flag in help text

---

helix-loader/src/grammar.rs

Whoops, I left a printf debug laying around. I think I must've accidentally rebased this in at some point when I was squashing down the commit history 😅

remove stray 'println!' from grammar building function

---

runtime/themes/gruvbox.toml
runtime/themes/gruvbox_light.toml

With `gruvbox` themes, `{ modifiers = ["reversed"] }` makes it
impossible to identify which pair the cursor is on. `ui.cursor.primary`
is set to be the same as `ui.cursor.match`.
Using `{ bg = "bg2" }` for `ui.cursor.match` instead makes sure that
it is possible to find out the current cursor position.

theme: Use distinct colors for match pair and cursor for gruvbox

---

.github/workflows/build.yml
.github/workflows/release.yml

79caa7b72bef94bd820758b2ebc20887324f7416 setup helix-term as the
default workspace member (which I believe is done to avoid building
xtask on every compile). This changes the behavior of 'cargo test'
though so that it only runs helix-term tests by default. To run all
tests, we switch to 'cargo test --workspace'.

use 'cargo test --workspace' in CI

---

helix-term/src/commands.rs
helix-term/src/ui/mod.rs

Use `^` and `$` to match the beginning and end of a line when searching

---

runtime/queries/c-sharp/highlights.scm

Adds more queries for better highlighting:
before:
after:

C# highlighting improvements

---

book/src/keymap.md

- Add missing key bindings to keymap docs
- Add a note about readline bindings in insert mode
- Rewrite section on selection extend mode
The biggest question I have with this is whether there are any remaining movements that don't obey extend mode. I don't think there are, but I can add a note back in about it if I'm wrong.
Some more sections could use reorganizing or splitting (eg. there's selection manipulation stuff under movement), but I've run out of time for now.

Update keymap documentation in the book

---

helix-term/src/commands.rs

`insert_register` ignores register name and always pastes the last yanked text.
- version: 0.6(nixpkg) and f1e90ac2e3040dd09b3652d1bcabb4aee834aedd on the main branch
- Set register name to `cx.register` instead of `cx.editor.selected_register`.
plus:
- Update `cx.editor.autoinfo` to display register contents, like `select_register`.
- Call `paste_after` instead of `paste_before`; the position of the pasted text matches other editors.
Now it seems to work well.

'insert_register' doesn't handle register name correctly

---

.github/workflows/build.yml

`restore-keys` is a configuration option for the actions/cache action
which specifies fallback behavior. The [docs][docs] say it best:
> When a cache miss occurs, the action searches for alternate keys
> called `restore-keys`.
>
> If you provide `restore-keys`, the `cache` action sequentially
> searches for any caches that match the list of `restore-keys`.
> ... If there are no exact matches, the action searches for partial
> matches of the restore keys. When the action finds a partial match,
> the most recent cache is restored to the `path` directory.
So this improves caching when there's a miss. For example if I edit
`.github/workflows/languages.toml`, the current behavior is that the
cache for downloaded grammars will miss and all of them will need to
be fetched again. With …

ci: configure restore-keys for caches

---

helix-term/src/commands.rs

Currently match is finding the match based on the anchor rather than the
head (cursor) so this behavior is rather unexpected when user is doing
a match but a different item was matched instead when the selection is
more than one character.
Example
```
#(let hello = {|)#
};
```
When `mm`
Before (it will match more than just the cursor matching char)
```
#(let hello = {
};|)#
```
After (it finds matching character based on the cursor)
```
#(let hello = {
}|)#;
```
There is one change I would like to do here but did not since it brings in more change, which is that `mm` will select everything within by default, rather than needing to do `v`. Maybe need to confirm with @sudormrfbin for that.

Match in visual use head not anchor

---

helix-term/src/commands.rs

Currently `x` only affect the current selection, but this will make it
affect every selection so `x` can be more useful with multi-cursors.

Perform extend line on every selection

---

helix-term/src/ui/picker.rs

When the picker results output is empty, movement actions result in a panic:
```
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', helix-term/src/ui/picker.rs:420:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This could be a no-op instead when the matches length is zero.

Handle panic on move within empty picker

---

.github/workflows/gh-pages.yml
book/src/SUMMARY.md
book/src/title-page.md

Fixes #1607. Docs for master is now deployed at https://docs.helix-editor.com/master. The docs for 0.6 will have to be pushed to the `gh-pages` branch manually, since the main docs are now updated only on releases.
I'm _think_ this should work, though I've not tested it.

Deploy docs for master separately

---

book/src/generated/typable-cmd.md
helix-term/src/commands.rs
helix-term/src/commands/typed.rs
helix-term/src/keymap.rs

This change proposes the addition of two new commands to open scratch buffers in splits. It works out to be very similar to `:hsplit src/newfilename.rs` where `newfilename.rs` is a file that doesn't exist, but with the intention of not actually creating a file when you are done with it.

Add horizontal and vertical split scratch buffers

---

languages.toml

This simplifies the setup for the Julia language server. 
Also changes the standard indent to 4 spaces, which is recommended in the style guide. 
https://docs.julialang.org/en/v1/manual/style-guide/#Indentation

simplify Julia config

---

helix-core/src/syntax.rs
helix-term/src/commands/typed.rs
helix-view/src/editor.rs

Serialize the `Config` struct and operate on `serde_json::Value`'s to deserialize back into `Config` instead of manually parsing arguments to `:set` and setting values.

Refactor :set to parse by deserializing values

---

helix-loader/src/grammar.rs

See https://github.com/helix-editor/helix/discussions/1817
It looks like we need the enums to have the `only`/`except` fields in order
to deserialize correctly.

fix enum definition for use-grammars selections

---

CHANGELOG.md

Some small markup fixes for the changelog:
- backtics around commit hashes (e.g. [`0b96201`](https://github.com/helix-editor/helix/commit/0b9620108dabe6a26fbeac32ba9d236b6d69b56a))
- trimmed some trailing spaces
- wrapped some commands and keybindings in backtics where necessary

cleanup changelog markup

---

languages.toml
runtime/queries/git-commit/injections.scm

Any text following a `scissors` node is now contained in one `message` node. This is a huge speed boost for verbose commits which inject tree-sitter-git-diff after the scissors. The old behavior was that each line was its own injection, which is slow when there are thousands of injections.
cherry-picked out of #1728
closes #1836
see also https://github.com/the-mikedavis/tree-sitter-git-commit/commit/d04666995496e6ebb014b7de05514afe8b18c33c

Update tree-sitter-git-commit with performance fix

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/org/highlights.scm
runtime/queries/org/injections.scm

Using (and many thanks to):
https://github.com/milisims/tree-sitter-org
https://github.com/nvim-orgmode/orgmode/tree/master/queries/org
And the-mikedavis from the matrix chat. I think I need to add a few more things like docs, but I would like to first know and what I can add and what I can improve? 
Ideally I'd want the headers to be a different colors each(I think this is a theming thing though) and property drawers to be colored different as well. Not entirely sure how to go about it?

Initial basic Org markup support thanks to tree-sitter-org

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/solidity/highlights.scm

Add syntax highlighting for Solidity

---

runtime/queries/rescript/highlights.scm

Hey there,
With the latest update of `tree-sitter-rescript`, there's a slight change to the query. This PR removes a node highlight query for a node that no longer exists.

Fix Rescript hightlights query

---

runtime/themes/bogster.toml
runtime/themes/solarized_dark.toml
runtime/themes/solarized_light.toml
runtime/themes/spacebones_light.toml

In the following four provided themes, `ui.cursor.match` has the same look with `ui.cursor.primary`.
For better discrimination, I think we need different colors. How about the following assignments?
- present
- PR
- present
- PR
- present
- PR
- present
- PR

Revise the color for ui.cursor.match

---

book/src/configuration.md
helix-term/src/application.rs
helix-term/src/config.rs
helix-view/src/editor.rs

This is mainly done to accomodate the new lsp.signature-help config option that will be introduced in https://github.com/helix-editor/helix/pull/1755 which will have to be accessed by commands. The top level config struct is split and moved to different places, making the relocation necessary.

Move top level lsp config to editor.lsp

---

grammars.nix

fetchTree with git is slow even with shallow cloning. It might also be that shallow cloning simply [doesn't work](https://github.com/NixOS/nix/issues/5119). Either way, the github fetcher is much faster as it downloads a tarball using the GitHub API. All the current grammars are from GitHub so this should reduce fetch time a lot.

grammars.nix: use github type for fetchTree where possible

---

helix-loader/src/grammar.rs
helix-term/src/commands/typed.rs
helix-term/src/health.rs

While this feature is undeniably ergonomic, it mostly inflates the MSRV, which is a problem over at Void Linux where bumping Rust version is a lengthy process.
Checked with `cargo-msrv` that with these changes the MSRV drops to 1.57

Avoid using the format ident Rust feature

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/elixir/highlights.scm
runtime/queries/erlang/highlights.scm
runtime/queries/gleam/highlights.scm
runtime/queries/gleam/locals.scm

There are some updates to bring tree-sitter-erlang and tree-sitter-elixir up to date including some fixes plus I've added tree-sitter-gleam!
highlights:
**Erlang**
- fixes for syntax highlighting
- `begin`
- `after`
- record fields without defaults but with typing
- [EEP49 `maybe`](https://www.erlang.org/eeps/eep-0049#specification) is now parsed (new syntax in OTP25)
**Elixir**
- fix for mistakenly highlighting keywords in some odd stab clause scenarios
- iirc it was some very rare syntax like
```elixir
fn
index ->
IO.inspect(index)      # some other line(s) and then the last line is an identifier
index
_index ->
0
end
```
- switch to `@namespace` for modules (upstream switched to `@module` and `@namespace` seems closest of the available highlights)
- nullary ranges are now parsed: …

update BEAM language tree-sitter grammars

---

helix-term/src/health.rs
helix-term/src/main.rs

Functions in health.rs now return std:io::Result<()>. All instances of println!
and eprintln! have been replaced with writeln!. This allows detection of errors
while printing messages and errors. BrokenPipe errors are ignored. All other
errors are returned.
Fixes #1841
Signed-off-by: Nirmal Patel <npate012@gmail.com>

Handle BrokenPipe when piping hx --health through head

---

book/src/keymap.md
helix-term/src/ui/picker.rs

Currently, the picker's re-using a few bindings which are also present
in the prompt. This causes some editing behaviours to not function on
the picker.
**Ctrl + k** and **Ctrl + j**
This should kill till the end of the line on prompt, but is overridden
by the picker for scrolling. Since there are redundancies (`Ctrl + p`,
`Ctrl + n`), we can remove it from picker.
**Ctrl + f** and **Ctrl + b**
This are used by the prompt for back/forward movement. We could modify
it to be Ctrl + d and Ctrl + u, to match the `vim` behaviour.

Resolve conflicts between prompt/picker bindings

---

helix-core/src/syntax.rs

If there exists no `indents.scm` for some language, we want to use the fallback (always copy the indentation from the current line). This didn't happen because we returned an empty query instead.

Fix indentation fallback

---

helix-view/src/clipboard.rs

I'm not sure if there is any desire for this to be reintroduced as it was removed in https://github.com/helix-editor/helix/commit/adf97e088e38c12eb6c363f674aab5dca1962bbe. But here is a small PR on the off chance that it is until https://github.com/helix-editor/helix/pull/1827 is in a good state to merge.
If this PR isn't a desired addition to the repo at the moment, I am happy to continue to keep this branch on my fork up to date with the upstream so that Arch WSL2 users who come across this via Google or GitHub search can use `yay` to install an edited version of `helix-git` from the AUR:
```bash
yay -G helix-git
cd ~/.cache/yay/helix-git
rm -rf helix pkg src
makepkg -si
```
Finally, a huge thanks to everyone that has dedicated their time and effort to creating such a wonderful text …

Reintroduce win32yank as a clipboard provider on Linux for WSL2 + Windows 10

---

languages.toml

Trying to add support for jsx (javascriptreact) syntax and language server.
Following up on this discussion: https://github.com/helix-editor/helix/discussions/1899

Add support for javascriptreact language

---

helix-term/src/commands.rs

The search implementation would start searching at the next grapheme
boundary after the previous selection. In case the next occurence of the
needle is immediately after the current selection, this occurence would
not be found (without wraparound) because the first grapheme is skipped.
The correct approach is to use the ensure_grapheme_boundary functions instead
of using the functions that skip unconditionally to the next grapheme.
Example case:
> hellohellohello
When searching for "hello", the first and third occurrence will be found.
(Second will be found once depending on starting-position of the cursor)

Fix start-position of next search

---

helix-term/src/commands.rs

Instead of first cloning the query and then allocating again to format
the error, format the error using a reference to the query.
Comment about borrow-checker warning is removed,
documenting simple borrow-checker constructions gets noisy pretty quickly, imho.

Avoid unnecessary clone when formatting error

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/javascript/highlights.scm
runtime/queries/jsx/highlights.scm
runtime/queries/jsx/indents.scm
runtime/queries/jsx/injections.scm
runtime/queries/jsx/locals.scm

It looks like a24fb17b2a978d3165bd6304e9edd69bddb6dd82 (and
855e438f55cb278de8203ac4911561c4c7ad656c) broke the typescript
highlights because typescript
; inherits: javascript
but it doesn't have those named nodes in its grammar.
So instead we can separate out JSX into its own language and copy
over everything from javascript and supplement it with the new
JSX highlights. Luckily there isn't too much duplication, just the
language configuration parts - we can re-use the parser with the
languages.toml `grammar` key and most of the queries with `inherits`.

separate JSX queries from javascript

---

helix-term/src/health.rs

For the Highlight, Textobject and Indent columns, health.rs now additionally prints either ✓ or ✘. This is in response to Issue #1894

Added checkmarks to health.rs output, Resolves #1894

---

book/src/generated/lang-support.md
languages.toml

Hi. I think [texlab](https://github.com/latex-lsp/texlab) should be a default langage server for latex. Let me know if this PR needs more work/consideration, docs for example?

Add texlab language server for latex

---

book/src/keymap.md
helix-core/src/lib.rs
helix-core/src/line_ending.rs
helix-core/src/movement.rs
helix-core/src/test.rs
helix-core/src/textobject.rs
helix-term/src/commands.rs
helix-term/src/keymap/default.rs

Also improved testing facility.
Fix #1580
Superseeds #784
Although this is not done I think it would be good to help review the new test helpers.
Not sure if we want to support extend mode for this even though inspiration is taken from kakoune, kakoune does not have extend mode but we have that, maybe we can make use of it to extend an additional paragraph? I didn't do it since I don't think I need it.

Add paragraph motion and textobject

---

book/src/generated/typable-cmd.md
helix-term/src/commands.rs
helix-term/src/commands/typed.rs

Hi Helix maintainers 👋 ,
This is the implementation for issue https://github.com/helix-editor/helix/issues/1926 to add the typed commands `buffer-next` and `buffer-previous`.
Best regards,
David

Add typed commands buffer-next and buffer-previous

---

helix-term/src/application.rs

when using helix over mosh, the screen doesn't get cleared and
characters get left all over the place until they are overwritten. with
this change, the screen gets properly cleared as soon as helix starts

clear terminal after switching to alternate screen

---

Cargo.lock

Deduplicates mio dependency which results no crates duplication now and
7 lesser crates for cargo to build.
I feel bad to push the signal-hook-mio and crossterm authors to get it released with updated mio even though they are busy. T_T

Bump crossterm to 0.32.2

---

book/src/generated/typable-cmd.md
helix-core/src/syntax.rs
helix-term/src/commands/typed.rs
helix-term/src/ui/mod.rs
helix-view/src/document.rs
helix-view/src/editor.rs

* Add set-language typable command to change the language of current buffer.
* Add completer for available language options.
Closes #1794

Add runtime language configuration (#1794)

---

book/src/keymap.md

fix keymap doc typo for 'delete' in insert-mode

---

helix-term/src/ui/editor.rs

During a single `HighlightEvent::Source`, the highlight spans do not change and we can merge them into a single style at the beginning of the event and use it instead of re-computing it for every grapheme.

Compute style only once per source highlight event

---

helix-term/src/commands.rs

Just a small fix to correct a typo.

Fix typo (pallete -> palette)

---

book/src/generated/lang-support.md
languages.toml

Formatting now works after much experimentation.
Neovim provides these additional settings:
```
init_options = {
embeddedLanguages = { css = true, javascript = true },
configurationSection = { 'html', 'css', 'javascript' },
},
```
But I don't think they are doing anything extra in Helix. Without them it still seems to be accepting and formatting JS, I think it is best to leave them out for now unless someone else knows more about them.
I will add to the WIKI when this is merged.

Add default language server for HTML

---

helix-core/src/movement.rs
helix-core/src/syntax.rs
helix-core/src/test.rs
helix-core/src/textobject.rs

connects #2026 
see also #1881
So we can continue targetting 1.57 as MSRV.

Remove usage of format ident feature from tests

---

book/src/generated/lang-support.md
languages.toml

Hello, 
this pull request adds two things to the default languages.toml:
After a lot of testing of different lsp implementations for php I found intelephense to be the best one for my projects (laravel, TYPO3, Wordpress). The free version offers a lot of value and the professional version is very affordable (15€). I understand that it can be controversial depending on a paid product for full functionality as an open source project, but as a developer I also value tools that save my time. 
I added `composer.json` (composer is the de facto standard package manager for PHP) and `index.php` (still the default entry point for all modern projects) as workspace roots.

PHP roots and languageserver improvements

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/swift/highlights.scm
runtime/queries/swift/locals.scm

https://github.com/helix-editor/helix/issues/1964
Was also planning on using this, so went ahead and implemented it. From that issue, I forked the current tree-sitter-swift and checked in the current build configs, until a better solution is implemented (if we just want to wait if they want to add a separate branch, that's fine too).
There are a few keywords that are in the highlights.scm that I didn't see in https://docs.helix-editor.com/themes.html#syntax-highlighting, so I didn't know how to handle them and just left them as is.
Finally, there is one issue in swift I can't seem to figure out.
when tabbing through, it's auto appending the parenthesis, but puts the cursor outside so you have to backspace. Is there a way to prevent this I didn't see?

Add swift language

---

book/src/generated/lang-support.md
languages.toml

Should resolve #2010. Sadly can't config [volar](https://github.com/johnsoncodehk/volar/tree/master/packages/vue-language-server) to it,only vetur works fine.

Add default language server for Vue

---

README.md
book/src/guides/adding_languages.md

Following up on https://github.com/helix-editor/helix/pull/2031#issuecomment-1093330411
It also seems to be a pretty common case that a new user will not know off the bat that they need to install the language server. I think VSCode/nvim plugins might install these themselves which makes it unexpected to have to install it when using helix. So I added a note to the bottom of the installation instructions pointing to the new lsp wiki.
Also, thanks @David-Else (and subsequent contributors) for setting up that wiki :)

Improve documentation on Language Server installation

---

helix-term/src/commands.rs
helix-term/src/keymap/default.rs

The `file_picker_at_cwd` command opens the file picker at the current
working directory (CWD). This can be useful when paired with the
built-in `:cd` command which changes the CWD.

Add command for picking files from CWD

---

book/src/guides/adding_languages.md
book/src/lang-support.md
languages.toml

Adding you here sudormrfbin as I see you were the original author.
Related to https://github.com/helix-editor/helix/issues/2058#issuecomment-1094276181
I wanted to stress
* you need a language server installed to support LSP-driven features (a somewhat common question)
* `hx --health` can show you the language support you have for the version installed
Plus I think linking to the `languages.toml` is unnecessary, I think we can just link to the other language docs. The `languages.toml` is probably confusing per the linked issue. I also added a pointer in the languages.toml to the lang docs. Seems a little excessive but meh, it's a low-cost thing that might help ¯\\\_(ツ)_/¯

Rewrite Language Support docs

---

helix-term/src/ui/editor.rs

The unstyled column on the left from the diagnostics_or_breakpoints gutter looks sad if you want to add a background to all gutters. Let's fix this.

Apply ui.gutter style to empty gutters

---

.github/workflows/release.yml
contrib/completion/hx.bash
contrib/completion/hx.fish
contrib/completion/hx.zsh

Ref #1975. I opted for `contrib/`, this of course is for debate. Installed automatically by brew via [homebrew-helix#6](https://github.com/helix-editor/homebrew-helix/pull/6), no idea about any other distribution methods.
The GH workflow is untested, as I simply don't know how …

Add shell completion

---

helix-term/src/health.rs

hx --health output table's second and third columns were not showing
symbols like ✔ or ✘ to indicate whether LSP or DAP binaries were found.
This change adds these symbols to improve accessibility.
Fixes #1894
Signed-off-by: Nirmal Patel <npate012@gmail.com>

Add true or false checkbox in health output table

---

helix-view/src/editor.rs

Skip launching a language server if a document doesn't have a valid URL.
Closes #1994

Fix panic when using set-language on a scratch buffer

---

helix-core/src/textobject.rs

Last paragraph shoud be selected if the cursor was placed on the
whitespace paragraph part and `map` is done, otherwise it would do
nothing useful, but now we select backwards for the last paragraph
which behaves similarly to kakoune, making `map` useful for the last
paragraph with whitespace. Example usecase is to copy and paste last
ledger cli paragraph quickly by `mapyp` to duplicate last entry.
[![asciicast](https://asciinema.org/a/rgGQgJnweeIDHYozEF6BQjJ7s.svg)](https://asciinema.org/a/rgGQgJnweeIDHYozEF6BQjJ7s)
I have always wanted to make it similar to kakoune for the last paragraph textobject behavior, did that in the last paragraph implementation but that have quite some bugs and I forgot to put it in the new one.

Make textobject select last paragraph

---

book/src/configuration.md

These are hinted at in the example config at the top (except `none`), but really should be listed explicitly near the option itself for clarity.

Document values for editor.cursor-shape

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/eex/highlights.scm
runtime/queries/eex/injections.scm
runtime/queries/elixir/highlights.scm
runtime/queries/elixir/injections.scm
runtime/queries/heex/highlights.scm
runtime/queries/heex/injections.scm

EEx and HEEx are templating languages for Elixir.
I thought about pulling in HEEx before (#881) but it needed the incremental injections refactor in order to use combined injections (#1378).
The highlights are not perfect because of the whitespace sensitivity of tree-sitter-elixir. I've removed the error highlighting in tree-sitter-elixir queries to make it less noticeable. It may take a bit to fix that so I think we're better off adding heex with "good enough" syntax highlights for now (see also https://github.com/elixir-lang/tree-sitter-elixir/issues/2#issuecomment-1097377723). I could be persuaded to drop the commit that removes error highlighting though.
Also updates tree-sitter-elixir with a fix for a case that bugged me during editing …

Add tree-sitters EEx and HEEx

---

book/src/generated/lang-support.md
flake.lock
languages.toml
runtime/queries/sql/highlights.scm

Finally got around to adding sql language support. The original PR is here: https://github.com/helix-editor/helix/pull/1464, but enough has changed since then (no submodules!) that I decided to just create a new branch & PR. 
Only thing I'm not sure of is why when I built with nix, `flake.lock` changed so much.

feat(languages): SQL

---

languages.toml

.mk is more or less standard for make files that aren't named "Makefile".

Add make file-type "mk" to languages.toml

---

book/src/configuration.md
helix-term/src/ui/editor.rs
helix-view/src/editor.rs
helix-view/src/gutter.rs
helix-view/src/tree.rs
helix-view/src/view.rs

This implements the feature request of issue https://github.com/helix-editor/helix/issues/1960 (slightly adapted based on feedback from @archseer).
Now one can configure the displayed gutters with
```toml
[editor]
gutters = ["diagnostics", "line-numbers"]
```
(default)
Here a picture with
```toml
[editor]
gutters = ["diagnostics"]
```

Make gutters configurable

---

helix-lsp/src/client.rs
helix-term/src/ui/completion.rs

LSP Auto-import

---

book/src/generated/typable-cmd.md
helix-term/src/commands.rs
helix-term/src/commands/typed.rs

An attempt at a solution for this issue https://github.com/helix-editor/helix/issues/1943
Adds a typable `:pipe` command which requires a shell command argument to pipe the selections to.
This would allow to map some keys to a specific command to which to pipe the selections to.

Pipe typable command

---

helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-term/src/commands/lsp.rs

This allows for e.g. clangd to properly send the quickfix code actions corresponding to those diagnostics as options.
The LSP spec v3.16.0 introduced an opaque `data` member that would allow the server to persist arbitrary data between the diagnostic and the code actions request, but this is not supported yet by this commit.

Send active diagnostics to LSP when requesting code actions.

---

helix-term/src/commands.rs

Equivalent to `extend_line`, but extends selection above rather than below.
One limitation I don't quite know how to fix is that currently it doesn't scroll the view upwards once it reaches the top of the screen. I figure it's because the "main cursor" stays at the bottom of the selection, so the view does not scroll to contain the top of the selection the same way it does for the bottom.

Add command to extend selection to line above

---

languages.toml
runtime/queries/erlang/highlights.scm
runtime/queries/heex/highlights.scm

HEEx has a small fix for the highlights: `{`/`}` should be `@keyword`s like the rest of the templating tokens.
Erlang has a few fixes
* macros with names that start with underscore like `?_assertEqual/2` are highlighted as macros rather than `comment.unused`
* quoted and unquoted atoms are now one node `(atom)` which simplifies some highlight scenarios
* all attributes are highlighted as keywords
* I was trying to be selective before and only cover the built-ins but meh, it's a good-looking highlight for all atttributes ¯\\\_(ツ)_/¯

Update tree-sitters Erlang and HEEx

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/ruby/textobjects.scm

It includes Ruby TextObjects and more Ruby file extensions
_It is my first time working with Tree-Sitter, improvements are welcome._

Ruby TextObjects and more file extensions

---

helix-loader/src/config.rs
runtime/queries/fish/highlights.scm

The code base treats "builtin" in two ways, so I tried to be consistent with the usage in those files, but wanted to fix the typo in any event.

Fixing (in two ways) a small typo

---

helix-lsp/src/lib.rs

Instead of panicing we can discard the malformed diagnostic. This
`.parse()` fails commonly when a non-conformant language server gives
a diagnostic with a location that breaks the spec:
{ "character": 0, "line": -1 }
can currently be returned by ElixirLS and the python LS. Other
messages in this block are discarded but this one feels special enough
to log. Maybe we should refactor all parses to log errors in cases of
malformed messages?
closes #1204

Prevent panic when receiving malformed LSP PublishDiagnostic

---

helix-core/src/syntax.rs
runtime/queries/go/textobjects.scm

df57914 has the details on the fix itself: it was a node that was removed when we updated for generics support.
Also included is an error log for failures to parse textobjects queries (see [here](https://github.com/helix-editor/helix/issues/1920#issuecomment-1089736393)) which makes it easier to debug this in the future.
closes #1920

Fix Golang textobject queries

---

runtime/themes/tokyonight.toml

Hello there! I'd like to add support for the beautiful tokyonight theme, based on the original color scheme (https://github.com/enkia/tokyo-night-vscode-theme), and on the neovim theme (https://github.com/folke/tokyonight.nvim).
Note that this is for the Night variant only (darkest one), but the other variants can easily be made from this one by changing the palette!

Add tokyonight theme

---

helix-term/src/ui/completion.rs
helix-term/src/ui/popup.rs

Restoring document state after completion cancel.

Restore document state on completion cancel

---

helix-loader/src/config.rs
helix-loader/src/lib.rs

We merge the elements of arrays for the top-level array. For
`languages.toml`, this is the array of languages. For any nested
arrays, we simply take the `right` array as-is instead of using
the union of `left` and `right`.
closes #1000

Override nested arrays when merging TOML

---

helix-term/src/commands.rs

Select multiple line and open should be based on the whole selection
and not just the line of the cursor, which causes weird behavior like
opening in the middle of the selection which user might not expect.
[![asciicast](https://asciinema.org/a/W7ykJFBFJDoHUpQbcvXijQiq6.svg)](https://asciinema.org/a/W7ykJFBFJDoHUpQbcvXijQiq6)

Fix open on multiline selection

---

helix-term/src/ui/editor.rs

Added ability to remap 0 if it is not part of a count

---

runtime/themes/dark_plus.toml

Hi, II added the border for the `rulers` based on the border color of the original theme.
Without this the `rulers` are not shown.

dark_plus: Add the borders color from the original theme

---

shell.nix

Since it wasn't available in the lockfile, I just hardcoded it
in the shell.nix file.
This is a possible solution for
https://github.com/helix-editor/helix/issues/2195

Fix nix shell by hardcoding the flakecompat library

---

languages.toml

1.  Gentoo ebuilds, Arch Linux PKGBUILDs and Alpine Linux APKBUILDs are actually bash scripts.
set set `*.ebuild,*.eclass,PKGBUILD,APKBUILD`  to `bash`
ref: 
https://wiki.gentoo.org/wiki/Eclass
https://wiki.gentoo.org/wiki/Ebuild
https://wiki.alpinelinux.org/wiki/APKBUILD_Reference
https://wiki.archlinux.org/title/PKGBUILD
2. a `*.nomad` file is actually `hcl` file
demo: https://github.com/hashicorp/nomad/blob/main/demo/csi/hostpath/redis.nomad
---------------------------------------
screenshots:

chore(filetype): bash and hcl file type add more common used extensions or files

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/gomod/highlights.scm
runtime/queries/gomod/injections.scm
runtime/queries/gowork/highlights.scm
runtime/queries/gowork/injections.scm

add go.mod and go.work support
according to `tree-sitter/tree-sitter-go`  https://github.com/tree-sitter/tree-sitter-go/pull/42#issuecomment-827768030
> since go.mod and Go are two completely different languages, and some users may only care about Go, but not go.mod, I would prefer to just keep the go.mod grammar in its own repository. 
so tree-sitter-go will not add `go.mod` and `go.work` support. we need add this standalone.
```shell
❯ hx --health gomod   
Configured language server: gopls
Binary for language server: /home/ttys3/go/bin/gopls
Configured debug adapter: None
Highlight queries: ✔
Textobject queries: ✘
Indent queries: ✘
```
```shell
❯ hx --health gowork
Configured language server: gopls
Binary for language server: /home/ttys3/go/bin/gopls
Configured debug adapter: None …
```

feat(lang): add go.mod and go.work support

---

book/src/themes.md

From the rulers feature (#2060)

Document `ui.virtual.ruler` scope in theme docs

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/nu/folds.scm
runtime/queries/nu/highlights.scm
runtime/queries/nu/injections.scm
runtime/queries/nu/locals.scm

Try to add [nushell](https://github.com/nushell/nushell) language support

feat(lang): add nushell language support

---

book/src/generated/typable-cmd.md
helix-term/src/commands/typed.rs

A `Transaction` is generated to replace all line endings (other than the one your changing it to) in a file. I opted to not create a method for `Document` since I'm not sure it would ever be used elsewhere, and it would be easy to pull out of the command function if needed.

Replace line endings using `set_line_ending` command

---

helix-term/src/commands.rs

Now should follow vim behavior more
- no longer remove text on cursor
- no longer remove selected text while inserting
- first kill to start non-whitespace, start, previous new line

Fix ctrl-u on insert behavior

---

helix-lsp/src/client.rs
helix-term/src/commands/lsp.rs

check rename capabilities before send rename action
and logging a kindly warning message to the log file so that the user knows that it maybe a client config problem.
some lang server implementation (like intelephense) need a license key configured to do `rename` action.
in neovim, the config looks like:
```lua
lsp.intelephense.setup {
settings = {
intelephense = {
licenceKey = "the-actual-license-key",
},
},
}
```
in helix, one may miss configured like this:
in `languages.toml`
```toml
[[language]]
name = "php"
config = { "intelephense" = { "licenceKey" = "the-actual-license-key" }}
```
but the correct init config in helix should be like this:
```toml
[[language]]
name = "php"
config = { "licenceKey" = "the-actual-license-key" }
```
with the warning message in the log, people will easy …

chore(lsp): check rename capabilities before send rename action

---

helix-loader/src/config.rs
helix-loader/src/lib.rs

history: this is a revert of the revert of #2145 with a fix on top. #2145 accidentally took out all array merging.
I got a bit confused when sorting out a merge conflict when rebasing #2145: I thought the call in `helix-loader/src/config.rs:22` was merging `config.toml` and not `languages.toml` 😅
So that boolean was just wrong and that was preventing the top-level array in languages.toml with user-specified languages.toml overrides. I gave this a spin locally with
```toml
[[language]]
name = "erlang"
auto-format = true
```
and all appears to be well 👍
closes #1000

Only merge top-level array when merging `languages.toml`

---

book/src/generated/lang-support.md
languages.toml

add yaml-language server configuration in languages.toml

feat(lsp): add yaml lsp

---

book/src/generated/lang-support.md
languages.toml

Terraform-ls uses two seperate language-ids for terraform and terraform-vars files.
Read more about it [here](https://github.com/hashicorp/terraform-ls/blob/main/docs/language-clients.md#language-ids)

fix(lsp): divide hcl into seperate languages

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/keymap/default.rs

As mentioned on the matrix. What do you think @pickfire, should the commands be renamed so it's `goto_next_paragraph` instead? That would line up with the other commands in this section in the docs

Rename paragraph motion commands from move to goto

---

book/src/generated/typable-cmd.md
helix-term/src/commands/typed.rs

Adds support for reading current config values. Closes #2218.

Add :get-option command

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/vala/highlights.scm

fix https://github.com/helix-editor/helix/issues/2224
one question: Vala allows comments to be recorded in code in different ways. but in `languages.toml` we can only config a single `comment-token = "//"`,  how can we to block comment toggle action ?
```vala
// Comment continues until end of line
/* Comment lasts between delimiters */
/**
* Documentation comment
*/
```
refs:
lang server: https://github.com/vala-lang/vala-language-server
ts: https://github.com/vala-lang/tree-sitter-vala
https://wiki.gnome.org/Projects/Vala/StringSample
https://learnxinyminutes.com/docs/vala/
https://naaando.gitbooks.io/the-vala-tutorial/content/en/3-basics/comments.html
-------------
demo vala code to test:
```vala
// Single line comment
/* Multiline
Comment */
/**
* Documentation comment
*/
char …
```

feat(lsp): add vala language support

---

helix-lsp/src/client.rs

the lsp i've been working on checks client capabilities, testing with helix showed that it doesn't register the publish_diagnostics capability, though it appears to be supported (and looks nice!).  From what I could tell none of the sub-options are used so I left it at `..Default::default()`.

register publish_diagnostics client capability

---

runtime/themes/autumn.toml

This commit mainly improves markup highlighting.
* Italic and bold are displayed as italic and bold without changing the font colour.
* URLs get their own colour.
* The lightness of `my_green` is slightly adjusted for better readability.
A new colour `my_yellow2` is introduced to distinguish warnings and methods visually more easily.

Autumn theme: improve markup highlighting

---

runtime/themes/base16_terminal.toml

The usage of light-white doesn't exist and its causing the base16_terminal to have a non existing cursor, also yielding an error in the error log. 
Helix uses the notion of naming light-gray rather than light-white.
No visible cursor in theme
Visible cursor after using the correct color

Fix base16_terminal theme using incorrect ansi-color

---

helix-term/src/commands/typed.rs

Looks like a small typo - the typed variants of these commands always
paste after the selection. This commit fixes the before/after direction
for those `*_before` commands.
closes #2284

Fix paste direction for typed paste commands

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/hare/highlights.scm
runtime/queries/hare/indents.scm
runtime/queries/hare/locals.scm

I want to test out the language [hare](https://harelang.org/) using helix.

feat(lang): add hare language support

---

helix-term/src/commands.rs
helix-view/src/editor.rs
helix-view/src/view.rs

Previously, when closing buffer, you would loose cursor position in other docs. Also, all splits where the buffer was open would be closed.
This PR changes the behavior, if the view has also other buffer previously viewed it switches back to the last one instead of the view being closed. As a side effect, since the views are persisted, the cursor history is persisted as well.
Fixes: https://github.com/helix-editor/helix/issues/1186

feat(commands): better handling of buffer-close

---

book/src/generated/lang-support.md
languages.toml

Add default lsp for toml
https://taplo.tamasfe.dev/

feat(lsp): add toml lsp

---

helix-term/src/commands.rs

Wrap current directory picker with overlay widget

---

book/src/usage.md
helix-core/src/surround.rs
helix-core/src/textobject.rs
helix-term/src/commands.rs

`m` now acts as a wildcard surround textobject, so for example with this text
```
[abc (def) ghi]
```
If the cursor is on `c`, `mim` will select everything inside `[]`, and if it's on `e` it will select inside `()`, without manually requiring either `mi(` or `mi[`.

Add `m` textobject to select closest surround pair

---

languages.toml
runtime/queries/nickel/highlights.scm

https://github.com/tweag/nickel/pull/681 introduced recursive let expressions to the Nickel language. This PR updates the tree-sitter grammar to include this keyword and updates the highlighting query.

feat(lang): Update nickel to include "rec" keyword

---

README.md
book/src/guides/adding_languages.md

#114 was solved so the docs should reflect that.

fix(docs): cleanup obsolete indents.toml mentions

---

helix-term/src/ui/prompt.rs

When fiddling with paths in a :o prompt, one usually would want Ctrl-W to erase a path segment rather than the whole path. This is how Ctrl-W works in e.g. (neo)vim out of the box.
---
Maybe eventually there should be a customizable list of word characters… but this really should be the default behavior.

feat(ui): treat slashes as word separators in prompt

---

helix-term/src/ui/editor.rs

closes #2328 
I must've mixed this up: there was https://github.com/helix-editor/helix/commit/45fd800925c7a9e2c9fa56c7259a6548689e67c8 but I must have dropped it out in a merge conflict or rebase, whoops! 😅

Prevent rendering visible whitespace on trailing cursor

---

book/src/configuration.md
helix-term/src/ui/editor.rs
helix-view/src/editor.rs

[`&nbsp;`](https://en.wikipedia.org/wiki/Non-breaking_space) maybe not the most common thing to see in files but e.g. Kakoune does support highlighting these.

feat(ui): add nbsp (non-breaking space) to rendered whitespace

---

helix-term/src/ui/prompt.rs

Allow tab-completion to continue when there is only a single, unambiguous
completion target which is a directory. This allows e.g. nested directories
to be quickly drilled down just by hitting tab instead of first selecting
the completion then hitting enter.
Close #1801

Auto-complete directory members (#1801)

---

book/src/configuration.md
helix-term/src/commands/typed.rs
helix-view/src/editor.rs

Believe it or not, not all projects have jumped onto the auto-formatting hype train :D and sometimes it is desirable to be able to quickly `:set-option auto-format false` when working on something where rustfmt would introduce too much undesirable changes in git diff.

feat(commands): make it possible to disable format-on-save via the 'auto-format' option

---

helix-view/src/clipboard.rs

cfg-gate unused functions on macos & windows

---

helix-term/src/commands.rs
helix-term/src/keymap/default.rs

adds command to manually commit undo state

Add undo checkpoint command

---

languages.toml

Just a small tweak: `.cjs` files should also be detected as Javascript. The Typescript language server [supports this file extension](https://github.com/microsoft/TypeScript/issues/38784), and afaik there is no difference in syntax so the same grammar can also be used.

feat(languages): detect cjs as javascript

---

book/src/configuration.md

The current docs are a bit confusing in my opinion because of the table: `true`/`false` aren't really keys per se. I think this clears up the usage for a common case of wanting to disable auto-pairs altogether (with `false`). See also https://github.com/helix-editor/helix/discussions/2383

Rewrite auto-pairs docs

---

book/src/generated/typable-cmd.md
helix-term/src/commands/typed.rs
xtask/src/main.rs

The syntax for the new `set-option` command is not obvious, and I had to check the code to see what it was (code comment is what is included in this PR).

Making the 'set-option' command help more descriptive.

---

runtime/queries/hcl/highlights.scm
runtime/themes/pop-dark.toml

There were 2 instances of `constant.number` in the codebase. Should be `constant.numeric` instead.

replace constant.number with constant.numeric

---

languages.toml

Perl tests have '.t' extension.

feat(languages): detect 't' as perl

---

runtime/queries/toml/highlights.scm

Makes the keys visually distinct from actual string values and is also consistent with the highlighting in the TOML docs https://toml.io/en/v1.0.0#keys
before:
after:

TOML highlight: `use variable.other.member` instead of `string` for quoted keys

---

book/src/generated/lang-support.md
helix-core/src/syntax.rs
languages.toml
runtime/queries/git-attributes/highlights.scm
runtime/queries/git-ignore/highlights.scm

This PR adds support for `.gitignore` and `.gitattributes` files. I was a little unsure of where to include dashes in the name/scope/injection regex, but I tried to be consistent with the other `git-*` filetypes. There's no indent values specified since these filetypes don't have indentation. I had to make one change to the core code to allow for hyphens in `; inherits: ...` comments, hope that's ok. Finally, using non-hyphenated grammar names seemed to be necessary, otherwise the grammars just don't work, but I'm not sure why...

feat(languages): git-ignore and git-attributes

---

languages.toml

Noticed the new grammar doesn't match the global gitignore by default, so I've added it here.

Adding the global gitignore to the default

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/odin/highlights.scm

This commit adds the odin language by using the grammar and highlighting
queries written by [MineBills repo](https://github.com/MineBill/tree-sitter-odin).
This commit resolves #2340 by just applying all the changes already
discussed in the issue.

feat(languages): add odin language

---

runtime/queries/markdown/highlights.scm

This should fix https://github.com/helix-editor/helix/issues/1597
I did it according to the current docs. Question is, should we
1. keep the 2 different styles for ordered/unordered
2. add markup for list text itself

fix Markdown list highlighting

---

runtime/themes/monokai_pro_spectrum.toml

current theme shows keyword and error in the same way - red on black
see: #2421 
before:
after:

Monokai pro spectrum theme shows error in yellow on red background

---

helix-term/src/commands.rs

Inserting a newline currently collapses any connected selections when inserting
or appending. It's happening because we're reducing the selections down to
their cursors (L2780) and then computing the new selection
based on the cursor. We're discarding the original head and anchor information
which are necessary to emulate Kakoune's behavior.
In Kakoune, inserting a newline retains the existing selection and _slides_
it (moves head and anchor by the same amount) forward by the newline and
indentation amount. Appending a newline extends the selection to include the
newline and any new indentation.
With the implementation of insert_newline here, we slide by adding the global
and local offsets to both head and anchor. We extend by adding the global
offset to both head and anchor but the local …

Prevent selection collapse when inserting a newline

---

helix-view/src/editor.rs

Inserting these with the `HashMap::insert` method evades the call
to `Selection::ensure_invariants`. The effect is that the scratch
buffer (or other buffers opened through these code-paths) can start
with a selection at (0, 0), when a file with equivalent contents ("\n")
would start with (0, 1).
I.e.:
hx
and
touch f
hx f
start with different selections even though they have an equivalent
Rope. With this change they both start with (0, 1).

prefer Document::set_selection to inserting selections directly

---

helix-view/src/handlers/dap.rs

`Tmux` is not available on windows, so it raises an error and closes the helix editor with a warning pointing to handlers/dap.
Therefore I decided to add a piece of code so that a new terminal can be opened, either with Windows Terminal or Conhost ( both running `cmd.exe` inside ).
In case of having windows terminal ( `wt.exe` ), it is executed in it.
In case of not having it, it is executed in ( `conhost.exe` ).
Example ( `conhost.exe` ):
Example ( `wt.exe` ):

feat(helix-view): view debug output on windows

---

helix-term/src/commands.rs

Currently ctrl-w in insert mode deletes the cursor which results in
unexpected behavior. The patch also reduces the selection to cursor before
performing prev word to remove the behavior of removing unnecessary text
when nothing should be removed.
1. `::#(|)#::` after `ctrl-w` should be `#(|)#::`, previously `#(|)#:`
2. `#(|::)#` after `ctrl-w` should be `#(|::)#`, previously `#(|)#`
Fix #2390
[![asciicast](https://asciinema.org/a/DMf0Kf3NsLbfQvLkcO7wwgzcy.svg)](https://asciinema.org/a/DMf0Kf3NsLbfQvLkcO7wwgzcy)
cc @scgtrp thanks for reporting the issue
Would be good if @cessen can review, I wonder if there is a better solution for this

Exclude cursor when doing ctrl-w

---

book/src/generated/typable-cmd.md
helix-term/src/commands/typed.rs

My first small contribution to an open source project.
I hope that all is in order.
Implements #2418

feat(commands): add log-open command

---

languages.toml

The Odin compiler+packages use tabs instead of spaces, so this PR sets tabs as default in `languages.toml`.

Default to tabs instead of spaces for Odin files

---

languages.toml

According to the [official Hare style guide](https://harelang.org/style/#a-general-conventions), "The tab size SHOULD be 8 columns."
I have made the corresponding change.

Change default Hare tab width to 8

---

helix-lsp/src/transport.rs

A language server may push a response which doesn't belong to any
request. With this change, we discard the response rather than
crashing.
In the case of #2474, the language server sends an error message
with a null request ID which should not ever exist in the
`pending_requests` HashMap.
closes #2474

Prevent panic when handling an LSP response with no request

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/sshclientconfig/highlights.scm

Related to #2455 
@pickfire I am a tree sitter noob, the file in this PR is just a copy of https://github.com/metio/tree-sitter-ssh-client-config/blob/769d7a01a2e5493b4bb5a51096c6bf4be130b024/queries/highlights.scm

Add tree-sitter ssh client config queries

---

helix-core/src/syntax.rs
runtime/queries/rust/textobjects.scm

in example like:
```rust 
/// some doc comment related to struct Test
#[derive(Debug)]
pub struct Test {
test: u32,
}
```
the `mac` selector will select `struct` with `#derive` macro and doc comments included

Include macro attributes to impls, structs, enums, functions etc. texobjects

---

book/src/themes.md
helix-term/src/ui/editor.rs
theme.toml

This commit adds separate diagnostic highlight colors for the different
types of LSP severities. If the severity type doesn't exist or is
unknown, we use some fallback coloring which was in use before this
commit.
Some initial color options were also added in the theme.toml
Resolves issue #2157

Separate colors for different diagnostics types

---

helix-term/src/commands.rs
helix-term/src/ui/picker.rs

Rust 1.61 was released a few hours ago and some of the new clippy lints break the CI. These should fix the Lint CI.

address rust 1.61.0 clippy lints

---

book/src/generated/lang-support.md
languages.toml

Added the language server command for the Eclipse JDT language server for Java `command = "jdtls"`

Added a default lsp server for Java in languages.toml

---

helix-term/src/commands.rs
helix-term/src/keymap/default.rs
helix-view/src/editor.rs
helix-view/src/tree.rs

* add Tree::swap_split_in_direction()
* add swap_view_{left,down,up,right} commands, bound to H,J,K,L
respectively in the Window menu(s)
* add test for view swapping

Implement view swapping

---

helix-term/src/commands/typed.rs

Fix panic when reloading a shrunk file

---

book/src/themes.md
helix-term/src/ui/picker.rs
theme.toml

Addresses #2522. 
I'm unsure what the most proper name/scope for the theme key is. I've chosen `ui.background.separator` as `ui.background` is the style used for widget borders so the scope should draw a reasonable default for all themes.

Add theme key for picker separator

---

helix-tui/src/widgets/block.rs
helix-tui/src/widgets/mod.rs

Specifying empty for bitflags is not recommended, it is now removed and added
Default. For BorderType, it now defaults to plain.

Refactor Block with Default and bitflags

---

book/src/keymap.md
helix-term/src/commands.rs
helix-term/src/keymap/default.rs

Implements #2002, with a difference in that using the command when the selection spans only a single line will not result in conditional logic.
I believe there's some holes in the logic that could open to a panic so marking as draft until I can address.

Add shrink equivalent of extend_to_line_bounds

---

.github/workflows/build.yml
.github/workflows/msrv-rust-toolchain.toml
.github/workflows/release.yml
helix-view/src/handlers/dap.rs
rust-toolchain.toml

Pinning to a particular version brings some extra burden that we have to remember to update rust, but I think it's worth it to make CI more reproducible around new rust releases. The CI uses new rust versions almost immediately after release which means that CI may start failing faster than we can fix the lints, as in #2514. Ideally we update rust and fix clippy lints all in one go.
Connects #2528

CI: pin rust to 1.61.0 and check MSRV

---

runtime/themes/catpuccin.toml

Add the soothing pastel color theme to helix
repository: https://github.com/catppuccin/helix

Add Catppuccin Theme

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/verilog/highlights.scm
runtime/queries/verilog/injections.scm
runtime/queries/verilog/locals.scm
runtime/queries/verilog/textobjects.scm

Verilog files support
* syntax highlighting
* language server `svlangserver`
* some textobjects

Basic verilog support

---

runtime/queries/c/textobjects.scm
runtime/queries/go/textobjects.scm
runtime/queries/php/textobjects.scm
runtime/queries/python/textobjects.scm
runtime/queries/rust/textobjects.scm

It allows `maa` to select `parameter`, `argument`, `type_parameter`, `type_argument`, `closure_parameter` with following comma
And also `next_argument` and `prev_argument` matches argument with comma
updated also for `C`, `PHP`, `Go`, `Python` languages

Add `parameter.around` text object query

---

languages.toml
runtime/queries/erlang/highlights.scm
runtime/queries/gleam/highlights.scm
runtime/queries/gleam/locals.scm

The commits have the nitty-gritty details: these are some small corner-case fixes that improve the highlights for Erlang and Gleam.

update tree-sitter queries and grammars for Erlang and Gleam

---

CHANGELOG.md

The link to the `pop-dark` PR in the [CHANGELOG.md](./CHANGELOG.md) points to a _different_ theme. This PR fixes the minor mistake :)

Fix link to `pop-dark` in `CHANGELOG.md`

---

helix-loader/src/grammar.rs

Earlier in the builder we enable C++ (`.cpp(true)`) but only mention
the C compiler in the build failure message. Some grammars that have
C++ external scanners can provoke build failures in this step if a
C++ compiler isn't installed, so mentioning it in the error message
should help out debugging.
See also https://github.com/helix-editor/helix/issues/2596#issuecomment-1140328579

mention the C++ compiler in the grammar build failure message

---

helix-core/src/path.rs

`strip_prefix` will itself check whether the string starts with the
prefix, so the extra call to `starts_with` was unnecessary.

Remove unnecessary `unwrap`

---

runtime/themes/tokyonight.toml
runtime/themes/tokyonight_storm.toml

Change `ui.virtual.ruler` color to `bg` instead of `fg`, correct syntax highlighting to more closely resemble the neovim theme.

Adjust colors in tokyonight themes

---

languages.toml
runtime/queries/nix/highlights.scm
runtime/queries/nix/indents.scm

Update grammar and queiries to the latest upstream. Also add improved indents thanks to @oxalica.

feat(lang): Update Nix grammar & improve queries

---

runtime/queries/elixir/injections.scm

@the-mikedavis I figured I'd checkout Helix and see how it compares to Neovim. Consider me a convert 😆  
This PR contains two changes:
- injects Markdown, the [official documentation format](https://hexdocs.pm/elixir/writing-documentation.html#markdown), into Elixir
- Removes the non-existent `h` sigil from Elixir language injections. Phoenix Live View only supports the uppercase `H` sigil for HEEx.
Please let me know if there are any tests or documentation that need to be updated. Thanks!

Elixir: inject Markdown into docs, remove h sigil HEEx injection

---

helix-term/src/commands.rs

Steps to reproduce:
1. press  `Shift+|` 
2. enter `ls` in prompt
3. press `u` for undo 
4. ether nothing happened or helix closed with error

Fix unwrap error when undo after `shell_append_output`

---

runtime/themes/catpuccin.toml

Looks like black_1 was defined but never used.  This was likely meant to be ui.popup all along?

catpuccin ui.popup should be a different color from ui.background

---

helix-loader/src/grammar.rs

When handling grammars, fetching and building is done in a thread pool.  Results are communicated over channels and the receiving channel is closed on first error. This causes subsequent sends to fail causing a mess in stderr. This ignores all SendErrors causing only the first error to be printed.
Solves #2642

Ignore SendErrors when handling grammars

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/edoc/highlights.scm
runtime/queries/edoc/injections.scm
runtime/queries/erlang/injections.scm
runtime/queries/markdown/highlights.scm
runtime/queries/tsq/highlights.scm

Syntax highlighting for the Erlang doc generator format: https://www.erlang.org/doc/apps/edoc/chapter.html. The XHTML part was actually quite easy to parse: it just looks for `<` and `>` and injects it as HTML.
Also included some fixes for markdown and tsq highlights.
Example:

add tree-sitter-edoc

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/jsdoc/highlights.scm

connects #2648
This is a pretty small grammar. The injection for comments is already set up in `runtime/queries/javascript/injections.scm`. Github also uses this for their syntax highlighting, like in:
```js
/**
* Extract the string matched by the regex and return both the resulting string
* and the matched string
*
* @param {string} source
* @param {RegExp} regExp
* @returns
*/
export function extract(source, regExp) {
const result = regExp.exec(source)
return result ? {
normalizedSource: source.replace(result[0], ''),
extracted: result[1]
} : { normalisedSource: source, extracted: '' }
}
```

add tree-sitter-jsdoc

---

runtime/themes/night_owl.toml

This lets you still see syntax highlighting instead of having a set fg for selected text. I also set it to `dim` to make it more recognizable.

Update selection style of Night Owl

---

helix-view/src/editor.rs
helix-view/src/view.rs

In certain circumstances it was possible to cause a panic when closing
buffers due to some mishandling of view document history.
A change has been made to delete removed documents from the history of
accessed documents for each view. The ensures we don't attempt to jump
to a deleted document by mistake.

Fix panic on close last buffer (#2367)

---

helix-term/src/commands/lsp.rs

When a goto command is cancelled, the jumplist should remain unchanged.
This commit delays saving the current selection to the jumplist until jumping to a reference.
Fixes #2663

Avoid modifying jumplist until jumping to ref

---

helix-term/src/commands/typed.rs

I lost my train of thought and accidentally typed `:q! :w` 😄
Since quitting is a little destructive, I think it makes sense to fail the quit if it's not a well-formed 0-arg `:quit(!)`.
What do you think?

ensure :quit and :quit! take no arguments

---

helix-term/src/commands.rs
helix-view/src/editor.rs

In certain circumstances it was possible to get into an infinite loop
when replaying macros such as when different macros attempt to replay
each other.
This commit adds changes to track which macros are currently being
replayed and prevent getting into infinite loops.
Fixes issue #2249

Fix crash due to cycles when replaying macros

---

book/src/languages.md
helix-core/src/syntax.rs
helix-lsp/src/client.rs
helix-view/src/document.rs

- adds optional field _format_ to **[[language]]** sections in **languages.toml**
- passes specified options to the LSPs via [FormattingOptions](https://github.com/microsoft/language-server-protocol/blob/gh-pages/_specifications/specification-3-16.md#document-formatting-request--leftwards_arrow_with_hook)
- updated documentation accordingly
typescript example:
```toml
[[language]]
name = "typescript"
auto-format = true
format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true }
```

Passing extra formatting options to LSPs

---

book/src/generated/typable-cmd.md
helix-term/src/commands/typed.rs

- Add `insert-output` and `append-output` to allow for usage within command list as-well-as config files
This will allow for the example below where I am trying to create a syntax-highlighted git diff command
```
G = [ 
":open ~/.config/helix/temp.diff",
"select_all",
"delete_selection",
":append-output git diff"
]
```

Add shell insert commands to typable and config

---

.github/workflows/release.yml
helix-loader/Cargo.toml
helix-loader/src/main.rs

This is an optimization for the release CI. The release CI can take
a while since it compiles release builds for all operating systems.
We cut down on duplicate work and overall time by fetching
tree-sitter grammar repositories and then using those repositories
in all later steps. Previously we built all of helix just to run
helix_loader::grammar::fetch_grammars()
which is wasteful on time. With this change we only build the
helix-loader crate.

Use a minimal binary to fetch grammar sources in release CI

---

book/src/remapping.md
helix-view/src/input.rs

Closes #2369 
Removed some of the existing named keys and added tests. Please let me know if there is anything more that I can do.

simplify some keymap key names

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/elixir/textobjects.scm
runtime/queries/erlang/highlights.scm
runtime/queries/erlang/textobjects.scm
runtime/queries/gleam/textobjects.scm
runtime/queries/rust/textobjects.scm

Adds [textobject](https://docs.helix-editor.com/usage.html#textobjects) queries for Erlang, Elixir & Gleam
Also includes an update for tree-sitter-erlang that makes `function_clause` a named node.
Erlang and Elixir may have multiple function clauses for one function:
```erl
fib(0) -> 0;                                %% one textobj, ]f selects this line
fib(1) -> 1;                                %% this line is another
fib(N) when N > 0 -> fib(N-1) + fib(N-2).   %% and this line is another
```
In these queries I'm capturing function clauses as `function.around` but I'm curious if others think it should be around the entire function definition.

add textobject queries for beam languages, capture rust closures as functions

---

helix-term/src/ui/markdown.rs

Do not add extra line breaks in markdown lists

---

languages.toml

Not all Elixir projects use dialyzer and it can cause the editor to slow down quite a bit on large projects if the PLT is not built.
See https://github.com/elixir-lsp/elixir-ls#dialyzer-integration=

elixirLS disable dialyzer by default

---

flake.nix

`rust-analyzer` is needed for development but not included in the shell environment.
Add it.

Add rust-analyzer to shell environment

---

runtime/tutor.txt

I have noticed some inconsistencies in the [tutor.txt](../blob/master/runtime/tutor.txt) file.
For example, there are no fixed amount of lines between each section (I opted for 3).
Also, in every numbered list, each element is never separated by a new line, except for the *COUNTS WITH MOTIONS* section:
https://github.com/helix-editor/helix/blob/efae76160d19ebba2bba31ecd5c104374c7b4483/runtime/tutor.txt#L243-L259

Cleanup for runtime/tutor.txt

---

book/src/themes.md
runtime/queries/c/highlights.scm
runtime/queries/rust/highlights.scm

Inspired by VIM's StorageClass hi group

Introduce storage_class highlight scope

---

helix-term/src/ui/mod.rs
helix-view/src/editor.rs

- Add file-picker.follow-symlinks configuration option (default is true), this
also controls if filename and directory completers follow symlinks.
- Update FilePicker to set editor error if opening a file fails, instead of
panicing.
Fix #1548
Fix  #2246

Better handling of symlinks

---

book/src/from-vim.md

Now helix has its own wiki for [Migrating from Vim](https://github.com/helix-editor/helix/wiki/Migrating-from-Vim), let's add the link to the book.

Add migrate from Vim wiki link

---

helix-term/src/application.rs
helix-view/src/editor.rs

This fixes a problem where editor.auto-pairs is not reloaded with the rest of the configuration.
I also added idle-timeout, but that is likely not to matter due to it being reset between each key press.

Update auto-pairs and idle-timeout when the config is reloaded

---

runtime/tutor.txt

The amount of empty lines between sections were truncated to 3 lines in #2590, but they were already deliberately spaced out by @Omnikar such that a section would take up exactly a 80x24 terminal screen (so 22 lines per section if you account for the status line).
Apparently @Omnikar approved of that change change though they didn't make any comment the pr itself. If the decision was made to truncate the spacing intentionally then that's fine, I was just confused why it was done.

Restore section spacing in tutor.

---

base16_theme.toml

The built-in base16_default theme was not updated with changes from 82fb217, which would look as below.
This reverts it to how it was before the change (ie. `ui.statusline`).

Update theme base16_default (`ui.menu`)

---

helix-view/src/input.rs

> Rather than just testing these keys are now unsupported, shouldn't we also test that they get parsed correctly by the new syntax?
Adding more happy path tests to make sure the removed key names are parsed correctly by the new syntax. This is a follow up to this [comment](https://github.com/helix-editor/helix/pull/2677#discussion_r889790263) in the previous PR #2677

simplify some keymap key names follow up tests

---

Cargo.lock
helix-lsp/Cargo.toml
helix-lsp/src/client.rs
helix-lsp/src/jsonrpc.rs
helix-lsp/src/lib.rs
helix-lsp/src/transport.rs

We should not depend on jsonrpc-core anymore:
* The project just announced it's no longer actively maintained[^1],
preferring their new implementation in `jsonrpsee`.
* The types are too strict: we would benefit from removing some
`#[serde(deny_unknown_fields)]` annotations to allow language
servers that disrespect the spec[^2].
* We don't use much of the project. Just the types out of core.
These are easy to embed directly into the `helix-lsp` crate.
[^1]: https://github.com/paritytech/jsonrpc/pull/674
[^2]: https://github.com/helix-editor/helix/issues/2786

embed jsonrpc types from jsonrpc-core crate

---

runtime/themes/noctis_bordo.toml

A port of the theme, Noctis Bordo: https://github.com/liviuschera/noctis#noctis-bordo
🤤

[Theme] Noctis Bordo

---

runtime/queries/javascript/injections.scm
runtime/queries/jsdoc/injections.scm

this adds the injection for tree-sitter-comment to javascript. i am not sure if there is a reason for this missing. maybe it was supposed to interfere with the injection for "jsdoc" comments?
anyhow, it does seem to work to with both injections on "comment".

adds missing tree-sitter-comment injection for js/ts

---

book/src/guides/adding_languages.md
book/src/languages.md

This change moves the configuration tables from the Adding
Languages guide into the overall Languages section. It also
adds more detailed documentation on the `language-server`
configuration key and fixes a typo in the "mylang" example
(the scope was `scope.mylang` instead of `source.mylang`).

rewrite language configuration docs

---

helix-view/src/gutter.rs

Fixes: #2827.
Gets sub-slice of diagnostics for all diagnostics on a line (still using binary search), and finds the max within the diagnostics of the line.

Display highest severity diagnostic in gutter

---

helix-term/src/commands.rs
helix-term/src/ui/editor.rs
helix-view/src/input.rs

The command palette previously used `+` as a delimiter for denoting a single key in a key sequence, (like `C+w`). This was at odds with how the statusline displayed them with pending keys (like `<C-w>`). This patch uses the `<C-w>` formatting everywhere.

Format keys identically in statusline and command palette

---

helix-core/src/shellwords.rs
helix-term/src/commands/typed.rs

Shellwords was previously disabled for Windows because it uses backslash for path separators, while we use backslash for escaping.
This change enables shellwords without escaping for Windows users, enabling them to open files with spaces in file names (using quotes or doublequotes)

Enable shellwords for Windows (with escaping disabled)

---

helix-term/src/ui/menu.rs

The scrollbar length used to increase with more entries in the menu, which was counter-intuitive to how scrollbars worked in most applications. Turns out there was a typo in the floor division implementation :)

Fix scrollbar length proportional to total menu items

---

helix-term/src/ui/editor.rs

Mouse-click-up copies the selection produced by dragging. The event
is ignored if the selection has a width of 1 though so you don't
copy when clicking rather than dragging. The current check copies
text when it has a visible width of 1 but is actually multiple
characters in the rope like a CRLF line-ending. With this change
we check the unicode width of the character(s) in the selection
rather than the range length, so clicking on a CRLF line-ending
does not copy.
Closes #2699

check selection's visible width when copying on mouse click

---

helix-core/src/register.rs
helix-term/src/ui/prompt.rs

This PR fixes the intended usage of last prompt on empty input but always shows wrongly the first prompt which is useless in b14c258a2c447b892c89d3e68ef4c9a74effca85 commit.

fixes showing the last prompt on empty input

---

runtime/themes/acme.toml

A Helix theme inspired by Plan 9 Acme & Sam.
Some people(including me) prefer [little to none syntax highlighting](https://www.linusakesson.net/programming/syntaxhighlighting/) for everything except comments and strings :slightly_smiling_face:

[Theme] Acme 

---

helix-core/src/object.rs

If a tree-sitter grammar outputs multiple nodes with the same range that contain each other (I noticed this with the LaTex grammar and the `text` and `word` nodes), the `expand_selection` command currently "gets stuck" at them. This happens because the `descendant_for_byte_range` function always returns the lowest of these nodes, so changing the selection to the range of its parent doesn't do anything.
I changed it, so that now it skips nodes with identical ranges.

Fix edge-case in tree-sitter expand_selection selection command

---

helix-term/src/ui/menu.rs

Adds a bit of padding to the left edge of the completion popup:
| --- | --- |
| ![before](https://user-images.githubusercontent.com/23398472/172911110-3e94c9aa-4b7b-4f9e-bfdc-7668bb696fb8.png) | ![after](https://user-images.githubusercontent.com/23398472/172911128-852324db-e18a-49d9-8a1a-1eec0e807258.png) |

Add single width left margin for completion popup

---

languages.toml

I found default listed ruby file type (`rakefile` and `gemfile`) does not match Rakefile and Gemfile, so fix them.

languages: Fix ruby rakefile and gemfile file type

---

book/src/themes.md
helix-term/src/ui/menu.rs
runtime/themes/onedark.toml
theme.toml

Depends on #2728.
---
- Align the scollbar to the right edge of the popup rather than at a margin of one.
- Add a scrollbar track and a new scope `ui.menu.scroll`.
| --- | --- |
| ![before](https://user-images.githubusercontent.com/23398472/173199025-2ef3e479-1555-4abe-9459-eabf2c41239a.png) | ![after](https://user-images.githubusercontent.com/23398472/175085392-65581406-7fb1-47cc-bb46-27126ca18732.png) |
A multiline scrollbar like the one mentioned in https://github.com/helix-editor/helix/pull/2728#issuecomment-1152034487 would be nicer though:

Right align scrollbar with track in completion popup

---

book/src/configuration.md
helix-term/src/ui/editor.rs
helix-view/src/editor.rs

Highlight all lines where cursers are on, imitating vim's `cursorline` option.
See #1761.

Implement cursorline

---

helix-lsp/src/client.rs
helix-term/src/commands.rs
helix-term/src/commands/lsp.rs
helix-term/src/keymap/default.rs

Hi !
This PR implements the LSP [textDocument/documentHighlight](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentHighlight) request. The command asks the LSP server for the ranges of references to current symbol, and select them (using multiple cursors).
I initially just wanted to have these symbols highlighted (like in nvim or vscode), but using multi-cursors is more convenient because the user can navigate between the references using `(` and `)`, and also because it reuses already existing components : 
I have set the `Space + h` (for highlight) mapping to use this.
Have a good day !

feat: highlight / select symbol under cursor using LSP textDocument/documentHighlight

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/starlark/highlights.scm
runtime/queries/starlark/injections.scm
runtime/queries/starlark/textobjects.scm

The Bazel build system uses Starlark as a DSL. Starlark is syntax-wise equivalent to python so we can just reuse the python grammar for simplicity :)
Also included is bash highlighting for [`bazelrc`](https://bazel.build/docs/bazelrc) files.

support Bazel languages

---

helix-term/src/commands.rs

Resolves #2845 
Resolves #2846 
Took me a bit to sit down and write the fix, but it seems quite straightforward (just shuffling two lines). I added a couple explicative comments, but to summarize:
The existing macro replay protection didn't work, because the guard (an entry in the `replaying_macro` vector) was cleared at the end of the `replay_macro` function, but all that function does is queue the keypresses to be executed in a separate context, so recursion could still happen. Now, the guard is cleared only after the entire queue of macro presses has resolved.
As for the lockdown, The problem is that we were marking the macro as being under replay before validating it, which left the register in an invalid unrecoverable state if the macro was invalid.

Fix recursive macro crash and empty macro lockout

---

flake.lock

This fixes the aarch64-darwin build - the newer revision uses the
cCompiler override to compile tree-sitter with clang instead of
gcc (which fails).
Supersedes #2906

nix: update nixCargoIntegration

---

book/src/configuration.md
book/src/themes.md
helix-term/src/ui/editor.rs
helix-view/src/editor.rs
runtime/themes/rose_pine.toml

In similar vein to neovim's `lualine` and similar statusline packages this allows helix users to style their mode based on which mode it is thus making each mode more visually distinct at a glance
Screenshots of how it looks attached below

Add mode specific styles

---

runtime/themes/tokyonight.toml
runtime/themes/tokyonight_storm.toml

Updates for tokyonight and tokyonight_storm to support cursorline.
tokyo-night:
tokyo-night-storm:

Update cursorline for tokyonight + tokyonight_storm

---

runtime/themes/nord_light.toml

[Nord](https://www.nordtheme.com/) inspired light theme

[Theme] Nord Light

---

helix-term/src/commands.rs

This issue closes #2842
In summary:
`delete_char_backward` ignored any other whitespace other than ' ', which resulted in you not being able to backspace or `C-h` on insert mode when there's only whitespace with the character next to the cursor being a lexiographic whitespace.

Fix backwards character deletion on other whitespaces

---

helix-term/src/ui/mod.rs

*I haven't contributed before. I'm not attached to this change. I realise it might not be considered worth while. Just excited by the project and noticed this minor thing.*
Previously the themes were appearing unordered after typing `:theme `.
This sorts them first by fuzzy score and then by name so that they
generally appear in a more ordered fashion in the initial list.
The sort by name does not really pay off when there is a score so an
alternative approach would be to sort by score if there is string to
fuzzy match against and otherwise sort by name.
I've lowercased the names as that avoids lower case & upper case letters
being sorted into separate groups. There might be a preferable approach
to that though.

Sort themes, language & files by score & then name

---

helix-term/src/ui/picker.rs

This is for themes that use `bg` to highlight the selection in picker menus. 
Makes it easier to navigate, looks cleaner, and is in line with the style of the autocomplete menu.
before:
after:
Not 100% sure if this is still needed:
https://github.com/helix-editor/helix/blob/fbb200b7ddd3f70bdc8f76b6c53f030d3990dc62/helix-term/src/ui/picker.rs#L638-L639

Highlight whole row in picker menus

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/elvish/highlights.scm
runtime/queries/elvish/injections.scm

Added [elvish](https://elv.sh/).  Can't see the grammar taking any effect so there is likely still sth. wrong with the config.

languages: added elvish

---

README.md
book/src/install.md

The Windows command used to set up the runtime directory in the installation documentation is valid when run with cmd.exe, but when run with Powershell, I need to use another command.
My Powershell version
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682
```

Add runtime `xcopy` command on powershell in docs

---

helix-term/src/commands.rs
helix-term/tests/test/commands.rs

Fix backwards selection duplication widening bug

---

helix-dap/src/types.rs

DAP follows the same strict TypeScript interface syntax as LSP
which states:
> The document uses TypeScript interfaces in strict mode to describe
> these. This means for example that a `null` value has to be explicitly
> listed and that a mandatory property must be listed even if a [falsy]
> value might exist.
So we have to skip serializing any fields that end in `?` instead
of passing `null`.
Also included is a change for a `cwd` field that was in an `Option` but is a required field.
More context: https://github.com/erlang-ls/erlang_ls/pull/1346
It looks like lsp-types does the same verbose `#[serde(skip_serializing_if = "Option::is_none")]` dance for optional fields: https://github.com/gluon-lang/lsp-types/blob/b26003aa38ad8a996b583de162b66615212b94a3/src/signature_help.rs#L13-L24

DAP: fix serialization of `Option`s

---

book/src/generated/lang-support.md
languages.toml

This pull request adds support for the [Idris2](https://github.com/idris-lang/Idris2) language. No grammar is included yet because I don't believe there is one (but I'm happy to be proven wrong if someone is able to find one). The only repo I could find was [this one](https://github.com/gwerbin/tree-sitter-idris2), but it's incomplete.
I have tested the language server and it works without issues.
The only thing I was unsure about is whether the filetype should be called `idris` or `idris2`, since there are breaking changes between the two languages. I lean towards `idris`, because:
- files of both types share the `.idr` extension, so we couldn't really support both even if we wanted to since there's no simple way to distinguish between the languages
- [Idris 1 is not actively …

add language `idris`
