book/src/configuration.md
helix-core/src/selection.rs
helix-core/src/transaction.rs
helix-lsp/src/lib.rs
helix-lsp/src/snippet.rs
helix-term/src/ui/completion.rs
helix-view/src/editor.rs

Fixes #4380 
Fixes #5469
This PR improves the completions in helix in multiple subtle ways. These fixes were lumped together as they all interact. 
The core change of this PR is a fix for #4380: Adding an option so that helix completions only insert text and don't replace the rest of the word (using `item.insert` instead of `item.replace`). I believe this to be the better default, so I changed the default behavior to use `item.insert`. This not only feels more appropriate for an *insert* mode action in a modal editor, but I feel that the replace mode has some issues that don't make it as suitable for a default setting (see below).
While working on this I noticed that in cases where a LSP does not supply a TextEdit, and we have to determine the range based on word boundaries ourself helix …

Improved Completion

---

book/src/themes.md
languages.toml
runtime/queries/yuck/highlights.scm
runtime/queries/yuck/injections.scm

This PR improves the tree-sitter-yuck parser and highlighting queries:
It also introduces a new `tag.builtin` scope, as I think this is a relatively uncontroversial addition.

Improved yuck highlighting (and parser), and introduced a tag.builtin scope

---

runtime/queries/rust/injections.scm

Now also highlights:
- `sqlx::query_unchecked!()`
- `sqlx::query_as_unchecked!()`
More or less copy-pasted from here: #3647, not sure if this can be deduplicated a bit (I'm not familiar with the language)

Also highlight unchecked variants of the sqlx query methods

---

book/src/configuration.md
book/src/themes.md
helix-core/src/diagnostic.rs
helix-core/src/doc_formatter/test.rs
helix-core/src/text_annotations.rs
helix-lsp/src/client.rs
helix-term/src/commands.rs
helix-term/src/commands/lsp.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/picker.rs
helix-view/src/document.rs
helix-view/src/editor.rs
helix-view/src/tree.rs
helix-view/src/view.rs
languages.toml

Add support for LSP type hints (merged in version 3.17 of the spec, a few month old now).
For now, I only added it in the main editor views, pickers do not have type hints.
Even if we decide they need to, I would prefer doing it in another PR since this one is already big
enough as it is.
I'll join a screen in a comment below, and if people could try it out with their LSPs and configs, it
would be very useful, since I pretty much only use Rust-Analyzer so testing may be somewhat limited still.
Closes #2070
EDIT: [instructions to test](https://github.com/helix-editor/helix/pull/5934#issuecomment-1445040945)

Feat: LSP Type Hints

---

helix-lsp/src/lib.rs
helix-term/src/ui/completion.rs

Fixes #6255
The way multi-line snippet indentation was implemented in #5864 was incorrect. Lines inserted in snippets were indented to align with the start of the snippet. However, snippets are supposed to be indented to match the indentation level of the line they are on, see vscode: https://github.com/microsoft/vscode/blob/1d0175478873e6ad29033d84925ce5d936032b3c/src/vs/editor/contrib/snippet/browser/snippetSession.ts#L404
This makes a lot more sense as this basically just ensures that snippet newlines are identical to hitting tab manually. Note that I opted not to run indentation queries here. The LS should be aware of any language specific indentation needs and wouldn't expect the client to do this for him (the standard also specifies that snippets should be adjusted to the …

indent snippets to line indent instead of completion start

---

runtime/themes/fleet_dark.toml

Diverges from Fleet, as far as I know they don't have inlay hints.

fleet_dark: theme inlay hints

---

runtime/themes/catppuccin_mocha.toml

this pr adds theme inlay hints for catppuccin
how it looks:

theme/catppuccin: add ui.virtual.inlay-hint

---

runtime/themes/dark_plus.toml

Taken from the official theme:
```json
"editorInlayHint.background": "#4d4d4dcc",
"editorInlayHint.foreground": "#ffffff",
"editorInlayHint.parameterBackground": "#4d4d4dcc",
"editorInlayHint.parameterForeground": "#ffffff",
"editorInlayHint.typeBackground": "#4d4d4dcc",
"editorInlayHint.typeForeground": "#ffffff",
```

dark_plus: theme inlay-hint

---

runtime/themes/autumn.toml

The configuration differs between parameters (upright) and types (slanted).

Autumn theme: add `ui.virtual.inlay-hint` config

---

helix-core/tests/indent.rs

This uses @stabor705's fix for #6262 and adds tests that fail with the current implementation, but pass with this fix.

Test indentation level calculation

---

helix-lsp/src/lib.rs
helix-term/src/application.rs

Some language servers send this request even though we don't enable dynamic capability registration. In some language servers that use the vscode-languageserver-node dependency, replying with an error can cause the server to exit because an un-caught rejected promise is fatal.
Replying with a JSONRPC error that the method is not handled is the correct thing to do but given that it causes some language servers in the wild to exit and that ignoring it doesn't cause any harm, we can workaround the exits by just sending an OK and doing nothing. This is similar to a workaround done by neovim.
Recent examples: #6230, #6243

LSP: No-op client/registerCapability requests

---

Cargo.lock
helix-term/Cargo.toml
helix-term/src/application.rs

From kill(3p):
If pid is 0, sig shall be sent to all processes (excluding an unspecified set
of  system processes) whose process group ID is equal to the process group ID
of the sender, and for which the process has permission to send a signal.
This fixes the issue of running `git commit`, attempting to suspend
helix with ^Z, and then not regaining control over the terminal and
having to press ^Z again.
---
Fixes https://github.com/helix-editor/helix/issues/3522.
---
I opted to add the `nix` crate because it has nice Rust wrappers around e.g. `kill`, handling error cases and other stuff for us. However, I could easily port it to the `libc` crate directly, if desired.

helix-term: send the STOP signal to all processes in the process group

---

runtime/themes/molokai.toml
runtime/themes/monokai.toml

Fixes #4704
Initial draft of a Molokai theme for Helix.

Add molokai theme

---

runtime/themes/gruvbox.toml
runtime/themes/gruvbox_dark_hard.toml
runtime/themes/gruvbox_light.toml

The gruvbox themes (`gruvbox`, `gruvbox dark hard` and `guvbox light`) don't provide a colour for the new virtual inlay hints. Looking at the original repo, and other derivatives, there doesn't appear to be a clear definition of what inlay hints should be. Although most sources indicate that it can be the same as the color for comments.
Considering that, this commit sets the new field on each of the three themes to be `gray1`, same as commented text.
`gruvbox` old:
`gruvbox` new:
`gruvbox dark hard` old:
`gruvbox dark hard` new:
`guvbox light` old:
`guvbox light` new:

Update gruvbox color themes to support inlay hint

---

helix-lsp/src/client.rs
helix-term/src/commands/lsp.rs

Tried my best to fix #6249
Tell me if there is something to change :smile:

Check language server symbol renaming support before prompting

---

helix-term/src/commands/lsp.rs

**Problem**
Currently in master lsp errors are reported as follows, as you can see the diagnostic message and code are attached to each other making it hard to read.
**This pr** solves that.

LSP: Separate diagnostic picker message and code

---

runtime/queries/php/highlights.scm

this pr is just simple fix for missing keywords in php queries

queries/php: add missing keywords `unset` and `clone`

---

runtime/themes/gruvbox_dark_hard.toml
runtime/themes/gruvbox_light.toml

These gruvbox variants were introduced before theme inheritance and only differ by a few colors. This change cleans up the duplicated theming with theme inheritance.

theme: Use inheritance for gruvbox themes

---

languages.toml
runtime/queries/erlang/highlights.scm
runtime/queries/nix/highlights.scm

**Nix**:
* Switch nix grammar repository location to the new repo. The author has transferred the repository to `nix-community`: https://github.com/nix-community/tree-sitter-nix
* Capture `:` and `...` as `punctuation.delimiter`.
**Erlang**:
* Macros that start with underscore were incorrectly marked as `comment.unused` rather than `keyword.directive` due to an ordering issue of those two patterns.
* Recognize escripts as Erlang by the shebang.

Update Nix and Erlang highlights

---

book/src/configuration.md
helix-term/src/application.rs
helix-tui/src/backend/crossterm.rs
helix-tui/src/lib.rs
helix-view/src/editor.rs

Fixes  #6196. If set to 'true' this option will force terminal undercurl support.
I don't have ArchLinux so tested this by setting `undercurl = true` in my config file and running a version of helix where `has_extended_underlines` was only set by the config option.
I didn't find any related integration tests that could help me in writing one for this. If needed (and someone can point me in the right direction) I may be able to add that as well.

Add undercurl config option

---

helix-term/src/commands/typed.rs

Edit: This doesn't _fix_ #2772, it does enable the fix. It fixes [my issue](https://github.com/helix-editor/helix/issues/5947) that was closed as duplicate, though.
I think there's a bigger change we can make here to address some other code duplication that looks something like setting argument types of commands within the TypableCommand struct and using that data both for completion _and_ for verification of the number of arguments. Currently, some commands have checks for argument length and emit errors while others silently ignore trailing arguments.
~I'm not _thrilled_ about having variadic length completers represented as different enum variants but as we statically allocate all the command configuration I couldn't use a dynamic container.~ I've also left the implementation of arity …

Only complete appropriate arguments for typed commands.

---

runtime/themes/fleet_dark.toml

As Fleet does not have these, this is an interpretation and adaptation for helix.
* Adjust inlay hints to make them blend more into the background and not stand out as much.
* Bring back color modes
* EDIT: Adjusted virtual + ruler while I was at it
No errors from themelint

adjust inlay hints, color modes and virtual for fleet dark

---

xtask/src/themelint.rs

Since #5934 closed #2070 I think the linter should check for these.
Maybe it's about time that we run the linter against PRs with changes to `/runtime/themes`?
EDIT: this now lints for `ui.virtual` as a catch all for present and future virtual text.

feat: lint for `ui.virtual` and catch present and future virtual based features

---

runtime/queries/gdscript/highlights.scm

- add gdscript2 type.builtin
- add gdscript2 keyword 'await'
- update label for more note_path
- update function and parmeter

Update gdscript highlight

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/v/highlights.scm
runtime/queries/v/indents.scm
runtime/queries/v/injections.scm
runtime/queries/v/textobjects.scm

- Update highlight
- add indents
- add textobject
- add injections
Issues #6164 and #6267.
vlang and verilog has file type conflicts in languages configurations.

Improve tree-sitter queries for vlang

---

runtime/themes/solarized_dark.toml
runtime/themes/solarized_light.toml

This uses the same color as comments, which is a light gray in both dark and light.
I think it also looks nice with italics, to visually distinguish it from "real" gray text like comments.
Without this, virtual hints were defaulting to the same white color used for identifiers, which looked confusing.

Add inlay-hint style for solarized themes.

---

helix-term/src/ui/document.rs

Addresses most of #6297. 
Would like some advice on what should be done about tab rendering. Is it even needed to be addressed because I don't think the inlay hints would draw a tab?

Prevent whitespace from rendering inside inlay hints

---

helix-lsp/src/client.rs
helix-term/src/application.rs
helix-term/src/commands/lsp.rs

This is a slight followup to #6173
I noticed that similar bugs could occur basically anytime the LS sends an edit to the client. The user can always add some new text which makes the received text invalid. However, for these edits the LSP standard actually includes a mechanism to deal with the problem: Whenever we send a change a notification to the server, the client must attach a unique version to the resulting document state. 
If the LSP server sends an edit to the client, that edit includes the document version it applies to and if that version doesn't match the current version then that change can not be applied/should be discarded.
For workspace edits specifically there are actually many capabilities which include the exact behavior here, but we didn't set any of them. Even worse …

Discard LSP requests/notifcation that target outdated versions

---

helix-lsp/src/snippet.rs
helix-parsec/src/lib.rs

There were multiple smaller bugs in the snippet parser.
This PR fixes them, I have included a more detailed explanation
in each commit.
Fixes #6288 and additional bugs mentioned in comments there and in #6293.
It turns out that #6293 was the correct fix. We can not allow an empty string in `text` on `zero_or_more`/`one_or_more` combinations because that would always cause an infinite loop (the parser would keep succeeding without advancing the input). Furthermore, it was correct that we were using a list here. That's how VSCode works and how other parts of the standard describe it too. I think the grammar is simply wrong here. I left a comment in the sourcecode explaining that.
However, #6288 should have never occurred even with that bug. The snippet parser should have reported an error …

Fix snippet parsing

---

runtime/themes/ayu_dark.toml
runtime/themes/ayu_light.toml
runtime/themes/ayu_mirage.toml

Based on vscode ayu badge.
Looks like no palette colors fit so I just put in the original color codes.
ayu_light
ayu_dark
ayu_mirage
vscode ayu_light
cc @enkodr

Update ayu theme for inlay-hint

---

runtime/themes/adwaita-dark.toml

The adwaita-dark theme has no distinction between active and inactive buffers on a bufferline. Add contrast to clarify differences.

theme: update adwaita-dark for bufferline

---

helix-term/src/ui/picker.rs
helix-tui/src/text.rs

Fixes #6254
This could be probably done in a less hacky way, but I didn't want to overcomplicate things.

Fix highlighting in picker with multiple columns

---

book/src/themes.md

This scope was added via https://github.com/helix-editor/helix/commit/bf5b9a9f354135933d7970863cf81e5a36585d03, but it was never documented.

Document `ui.highlight` theme key

---

runtime/themes/fleet_dark.toml

A few changes that does not comply with the original theme, but adjusts the theme to better fit the editor of choice.
* Statusline is now visible. This was an issue when using horizontal splits
* ui.virtual was adjusted to a much lighter color. This is an issue only because we are using the "reversed" modifier for the cursor, and thus this change is required to make the cursor visible again when moving through whitespace.  As a result, whitespace is now much more "in your face" when enabled. I consider this an okay price to pay. Feel free to disagree

fleet-dark improvements

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/smithy/highlights.scm
runtime/queries/smithy/injections.scm

Adds syntax highlighting support for https://smithy.io/2.0/index.html a meta-modeling language to describe APIs.
LSP: https://github.com/disneystreaming/smithy-language-server
Treesitter grammar: https://github.com/indoorvivants/tree-sitter-smithy

Add initial Smithy support

---

helix-term/src/ui/editor.rs

Similar to #6095
**Problem** currently during diagnostic rendering only the description is shown but the code is also useful when one wants to ignore that error report.
**After this pr** errors will be rendered as follows.
Now you know what code to use to ignore the error

Show diagnostic codes for LSP diagnostics

---

helix-lsp/src/snippet.rs

Closes #6347
Fixes a bunch of small bugs in the snippet parsing, mostly relating to escape sequences. The LSP standard is incomplete, ambigous/missleading and sometimes even downright wrong so I just used the vscode implementation as a reference. I have started porting a bunch of tests over from there to be sure we are doing the right thing now. However due to the sheer number of tests I stopped with that at some point to preserver my sanity.
The large number of inserted lines are just tests, the code changes itself are pretty minor.

Robust snippet parsing

---

languages.toml

*.xib and *.storyboard files are just xml files used for UI development on Apple platforms.
About [xib](http://www.monobjc.net/xib-file-format.html) and [storyboard](https://chris-mash.medium.com/the-anatomy-of-an-ios-storyboard-d473a4076b25).

Add xib and storyboard file types

---

languages.toml

Add "svg" as a file type for xml.
Fixes: https://github.com/helix-editor/helix/issues/6337

feat(languages): highlight .svg as xml

---

book/src/themes.md
runtime/queries/markdown/highlights.scm
runtime/themes/onelight.toml

- https://github.com/MDeiml/tree-sitter-markdown/blob/split_parser/tree-sitter-markdown/corpus/extension_task_list.txt
```markdown
```

Add theme keys for (un)checked markup list items

---

Cargo.lock
helix-vcs/Cargo.toml
helix-vcs/src/git.rs
helix-vcs/src/git/test.rs
helix-vcs/src/lib.rs

Issues with the diff gutter like #6358 are pretty hard to debug right now because there is essentially no logging of failures in the git integration (they all get turned into options). This PR makes the functions of the `DiffProvider` trait return a Result and log any failures.

log failures in the git integration

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/rego/highlights.scm
runtime/queries/rego/injections.scm

Tree-sitter grammar from https://github.com/FallenAngel97/tree-sitter-rego.
Queries from https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/rego/highlights.scm

Add language support for rego (OpenPolicyAgent)

---

helix-core/src/lib.rs
helix-core/src/position.rs
helix-core/src/text_annotations.rs
helix-term/src/commands.rs
helix-term/src/ui/document.rs
helix-term/src/ui/editor.rs
helix-view/src/view.rs

Extracted from #6417
Fixes #6397
This is a collection of bugfixes for oversights introduced in #5420 that I noticed while working on #6417. I backported these to a standalone PR, so they can merged independently of the larger changes in #6417. It's a bit of a kitchen sink PR in that these fixes are pretty independent of each other, but it didn't seem worth splitting each commit into seperate PR because they are mostly not large changes and didn't really contain any design decisions (just bugfixes) so it didn't seem like they would need separate discussion.
Each commit in this PR is a standalone bugfix mostly independent of the other fixes. As such I added a detailed description to each commit to describe what it's doing from a technical point of view. A short summery below
* ec37277, …

Fix minor oversights in positioning code

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/git-commit/textobjects.scm

The update includes a fix for comments in commit messages where there was no space separating the '#' and the comment text.
The comment textobject can be useful occasionally to jump to the summary part of the commit edit message.
See https://github.com/the-mikedavis/tree-sitter-git-commit/issues/7

Update tree-sitter-git-commit, add comment textobject

---

runtime/themes/catppuccin_mocha.toml

This PR update theme according to the latest changes in https://github.com/catppuccin/helix.git. But I also added some additional changes as like:
-  removing italic modifier from `markup.link.url`
- added fg for `keyword.storage.modifier.ref`

Update catppuccin theme

---

helix-tui/src/backend/crossterm.rs

If the terminal doesn't send the primary device attributes response to the query, the `terminal::supports_keyboard_enhancement` function from crossterm may timeout and return an Err.
We should interpret this error to mean that the terminal doesn't support the keyboard enhancement protocol rather than an error in claiming the terminal.
This was a bug introduced in the refactor in #6194

tui: Handle keyboard enhancement check failure

---

book/src/themes.md
helix-dap/src/client.rs
helix-term/src/ui/editor.rs
helix-view/src/editor.rs
helix-view/src/gutter.rs
runtime/themes/acme.toml
runtime/themes/autumn.toml
runtime/themes/ayu_dark.toml
runtime/themes/ayu_light.toml
runtime/themes/ayu_mirage.toml
runtime/themes/dracula.toml
runtime/themes/dracula_at_night.toml
runtime/themes/onedark.toml
runtime/themes/onedarker.toml
theme.toml

Add new theme highlight keys, for setting the colour of the breakpoint
character and the current line at which execution has been paused at.
The two new keys are `ui.highlight.frameline` and `ui.debug.breakpoint`.
Highlight according to those keys, both the line at which debugging
is paused at and the breakpoint indicator.
Add an indicator for the current line at which execution is paused
at, themed by the `ui.debug.active` theme scope. Update various themes
to showcase how the new functionality works.
Better icons are dependent on #2869, and as such will be handled in the
future, once it lands.
Closes: #5952
Signed-off-by: Filip Dutescu <filip.dutescu@gmail.com>

feat(debug): highlight current line

---

Cargo.lock
book/src/configuration.md
book/src/generated/typable-cmd.md
book/src/languages.md
helix-core/src/lib.rs
helix-core/src/syntax.rs
helix-loader/src/config.rs
helix-loader/src/lib.rs
helix-lsp/Cargo.toml
helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/commands/typed.rs
helix-term/src/config.rs
helix-term/src/keymap.rs
helix-term/src/main.rs
helix-term/tests/test/helpers.rs
helix-view/src/editor.rs

Supersedes #4439 and (mostly) #3207
Fixes: #3993
Fixes: #4436
fixes #5852
Closes #5919
The aim of this PR is primarily to address the problem from #4439 as described in https://github.com/helix-editor/helix/pull/4439#issuecomment-1345568363. As the solution described there uses a workspace config I ended up implementing support for that as well. The syntax I proposed in https://github.com/helix-editor/helix/pull/4439#issuecomment-1345568363 didn't quite work out as adding a new top-level header (that can be accessed in `helix-view`) like `[workspace]` would have required more changes that didn't seem worth the effort here. Furthermore, the language specialization I proposed in my comment is incompatible with the toml standard (sadly). I ended up with the following solution:
To force LSP …

LSP workspaces

---

runtime/queries/julia/injections.scm

Julia has support for Markdown strings, denoted by `md"foo"`.  This PR adds an injection for highlighting these as Markdown.

Add injection for Markdown strings in Julia

---

book/src/generated/lang-support.md
runtime/queries/julia/indents.scm

Automatic indentation for my favorite programming language, filling in one of the holes in the language support chart.

Add indents.scm for Julia

---

Cargo.lock
book/src/configuration.md
helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/commands/lsp.rs
helix-term/src/commands/typed.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/menu.rs
helix-term/src/ui/picker.rs
helix-term/src/ui/popup.rs
helix-tui/src/buffer.rs
helix-tui/src/widgets/table.rs
helix-vcs/Cargo.toml
helix-view/src/editor.rs

This PR is a kitchen sink for all outstanding bug fixes left on the milestone.
Closes #6482
Closes #6346 
Closes #3821
Closes #6467
Closes #6483
- Update dependencies
primarly gitoxide (plus cargo update) since depandabot missed it. Includes some fixes for bugs that affect helix on Windows (https://github.com/Byron/gitoxide/pull/800 in particular)
- add option to hide snippets (`editor.lsp.show-snippet-completions`)
- Truncate paths in the file picker (#6410)
- Performant and correct set_spans_truncated
fixes the issues with #6410 I found
- Correctly reload theme on :config-reload
small bug I found while testing this PR
- Hide signature help if it overlays completion menu (#5523)
Includes some style nits and conflict resolution
- Prefer utf-8 over utf-32, hopefully fixes #6483.
I can't …

Prepare for 23.3 release

---

flake.lock
flake.nix

Removes the usage of a deprecated nci option, also updated the flake dependencies as well.

build(nix): update flake dependencies, remove deprecated code from flake

---

.github/workflows/release.yml

Fixes #6495
See the dry-run https://github.com/helix-editor/helix/actions/runs/4576449372
This could be solved instead by using `rustup target add ${{ matrix.target }}` but that would be papering over the problem: we do install stable-aarch64-apple-darwin but that's for the wrong Rust version. `cargo` looks to use 1.65 because of the `rust-toolchain.toml` file but `dtolnay/rust-toolchain` installs it for stable which is 1.68.2 currently.

Fix aarch64 macos release builds

---

helix-lsp/src/client.rs
helix-lsp/src/lib.rs

Fixes #6505
We didn't normalize/canoncialize LSP workspace paths with can both lead to bugs in the workspace detection and leads to inconsistent paths being sent to the LS which might not handle this correctly.

normalize LSP workspaces

---

helix-lsp/src/lib.rs
helix-term/src/ui/completion.rs

Fix crashes with the TS language server reported on matrix
The Problem is that the way helix deals with invalid LSP ranges is different from other editors right now. Helix currently panics if the start of a LSP range is after the end of the range. The standard doesn't actually state that this is forbidden. VSCode simply sets `start=end` in that case and there seem to be a few servers relying on this sadly. I matched that behavior but logged an error to make sure this is not missed when tracking down issues. Alternatively we could discard such ranges. We definitely shouldn't panic tough.
Similarly, we now allow ranges with line numbers past the end (simply treated as EOF). VSCode behaves the same and so does neovim. I copied their comment here:
> If it extends past the end, truncate it to …

robustly handle invalid LSP ranges

---

helix-term/src/commands/typed.rs

This is just a minor PR to remove two `TODOs` by rewriting to `let..else`.

chore: `let..else` refactor to remove TODOs

---

runtime/themes/dracula.toml

This styles all inlay hints in the same color as comments. Additionally, types and parameters will be italic.
I haven't yet found any colors I really like for styling types and parameters differently, though I'm open to suggestions. 
For reference, this is what it looks like using the same colors as ordinary types and parameters, respectively, but with an additional dim modifier:

dracula theme: style inlay hints as comments

---

helix-term/src/commands/lsp.rs

Fix line number display for LSP goto pickers

---

languages.toml

R `--slave` option was replaced by `--no-echo` in 2019; update `languages.toml` to reflect this change.

minor: R lang config update --slave to --no-echo

---

runtime/themes/base16_transparent.toml
runtime/themes/dark_high_contrast.toml

Update base16_transparent and dark_high_contrast theme

Update base16_transparent and dark_high_contrast themes

---

runtime/themes/mellow.toml
runtime/themes/rasmus.toml

Changes:
- Update/Add inlay-hint color for `mellow` theme.
- Update/Add inlay-hint color for `rasmus` theme.

Update inlay-hint color for mellow & rasmus themes

---

runtime/themes/base16_transparent.toml

> Proposed change to [update panes separator color](https://github.com/helix-editor/helix/blob/23ed8c12f17c28ee888b5560d0ab2a9f9cd74dc9/runtime/themes/base16_transparent.toml#L12) in order to increse the focus on the actual code
current:
```toml
ui.window = { fg = "white" }
```
proposed: 
```toml
ui.window = { fg = "gray" }
```

Dim pane divider color in base16_transparent theme

---

languages.toml

Without this change, GDScript code doesn't get formatted.
You can install GDFormat like this:
```
pip install gdtoolkit
pip3 install gdtoolkit
```

Add support for formatting GDScript with GDFormat

---

Cargo.lock
Cargo.toml

We used a git dependency to take advantage of the latest fixes in master but a new release is now available: https://crates.io/crates/tree-sitter/0.20.10

Update tree-sitter to v0.20.10

---

runtime/themes/ferra.toml

This PR adds my theme `ferra`. It's a original theme I created a few years ago. A small description for the theme:
> Ferra is a visually appealing theme that is inspired by the vibrant colors of [Kanagawa](https://github.com/rebelot/kanagawa.nvim) and the warm tones of [Gruvbox](https://github.com/morhetz/gruvbox). This theme features a rich palette of earthy browns and greens, accented by subtle pops of blush, coral, and rose. The result is a harmonious blend of colors that is both inviting and easy on the eyes.
Running `cargo xtask themelint ferra` shows no current linting errors:
```sh
➜  helix git:(theme/ferra) ✗ cargo xtask themelint ferra
Finished dev [unoptimized + debuginfo] target(s) in 0.13s
Running `target/debug/xtask themelint ferra`
```
Let me know what you think, and let me …

Added `ferra` theme

---

languages.toml

xsd or "XML Schema Definition" files are in XML format and should therefore be highlighted as such

xml: highlight .xsd as XML files

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/robot/highlights.scm

Language server and tree-sitter support for Robot Framework files.
Highlight queries made by the author of the tree-sitter parser for Robot: https://github.com/robotframework/robotframework/issues/4495#issuecomment-1270691525

Add support for Robot Framework files

---

languages.toml
runtime/queries/gleam/highlights.scm

Adds support for the new `let assert ...` as only `assert ...` has been deprecated in gleam.

Update gleam grammar

---

runtime/themes/ayu_dark.toml
runtime/themes/ayu_light.toml
runtime/themes/ayu_mirage.toml

Fix ayu theme markup unreadable bg

---

book/src/install.md

Made Helix available within winget package manager see [pull request](https://github.com/microsoft/winget-pkgs/pull/101377) on the winget-pkgs repo.
Improved the Helix documentation for installing on windows.

Add Windows install instructions using Winget

---

book/src/configuration.md

discovered this while using the current release, if it has changed in master reject this.

Fix `file-picker.follow-symlinks` config option name in docs

---

helix-term/src/application.rs

Fixes #6687
Quick-fix is to propagate error replacing `.get_by_id(server_id).unwrap()` with `.get_by_id(server_id)?`. 
I've manually tested the fix. It works. Restarting LSP server after stopping it mid-flight works as expected.

LSP: Gracefully handle 'workspace/configuration' from a stopped server

---

helix-term/src/commands.rs
helix-view/src/editor.rs

Hopefully solves #6628.
Moved the code to a separate function as was recommended in the issue.

Fix crash on opening jumplist

---

runtime/themes/everforest_dark.toml
runtime/themes/everforest_light.toml

Adjust palettes and assignments:
- Color palettes of upstream everforest where tweaked since creation of this port:
- https://github.com/sainnhe/everforest/pull/108
- https://github.com/sainnhe/everforest/pull/109
- Move the helix everforest theme closer to the documented
upstream vim theme

Adjust everforest to resemble original more closely

---

runtime/queries/haskell/injections.scm

Similar to tagged templates in JS, quasiquoters allow to embed external languages in haskell, so it makes sense to treat them as an injection point.
I have been using it locally for a few weeks now.

tree-sitter(haskell): use quasiquoters as an injection point

---

runtime/themes/dracula.toml

I tried to make dracula scheme more comfortable.
normal color is now purple
insert cursor color is green now
and select is cyan now
selection colors are also changed
cursorline and statusline colors are lighter now
i changed some colors of variables, types and operators, so now they are nicer to the eyes, imho :)
diagnostic info color is cyan now
diagnostic warning is now yellow
there are also some changes that u can see in the commit info :)

Refactor dracula theme

---

helix-term/src/ui/prompt.rs

Theme preview doesn't return theme to normal when delete name with Alt-Backspace

Fix #6669: Theme preview doesn't return theme to normal

---

runtime/themes/darcula.toml

Currently affects `darcula` and `darcula-solid` themes.

Add inlay hints styling to darcula theme

---

helix-view/src/editor.rs

Fixes #6605
As described in https://github.com/helix-editor/helix/pull/6656#issuecomment-1500887367 the correct fix here was simply to default to `Some(false)` for the global config (instead of `None` which lead to the same behaviour but caused issues with `:toggle`) while continuing to default to `None` for the language config so that the fallback keeps working correctly.

ensure :toggle soft-wrap.enable works by default

---

runtime/queries/python/highlights.scm

- Fix: python query highlight now support single-character and alphanumeric constant identifier. 
Merging this PR would close #6730 issue.

Fix python constant identifier highlight

---

runtime/tutor

Hello! I noticed the tutor has a single reference to Visual mode in what I understand is Select mode. I imagine it can be easy for people coming from vim to mix the naming up, so I think it will be helpful to be consistent in the tutor.
Thanks!

Replace 'Visual' (mode) with 'Select' in tutor

---

helix-loader/build.rs
helix-loader/src/grammar.rs

While triaging issues I often noticed that the revision reported by `helix --version` if often wrong. I finally found the reason for this: The `build.rs` script that extracts the HEAD branch by calling `git` is not automatically rerun so if you build helix then checkout/merge a branch/revision that doesn't touch `helix-loader` (which doesn't see that much activity compared to the rest of the editor) and rebuild then build script will not be rerun and`helix --version` will report the old (incorrect) revision.
I made the build script emit an appropriate `cargo:rerun-if-changed=` so that it is rerun if `HEAD` changes to fix that.

emit cargo metadata duiring build scripts to avoid outdated buildscript outputs

---

runtime/queries/go/locals.scm

This pull request makes a tiny fix to the `var_spec` locals query for Go. The existing query makes use of the "name" field, but when there are multiple variables in the same declaration, only the first gets captured. It's fine for us to not specify the field, because if a type or a value is provided, any identifier nodes within them either have a different name such as type_identifier, or they're nested within a further sub-expression. Below are some screenshots showing the change, and the edge cases that I considered, which seem to be handled correctly with the updated query:
- before (`b` is not recognized as a local):
- after (`b` is recognized as a local):
- after, with a type identifier (`c` is not recognized as local):
- after, with assigned value identifiers (`c` is not recognized …

Fix go locals query for var_spec identifiers

---

runtime/themes/ferra.toml

Ferra's current ruler styling overrides the foreground style, which is an odd look only for characters in the ruler column. This commit removes the foreground styling for the ruler rule. This is more in line with what other themes do for the ruler.

ferra: fix ruler overriding foreground style

---

runtime/themes/kanagawa.toml

Makes the LSP hints more legible against the background colour and more in line with the normal colours in the theme.

Add `inlay-hint` colours to Kanagawa

---

helix-term/src/commands/typed.rs

I think some kind of feedback is useful for this command. I chose to set the status line with format `key = new_value`. For example, `:toggle lsp.enable` will set the status line to `lsp.enable = false` or `lsp.enable = true` after successfully applying updated config to the editor.

make :toggle-option print the new value

---

helix-term/src/application.rs

Fixes [#6725](https://github.com/helix-editor/helix/issues/6725)
This commit is copy/paste from same issue of neovim:
- [Issue](https://github.com/neovim/neovim/issues/12322)
- [Fixes](https://github.com/neovim/neovim/pull/13084/commits/2e70fee1e9da6ed044b207e9ec03bb5950846ef1)

Fix crash on opening from suspend state

---

helix-dap/src/client.rs
helix-dap/src/transport.rs
helix-view/src/handlers/dap.rs

Fix unwrap bug in DAP

---

Cargo.lock
helix-loader/Cargo.toml
helix-loader/src/grammar.rs

Closes #6788
Usually, modern compilers always default to c++ 14 or c++17 anyway. Clang defaults to c++14 and gcc to c++17. MSVC++ even dropped support for older standards in msvc17 (and defaults to c++14) However, it seems that apple-clang sometimes (but not always) defaults to c++98. By explicitly setting the argument we can work around such cases.
This also ensures more consistent builds across various systems (that may default to newer c++ standards in the future) and provides more easily understood error messages on ancient systems that don't support c++14 yet.

always build grammars with c++14 and c11

---

book/src/install.md

Before the release of 23.03.1, I wanted to address a few issues that have been bothering me and make some general improvements. 
Primarily, I corrected grammar and clarity issues, but I also added a new requirements section. Initially, we had agreed that this section was unnecessary as everyone knew that the Rust toolchain was mandatory. However, since a c++14 requirement was recently added, I included the Rust toolchain requirement in the new section as well. I think it is much better now as I also added the `If you are using the musl-libc...` section to the requirements up front, it made no sense to have it after you had tried to install Helix as it would have failed by then!
I think there was some debate about numbering `Clone the repository` and `compile from source`, but with the new …

Improve and update the installation documentation

---

helix-loader/src/grammar.rs

Fixes the issue described in https://github.com/helix-editor/helix/pull/6792#issuecomment-1512058559.
Currently, grammar builds fail without actually aborting the build (even tough that seems to be the intention since we explicitly call `except`) because we only print to stdout when the build fails but don't actually return an error. This makes diagnosing and fixing build failures harder. This PR fixes that by simply calling `bail!` instead of `println!`. As described here https://github.com/helix-editor/helix/pull/6792#issuecomment-1512080841 this slightly changes the formatting of the error message. I have therefore opted to remove the indentation from the failure message as that now looks a bit out of place

produce error when grammar build fails

---

helix-loader/src/grammar.rs

#6792 seems to have broken windows builds apparently `/std=c11` and `/std=c++14` can not be used together after all even tough it did sound like that in the documentation. I added the same workaround we already had for unix. I don't have a local windows environment setup and relied on CI for testing but that used a cached build, because the actual grammars didn't change. 
I had to clear windows CI caches for #6808 which meant that CI is now failing on master even tough it passed for all PRs.

fix windows build

---

helix-term/src/commands/lsp.rs

In #5986 the various LSP based goto commands were changed to select the entire symbol range instead of just placing the cursor at the symbol start to bring them in line with other pickers like diagnostics/symbol picker. However, in the symbol picker and the diagnostic picker the range sent by the LSP is flipped, so the cursor is placed at the start of the range (the start of the function instead of the end for example). This is very useful when jumping to the definition of large symbols like modules/classes or function.
This PR adjusts the LSP goto commands to match the other LSP pickers in this regard. This behavior is closer to the old behaviour (which paced the cursor at the start of the symbol too but just didn't add the remaining selection) and I therefore added it to the bugfix …

flip symbol range in LSP goto commands

---

languages.toml

`roots` doesn't support wildcards. As such this root is dropped, and `cabal.project` is added, which is probably the best we can do for Cabal-based projects for now.

Replace `*.cabal` in Haskell `roots` with `cabal.project`

---

runtime/themes/dracula.toml

I changed the colors according to the  official Dracula specifications and vscode theme and I hope u'll like it :)
As I said earlier, I'm open to any ideas :)

Another dracula refactoring

---

helix-term/src/application.rs
helix-tui/src/backend/crossterm.rs
helix-tui/src/backend/mod.rs
helix-tui/src/backend/test.rs
helix-tui/src/terminal.rs

This picks up changes to the `editor.mouse` option at runtime - either through `:set-option` or `:config-reload`. When the value changes, we tell the terminal to enable or disable mouse capture sequences.
Closes #6638
Closes #5648
Closes #5931

tui: Allow toggling mouse capture at runtime

---

helix-loader/src/grammar.rs

Closes #6844
CI doesn't seem super reliable because the caching strategy around grammars is a bit dodgy, so I fiddled around and after a while, I got `cargo-xwin` working locally and was able to debug the build failures. Could you confirm that this works for you @Chickenkeeper? I don't want to clear CI caches because that might make builds fail.

fix windows builds

---

helix-core/src/movement.rs

Change to use the result of move_vertically if soft wrap is disabled
In reading the helix code, I wondered if not using the result of move_vertically was not the intent.
If you do not need this change, please feel free to CLOSE it!

return early if soft wrap is disabled

---

helix-term/src/commands.rs

Add extend_to_first_nonwhitespace

---

runtime/queries/go/indents.scm

(see commit message)
Fixes #6772.

Avoid extra indentation on Go switches

---

languages.toml

fix(nix): fix superflous `/` that breaks the build

---

languages.toml

add go.work and remove Gopkg.toml as Go roots

---

book/src/generated/lang-support.md
languages.toml

This change adds the PerlNavigator Language Server as the default for perl files (https://github.com/bscan/PerlNavigator)

Set PerlNavigator as the language server for Perl

---

helix-term/src/commands/lsp.rs

Fixes the crash from this comment https://github.com/helix-editor/helix/issues/6752#issuecomment-1517580073
Note that this crash is not the same crash that #6752 is about and was incorrectly reported there. The problem here is simply that `view.offset.anchor` was used directly with `char_to_line`, but the anchor can be out of bounds which causes a crash here. Everywhere else where the anchor is used we currently used `anchor.min(doc.len_char())` for that reason. This PR just adds that to the inlay hint computation too since we forgot about it there.

fix panic in inlay hint computation when view anchor is out of bounds

---

runtime/queries/rust/injections.scm

I noticed these two were missing, so I figured we should add them for completeness.

Highlight sqlx's `query_scalar{,_unchecked}` macros as SQL

---

Cargo.lock
helix-vcs/Cargo.toml
helix-vcs/src/git.rs

This PR *should* fix #6867, and supersedes #6882.

upgrade gitoxide to v0.44 and change repository discovery to worktree-only (#6867)

---

book/src/configuration.md
helix-lsp/src/client.rs
helix-term/src/commands/lsp.rs
helix-view/src/editor.rs

feat: add a config option to exclude declaration from LSP references

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/odin/highlights.scm
runtime/queries/odin/indents.scm

The previously adopted grammar, `MineBill/tree-sitter-odin`, is unmaintained and mentions my repository as an alternative source.

Change Odin grammar to `ap29600/tree-sitter-odin`

---

book/src/generated/typable-cmd.md
helix-core/src/register.rs
helix-term/src/commands/typed.rs

Closes #4256. This is a rework of closed https://github.com/helix-editor/helix/pull/4408. Summary of discussion from there:
* clear registers by pressing `"` and then the key to clear the registers
* the key to clear the registers is suggested to be `|`

feat(commands): add clear_registers command

---

book/src/SUMMARY.md
book/src/guides/injection.md
helix-core/src/syntax.rs
helix-term/src/ui/markdown.rs
languages.toml
runtime/queries/markdown/injections.scm
runtime/queries/nix/highlights.scm
runtime/queries/nix/injections.scm

Nodes can now be captured with "injection.filename". If this capture contains a valid file extension known to Helix, then the content will be highlighted as that language. In addition, a new "injection.shebang" is added which injects based on a valid shebang.
For consistency, both implementations use the same logic as used to detect the document filetype as a whole.
~~I'm not sure if the following is the most efficient way to capture the built in configuration, or if it can be passed in from somewhere else:
https://github.com/nrdxp/helix/blob/7f61de137f07cf5897d5a3240b1ece98febc0eb0/helix-core/src/syntax.rs#L1836~~
~~Also, it would probably be nice to extend this to user defined languages as well.~~ 65bc9da1f4b0b67dc3189c4a21e5cd551a733b07
Also includes an additional query for Nix so one …

inject language based on file extension & shebang

---

helix-term/src/commands.rs
helix-view/src/document.rs
helix-view/src/editor.rs

Hi!
This is naive implementation of most-recent-used buffers picker.
As vim user in past this feature is very needs for me )
Sorry for my poor English.

Sort the buffer picker by most recent access

---

runtime/tutor

`"/y` Represents a key sequence to press, if you add space between, it can be misinterpreted, in which case literally pressing `"/<space>y` will not do what it is supposed.

tutor: Delete space between shorthand

---

helix-term/src/commands.rs
helix-term/tests/test/commands/write.rs
helix-view/src/document.rs
helix-view/src/editor.rs

Create an enum EncodingBom in `helix-view/src/document.rs` that represent the Document encoding with BOM information.
Previous behaviour:
```bash
$ printf '\xEF\xBB\xBFtest\n' > utf8
$ file utf8
utf8: Unicode text, UTF-8 (with BOM) text
$ hx utf8    # Only type ':x' inside helix
$ file utf8
utf8: ASCII text
```
New behaviour:
```bash
$ printf '\xEF\xBB\xBFtest\n' > utf8
$ file utf8
utf8: Unicode text, UTF-8 (with BOM) text
$ hx utf8    # Only type ':x' inside helix
$ file utf8
utf8: Unicode text, UTF-8 (with BOM) text
```
This close #6246.
I'm still new to Rust, so feedback to improve this pull request is appreciated.
After some work, I removed the enum EncodingBom and replaced it by a boolean value, as per the feedback from @archseer.
I added some more commits on top of it to support …

UTF Conserve BOM bytes and properly support UTF16

---

helix-lsp/src/client.rs

Fixes https://github.com/rust-lang/rust-analyzer/issues/14679
In https://github.com/helix-editor/helix/pull/5894 I overlooked that the incremental sync code manually transcodes char positions to utf16 line/column offset. This could cause server crashes for LSP servers that support utf8 or utf32 when editing on the same line after a non-ascii character.
This issue has been noticed by quite a few people both on matrix and in various github comments (for example https://github.com/helix-editor/helix/pull/6594#issuecomment-1519028627) altough we don't have an issue for it in our repo

fix didChange notification offset encoding

---

languages.toml

Gradle scripts written in kotlin use a .kts extension:
https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:scripts

languages: add build.gradle.kts to java and scala roots

---

book/src/keymap.md

This fixes a broken anchor tag in the Keymap page's table of contents.

Fix keymap select / extend mode anchor link

---

languages.toml

`.sty` files are LaTeX packages, and `.cls` files are LaTeX class files.

Treat .sty and .cls files as latex

---

helix-view/src/document.rs

Fixes #5229
had to google to workout how to save with parents (and found that issue) so thought it would be worth fixing it for others

Add better error message for file save failure due to parent not existing

---

helix-core/src/surround.rs
helix-core/src/syntax.rs
helix-loader/src/lib.rs
helix-term/src/ui/editor.rs
helix-tui/src/buffer.rs
helix-view/src/clipboard.rs
helix-view/src/editor.rs
helix-view/src/tree.rs

I found clippy complained a lot and thus fix them.
<details>                                                                                                                                                                                         <summary>cargo clippy --workspace --all-targets</summary> …

Fix warnings from clippy

---

languages.toml
runtime/queries/dockerfile/highlights.scm

fix: update upstream tree-sitter-dockerfile

---

helix-term/src/commands.rs
helix-term/src/commands/dap.rs

Steps to reproduce original issue:
- Add breakpoint
- Start debugging
- Program stops at breakpoint
- List variables
- Step to next
- List variables again
Before:

Replace DAP vars popup, instead of adding new

---

helix-term/src/commands.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/editor.rs
helix-view/src/document.rs
helix-view/src/editor.rs

Alternative to #6511
Closes #6259
Closes #6261
Fixes a similar bug with the typescript LSP reported on matrix where imports would be duplicated. 
This PR resolved the same issue as #6511 but keeps the current behavior of previewing the current completion. This is achieved by generating "ghost" transactions. Ghost transactions are normal transactions that are never sent to the LS.
Maintaining such transactions is tricky/dangerous because we always need to undo them (with the undo transaction also not sent to the LS) before we apply any other transaction to the document. Otherwise, we would send invalid changes to LS with incremental sync and therefore break the server (until `:lsp-restart`).
To that end I used the more generic savepoints introduced in #6173. The completion menu now saves a …

correctly handle completion rerequest

---

helix-core/src/lib.rs
helix-core/src/transaction.rs
helix-term/src/commands.rs
helix-term/tests/test/commands.rs

Fixes #6021
Fixes https://github.com/helix-editor/helix/issues/5272
Fixes https://github.com/helix-editor/helix/issues/6029
The `delete_char_backward` command delete indentation when at the start of the line. The problem is that this can cause multiple overlaing deletions with multiple cursors. For example in #6021 one of the cursors is after the 3. space and one after the 1. char. Because the indent unit is 4 spaces `delete_char_backward` deletes to the start of the line for both cursors. The generated transaction is therefore invalid which causes an integer underflow when the transaction is applied.
I fixed a similar crash in #5728. Mutlicursors potentially generating overlapping changes is a common pitfall and something we should be wary of. In that PR I simply discarded changes that …

Fix crash when deleting with multiple cursors

---

helix-core/src/syntax.rs
helix-core/tests/indent.rs
helix-term/src/ui/markdown.rs
helix-term/src/ui/picker.rs
helix-view/src/document.rs

Fixes #6697
Closes #338
This PR addresses TS syntax highlighting freezing the UI loop in two separate ways:
* It uses the parser timeout mechanism in TS to limit all TS parsing to 500ms. If parsing exceeds 500ms, its canceled and TS is automatically disabled for that buffer. This is preferable to a fixed size limit (as suggested in #338) as it takes different CPU speeds/grammar speeds into account (and future optimizations in the parser/TS). If parsing takes longer than 500ms the editor always feels laggy.
* In the picker syntax highlighting is now performed in a background thread to avoid micro stutters in the UI (if trying to move after a short a delay)

Fix TS freezing the editor

---

helix-term/src/commands/typed.rs

It solves #5779
Before:
After:
P.S. I fixed this by getting word_len for a range replacement from the actual word being displayed (instead of initial representation of a path from autocomp), hope that was an initial idea here.

Fix completion on paths containing spaces

---

book/src/generated/typable-cmd.md
book/src/guides/adding_languages.md
book/src/languages.md
helix-core/src/diagnostic.rs
helix-core/src/syntax.rs
helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-lsp/src/transport.rs
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/commands/lsp.rs
helix-term/src/commands/typed.rs
helix-term/src/health.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/statusline.rs
helix-view/src/document.rs
helix-view/src/editor.rs
helix-view/src/gutter.rs
languages.toml
xtask/src/docgen.rs

Adds support for multiple language servers per language.
Language Servers are now configured in a separate table in `languages.toml`:
```toml
[langauge-server.mylang-lsp]
command = "mylang-lsp"
args = ["--stdio"]
config = { provideFormatter = true }
[language-server.efm-lsp-prettier]
command = "efm-langserver"
[language-server.efm-lsp-prettier.config]
documentFormatting = true
languages = { typescript = [ { formatCommand ="prettier --stdin-filepath ${INPUT}", formatStdin = true } ] }
```
The language server for a language is configured like this (`typescript-language-server` is configured by default):
```toml
[[language]]
name = "typescript"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "typescript-language-server" ]
```
or equivalent:
```toml …
```

Add support for multiple language servers per language

---

flake.nix

This just adds an overlay to the nix flake to make it convenient to use helix.
It's not a big change. I'm adding it since a feature I really want to try was merged yesterday (multiple lsps).
@yusdacra @archseer when you have a moment.
closes #7042

nix: add overlay for convenient package usage

---

languages.toml

Characters should maximally reside *inside* the ruler, not on top of it.
At least, that's my personal taste. Maybe the existing behavior is intentional?

fix off-by-one git-commit rulers

---

book/src/keymap.md
helix-core/src/selection.rs
helix-term/src/commands.rs
helix-term/src/keymap/default.rs

Situations may arise in which you want to extend your selection up to a search result, or simply select everything between two or more cursors.
Currently there is no mechanism for this other than badly abusing `goto_last_modification` as a poor man's mark.[^1]
`merge_selections` combines all current ranges into a single range spanning from the first selection in the buffer to the last.
Now you can search in visual mode for the token you want to select up to, then hit `Alt-minus` (since `Alt-_` could already merge consecutive selections).
[helix_merge_ranges_macro_demo](https://github.com/helix-editor/helix/assets/18398499/728e9fad-2a8a-43b8-8d4f-46f1bf13df28)
[^1]: [How to select "until next occurrence"? - Reddit](https://www.reddit.com/r/HelixEditor/comments/13i527h/how_to_select_until_ne …

Add command to merge non-consecutive ranges

---

book/src/languages.md

Aligns docs with https://github.com/helix-editor/helix/pull/2507/files#diff-e78218ec4fe8cd27d4141d6d1077b4e929f734f03e97dcadfcc82f03d9ed661cL88-L90 
Fixes #7081

fix(docs): Remove `config` from language configuration docs

---

languages.toml

XAML files are types of XML files that are used quite a bit in UI development, so it would be handy to recognise them.

Recognise XAML files as XML

---

helix-term/src/application.rs
helix-term/src/ui/statusline.rs

LSPs can produce diagnostics for unopened documents, which previously made Helix increase the
workspace diagnostic count increase on each LSP restart.
There was also a bug in that if a document had diagnostics from two LSPs and one was exited, all
the diagnostics for all LSPs were cleared in `editor.diagnostics`, this has now been fixed.
Initially I was troubleshooting the ever increasing workspace count, that's why my first commit is a
small fix to the workspace diagnostics rendering code

Update diagnostics correctly on LSP exit

---

helix-term/src/commands/lsp.rs

This merge request fixes an off-by-one error in `select_references_to_symbol_under_cursor`.
When finding the range which contains the head of the current primary selection (so that this range will be the new primary selection), using the `head` field of the primary selection leads to the correct range being missed when `head > anchor` and the cursor is on the final character of the range, since `Range::contains`'s `pos` parameter seems to refer to the position of a character since it is non-inclusive. Using the `cursor` method fixes this since it returns the position of the character under the cursor.

Fix off-by-one in select symbol references

---

languages.toml
runtime/queries/nickel/highlights.scm
runtime/queries/nickel/indents.scm
runtime/queries/nickel/injections.scm

Update the revision of `tree-sitter-nickel` and copy over the highlighting queries. Also, adjust the `auto-pairs` configuration, since `'` isn't a paired delimiter in Nickel.

Update languages.toml for Nickel

---

languages.toml

`Vagrantfile`s are configuration files for the [vagrant](https://www.vagrantup.com/) tool, and they are written in Ruby. Even as vagrant [is ported to Go](https://www.hashicorp.com/blog/toward-vagrant-3-0), `Vagrantfile`s [will be written in Ruby](https://developer.hashicorp.com/vagrant/docs/experimental/vagrant_go)
When a Vangrantfile is created, it starts with these lines:
```
```
But since Helix (quite reasonably) doesn't change editor behavior based on file contents, adding this to `languages.toml` seems like a reasonable way to get this functionality.

Treat 'Vagrantfile' files as Ruby code

---

languages.toml

Also removed `just` from the file types list as `just` does not recognize that. https://github.com/casey/just#quick-start, the 5th non-code paragraph

Recognize hidden justfiles

---

runtime/themes/ferra.toml

This is just a tiny update for the selection color in Ferra theme.  
Currently the selection color is hard to read:
This has now been updated to the below image:

Fix: better selection color in Ferra

---

runtime/themes/spacebones_light.toml

Observe 'close' and 'open' members w.r.t type variable 'self'
Before:
After:

spacebones: Improve contrast between type variable and its members

---

book/src/install.md

This is really the most simple way, and helix is well maintained in nixpkgs.
The flake solution is overly complicated for newcomers to NixOS, as I just
witnessed on our support room. Copying/adapting/understanding that
expression is far easier.

book: Install helix declaratively from nixpkgs on NixOS

---

runtime/queries/java/highlights.scm
runtime/queries/typescript/highlights.scm

Java highlights were completely missing punctuation and operator highlights. This PR adds them based on the JSE 20 language spec. Changes include:
- Add punctuation according to the [spec](https://docs.oracle.com/javase/specs/jls/se20/html/jls-3.html#jls-3.12) (see "3.11. Separators"). I defined `@` and `...` as special punctuation because those are somewhat different to the regular punctuation symbols.
- Add operators according to the [spec](https://docs.oracle.com/javase/specs/jls/se20/html/jls-3.html#jls-3.12) (see "3.12. Operators").
- Highlight the wildcard type argument `?` as a type instead of as an operator, in the context of type arguments, according to the [spec](https://docs.oracle.com/javase/specs/jls/se20/html/jls-4.html#d5e3254) (see "4.5.1. Type Arguments of Parameterized …

Highlight query improvements for java and typescript

---

languages.toml

This adds a support for highlighting the configuration file for https://github.com/zimfw/zimfw

languages: add .zimrc to bash filetypes

---

languages.toml

GIR is a file format used by [GObject Introspection][1] to store machine-readable API metadata of GObject libraries.
Example: [`GObject-2.0.gir`](https://github.com/gtk-rs/gir-files/blob/43cac7495ff5daa303fcd5e360644a3b0a4cd4c3/GObject-2.0.gir)
[1]: https://gi.readthedocs.io/

Recognise `.gir` as XML

---

languages.toml
runtime/queries/scala/locals.scm

Update to a new Scala tree-sitter grammar revision, because the current one lags behind by quite a bit:
https://github.com/tree-sitter/tree-sitter-scala/commits/master

chore: update scala tree-sitter grammar

---

book/src/themes.md

Add a description for 'ui.text.foucs' saying that it styles the selected line in the picker, which is quite a prominent styling element I would say.
Took me some time to figure out which key it was since I couldn't find it in the docs.

Add description for 'ui.text.focus' in theme.md

---

helix-vcs/src/diff/line_cache.rs

Fixes UB in the diff gutters that lead to crashes in rust 1.71.
See https://github.com/rust-lang/rust/issues/112171#issuecomment-1575573079
Note that this is a temporary fix that I will revert once I land the improvements described in the comment land in ropey. That could take a while tough, and we really don't want UB in the meantime.

fix UB in diff gutter

---

book/src/usage.md

the key/textobject table is out of date, e.g. says `c` for Class (doesn't work), should say `t` for Type (or Class) (works)

Fix textobject keybindings in usage docs

---

book/src/install.md

Fixes `ln` command line bug that could hit users moving from packaged to source builds.

Update install.md instructions regarding symlinks

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/blueprint/highlights.scm

- Add blueprint tree-sitter queries

Add blueprint language

---

helix-core/src/match_brackets.rs
helix-term/src/commands.rs

This patch introduces bracket matching independent of tree-sitter grammar. This matching is introduced as a fallback in cases where the tree-sitter matcher does not match any bracket. The fallback should provide a better experience in cases like the ones reported in #3614
Relates to #3584 as well

feat(core): add plaintext matching fallback to tree-sitter matching

---

helix-core/src/syntax.rs
helix-view/src/document.rs

Closes #7094. I think it is weird to set tab width to zero, so I added a custom deserialization function (a small wrapper that checks if the tab width value is zero).

Add check for a non-zero value for tab width

---

helix-term/src/commands.rs
helix-term/src/ui/editor.rs

Previously the register selection (via `"`) would be lost in the middle of any key sequence longer than one key. For example, `<space>f` would clear the register selection after the `<space>` making it inaccessible for the `file_picker` command.
This behavior does not currently have any effect in the default keymap but might affect custom keymaps. This change aligns the behavior of the register with count. Making this change allows propagating the register to the `command_palette` (see the child commit) or other pickers should we decide to use registers in those in the future. (Interactive global search for example.)

Persist register selection in pending keymaps

---

book/src/configuration.md

Also, reduce overlong sentence, which also improves readability

Break long sentence in book configuration footnote

---

helix-core/src/movement.rs
helix-term/src/commands.rs

Fixes #6904
Adds the `move_prev_long_word_end` and `extend_prev_long_word_end` commands.
Tests are adapted from `test_behaviour_when_moving_to_start_of_previous_long_words` of the `move_prev_long_word_start` command, please double check if these are correct.
Here's a quick config to test the new commands with the keybinding `A-W`, together with `A-w` for the already existing but by default unbound `move_prev_word_end`.
```toml
[keys.normal]
A-w = "move_prev_word_end"
A-W = "move_prev_long_word_end"
[keys.select]
A-w = "extend_prev_word_end"
A-W = "extend_prev_long_word_end"
```

add move_prev_long_word_end and extend_prev_long_word_end commands

---

helix-term/src/commands/lsp.rs

The behavior prior to this commit opened the picker and then showed the error. We can check the feature availability before performing the first query to prevent opening up the picker unnecessarily.

Bail if no language servers support workspace symbols

---

helix-tui/src/widgets/table.rs

This is a fix for a subtle bug in the styling of cells in a table: only the last Cell in the selected Row will display fuzzy-matching highlights.
The simplest way to reproduce the bug is to open up the buffer picker. Inputting a buffer ID number or a flag which is present like * should highlight matched characters with your theme's 'ui.text.focus' scope, but the styles are not applied.
The issue is that the block moved in this commit was called per-cell but operates on the whole row's area, so the call in the last cell would overwrite all prior cells. The block must be moved outside the for-loop over the cells.
|---|---|
| ![before](https://github.com/helix-editor/helix/assets/21230295/0c2e639f-7d0b-43b4-83d4-7122e078a1c8) | …

Fix style overwriting in table rows with multiple cells

---

helix-term/src/commands.rs
helix-term/tests/test/commands.rs

First attempt at #4859. This makes `I` and `A` automatically indent, but **only** if the line is empty. Otherwise it behaves exactly as before. I thought about also handling indentation when the line only contains white space, but I left this out for now. Either way, this is a breaking change.
I roughly followed the implementation of `open_above`/`open_below`. Though, I'm not sure if the implementation is very good, all the text editing functions in the code base are new to me.
Here's the result of `insert_at_line_start` / `I` with this change (the only difference is on the empty line):
| before | master | this PR |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/3957610/216818723-ad0aaaaa-2e30-4e54-9175-3696f2d9c996.png) | …

Auto indent on `insert_at_line_start`

---

book/src/configuration.md
helix-term/src/ui/statusline.rs
helix-view/src/editor.rs

Resolves issue #1585 by adding a status message when a register is selected with the `select_register` command, similar to the message produced when starting to record a macro. Additionally, an indicator appears on the right with the selected register.

Add register statusline element

---

book/src/configuration.md
helix-term/src/ui/completion.rs
helix-view/src/editor.rs

This PR adds the config option `preview_completion_insert` which controls the insertion behavior of autocompletion.
Currently, Helix inserts the selected completion entry instantly into the document (reversible with c-c), this behavior is a personal preference though and should be configurable, as I prefer it to only insert on confirmation.
The new option defaults to true, thus the default behavior is not changed.

Add config option for instant completion entry preview.

---

runtime/queries/fortran/injections.scm

Enables highlighting of notes like `@todo`, `@note`, `TODO`, `NOTE` in Fortran comments.

Add Fortran comment injections

---

book/src/generated/lang-support.md
languages.toml

To support newer Vue features introduced with Vue 3 the existing Vue
language server has been replaced.
Closes #2194
Update wiki after merging, need to install `@vue/language-server`: https://www.npmjs.com/package/@vue/language-server

Use Vue language server based on Volar

---

Cargo.lock
helix-loader/Cargo.toml
helix-loader/src/grammar.rs

Previously the error message for this potential failure-case was confusing: "no such file or directory". `hx -g fetch`, `hx -g build` and the helix-term builder should bail early if the git binary is not available.

Check for 'git' before fetching/building grammars

---

helix-term/src/ui/editor.rs

While rewriting #2608 I have had a panic, when repeating a completion edit at the beginning of a buffer, with a negative start range, this should fix the issue...

Fix underflow when repeating a completion that has a negative shift position

---

helix-term/src/commands.rs

This fills a gap in the commands - you can rotate selections backwards and forwards, but to the best of my knowledge you can't *reverse* the order of the selection contents.
I don't really like the name of the command, what would be better?

Add reverse_selection_contents

---

helix-core/src/movement.rs

Fixes #7223 
Before there where different results going to next or previous due to sorting not dealing with multiple captures that start/end at the same pos. I chose to prefer longer matches.

Fix next/prev tree-sitter inconsistency

---

helix-term/src/commands.rs

Fixes #7330.
There seems to be a fair bit of code duplication between `buffer_picker` and `jumplist_picker` which should maybe be factored out in the future...

Preview scratch buffers in jumplist picker

---

book/src/keymap.md

I was struggling to find the hotkey for entering select mode by search, and noticed that the other modes had a leading paragraph after their headings with how to enter them. I added the same for Select and Insert mode.

Explain how to enter Select mode in keymap

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/webc/highlights.scm
runtime/queries/webc/injections.scm

Add [webc](https://github.com/11ty/webc) grammar.

Webc language support

---

book/src/configuration.md
helix-core/src/lib.rs
helix-core/src/line_ending.rs
helix-term/tests/test/auto_pairs.rs
helix-term/tests/test/helpers.rs
helix-view/src/document.rs
helix-view/src/editor.rs

I've finally gotten around to giving this a shot.
This adds a key to the editor config that allows specifying the default line ending for new documents. I added variants for `native`, `lf`, `crlf`, `ff`, `cr` or `nel`. `native` uses the platform's native line ending (`crlf` on Windows, otherwise `lf`). The default is `native`, so the out-of-the-box behavior remains unchanged.
One thing I noticed is that the enum naming is a little odd - `Crlf` vs. `LF`. But I kept the existing variant names.
closes #4378

Add config for default line ending

---

book/src/generated/typable-cmd.md
helix-term/src/commands.rs
helix-term/src/commands/typed.rs

Resolves issue #6888 by adding a command to join all selections and yank them to the specified register. The typed command takes an argument as the separator to use when joining the selections.
This command works the same as `yank_joined_to_clipboard` except that it yanks to a register.

Add yank_joined command

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/forth/highlights.scm

Correctly identifies all non-whitespace identifiers as words, added numbers with various formats and in general a much more solid experience.

Add forth-lsp and update tree-sitter-forth

---

helix-view/src/document.rs

Read the the `default_line_ending` setting from the config in the places where `NATIVE_LINE_ENDING` was still used.
fixes #7356

Use default line ending in open command

---

helix-view/src/theme.rs

My current vim theme doesn't use rgb colors but instead uses the ANSI color (150, 174, etc). 
Is this something Helix want to be able to do? It seems it already supports some colors (black, etc) but not all the ANSI colors.

Allow ANSI colors in themes

---

helix-term/src/commands.rs
helix-term/src/commands/dap.rs
helix-term/src/commands/lsp.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/picker.rs

This reduces a lot of duplicated code between the Picker and FilePicker which will pave the way for larger changes to Picker necessary for https://github.com/helix-editor/helix/pull/4687.
This is sudormrfbin's lovely work from https://github.com/helix-editor/helix/pull/5801 merged with master and with the outstanding review feedback addressed.
Closes #5801

Merge FilePicker into Picker

---

helix-term/src/ui/picker.rs

The handle_event, required_size, and cursor functions were mistakenly moved into the `impl Picker` rather than the `impl Component for Picker` block when merging the Picker and FilePicker (whoops! 😅), causing bugs like the picker ignoring all input and not rendering the cursor position correctly.
Closes #7379

Fix Component implementations for Picker

---

helix-core/src/match_brackets.rs
helix-term/src/commands.rs
helix-term/src/ui/editor.rs

Closes #3357
Closes #5177
These issues where caused by us requiring pairs to form a standalone TS node. This change looks at the sibling nodes (so still within the same node) to also find pairs formed by siblings. Syntax trees are usually much wider than deep, so I introduced a fairy aggressive limit on the number of examined nodes. Usually pairs form immediate siblings and looking at additional siblings is just done to handle weird grammars (and comments). The limit does lead to missing some matches but those cases are so rare that it's worth the improved performance IMO.

match pairs which don't form a standalone TS node

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/matlab/context.scm
runtime/queries/matlab/folds.scm
runtime/queries/matlab/highlights.scm
runtime/queries/matlab/indents.scm
runtime/queries/matlab/injections.scm
runtime/queries/matlab/locals.scm
runtime/queries/matlab/textobjects.scm

Product of #7386.
I believe I got the highlight right, or at least now I get a nice rainbow-vomit when using the `doom_acario_dark` theme. And no more quirks.
Textobjects and indents were tested and are inline with what I found in other grammars. That is to say "could you please take a look at the indents because I think it is broken, but it is defined the same as other languages so I don't know if it's broken or if it's just me who doesn't know how this editor works".
I simply copied the other queries and did not adapt them or anything. I not even know if helix supports them.

Switch MATLAB tree-sitter parser

---

helix-core/src/indent.rs

Previously, helix only allowed indent sizes up to 8. This commit changes to allow any indent sizes that fit within a u8.
This pr is motivated by a hackernews user with a ~deranged~ normal desire to have a 12 space indent.
See request here: https://news.ycombinator.com/item?id=36429221
Code motivated by suggestions here: https://news.ycombinator.com/item?id=36432996
I used a single line of 256 spaces because it's super simple and easy to validate rather than using an additional dependency like const_format or writing a macro myself.

Allow any indent size from 1 to 16

---

languages.toml

Updates the referenced commit. No changes to the queries are necessary.
Fixes a bug where `{'a' 'a'}` was not correctly parsed.

highlight(matlab): Bumps tree-sitter-matlab commit.

---

runtime/queries/toml/highlights.scm

This highlights toml `[table]` headers differently, which matches GitHub (via [linguist](https://github.com/github-linguist/linguist)) and [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/toml/highlights.scm) (although this implementation overlooks some combinations of quoted and dotted keys).
Before |  After
:------:|:------:
And for reference:
<details><summary>GitHub markdown</summary>
<p>
```toml
title = "TOML Example"
[table]
name = "Tom Preston-Werner"
["table"."dotted"]
enabled = true
ports = [8000, 8001, 8002]
dotted.key = { cpu = 79.5, case = 72.0 }
"quoted.key" = [["delta", "phi"], [3.14]]
[[table.dotted.array]]
ip = "10.0.0.1"
role = "frontend"
[bare]
[dot.ted]
["quoted"]
[[bare]]
[[dot.ted]]
[["quoted"]]
```
</p>
</details>

feat(toml): highlight table headers

---

helix-view/src/document.rs
helix-view/src/editor.rs

This resolves some confusing behavior where a scratch document created by piping into hx is discarded when navigating away from that document.
We discard any scratch documents that are not modified and the original `Editor::new_file_from_stdin` would create unmodified documents. We refactor this function to create an empty document first and then to apply the text from stdin as a change.
This comes out of the discussion in #3306
Closes #3306 
Closes #3305

Mark buffers created from stdin as modified

---

helix-core/src/transaction.rs
helix-view/src/document.rs

Fixes #7468
Fixes #7470
#7408 caused cashes because it assumed that all positions that are mapped with `update_position` are sorted. This is almost always the case. Except for the **end** of diagnostics. Diagnostics are sorted by their start position (and only if start positions are equal by end position). That caused various crashes. This is not a problem for selections since they are non-overlapping so ends re always sorted. 
This PR addresses that by allowing `update_positions` to backtrack in case if encounters an unsorted position. That does mean that the position mapping isn't quite linear anymore for diagnostics ends. However, this shouldn't really be an issue in practice as most diagnostics don't overlap, so the performance impact should be quite small in practice.

correctly map unsorted positions

---

helix-term/src/application.rs

The spec explicitly disallows publishDiagnostic to be sent before the initialize response:
> ... the server is not allowed to send any requests or notifications to the client until it has responded with an InitializeResult ...
(https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize)
But if a non-compliant server sends this we currently panic because we '.expect()' the server capabilities to be known to fetch the position encoding. Instead of panicking we can discard the notification and log the non-compliant behavior.
See #7466

LSP: Discard publishDiagnostic from uninitialized servers

---

helix-term/src/application.rs

Previously this was hard-coded to UTF-8 but we might have negotiated another position encoding.

LSP: Use negotiated position encoding for workspace edits

---

helix-lsp/src/transport.rs

The LSP spec has this to say about initialize:
> The initialize request is sent as the first request from the client to the server. If the server receives a request or notification before the initialize request it should act as follows: ...
> Notifications should be dropped, except for the exit notification. This will allow the exit of a server without an initialize request.
> Until the server has responded to the `initialize` request with an `InitializeResult`, the client must not send any additional requests or notifications to the server.
(https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize)
The spec is not really explicit about how to handle this scenario. Before a client sends the 'initialize' request we are allowed to send an 'exit' …

LSP: Forcefully shutdown uninitialized servers

---

languages.toml

The .cppm extension is used for C++2x modules

Add .cppm file type to cpp language configuration

---

runtime/queries/matlab/highlights.scm

There are two small changes in the commit:
1. Fixes a priority error that makes single quotes highlight as operators even when delimiting strings (it should highlight as an operator only when it is used as the transpose operator).
2. Makes the sign in numbers like `-1` and `+2` have the same highlight as the numbers instead of highlighting as an operator. If you don't like this one I can remove it, no problem.

highlight(matlab): Fix string's single-quote's color

---

book/src/install.md

After the https://archlinux.org/news/git-migration-completed/

book: Rename Arch Linux's repository from `community` to `extra`

---

helix-view/src/editor.rs

`"spacer"` was listed twice in the `editors.gutter` example and the error message for the gutter config parsing was missing newer options.

Fix incorrect gutter bail message

---

helix-term/src/application.rs
helix-view/src/editor.rs

See https://github.com/helix-editor/helix/pull/7373#issuecomment-1616716678 for prior discussion
Fixes helix not redrawing after receiving messages from the LSP by replacing the existing (buggy) special-purpose deboucing with using the redraw handle that was added as part of #3890

use redraw handle for debouncing LSP messages

---

helix-term/src/commands.rs

Fixes #6717 
Added a completer for shell command using `!`, so we can have the same experience as `run-shell-command` where we complete using the filenames available.
https://github.com/helix-editor/helix/assets/13922607/c3cc3006-9a9e-4aaf-9de3-3bbeddccf387

Add filename completer for shell prompt

---

helix-loader/src/lib.rs
helix-term/src/main.rs

The command always opened the default log file path. The path can be customized passing the `--log` optional argument. When this is the case the `open-log` command should respect it.

Fix `:log-open` when `--log` is specified

---

book/src/generated/typable-cmd.md
helix-term/src/commands/typed.rs

Resolves #7556
There are times this command would've been useful for me, and I think it makes sense to add this as an option.

Implement the wa! command

---

languages.toml

Me again. The "fuzzer" found problems in the code that caused hangs and sigsegvs. They were related mostly to baddly handled UTF-8 chars in my code (and the sigsegv came from the stdlib O.o). Now fixed. It now ran for 1 hour without finding any more problems so hopefully there's nothing like that anymore.

highlight(matlab): Better UTF-8 handling.

---

helix-term/src/main.rs

Either after parsing arguments or before running the `--health` logic, since that one already requires access to the `config` dir. I'd say it's better to play it safe and put it right after parsing arguments.

Initialize log and config files right after parsing arguments

---

runtime/themes/nord.toml

This rewrites the entire Nord theme to make it follow the [upstream style guide](https://www.nordtheme.com/docs/colors-and-palettes). The current Nord theme does not follow the style guide and also does not look like any of the official ports. The [nord.vim](https://www.nordtheme.com/ports/vim) port was used as a guide when the nord style guide was unclear. This looks much more similar to the other Nord ports,  and also improves the
contrast of code compared to the old theme.

Update the Nord theme to follow the Nord style guide

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/haskell-persistent/folds.scm
runtime/queries/haskell-persistent/highlights.scm
runtime/queries/haskell-persistent/locals.scm
runtime/queries/haskell/injections.scm

This adds support for the language used by a [persistent](https://hackage.haskell.org/package/persistent) library to define the database models. This syntax is only used by one library, so I chose to prefix the language name with "haskell-" for specificity.
The haskell [injections query](https://github.com/helix-editor/helix/blob/master/runtime/queries/haskell/injections.scm) uses the name of the function that handles that content of the quasi-quote as the name of the language. The persistent library has three of them that I included into the `injection-regex`.

Add language support for persistent library syntax

---

helix-term/src/commands.rs
helix-view/src/editor.rs

Same as #6061 but without relying on #6056 as per the discussion we had there.
`last_motion` is now a private field and can only be set by calling `editor.apply_motion()`. Thus removing the need (and possibility of forgetting) to write the following every time a motion is to be applied and saved:
```
motion(editor); 
editor.last_motion = motion
```
Now it's just: `editor.apply_motion(motion)`
New behavior that fell out from this is that repetitions of t,T,f,F motions are stored with the context of extension/move and count. (Not defaulting to extend by 1 count). So 3f -> repeat_last_motion becomes 3f and not 1f. I'm not sure the old behavior was intentional, as I saw no discussion of it when introduced in #891.
Of all the open PRs that are currently mergeable with master, and pass all CI …

(Updated) Apply motion API refinements

---

languages.toml

This fixes syntax highlighting problems with major Dart 3 update on classes, enums, and switch statements

Update dart commit in languages.toml

---

helix-core/src/lib.rs
helix-core/src/rope_reader.rs
helix-term/src/commands.rs

Followup to #5639, addresses https://github.com/helix-editor/helix/issues/5604#issuecomment-1399674583
Currently, helix always queries the FS when performing global search.
However, when previewing and opening a file helix automatically uses the buffer if it's already open.
That means that the search would report incorrect results for unsaved buffers (which lead to crashes prior to #5639).
This PR creates am implementation of `std::io::Read` for `Rope`, so we can easily reuse the existing API in `grep_searcher`.
This change has the nice side effect of avoiding IO for already open buffers for global search. The performance difference will rarely matter in practice, but it's a nice boost when a huge file is already open in helix.
A similar mechanism can be used for #5645 so that files that …

search buffer contents during global search

---

Cargo.lock
helix-core/src/path.rs
helix-loader/Cargo.toml
helix-loader/src/lib.rs
helix-lsp/src/lib.rs
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/commands/dap.rs
helix-term/src/commands/lsp.rs
helix-term/src/commands/typed.rs
helix-term/src/ui/mod.rs

Should solve #2527
I didn't figure out how to set an error on the editor from some places.
Where is was crashing before, it now relies on the scratch buffer instead.
In some other places (not related to buffer, like the `open` command or the global search ), I was able to generate a message or rely on the default value of the PathBuffer.
Let me know any improvements/suggestions you can see, I'll be more than happy to correct them :)

Fix crash when cwd is deleted

---

helix-term/src/commands.rs

This make `c` auto indent if the selection begins by a whole line. 
I inspired from the other functions in `command.rs`.  I'm not sure if the implementation is very good, all the text editing functions in the code base are new to me.
Resolve https://github.com/helix-editor/helix/discussions/4507 https://github.com/helix-editor/helix/discussions/2783
|before|after|
|----|-----|
|![before_1](https://github.com/helix-editor/helix/assets/56633664/37fa684b-7605-4fcf-a1db-449c9c637b53)|![before_1](https://github.com/helix-editor/helix/assets/56633664/37fa684b-7605-4fcf-a1db-449c9c637b53)|
|![before_2](https://github.com/helix-editor/helix/assets/56633664/7bff72e5-3400-4cbb-95b2-5ea49305c669)|![after_2](https://github.com/helix-editor/helix/assets/56633664/8364f271-b6e7-4fb2-aa81-7fb9dac078cd)| …

Auto indent change if selection is linewise

---

languages.toml

Add to languages.toml the shebang to nushell files (`#!/usr/bin/env nu`)

Add shebang for nushell files

---

languages.toml

Howdy yall,
I edit a lot of systemd files, which are the INI format, and upon opening helix I constantly have to `:set-language`. I was wondering if it would be okay to add them to the ini file types.
- [Systemd unit files](https://www.man7.org/linux/man-pages/man5/systemd.unit.5.html)
- [Podman quadlet systemd units](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html)

Register systemd files as ini

---

runtime/themes/dark_plus.toml

A little change to the `dark_plus` theme.
- Before:
- After:

Change dark_plus inlay-hints colors to more pleasant colors

---

Cargo.lock
helix-term/Cargo.toml
helix-term/src/application.rs

Crossterm will soon merge https://github.com/crossterm-rs/crossterm/pull/735 which will let it use /dev/tty on macOS. This will fix #2111 and allow piping to Helix on macOS.
Fixes #6734

Fix piping to Helix on macOS

---

runtime/themes/naysayer.toml

This theme is a port of https://github.com/nickav/naysayer-theme.el.

runtime/themes: Add "naysayer" theme

---

helix-term/src/commands.rs

When the target character is pressed, the selection is temporarily updated to display the affected positions. It restores the original selection after the operation is cancelled or completed.

enhanced `surround_replace` to provide visual feedback

---

languages.toml

[Brewfile](https://thoughtbot.com/blog/brewfile-a-gemfile-but-for-homebrew) is a Ruby Gemfile, but for [Homebrew](https://brew.sh).

feat: add Brewfile to Ruby file-types

---

languages.toml

Registers extra R ecosystem files
- `.Rprofile` & `Rprofile.site` files, which are configured in R
- `Renviron` & `.Renviron` files, which are [GNU configuration files](https://www.gnu.org/prep/standards/html_node/Configuration.html), a syntax that is a subset of the existing `bash` syntax
- `Rd` documentation files, which use `infotex`, a subset of LaTeX
- `.Rbuildignore` (sort of like a `.gitignore` for R packages), which is defined as `regex`s
Quite a few files in the R ecosystem use the Debian Control File (DCF) format, but there isn't an existing language to couple that to, so I'll leave that for a separate PR.
(using [R administration guide as reference](https://cran.r-project.org/doc/manuals/R-admin.html))

Add a more file types for R

---

helix-core/src/syntax.rs

Fixes #7434
fixes https://github.com/helix-editor/helix/issues/3816
fixes https://github.com/nix-community/tree-sitter-nix/issues/39
fixes https://github.com/helix-editor/helix/issues/7578
fixes https://github.com/helix-editor/helix/issues/3283
fixes https://github.com/helix-editor/helix/issues/7615
The crash was caused by creating multiple overlapping injections (one for `bash` and another one for the shebang). Having two overlapping injections in the same layer doesn't make much sense. Therefore, I added a simple check that skips any injection that intersects with a previous one.
This works because queries are visited in ascending order (start never decreases). However, we had two queries for injections: one for combined injections and normal injections. That meant that overlaps between …

Fix crash for overlapping injections

---

helix-term/src/ui/prompt.rs

Closes #6478
The prompt acts as an overlay and should hide any text underneath.

Clear statusline while prompt is visible

---

runtime/themes/kaolin-dark.toml
runtime/themes/kaolin-light.toml
runtime/themes/kaolin-valley-dark.toml

Hi, I tried porting these variations based on the original [Kaolin themes](https://github.com/ogdenwebb/emacs-kaolin-themes) palette:
<details>
<summary>Kaolin Dark</Summary>
<br>
</details>
<details>
<summary>Kaolin Light</Summary>
<br>
</details>
<details>
<summary>Kaolin Valley Dark</Summary>
<br>
</details>

Add Kaolin Dark, Light and Valley Dark themes

---

helix-lsp/src/client.rs
helix-term/src/commands/lsp.rs

fix https://github.com/helix-editor/helix/issues/5118
tested with deno (works)
I imagine the code is not ideal since I'm blocking for a future inside the callback to wait for the resolver also I had to clone the code action

feat: resolve code action

---

runtime/themes/gruvbox_dark_hard.toml
runtime/themes/gruvbox_light.toml

Fix the problem already explained in #7126 for both `gruvbox_light` and
`gruvbox_dark_hard` themes by letting them use `ui.selection` related
configuration from the parent theme.
Closes #7126

Fix selection highlighting in remaining gruvbox derived themes

---

runtime/themes/gruvbox.toml

Hi!
I find the default brightness of the soft-wrap indicator to be too distracting. This dims it quite a bit, bringing it down almost to the background level.
Could such a change be considered for merging? I personally think it has a positive impact on the quality of gruvbox-derived themes.

Update soft-wrap indicator in gruvbox.toml and themes derived from it

---

runtime/queries/comment/highlights.scm

These 2 captures were missing `#` so it's not working as intended
Was there any particular reason they were done as such?

fix(comment): fix incorrect predicate

---

runtime/themes/everforest_dark.toml

everforest_dark had missing color definitions, and so the modes had no colors in the statusline, and the bufferline had no highlighting

Update everforest_dark.toml to add missing color definitions

---

runtime/themes/pop-dark.toml

This PR is meant to make the hover diagnostics more legible by inverting the background and foreground color settings for `info`, `warning`, `hint`, and `error`. 
Previously, it was not clear the status level of each item in the diagnostics picker. These changes fix that as well.
Before:
After:

Theme Pop-Dark: Increase Diagnostics clarity

---

helix-term/src/ui/completion.rs

See https://github.com/helix-editor/helix/issues/7643#issuecomment-1642740855
When you accidentally accept the wrong completion candidate and then go to normal mode and undo, the whole insert is undone which feels like too much. We can save an undo checkpoint when accepting a completion of the text before the completion takes effect so that the undo window is smaller.
I'm not sure if this is too granular or not: if you use completions frequently this can introduce many undo points.

Save an undo checkpoint before accepting completion

---

helix-core/src/history.rs
helix-core/src/syntax.rs
helix-core/src/transaction.rs
helix-core/tests/indent.rs
helix-term/src/ui/lsp.rs
helix-term/src/ui/markdown.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/picker.rs
helix-term/src/ui/prompt.rs
helix-view/src/document.rs
runtime/queries/regex/highlights.scm

We can re-use the code-block highlighting function from the markdown component to highlight regex prompts with tree-sitter-regex. To make this change a little cheaper, we switch some functions from taking `&Rope`s to `RopeSlice`s (see 50557c62747e076e0c35f72c396e20d48d4e9052's message).

Syntax-highlight regex prompts

---

helix-core/src/match_brackets.rs
helix-core/src/transaction.rs
helix-loader/build.rs
helix-lsp/src/lib.rs
helix-term/src/commands/lsp.rs
helix-term/src/commands/typed.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/picker.rs

As discussed in https://github.com/helix-editor/helix/pull/4443#discussion_r1271457803
I ran a format with rust nightly over the code, and fixed all issues where MSRV rustfmt would do something different (so that CI runs through).
I think this makes sense, since I often (and I'm sure I'm not the only one) reformat code with whatever rustfmt version I'm currently using, and this introduces a lot of changes that are unwanted compared to the actual change I was doing. This should at least minify this issue (two changes are still different with nightly rustfmt, the infamous comment in `helix-view/src/editor.rs` and a let else in a macro (which I formatted manually)).

Reformat with nightly rustfmt for better let-else formatting

---

flake.lock
flake.nix

This resolves a build issue with nci/dream2nix and git dependencies. We can keep most of the helix-specific parts of the flake, we just need to switch from configuring nci to calling craneLib functions.
We also switch to flake-utils from flake-parts:
* Using rust-overlay with flake-parts directly is unergonomic (see https://github.com/hercules-ci/flake-parts/discussions/83).
* Removing flake-parts reduces the overall dependencies: rust-overlay already depends on flake-utils.
Closes #7761

Refactor Nix flake to use crane

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/wren/highlights.scm
runtime/queries/wren/textobjects.scm

Add basic support for the [Wren](https://wren.io) scripting language, based on my Tree-sitter grammar.

Add Wren support

---

languages.toml
runtime/queries/prql/highlights.scm

* updates the PRQL tree-sitter parser to the newest version
* adds new keywords and removes ones that are deprecated
* compatible with PRQL v0.9.x

feat: update prql parser

---

runtime/themes/vim_dark_high_contrast.toml

it doesn't follow it exactly, it tweaks the colors a bit to be easier to read, but it follows the same basic concept.
preview:

add new theme based on the default vim dark theme

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/v/highlights.scm
runtime/queries/v/indents.scm
runtime/queries/v/textobjects.scm

replace new lsp for vlang

---

Cargo.lock

I noticed that [hermit-abi 0.3.1](https://crates.io/crates/hermit-abi/0.3.1) is yanked, so this just updates that to the next version in Cargo.lock

update yanked dependency

---

languages.toml
runtime/queries/t32/highlights.scm

Version 2.2.1 of the grammar adds extended support for HLL (C, C++,..) expressions. Quite a few node types were added, renamed or removed in the process.
This change brings the highlight queries in sync with the ones found in the repository of the grammar. The highlighting tests "look" okay after updating the queries.
Recently, Codeberg had some reliability issues. That is why the language is now using the mirror repository on GitLab as source instead.

Update t32 language queries to version 2.2.1

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/wren/highlights.scm
runtime/queries/wren/indents.scm
runtime/queries/wren/injections.scm
runtime/queries/wren/locals.scm
runtime/queries/wren/textobjects.scm

This uses the improved grammar and adds queries for indenting, injections and locals, plus overall improvements.
Maybe this isn't the right place to ask this, but is there a reason why only parameters are highlighted a different color using the locals queries?
Example:
```javascript
function test(a) {
a // highlighted
const b = 1
b // not highlighted
}
```
I guess it's because it's less confusing?

Improve wren support

---

.github/workflows/release.yml

The steps mistakenly produce a x86_64 appimage and call it aarch64. linuxdeploy doesn't currently support producing aarch64 appimages so we should just remove these steps for aarch64-linux.
Closes #5237

CI: Remove the aarch64 appimage build steps from release

---

book/src/generated/lang-support.md
runtime/queries/bash/textobjects.scm

This implements function, (calling) argument and comment captures for use in the textobject selections in bash.
This also updates the generated docs after adding the textobjects for bash.

Add tree-sitter textobjects queries for bash

---

languages.toml
runtime/queries/_jsx/highlights.scm
runtime/queries/_jsx/indents.scm
runtime/queries/ecma/highlights.scm

Closes #7845.
**Disclaimer**: _The quotations below show that this phrase is taken from the relevant upstream commit/pr. This is my first time using this format, so if it's not comfortable, let me know. Just want to provide some guidance to make the PR review as easy as possible (I spent a lot of time jumping between upstream commits and understanding the api changes)._
* rename `?.` to `optional_chain`.
> Optional chaining property/array access and optional function calls now produce an `optional_chain` named field.
* Remove some queries with `nested_identifier`, 
> Made the Foo.Bar part in <Foo.Bar/> have the same parse tree as in const Component = Foo.Bar using aliases. We get the parse tree (member_expression (identifier) (property_identifier)) instead of (nested_identifier …

build(tree-sitter): update javascript, typescript and tsx

---

helix-term/src/ui/editor.rs
helix-view/src/view.rs

Closes https://github.com/helix-editor/helix/issues/7154
Setting `gutters.line-numbers.min-width` to a value higher than `terminal_width * terminal_height` led to index out of bounds.  
My approach was to have the width of `LineNumbers` be capped at 90% of the viewport size. Everything works as expected until the threshold is reached, when `min_width` is set to default value.
https://github.com/helix-editor/helix/assets/83179501/6f4b82a2-3c02-49c9-adf0-24683ccedbe6

Skip rendering gutters when gutter width exceeds view width

---

helix-term/src/ui/picker.rs

this way the preview always shows the selection even if lines were wrapped
fixes #7836

Center the picker preview selection using visual lines

---

helix-term/src/commands.rs
helix-term/src/commands/lsp.rs
helix-term/tests/integration.rs
helix-term/tests/test/picker.rs
helix-view/src/editor.rs
helix-view/src/view.rs

Closes #7673
Now if `alt-ret` is pressed, it opens the selected file and places the cursor on the selected line (if path contained a line number), but in the background (i. e the focused document remains unchanged).

Align view for background buffer  opened with `alt-ret`

---

book/book.toml

This makes search results less surprising, because it is how major web search engines behave

use AND operator when searching

---

helix-view/src/document.rs

Previously all files not backed by an existing file (`:open does-not-exist.txt`) would be marked as readonly in the new read-only-indicator statusline element (#7740).

Detect non-existent files as non-readonly

---

helix-term/src/commands/typed.rs

Update toggle implementation to accept toggling numbers. Thanks to https://github.com/helix-editor/helix/pull/4411#issuecomment-1669848066 where it became clear that adding support for it is quite trivial.

Enhance :toggle to support cycling numbers

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/todotxt/highlights.scm

Add support for todo.txt ([docs](https://github.com/todotxt/todo.txt), [website](http://todotxt.org/)).
Since i often use todo.txt for organizing and markdown is already included i wanted to offer upstreaming my config.
The official file extension is `.todo.txt`, but that doesn't work with helix (and a bunch of other editors) due to the recognition prioritization, therefore i also added the alternative `.todotxt` extension.
This uses the same tree-sitter as [neovim](https://github.com/nvim-treesitter/nvim-treesitter/pull/2594).

feat: add todo.txt tree-sitter

---

helix-core/src/graphemes.rs

I noticed that the `From<String>` impl of `GraphemeStr` doesn't set the high bit on `self.len`.  My understanding is that this would mean that the backing memory for the string will not get dropped when the `GraphemeStr` is dropped. This PR fixes the that by setting the high bit during conversion.

Prevent GraphemeStrs created from Strings from leaking

---

languages.toml

- Added csharp-ls for C# LSP server
- Added pyright for Python LSP server
- Updated python's `roots` for better determination of project root
- Added pylyzer for Python LSP server
Note: All LSP servers are not set to default, they are just for people who prefer them.

Added some LSP servers and updated python's roots

---

runtime/queries/rust/textobjects.scm

looks like two lines were unintentionally joined - it doesn't appear to affect the functionality, but it's confusing to read

fix formatting in the rust textobject query file

---

helix-term/src/commands/dap.rs
helix-term/src/ui/mod.rs

Fix [#6481](https://github.com/helix-editor/helix/issues/6481)

Include completions for git-ignored files in debugger prompt

---

helix-term/src/commands.rs
helix-view/src/register.rs

Resolves #5112.
This PR makes changes to the behavior of search commands:
- The editor now remembers the _search register_ used to kick start a `search`/`rsearch`/`global_search` command;
- `search_next`, `search_prev`, `extend_search_next`, and `extend_search_prev` now uses the _search register_ to continue the search;
- `search_selection` now uses the selected register. It also updates the _search register_;
- `make_search_word_bounded` defaults to using the _search register_ to make the `search_selection`-`make_search_word_bounded` flow more ergonomic, while also accepting register selection.
Overall, this PR should make the whole family of search commands play more nicely with register selection.

Make editor remember the latest search register

---

helix-tui/src/terminal.rs

This is intended to be a fix for #7404. I was able to replicate on MacOS by setting Terminal.app's default cursor to something other than Block, and then binding a key to `:quit` as described in the issue. Via debugging, I found that `Terminal::restore` actually does reset the cursor correctly regardless of if a keybind is used or if `:quit` is used.
However, the cursor gets set back to `CursorKind::Block` when the process exits if a keybinding was used.
It turns out that the `Drop` impl for `Terminal` will put the cursor back in block mode if `terminal.cursor_kind` is `Hidden`. Via debugging, I found that this was not the case if `:quit` was used but was the case if the keybind was used.
My understanding is that either `Terminal::restore` or `TerminalBackend::force_restore` will be …

Always reset cursor correctly on exit.

---

languages.toml

Including `zshrc` et al. since it is convention in dotfiles repos to store these config files without the `.` prefix. Please let me know if I should also add the un-prefixed file types for the bash configs.

Update languages.toml for `zshrc` et al

---

helix-term/src/commands.rs

Closes #7906.
Potential problems:
- Relative paths are resolved with reference to the current working directory, instead of the file they are selected from (this was already the behavior, I tried to fix it but couldn't)

feat: open file picker on directories using goto_file (gf)

---

languages.toml

In addition to the other defined extensions, `.star` is a frequently used extension for starlark files. This can be demonstrated through a cursory search of github for files ending in `.star` here: https://github.com/search?q=path%3A%2F.star%24%2F&type=code

Add .star as starlark file extension

---

book/src/keymap.md

I found out about the existence of `Alt-Enter` when I noticed #7691 being merged. I then tested it in the `space-f` picker and found it worked there as well. Since this seems to be consistent behavior, I figured it should be documented.

Document Alt-Enter for the picker

---

runtime/queries/markdown.inline/injections.scm

Problem: Closing tags for markdown is sometimes not highlighted 
Solution: Add `injection.combined` to create a valid syntax tree for highlighting
Similar to #5265, but for markdown inline

markdown.inline: Add `injection.combined` to html tag

---

runtime/themes/nord.toml

The new nord theme sets the `fg` value of `"ui.virtual.ruler"` instead of the `bg`, which makes it really hard to see where the ruler actually is.
Also, this should make it more consistent with the other themes. (they all set `bg`)
note: Changed it to `nord1` because that's what nord-vim uses for [`ColorColumn`](https://github.com/nordtheme/vim/blob/main/colors/nord.vim#L131)
before:
after:

Nord theme: Update ruler to set bg instead of fg

---

helix-term/src/commands/typed.rs

Since the argument of `:new` is never used, the completion might be confusing for user.

Remove path completions for `:new` command

---

helix-core/src/path.rs
helix-term/src/application.rs
helix-term/src/commands/typed.rs
helix-term/src/ui/picker.rs
helix-term/tests/test/picker.rs
helix-view/src/document.rs
helix-view/src/editor.rs

Following function never fails but returns a `Result`.
https://github.com/helix-editor/helix/blob/01a1e5ec2a8c5b81da1360746dad0a96cd88ae8e/helix-core/src/path.rs#L88-L97
This change just fixes this and all the callers of this function.
History:
Previously the function returned a `Result` as it had to rely on `std::env::current_dir` which could fail. But in https://github.com/helix-editor/helix/commit/8afc0282f28e73cf78d1bd7b11d78fd853ae2036 we started relying on `helix_loader::current_working_dir` which consumes the `Err` already.

[chore] Remove unnecessary `Err` from `get_canonicalized_path`

---

helix-term/src/commands.rs

Changed the function to join the selected path with the parent of the document. It will use the working directory if doc.relative_path() returns None.

goto_file_impl: use relative path to open file

---

helix-term/src/application.rs
helix-view/src/editor.rs

The redraw handle was using the idle timeout to denounce redraw requests so far. I will openly admit that I didn't quite appreciate the importance of the idle timeout back when I wrote the diff gutter PR (as I was still new to the codebase). It didn't really matter back then because the diff gutter timing out is a very rare occurrence but with #7538 the redraw handle is now triggered quite commonly which essentially makes the idle-timeout setting useless.
This PR fixes that by simply adding a separate timer for the redraw handle. In the long term we may move away from using the idle-timeout for debouncing data model update (#8021) at which point it would be fine to switch back to the idle timeout. Until all of that (substantial) work is finished I think its a good idea to fix this in the …

create separate timer for redraw requests

---

runtime/queries/dart/highlights.scm

Dart 3 introduces new `sealed` and `base` class modifiers, but they are not properly highlighted in Helix. This PR fixes that by adding them to the keyword list.

Highlight Dart 3 `sealed` and `base` keywords

---

book/src/generated/lang-support.md
languages.toml

`ltex-ls` now supports spelling and grammar correction for git-commit files, so I think it makes sense to support it by default. Everyone could benefit from it as Helix has no built-in spelling/grammar checker.

Add ltex-ls language server

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/gemini/highlights.scm

`text/gemini` is the canonical content type of the gemini protocol.
[cheatsheet](https://gemini.circumlunar.space/docs/gemtext.gmi), [specification](https://gemini.circumlunar.space/docs/specification.gmi), [tree-sitter grammar i wrote](https://git.sr.ht/~sfr/tree-sitter-gemini)

languages: add gemini

---

languages.toml

Updates to the v0.30.4 release of tree-sitter-gleam which adds support for some new syntaxes added to the language. The changes are backwards compatible with the queries and we shouldn't need to add anything extra to the queries to cover the changes.
Also enables auto-format since the gleam language server supports it and gleam has a centralized formatter built into the compiler.

Update tree-sitter-gleam, enable auto-format

---

book/src/themes.md
helix-view/src/theme.rs

Seems like this was a pretty trivial fix, but please let me know if you spot anything obviously wrong here.
I tested it and it seemed like you could pretty easily modify `reset` to whatever you want and have it show up in your theme.

Expose "reset" color value in themes

---

flake.nix

Copy `contrib/Helix.desktop`, `logo.svg` and `contrib/helix.png` to the Nix output.
This allows nix (or home-manager) users to have their XDG desktop set up without manually copying these files.

Copy desktop and icon files to Nix output

---

book/src/themes.md
helix-view/src/theme.rs

This PR addresses the comment presented on https://github.com/helix-editor/helix/pull/8083
- Use `default` instead of `reset`, as this is the conventional name for ANSI codes 39/49. The word `reset` should be reserved for ANSI code `0`, which resets both fg and bg colors at once, while also removing all modifiers. While the code uses the value name `Reset`, this is misleading and should not leak into the user space.

Rename reset to default

---

helix-tui/src/backend/crossterm.rs

Crossterm supports the 'hidden' SGR parameter but we previously didn't set the attribute when the "hidden" modifier was specified in a theme.
See https://github.com/helix-editor/helix/discussions/8082

crossterm: Handle 'hidden' modifier

---

helix-term/src/ui/editor.rs

The completion component assumes that it operates on the same View but it's possible to break this assumption by switching windows through left-clicking. I believe we should clear the completion menu when switching windows to fix this.
This change fixes a panic for this scenario:
* Open a buffer with LSP completion available
* Split the window (for example `<C-w>v`)
* Enter insert mode and trigger the completion menu
* Select a completion candidate (for example with `<C-n>`)
* Switch to the original window by left-clicking in its area
* Enter insert mode and make edits (for example `o<backspace>`)
This will trip the `assert_eq` in Document::restore.

Clear completion when switching windows via click

---

helix-term/src/compositor.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/picker.rs

We currently keep the picker around after it's closed to allow it to be reopened. This can lead to excessive memory consumption for very large pickers (like when crawling home with nucleo). This PR ensures that we drop the last picker immediately when a new picker is opened, that we stop streaming in new matches into the closed picker and the background and does not store pickers with more than 100_000 items. 
In the long term a better solution would be to restart the stream (recrawl the FS) for such large pickers instead, but that requires larger changes.

avoid excessive memory consumption in picker

---

helix-term/src/commands.rs
helix-term/tests/test/movement.rs

Adds separate method for finding `<ret>` char.
Closes #8057 
Resolves TODO: https://github.com/helix-editor/helix/blob/79c04251547e6c0c21366d322e268a6581c0f5dd/helix-term/src/commands.rs#L1270-L1273

Fix find commands for buffers with non-LF line-endings

---

helix-term/src/commands.rs
helix-term/src/commands/typed.rs

Maintain the current cursor's position and view in the vsplit/hsplit commands too

---

runtime/themes/nord.toml

During a refactor of the theme the ui text focus was removed (accidentally?) which makes the picker much less easy to read. The diagnostic undercurls had also been removed in the refactor so added them back.
Before:
After:

Nord Theme: Fix missing ui text focus, use undercurls for diagnostics

---

helix-view/src/clipboard.rs

Currently, only `pbcopy` and `pbpaste` are allowed as clipboard provider on macOS, seemingly without good reasons.
When SSH-ing into a macOS server, there's no way to yank to the client clipboard, even inside a tmux session, as Helix refuses to use tmux as clipboard provider on macOS, and the default provider (`pbcopy`) does not pass the content to SSH clients.
This PR adds the same tmux test to macOS.

Detect tmux clipboard provider on macOS

---

Cargo.lock
helix-term/src/ui/mod.rs

Closes #8142
There were actually two issues here:
* `nucleo` had a bug where it would start the matcher but not wait for it to finish on the first call to `tick`. I fixed this upstream and also updated the `Cargo.lock` file a bit (using cargo update) to remove some duplicate dependencies.
* For the file picker the `(running)` indicator would still always appear because starting a background thread takes a while causing a timeout. I fixed this by running the FS transversal on the UI thread for up to 30ms. This is short enough to not cause UI lag but long enough for most reasonable directories to finish.
For the global search picker the problem persists, but since the global search runs eagerly there is no way to fix that (one we start the search it will always block the main thread until …

Do not show (running) when opening picker

---

helix-core/src/fuzzy.rs
helix-term/src/ui/menu.rs

This fixes a regression introduced in the nulceo PR.
We used `Pattern::new` for fuzzy matching, however during the nulceo 0.2 release the definition of that function changed so that it also performs word splitting. That would mean that typing spaces would for example never close the completion popup. This PR fixes that by switching to `Atom::new` instead which is the right API for our use case (exactly the same as Pattern::new but does not perform word splitting).

Don't use word splitting during fuzzy matching

---

helix-term/src/ui/picker.rs

Injectors detect that a Picker has been shut down / removed by checking the shutdown atomic bool (which is shared with the Picker instance and is set to `true` on Picker's Drop). Cloning Injector should create more references to the Picker's atomic bool rather than creating new ones. This should fix global search so that the WalkBuilder halts when the picker is dropped.

Fix Clone definition for Injector

---

book/src/languages.md

Seems like the file in the branch that the existing link was pointing to has been moved/removed. This new link is the page version of the same source code docs.

docs: fix link to document formatting requests

---

helix-term/src/ui/picker.rs

Closes #8205
This bug was caused by us only looking for the normal picker (but not the dyn picker) component in the compositor when doing syntax highlighting. This was a regression caused by #7028.

fix syntax highlights in dynamic picker

---

languages.toml

This updates the esdl tree sitter grammar to the most recent version.
For context: Edgedb v3 came with some syntax changes which required an update to the tree sitter along with some other fixes.

Update EdgedDB (ESDL) grammar

---

languages.toml

Various files use the same syntax highlighting as `.gitignore` and similarly tell different tools what files/folders to ignore. Update the languages files so that other ignore type files use the same highlighting gitignore. The files added are:
- .ignore
- .prettierignore
- .eslintignore
- .npmignore
Resolves: #8089

chore: add additional ignore file highlights

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/perl/indents.scm
runtime/queries/perl/textobjects.scm

followup from https://github.com/helix-editor/helix/pull/7644#issuecomment-1637390250
opening this as a draft because it depends on some minor tweaks to the grammar itself that i'm working on here https://github.com/tree-sitter-perl/tree-sitter-perl/pull/110, but wanted to make sure the changes don't get lost

re-add indent and textobject queries for perl

---

helix-core/src/syntax.rs
helix-view/src/document.rs
runtime/themes/jellybeans.toml
runtime/themes/molokai.toml
runtime/themes/nightfox.toml
runtime/themes/noctis.toml
runtime/themes/rose_pine.toml

Various typos, found using [typos-cli](https://github.com/crate-ci/typos). This actually modifies the molokai and jellybeans themes as some keys were incorrect (but the changes "look" correct).

Fix various typos

---

runtime/queries/yaml/injections.scm

Adds injections for Github Actions & Gitlab CI.
Taken from https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/yaml/injections.scm, which is licensed under Apache-2.0. Let me know if I need to change the license text here :)

Add additional YAML injections

---

book/src/configuration.md
helix-term/src/commands/typed.rs
helix-term/tests/test/commands/write.rs
helix-term/tests/test/helpers.rs
helix-term/tests/test/splits.rs
helix-view/src/editor.rs

This resolves #4274 with the implementation largely based off of #5435
and also addresses the review from @the-mikedavis on that PR.
The option name is from EditorConfig's `insert_final_newline`, which is
also used by VS Code as `files.insertFinalNewline`.
We match Vim's behavior in that :w will add the newline to unmodified
files but :wa will not; see #1760. Tests are included for this.
Co-authored-by: Xalfer <64538944+Xalfer@users.noreply.github.com>

Add `insert-final-newline` config option

---

languages.toml

Similar to what was done in #6381, the backquote in OCaml can be used in the beginning of a constructor (<code>type t = [`Foo]</code>) and should not be auto-paired.

Disable auto-pairing ` in OCaml

---

book/custom.css
docs/CONTRIBUTING.md

Closes #8214
Also adds some documentation on how to preview book changes. Is running mdBook something we'd like to use xtask for in the future?

Fix search highlighting for the default docs theme

---

runtime/themes/papercolor-dark.toml
runtime/themes/papercolor-light.toml

Started out as just fixing the lints, ended up being a bit more substantial overhaul.
Primary changes:
*  Unify dark and light variants to share everything except palette
* Enables using `inherits` feature
* Extend original Papercolor with multi-cursor color variations
* Add indication for primary cursor
* Make cursor visible from selection
Minor changes:
* Add more and align existing scopes with Vim plugin papercolor
* Match UI elements closer to original
For both light and dark Vim screenshots, the cursor should be filled in, just like in Helix. Due to loss of focus when taking screenshots we get the boxed in letter variant instead.

Theme: Papercolor: Cleanup, linting and using inheritance

---

runtime/themes/zenburn.toml

Instead of using comment pick a color that stands out less

[theme] Fix zenburn theme inlay hint color

---

helix-term/src/ui/picker.rs

This PR fixes some issues with the picker preview.
Firstly it fixes a panic when previewing invalid ranges in the picker by simply only showing a placeholder in this case. Closes #8259.
While investigating this I noticed that #7837 had introduced a regression. In the past the picker centered all previewed ranges. However, after that PR only the *fist line* (instead of the middle of the previewed ranges) was centered.
I misread what the old code and therefore didn't notice during review. The second commit in this PR restores that behavior (can be easily tested by searching for `Modifier` in the global symbol picker in helix codebase) while keeping the soft wrap compatibility added by #7837.
Adding to the release milestone since it's an easy fix for a crash plus a fix for a regression in …

Fix picker preview

---

runtime/themes/cyan_light.toml

👋🏼  Hi there,
This is an approximate port of the [Cyan Light JetBrains](https://plugins.jetbrains.com/plugin/12102-cyan-light-theme) Light color scheme.
I hope others find it useful and would contribute if they find color accessibility issues.
Here are few screenshots
https://github.com/helix-editor/helix/assets/302837/1d339b65-0fcf-4e0b-96a5-1de3497994e2

[theme] add cyan_light theme

---

languages.toml

Configures `flake.lock` Nix files to use JSON highlighting.
Built locally and verified that this works.
Closes #8281

Add JSON highlighting for `flake.lock` files

---

languages.toml

As discussed in #8076 (https://github.com/helix-editor/helix/pull/8076#issuecomment-1722254250), this PR adds syntax highlighting for `.editorconfig` files as INI temporarily until Helix supports them directly.
While there is a difference between `.editorconfig` and INI syntax, it is very minor (see below) and most files are likely to highlight correctly, which should be a better compromise that not highlighting at all.
> EditorConfig files use an INI format that is compatible with the format used by Python ConfigParser Library, but [ and ] are allowed in the section names. The section names are filepath globs, similar to the format accepted by gitignore. Forward slashes (/) are used as path separators and semicolons (;) or octothorpes (#) are used for comments. Comments should go …

Add `.editorconfig` highlighting as INI

---

languages.toml

In frontend projects using [Babel](https://babeljs.io), `.babelrc` is a config file variant that is allowed as an alias for `.babelrc.json`.
> For compatibility reasons, .babelrc is an alias for .babelrc.json.
This PR highlights those files as JSON.
Built locally and tested.

Add `.babelrc` highlighting

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/purescript/highlights.scm
runtime/queries/purescript/injections.scm
runtime/queries/purescript/locals.scm
runtime/queries/purescript/textobjects.scm

Currently PureScript piggybacks on the haskell tree-sitter, which is less than optimal. I use @Maskhjarna's tree-sitter-purescript, which currently is the most feature complete implementation. I use this daily in my work, and while it has a couple bugs, it's far better than the haskell tree-sitter.

Use Maskhjarnas tree-sitter-purescript

---

book/src/themes.md
helix-view/src/gutter.rs

Currently the `diff.plus/minus/delta` keys are used both for the gutter indicator and the syntax highlighting (for example in `.patch` files). This limits the abilities to theme the diffs nicely, as the background appear in the gutter line. For example, with existing `papercolor_light` theme this gives:
It is also hard to find a good color as the gutter indicator needs to be very colored as it has a very small surface, but it forces a very bright text.
This change allows using a different style for the gutter diff indicator, allowing things like:
with:
```toml
"diff.plus" = { fg = "fg-added", bg = "bg-added" }
"diff.plus.gutter" = "green-intense"
"diff.minus" = { fg = "fg-removed", bg = "bg-removed" }
"diff.minus.gutter" = "red-intense"
"diff.delta" = { fg = "fg-changed", bg = …
```

Allow specifying a different style for diff indicator in vcs gutter

---

helix-term/src/ui/markdown.rs

Style doc comment markdown correctly with Bold / Strikethrough / Italics.
**Before:**
**After:**
Note the Italics of the word `do`

Style Bold/Italic/Strikethrough markdown in docs

---

helix-term/src/ui/markdown.rs

Previously, blocks like
<code style="..">..</code>
would not be properly recognized.
Closes #8378.

markdown: Recognize `<code>` tags with attributes as code

---

runtime/queries/go/highlights.scm

I've removed the query for all caps vars, because naming variables in this way isn't a go convention, but can relocate it to the bottom of the file as suggested in the issue discussion if that's preferred. 
[Go Wiki](https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps):
> See https://go.dev/doc/effective_go#mixed-caps. This applies even when it breaks conventions in other languages. For example an unexported constant is maxLength not MaxLength or MAX_LENGTH.
[Google Go Styleguide](https://google.github.io/styleguide/go/guide#mixedcaps):
> Go source code uses MixedCaps or mixedCaps (camel case) rather than underscores (snake case) when writing multi-word names.
>
> This applies even when it breaks conventions in other languages. For example, a constant is MaxLength (not …

update go highlight queries

---

helix-lsp/src/lib.rs
helix-view/src/editor.rs

Return `Result<Arc<Client>>` instead of `Arc<Client>` so that we can then filter only successfully started language servers and create an error log otherwise.
Closes #8361

Filter out language servers which fail to spawn

---

languages.toml

For example, this is standard for Debian rules files: https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#defaultrules

Add shebangs for Makefiles

---

runtime/themes/onedark.toml

HTML Tags were not colorized if using the "onedark" theme. I just set them to the color "red" like its also done in VSCode using the onedark theme.

Fix missing HTML tag colorization in onedark theme

---

runtime/themes/darcula-solid.toml
runtime/themes/darcula.toml

refine darcula and darcula-solid themes

---

helix-lsp/src/lib.rs

Closes #8422
The code worked as intended for the most part, the head < anchor and anchor < head case was just swapped accidentally. This caused a selection to be created from the first tabstop to the anchor (if the selection is forward) which would be merged with all other tabstop selections.

fix multicursor snippet placeholder directions

---

languages.toml

This brings Helix's out of the box experience concerning recognizing file extensions mostly in line (or with more associations) than VSCode for supported languages. 
See https://github.com/helix-editor/helix/issues/8375 for more context
Closes #8375

Add VSCode file associations

---

languages.toml

This adds validation to the CSS and JSON language servers. There is no validation availablre for the HTML server. I hope it can make it into the next release, this is a big upgrade for frontend use and should be available out of the box.
EDIT: It also enables validation for SCSS files too.

Add validation to the CSS and JSON language servers

---

helix-lsp/src/client.rs

Previously we accidentally checked the server's _completion_ resolve capability rather than the code action resolve capability. It looks like this was an oversight introduced in #7677.
Fixes https://github.com/helix-editor/helix/issues/8413
Fixes https://github.com/astral-sh/ruff-lsp/issues/249

LSP: Fix codeAction/resolve server capability check

---

languages.toml

EDIT I just saw https://github.com/helix-editor/helix/pull/7080 .. arrghhh! Please could people still have a look at the questions I bring up here and we can get the other one merged! Also, we have started merging more language server definitions since multiple language servers arrived on the scene...
The following appears to work fine with this pull request, which is simply `tailwindcss-ls = { command = "tailwindcss-language-server", args = ["--stdio"] }`:
```
sudo npm install -g @tailwindcss/language-server@insiders
```
```toml
[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]
```
`input.css`
(tailwind message)
(vscode-css-language-server …

Add tailwindcss language server

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/json5/highlights.scm

adds support for https://json5.org/
used for example by configuration files for [diffsitter](https://github.com/afnanenayet/diffsitter)

add json5 language

---

book/src/generated/lang-support.md
languages.toml

Add ansible support to yaml.
If this PR is accepted, I’ll update wiki accordingly.

Add ansible-language-server for yaml

---

helix-loader/src/lib.rs
helix-term/src/application.rs
helix-term/src/main.rs

When you start the editor with a directory as the first argument, or specify `-w, --working-dir <path>` it loads `.helix/config.toml` as if you didn't specify it.
This fixes issue #8469

Set the working directory before loading the config

---

helix-term/src/args.rs
helix-term/src/main.rs

Since the PR #5603 has not been updated, I went ahead and fixed the minor feedback from that PR and created a new one. I also fixed an issue making the first file never working with `<file>:<line>` as it was overridden.
Fixes https://github.com/helix-editor/helix/issues/5437

Add +N CLI argument to jump to first file's line number

---

helix-view/src/input.rs

When running the integration tests, I ended up with temp file paths containing "-" in the name. This in turn triggered an issue where the key "" could not be resolved. This is one way of fixing this issue, another is to check for "-" in parse_macro() and replace it with "minus".

Make parse_macro work for "-" outside "<..>"

---

helix-term/src/health.rs

Hi there, today I had to debug an lsp configuration with multiple servers and came across this missing feature.
I wrote a quick implementation for the `--health <language>` subcommand, but now I'm stuck at `--health languages`.
In my machine `--health languages` doesn't fully show lang-servers' names and if I were to print all names one after another it would be pretty useless.
My idea was to check for the number of lang-servers and if there are more than one than the output could be something like (the names are pretty bad, I'm seeking better ideas):
```
✓ All (in green, it means all servers are ok)
- Some (in yellow, it means some servers are ok and some are not)
✘ None (in red, it means all servers are not ok)
```
Then for a more detailed output the user could use `--health …

Add support for showing all LSPs in --health

---

helix-term/src/ui/editor.rs

Should close https://github.com/helix-editor/helix/issues/8550
The PR ensures we only show diagnostic highlights for lsp that have the `diasgnostics` feature enabled!

fix(lsp): ensure we only highlight diagnostics for lsp with the feature enabled

---

languages.toml
runtime/queries/haskell/highlights.scm

Bump tree-sitter-haskell and update queries

---

helix-term/src/application.rs
helix-term/src/args.rs
helix-term/src/main.rs
helix-term/tests/test/helpers.rs

When opening the editor using `hx <dir>` where `<dir>` is relative it would either open the wrong directory in the picker, or a new file.
This was introduced by #8498 
My solution is to replace the first argument by "." when it is a directory and override `args.working_directory`. This should effectively leave the original logic in place while still solve the config issue.

Fix issue with opening a relative directory with `hx <dir>` introduced in #8498

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/templ/highlights.scm
runtime/queries/templ/injections.scm

Added [templ](https://github.com/a-h/templ).
The captures probably still need some renaming.
Is the `structure.scm` needed?
[Quickstart](https://templ.guide/quick-start/creating-a-simple-templ-component)
[IDE Support](https://templ.guide/commands-and-tools/ide-support)

languages: add templ

---

runtime/themes/cyan_light.toml

Use the highlight names that are used to separate between gutter colors from diff lang colors in the highlight names and thus have better colors for diff lang
👇🏼

Theme cyan light diff colors

---

book/src/install.md
helix-loader/src/lib.rs

Currently, Helix looks for its runtime directory in the user's home directory, in the `HELIX_RUNTIME` directory if set, and finally the binary's directory. This makes it somewhat difficult for downstream packagers to figure out how to package the Helix runtime that we generate so that Helix can find it out of the box with no other user intervention.
Additionally, since each OS and distro will have its own conventional place they put application files, we can't simply choose a directory we think is common.
This has led to a few packages resorting to making `hx` a wrapper script that sets `HELIX_RUNTIME` and then invokes the real binary, which is not ideal.
This change adds the ability to hardcode one additional directory into the runtime search path by setting the `HELIX_DEFAULT_RUNTIME` …

Add optional runtime fallback directory

---

runtime/queries/rust/injections.scm

Add rust html injection query

---

.github/workflows/gh-pages.yml

Previously, the stable release would wipe the master files since master is a subdirectory of stable. We can publish stable first and then master so that both exist after pushing a new tag. This change swaps those two blocks.
See #8615

CI: Publish stable book before master

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/lpf/highlights.scm

Adds a small tree-sitter parser for the LPF configuration language https://github.com/danderson/ulxs/blob/main/lpf.md

Add LPF tree sitter

---

helix-tui/src/backend/crossterm.rs

Uses the `cnorm` capability from `terminfo` if available to reset the terminal cursor style. I tested this with `xterm` and it seems to fix the issue with making the cursor blink like in #3741.
Closes #2684

Use terminfo to reset terminal cursor style

---

languages.toml
runtime/queries/ron/highlights.scm
runtime/queries/ron/indents.scm
runtime/queries/ron/injections.scm

fixes #8578 
here is the pr @Omnikar its based on the queries from https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/ron and https://github.com/zee-editor/tree-sitter-ron/tree/main/queries changed to work with helix

switch to tree-sitter-ron

---

runtime/tutor

It doesn't really make sense to say that adding whitespace is "indenting" and removing it is "outdenting". And people would usually say "indent "/ "unindent", which is how the actions are actually called in helix. So, for consistency, they should be called the same in tutor.
Also in RECAP, it says 
```
* Type < and > to indent / outdent lines.
```
Which makes it seem like removing whitespace is "indenting" and adding it is "outdenting", which is the other way around.

Say "unindent" instead of "outdent" in tutor

---

helix-core/src/indent.rs

Fix precedence order of `@align` captures in indent computation

---

book/src/generated/lang-support.md
languages.toml

Adds the [`golangci-lint-langserver`](https://github.com/nametake/golangci-lint-langserver) for Go.

languages: add golangci-lint-langserver

---

book/src/configuration.md

I was reading the 23.10 changelog and saw that idle-timeout has been changed to 250ms https://github.com/helix-editor/helix/commit/060e73a

Update idle-timeout in docs

---

runtime/themes/licenses/everforest.LICENSE
runtime/themes/licenses/serika-syntax.LICENSE
runtime/themes/licenses/sonokai.LICENSE

Some themes are based on `MIT` licensed themes / code. For this reason we need to add  the original license text to be able to redistribute them. This is required for Fedora. I can add them myself in Fedora but having the files upstream makes it easier :D.

Add missing license files for themes

---

helix-view/src/register.rs

Swap system and primary clipboard registers

---

book/src/themes.md
runtime/queries/rust/highlights.scm
runtime/queries/rust/locals.scm

Highly generic code can be challenging to read when type parameters are highlighted the same as other types. This is especially true when the type parameters are not single letters, e.g. `Fut` is somewhat common in Rust. 
So this PR adds a new highlighting scope for type parameters. I added it only for Rust as a proof-of-concept, but if accepted I'll update the queries for any other languages I'm familiar with (either in this PR or in a follow-up, whichever is preferred).
Here is a before and after with my in-progress port of the [Codely theme](https://plugins.jetbrains.com/plugin/12891-codely-theme).

rust: add highlight scope for type parameters

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/kdl/highlights.scm
runtime/queries/kdl/indents.scm
runtime/queries/kdl/textobjects.scm

The tree-sitter for the kdl language currently being used contains bugs.
Consider the following kdl config:
```kdl
bigFlatItems "multiline \" \" \"\nstring\n" null
c "multiline string\nwith special characters:\n\t \n \" \"\n"
```
With the current tree-sitter implementation, escaped double quotes `\"` are being detected as characters ending a string. As such, they are improperly highlighted.
I propose to change the used implementation to https://github.com/amaanq/tree-sitter-kdl. It seems to be more up to date, more activate and highlights the previous example correctly.

fix: replace kdl tree-sitter to fix highlighting

---

.github/ISSUE_TEMPLATE/bug_report.yaml

We can guess the installation method from the version tag and platform in some cases but it would be useful to have this be explicit for the sake of debugging packager-specific problems.

Add an installation method field to the bug report template

---

book/src/usage.md
helix-term/src/commands.rs
helix-term/src/commands/typed.rs

#8703 swapped the `+` and `*` registers, but did not swap them in the corresponding yank commands.

swap yank command registers

---

runtime/queries/_typescript/highlights.scm
runtime/queries/_typescript/locals.scm
runtime/queries/go/highlights.scm
runtime/queries/go/locals.scm
runtime/queries/haskell/highlights.scm
runtime/queries/kotlin/highlights.scm
runtime/queries/kotlin/locals.scm
runtime/queries/ocaml/highlights.scm

This is a follow-up to https://github.com/helix-editor/helix/pull/8660 where I introduced the `@type.parameter` highlight scope to improve readability of generic code.
I've added the scope to several more languages:
* TypeScript
* Go
* Haskell
* OCaml
* The above two don't need queries `locals.scm` since type variables are distinguished syntactically
* Kotlin
* There was a typo causing all types to be highlighted as builtins, so I fixed that as well

highlights: add type.parameter scope to several more languages 

---

book/src/generated/typable-cmd.md
helix-lsp/src/client.rs
helix-term/src/commands/typed.rs

close #4393
Allows to rename the active buffer by moving it to another path.
```
:move my_new_file.rs
```
Heavily based on all the work done in https://github.com/helix-editor/helix/pull/5531 by @ontley and apply the suggestions
The PR seems dead and I would really like to see that feature come into helix :)

Add command to move files with LSP support

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/common-lisp/indents.scm
runtime/queries/racket/indents.scm
runtime/queries/scheme/indents.scm

Add indent queries for scheme following [this guide](https://github.com/ds26gte/scmindent#how-subforms-are-indented). The only thing which isn't fully implemented is the section about Lisp keywords: The queries handle them in a very simple way that sometimes underestimates the indent and the regex that matches keywords is definitely not complete. Still, it should be good enough to provide a good editing experience. Since I don't have any experience with Scheme/Lisp, it wouldn't hurt if someone more knowledgeable double-checked this though.
Since Lisp & Racket use the same grammar, I also just inherited the queries from scheme for them. For Racket, I added a default indent width, since there is a workaround in the queries that requires this (this workaround is a short-term solution but a …

Add indent queries for scheme

---

grammars.nix

You can now apply overlays to the grammar derivations via `grammarOverlays`. Also, the `src` in the derivation is now properly unpacked to the build directory, allowing the user to mutate the source files if they want to.
Example usage:
```nix
helix.override {
grammarOverlays = [
(final: prev: {
markdown_inline = prev.markdown_inline.overrideAttrs {
EXTENSION_TAGS = 1;
EXTENSION_WIKI_LINK = 1;
nativeBuildInputs = with pkgs; [ tree-sitter nodejs ];
preBuild = ''
rm src/parser.c
tree-sitter generate
'';
};
})
];
}
```
This builds the `markdown_inline` parser with optional extensions enabled.

grammars.nix: allow the user to apply overlays

---

helix-core/src/syntax.rs
languages.toml

Previously roots needed to be specified by every language and `[]` was used as an explicit default. Root files don't make sense for every language (for example TOML) so I think we should allow languages to not explicitly mention the key and have the `[]` default automatically.

Default 'roots' field of language config

---

runtime/themes/starlight.toml

Hi! This is a higher contrast, usability-focused theme. It uses the colors of the [Starlight](https://github.com/CosmicToast/starlight) ansi color palette that is designed with accessibility and usability as a priority.
My use case with this theme is to have a dark theme that still maintains readability in brighter ambient light and allows for less monitor brightness.
Below are a couple design choices I've made that differ from many other bright themes already in Helix:
- Fewer highlighting scopes: Keep scopes (and colors) distinguishable
- Even brightness: I've avoided big differences in brightness to keep all scopes readable even in bright light
- UI should be readable too: All selections and cursors are very visible, and differentiating between primary and secondary selections should …

theme: add starlight

---

book/src/install.md

Remove COPR install in favour of official Helix package
===
Helix has now been approved for official inclusion into the Fedora project, so this PR updates the documentation to enable users to install the official version rather than the community provided COPR version.
Please do not merge this just yet, as it will still be a week or so until the package is live, at which point I will update this from a draft to allow merging.
Thanks.

Change Fedora installation to the new official Helix package

---

book/src/configuration.md

Small fix because there were some unformatted default values in `[editor.file-picker]`.

Book: fix formatting of some default values

---

languages.toml
runtime/queries/purescript/highlights.scm
runtime/queries/sql/highlights.scm

This PR is kind of tricky because I am unsure how you guys handle language / grammar updates.
Problem I am trying to solve here: We need to include license files for all grammars. Some grammars that are used in `languages.toml` use an old commit where the license file is not included. I updated the grammars to a commit that includes the license file.

Update some grammars to a commit where the license file is included

---

helix-term/src/commands.rs

Fixes #8687 
The issue also mentioned that paste exits select mode but I don't think that is the case, only replace seems to. Should we also add exiting select mode to paste or any other commands?

feat: make more commands exit select mode

---

runtime/themes/README.md
runtime/themes/licenses/poimandres.LICENSE
runtime/themes/licenses/starlight.LICENSE

In the process of packaging helix for Fedora, I submitted a [PR](https://github.com/helix-editor/helix/commit/a069b928973aad99b85dffb9d5ade7dae4b58c43) to add missing license files for themes. This is **must** requirement for Fedora and probably other distributions. This PR adds a note and ask contributors to also submit license files with themes that require them. This is the case when the work is derived from another theme or color palette.
I also added the missing license files for the recently added themes.

Mention license file for themes in README

---

helix-term/src/application.rs
helix-term/src/args.rs
helix-term/src/main.rs

As discussed with @the-mikedavis in https://github.com/helix-editor/helix/issues/8520#issuecomment-1784158957

Resolve args.files before changing directory

---

helix-term/src/ui/document.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/picker.rs

This fixes the first half of https://github.com/helix-editor/helix/issues/5675, namely the whitespace case.
Based on the suggestions by @pascalkuthe in https://github.com/helix-editor/helix/pull/8733
Is this along the lines of what you envisioned?

Fix precedence of ui.virtual.whitespace

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/dbml/highlights.scm

It would be great if we can read/write DBML files in Helix.
[DBML](https://dbml.dbdiagram.io/home/) (Database Markup Language) is an open-source language for documenting database schemas and structures.
The highlighting is not complete, but it is good starting point:

DBML Language support

---

runtime/themes/modus_operandi.toml
runtime/themes/modus_operandi_deuteranopia.toml
runtime/themes/modus_operandi_tinted.toml
runtime/themes/modus_operandi_tritanopia.toml

This PR adds themes based on the light variants of the carefully designed [modus](https://protesilaos.com/emacs/modus-themes) themes (built-in with Emacs). This is not a port of the original theme, as Emacs themes are much more than a color scheme, but a set of Helix themes inspired by the defaults of the modus operandi (light) theme, and reusing their color palette. They follow the same goals, i.e. legibility and accessibility (following the highest WCAG AAA standard), even over esthetics when necessary. 
The themes are:
* `modus_operandi`: the base theme
* `modus_operandi_tritanopia`: a variant of the base theme for blue-yellow color deficiency
* `modus_operandi_deuteranopia`: a variant of the base theme for red-green color deficiency
* `modus_operandi_tinted`: a variant with a …

Add modus operandi themes

---

.github/workflows/build.yml
helix-core/src/syntax.rs
helix-term/Cargo.toml
helix-term/src/commands.rs
helix-term/src/commands/lsp.rs
helix-tui/src/buffer.rs
helix-view/src/editor.rs
helix-view/src/gutter.rs
helix-view/src/handlers/dap.rs
rust-toolchain.toml

With Firefox 120 released on 21 November 2023, the MSRV is now 1.70.0.
---
According to https://firefox-source-docs.mozilla.org/writing-rust-code/update-policy.html (and after attempting to download Firefox myself), Firefox 120 has been released. Since helix follows Firefox's MSRV (https://github.com/helix-editor/helix/blob/47b6c4bc78d449e3586f28d26507bfc8fb8608e2/docs/CONTRIBUTING.md#minimum-stable-rust-version-msrv-policy), I bumped the MSRV to 1.70.0 in line with Firefox!
(The main thing I'm looking forward to is the sparse crates registry support added in 1.68.0.)

rust-toolchain.toml: bump MSRV to 1.70.0

---

book/src/themes.md
helix-term/src/ui/document.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/picker.rs

This fixes the first half of https://github.com/helix-editor/helix/issues/5675, namely the whitespace case.
This is a patch up from https://github.com/helix-editor/helix/pull/8750, which was reverted. Sorry for that.

Fix precedence of ui.virtual.whitespace 

---

Cargo.lock
helix-dap/Cargo.toml
helix-loader/Cargo.toml
helix-lsp/Cargo.toml
helix-term/Cargo.toml
helix-view/Cargo.toml

Looking at which crate changelog for version 5.0.0
5.0.0
Remove several unused error messages
Windows executables can now be found even if they don't have a '.exe' extension.
Add new error message, Error::CannotGetCurrentDirAndPathListEmpty
It seems that no breaking changes have been implemented
UPDATE: added cargo lock to PR due to a CI error in previous upload

update which crate to 5.0.0

---

helix-term/src/ui/editor.rs

All but the documents block cursor change their shape to a box outline if the terminal loses focus. I am missing that feature because (depending on your window manager) it can be hard to tell which editor has focus if you have multiple open at the same time. Because the custom rendered block cursor is just the background color of the respective char it is no possible to achieve the same behavior (display as outline).
Therefore I created a proof of concept for the custom block cursor to change its color when the terminal window loses focus. 
If the theme does not define a color for the unfocused cursor (e.g. `ui.cursor.primary.unfocused`) it should calculate the color by faking transparency of the cursor. Therefore it tries to get the background color and the cursor color and mix them. …

Use crossterm cursor when terminal loses focus

---

helix-term/src/ui/editor.rs

I found a missing special case for the out-of-focus crossterm cursor: When the block cursor is at the end of the rope it is not hidden.

fix(ui): use crossterm cursor when at the end of the rope

---

languages.toml

MusicXML is an open standard for digital sheet music
[https://www.w3.org/2021/06/musicxml40/](https://www.w3.org/2021/06/musicxml40/)
[https://en.wikipedia.org/wiki/MusicXML](https://en.wikipedia.org/wiki/MusicXML)
PS:
Note that `mxl` is the extension for compressed MusicXml files and should not be treated as `XML`

Add musicxml to xml extensions

---

.envrc

This allows direnv to switch the Nix dev shell when switching across branches running different Rust verions.
Switching between master and older branches won't automatically change cargo/Rust versions after #8877 unless direnv is watching the rust-toolchain file.

direnv: Watch the rust-toolchain file

---

book/src/configuration.md

I do not find anywhere where the name omits the 's'

docs: Fix reference to git `core.excludesfile` option

---

flake.lock
flake.nix

also removed non-existent crane flake input overrides
This was just a simple `nix flake update`

nix: update flake inputs

---

languages.toml

These files are commonly used in .envrc with the source_env or source_env_if_exists functions. The direnv stdlib shows an example with .envrc.private and my use of sourcegraph showed .envrc, .envrc.local, and .envrc.private as the most popular basenames for these files. It would be nice to have the common files highlighted without having to extend the config locally.

Add .envrc.local and .envrc.private to env file-types

---

runtime/themes/darcula.toml

Includes new type parameter settings as implemented by https://github.com/helix-editor/helix/pull/8660.

Add more accurate to official theme type highlighting to Darcula themes

---

languages.toml
runtime/queries/gleam/highlights.scm

Updates tree-sitter-gleam to 0.32.4.
I also updated the queries according to the ones [from tree-sitter-gleam itself](https://github.com/gleam-lang/tree-sitter-gleam/tree/v0.32.4/queries) and from a quick test everything seems to work fine.

Update gleam grammar and queries

---

helix-term/src/commands.rs
helix-term/tests/test/commands.rs

fixes the issue that lines with only spaces are getting joined as well
fixes https://github.com/helix-editor/helix/issues/8977

Join empty lines with only one space in `join_selections`

---

flake.nix

The version of the Nix package is using a placeholder (probably since bf7c4e1).
This PR fixes this issue by taking the package's version from the workspace `Cargo.toml`.

Fix version of Nix package

---

languages.toml

One of the included changes is gdamore/tree-sitter-d#22 which fixes the build of Helix when using clang as `CC`.

chore: Update tree-sitter-d

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/janet/highlights.scm

Resolves https://github.com/helix-editor/helix/issues/4617 https://github.com/helix-editor/helix/issues/4574

Add initial support for janet-lang

---

languages.toml

This merge request renames the R markdown language from `rmarkdown` to `rmd`. When I added R and R markdown support back in #1998, I mistakenly chose the `rmarkdown` name because I didn't realize it was used for anything other than the display name in Helix's statusline. Switching the name to `rmd` is necessary to fix the R language server's filetype detection, which relies on the language name (see [this line of code](https://github.com/REditorSupport/languageserver/blob/7f7605b55a6cbe05e0033b40f21e87408c06e102/R/document.R#L18)).

Change R markdown language id to fix language server filetype detection

---

runtime/themes/darcula.toml

Before:
After:
The cursor is in the exact same position in both screenshots.

Fix cursor dissapearing when over indent lines in Darcula themes

---

runtime/queries/_typescript/highlights.scm
runtime/queries/yuck/highlights.scm

This PR fix the typos seen in multiple files
```pseudo
continous > continuous
indecies > indicies
posible > possible
thhis > this
reeplace > replace
witth > with
```

fix: typo in multiple files

---

book/src/configuration.md
book/src/guides/indent.md
helix-core/src/indent.rs
helix-core/src/syntax.rs
helix-core/tests/indent.rs
helix-term/src/commands.rs
helix-view/src/editor.rs
runtime/queries/c/indents.scm

Essentially, to compute the indentation of a new line, we run an indent query both for the insertion position and for a non-empty line above. Then, we add the difference of these computed indents to the actual indentation of the line above. This makes indent queries a lot more resilient: Any error / inconsistency which applies to both lines will be canceled out, e.g.:
- Incorrect / Incomplete indent queries. In particular, incomplete indent queries are no longer worse than no indent queries with this change. This should also make it easier to contribute new languages since one can start by adding a few simple captures and then gradually add more.
- Incorrect parsing of the syntax tree by tree-sitter (e.g. if the code is incomplete)
- Different formatting styles where only one can …

Consider actual indentation of previous line for smart indent

---

book/src/generated/typable-cmd.md
helix-core/src/indent.rs
helix-term/src/commands/typed.rs

Closes https://github.com/helix-editor/helix/issues/9082

fix `:indent-style` crash

---

book/src/configuration.md

Hello, first-timer here 👋
Just wanted to add this since the documentation didn't mention much about .ignore files and did state nothing about helix-specific ignore files. But now, the `[editor.file-picker]` section has a nice addition to it:
This PR is relevant to #8099 and #7423.

book: Describe usage of `.ignore` and helix-specific ignore files in `[editor.file-picker]` section

---

helix-lsp/src/client.rs

see https://github.com/microsoft/language-server-protocol/issues/288 for details
fixes #9034 and https://github.com/helix-editor/helix/discussions/8305
I tested that this does fixes the issues but it would be great if @akhilman could also confirm

when text document sync capability is only kind send didSave without text

---

languages.toml

Add Apache Avro schema file extension to the list of JSON file types.
[(See here.)](https://avro.apache.org/docs/1.11.1/#schemas)

Add Avro schema file support

---

runtime/themes/noctis.toml

Take closer to original theme (vscode). Previously it failed to highlight differently some keywords, and there were some other quirks.

theme: update noctis

---

languages.toml

`.glif` files are standard files in the type design industry. From the Unified Font Object specification website:
> The Glyph Interchange Format (GLIF) is a simple and clear XML representation of a single glyph. GLIF files typically have a .glif extension.
https://unifiedfontobject.org/versions/ufo3/glyphs/glif/

Add .glif to XML file-types

---

book/src/languages.md
helix-core/src/diagnostic.rs
helix-core/src/syntax.rs
helix-core/src/transaction.rs
helix-term/src/application.rs
helix-view/src/document.rs
languages.toml

Fixes #701
This PR adds a configuration option (`persistant-diagnostic-sources`) that allows helix to ignore some diagnostics in `publishDiagnostic`. This option takes affect if all diagnostics from a single `lsp_type::Diagnostic::source` are identical to the last list of diagnostics received `publishDiagnostic` for this source. In that case (If the `source` is part of the `persistant-diagnostic-sources` list) all these diagnostics are ignored and instead, the "old" diagnostics for that source are maintained.
Helix already automatically updates the position of diagnostics based on edits so by keeping the existing diagnostics around we can use this mapping mechanism of helix if the server doesn't map long-lived diagnostics through changes itself.
`rust-analyzer` is a good example here …

Track long lived diagnostics inside helix

---

Cargo.lock
helix-vcs/Cargo.toml

Basic maintenance, as it turned out there was no breaking change for `helix`' usage.'

build(deps): bump gix from 0.56.0 to 0.57.0

---

languages.toml

Currently, typing a single quote in a `.scm` file "helpfully" auto- completes a closing quote. This is because there is no auto-pairs section in the languages.toml. This commit adds that.

Add auto-pairs to scheme language support

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/hocon/highlights.scm
runtime/queries/hocon/indents.scm

Adds support for [HOCON](https://github.com/lightbend/config/blob/main/HOCON.md) configuration language (highlights and indents).

Add HOCON language support

---

book/src/generated/lang-support.md
runtime/queries/scala/textobjects.scm

This PR adds textobject query support for Scala. Supports queries for functions, classes, parameters and comments.

Add textobject queries for Scala

---

runtime/themes/tokyonight.toml
runtime/themes/tokyonight_day.toml
runtime/themes/tokyonight_moon.toml
runtime/themes/tokyonight_storm.toml

Hey there!
After seeing some [auto-generated Helix themes](https://github.com/folke/tokyonight.nvim/tree/main/extras/helix) by folke in his `neovim` tokyonight repository, I decided to update Helix's themes accordingly.
I carefully went through everything and landed on a clean, best-of-both-worlds result which I think is a nice improvement from the previous versions. I've added the two missing themes, `tokyonight_moon` and `tokyonight_day`, and updated my email address.
Here are some screenshots below.
If you see any mistake or improvement to make, feel free to contact me or make any changes!
Cheers!

Update tokyonight themes

---

book/src/generated/lang-support.md
runtime/queries/protobuf/textobjects.scm

Given `message Foo {string s = 1;}`
- `mat` selects `message Foo {string s = 1}`
- `mit` selects `{string s = 1;}`
Given `service SearchService { rpc Search(Req) returns (Resp); }`
- `mit` or `mat` selects `Req` or `Resp`
- `mif` or `maf` selects `rpc Search(Req) returns (Resp);`
- `mit` selects `{ rpc Search(Req) returns (Resp); }`
- `mat` selects `service SearchService { rpc Search(Req) returns (Resp); }`

Add textobject queries for protobuf grammar.

---

book/src/install.md

Currently, the documentation doesn't indicate users can compile Helix without building grammars
Add instructions on how to compile without compiling grammars to the install doc

Info on how to skip grammar build when building from source

---

languages.toml

fix build error: 'error: Server does not allow request for unadvertised object 793d58266924e6efcc40e411663393e9d72bec87'

feat: update wren tree-sitter grammar

---

runtime/themes/ttox.toml

I've made a small theme that should play well with most terminals, including Terminal.app on macOS. This theme has no explicit `ui.background` which means that if you were to use something like Terminal.app, it automatically handles dark and light mode for you.
Here are a couple of screenshots

runtime/themes: adding "ttox" theme

---

helix-view/src/document.rs

Closes #9175
Normal diagnostics can be removed when all the text they cover has been removed.
This is not the case for zero width diagnostics as these are not attached to any
particular text. These diagnostics can not be automatically dismissed and must
be mapped as a point instead of as a range to avoid that.

don't automatically dismiss zero width diagnostics

---

helix-term/src/commands/lsp.rs

Previously we always showed the prompt even if the current document didn't have a language server that could perform a rename. For example we showed a rename prompt even when using `<space>r` in a scratch buffer.
Instead we should check the document's language servers to see if any supports a rename and bail if there are none.
This was originally https://github.com/helix-editor/helix/issues/6249 (fixed in https://github.com/helix-editor/helix/pull/6257) but regressed in https://github.com/helix-editor/helix/pull/2507

Check for rename support before showing LSP rename prompt

---

helix-term/src/ui/editor.rs

closes #9181
This change effectively reverts #3508 and #3633.
When a view is changed we must make history commits (and ensure that
the cursor is in view) for the newly focused view. Not the old view.
We already create a history commit on view change so the old view should not need them (the current solution was inadequate for that case anyway since it didn't handle multiple view changes).
These changes were originally introduced to fix mode switch hooks.
However, the mode switch hooks have been moved elsewhere so that concern
no longer applies. In particular, because modes are now editor-wide
and not per view and also because view switches now always reset the
editor back to normal mode.
I tested all the reproduction cases from back in the day and unsurprisingly all of them do not cause …

update history of a newly focused view

---

helix-core/src/syntax.rs
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/commands/typed.rs
helix-term/src/ui/editor.rs
helix-term/src/ui/picker.rs
helix-term/src/ui/statusline.rs
helix-view/src/document.rs
helix-view/src/editor.rs

I've noticed, that diagnostics that are sent from the language server aren't propagated when opening a document (via `helix_view::Document::open`). So that the language server needs to send a `PublishDiagnostics` again to populate the document with diagnostics. This can take some time (noticed with rust-analyzer), when opening a file via the workspace diagnostic picker (if it is sent at all). 
This PR should ensure that diagnostics that are already in the editor instance are propagated when opening a document.
This has the additional advantage, that diagnostics can be rendered directly in the workspace diagnostic picker, when the file/buffer isn't open yet.

Initialize diagnostics when opening a document

---

helix-view/src/input.rs

Keymaps that use the shift modifier and a lowercase ascii character should be equivalent to keymaps that use just the uppercase of that ascii character. We can normalize key events as we parse them out of strings so that both representations parse to the same event. This allows mapping keys like `C-S-r` which previously could only be bound by `C-R`.

Normalize `S-<lower-ascii>` keymaps to uppercase ascii

---

helix-term/src/commands/lsp.rs
helix-term/src/commands/typed.rs
helix-view/src/editor.rs

this fixes bugs when applying workspace edits with lsp to a view where the most recent selection range is outside the current document or when adding a newline/formatting during write all in the same situation
fixes https://github.com/helix-editor/helix/discussions/9157 and fixes #6752
I decided to sync the view when getting the id instead of calling sync when applying the transaction. I am not sure if I put the utility function in the correct place, I did have to take the tree instead of the editor because rust was giving me error for passing the editor within the closure in write-all, which I wasnt able to figure out
(I think we might be able to use this function in reload-all as well, though it already properly handles this)

make sure to sync views when applying edits to unfocused views

---

Cargo.lock
helix-core/Cargo.toml

Reverts helix-editor/helix#9281
Ahash 0.8.7 regressed its MSRV to 1.72 for aarch64 builds. We don't really loose much from reverting (changes are mostly relevant to rustc bootstrap) so lets fix the build for those platforms. We don't have an aarch64 CI yet hence it wasn't caught.
ref https://github.com/tkaitchuck/aHash/issues/195

Revert "build(deps): bump ahash from 0.8.6 to 0.8.7"

---

languages.toml

Sourcehut has outages occasionally that cause the CI and from-source builds to fail. It also doesn't setup redirects when a user renames themselves, so if a user that publishes a tree-sitter grammar we use changes their sourcehut name then it breaks the build and any prior builds using that grammar.
For now let's remove them from the default build. It's a bandaid over a larger reliability and trust problem with the grammar repositories but it should fix the build for now.

Remove sourcehut tree-sitter grammars from default build

---

grammars.nix

https://github.com/helix-editor/helix/commit/17dd102e5cccbb2a9a0f0224af63e52f3dab846b marked some grammars as "do not use", but the nix flake doesn't respect this setting. This is my attempt to rectify this situation.

Make nix flake respect unused grammars

---

Cargo.lock
helix-core/Cargo.toml
helix-core/src/path.rs
helix-core/tests/path.rs

Closes https://github.com/helix-editor/helix/issues/7458
Successor to #7658, which I messed up somehow.

Change path normalization strategy to not resolve symlinks

---

helix-core/src/match_brackets.rs

fixes #9327
This crash was caused by two (if you count upstream 3) separate bugs:
* the TS match bracket code would try to perform plaintext matching on empty nodes if there were any at the cursor
* the plaintext bracket matching code crashes when used at the eof character (always for empty files)
Fixing the first bug alone is not enough to fix the crash since TS produces only an error node at (0, 0) and apparently if there is no node within the requested subrange TS returns the original range (I consider this a bug in TS but maybe its intentional?).  for now I simply request a range with at least a byte length of 1 (TS doesn't care about codepoint alignment) to avoid empty nodes messing with plaintext bracket matching. The TS bug doesn't matter too much since the rest of the code now …

fix crashes in match bracket code

---

Cargo.lock
Cargo.toml
book/src/guides/indent.md
book/src/guides/injection.md
helix-core/src/indent.rs
helix-core/src/syntax.rs
runtime/queries/tsq/highlights.scm

* query capture names now return `&str`s rather than `String`s
* the `#any-of?` predicate is now supported
I've also switched to our fork after fast-forwarding it to the latest master. The plan will be to publish a release to Cargo of our tree-sitter fork (with no changes to the library) right before the next Helix release.

Bump tree-sitter to latest master

---

helix-core/src/syntax.rs
helix-term/src/commands/typed.rs

`:tree-sitter-subtree` could previously only print subtrees of nodes in the root injection layer. We can improve on that by finding the layer that contains the given byte range and printing the subtree within that layer. That gives more useful results when a selection is within an injection layer.
For example in a markdown file:
```markdown
One
<h1>
<div>
<p>Foo</p>
</div>
Two
<div>
<p>Bar</p>
</div>
</h1>
Three
```
Selecting the overall document will show the root layer's subtree while selecting a part within the injections like `<p>Foo</p>` will show that subtree within the HTML layer. This works even with combined injections, for example selecting around the `h1` tags.

Select subtree within injections in `:tree-sitter-subtree`

---

book/src/install.md

I have tried to install helix from source, including following the instructions at: https://docs.helix-editor.com/install.html#configuring-helixs-runtime-files . I am on Ubuntu 22.04, and I tried to install the latest master branch.
I hit 2 issues:
- 1: if I understand well, in bash, in order to export an env variable, the ```export``` keyword is needed; otherwise, the variable is not exported to child processes, and helix does not seem to receive the env variable (inspecting the ```hx --health``` output without the ```export``` keyword, I cannot see the added path from ```HELIX_RUNTIME``` listed).
- 2: it seems that helix is not able to expand ```~```. I.e., if I use in my ```.bashrc```: ```export HELIX_RUNTIME="~/src/helix/runtime"```, I then get a not recognized path:
```sh …
```

Fix export instructions in installation doc

---

helix-core/Cargo.toml

We use `3.9` already in our dependency tree

update tempfile dev-dependency to 3.9

---

languages.toml

[PureScript's rewritten package manager / build system, spago@next](https://discourse.purescript.org/t/announcing-spago-next-a-purescript-rewrite-registry-support-and-more/3737), has moved from `spago.dhall` to `spago.yaml` config files.
When [purescript-language-server](https://github.com/nwolverson/purescript-language-server) is launched in a directory that does not appear to be a PureScript (spago) project, it tries to ask the user to resolve this issue. [In Helix, this causes purescript-language-server to exit immediately](https://github.com/helix-editor/helix/pull/5492):
```
2024-01-16T22:47:18.699 helix_lsp::transport [ERROR] purescript-language-server err <- "ResponseError: Method not found: window/showMessageRequest\n"
```
This change adds support for new `spago.yaml` config files …

Support PureScript's new spago.yaml configs

---

helix-lsp/src/transport.rs
helix-term/src/application.rs

I've been struggling to get c# + omnisharp working reliably with helix. Omnisharp [occasionally sends messages with malformed json](https://github.com/OmniSharp/omnisharp-roslyn/issues/2594), which causes the helix LSP event listener thread to die. After this happens, the LSP functionality within helix no longer works, even though omnisharp is still up and running. If I try to close helix at this point, it hangs for a bit and writes an lsp shutdown timeout log. If I run `:lsp-restart`, a second instance of omnisharp is started, leaving the first one running in the background.
This PR updates the recv function in helix-lsp::transport to request that an LSP is exited after it sends a message that cannot be parsed. This causes the `Language server exited` message to be displayed in the …

Exit a language server if it sends a message with invalid json

---

runtime/themes/sonokai.toml

Added `"ui.virtual.whitespace" = { fg = "grey_dim" }` line

Fixed look of inlay hints in sonokai theme

---

Cargo.lock
Cargo.toml
helix-core/Cargo.toml
helix-core/src/lib.rs
helix-loader/Cargo.toml
helix-loader/src/lib.rs
helix-lsp/Cargo.toml
helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-stdx/Cargo.toml
helix-stdx/src/env.rs
helix-stdx/src/lib.rs
helix-stdx/src/path.rs
helix-stdx/tests/path.rs
helix-term/Cargo.toml
helix-term/src/application.rs
helix-term/src/commands.rs
helix-term/src/commands/dap.rs
helix-term/src/commands/lsp.rs
helix-term/src/commands/typed.rs
helix-term/src/main.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/picker.rs
helix-term/tests/test/commands/write.rs
helix-term/tests/test/splits.rs
helix-view/Cargo.toml
helix-view/src/document.rs
helix-view/src/editor.rs

We've talked internally about introducing a stdx crate similar to [rust-analyzer's](https://github.com/rust-lang/rust-analyzer/tree/master/crates/stdx). It should contain some of the functionality that extends Rust's standard library and can be a dependency of any other crate.
I started small in this PR with the path operations from `helix-core`. Canonicalizing and normalizing paths is useful in `helix-loader` as well, for example to expand tildes and normalize the path optionally provided in the `HELIX_RUNTIME` environment variable. This PR is mostly moved lines except for adding canonicalization/normalization/tilde-expansion to helix-loader (see the second commit).
In the future we could move other things like `helix-view/src/base64.rs`. @pascalkuthe also mentioned moving …

Add a helix-stdx crate for stdlib extensions

---

helix-tui/src/backend/crossterm.rs

match statement instead of crash for https://github.com/helix-editor/helix/issues/9336

Handle failure when enabling bracketed paste

---

helix-core/src/syntax.rs

I noticed a small typo in the error message when no configured language server supports goto-reference. This pull request fixes it.

Fix typo in string representation of GotoReference

---

book/src/generated/lang-support.md
runtime/queries/bash/highlights.scm
runtime/queries/css/indents.scm
runtime/queries/make/indents.scm

[highlights(bash): rework keywords section](https://github.com/helix-editor/helix/commit/579e55d7d45867d8e9a9738fa0c9d04abeab93e2) 
* Use more specified scope when possible for keywords like @keyword.repeat.
* Add more keywords like "local" or "unsetenv".
Limitation:
* Bash doesn't allow you to have a local variable outside of a function, so maybe we need to have better queries to not highlight the local in this case.
* If we name a function with a keyword (such as unset or local), it will use the highlight scope "keyword" instead of "function".
[indents(css, make): add basic queries](https://github.com/helix-editor/helix/commit/731dc49d1d694f03dfca180977ffc0b00d58ee7a) 
* Despite the fact that queries look simple, they improve indentation in some edge cases that helix couldn't handle …

bash, make, css: highlight and indent queries improvement

---

languages.toml
runtime/queries/scala/highlights.scm
runtime/queries/scala/textobjects.scm

Updates Scala grammar to the [latest commit in master](https://github.com/tree-sitter/tree-sitter-scala/tree/7891815f42dca9ed6aeb464c2edc39d479ab965c).
I verified quickly that everything seems still working.
Fixes multiple things, at least:
- Scala 3 [braceless](https://docs.scala-lang.org/scala3/reference/other-new-features/indentation.html) try-catch highlighting in one-liner catch clause
- Enables text object queries for block lambdas and Scala 3 [fewer braces](https://docs.scala-lang.org/sips/fewer-braces.html) lambdas
- Highlights scala-cli [using directives](https://scala-cli.virtuslab.org/docs/reference/directives/)

Update Scala tree-sitter grammar

---

runtime/themes/onedark.toml
runtime/themes/onedarker.toml

Highlight the active buffer more clearly in onedark and onedarker themes.
Before:
After:

Add bufferline config for onedark & onedarker themes

---

book/src/generated/lang-support.md
runtime/queries/dart/textobjects.scm

I added queries for text objects for dart.
To do it, I looked at what was done in queries for rust. And I looked with `:tree-sitter-scopes` and `:tree-sitter-subtree` in my dart code. I works quite well for me (and should work well for others too, unless there is parts of the grammar not covered in my dart code)
For the "test" object, I used an alternation with `#eq?` predicates, because I could not make it work with one `#any-of?` predicate (it matched any name). I don't know if I missed something and it could work, or if I missed something in my understanding and that it cannot work

Add text object queries for dart

---

Cargo.lock
helix-dap/Cargo.toml
helix-dap/src/client.rs
helix-dap/src/lib.rs
helix-loader/Cargo.toml
helix-loader/src/grammar.rs
helix-lsp/Cargo.toml
helix-lsp/src/client.rs
helix-lsp/src/lib.rs
helix-stdx/Cargo.toml
helix-stdx/src/env.rs
helix-term/Cargo.toml
helix-term/src/health.rs
helix-view/Cargo.toml
helix-view/src/clipboard.rs
helix-view/src/document.rs
helix-view/src/editor.rs
helix-view/src/env.rs
helix-view/src/lib.rs

We use `which::which` in many crates, so `which` was a separate dependency across all of them. We can centralize `which` into the stdx crate so it's easy for all crates to depend on it.
I also moved the rest of `helix-view/src/env.rs` into helix-stdx's `env` module since it only contained a thin wrapper around `which` and `std::env`.
This also updates `which` to 6.0.0, so it closes #9406

Re-export `which` from `helix-stdx::env`

---

helix-core/src/syntax.rs

Fixes https://github.com/gleam-lang/tree-sitter-gleam/issues/81
This is a part of https://github.com/tree-sitter/tree-sitter/pull/1602 - I forgot to make this change to Helix after making it to tree-sitter-cli. If you have a pattern that has multiple captures and uses the `#is-not? local` predicate:
```scm
; runtime/queries/gleam/highlights.scm
((field_access
record: (identifier) @namespace
field: (label) @function)
(#is-not? local))
```
the entire pattern should not apply if the `@namespace` (i.e. the first) capture is not defined locally. To do that we need to remove the match so that the captures iterator doesn't return the remaining captures from the match in the future.

highlighting: Gate multiple captures behind `#is-not? local` predicates

---

helix-term/src/commands/lsp.rs

When a symbol with no references is <kbd>g</kbd><kbd>r</kbd>'d on, the message shown is `No definition found.` Make it `No references found.`
Achieves this by introducing empty container checks at call sites rendering one of the patterns redundant. Another possible solution is to pass the error message as another argument.

Fix error message shown for goto references

---

languages.toml

`.config/helix/ignore` and `.helix/ignore` support was added in https://github.com/helix-editor/helix/pull/8099

lang(git-ignore): add `helix/ignore` to git-ignore file types

---

runtime/themes/onedark.toml
runtime/themes/onedarker.toml

This is just my opinion, but with the colored backgrounds, the mode is much easier to read when bold (like the catppuccin themes).
before:
after:

Make status line modes bold for theme onedark

---

runtime/queries/scala/injections.scm

Matches SQL strings from (at least) three popular Scala database libraries:
- [Doobie](https://tpolecat.github.io/doobie/docs/04-Selecting.html#reading-rows-into-collections)
- [Quill](https://zio.dev/zio-quill/extending-quill#raw-sql-queries)
- [Slick](https://scala-slick.org/doc/stable/sql.html)
Injection query matches this kind of syntax:
```scala
val query1 = sql"SELECT foo FROM bar WHERE baz IS NOT NULL"
```
For some reason the injection query does not reliably work for multiline strings:
I'm not sure whether this is a problem with tree-sitter-scala, tree-sitter-sql, Helix, or the injection query itself. Helix shows identical subtrees for `query1` and `query2`. To my understanding it should thus highlight them equally.
Nevertheless having some highlighting for inline SQL is an …

Include interpolated SQL strings in Scala injection queries

---

helix-core/src/match_brackets.rs
helix-core/src/movement.rs
helix-core/src/syntax.rs
helix-term/src/commands/typed.rs

Previously we used the root syntax tree for bracket matching. We can use the new functionality in `Syntax` for finding the correct syntax tree for a given byte range though so we use the correct syntax tree within injections. This improves bracket matching behavior within HTML injections like script or style tags for example.
Fixes #9423

Respect injections when using the syntax tree's root node

---

runtime/queries/scala/highlights.scm

Updates Scala queries to highlight abstract methods in traits and abstract classes.
Currently they are highlighted differently:
Updated queries highlight them equally:

highlight(scala): highlight abstract methods in traits and classes

---

runtime/queries/gdscript/textobjects.scm

Currently `maa` only selects parameters in a function definition.
Allow it to also select arguments inside a function call.

Add argument to textobject in gdscript

---

runtime/themes/gruvbox_light_hard.toml
runtime/themes/gruvbox_light_soft.toml

This PR adds the hard & soft contrast variants of gruvbox light theme.
ref: #7139
doc: https://github.com/morhetz/gruvbox

feat: add hard/soft contrast for gruvbox light mode

---

helix-lsp/src/client.rs
helix-lsp/src/file_operations.rs
helix-lsp/src/lib.rs
helix-term/src/application.rs
helix-term/src/commands/lsp.rs
helix-term/src/commands/typed.rs
helix-view/src/document.rs
helix-view/src/editor.rs
helix-view/src/handlers/lsp.rs

Closes #8942
Supercedes #8924
Currently, helix implements operations which change the paths of files
incorrectly and inconsistently. This PR ensures that we do the following
whenever a buffer is renamed (`:move` and workspace edits)
* always send did_open/did_close notifications
* send will_rename/did_rename requests correctly
* send them to all LSP servers not just those that are active for a
buffer
* also send these requests for paths that are not yet open in a buffer (if
triggered from workspace edit).
* only send these if the server registered interests in the path
* autodetect language, indent, line ending, ..
This PR also centralizes the infrastructure for path setting and
therefore `:w <path>` benefits from similar fixed (but without `didRename` and `willRename`).
I also used the …

make path changes LSP spec conformant

---

helix-term/src/commands.rs
helix-view/src/editor.rs

Fixes #9443
Uses the relative postion of the anchor and the head of a selection to determine whether to shift the selection or to extend it.

Use range positions to determine insert_newline motion

---

runtime/themes/github_dark.toml
runtime/themes/github_light.toml

Turning on a ruler does not show a visible ruler line for the GitHub themes. This change renders rulers using the `canvas.subtle` color. This matches the color used for the `cursorline` and creates a visible ruler that fits the theme.

Set ui.virtual.ruler background for GitHub themes

---

Cargo.lock
helix-vcs/Cargo.toml
helix-vcs/src/git.rs

Use gix pipeline filter instead of manual crlf implementation

---

runtime/queries/go/injections.scm

Ported from nvim.[^1]
[^1]: https://github.com/nvim-treesitter/nvim-treesitter/blob/f2119df35cdcdb0c6c9bf791a04000d4d131cef7/queries/go/injections.scm

feat(queries): regex injection for golang

---

languages.toml
runtime/queries/nu/highlights.scm

[https://github.com/nushell/tree-sitter-nu](tree-sitter-nu) has seen many updates since the version currently specified in `languages.toml` and the language itself has changed to the extent that my modern configs (for 0.89.0) don't really parse well anymore, particularly with commands like `def` now taking flags like `--wrapped` and `--env`.
This commit specifies the latest version, and also updates the queries.

Update grammars for Nushell to rev 358c4f50

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/tact/highlights.scm
runtime/queries/tact/indents.scm
runtime/queries/tact/injections.scm
runtime/queries/tact/locals.scm
runtime/queries/tact/textobjects.scm

About queries:
* `locals.scm` are copied from [tact-lang/tree-sitter-tact](https://github.com/tact-lang/tree-sitter-tact)
* `highlights.scm`, `textobjects.scm`, `injections.scm` and `indents.scm` are tailor-made for 🧬 Helix!
About the language:
https://tact-lang.org

feat: Add `Tact` language support

---

runtime/queries/scala/highlights.scm
runtime/queries/scala/textobjects.scm

- Simplify function highlighting
- Highlight extension methods
- Textobject query (`mia`/`maa`) for class/trait constructor parameters/arguments
- Textobject query (`mif`/`maf`) for Scala 3 braceless lambdas

Improve tree-sitter queries for Scala

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/unison/highlights.scm
runtime/queries/unison/indents.scm

Unison's syntax changes and `unique` is now optional, updated grammar rev and tweaked the queries in this PR.

Update Unison tree-sitter grammar for type changes and add indent queries

---

runtime/queries/go/highlights.scm

Adjust golang highlight queries for float numeric type and documentation comments. (based on nvim https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/go/highlights.scm)

feat(languages): golang comments and numeric types

---

runtime/themes/zed_onedark.toml
runtime/themes/zed_onelight.toml

Official colors used are now [publicly available](https://github.com/zed-industries/zed/blob/main/assets/themes/one/one.json)
Modified the theme to more accurately reflect the actual colors being used.

Update colors used for zed themes

---

helix-term/src/ui/prompt.rs

fix division by zero when prompt completion area is too small

---

helix-term/src/ui/menu.rs
helix-term/src/ui/popup.rs

Fix scroll track

---

Cargo.lock
book/src/languages.md
helix-core/Cargo.toml
helix-core/src/config.rs
helix-core/src/syntax.rs
helix-core/tests/indent.rs
helix-term/src/application.rs
helix-term/src/health.rs
helix-term/src/main.rs
helix-term/tests/test/commands/write.rs
helix-term/tests/test/helpers.rs
languages.toml

One of the issues I've run into with Helix (coming from nvim) is the ability to specify file types based on a full path pattern and not just a suffix. This is necessary for file types like YAML which might need different tooling based on their filesystem context (examples include GitHub Actions and Helm charts) or things like Dockerfile (a common paradigm is to add a suffix for different use cases, e.g. `Dockerfile.dev`).
It seems that this issue was already discussed in #2455; not sure if there are plans to introduce a different paradigm for file type matching which solves it without globs but I think it's a rather necessary feature either way. Other options would include:
- adding a separate prefix option => this makes the file-types even more complicated and also might end up with …

Add glob file type support

---

languages.toml
runtime/queries/swift/highlights.scm

This updates `runtime/queries/swift/highlights.scm`, adding `any` and `await` as keywords. It also removes a todo that was already done, and updates the upstream-comment on Line 1 with newest commit ID for `tree-sitter-swift (main)`.
The `languages.toml` file was also updated, setting Swift's `source.rev` to the newest commit ID for `tree-sitter-swift (with-generated-files)`.
There are a handful of other issues with Swift syntax-highlighting, but they're all upstream, so I'll summarize them here, and open issues with tree-sitter/tree-sitter-swift:
- `defer` should be a keyword
- `inout` is highlighted, but `borrowing` and `consuming` are not
- `Self` and `self` should be highlighted the same way (`Self` is also a builtin variable)
- the new if- and switch-expressions are not parsed …

Updated Swift grammar, adding 'any' and 'await' keywords.

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/cel/highlights.scm
runtime/queries/spicedb/highlights.scm
runtime/queries/spicedb/injections.scm
runtime/queries/spicedb/tags.scm

CEL (Common Expression Language) is a non-Turing-Complete language created at Google for embedding into programs. It's used in a variety of projects such as Kubernetes and SpiceDB.
SpiceDB is a popular, open source authorization system inspired by the system internal at Google, Zanzibar.
This PR adds language/grammar support for both of these projects.
I'm not sure the CEL highlighting is working -- I might need some help with writing custom queries for it. The SpiceDB grammar includes queries that target Helix.

languages: add CEL, SpiceDB schema language

---

languages.toml

Per the [documentation](https://just.systems/man/en/chapter_57.html?highlight=format#formatting-and-dumping-justfiles) `just --dump` can be used to output a formatted representation of the justfile in the current working directory to stdout.

feat(languages): add formatter for just, fish

---

languages.toml

`build.zig.zon` is what 0.11.0 uses for external dependencies.  The syntax is a subset of zig and can be highlighted and formatted like normal zig code.

Add "zon" file type to zig language section

---

book/src/configuration.md

Before there was no document about what the `diff` gutter is displaying
or what the colors mean.
These docs clarify it's a `git` diff and makes it easier to
cross-reference the theme if you aren't sure what the colors mean or
want to change them.

docs: Document what the `diff` gutter symbol does

---

languages.toml

Odin's language server also comes with a formatter, so it would be nice to make use of it.

Add support for Odin's formatter

---

Cargo.lock
helix-core/src/syntax.rs
helix-core/tests/indent.rs
helix-lsp/Cargo.toml
helix-lsp/src/lib.rs
helix-term/src/application.rs
helix-term/src/ui/lsp.rs
helix-term/src/ui/markdown.rs
helix-term/src/ui/mod.rs
helix-term/src/ui/picker.rs
helix-term/src/ui/prompt.rs
helix-view/src/document.rs
helix-view/src/editor.rs

This PR attempts to fix #9398 
`syn_loader` was replaced rather than interior value being replace, 
old value was still being referenced and not updated after `:config-refresh`. 
By using `ArcSwap` similarly to `config`, each `.load()` call will return the most updated value.
1. Open the helix repo in Helix and open a document.
1. Add a custom language config for `rust-analyzer` in `languages.toml`.
```
[language-server.rust-analyzer.config]
cargo.features = "all" 
rust-analyzer.check.command = "clippy"
+ rust-analyzer.inlayHints.typeHints.enable= false
+ rust-analyzer.inlayHints.parameterHints.enable= false
+ rust-analyzer.inlayHints.chainingHints.enable= false
```
1. `:config-reload` and `:lsp-restart`
1. page-up/down to trigger re-rendering
1. inlay hints should now be disabled, lsp …

fix lsp config reload

---

helix-term/src/commands.rs

Fixes #9619.
Adds the history persistence and cursor position in view that was missed in #5790.

Add changes to history when paste-replacing

---

helix-term/src/keymap.rs
helix-term/src/ui/editor.rs

This will allow using numbers as second key event. Closes #8113

Allow numbers as second input event

---

languages.toml
runtime/queries/erlang/highlights.scm

This update fixes parsing for some newer accepted EEPs:
* <https://www.erlang.org/eeps/eep-0058> map comprehensions
* <https://www.erlang.org/eeps/eep-0064> triple quoted strings
* <https://www.erlang.org/eeps/eep-0066> sigils
Also now that glob file-types are supported I've added `*.app.src` which are files that build tools like rebar or make will generate into `.app` files.

Bump tree-sitter-erlang, add `*.app.src` file-type

---

helix-view/src/handlers/dap.rs

Fix #4683.
xdebug.php-debug-1.34.0 does not provide a line value for this event, this change fixes the issue for me
```
helix_dap::transport [INFO] <- DAP event Breakpoint(Breakpoint { reason: "changed", breakpoint: Breakpoint { id: Some(6), verified: false, message: None, source: None, line: None, column: None, end_line: None, end_column: None, instruction_reference: None, offset: None } })
```

Remove unwrap on line option, preventing DAP crash

---

runtime/themes/sonokai.toml

The Sonokai theme had some inconsistencies, so I fixed some of them.
* Copied the palette exactly from https://github.com/sainnhe/sonokai/blob/master/autoload/sonokai.vim
* Used the following two resources to pick correct colors for different scopes:
1. https://www.sainnhe.dev/post/contributing-guide/#sonokai
2. https://github.com/sainnhe/sonokai/blob/master/colors/sonokai.vim
Edit: Changes I made as listed in the git commit:
* Make constants white (1)
* Make builtin variables purple (1)
* Make members orange (1)
* Make labels red (2)
* Make operators red (1)
* Make all punctuation grey (2)
* Make builtin functions and macros green (2)
* Make diff delta blue (2)
* Make cursor match bg4 (2)
* Make visible whitespace bg4 (2)

Fix Sonokai theme to better match original

---

runtime/queries/dart/textobjects.scm

Change queries for `@parameter` for Dart to match a single parameter (instead of all of them), and add queries to match arguments and type parameters

Improve textobjects for parameter/argument for Dart

---

languages.toml

Tmux and tmux.conf are used widely among Helix users. Having the tmux.conf file not have any syntax highlighting by default is (IMO) not ideal for an editor that otherwise "just works". Feel free to close without merge if you disagree, but I thought it's better I bring this up and give this change a chance to be merged.

Add tmux.conf glob as a bash file type

---

book/src/keymap.md
helix-core/src/movement.rs
helix-term/src/commands.rs
helix-term/src/keymap/default.rs
helix-term/src/ui/editor.rs

Solves #7639 - adds a new scroll function so that the cursor and page jump by the same distance vertically. Assigns this to C-u and C-d, similar to neovim. 
The consistent distance between cursor and view top would break if the cursor were to land on a whole line of virtual text- the cursor would be placed on the closest non-virtual text above where it landed. Meaning the view and cursor would not have jumped the same vertical distance. 
This should be pretty rare though- unless you are using #6417 and have a ton of error messages. I could refactor this nvim-scroll function though- to first calculate how many lines the cursor jumped (eg the cursor tried to jump by half a page but could only jump by half a page -1 line due to virtual text) and then move the view by exactly this number. …

Scroll cursor and page together (neovim-like scrolling)

---

runtime/themes/monokai_soda.toml

I've been using this theme for about a year and haven't really touched it in a while, so I consider it pretty stable.
Monokai Soda is a fairly old theme around from the TextMate era. It's not as popular, but exists for every text editor, shell, etc that I've used.
Some screenshots:

themes: add monokai soda

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/docker-compose/highlights.scm
runtime/queries/docker-compose/indents.scm
runtime/queries/docker-compose/injections.scm

Also add luajit as a shebang of lua

Add docker-compose language

---

helix-term/src/ui/editor.rs
helix-view/src/editor.rs

Resolves #5425. Design rationale detailed in #5425 comments.
I'm not entirely sure whether this change is desired, but am still submitting this optimistically as I think it makes a lot of sense. I use Helix on a touch screen device (phone) sometimes and find this extremely useful for selecting code blocks as touches are easier to do than key strokes on such devices. It annoys me that currently the only way to extend a selection would be to use a keyboard.
This PR should improve the mouse UX. It's now possible to extend the primary selection with mouse clicks. The original drag-to-yank behavior is also retained.
With this PR, the editor no longer collapses all selections into a single point on mouse clicks unconditionally. Instead, it extends the primary selection to the point click when …

Make mouse click extend selection in select mode

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/groovy/highlights.scm
runtime/queries/groovy/injections.scm

Closes https://github.com/helix-editor/helix/issues/4211
Took queries from [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/groovy).

Add Groovy grammar

---

helix-lsp/src/client.rs
helix-term/src/ui/completion.rs
helix-term/src/ui/editor.rs

Previously we used the IdleTimeout event to trigger LSP `completion/resolveItem` requests. We can now refactor this to use an event system hook instead and lower the timeout.
Connects #9629

Use a hook for resolving completion items

---

contrib/completion/hx.bash

I made an PR earlier (#9702) to fix issue #9701, but it seems that I forgot to wrap a `$2` in quotes and escape the quotes in some of the lines above. With this mistake, most of the behavior when filenames include spaces still works properly, but some problems still occur when multiple file paths are similar and contain spaces.
- Assume the current directory contains the file "foo bar.txt" and "foo biz.txt"
- `hx foo\ ba` + `Tab` autocompletes to `hx foo\ b`
- `hx foo\ biz` + `Tab` autocompletes to `hx foo\ b`
- `hx foo\ ba` + `Tab` autocompletes to `hx foo\ bar.txt`
- `hx foo\ biz` + `Tab` autocompletes to `hx foo\ biz.txt`
- This change can be tested by replacing the contents of `/usr/share/bash-completion/completions/hx` with the new contents of `contrib/completion/hx.bash`.

Completely fix bash autocomplete handling of filenames with spaces

---

.github/workflows/build.yml

From searching online, it doesn't seem like there is a way to do this by default, so I just added what was suggested in the issue :)
Closes #9591

Don't run scheduled builds on forks

---

helix-term/src/application.rs
helix-term/src/commands/lsp.rs
helix-view/src/editor.rs

URIs need to be normalized to be comparable. For example a language server could send a URI for a path containing `+` as `%2B` but we might encode this in something like `Document::url` as just `+`. We can normalize the URI straight into a PathBuf though since this is the only value we compare these diagnostics URIs against. This also covers edge-cases like windows drive letter capitalization.
Closes #3267 
Also see https://github.com/helix-editor/helix/discussions/7321 (thanks for the pointer on this @pascalkuthe!)

LSP: Key diagnostics off file path instead of URI

---

runtime/themes/tokyonight.toml

In the last commit that affected this file, the colors of tokyonight diagnostic undercurls got accidentally dropped. The effect was that those undercurls, instead of being red, yellow, blue or teal, had the color of the text above them.
Here we add the colors back in, fixing the looks of the diagnostic undercurls.

Fix colors of tokyonight diagnostic undercurls

---

languages.toml

Fix some MISSING nodes being generated by the parser that slipped through the cracks before.

slint: Update SHA of tree-sitter parser

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/fidl/folds.scm
runtime/queries/fidl/highlights.scm
runtime/queries/fidl/injections.scm

Add language support for [FIDL](https://fuchsia.dev/fuchsia-src/reference/fidl/language/language) (Fuchsia Interface Definition Language), only treesitter support.

add language fidl

---

book/src/keymap.md
book/src/languages.md
helix-core/src/comment.rs
helix-core/src/indent.rs
helix-core/src/lib.rs
helix-core/src/syntax.rs
helix-core/tests/indent.rs
helix-stdx/src/rope.rs
helix-term/src/commands.rs
helix-term/src/keymap/default.rs
languages.toml

this is an initial implementation of toggling block comments which fixes #1505 it still needs
any other feedback appreciated, this is still a draft and nothing is set in stone
some implementation notes:
- the command normalizes the commenting across the selections so if one selection is uncommented all selections get commented, this can be changed if needed
- comments surround the content of each selection ignoring whitespace when commenting and leave any whitespace surrounding block comment tokens when uncommenting
- ~~i tried to do the same thing as `find_first_non_whitespace_character` in `find_last_non_whitespace_character` but apparently `Chars` doesn't implement `DoubleEndedIterator` so I just iterate over a reversed range of chars len instead. I don't think this should have …

Toggle block comments

---

helix-term/src/ui/editor.rs
helix-term/src/ui/info.rs
helix-term/src/ui/lsp.rs
helix-term/src/ui/markdown.rs
helix-term/src/ui/text.rs
helix-tui/src/widgets/paragraph.rs
helix-tui/tests/terminal.rs
helix-tui/tests/widgets_paragraph.rs

No corresponding issue, just found it odd while reading. Feel free to reject it, but I think that cloning the whole content of a paragraph just to render it can be significant. This is not just one allocation, these are multiple allocations because `Text` is a vector of vectors of possibly owned strings.

Avoid cloning the whole paragraph content just for rendering

---

languages.toml

`pde` files are used to store programs written for Processing, and are simply Java files which are implied to use the libraries included with Processing.

Add support for pde files

---

languages.toml
runtime/queries/lua/highlights.scm

repo has moved, use new URL and the rev of the latest release (v0.0.19)
There is a more recent release of the tree-sitter-lua grammar (and new repo url, which appears to be the same repo, just moved):
https://github.com/tree-sitter-grammars/tree-sitter-lua/commit/88e446476a1e97a8724dff7a23e2d709855077f2
I'm a first-time contributor, opening this PR per request from @archseer on #9726. 
I tested locally by adding a `.config/helix/languages.toml` file with the following content (the `source =` line is the same content as this PR):
```toml
use-grammars = { only = [ "lua" ] }
[[grammar]]
name = "lua"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-lua", rev = "88e446476a1e97a8724dff7a23e2d709855077f2" }
```
Then updated the grammar:
```zsh
% hx --grammar fetch
Fetching 1 …
```

update languages.toml: tree-sitter-lua grammar

---

helix-core/src/selection.rs

closes #9752
fixes regression introduced in #9422
I forgot the way the ropey lines iterator work (despite having written it) so I didn't properly conciser that the last yielded line will never have a line terminator and used an ill-advised `unwrap_or(0)`. I cleaned up the code a bit in the process

fix split_on_newline

---

book/src/configuration.md

Document embracing smart-tab navigation.

---

book/src/generated/lang-support.md
languages.toml

I would like to add this language server. How do you all handle this? https://github.com/Feel-ix-343/markdown-oxide

feat: Add markdown-oxide language server

---

languages.toml

This fixes issue https://github.com/helix-editor/helix/issues/9703 by removing the wrong formatting command for justfiles.

Fix bug 9703 by commenting out the wrong command

---

book/src/themes.md
helix-lsp/src/client.rs
helix-term/src/ui/editor.rs
theme.toml

These are defined as [`DiagnosticTag`] in the spec. Tags are an optional part of a diagnostic that can give some extra metadata. Currently the spec only contains `Unnecessary` and `Deprecated` and it gives some hints on how to theme those keys. We can introduce some new theme keys for these tags and fall back to the diagnostic's severity highlight.
[`DiagnosticTag`]: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticTag
I mixed up the branches somehow but this is https://github.com/helix-editor/helix/pull/9767 with a slight tweak to the theming of the new keys in the default theme.
For example a deprecated diagnostic from rust-analyzer:

Support LSP diagnostic tags

---

runtime/queries/svelte/injections.scm

Reported here: https://github.com/helix-editor/helix/discussions/9623#discussioncomment-8643853
JavaScript was taking precedence because it was higher in the file

Fix precedence of svelte typescript injection

---

helix-term/src/commands.rs
helix-term/tests/test/commands.rs

Joining lines with Alt-J does not properly select the inserted spaces when the selection contains blank lines. In the worst case it panics with an out of bounds index.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 11, Rope/RopeSlice char length 10'
Steps to reproduce:
* Create a new document 
```
a
b
c
d
e
```
* % (Select all)
* Alt-J (join and select the spaces)

Fix panic when using join_selections_space

---

helix-core/src/surround.rs
helix-term/tests/test/movement.rs

1. Create a document containing `{A}`
1. C-w v # vsplit
1. gl    # goto_line_end
1. b     # move_prev_word_start
1. `     # switch_to_lowercase
1. mrm(  # surround replace
1. C-w v # vsplit
In the debug build surround_replace/delete will immedately assert with `assertion failed: last <= from', transaction.rs:597:13`. The splits and lowercase conversion are not needed to trigger the bug.
In the release build the surround becomes `)a(` and the last vsplit causes the transaction to panic.
`internal error: entered unreachable code:
(Some(Retain(18446744073709551573)))', transaction.rs:185:46`
Since the selection direction is backwards get_surround_pos returns the pairs reversed but the downstream code assumes they are in the forward direction.

Fix panic when using surround_replace/delete

---

languages.toml

Current `file-types` only supports up to a `Dockerfile.frontend` naming scheme.
With these changes `frontend.Dockerfile` now gives proper highlights and lsp actions.

feat(languages): add support for `*.Dockerfile` `file-types` naming convention

---

flake.lock

Crane fixed it upstream, but the helix flake needs an update to use the fixed version.
Prevents following warning message:
`overrideScope'` (from `lib.makeScope`) has been renamed to `overrideScope`
triggered by an outdated crane revision
Flake lock file updates:
• Updated input 'crane':
'github:ipetkov/crane/42afaeb1a0325194a7cdb526332d2cb92fddd07b' (2023-11-26)
→ 'github:ipetkov/crane/81c393c776d5379c030607866afef6406ca1be57' (2024-03-05)
• Updated input 'flake-utils':
'github:numtide/flake-utils/ff7b65b44d01cf9ba6a71320833626af21126384' (2023-09-12)
→ 'github:numtide/flake-utils/d465f4819400de7c8d874d50b982301f28a84605' (2024-02-28)
• Updated input 'nixpkgs':
'github:nixos/nixpkgs/5a09cb4b393d58f9ed0d9ca1555016a8543c2ac8' (2023-11-24)
→ …

flake.lock: Bump flake inputs to prevent a warning message

---

helix-term/src/commands.rs
helix-term/tests/test/movement.rs

Test Document
-------------
```
{{
}
}
```
Steps To Reproduce
------------------
1. 2j  # move_visual_line_down
1. C   # copy_selection_on_next_line
1. mdm # surround_delete
Debug
-----
`assertion failed: last <= from', transaction.rs:597:13`
Release
-------
`called `Result::unwrap()` on an `Err` value: Char range out of bounds: char range 18446744073709551614..18446744073709551615, Rope/RopeSlice char length 7', ropey-1.6.1/src/rope.rs:546:37`
Description
-----------
Processing the surrounding pairs in order violates the assertion the ranges are ordered. To handle nested surrounds all positions have to be sorted. Also surround_replace has to track the proper replacement character for each position.

Fix panic in surround_replace/delete nested multi-cursor

---

languages.toml
runtime/queries/comment/highlights.scm
runtime/queries/ocaml/highlights.scm

Jumped forward three years for the OCaml tree-sitter :)
Fixes #9771 for all languages.

fix: close #9771 fix comments with `(` and `)`

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/ld/highlights.scm
runtime/queries/ld/indents.scm
runtime/queries/ld/injections.scm

This pull request adds support for linker scripts. The grammar is based on the `ld/ldgram.y` file in the binutils-gdb repository located at `git://sourceware.org/git/binutils-gdb.git`. The grammar succesfully parses all `.ld` files in that repository's `ld/testsuite` directory, except two.
Here's a screenshot with the gruvbox theme:

add linker script language

---

helix-term/src/ui/prompt.rs

This makes helix behave like vim and kakoune.

helix-term: allow to backspace out-of the command prompt

---

runtime/queries/java/textobjects.scm

This allows native functions definitions and constructors to be accessible as part of goto_{next,prev}_func.
Change-Id: Ia1234004e8b38e1c5871331a38fcf4f267da935e

Add textobjects for Java native funcs and constructors

---

runtime/themes/catppuccin_mocha.toml

See https://github.com/catppuccin/helix/commit/4bf31e995ead4e5f6e8cd4a08ea0497f1d35695b

fix(themes-catppuccin): make inlay hints more legible

---

book/src/generated/typable-cmd.md
helix-term/src/commands.rs
helix-term/src/commands/typed.rs

Add a yank diagnostic command

---

helix-term/src/ui/editor.rs

We need to handle number key events differently depending on whether the count has been started or not:
* If the count has been started, any number will continue the count.
* If the count hasn't been started yet, a non-zero numeric key can start the count if it isn't bound to a command.
This supports custom bindings for any of the number keys. (Though those bindings cannot use counts.)
Fixes #9871

Handle starting and continuing the count separately

---

languages.toml

Fixes #9893.
There are only block comments in OCaml. Removed the `comment-token`.
https://github.com/helix-editor/helix/assets/64728420/a8ccdcbf-abf9-4b43-a270-6c6ca4e9d2dd

Fix comment key bind behaviour in OCaml

---

helix-term/src/commands.rs

Keybind for Extend/shrink selection up and down

---

runtime/queries/nix/highlights.scm

Related issue: #9436
I looked into injections too, ~~and most of them don't work for me (eg builders). But they don't work for me on master either, so I'm not sure what's the issue, and at least reversing doesn't seem to introduce any new breakage.~~ nevermind they seem to all work.

Reverse Nix highlights queries

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/hyprlang/highlights.scm
runtime/queries/hyprlang/indents.scm
runtime/queries/hyprlang/injections.scm

This adds support for the hyprland configuration language
---
Old picture with unadjusted highlights

Add support for hyprland config

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/jsonc/highlights.scm
runtime/queries/jsonc/indents.scm

`jsonc` is currently part of the `json` language definition.
This currently doesn't allow for comments to be added to the JSON. It is both linted as incorrect by the language server and not highlighted correctly.
The language server configured by the JSON language can take either `json` or `jsonc` as valid language ids.
Here is what the same file opened as a `.jsonc` looks like in this PR:

Add Support for JSONC

---

runtime/themes/tokyonight.toml

Before the fix, the color that the original (Neovim) tokyonight uses for Neovim's visual mode was used in Helix for highlighting the selected item in the picker. But for the highlighting of selected _text_ in Helix (corresponding to Neovim's visual mode), a much darker background was used. This made it very hard to pick out selected text, in particular in suboptimal lighting conditions.
I swapped the two colors, so that text selection now looks like in Neovim, while selected items in the picker are highlighted a bit less strongly. (But still easy to see because the whole line is highlighted.)

Fix selected text background in toykonight

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/blade/folds.scm
runtime/queries/blade/highlights.scm
runtime/queries/blade/injections.scm
runtime/queries/php-only/highlights.scm
runtime/queries/php-only/injections.scm
runtime/queries/php-only/tags.scm

Fixes #8562
Add [`blade`](https://github.com/EmranMR/tree-sitter-blade) tree-sitter config.
It needs [`php_only`](https://github.com/tree-sitter/tree-sitter-php/tree/master/php_only), which is separate from the regular `php` grammar.

Add blade support

---

book/src/generated/lang-support.md
runtime/queries/vala/textobjects.scm

This adds textobjects queries for vala, with support for functions, classes, comments, and parameters. Class support is partial - I couldn't find a way to support `@class.inside` with the vala grammar.

Add textobject queries for vala

---

Cargo.lock
Cargo.toml
helix-core/src/syntax.rs
runtime/queries/go/highlights.scm
runtime/queries/julia/highlights.scm
runtime/queries/pkl/highlights.scm
runtime/queries/pkl/injections.scm
runtime/queries/scss/highlights.scm
xtask/src/querycheck.rs

There were breaking changes to the `Language` type necessary because of loading WASM-based parsers: https://github.com/tree-sitter/tree-sitter/pull/2840. `Hash` is now implemented for `Language` though which simplifies our `Hash for LanguageLayer` impl

Bump tree-sitter to 0.22.2

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/supercollider/folds.scm
runtime/queries/supercollider/highlights.scm

Implements syntax highlighting for SuperCollider. See also #7368.

Add initial support for SuperCollider

---

book/src/generated/lang-support.md
languages.toml

Since docker compose LSP does not support for example `documentSymbol` requests, add yaml-language-server as a second LSP to provide missing capabilities.

Add yaml LSP for docker compose

---

helix-tui/src/backend/crossterm.rs

I have just found out that my recent Windows Terminal version supported rendering undercurl (see
https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-20-release ). However, looking at the source, terminfo is required for helix to emit the undercurl control code, which isn't available on Windows AFAIK.
This commit make helix respects the `editor.undercurl` option when there is no terminfo.
Tested on Windows Terminal Preview 1.20. Works without WSL.
Fixes #7065?

Respect undercurl config even with no terminfo

---

helix-term/src/lib.rs

Ignore `.pijul`, `.hg` and `.jj` as well as `.git`. This makes hx so much more usable with VCSes other than git!

Ignore more version control systems

---

helix-term/src/commands/typed.rs
helix-term/src/ui/mod.rs

This also adjusts `yank_diagnostic` to fail early if the register argument is invalid

add register completion for typed commands

---

helix-term/src/ui/statusline.rs

The current statusline implementation uses ad-hoc write callbacks to render statusline elements. This make statusline elements hard to work with, because we get no useful information about their output.
This PR refactors these elements to work more like widgets: each `render_*` function returns a `Spans`, which can be combined into a complete statusline. This has remained the responsibility of the `render` function.
This PR also separates the `render` function into two parts: `render_statusline` combines the aforementioned elements into one large `Spans` with given size constraints, while `render` blits it to a given `Surface` as it has done so previously. 
The rationale behind this is to allow post-processing the widget outputs and to make decisions based on them. 
For example, in the …

Refactor statusline elements to build `Spans`

---

languages.toml

Defines the correct comment-token for PKGBUILD files
fixes #9942

fix(languages): specify correct comment-token for PKGBUILD files

---

runtime/themes/dark_plus.toml

Now https://github.com/helix-editor/helix/pull/9780 is merged I have added the new theme keys.
Deprecated used to look like:
Now it looks like:
I can't find any code to show `unnecessary`, but the `dim` modifier works in general in the theme and does exactly as expected, it just dims the text slightly.
@kirawi Looks good to you?

Add new theme keys for LSP diagnostic tags for dark_plus

---

helix-term/src/ui/statusline.rs

The refactor in #9122 introduced a possible subtraction with overflow when the statusline is layed out so that the left or right sides are larger than the padding it would take to align the center area to the middle.
When the left or right areas are too large, we can evenly space the elements rather than trying to align the center area to the middle. This prevents possible underflows and makes sense visually - it's still easy to tell the areas apart at a glance.
Fixes #9948

Evenly space statusline areas when there isn't space to align middle

---

languages.toml

`rclone.conf` is actually an ini file, it is stated in the docs:
https://rclone.org/docs/#config-config-file
> The file format is basic [INI](https://en.wikipedia.org/wiki/INI_file#Format): Sections of text, led by a [section] header and followed by key=value entries on separate lines.
Following the discussion https://github.com/helix-editor/helix/pull/9653 relating to `.conf` files I have added it here as a glob so as the config file gets the correct highlighting and treesitter editing features.

Add rclone.conf as a glob to make it behave as an ini file

---

runtime/themes/gruvbox.toml

Gruvbox theme doesn't take advantage of specific bufferline colors and just uses defaults
Colors were chosen for the following reasons:
- bufferline
- fg - default text color
- bg - slightly darker than statusline, enough contrast to see tabs
- bufferline.active
- fg - contrast, hard and soft contrast will change this
- bg - arbitrary, just looked right of the available colors in the palette
- bufferline.background
- bg - match statusline

define bufferline colors for gruvbox

---

book/src/keymap.md
helix-term/src/commands.rs

Currently `goto_<next/prev>_diagnostic` does not work with `repeat_last_motion`, even though other `goto_xyz` motions under `[` or `]` respect `repeat_last_motion`.

Fix repeat last motion for goto next/prev diagnostic

---

helix-core/src/object.rs
helix-core/src/syntax.rs
helix-core/src/syntax/tree_cursor.rs
helix-term/src/commands.rs
helix-term/tests/test/movement.rs

Tree-sitter motions didn't work well for languages with injections such as Vue or JavaScript inside HTML since only the root layer's syntax-tree was considered. This change uses the range information for each injected language layer to find the appropriate syntax tree so that tree-sitter motions (A-p, A-i, A-o, A-n) work within injected content.
Here the tree-sitter motions work on the JavaScript syntax tree even though the root layer is HTML. Previously, A-o within the script tag would expand the selection to the whole script tag element.
Closes #2311

Cross injection layers in tree-sitter motions

---

book/src/configuration.md
book/src/keymap.md
book/src/themes.md
helix-core/src/doc_formatter.rs
helix-core/src/doc_formatter/test.rs
helix-core/src/graphemes.rs
helix-core/src/selection.rs
helix-core/src/text_annotations.rs
helix-term/src/commands.rs
helix-term/src/commands/lsp.rs
helix-term/src/keymap/default.rs
helix-term/src/ui/editor.rs
helix-view/src/document.rs
helix-view/src/editor.rs
helix-view/src/view.rs
runtime/themes/everforest_dark.toml
theme.toml

Closes #274
Closes #510
Closes #5340
This is a simple amp-like jumpmode that @the-mikedavis and I have been toying around with for a while. When discussing/starting to review #5340 we found the PR more complex than we would like for this feature (a diff above 1k loc). We were uncomfortable with how closely it follows hop and the subsequent debate about emulating the million other jumpmode plugins out there. There are many different approaches to jump commands, and we cannot maintain them all in core. Instead, we want to pick a single opinionated choice that we feel fits well with the rest of the editor.
While testing that PR we made the following observations:
* character based jumps (which require a character before tying a label) don't really hold their water, you can use `f` for simple …

Add a simple amp-like jump command

---

runtime/themes/catppuccin_mocha.toml

Preview of `catppuccin_mocha` displaying `helix-term/src/main.rs`:

Use "rosewater" for the jump label color in catppuccin themes

---

book/src/configuration.md
helix-core/src/chars.rs
helix-term/src/ui/document.rs
helix-tui/src/widgets/reflow.rs
helix-view/src/editor.rs

The goal of this PR is to support the rendering of narrow no-break spaces as asked in #6640.
Note that I'm not proficient in Rust, but since it looked simple, I gave it a try by looking at what have been done for regular `nbsp`.
The tests passes and the feature works using `cargo run`.
I don't know what's better between having a dedicated `editor.whitespace.render` option for `nnbsp` or including it in the existing `nbsp` parameter.
Currently, the new config parameters would look like this:
```toml
[editor.whitespace.render]
space = "all"
nbsp = "all"
nnbsp = "all"
tab = "all"
newline = "none"
[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"
```

Add narrow no-break space support

---

helix-term/src/ui/prompt.rs

This reverts commit 0dc67ff8852ce99d40ad4464062ebe212b0b03a1 / #9828.
See the post-merge discussion in #9828. The old behavior was less surprising and we have other ways to abort from a prompt, so let's revert the behavior change.

Revert allowing backspace to close empty prompts

---

runtime/themes/gruvbox.toml

`gruvbox`:
`gruvbox-dark-hard`:
`gruvbox-dark-soft`
`gruvbox-light`:
`gruvbox-light-hard`:
`gruvbox-light-soft`:

feat(themes): add `jump-label` for gruvbox themes

---

helix-term/src/handlers.rs
helix-term/src/lib.rs

Newer rustc versions warn about these unused exports. On rustc 1.76.0 for example:
```
warning: unused import: `helix_view::handlers::lsp::SignatureHelpInvoked`
--> helix-term/src/handlers.rs:12:9
|
12 | pub use helix_view::handlers::lsp::SignatureHelpInvoked;
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `keymap::macros::*`
--> helix-term/src/lib.rs:23:9
|
23 | pub use keymap::macros::*;
|         ^^^^^^^^^^^^^^^^^
warning: `helix-term` (lib) generated 2 warnings (run `cargo fix --lib -p helix-term` to apply 2 suggestions)
```

Fix rustc warnings about unused 'pub use's

---

runtime/queries/comment/highlights.scm

Since https://github.com/helix-editor/helix/pull/9253 landed, `(` `)` and `:` are always highlighted in comments.
`(` `)` highlighting was resolved in https://github.com/helix-editor/helix/pull/9800, this PR removes `:` highlighting.
I imagine there are cases where we would like `:` to be highlighted, e.g. `TODO:`, but I have no idea what I'm doing, so in the meantime I think highlighting nothing is better than highlighting everything, especially when it comes to themes where it really stands out (in this case, noctis)

fix: don't highlight colons (:) in comments

---

runtime/themes/kanagawa.toml

I added the `ui.virtual.jump-label` to the Kanagawa theme and made some formatting.
Please let me know if I overstepped while formatting the file.
I got the colors from the [official Kanagawa repository](https://github.com/rebelot/kanagawa.nvim/blob/bfa818c7bf6259152f1d89cf9fbfba3554c93695/extras/kanagawa-theme.el#L394)

Add jump-label to Kanagawa theme + format

---

runtime/queries/ruby/injections.scm

This change adds 2 new injections for Ruby heredocs, ERB and GraphQL:
(Realistically you probably wouldn't write a GraphQL query in a [ViewComponent](https://viewcomponent.org/) but this fits in one screenshot)

Add injections for GraphQL and ERB in Ruby

---

languages.toml

The revision I chose here is simply the latest release on the repo:
https://github.com/tree-sitter-grammars/tree-sitter-markdown/releases/tag/v0.2.3
Closes #8821

chore: update tree-sitter-markdown

---

runtime/themes/material_darker.toml
runtime/themes/material_deep_ocean.toml
runtime/themes/material_oceanic.toml
runtime/themes/material_palenight.toml

The cursorline on material theme is white. The theme is not bad but this makes it clearly unusable :smile: 
I'm trying to make that a bit more beautiful with this PR (I took the active color from some [nvim color scheme](https://github.com/marko-cerovac/material.nvim/blob/main/lua/material/colors/init.lua) of material)

fix: cursor line on material themes

---

runtime/themes/jetbrains_dark.toml

Hey, I have attempted to recreate the default JetBrains dark theme in Helix as closely as possible.

Add JetBrains default dark theme

---

languages.toml

`ols` recently gained the ability to use a global `ols.json` config instead of/in addition to local `ols.json` configs. However, a global config cannot properly work on its own in Helix, as Helix is unable to create the workspace it needs without a local config.
But, most Odin projects will have a `main.odin` file at the route of their sources, so also detecting this as a root could be a workaround for most Odin projects that don't want/need a local config.

Add main.odin to Odin roots

---

contrib/Helix.appdata.xml

The `<description>` tag shouldn't be translated, but instead the individual paragraphs. This is kind of weird imo, but a spec is a spec i guess. 
The `<developer>` tag is required. I just put "The Helix Community" in there, but maybe just put @archseer by name?
It turns out, the `<requires>` tag actually means that the app can't even be installed without that control. What this should be is `<recommends>`.

Make Helix.appdata.xml spec-compliant

---

runtime/themes/nightfox.toml

Add `jump-label` style for nightfox theme, _inspired_ by their [integration with hop.nvim](https://github.com/EdenEast/nightfox.nvim/blob/main/lua/nightfox/group/modules/hop.lua). The first key styling (`HopNextKey1`)  is applied to Helix's `jump-label` fully, since there isn't per key styling support.
Current:
Updated:

feat(themes): add `jump-label` style for nightfox

---

runtime/themes/solarized_dark.toml
runtime/themes/solarized_light.toml

I don't know if there are any recommendations, but red works for me - stands out, and I'm an exclusive solarized-dark user.

chore: add "ui.virtual.jump-label" to solarized colorschemes

---

runtime/themes/cyan_light.toml

Add Jump Label styles to Cyan Light theme

Add jump-label to Cyan Light theme

---

languages.toml

GitHub recognizes `.mkdn` as markdown files. Add `.mkdn` as a valid file type for Markdown.

feat(languages): .mkdn as markdown extension

---

helix-term/tests/test/auto_indent.rs
helix-term/tests/test/auto_pairs.rs
helix-term/tests/test/commands.rs
helix-term/tests/test/commands/movement.rs
helix-term/tests/test/commands/write.rs
helix-term/tests/test/helpers.rs
helix-term/tests/test/languages/go.rs
helix-term/tests/test/languages/yaml.rs
helix-term/tests/test/movement.rs
helix-term/tests/test/splits.rs
helix-vcs/src/lib.rs

Prior to this change, every integration test which wanted its line endings to be handled transparently across platforms, i.e. test with the same input that has its platform's line feed characters, converting the line endings was up to each individual test by calling the `platform_line` helper function. This significantly increases the amount of boilerplate one has to copy between all the tests.
However, there are some test cases that need to exert strict control over the exact input text without being manipulated behind the scenes by the test framework.
So, with this change, the line feed conversions are factored into the `TestCase` struct. By default, line endings of the input text are converted to the platform's native line feed ending, but one can explicitly specify in their test case …

Factor out line ending handling in integration tests

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/bitbake/highlights.scm
runtime/queries/bitbake/injections.scm

- integrate bitbake treesitter from https://github.com/tree-sitter-grammars/tree-sitter-bitbake
- highlights.scm and injections.scm are now nearly written from scratch and small, taking advantage of injections as bitbake is mostly based on bash and python languages. tested OK with treesitter examples https://github.com/tree-sitter-grammars/tree-sitter-bitbake/tree/master/examples
- bitbake-language-server integration tested with https://github.com/Freed-Wu/bitbake-language-server.git

add initial support for bitbake language

---

runtime/themes/onelight.toml

feat(themes): add `jump-label` for oneLight theme

---

runtime/queries/gleam/injections.scm

Noticed there wasn't an `injections.scm` for Gleam yet so I added one.

Adds query injection for comments in Gleam

---

base16_theme.toml
runtime/themes/base16_default_dark.toml
runtime/themes/base16_default_light.toml
runtime/themes/base16_terminal.toml
runtime/themes/base16_transparent.toml

To respect the minimalistic look of the theme and inherit the link styling from the Web platform, I kept it simple by making labels underlined.

Add jump-label styling for base16 themes

---

runtime/themes/kanagawa.toml

I'm using `kanagawa` style and sometimes its pretty difficult to recognize selections:
Here is an example.
No selection:
Selected:
This PR adds dimming to make it a bit more obvious:

Dim primary selection in kanagawa

---

runtime/queries/yaml/injections.scm

Adds injection support to yaml for [buildkite command steps](https://buildkite.com/docs/pipelines/command-step#command-step-attributes).

Add Buildkite command/commands support to yaml injections

---

languages.toml

`LLVM v18.0.0` changed the name here: llvm/llvm-project#69264
Current users of `lldb-vscode` not able to upgrade will have to create a symlink so that `lldb-dap` links to `lldb-vscode`.
BREAKING CHANGE: debugger looks for `lldb-dap` rather than `lldb-vscode`
closes: #9964

refactor(languages)!: `lldb-vscode` -> `lldb-dap`

---

runtime/themes/tokyonight.toml

Does what it says on the tin
tokyonight:
tokyonight_day:
tokyonight_moon:
tokyonight_storm:

add support for jump labels in tokyonight themes

---

book/src/keymap.md
helix-term/src/commands.rs
helix-view/src/view.rs

These are a few patches I've collected while using Helix. Let the world finally see them.
commit 94db1511f8f7789fe7eed378d1e0407aff3bcca2 : docs: mention `<space>g` changed file picker. This was missed in the #5645
These two are personal preferences, but I think they're fair:
commit a4b5b4c16bbfc65efce7cddcd4e0c36fb0e2d4b0 : picker(jumplist): show newest options on top instead of bottom
~commit ef13bf544daec50034009291bc61030831d43ee7 : picker(global-search): append line number to found options~
You can reject them all, select only docs commit, or do whatever you want :)

show newest options in jumplist picker first, fix docs

---

helix-view/src/tree.rs

This patch merges the last child of a container node to the parent. This avoids the bug where uneven spaced Views would be created. To reproduce:
1. `vsplit`
2. `split`
3. `quit`
4. `vsplit`
With this patch the bug cannot be seen anymore.

Bug fix: Reconfigure tree properly after closing view.

---

languages.toml

Add block-comment-tokens property for fsharp language to utilize the recent block comments feature. F# block comments are documented [here](https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-comments)

Add fsharp block comment tokens to languages.toml

---

languages.toml
runtime/queries/templ/highlights.scm

Update the templ grammar. Fixes a lot of bugs, new syntax support.
Most of the highlight syntax can be removed because it's inherited from the go highlights.

languages: update templ

---

languages.toml

Hi!
Sets `starlark` language for `Tiltfile`
https://docs.tilt.dev/api

feat(languages): Tiltfile as starlark language

---

helix-view/src/editor.rs

Without a serializer, we drop the custom alphabet when making config modifications like with `:set`. For example before this commit, `:set mouse false` would reset a custom alphabet to the default.
Closes #10153

Add a serializer for the jump alphabet config option

---

helix-term/src/commands.rs

Using an enum makes the intent more clearer as the names of the enum variants indicate the decision more better than booleans

Use an enum to represent yank decision during deletion of a selection

---

runtime/queries/python/highlights.scm

Fixes inconsistency in Python highlighting

Remove duplicate keyword highlight for Python 'and'

---

helix-term/src/ui/editor.rs

Previously unnecessary/deprecated diagnostic tags replaced the highlight for the severity of a diagnostic. This could cause either the severity or unnecessary/deprecated scopes to disappear when diagnostic ranges overlapped though. Plus the severity highlight can be interesting in addition to the unnecessary/deprecated highlight.
So this change separates the unnecessary and deprecated highlights from the severity highlights, so each is merged separately and when the highlights combine when overlapped.
Fixes https://github.com/helix-editor/helix/issues/10080

Merge unnecessary/deprecated diagnostic highlights separately

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/koka/highlights.scm
runtime/queries/koka/indents.scm

This pull request adds support for Koka's language server, and updates the grammar. The language server is built into the `koka` binary; no additional steps are required to get it working. Using the language server over stdin/stdout is supported starting in v3.1.0.

Add koka language server and update grammar

---

helix-lsp/src/lib.rs

This PR attempts to fix #9624.
While testing helix-gpt out, helix crashed many times for me. I decided to take a shot at fixing this issue myself, with a simple check inside the Transaction change edit's closure. When the range is invalid, I simply discarded the edit and logged it.
As noted in the issue, this is mainly a problem inside helix-gpt itself, but a crash is undesirable.

Fix crash on LSP text edits with invalid ranges

---

helix-view/src/document.rs

One language server being uninitialized or exited should not prevent the other(s) from being notified of didSave.
Fixes #10162

Handle partial failure when sending textDocument/didSave

---

languages.toml

Following intruction to enable it
Install <code>@angular/language-server</code> with npm
```
npm i -g @angular/language-server
```
Install <code>@angular/language-service</code> as dev dependencies in project
```
npm i -D @angular/language-service
```
Add <code>angular</code> to language-servers html and typescript in languages.toml
```TOML
[[language]]
name ="html"
language-servers = ["angular","vscode-html-language-server"]
[[language]]
name = "typescript"
language-servers = ["angular","typescript-language-server"]
```
Auto completion and error checking
Goto reference and goto definition
Related to #4861

Add angular language server

---

book/src/generated/lang-support.md
languages.toml
runtime/queries/adl/highlights.scm
runtime/queries/adl/indents.scm
runtime/queries/adl/textobjects.scm

Created a tree-sitter grammar for [ADL](https://github.com/adl-lang/adl) to get syntax highlighting (and other goodness) in Helix.

feat: Add ADL language support

---

helix-lsp/src/lib.rs

closes  #9799
was originally not able to pin this down since the provided doc file didn't contain any information. But this was very easy to reproduce with python. Turns out to be a simple off by one by error that slipped trough since almost every fully featured lsp only sends full edits.

fix off by one error for completion-replace option

---

helix-term/src/ui/editor.rs

fix mouse right click selection
